DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Alter_PM_Schema`(IN GT_DB VARCHAR(100))
BEGIN
SELECT SUBSTRING(gt_strtok(GT_DB,3,'_'),7,2) INTO @DATE_DY;
IF @DATE_DY LIKE '01' THEN 	
	INSERT INTO gt_covmo.dim_pm_ericsson_umts (`INDEX`, VENDOR_KEY, PM_COUNTER_NAME, DATA_TYPE, COUNTER_TYPE) 
	SELECT A.`INDEX`, A.VENDOR_KEY, A.PM_COUNTER_NAME, A.DATA_TYPE, A.COUNTER_TYPE
	FROM gt_covmo.dim_pm_ericsson_umts_growing AS A
	LEFT JOIN gt_covmo.dim_pm_ericsson_umts AS B ON (B.PM_COUNTER_NAME = A.PM_COUNTER_NAME)
	WHERE B.PM_COUNTER_NAME IS NULL;
    
	INSERT INTO gt_covmo.dim_pm_ericsson_lte (`INDEX`, VENDOR_KEY, PM_COUNTER_NAME, DATA_TYPE, COUNTER_TYPE) 
	SELECT A.`INDEX`, A.VENDOR_KEY, A.PM_COUNTER_NAME, A.DATA_TYPE, A.COUNTER_TYPE
	FROM gt_covmo.dim_pm_ericsson_lte_growing AS A
	LEFT JOIN gt_covmo.dim_pm_ericsson_lte AS B ON (B.PM_COUNTER_NAME = A.PM_COUNTER_NAME)
	WHERE B.PM_COUNTER_NAME IS NULL;
END IF;
END$$
DELIMITER ;
