DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_CreateDB_NT_Schema_LTE`(IN GT_DB VARCHAR(100))
BEGIN
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_pu_current`
		(           
		`PU_ID` MEDIUMINT(9) DEFAULT NULL,
		`PU_NAME` VARCHAR(50) DEFAULT NULL,
		`MCC` VARCHAR(3) NOT NULL,
		`MNC` VARCHAR(3) NOT NULL,
		`TECH_MASK` TINYINT(4) DEFAULT NULL,
		`VEDNOR` VARCHAR(30) DEFAULT NULL,
		`SITE_CNT` SMALLINT(6) DEFAULT NULL,
		`CELL_CNT` SMALLINT(6) DEFAULT NULL
		) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1;
		');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_cell_lte`
		(           
		`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
		`ENODEB_NAME` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
		`ENODEB_LOC_ID` VARCHAR(20) CHARACTER SET utf8  DEFAULT NULL,
		`ENODEB_NE_ID` VARCHAR(20)  CHARACTER SET utf8  DEFAULT NULL,
		`ENODEB_OSS_NODE_ID` INT(20) DEFAULT NULL,
		`CELL_ID` MEDIUMINT(9) DEFAULT NULL,
		`cell_name` varchar(125) CHARACTER SET utf8 COLLATE utf8_swedish_ci  DEFAULT NULL,
		`CELL_LOC_ID` VARCHAR(20) CHARACTER SET utf8  DEFAULT NULL,
		`CELL_NE_ID` VARCHAR(20) CHARACTER SET utf8  DEFAULT NULL,
		`CELL_OSS_NODE_ID` INT(20) DEFAULT NULL,  
		`EUTRABAND` MEDIUMINT(9) DEFAULT NULL,
		`PCI` SMALLINT(6) DEFAULT NULL,
		`BWCHANNEL` DECIMAL(6,3) DEFAULT NULL,
		`DL_EARFCN` MEDIUMINT(9) DEFAULT NULL,
		`UL_EARFCN` MEDIUMINT(9) DEFAULT NULL,
		`ENODEB_TYPE` VARCHAR(50)  DEFAULT NULL,
		`ENODEB_VENDOR` VARCHAR(50)  DEFAULT NULL,
		`INDOOR` TINYINT(4) DEFAULT NULL,
		`IP` VARCHAR(100) DEFAULT NULL,
		`CLUSTER_NAME_REGION` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
		`CLUSTER_NAME_SUB_REGION` VARCHAR(100)  CHARACTER SET utf8  COLLATE utf8_swedish_ci DEFAULT NULL,
		`CLUSTER_NAME_STRUCTURE_TYPE` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
		`ACT_START` DATE DEFAULT NULL,
		`ACT_END` DATE DEFAULT NULL,
		`PLAN_START` DATE DEFAULT NULL,
		`PLAN_END` DATE DEFAULT NULL,
		`ACT_STATE` VARCHAR(50) DEFAULT NULL,
		`ENODEB_MODEL` VARCHAR(100) DEFAULT NULL,
		`CLUSTER_NAME_ZONE` VARCHAR(100)  CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
		`CELL_RADIUS` MEDIUMINT(9) DEFAULT NULL,
		`AMDINSTATE_LOCKED` TINYINT(4) DEFAULT NULL,
		`OPERSTATE_ENABLE` TINYINT(4) DEFAULT NULL,
		`REGION_ID` MEDIUMINT(9) DEFAULT NULL,
		`SUB_REGION_ID` MEDIUMINT(9) DEFAULT NULL,
		`NBR_DISTANCE_4G_CM` DOUBLE  DEFAULT NULL, 
		`NBR_DISTANCE_4G_VORONOI` DOUBLE  DEFAULT NULL,
		`PU_ID` MEDIUMINT(9) DEFAULT NULL,
		`SITE_DENSITY_TYPE` tinyint(4) DEFAULT NULL,
		`RACH_ROOT_SEQUENCE` MEDIUMINT(9) DEFAULT NULL, 
		`SLA` CHAR(1) DEFAULT NULL,
		`VIP` CHAR(1) DEFAULT NULL,
		`FLAG` SMALLINT(6) DEFAULT ''0'',
		SERVING_AREA VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
		KEY `NT_CELL_LTE_IDX1` (`ENODEB_ID`,`CELL_ID`),
		KEY `ENODEB_ID_IDX` (`ENODEB_ID`),
		KEY `CELL_OSS_NODE_ID_IDX` (`CELL_OSS_NODE_ID`)
		) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_cell_current_lte`
		(           
		`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
		`ENODEB_NAME` VARCHAR(50) CHARACTER SET utf8  COLLATE utf8_swedish_ci  DEFAULT NULL,
		`ENODEB_LOC_ID` VARCHAR(20) CHARACTER SET utf8  DEFAULT NULL,
		`ENODEB_NE_ID` VARCHAR(20) CHARACTER SET utf8   DEFAULT NULL,
		`ENODEB_OSS_NODE_ID` INT(20) DEFAULT NULL,
		`CELL_ID` MEDIUMINT(9) DEFAULT NULL,
		`cell_name` varchar(125) CHARACTER SET utf8  COLLATE utf8_swedish_ci   DEFAULT NULL,
		`CELL_LOC_ID` VARCHAR(20) CHARACTER SET utf8  DEFAULT NULL,
		`CELL_NE_ID` VARCHAR(20) CHARACTER SET utf8  DEFAULT NULL,
		`CELL_OSS_NODE_ID` INT(20) DEFAULT NULL,  
		`EUTRABAND` MEDIUMINT(9) DEFAULT NULL,
		`PCI` SMALLINT(6) DEFAULT NULL,
		`BWCHANNEL` DECIMAL(6,3) DEFAULT NULL,
		`DL_EARFCN` MEDIUMINT(9) DEFAULT NULL,
		`UL_EARFCN` MEDIUMINT(9) DEFAULT NULL,
		`ENODEB_TYPE` VARCHAR(50)  DEFAULT NULL,
		`ENODEB_VENDOR` VARCHAR(50)  DEFAULT NULL,
		`INDOOR` TINYINT(4) DEFAULT NULL,
		`IP` VARCHAR(100) DEFAULT NULL,
		`CLUSTER_NAME_REGION` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
		`CLUSTER_NAME_SUB_REGION` VARCHAR(100)  CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
		`CLUSTER_NAME_STRUCTURE_TYPE` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
		`ACT_START` DATE DEFAULT NULL,
		`ACT_END` DATE DEFAULT NULL,
		`PLAN_START` DATE DEFAULT NULL,
		`PLAN_END` DATE DEFAULT NULL,
		`ACT_STATE` VARCHAR(50) DEFAULT NULL,
		`ENODEB_MODEL` VARCHAR(100) DEFAULT NULL,
		`CLUSTER_NAME_ZONE` VARCHAR(100)  CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
		`CELL_RADIUS` MEDIUMINT(9) DEFAULT NULL,
		`AMDINSTATE_LOCKED` TINYINT(4) DEFAULT NULL,
		`OPERSTATE_ENABLE` TINYINT(4) DEFAULT NULL,
		`REGION_ID` MEDIUMINT(9) DEFAULT NULL,
		`SUB_REGION_ID` MEDIUMINT(9) DEFAULT NULL,
		`NBR_DISTANCE_4G_CM` DOUBLE  DEFAULT NULL, 
		`NBR_DISTANCE_4G_VORONOI` DOUBLE  DEFAULT NULL,
		`PU_ID` MEDIUMINT(9) DEFAULT NULL,
		`SITE_DENSITY_TYPE` tinyint(4) DEFAULT NULL,
		`RACH_ROOT_SEQUENCE` MEDIUMINT(9) DEFAULT NULL,
		`SLA` CHAR(1) DEFAULT NULL,
		`VIP` CHAR(1) DEFAULT NULL,
		`FLAG` SMALLINT(6) DEFAULT ''0'',
		SERVING_AREA VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
		KEY `NT_CELL_LTE_IDX1` (`ENODEB_ID`,`CELL_ID`),
		KEY `ENODEB_ID_IDX` (`ENODEB_ID`),
		KEY `CELL_OSS_NODE_ID_IDX` (`CELL_OSS_NODE_ID`)
		) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_tac_cell_lte`
		(          
		`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,      
		`CELL_ID` MEDIUMINT(9) DEFAULT NULL,
		`TAC` VARCHAR(20) DEFAULT NULL
		) ENGINE=MYISAM DEFAULT CHARSET=UTF8 DELAY_KEY_WRITE=1');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_tac_cell_current_lte`
		(   
		`ENODEB_ID`MEDIUMINT(9) DEFAULT NULL,     
		`CELL_ID` MEDIUMINT(9) DEFAULT NULL,
		`TAC` VARCHAR(20) DEFAULT NULL
		) ENGINE=MYISAM DEFAULT CHARSET=UTF8 DELAY_KEY_WRITE=1');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_antenna_lte`
		(     
		`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
		`CELL_ID` TINYINT(4) DEFAULT NULL,
		`LONGITUDE` DOUBLE DEFAULT NULL,
		`LATITUDE` DOUBLE DEFAULT NULL,
		`AZIMUTH` SMALLINT(6) DEFAULT NULL,
		`ANTENNA_TYPE` TINYINT(4) DEFAULT NULL,
		`REPEATER` TINYINT(4) DEFAULT NULL,
		`REPEATER_TYPE` VARCHAR(20) DEFAULT NULL,
		`REPEATER_TA_DELAY` MEDIUMINT(9) DEFAULT NULL,    
		`ANTENNA_MODEL` VARCHAR(50) CHARACTER SET utf8  DEFAULT NULL,
		`ANTENNA_HEIGHT` DOUBLE DEFAULT NULL,
		`ANTENNA_GAIN` DOUBLE DEFAULT NULL,
		`BEAM_WIDTH_HORIZONTAL` DOUBLE DEFAULT NULL,
		`BEAM_WIDTH_VERTICAL` DOUBLE DEFAULT NULL,
		`DOWN_TILT_MECHANICAL` DOUBLE DEFAULT NULL,
		`DOWN_TILT_ELECTRICAL` DOUBLE DEFAULT NULL,
		`FEEDER_ATTEN` DOUBLE DEFAULT NULL,
		`REFERENCE_SIGNAL_POWER` DOUBLE DEFAULT NULL,
		`ELEVATION` DOUBLE DEFAULT NULL,
		`INDOOR_TYPE` TINYINT(4) DEFAULT NULL,
		`ANTENNA_ID` TINYINT(4) DEFAULT ''1'',
		`PATHLOSS_DISTANCE` float DEFAULT NULL,
		`ANTENNA_RADIUS` float DEFAULT NULL,
		`CLOSED_RADIUS` float DEFAULT NULL,
		`FLAG` SMALLINT(6) DEFAULT ''0'',
		KEY `ID_KEY` (`ENODEB_ID`,`CELL_ID`)
		) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_antenna_current_lte`
		(
		`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
		`CELL_ID` TINYINT(4) DEFAULT NULL,
		`LONGITUDE` DOUBLE DEFAULT NULL,
		`LATITUDE` DOUBLE DEFAULT NULL,
		`AZIMUTH` SMALLINT(6) DEFAULT NULL,
		`ANTENNA_TYPE` TINYINT(4) DEFAULT NULL,
		`REPEATER` TINYINT(4) DEFAULT NULL,
		`REPEATER_TYPE` VARCHAR(20) DEFAULT NULL,
		`REPEATER_TA_DELAY` MEDIUMINT(9) DEFAULT NULL,    
		`ANTENNA_MODEL` VARCHAR(50) CHARACTER SET utf8  DEFAULT NULL,
		`ANTENNA_HEIGHT` DOUBLE DEFAULT NULL,
		`ANTENNA_GAIN` DOUBLE DEFAULT NULL,
		`BEAM_WIDTH_HORIZONTAL` DOUBLE DEFAULT NULL,
		`BEAM_WIDTH_VERTICAL` DOUBLE DEFAULT NULL,
		`DOWN_TILT_MECHANICAL` DOUBLE DEFAULT NULL,
		`DOWN_TILT_ELECTRICAL` DOUBLE DEFAULT NULL,
		`FEEDER_ATTEN` DOUBLE DEFAULT NULL,
		`REFERENCE_SIGNAL_POWER` DOUBLE DEFAULT NULL,
		`ELEVATION` DOUBLE DEFAULT NULL,
		`INDOOR_TYPE` TINYINT(4) DEFAULT NULL,
		`ANTENNA_ID` TINYINT(4) DEFAULT ''1'',
		`PATHLOSS_DISTANCE` float DEFAULT NULL,
		`ANTENNA_RADIUS` float DEFAULT NULL,
		`CLOSED_RADIUS` float DEFAULT NULL,
		`FLAG` SMALLINT(6) DEFAULT ''0'',
		KEY `NT_ANTENNA_CURRENT_LTE_IDX1` (`ENODEB_ID`,`CELL_ID`)
		) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_mme_lte`
		(           
		`MME_ID` BIGINT(20) DEFAULT NULL,
		`MME_NAME` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
		`MME_NE_ID` VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL,
		`S_GW_ID` MEDIUMINT(9) DEFAULT NULL,
		`S_GW_NAME` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
		`USER_LABEL` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL,
		`MCC` VARCHAR(3) DEFAULT NULL,
		`MNC` VARCHAR(2) DEFAULT NULL,
		`VENDOR` VARCHAR(50) DEFAULT NULL
		) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_mme_current_lte`
		(           
		`MME_ID` BIGINT(20) DEFAULT NULL,
		`MME_NAME` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
		`MME_NE_ID` VARCHAR(20) CHARACTER SET utf8   DEFAULT NULL,
		`S_GW_ID` MEDIUMINT(9) DEFAULT NULL,
		`S_GW_NAME` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
		`USER_LABEL` VARCHAR(50) CHARACTER SET utf8  DEFAULT NULL,
		`MCC` VARCHAR(3) DEFAULT NULL,
		`MNC` VARCHAR(2) DEFAULT NULL,
		`VENDOR` VARCHAR(50) DEFAULT NULL
		) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_nbr_4_2_lte`
		(         
		`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
		`CELL_ID` MEDIUMINT(9) DEFAULT NULL,
		`NBR_BSC_ID` INT(11) DEFAULT NULL,
		`NBR_CELL_ID` MEDIUMINT(9) DEFAULT NULL,
		`PRIORITY` TINYINT(4) DEFAULT NULL,
		`ARFCN` MEDIUMINT(9) DEFAULT NULL,
		`BCC` MEDIUMINT(9) DEFAULT NULL,
		`NCC` MEDIUMINT(9) DEFAULT NULL,
		`LAC` MEDIUMINT(9) DEFAULT NULL
		) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_nbr_4_2_current_lte`
		(
		`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
		`CELL_ID` MEDIUMINT(9) DEFAULT NULL,
		`NBR_BSC_ID` INT(11) DEFAULT NULL,
		`NBR_CELL_ID` MEDIUMINT(9) DEFAULT NULL,
		`PRIORITY` TINYINT(4) DEFAULT NULL,
		`ARFCN` MEDIUMINT(9) DEFAULT NULL,
		`BCC` MEDIUMINT(9) DEFAULT NULL,
		`NCC` MEDIUMINT(9) DEFAULT NULL,
		`LAC` MEDIUMINT(9) DEFAULT NULL
		) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_nbr_4_3_lte`
		(          
		`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
		`CELL_ID` MEDIUMINT(9) DEFAULT NULL,
		`NBR_RNC_ID` INT(11) DEFAULT NULL,
		`NBR_CELL_ID` MEDIUMINT(9) DEFAULT NULL,
		`PRIORITY` TINYINT(4) DEFAULT NULL,
		`PSC` SMALLINT(6) DEFAULT NULL
		) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_nbr_4_3_current_lte`
		(
		`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
		`CELL_ID` MEDIUMINT(9) DEFAULT NULL,
		`NBR_RNC_ID` INT(11) DEFAULT NULL,
		`NBR_CELL_ID` MEDIUMINT(9) DEFAULT NULL,
		`PRIORITY` TINYINT(4) DEFAULT NULL,
		`PSC` SMALLINT(6) DEFAULT NULL
		) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_nbr_4_4_lte`
		(     
		`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
		`CELL_ID` MEDIUMINT(9) DEFAULT NULL,
		`NBR_ENODEB_ID` VARCHAR(20)  DEFAULT NULL,
		`NBR_CELL_ID` MEDIUMINT(9) DEFAULT NULL,
		`PRIORITY` TINYINT(4) DEFAULT NULL,
		`NBR_TYPE` VARCHAR(50) CHARACTER SET utf8  DEFAULT NULL,
		`NBR_DISTANCE` DOUBLE DEFAULT NULL,
		`NBR_ANGLE` MEDIUMINT(9) DEFAULT NULL,
		`NBR_AZIMUTH_ANGLE` MEDIUMINT(9) DEFAULT NULL,
		KEY `NT_NBR_4_4_LTE_IDX1` (`ENODEB_ID`, `CELL_ID`, `NBR_ENODEB_ID`, `NBR_CELL_ID`),
		KEY `NT_NBR_4_4_LTE_IDX2` (`NBR_ENODEB_ID`,`NBR_CELL_ID`)
		) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_nbr_4_4_current_lte`
		(   
		`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
		`CELL_ID` MEDIUMINT(9) DEFAULT NULL,
		`NBR_ENODEB_ID` VARCHAR(20) DEFAULT NULL,
		`NBR_CELL_ID` MEDIUMINT(9) DEFAULT NULL,
		`PRIORITY` TINYINT(4) DEFAULT NULL,
		`NBR_TYPE` VARCHAR(50) CHARACTER SET utf8   DEFAULT NULL,
		`NBR_DISTANCE` DOUBLE DEFAULT NULL,
		`NBR_ANGLE` MEDIUMINT(9) DEFAULT NULL,
		`NBR_AZIMUTH_ANGLE` MEDIUMINT(9) DEFAULT NULL,
		KEY `NT_NBR_4_4_CURRENT_LTE_IDX1` (`ENODEB_ID`,`CELL_ID`, `NBR_ENODEB_ID`, `NBR_CELL_ID`),
		KEY `NT_NBR_4_4_CURRENT_LTE_IDX2` (`NBR_ENODEB_ID`,`NBR_CELL_ID`)
		) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_neighbor_voronoi_lte`
		(   
		`ENODEB_ID` VARCHAR(20) DEFAULT NULL,
		`NBR_ENODEB_ID` VARCHAR(20) DEFAULT NULL,
		`ANGLE` DOUBLE DEFAULT NULL,
		`DISTANCE` DOUBLE DEFAULT NULL,
		`DL_EARFCN` MEDIUMINT(9) DEFAULT NULL,
		`INDOOR_TYPE` TINYINT(4) DEFAULT NULL,
		`SITEDENSITY_RANGE` INT(11) DEFAULT NULL,
		`REFINE_DISTANCE` FLOAT DEFAULT NULL,
		KEY `ENODEB_ID_IDX` (`ENODEB_ID`,`NBR_ENODEB_ID`)        
		) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`RULE_NT_NBR_ENODEB_LTE`
		(   
		`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
		`BL_MCC_TRAGET` VARCHAR(3) DEFAULT NULL,
		`BL_MNC_TARGET` VARCHAR(3) DEFAULT NULL,
		`BL_ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
		`BL_TYPE` VARCHAR(20) DEFAULT NULL,
		KEY `NT_NBR_LTE_BLACKLIST_IDX1` (ENODEB_ID,`BL_ENODEB_ID`)
		) ENGINE=MYISAM DEFAULT CHARSET=UTF8 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`RULE_NT_NBR_CELL_PCI_LTE`
		(   
		`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
		`CELL_ID` MEDIUMINT(9) DEFAULT NULL,
		`BL_FREQ_EARFCN` MEDIUMINT(9) DEFAULT NULL,
		`BL_PCI` SMALLINT(6) DEFAULT NULL,
		KEY `NT_NBR_CELL_BLACKLIST_PCI_IDX1` (ENODEB_ID,`CELL_ID`)
		) ENGINE=MYISAM DEFAULT CHARSET=UTF8 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`opt_pci_result` (
		  `pu_id` MEDIUMINT(9) DEFAULT NULL,
		  `enodeb_id` INT(11) NOT NULL,
		  `cell_id` INT(11) NOT NULL,
		  `cell_name` varchar(125) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
		  `longitude` DOUBLE NOT NULL,
		  `latitude` DOUBLE NOT NULL,
		  `pci` INT(11) NOT NULL,
		  `nbr_pu_id` MEDIUMINT(9) DEFAULT NULL,
		  `nbr_enodeb_id` INT(11) NOT NULL,
		  `nbr_cell_id` INT(11) NOT NULL,
		  `nbr_cell_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
		  `distance` DOUBLE DEFAULT NULL,
		  `depth` MEDIUMINT(9) DEFAULT NULL,
		  `depth_1_enodeb` INT(11) DEFAULT NULL,
		  `depth_1_cell` INT(11) DEFAULT NULL,
		  `depth_2_enodeb` INT(11) DEFAULT NULL,
		  `depth_2_cell` INT(11) DEFAULT NULL,
		  UNIQUE KEY `enodeb_id` (`enodeb_id`,`cell_id`,`nbr_enodeb_id`,`nbr_cell_id`)
		) ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`opt_pci_suggest` (
		  `pu_id` MEDIUMINT(9) DEFAULT NULL,
		  `enodeb_id` INT(11) DEFAULT NULL,
		  `cell_id` INT(11) DEFAULT NULL,
		  `cell_name` varchar(125) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
		  `nbr_pu_id` MEDIUMINT(9) DEFAULT NULL,
		  `nbr_enodeb_id` INT(11) DEFAULT NULL,
		  `nbr_cell_id` INT(11) DEFAULT NULL,
		  `nbr_cell_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
		  `pci_suggest` INT(11) DEFAULT NULL,
		  `distance` DOUBLE DEFAULT NULL,
		  `pci_enodeb_id` INT(11) DEFAULT NULL,
		  `pci_cell_id` INT(11) DEFAULT NULL,
		  `pci_cell_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL
		) ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;  
 
  
    
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`cell_pu_mapping`
		(   
		`DATA_DATE` DATE NOT NULL,
		`DATA_HOUR` TINYINT(4) NOT NULL,
		`PU_ID` MEDIUMINT(9) NOT NULL,
		`ENODEB_ID` MEDIUMINT(9) NOT NULL,
		`CELL_ID` MEDIUMINT(9) NOT NULL,
		PRIMARY KEY (`CELL_ID`,`DATA_DATE`,`DATA_HOUR`,`ENODEB_ID`,`PU_ID`)    
		) ENGINE=MYISAM DEFAULT CHARSET=UTF8 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
  
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`Opt_rsi_result`
		(
			`PU_ID` MEDIUMINT(9) NOT NULL,
			`ENODEB_ID` MEDIUMINT(9)  NOT NULL,
			`CELL_ID` TINYINT(4) NOT NULL,
			`cell_name` varchar(125) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
			`INDOOR` TINYINT(1) DEFAULT NULL,
			`RSI` SMALLINT(6) NOT NULL,
			`SOFT_CONFLICT` TINYINT(1) DEFAULT NULL,
			`DEPTH` SMALLINT(6) DEFAULT NULL,
			`DISTANCE` FLOAT DEFAULT NULL,
			`NBR_PU_ID` MEDIUMINT(9) DEFAULT NULL,
			`NBR_ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
			`NBR_CELL_ID` TINYINT(4) DEFAULT NULL,
			`NBR_CELL_NAME` VARCHAR(50) DEFAULT NULL,
			`NBR_INDOOR` TINYINT(1) DEFAULT NULL,
			`COLLISION_RSI` SMALLINT(6) DEFAULT NULL,
			`RSI_SUGGEST_1` SMALLINT(6) DEFAULT NULL,
			`RSI_SUGGEST_2` SMALLINT(6) DEFAULT NULL,
			`BREAK_RULE` TINYINT(4) NOT NULL DEFAULT ''0'',
			PRIMARY KEY (ENODEB_ID,CELL_ID,NBR_ENODEB_ID,NBR_CELL_ID)
		) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
    
    
  
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_nbr_lte_blacklist` (
		   `ENODEB_OSS_NODE_ID_SOURCE` VARCHAR(20) DEFAULT NULL,
		  `MCC_TARGET` VARCHAR(3) DEFAULT NULL,
		  `MNC_TARGET` VARCHAR(3) DEFAULT NULL,
		  `ENODEBID_TARGET` MEDIUMINT(9) DEFAULT NULL,
		  `X2LIST_TYPE` VARCHAR(20) DEFAULT NULL,
		  KEY `NT_NBR_LTE_BLACKLIST_IDX1` (`ENODEB_OSS_NODE_ID_SOURCE`,`ENODEBID_TARGET`)
		) ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_nbr_cell_blacklist_pci` (
		`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
		`CELL_ID` MEDIUMINT(9) DEFAULT NULL,
		`NBCB_FREQUENZ` MEDIUMINT(9) DEFAULT NULL,
		`NBCB_PCI_STARTWERT` SMALLINT(6) DEFAULT NULL,
		`NBCB_PCI_BEREICH` MEDIUMINT(9) DEFAULT NULL,
		KEY `NT_NBR_CELL_BLACKLIST_PCI_IDX1` (`ENODEB_ID`,`CELL_ID`)
		) ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`REPEATER`
		(   
		`REPEATER_OSS_NODE_ID` INT(11),
		`REPEATER_NE_ID` TINYINT(4) DEFAULT  NULL,
		`REPEATER_STO_NAME` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
		`REPEATER_STO_KNG` VARCHAR(50) DEFAULT  NULL,
		`ACT_START`  VARCHAR(50) DEFAULT  NULL,
		`ACT_END` VARCHAR(50) DEFAULT  NULL,
		`PLN_START`  VARCHAR(50) DEFAULT  NULL,
		`PLN_END`  VARCHAR(50) DEFAULT  NULL,
		`ACT_STATE`  VARCHAR(50) DEFAULT  NULL,
		`REPEATER_TYPE` VARCHAR(20) DEFAULT NULL,
		`REPEATER_TA_DELAY` MEDIUMINT(9) DEFAULT NULL   
		) ENGINE=MYISAM DEFAULT CHARSET=UTF8 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`REPEATER_REF_AAA`
		(   
		`REPEATER_OSS_NODE_ID` INT(11),
		`AAA_OSS_NODE_ID` INT(11) DEFAULT  NULL 
		) ENGINE=MYISAM DEFAULT CHARSET=UTF8 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`REPEATER_REF_VAA`
		(   
		`REPEATER_OSS_NODE_ID` INT(11),
		`VAA_OSS_NODE_ID` INT(11) DEFAULT  NULL 
		) ENGINE=MYISAM DEFAULT CHARSET=UTF8 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`REPEATER_REF_CELL`
		(   
		`REPEATER_OSS_NODE_ID` INT(11),
		`CELL_OSS_NODE_ID` INT(11) DEFAULT  NULL 
		) ENGINE=MYISAM DEFAULT CHARSET=UTF8 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;  
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT_CELL_LTE_SLAVIP`
		(           
		`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
		`CELL_ID` MEDIUMINT(9) DEFAULT NULL,
		`SLA` CHAR(1) DEFAULT NULL,
		`VIP` CHAR(1) DEFAULT NULL,
		KEY `NT_CELL_LTE_SLAVIP_IDX1` (`ENODEB_ID`,`CELL_ID`)
		) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT_CELL_LTE_USERLABEL`
		(           
		`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
		`ENODEB_USERLABEL` VARCHAR(200) DEFAULT NULL
		) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT_NBR_ENODEB_CELL`
		(   
		`ENODEB_OSS_NODE_ID_SOURCE` INT(11),
		`CELL_OSS_NODE_ID_TARGET` VARCHAR(50) DEFAULT  NULL
		) ENGINE=MYISAM DEFAULT CHARSET=UTF8 DELAY_KEY_WRITE=1
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	CALL gt_gw_main.SP_CreateDB_NT_Schema_Sub(GT_DB);
END$$
DELIMITER ;
