DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_CovMo_Cross_Query_Distinct_Column`(IN COL_VALUE TEXT,OUT result_col TEXT,OUT result_schema TEXT)
a_label:
BEGIN
	DECLARE COL_VALUE_TMP TEXT DEFAULT '';
	DECLARE COL_STR TEXT;
	DECLARE COL_SCHEMA_TMP TEXT DEFAULT '';
	DECLARE COL_SCHEMA_STR TEXT;
	DECLARE i INT DEFAULT 0;
	DECLARE j INT DEFAULT 0;
	IF COL_VALUE='' THEN 
		SET COL_STR=SPACE(0);
	ELSE 
	BEGIN	
		IF COL_VALUE REGEXP '\\/'>0  THEN 
			SET @COL_VALUE_RE=REPLACE(COL_VALUE,'/',' AS |');
		ELSE 
			SET @COL_VALUE_RE=COL_VALUE;
		END IF;
		SET  @COL_VALUE_RE=REPLACE(@COL_VALUE_RE,'SQL_CALC_FOUND_ROWS','');
		
		SET @col_cnt=(LENGTH(@COL_VALUE_RE) - LENGTH(REPLACE(@COL_VALUE_RE, '|', '')))+1;
		SET i=1;
		WHILE i <= @col_cnt DO
		BEGIN	
 			SET @COL_VALUE_TMP_STR=TRIM(SUBSTRING_INDEX(SPLIT_STR(@COL_VALUE_RE,'|',i),' AS ',1));
 			IF @COL_VALUE_TMP_STR REGEXP '\\".*\\"'>0  THEN			
 				SET @COL_VALUE_TMP_STR='';
 			END IF;
			IF @COL_VALUE_TMP_STR REGEXP ' NOT IN '>0  THEN
				SET @COL_VALUE_TMP_STR_L=TRIM(SUBSTRING_INDEX(@COL_VALUE_TMP_STR,' NOT IN ',1));
				SET @COL_VALUE_TMP_STR_R=TRIM(SUBSTRING_INDEX(@COL_VALUE_TMP_STR,' NOT IN ',-1));
				SET @COL_VALUE_TMP_STR=CONCAT(@COL_VALUE_TMP_STR_L,',',@COL_VALUE_TMP_STR_R);
			END IF; 			
			IF @COL_VALUE_TMP_STR REGEXP ' IN '>0  THEN
				SET @COL_VALUE_TMP_STR_L=TRIM(SUBSTRING_INDEX(@COL_VALUE_TMP_STR,' IN ',1));
				SET @COL_VALUE_TMP_STR_R=TRIM(SUBSTRING_INDEX(@COL_VALUE_TMP_STR,' IN ',-1));
				SET @COL_VALUE_TMP_STR=CONCAT(@COL_VALUE_TMP_STR_L,',',@COL_VALUE_TMP_STR_R);
			END IF;	
			IF @COL_VALUE_TMP_STR REGEXP ' AND '>0  THEN
				SET @COL_VALUE_TMP_STR_L=TRIM(SUBSTRING_INDEX(@COL_VALUE_TMP_STR,' AND ',1));
				SET @COL_VALUE_TMP_STR_R=TRIM(SUBSTRING_INDEX(@COL_VALUE_TMP_STR,' AND ',-1));
				SET @COL_VALUE_TMP_STR=CONCAT(@COL_VALUE_TMP_STR_L,',',@COL_VALUE_TMP_STR_R);
			END IF;
			IF @COL_VALUE_TMP_STR REGEXP ' OR '>0  THEN
				SET @COL_VALUE_TMP_STR_L=TRIM(SUBSTRING_INDEX(@COL_VALUE_TMP_STR,' OR ',1));
				SET @COL_VALUE_TMP_STR_R=TRIM(SUBSTRING_INDEX(@COL_VALUE_TMP_STR,' OR ',-1));
				SET @COL_VALUE_TMP_STR=CONCAT(@COL_VALUE_TMP_STR_L,',',@COL_VALUE_TMP_STR_R);
			END IF;
			IF (@COL_VALUE_TMP_STR REGEXP '=.*'>0) OR (@COL_VALUE_TMP_STR REGEXP ' =.*'>0)  OR (@COL_VALUE_TMP_STR REGEXP ' = .*'>0) THEN 
				SET @COL_VALUE_TMP_STR_L=TRIM(SUBSTRING_INDEX(@COL_VALUE_TMP_STR,'=',1));
				SET @COL_VALUE_TMP_STR_R=TRIM(SUBSTRING_INDEX(@COL_VALUE_TMP_STR,'=',-1));
				SET @COL_VALUE_TMP_STR=CONCAT(@COL_VALUE_TMP_STR_L,',',@COL_VALUE_TMP_STR_R);
			END IF;
			SET @COL_VALUE_TMP_STR=REPLACE(REPLACE(@COL_VALUE_TMP_STR,'POW(',''),',2)','');
			SET @COL_VALUE_TMP_STR=REPLACE(REPLACE(@COL_VALUE_TMP_STR,'ROUND(',''),',2)','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'SQRT(','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'gt_covmo_proj_hex_geohash_to_lat(','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'gt_covmo_proj_hex_geohash_to_lng(','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'gt_covmo_proj_geohash_to_lat(','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'gt_covmo_proj_geohash_to_lng(','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'gt_geohash_ext(','');
			SET @COL_VALUE_TMP_STR=REPLACE(REPLACE(@COL_VALUE_TMP_STR,'IFNULL(',''),',0)','');
			SET @COL_VALUE_TMP_STR=REPLACE(REPLACE(@COL_VALUE_TMP_STR,'IFNULL(',''),',''Unknown'')','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'1-(','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'IF(','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'LEFT(','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'RIGHT(','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'SUM(','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'100*','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'*100','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'*100','');
 			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'MAX(','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'MIN(','');
 			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'AVG(','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'COUNT(','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'@','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'''','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'CONCAT(','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'NULL','');	
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'DISTINCT ','');	
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'CONVERT(','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'SIGNED','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'FLOOR(','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,' IS ','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'Unknown','');
			SET @COL_VALUE_TMP_STR=REPLACE(REPLACE(@COL_VALUE_TMP_STR,'(',''),')','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'=','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'~','');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'+',',');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'-',',');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'*',',');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'/',',');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'>',',');
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'<',',');   
			SET @COL_VALUE_TMP_STR=REPLACE(@COL_VALUE_TMP_STR,'.',',');
	
			SET @col_cnt_j=(LENGTH(@COL_VALUE_TMP_STR) - LENGTH(REPLACE(@COL_VALUE_TMP_STR, ',', '')))+1;
			
			SET j=1;
			SET @col_val=''; 
			SET @col_schema=''; 
			SET @col_j=''; 
			WHILE j <= @col_cnt_j DO
			BEGIN
				SET @col_j=TRIM(SPLIT_STR(@COL_VALUE_TMP_STR,',',j));	
				IF IsNum(@col_j) OR @col_j='' THEN 
					SET @col_val=CONCAT(@col_val,'');
				ELSE
					IF FIND_IN_SET(@col_j,COL_VALUE_TMP)=0 AND FIND_IN_SET(@col_j,@col_val)=0 THEN 
						SET @col_val=CONCAT(@col_val,@col_j,',');
						SET @col_schema=CONCAT(@col_schema,@col_j,' VARCHAR(100),');
					END IF;
				END IF;
				SET j=j+1;
			END;
			END WHILE;
			SET COL_VALUE_TMP=CONCAT(COL_VALUE_TMP,@col_val);
			SET COL_SCHEMA_TMP=CONCAT(COL_SCHEMA_TMP,@col_schema);
			SET i = i + 1;
		END;
		END WHILE;
		SET COL_STR=CONCAT(COL_VALUE_TMP,',');
		SET COL_SCHEMA_STR=CONCAT(COL_SCHEMA_TMP,',');
	END;
	END IF;
	SELECT REPLACE(COL_STR,',,',''),REPLACE(COL_SCHEMA_STR,',,','') INTO result_col,result_schema;
END$$
DELIMITER ;
