DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_CreateDB_Schema_GSM`(IN GT_DB VARCHAR(50), IN FILEDATE VARCHAR(18))
BEGIN
    
	DECLARE DAILY_JUDGE  BOOLEAN DEFAULT IF(RIGHT(FILEDATE,9)='0000_0000',TRUE,FALSE);
	DECLARE PARTITION_STR VARCHAR(1500) DEFAULT 
		' PARTITION BY LIST (DATA_HOUR)
		(
		 PARTITION h0 VALUES IN (0) ENGINE = MYISAM,
		 PARTITION h1 VALUES IN (1) ENGINE = MYISAM,
		 PARTITION h2 VALUES IN (2) ENGINE = MYISAM,
		 PARTITION h3 VALUES IN (3) ENGINE = MYISAM,
		 PARTITION h4 VALUES IN (4) ENGINE = MYISAM,
		 PARTITION h5 VALUES IN (5) ENGINE = MYISAM,
		 PARTITION h6 VALUES IN (6) ENGINE = MYISAM,
		 PARTITION h7 VALUES IN (7) ENGINE = MYISAM,
		 PARTITION h8 VALUES IN (8) ENGINE = MYISAM,
		 PARTITION h9 VALUES IN (9) ENGINE = MYISAM,
		 PARTITION h10 VALUES IN (10) ENGINE = MYISAM,
		 PARTITION h11 VALUES IN (11) ENGINE = MYISAM,
		 PARTITION h12 VALUES IN (12) ENGINE = MYISAM,
		 PARTITION h13 VALUES IN (13) ENGINE = MYISAM,
		 PARTITION h14 VALUES IN (14) ENGINE = MYISAM,
		 PARTITION h15 VALUES IN (15) ENGINE = MYISAM,
		 PARTITION h16 VALUES IN (16) ENGINE = MYISAM,
		 PARTITION h17 VALUES IN (17) ENGINE = MYISAM,
		 PARTITION h18 VALUES IN (18) ENGINE = MYISAM,
		 PARTITION h19 VALUES IN (19) ENGINE = MYISAM,
		 PARTITION h20 VALUES IN (20) ENGINE = MYISAM,
		 PARTITION h21 VALUES IN (21) ENGINE = MYISAM,
		 PARTITION h22 VALUES IN (22) ENGINE = MYISAM,
		 PARTITION h23 VALUES IN (23) ENGINE = MYISAM	
		 );';		
		 
	DECLARE TABLE_CALL_COL_STR VARCHAR(50000) DEFAULT
	'
	`CALL_ID` BIGINT(20),
	`START_TIME` DATETIME DEFAULT NULL,
	`START_TIME_MS` MEDIUMINT(9) DEFAULT NULL,
	`END_TIME` DATETIME DEFAULT NULL,
	`END_TIME_MS` MEDIUMINT(9) DEFAULT NULL,
	`DURATION` BIGINT(20) DEFAULT NULL,
	`IMSI` VARCHAR(20) CHARACTER SET utf8,
	`TMSI` VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL,
	`IMEI` VARCHAR(20) CHARACTER SET utf8,
	`IMSI_GROUP_ID` SMALLINT(6) DEFAULT NULL,
	`MCC` CHAR(3) DEFAULT NULL,
	`MNC` VARCHAR(3) CHARACTER SET utf8 DEFAULT NULL,
	`MAKE_ID` SMALLINT(6) DEFAULT NULL,
	`MODEL_ID` MEDIUMINT(9) DEFAULT NULL,
	`START_LAC` MEDIUMINT(9) DEFAULT NULL,
	`START_CELL_ID` MEDIUMINT(9),
	`START_BSC_ID` MEDIUMINT(9) DEFAULT NULL,
	`START_TCH_TYPE` SMALLINT(5) DEFAULT NULL,
	`END_LAC` MEDIUMINT(9) DEFAULT NULL,
	`END_CELL_ID` MEDIUMINT(9) DEFAULT NULL,
	`END_BSC_ID` MEDIUMINT(9) DEFAULT NULL,
	`END_TCH_TYPE` SMALLINT(5) DEFAULT NULL,
	`CALL_TYPE` SMALLINT(6) DEFAULT NULL,
	`BSSMAP_FAILURE_CNT` BIGINT(20) DEFAULT NULL,
	`BSSMAP_FAILURE_EVENT_LAST` MEDIUMINT(9) DEFAULT NULL,
	`BSSMAP_FAILURE_CAUSE_LAST` BIGINT(20) DEFAULT NULL,
	`RSL_FAILURE_CNT` MEDIUMINT(9) DEFAULT NULL,
	`RSL_FAILURE_EVENT_LAST` BIGINT(20) DEFAULT NULL,
	`RSL_FAILURE_CAUSE_LAST` MEDIUMINT(9) DEFAULT NULL,
	`RR_DTAP_FAILURE_CNT` BIGINT(20) DEFAULT NULL,
	`RR_DTAP_FAILURE_EVENT_LAST` MEDIUMINT(9) DEFAULT NULL,
	`RR_DTAP_FAILURE_CAUSE_LAST` BIGINT(20) DEFAULT NULL,
	`CALL_STATUS` SMALLINT(6) DEFAULT NULL,
	`REQUEST_TYPE` SMALLINT(6) DEFAULT NULL,
	`HO_ATTEMPT_COUNT` SMALLINT(6) DEFAULT NULL,
	`HO_FAILURE_COUNT` SMALLINT(6) DEFAULT NULL,
	`ACCESS_POINT_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL,
	`CALL_SETUP_TIME` MEDIUMINT(9) DEFAULT NULL,
	`B_PARTY_NUMBER` VARCHAR(15) CHARACTER SET utf8 DEFAULT NULL,
	`ACCESS_REASON` BIGINT(20) DEFAULT NULL,
	`ACCESS_RESULT_CAUSE` BIGINT(20) DEFAULT NULL,
	`RELEASE_RESULT_CAUSE` BIGINT(20) DEFAULT NULL,
	`APN` SMALLINT(6) DEFAULT NULL,
	`RR_CONN_CAUSE` TINYINT(4) DEFAULT NULL,
	`BATCH` SMALLINT(6) unsigned  DEFAULT NULL,
	`PU_ID` SMALLINT(6) unsigned  DEFAULT NULL,
	`DATA_DATE` DATE DEFAULT NULL,
	`DATA_HOUR` TINYINT(4) DEFAULT NULL,
	`MOVING` TINYINT(4) DEFAULT NULL,
	`INDOOR` TINYINT(4) DEFAULT NULL,
	`MOVING_SPEED` FLOAT DEFAULT NULL,
	`MOVING_TYPE` TINYINT(4) DEFAULT NULL,
	`POS_FIRST_LAC` MEDIUMINT(9) DEFAULT NULL,
	`POS_FIRST_BSC_ID` MEDIUMINT(9),
	`POS_FIRST_CLUSTER_ID` MEDIUMINT(9) DEFAULT NULL,
	`POS_FIRST_CELL_INDOOR` TINYINT(4) DEFAULT NULL,
	`POS_FIRST_SITE_ID` VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL,
	`POS_FIRST_CELL_ID` MEDIUMINT(9),
	`POS_FIRST_CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL,
	`POS_FIRST_LOC` BIGINT(20) DEFAULT NULL,
	`POS_FIRST_TILE` BIGINT(20) DEFAULT NULL,
	`POS_FIRST_LON` FLOAT(9,6) DEFAULT NULL,
	`POS_FIRST_LAT` FLOAT(9,6) DEFAULT NULL,
	`POS_FIRST_FREQUENCY` SMALLINT(6) DEFAULT NULL,
	`POS_FIRST_ARFCN` SMALLINT(5) UNSIGNED DEFAULT NULL,
	`POS_FIRST_RXLEV_FULL_DOWNLINK` FLOAT DEFAULT NULL,
	`POS_FIRST_RXQUAL_FULL_DOWNLINK` FLOAT DEFAULT NULL,
	`POS_FIRST_RXLEV_FULL_UPLINK` FLOAT DEFAULT NULL,
	`POS_FIRST_RXQUAL_FULL_UPLINK` FLOAT DEFAULT NULL,
	`POS_FIRST_OVERFLAG` TINYINT(4) DEFAULT NULL,
	`POS_FIRST_OVERSHOOT_DISTANCE` FLOAT DEFAULT NULL,
	`POS_LAST_LAC` MEDIUMINT(9) DEFAULT NULL,
	`POS_LAST_BSC_ID` MEDIUMINT(9),
	`POS_LAST_CLUSTER_ID` MEDIUMINT(9) DEFAULT NULL,
	`POS_LAST_CELL_INDOOR` TINYINT(4) DEFAULT NULL,
	`POS_LAST_SITE_ID` VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL,
	`POS_LAST_CELL_ID` MEDIUMINT(9),
	`POS_LAST_CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL,
	`POS_LAST_LOC` BIGINT(20) DEFAULT NULL,
	`POS_LAST_TILE` BIGINT(20) DEFAULT NULL,
	`POS_LAST_LON` FLOAT(9,6) DEFAULT NULL,
	`POS_LAST_LAT` FLOAT(9,6) DEFAULT NULL,
	`POS_LAST_FREQUENCY` VARCHAR(10) CHARACTER SET utf8 DEFAULT NULL,
	`POS_LAST_ARFCN` SMALLINT(5) DEFAULT NULL,
	`POS_LAST_RXLEV_FULL_DOWNLINK` FLOAT DEFAULT NULL,
	`POS_LAST_RXQUAL_FULL_DOWNLINK` FLOAT DEFAULT NULL,
	`POS_LAST_RXLEV_FULL_UPLINK` FLOAT DEFAULT NULL,
	`POS_LAST_RXQUAL_FULL_UPLINK` FLOAT DEFAULT NULL,
	`POS_FIRST_CONFIDENCE` TINYINT(4) DEFAULT NULL,
	`POS_LAST_CONFIDENCE` TINYINT(4) DEFAULT NULL,
	`POS_FIRST_DEVIATION_LEVEL` INT(11) DEFAULT NULL,
	`POS_LAST_DEVIATION_LEVEL` INT(11) DEFAULT NULL
	';  
	
	DECLARE table_tile_start_str VARCHAR(5000) DEFAULT
	'
	`CALL_CNT` INT(11) DEFAULT NULL,
	`BLOCK_CNT` MEDIUMINT(9) DEFAULT NULL,
	`SETUP_FAILURE_CNT` MEDIUMINT(9) DEFAULT NULL,
	`RXLEV_FULL_DOWNLINK_CNT` INT(11) DEFAULT NULL,
	`RXLEV_FULL_DOWNLINK_SUM` DOUBLE DEFAULT NULL,
	`RXQUAL_FULL_DOWNLINK_CNT` INT(11) DEFAULT NULL,
	`RXQUAL_FULL_DOWNLINK_SUM` DOUBLE DEFAULT NULL,
	`RXLEV_FULL_UPLINK_CNT` INT(11) DEFAULT NULL,
	`RXLEV_FULL_UPLINK_SUM` DOUBLE DEFAULT NULL,
	`RXQUAL_FULL_UPLINK_CNT` INT(11) DEFAULT NULL,
	`RXQUAL_FULL_UPLINK_SUM` DOUBLE DEFAULT NULL,
	`IMSI_CNT` INT(11) DEFAULT NULL,
	`CALL_TYPE_10` MEDIUMINT(9) DEFAULT NULL,
	`CALL_TYPE_11` MEDIUMINT(9) DEFAULT NULL,
	`CALL_TYPE_14` MEDIUMINT(9) DEFAULT NULL,
	`CALL_TYPE_15` MEDIUMINT(9) DEFAULT NULL,
	`CALL_TYPE_16` MEDIUMINT(9) DEFAULT NULL,
	`CALL_TYPE_20` MEDIUMINT(9) DEFAULT NULL,
	`CALL_TYPE_99` MEDIUMINT(9) DEFAULT NULL,
	`BLOCK_RXLEV_FULL_DOWNLINK_CNT` INT(11) DEFAULT NULL,
	`BLOCK_RXLEV_FULL_DOWNLINK_SUM` DOUBLE DEFAULT NULL,
	`BLOCK_RXQUAL_FULL_DOWNLINK_CNT` INT(11) DEFAULT NULL,
	`BLOCK_RXQUAL_FULL_DOWNLINK_SUM` DOUBLE DEFAULT NULL,
	`BLOCK_RXLEV_FULL_UPLINK_CNT` INT(11) DEFAULT NULL,
	`BLOCK_RXLEV_FULL_UPLINK_SUM` DOUBLE DEFAULT NULL,
	`BLOCK_RXQUAL_FULL_UPLINK_CNT` INT(11) DEFAULT NULL,
	`BLOCK_RXQUAL_FULL_UPLINK_SUM` DOUBLE DEFAULT NULL,
	`OVER_LOC_CALL_CNT`	MEDIUMINT(9) DEFAULT NULL,
	`NONOVER_LOC_CALL_CNT`	MEDIUMINT(9) DEFAULT NULL,
	`TILE_OVER_FLAG`	TINYINT(1) DEFAULT NULL,
	`OVER_DISTANCE_SUM` DOUBLE DEFAULT NULL,
	`OVER_DISTANCE_MAX` DOUBLE DEFAULT NULL,
	`CALL_SETUP_TIME` DOUBLE DEFAULT NULL,
	`CALL_SETUP_TIME_CNT` INT(11) DEFAULT NULL,
	';
	DECLARE table_tile_end_str VARCHAR(5000) DEFAULT
	'
	`CALL_CNT` INT(11) DEFAULT NULL,
	`CALL_END_CNT` INT(11) DEFAULT NULL,
	`DROP_CNT` MEDIUMINT(9) DEFAULT NULL,
	`RXLEV_FULL_DOWNLINK_CNT` INT(11) DEFAULT NULL,
	`RXLEV_FULL_DOWNLINK_SUM` DOUBLE DEFAULT NULL,
	`RXQUAL_FULL_DOWNLINK_CNT` INT(11) DEFAULT NULL,
	`RXQUAL_FULL_DOWNLINK_SUM` DOUBLE DEFAULT NULL,
	`RXLEV_FULL_UPLINK_CNT` INT(11) DEFAULT NULL,
	`RXLEV_FULL_UPLINK_SUM` DOUBLE DEFAULT NULL,
	`RXQUAL_FULL_UPLINK_CNT` INT(11) DEFAULT NULL,
	`RXQUAL_FULL_UPLINK_SUM` DOUBLE DEFAULT NULL,
	`BSSMAP_11` MEDIUMINT(9) DEFAULT NULL,
	`BSSMAP_12` MEDIUMINT(9) DEFAULT NULL,
	`BSSMAP_13` MEDIUMINT(9) DEFAULT NULL,
	`BSSMAP_14` MEDIUMINT(9) DEFAULT NULL,
	`BSSMAP_15` MEDIUMINT(9) DEFAULT NULL,
	`BSSMAP_16` MEDIUMINT(9) DEFAULT NULL,
	`BSSMAP_17` MEDIUMINT(9) DEFAULT NULL,
	`BSSMAP_18` MEDIUMINT(9) DEFAULT NULL,
	`RSL_21` MEDIUMINT(9) DEFAULT NULL,
	`RSL_22` MEDIUMINT(9) DEFAULT NULL,
	`RSL_23` MEDIUMINT(9) DEFAULT NULL,
	`RR_31` MEDIUMINT(9) DEFAULT NULL,
	`RR_32` MEDIUMINT(9) DEFAULT NULL,
	`RR_33` MEDIUMINT(9) DEFAULT NULL,
	`RR_34` MEDIUMINT(9) DEFAULT NULL,
	`RR_35` MEDIUMINT(9) DEFAULT NULL,
	`RR_36` MEDIUMINT(9) DEFAULT NULL,
	`DROP_RXLEV_FULL_DOWNLINK_CNT` INT(11) DEFAULT NULL,
	`DROP_RXLEV_FULL_DOWNLINK_SUM` DOUBLE DEFAULT NULL,
	`DROP_RXQUAL_FULL_DOWNLINK_CNT` INT(11) DEFAULT NULL,
	`DROP_RXQUAL_FULL_DOWNLINK_SUM` DOUBLE DEFAULT NULL,
	`DROP_RXLEV_FULL_UPLINK_CNT` INT(11) DEFAULT NULL,
	`DROP_RXLEV_FULL_UPLINK_SUM` DOUBLE DEFAULT NULL,
	`DROP_RXQUAL_FULL_UPLINK_CNT` INT(11) DEFAULT NULL,
	`DROP_RXQUAL_FULL_UPLINK_SUM` DOUBLE DEFAULT NULL,
	`DURATION` DOUBLE DEFAULT NULL,
	';
	DECLARE table_tile_dominant_cell_str VARCHAR(5000) DEFAULT
	'
	`CALL_CNT` INT(11) DEFAULT NULL,
	`RXLEV_FULL_DOWNLINK_CNT` INT(11) DEFAULT NULL,
	`RXLEV_FULL_DOWNLINK_SUM` DOUBLE DEFAULT NULL,
	`RXQUAL_FULL_DOWNLINK_CNT` INT(11) DEFAULT NULL,
	`RXQUAL_FULL_DOWNLINK_SUM` DOUBLE DEFAULT NULL,
	';
	DECLARE table_tile_handset_str VARCHAR(5000) DEFAULT
	'
	`CALL_CNT` INT(11) DEFAULT NULL,
	`BLOCK_CNT` MEDIUMINT(9) DEFAULT NULL,
	`SETUP_FAILURE_CNT` MEDIUMINT(9) DEFAULT NULL,
	`CALL_END_CNT` INT(11) DEFAULT NULL,
	`DROP_CNT` MEDIUMINT(9) DEFAULT NULL,
	`DURATION` BIGINT(20) DEFAULT NULL,
	`CS_ERLANG` BIGINT(20) DEFAULT NULL,
	`SMS_CNT` INT(11) DEFAULT NULL,
	`VOICE_CNT` INT(11) DEFAULT NULL,
	`GPRS_DATA_CNT` INT(11) DEFAULT NULL,
	`OTHERS_CNT` INT(11) DEFAULT NULL,
	`FIRST_RXLEV_FULL_DOWNLINK_CNT` INT(11) DEFAULT NULL,
	`FIRST_RXLEV_FULL_DOWNLINK_SUM` DOUBLE DEFAULT NULL,
	`FIRST_RXQUAL_FULL_DOWNLINK_CNT` INT(11) DEFAULT NULL,
	`FIRST_RXQUAL_FULL_DOWNLINK_SUM` DOUBLE DEFAULT NULL,
	`FIRST_RXLEV_FULL_UPLINK_CNT` INT(11) DEFAULT NULL,
	`FIRST_RXLEV_FULL_UPLINK_SUM` DOUBLE DEFAULT NULL,
	`FIRST_RXQUAL_FULL_UPLINK_CNT` INT(11) DEFAULT NULL,
	`FIRST_RXQUAL_FULL_UPLINK_SUM` DOUBLE DEFAULT NULL,
	`LAST_RXLEV_FULL_DOWNLINK_CNT` INT(11) DEFAULT NULL,
	`LAST_RXLEV_FULL_DOWNLINK_SUM` DOUBLE DEFAULT NULL,
	`LAST_RXQUAL_FULL_DOWNLINK_CNT` INT(11) DEFAULT NULL,
	`LAST_RXQUAL_FULL_DOWNLINK_SUM` DOUBLE DEFAULT NULL,
	`LAST_RXLEV_FULL_UPLINK_CNT` INT(11) DEFAULT NULL,
	`LAST_RXLEV_FULL_UPLINK_SUM` DOUBLE DEFAULT NULL,
	`LAST_RXQUAL_FULL_UPLINK_CNT` INT(11) DEFAULT NULL,
	`LAST_RXQUAL_FULL_UPLINK_SUM` DOUBLE DEFAULT NULL,
	';
	DECLARE table_tile_fp_str VARCHAR(5000) DEFAULT
	'
	`FP_RXLEV_BEST_SUM` DOUBLE DEFAULT NULL,
	`FP_RXLEV_SERVING_SUM` DOUBLE DEFAULT NULL,
	`FP_RXQUAL_SERVING_SUM` DOUBLE DEFAULT NULL,
	`FP_RXLEV_ALL_SUM` DOUBLE DEFAULT NULL,
	`MMR_CNT` INT(11) DEFAULT NULL,
	`BEST_CNT` INT(11) DEFAULT NULL,
	`BEST_SERVING_CNT` INT(11) DEFAULT NULL,
	`SERVING_CNT` INT(11) DEFAULT NULL,
	`DURATION` BIGINT(20) DEFAULT NULL,
	`RXLEV_BEST_SECOND_GAP_SUM` DOUBLE DEFAULT NULL,
	`RXLEV_BEST_SECOND_GAP_CNT` INT(11) DEFAULT NULL,
	`RXLEV_BESTSERVING_SECOND_GAP_SUM` DOUBLE DEFAULT NULL,
	`RXLEV_BESTSERVING_SECOND_GAP_CNT` MEDIUMINT(9) DEFAULT NULL,
	`RXLEV_BEST_SERVING_GAP_SUM` DOUBLE DEFAULT NULL,
	`RXLEV_BEST_SERVING_GAP_CNT` MEDIUMINT(9) DEFAULT NULL,
	`DOWLINK_INTERFERED_CNT` INT(11) DEFAULT NULL,
	`UPLINK_INTERFERED_CNT` INT(11) DEFAULT NULL,
	`MS_POWER_SUM` MEDIUMINT(9) DEFAULT NULL,
	`MS_POWER_CNT` MEDIUMINT(9) DEFAULT NULL,
	`INTER_CELL_HO_CNT` INT(11) DEFAULT NULL,
	`INTER_CELL_HO_FAIL_CNT` INT(11) DEFAULT NULL,
	`INTRA_CELL_HO_CNT` INT(11) DEFAULT NULL,
	`INTRA_CELL_HO_FAIL_CNT` INT(11) DEFAULT NULL,
	`CS_ERLANG` BIGINT(20) DEFAULT NULL,
	`CS_ERLANG_CNT` INT(11) DEFAULT NULL,
	`SERVING_T1_EVENT_CNT` MEDIUMINT(9) DEFAULT NULL,
	`SERVING_T0_EVENT_CNT` MEDIUMINT(9) DEFAULT NULL,
	`BEST_T1_EVENT_CNT` MEDIUMINT(9) DEFAULT NULL,
	`BEST_T0_EVENT_CNT` MEDIUMINT(9) DEFAULT NULL,
	`SERVING_MAINBEAM_T1_EVENT_CNT` MEDIUMINT(9) DEFAULT NULL,
	`SERVING_MAINBEAM_T0_EVENT_CNT` MEDIUMINT(9) DEFAULT NULL,
	`BEST_MAINBEAM_T1_EVENT_CNT` MEDIUMINT(9) DEFAULT NULL,
	`BEST_MAINBEAM_T0_EVENT_CNT` MEDIUMINT(9) DEFAULT NULL,
	`TILE_SERVING_MAINBEAM` TINYINT(1) DEFAULT NULL,
	`TILE_BEST_MAINBEAM` TINYINT(1) DEFAULT NULL,
	';
	DECLARE table_tile_imsi_str VARCHAR(5000) DEFAULT
	'
	`IMEI` VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL,
	`MAKE_ID` SMALLINT(6) DEFAULT NULL,
	`MODEL_ID` MEDIUMINT(9) DEFAULT NULL,
	`CALL_CNT` INT(11) DEFAULT NULL,
	`BLOCK_CNT` MEDIUMINT(9) DEFAULT NULL,
	`SETUP_FAILURE_CNT` MEDIUMINT(9) DEFAULT NULL,
	`CALL_END_CNT` INT(11) DEFAULT NULL,
	`DROP_CNT` MEDIUMINT(9) DEFAULT NULL,
	`DURATION` BIGINT(20) DEFAULT NULL,
	`CS_ERLANG` BIGINT(20) DEFAULT NULL,
	`SMS_CNT` INT(11) DEFAULT NULL,
	`VOICE_CNT` INT(11) DEFAULT NULL,
	`GPRS_DATA_CNT` INT(11) DEFAULT NULL,
	`OTHERS_CNT` INT(11) DEFAULT NULL,
	`FIRST_RXLEV_FULL_DOWNLINK_CNT` INT(11) DEFAULT NULL,
	`FIRST_RXLEV_FULL_DOWNLINK_SUM` DOUBLE DEFAULT NULL,
	`FIRST_RXQUAL_FULL_DOWNLINK_CNT` INT(11) DEFAULT NULL,
	`FIRST_RXQUAL_FULL_DOWNLINK_SUM` DOUBLE DEFAULT NULL,
	`FIRST_RXLEV_FULL_UPLINK_CNT` INT(11) DEFAULT NULL,
	`FIRST_RXLEV_FULL_UPLINK_SUM` DOUBLE DEFAULT NULL,
	`FIRST_RXQUAL_FULL_UPLINK_CNT` INT(11) DEFAULT NULL,
	`FIRST_RXQUAL_FULL_UPLINK_SUM` DOUBLE DEFAULT NULL,
	`LAST_RXLEV_FULL_DOWNLINK_CNT` INT(11) DEFAULT NULL,
	`LAST_RXLEV_FULL_DOWNLINK_SUM` DOUBLE DEFAULT NULL,
	`LAST_RXQUAL_FULL_DOWNLINK_CNT` INT(11) DEFAULT NULL,
	`LAST_RXQUAL_FULL_DOWNLINK_SUM` DOUBLE DEFAULT NULL,
	`LAST_RXLEV_FULL_UPLINK_CNT` INT(11) DEFAULT NULL,
	`LAST_RXLEV_FULL_UPLINK_SUM` DOUBLE DEFAULT NULL,
	`LAST_RXQUAL_FULL_UPLINK_CNT` INT(11) DEFAULT NULL,
	`LAST_RXQUAL_FULL_UPLINK_SUM` DOUBLE DEFAULT NULL,
	';
	
	DECLARE opt_nbr_relation_str VARCHAR(5000) DEFAULT
	'
	`HO_ALL_CNT` SMALLINT(6) DEFAULT NULL,
	`HO_SUCC_CNT` SMALLINT(6) DEFAULT NULL,
	`HO_FAIL_CNT` SMALLINT(6) DEFAULT NULL,
	`HO_DROP_CNT` SMALLINT(6) DEFAULT NULL,
	`MEAS_RXLEV` DOUBLE DEFAULT NULL,
	`MEAS_CNT` MEDIUMINT(6) DEFAULT NULL,
	`SERV_RXLEV` DOUBLE DEFAULT NULL,
	`SERV_RXLEV_CNT` MEDIUMINT(6) DEFAULT NULL,
	`SERV_RXQUAL` DOUBLE DEFAULT NULL,
	`SERV_RXQUAL_CNT` MEDIUMINT(6) DEFAULT NULL,
	';
	DECLARE CUSTOMER_USER_FLAG VARCHAR(10);
   
	
	SELECT LOWER(`value`) INTO CUSTOMER_USER_FLAG  FROM gt_gw_main.integration_param WHERE gt_group = 'sp' AND gt_name = 'special_imsi' ;
	SET @SqlCmd =CONCAT('CREATE DATABASE ', GT_DB);
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
			
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_call_cnt` 
				(
				  `DATA_DATE` DATE DEFAULT NULL,
				  `DATA_HOUR` TINYINT(4) DEFAULT NULL,
				  `PU_ID` MEDIUMINT(9) DEFAULT NULL,
				  `SERVICETYPE` VARCHAR(10) DEFAULT NULL,
				  `TOT_CALL_CNT` BIGINT DEFAULT NULL,
				  `TECH_MASK` TINYINT(4) DEFAULT 1,
				  `NOTE` VARCHAR(200) DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1'
				,IF(DAILY_JUDGE=TRUE,PARTITION_STR,';'));	
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_fp_gsm` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CALL_TYPE` TINYINT(4) COMMENT ''KEY'',
				`CALL_STATUS` TINYINT(4) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_fp_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`TILE_ID`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`,`CALL_TYPE`,`CALL_STATUS`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_fp_gsm_t` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CALL_TYPE` TINYINT(4) COMMENT ''KEY'',
				`CALL_STATUS` TINYINT(4) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				',table_tile_fp_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`TILE_ID`,`FREQUENCY`,`ARFCN`,`CALL_TYPE`,`CALL_STATUS`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_fp_gsm_c` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CALL_TYPE` TINYINT(4) COMMENT ''KEY'',
				`CALL_STATUS` TINYINT(4) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_fp_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`,`CALL_TYPE`,`CALL_STATUS`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_fp_gsm_dy` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CALL_TYPE` TINYINT(4) COMMENT ''KEY'',
				`CALL_STATUS` TINYINT(4) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_fp_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`TILE_ID`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`,`CALL_TYPE`,`CALL_STATUS`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_fp_gsm_dy_t` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CALL_TYPE` TINYINT(4) COMMENT ''KEY'',
				`CALL_STATUS` TINYINT(4) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				',table_tile_fp_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`TILE_ID`,`FREQUENCY`,`ARFCN`,`CALL_TYPE`,`CALL_STATUS`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_fp_gsm_dy_c` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CALL_TYPE` TINYINT(4) COMMENT ''KEY'',
				`CALL_STATUS` TINYINT(4) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_fp_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`,`CALL_TYPE`,`CALL_STATUS`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_fp_gsm_dy_def` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_fp_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`TILE_ID`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_fp_gsm_dy_t_def` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				',table_tile_fp_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`TILE_ID`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_fp_gsm_dy_c_def` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_fp_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_fp_gsm_def` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_fp_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`TILE_ID`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_fp_gsm_t_def` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				',table_tile_fp_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`TILE_ID`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_fp_gsm_c_def` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_fp_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_start_gsm` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CALL_TYPE` TINYINT(4) COMMENT ''KEY'',
				`CALL_STATUS` TINYINT(4) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_start_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`TILE_ID`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`,`CALL_TYPE`,`CALL_STATUS`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_start_gsm_t` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CALL_TYPE` TINYINT(4) COMMENT ''KEY'',
				`CALL_STATUS` TINYINT(4) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				',table_tile_start_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`TILE_ID`,`FREQUENCY`,`ARFCN`,`CALL_TYPE`,`CALL_STATUS`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_start_gsm_c` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CALL_TYPE` TINYINT(4) COMMENT ''KEY'',
				`CALL_STATUS` TINYINT(4) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_start_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`,`CALL_TYPE`,`CALL_STATUS`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_start_gsm_dy` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CALL_TYPE` TINYINT(4) COMMENT ''KEY'',
				`CALL_STATUS` TINYINT(4) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_start_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`TILE_ID`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`,`CALL_TYPE`,`CALL_STATUS`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_start_gsm_dy_t` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CALL_TYPE` TINYINT(4) COMMENT ''KEY'',
				`CALL_STATUS` TINYINT(4) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				',table_tile_start_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`TILE_ID`,`FREQUENCY`,`ARFCN`,`CALL_TYPE`,`CALL_STATUS`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_start_gsm_dy_c` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CALL_TYPE` TINYINT(4) COMMENT ''KEY'',
				`CALL_STATUS` TINYINT(4) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_start_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`,`CALL_TYPE`,`CALL_STATUS`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_start_gsm_dy_def` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_start_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`TILE_ID`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_start_gsm_dy_t_def` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				',table_tile_start_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`TILE_ID`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_start_gsm_dy_c_def` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_start_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_start_gsm_def` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_start_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`TILE_ID`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_start_gsm_t_def` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				',table_tile_start_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`TILE_ID`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_start_gsm_c_def` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_start_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_end_gsm` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CALL_TYPE` TINYINT(4) COMMENT ''KEY'',
				`CALL_STATUS` TINYINT(4) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_end_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`TILE_ID`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`,`CALL_TYPE`,`CALL_STATUS`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_end_gsm_t` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CALL_TYPE` TINYINT(4) COMMENT ''KEY'',
				`CALL_STATUS` TINYINT(4) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				',table_tile_end_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`TILE_ID`,`FREQUENCY`,`ARFCN`,`CALL_TYPE`,`CALL_STATUS`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_end_gsm_c` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CALL_TYPE` TINYINT(4) COMMENT ''KEY'',
				`CALL_STATUS` TINYINT(4) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_end_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`,`CALL_TYPE`,`CALL_STATUS`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_end_gsm_dy` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CALL_TYPE` TINYINT(4) COMMENT ''KEY'',
				`CALL_STATUS` TINYINT(4) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_end_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`TILE_ID`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`,`CALL_TYPE`,`CALL_STATUS`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_end_gsm_dy_t` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CALL_TYPE` TINYINT(4) COMMENT ''KEY'',
				`CALL_STATUS` TINYINT(4) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				',table_tile_end_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`TILE_ID`,`FREQUENCY`,`ARFCN`,`CALL_TYPE`,`CALL_STATUS`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_end_gsm_dy_c` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CALL_TYPE` TINYINT(4) COMMENT ''KEY'',
				`CALL_STATUS` TINYINT(4) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_end_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`,`CALL_TYPE`,`CALL_STATUS`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_end_gsm_dy_def` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_end_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`TILE_ID`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_end_gsm_dy_t_def` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				',table_tile_end_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`TILE_ID`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_end_gsm_dy_c_def` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_end_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_end_gsm_def` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_end_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`TILE_ID`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_end_gsm_t_def` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				',table_tile_end_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`TILE_ID`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_end_gsm_c_def` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_end_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_dominant_cell_gsm` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_dominant_cell_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`TILE_ID`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_dominant_cell_gsm_dy` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`TILE_ID` BIGINT(20) COMMENT ''KEY'',
				`LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`CLUSTER_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				`CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`FREQUENCY` SMALLINT(6) COMMENT ''KEY'',
				`ARFCN` MEDIUMINT(9) COMMENT ''KEY'',
				`MOVING` TINYINT(4) COMMENT ''KEY'',
				`INDOOR` TINYINT(4) COMMENT ''KEY'',
				`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COMMENT ''TAG'',
				',table_tile_dominant_cell_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`TILE_ID`,`LAC`,`BSC_ID`,`CLUSTER_ID`,`SITE_ID`,`CELL_ID`,`FREQUENCY`,`ARFCN`,`MOVING`,`INDOOR`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_imsi_gsm` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`IMSI` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				',table_tile_imsi_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`IMSI`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_imsi_gsm_dy` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`IMSI` VARCHAR(20) CHARACTER SET utf8 COMMENT ''KEY'',
				',table_tile_imsi_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`IMSI`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_handset_gsm` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`MAKE_ID` SMALLINT(6) COMMENT ''KEY'',
				`MODEL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				',table_tile_handset_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`MAKE_ID`,`MODEL_ID`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_tile_handset_gsm_dy` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`MAKE_ID` SMALLINT(6) COMMENT ''KEY'',
				`MODEL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				',table_tile_handset_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`MAKE_ID`,`MODEL_ID`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_position_gsm` (
				`CALL_ID` bigint(20),
				`DATE_TIME` datetime DEFAULT NULL,
				`DATE_TIME_MS` MEDIUMINT(9) DEFAULT NULL,
				`SEQ_ID` MEDIUMINT(9),
				`EVENT_ID` SMALLINT (6) UNSIGNED DEFAULT NULL,
				`SERVING_LAC` MEDIUMINT(9) DEFAULT NULL,
				`SERVING_BSC_ID` MEDIUMINT(9) DEFAULT NULL,
				`SERVING_CLUSTER_ID` MEDIUMINT(9) DEFAULT NULL,
				`SERVING_SITE_ID` VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL,
				`SERVING_CELL_ID` MEDIUMINT(9) DEFAULT NULL,
				`SERVING_CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL,
				`SERVING_ARFCN` SMALLINT (6) UNSIGNED DEFAULT NULL,
				`SERVING_FREQUENCY` VARCHAR(10) CHARACTER SET utf8 DEFAULT NULL,
				`RXLEV_FULL_UPLINK` FLOAT DEFAULT NULL,
				`RXLEV_SUB_UPLINK` FLOAT DEFAULT NULL,
				`RXQUAL_FULL_UPLINK` FLOAT DEFAULT NULL,
				`RXQUAL_SUB_UPLINK` FLOAT DEFAULT NULL,
				`RXLEV_FULL_DOWNLINK` FLOAT DEFAULT NULL,
				`RXLEV_SUB_DOWNLINK` FLOAT DEFAULT NULL,
				`RXQUAL_FULL_DOWNLINK` FLOAT DEFAULT NULL,
				`RXQUAL_SUB_DOWNLINK` FLOAT DEFAULT NULL,
				`MS_POWER` smallint(5) DEFAULT NULL,
				`HO_CAUSE_VALUE` bigint(20) DEFAULT NULL,
				`TIMING_ADVANCE` smallint(5) DEFAULT NULL,
				`DURATION` mediumint(9) DEFAULT NULL,
				`MEASURED_NCELL_RXLEV` VARCHAR(30) CHARACTER SET utf8 DEFAULT NULL,
				`MEASURED_NCELL_LAC` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL,
				`MEASURED_NCELL_BSC_ID` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL,
				`MEASURED_NCELL_CELL_ID` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL,
				`HO_RESULT` TINYINT(4) DEFAULT NULL,
				`HO_TYPE` TINYINT(4) DEFAULT NULL,
				`IMSI` VARCHAR(20) CHARACTER SET utf8,
				`IMEI` VARCHAR(20) CHARACTER SET utf8,
				`CALL_TYPE` SMALLINT(6) DEFAULT NULL,
				`CALL_STATUS` SMALLINT(6) DEFAULT NULL,
				`MAKE_ID` SMALLINT(6) DEFAULT NULL,
				`MODEL_ID` MEDIUMINT(9) DEFAULT NULL,
				`BATCH` SMALLINT(6) unsigned DEFAULT NULL,
				`PU_ID` SMALLINT(6) unsigned DEFAULT NULL,
				`DATA_DATE` DATE DEFAULT NULL,
				`DATA_HOUR` TINYINT(4) DEFAULT NULL,
				`MOVING` TINYINT(4) DEFAULT NULL,
				`INDOOR` TINYINT(4) DEFAULT NULL,
				`MOVING_SPEED` FLOAT DEFAULT NULL,
				`LONGITUDE` FLOAT(9,6) DEFAULT NULL,
				`LATITUDE` FLOAT(9,6) DEFAULT NULL,
				`LOC_ID` bigint(20) DEFAULT NULL,
				`TILE_ID` bigint(20) DEFAULT NULL,
				`UPLINK_INTERFERENCE_FLAG` TINYINT(1) DEFAULT NULL,
				`DOWNLINK_INTERFERENCE_FLAG` TINYINT(1) DEFAULT NULL,
				`SERVING_MAINBEAM_OVERSHOOT` TINYINT(1) DEFAULT NULL,
				`BEST_MAINBEAM_OVERSHOOT` TINYINT(1) DEFAULT NULL,
				`BEST_LAC` MEDIUMINT(9) DEFAULT NULL,
				`BEST_BSC_ID` MEDIUMINT(9) DEFAULT NULL,
				`BEST_CLUSTER_ID` MEDIUMINT(9) DEFAULT NULL,
				`BEST_SITE_ID` VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL,
				`BEST_CELL_ID` MEDIUMINT(9) DEFAULT NULL,
				`BEST_CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL,
				`BEST_ARFCN` SMALLINT (6) UNSIGNED DEFAULT NULL,
				`BEST_FREQUENCY` VARCHAR(10) CHARACTER SET utf8 DEFAULT NULL,
				`BEST_RXLEV_FULL_DOWNLINK` FLOAT DEFAULT NULL,
				`MERGE_MR_REC_CNT` SMALLINT(6) DEFAULT NULL,
				`CAUSE` bigint(20) DEFAULT NULL,
				`METHOD` SMALLINT (6) UNSIGNED DEFAULT NULL,
				`DEVIATION_LEVEL` INT(11) DEFAULT NULL
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_call_gsm` (
				',TABLE_CALL_COL_STR,',
				KEY `CALL_ID` (`CALL_ID`),
				KEY `IMSI` (`IMSI`),
				KEY `IMEI` (`IMEI`),
				KEY `IX_FIRST_CELL` (`POS_FIRST_CELL_ID`),
				KEY `IX_LAST_CELL` (`POS_LAST_CELL_ID`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_call_gsm_dump` (
				',TABLE_CALL_COL_STR,'
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`opt_cf_report_gsm_d1` 
				(
				`SERVING_BSC` MEDIUMINT(9) NOT NULL, 
				`SERVING_LAC` MEDIUMINT(9) UNSIGNED NOT NULL, 
				`SITE_ID` VARCHAR(50) CHARACTER SET UTF8 NOT NULL, 
				`SITE_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				`CELL_ID_A` MEDIUMINT(9) UNSIGNED NOT NULL,
				`CELL_ID_B` MEDIUMINT(9) UNSIGNED NOT NULL,
				`CELL_A_AZIMUTH` DOUBLE NOT NULL,
				`CELL_B_AZIMUTH` DOUBLE NOT NULL,
				`CELL_A_AVG_ANGLE` DOUBLE NOT NULL,
				`CELL_B_AVG_ANGLE` DOUBLE NOT NULL,
				`SOURCE_CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				`TARGET_CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				`ANGLE_DIFF` DOUBLE NOT NULL,
				`AZIMUTH_DIFF` SMALLINT(6) NOT NULL,
				`EVENT_CNT_A` BIGINT(20) NOT NULL,
				`EVENT_CNT_B` BIGINT(20) NOT NULL,
				`SWAP_OF_A` DOUBLE DEFAULT 0,
				`SWAP_OF_B` DOUBLE DEFAULT 0,
				`BEAM_TILE_CNT_A` BIGINT(20) NOT NULL,
				`BEAM_TILE_CNT_B` BIGINT(20) NOT NULL,
				`CALL_CNT_A` BIGINT(20) NOT NULL,
				`CALL_CNT_B` BIGINT(20) NOT NULL
				,KEY `IX_NT_GSM` (`SERVING_BSC`,`SERVING_LAC`,`CELL_ID_A`,`CELL_ID_B`)
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1
				;');	
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd =CONCAT('CREATE TABLE ',GT_DB,'.opt_cf_report_gsm_d7 LIKE ',GT_DB,'.opt_cf_report_gsm_d1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`opt_nbr_result_gsm_d1` 
				(
				`DATA_DATE` DATE NULL, 
				`DATA_HOUR` TINYINT(4) NULL, 
				`SERVING_BSC` MEDIUMINT(9) NULL, 
				`SERVING_LAC` SMALLINT(5) UNSIGNED NULL, 
				`SERVING_CID` MEDIUMINT(9) NULL, 
				`SITE_ID` VARCHAR(20) CHARACTER SET UTF8 NULL, 
				`SOURCE_CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				`TARGET_CID` MEDIUMINT(9) NULL, 
				`TARGET_LAC` SMALLINT(5) UNSIGNED NULL, 
				`TARGET_BSC` MEDIUMINT(9) NULL, 
				`TARGET_CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				`EVENT_TYPE` TINYINT(4) NULL, 
				`NBR_TYPE` VARCHAR(10) NULL, 
				`LONGITUDE` DOUBLE NULL, 
				`LATITUDE` DOUBLE NULL, 
				`DISTANCE_METER` DOUBLE NULL, 
				`HO_ALL_CNT` SMALLINT(6) NULL, 
				`HO_SUCC_CNT` SMALLINT(6) NULL, 
				`HO_FAIL_CNT` SMALLINT(6) NULL, 
				`HO_DROP_CNT` SMALLINT(6) NULL, 
				`MEAS_RXLEV` DOUBLE NULL, 
				`MEAS_CNT` DOUBLE NULL, 
				`SERV_RXLEV` DOUBLE NULL, 
				`SERV_RXLEV_CNT` DOUBLE NULL, 
				`SERV_RXQUAL` DOUBLE NULL, 
				`SERV_RXQUAL_CNT` DOUBLE NULL, 
				`PRI_WEIGHTED` FLOAT DEFAULT NULL, 
				`RANK` MEDIUMINT(9) DEFAULT NULL, 
				`ACTION` VARCHAR(10) DEFAULT NULL, 
				`HEIGHT` DOUBLE DEFAULT NULL, 
				`PRI_HO` MEDIUMINT(9) DEFAULT NULL, 
				`PRI_MEAS` MEDIUMINT(9) DEFAULT NULL, 
				`PRI_RXLEV` MEDIUMINT(9) DEFAULT NULL, 
				`PRI_DISTANCE` DOUBLE DEFAULT NULL, 
				`PRI_ANG` DOUBLE DEFAULT NULL, 
				`AZIMUTH` DOUBLE DEFAULT NULL 
				,KEY `IX_NT_GSM` (`SERVING_BSC`,`SERVING_LAC`,`SERVING_CID`,`TARGET_BSC`,`TARGET_LAC`,`TARGET_CID`)
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1
				;');	
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd =CONCAT('CREATE TABLE ',GT_DB,'.opt_nbr_result_gsm_d7 LIKE ',GT_DB,'.opt_nbr_result_gsm_d1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`opt_nbr_relation_gsm` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` TINYINT(4) COMMENT ''KEY'',
				`SERVING_LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`SERVING_BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SERVING_CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`TARGET_LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`TARGET_BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`TARGET_CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`TARGET_ARFCN` MEDIUMINT(9) COMMENT ''TAG'',
				`TARGET_BSIC` SMALLINT(6) COMMENT ''TAG'',
				`SERVING_SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''TAG'',
				`SERVING_CELL_NAME` VARCHAR(50) CHARACTER SET utf8 COMMENT ''TAG'',
				`SERVING_FREQUENCY` SMALLINT(6) COMMENT ''TAG'',
				`SERVING_ARFCN` MEDIUMINT(9) COMMENT ''TAG'',
				`TARGET_SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''TAG'',
				`TARGET_CELL_NAME` VARCHAR(50) CHARACTER SET utf8 COMMENT ''TAG'',
				`TARGET_FREQUENCY` SMALLINT(6) COMMENT ''TAG'',
				',opt_nbr_relation_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,`DATA_HOUR`,`SERVING_LAC`,`SERVING_BSC_ID`,`SERVING_CELL_ID`,`TARGET_LAC`,`TARGET_BSC_ID`,`TARGET_CELL_ID`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`opt_nbr_relation_gsm_d1` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` tinyint(4) COMMENT ''KEY'',
				`SERVING_LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`SERVING_BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SERVING_CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`TARGET_LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`TARGET_BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`TARGET_CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`TARGET_ARFCN` MEDIUMINT(9) COMMENT ''TAG'',
				`TARGET_BSIC` SMALLINT(6) COMMENT ''TAG'',
				`SERVING_SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''TAG'',
				`SERVING_CELL_NAME` VARCHAR(50) CHARACTER SET utf8 COMMENT ''TAG'',
				`SERVING_FREQUENCY` SMALLINT(6) COMMENT ''TAG'',
				`SERVING_ARFCN` MEDIUMINT(9) COMMENT ''TAG'',
				`TARGET_SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''TAG'',
				`TARGET_CELL_NAME` VARCHAR(50) CHARACTER SET utf8 COMMENT ''TAG'',
				`TARGET_FREQUENCY` SMALLINT(6) COMMENT ''TAG'',
				',opt_nbr_relation_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,DATA_HOUR,`SERVING_LAC`,`SERVING_BSC_ID`,`SERVING_CELL_ID`,`TARGET_LAC`,`TARGET_BSC_ID`,`TARGET_CELL_ID`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`opt_nbr_relation_gsm_d7` (
				`DATA_DATE` DATE COMMENT ''KEY'',
				`DATA_HOUR` tinyint(4) COMMENT ''KEY'',
				`SERVING_LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`SERVING_BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`SERVING_CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`TARGET_LAC` MEDIUMINT(9) COMMENT ''KEY'',
				`TARGET_BSC_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`TARGET_CELL_ID` MEDIUMINT(9) COMMENT ''KEY'',
				`TARGET_ARFCN` MEDIUMINT(9) COMMENT ''TAG'',
				`TARGET_BSIC` SMALLINT(6) COMMENT ''TAG'',
				`SERVING_SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''TAG'',
				`SERVING_CELL_NAME` VARCHAR(50) CHARACTER SET utf8 COMMENT ''TAG'',
				`SERVING_FREQUENCY` SMALLINT(6) COMMENT ''TAG'',
				`SERVING_ARFCN` MEDIUMINT(9) COMMENT ''TAG'',
				`TARGET_SITE_ID` VARCHAR(20) CHARACTER SET utf8 COMMENT ''TAG'',
				`TARGET_CELL_NAME` VARCHAR(50) CHARACTER SET utf8 COMMENT ''TAG'',
				`TARGET_FREQUENCY` SMALLINT(6) COMMENT ''TAG'',
				',opt_nbr_relation_str,'
				KEY `PRIMARY KEY` (`DATA_DATE`,DATA_HOUR,`SERVING_LAC`,`SERVING_BSC_ID`,`SERVING_CELL_ID`,`TARGET_LAC`,`TARGET_BSC_ID`,`TARGET_CELL_ID`)
				)ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	IF CUSTOMER_USER_FLAG = 'true' THEN
		SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_call_gsm_imsig` (
					',TABLE_CALL_COL_STR,',
					KEY `CALL_ID` (`CALL_ID`),
					KEY `IMSI` (`IMSI`),
					KEY `IMEI` (`IMEI`),
					KEY `IX_FIRST_CELL` (`POS_FIRST_CELL_ID`),
					KEY `IX_LAST_CELL` (`POS_LAST_CELL_ID`)
					) ENGINE=MyISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1;');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
		
		SET @SqlCmd =CONCAT('CREATE TABLE IF NOT EXISTS ',GT_DB,'.table_position_gsm_imsig LIKE ',GT_DB,'.table_position_gsm;');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;	
	END IF;
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_overshooting_severity_gsm_d1` 
				 (
					DATA_DATE DATE DEFAULT NULL,
					LAC MEDIUMINT(9) DEFAULT NULL,
					BSC_ID MEDIUMINT(9) DEFAULT NULL,
					CLUSTER_ID MEDIUMINT(9) DEFAULT NULL,
					SITE_ID VARCHAR(20) DEFAULT NULL,
					CELL_ID MEDIUMINT(9) DEFAULT NULL,
					FREQUENCY SMALLINT(6) DEFAULT NULL,
					ARFCN MEDIUMINT(9) DEFAULT NULL,
					CELL_NAME VARCHAR(50) DEFAULT NULL,
					ANTENNA_RADIUS FLOAT DEFAULT NULL,
					CLOSED_RADIUS FLOAT DEFAULT NULL,
					T1_CALL_CNT DOUBLE DEFAULT NULL,
					T0_CALL_CNT DOUBLE DEFAULT NULL,
					OVER_DISTANCE_SUM DOUBLE DEFAULT NULL,
					OVER_DISTANCE_MAX DOUBLE DEFAULT NULL,
					T0_TILE_CNT MEDIUMINT(9) DEFAULT NULL,
					T1_TILE_CNT BIGINT(20) DEFAULT NULL,
					KEY `IX_GT_CELL` (`CELL_ID`,`BSC_ID`)
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`table_overshooting_severity_event_gsm_d1` (
					DATA_DATE DATE DEFAULT NULL,
					LAC MEDIUMINT(9) DEFAULT NULL,
					BSC_ID MEDIUMINT(9) DEFAULT NULL,
					CLUSTER_ID MEDIUMINT(9) DEFAULT NULL,
					SITE_ID VARCHAR(20) DEFAULT NULL,
					CELL_ID MEDIUMINT(9) DEFAULT NULL,
					FREQUENCY SMALLINT(6) DEFAULT NULL,
					ARFCN MEDIUMINT(9) DEFAULT NULL,
					CELL_NAME VARCHAR(50) DEFAULT NULL,
					ANTENNA_RADIUS FLOAT DEFAULT NULL,
					CLOSED_RADIUS FLOAT DEFAULT NULL,
					SERVING_T1_EVENT_CNT MEDIUMINT(9) DEFAULT NULL,
					SERVING_T0_EVENT_CNT MEDIUMINT(9) DEFAULT NULL,
					SERVING_T1_TILE_CNT MEDIUMINT(9) DEFAULT NULL,
					SERVING_T0_TILE_CNT MEDIUMINT(9) DEFAULT NULL,
					SERVING_OVER_DISTANCE_MAX FLOAT(9,2) DEFAULT NULL,
					SERVING_OVER_DISTANCE_AVG FLOAT(9,2) DEFAULT NULL,
					BEST_T1_EVENT_CNT MEDIUMINT(9) DEFAULT NULL,
					BEST_T0_EVENT_CNT MEDIUMINT(9) DEFAULT NULL,
					BEST_T1_TILE_CNT MEDIUMINT(9) DEFAULT NULL,
					BEST_T0_TILE_CNT MEDIUMINT(9) DEFAULT NULL,
					BEST_OVER_DISTANCE_MAX FLOAT DEFAULT NULL,
					BEST_OVER_DISTANCE_AVG FLOAT DEFAULT NULL,
					SERVING_MAINBEAM_T1_EVENT_CNT MEDIUMINT(9) DEFAULT NULL,
					SERVING_MAINBEAM_T0_EVENT_CNT MEDIUMINT(9) DEFAULT NULL,
					SERVING_MAINBEAM_OVER_DISTANCE_MAX FLOAT(9,2) DEFAULT NULL,
					SERVING_MAINBEAM_OVER_DISTANCE_AVG FLOAT(9,2) DEFAULT NULL,
					BEST_MAINBEAM_T1_EVENT_CNT MEDIUMINT(9) DEFAULT NULL,
					BEST_MAINBEAM_T0_EVENT_CNT MEDIUMINT(9) DEFAULT NULL,
					BEST_MAINBEAM_OVER_DISTANCE_MAX FLOAT(9,2) DEFAULT NULL,
					BEST_MAINBEAM_OVER_DISTANCE_AVG FLOAT(9,2) DEFAULT NULL,
					KEY `IX_GT_CELL` (`CELL_ID`,`BSC_ID`)
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');					
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.table_roamer_call_gsm LIKE ',GT_DB,'.table_call_gsm;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
END$$
DELIMITER ;
