DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_CreateDB_NT_Schema_LTE`(IN GT_DB VARCHAR(100))
BEGIN
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_pu_current`
				(
				`PU_ID` MEDIUMINT(9) DEFAULT NULL,
				`PU_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				`MCC` VARCHAR(3) DEFAULT NULL,
				`MNC` VARCHAR(3) DEFAULT NULL,
				`TECH_MASK` TINYINT(4) DEFAULT NULL,
				`VEDNOR` VARCHAR(30) DEFAULT NULL,
				`SITE_CNT` SMALLINT(6) DEFAULT NULL,
				`CELL_CNT` SMALLINT(6) DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;
				');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_cell_lte`
				(
				`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
				`ENODEB_NAME` VARCHAR(50) CHARACTER SET UTF8  DEFAULT NULL,
				`ENODEB_LOC_ID` VARCHAR(20) DEFAULT NULL,
				`ENODEB_NE_ID` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
				`ENODEB_OSS_NODE_ID` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
				`CELL_ID` TINYINT(4) DEFAULT NULL,
				`CELL_NAME` VARCHAR(125) CHARACTER SET UTF8 DEFAULT NULL,
				`CELL_LOC_ID` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
				`CELL_NE_ID` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
				`CELL_OSS_NODE_ID` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,	
				`EUTRABAND` MEDIUMINT(9) DEFAULT NULL,
				`PCI` SMALLINT(6) DEFAULT NULL,
				`BWCHANNEL` DECIMAL(6,3) DEFAULT NULL,
				`DL_EARFCN` MEDIUMINT(9) DEFAULT NULL,
				`UL_EARFCN` MEDIUMINT(9) DEFAULT NULL,
				`ENODEB_TYPE` VARCHAR(50)  DEFAULT NULL,
				`ENODEB_VENDOR` VARCHAR(50)  DEFAULT NULL,
				`INDOOR` TINYINT(4) DEFAULT NULL,
				`IP` VARCHAR(100) DEFAULT NULL,
				`CLUSTER_NAME_REGION` VARCHAR(100) CHARACTER SET UTF8  DEFAULT NULL,
				`CLUSTER_NAME_SUB_REGION` VARCHAR(100) CHARACTER SET UTF8  DEFAULT NULL,
				`CLUSTER_NAME_STRUCTURE_TYPE` VARCHAR(100) CHARACTER SET UTF8  DEFAULT NULL,
				`ACT_START` DATE DEFAULT NULL,
				`ACT_END` DATE DEFAULT NULL,
				`PLAN_START` DATE DEFAULT NULL,
				`PLAN_END` DATE DEFAULT NULL,
				`ACT_STATE` VARCHAR(50) DEFAULT NULL,
				`ENODEB_MODEL` VARCHAR(100) DEFAULT NULL,
				`CLUSTER_NAME_ZONE` VARCHAR(100) CHARACTER SET UTF8 DEFAULT NULL,
				`CELL_RADIUS` MEDIUMINT(9) DEFAULT NULL,
				`AMDINSTATE_LOCKED` TINYINT(4) DEFAULT NULL,
				`OPERSTATE_ENABLE` TINYINT(4) DEFAULT NULL,
				`REGION_ID` MEDIUMINT(9) DEFAULT NULL,
				`SUB_REGION_ID` MEDIUMINT(9) DEFAULT NULL,
				`NBR_DISTANCE_4G_CM` DOUBLE  DEFAULT NULL, 
				`NBR_DISTANCE_4G_VORONOI` DOUBLE  DEFAULT NULL,
				`PU_ID` MEDIUMINT(9) DEFAULT NULL,
				`SITE_DENSITY_TYPE` TINYINT(4) DEFAULT NULL,
				`RACH_ROOT_SEQUENCE` MEDIUMINT(9) DEFAULT NULL, 
				`FLAG` SMALLINT(6) DEFAULT NULL,
				`SERVING_AREA` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
				KEY `NT_CELL_LTE_IDX1` (`ENODEB_ID`,`CELL_ID`)
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 				
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_cell_current_lte`
				(
				`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
				`ENODEB_NAME` VARCHAR(50) CHARACTER SET UTF8  DEFAULT NULL,
				`ENODEB_LOC_ID` VARCHAR(20) DEFAULT NULL,
				`ENODEB_NE_ID` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
				`ENODEB_OSS_NODE_ID` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
				`CELL_ID` TINYINT(4) DEFAULT NULL,
				`CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				`CELL_LOC_ID` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
				`CELL_NE_ID` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
				`CELL_OSS_NODE_ID` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,	
				`EUTRABAND` MEDIUMINT(9) DEFAULT NULL,
				`PCI` SMALLINT(6) DEFAULT NULL,
				`BWCHANNEL` DECIMAL(6,3) DEFAULT NULL,
				`DL_EARFCN` MEDIUMINT(9) DEFAULT NULL,
				`UL_EARFCN` MEDIUMINT(9) DEFAULT NULL,
				`ENODEB_TYPE` VARCHAR(50)  DEFAULT NULL,
				`ENODEB_VENDOR` VARCHAR(50)  DEFAULT NULL,
				`INDOOR` TINYINT(4) DEFAULT NULL,
				`IP` VARCHAR(100) DEFAULT NULL,
				`CLUSTER_NAME_REGION` VARCHAR(100) CHARACTER SET UTF8  DEFAULT NULL,
				`CLUSTER_NAME_SUB_REGION` VARCHAR(100) CHARACTER SET UTF8  DEFAULT NULL,
				`CLUSTER_NAME_STRUCTURE_TYPE` VARCHAR(100) CHARACTER SET UTF8  DEFAULT NULL,
				`ACT_START` DATE DEFAULT NULL,
				`ACT_END` DATE DEFAULT NULL,
				`PLAN_START` DATE DEFAULT NULL,
				`PLAN_END` DATE DEFAULT NULL,
				`ACT_STATE` VARCHAR(50) DEFAULT NULL,
				`ENODEB_MODEL` VARCHAR(100) DEFAULT NULL,
				`CLUSTER_NAME_ZONE` VARCHAR(100) CHARACTER SET UTF8 DEFAULT NULL,
				`CELL_RADIUS` MEDIUMINT(9) DEFAULT NULL,
				`AMDINSTATE_LOCKED` TINYINT(4) DEFAULT NULL,
				`OPERSTATE_ENABLE` TINYINT(4) DEFAULT NULL,
				`REGION_ID` MEDIUMINT(9) DEFAULT NULL,
				`SUB_REGION_ID` MEDIUMINT(9) DEFAULT NULL,
				`NBR_DISTANCE_4G_CM` DOUBLE  DEFAULT NULL, 
				`NBR_DISTANCE_4G_VORONOI` DOUBLE  DEFAULT NULL,
				`PU_ID` MEDIUMINT(9) DEFAULT NULL,			  		 
				`SITE_DENSITY_TYPE` TINYINT(4) DEFAULT NULL,
				`RACH_ROOT_SEQUENCE` MEDIUMINT(9) DEFAULT NULL,
				`FLAG` SMALLINT(6) DEFAULT NULL,
				`SERVING_AREA` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
				KEY `NT_CELL_CURRENT_LTE_IDX1` (`ENODEB_ID`,`CELL_ID`)
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_tac_cell_lte`
				(
				`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
				`CELL_ID` TINYINT(4) DEFAULT NULL,
				`TAC` MEDIUMINT(9) DEFAULT NULL,
				`TAC_TYPE` TINYINT(4) DEFAULT ''0'',
				KEY TAC_CELL_LTE_IDX (ENODEB_ID, CELL_ID) 
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_tac_cell_current_lte`
				(
				`ENODEB_ID`MEDIUMINT(9) DEFAULT NULL,			
				`CELL_ID` TINYINT(4) DEFAULT NULL,
				`TAC` MEDIUMINT(9) DEFAULT NULL,
				`TAC_TYPE` TINYINT(4) DEFAULT ''0'',
				KEY IX_CELL_ID (ENODEB_ID, CELL_ID,TAC) 
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_antenna_lte`
				(
				`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
				`CELL_ID` TINYINT(4) DEFAULT NULL,
				`LONGITUDE` DOUBLE DEFAULT NULL,
				`LATITUDE` DOUBLE DEFAULT NULL,
				`AZIMUTH` SMALLINT(6) DEFAULT NULL,
				`ANTENNA_TYPE` TINYINT(4) DEFAULT NULL,
				`REPEATER` TINYINT(4) DEFAULT NULL,
				`REPEATER_TYPE` VARCHAR(20) DEFAULT NULL,
				`REPEATER_TA_DELAY` MEDIUMINT(9) DEFAULT NULL,	  
				`ANTENNA_MODEL` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				`ANTENNA_HEIGHT` DOUBLE DEFAULT NULL,
				`ANTENNA_GAIN` DOUBLE DEFAULT NULL,
				`BEAM_WIDTH_HORIZONTAL` DOUBLE DEFAULT NULL,
				`BEAM_WIDTH_VERTICAL` DOUBLE DEFAULT NULL,
				`DOWN_TILT_MECHANICAL` DOUBLE DEFAULT NULL,
				`DOWN_TILT_ELECTRICAL` DOUBLE DEFAULT NULL,
				`FEEDER_ATTEN` DOUBLE DEFAULT NULL,
				`REFERENCE_SIGNAL_POWER` DOUBLE DEFAULT NULL,
				`ELEVATION` DOUBLE DEFAULT NULL,
				`INDOOR_TYPE` TINYINT(4) DEFAULT NULL,
				`ANTENNA_ID` TINYINT(4) DEFAULT ''1'',
				`PATHLOSS_DISTANCE` FLOAT DEFAULT NULL,
				`ANTENNA_RADIUS` FLOAT DEFAULT NULL,
				`CLOSED_RADIUS` FLOAT DEFAULT NULL,
				`FLAG` SMALLINT(6) DEFAULT NULL,
				KEY `ID_KEY` (`ENODEB_ID`,`CELL_ID`)
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_antenna_current_lte`
				(
				`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
				`CELL_ID` TINYINT(4) DEFAULT NULL,
				`LONGITUDE` DOUBLE DEFAULT NULL,
				`LATITUDE` DOUBLE DEFAULT NULL,
				`AZIMUTH` SMALLINT(6) DEFAULT NULL,
				`ANTENNA_TYPE` TINYINT(4) DEFAULT NULL,
				`REPEATER` TINYINT(4) DEFAULT NULL,
				`REPEATER_TYPE` VARCHAR(20) DEFAULT NULL,
				`REPEATER_TA_DELAY` SMALLINT(6) DEFAULT NULL,	  
				`ANTENNA_MODEL` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				`ANTENNA_HEIGHT` DOUBLE DEFAULT NULL,
				`ANTENNA_GAIN` DOUBLE DEFAULT NULL,
				`BEAM_WIDTH_HORIZONTAL` DOUBLE DEFAULT NULL,
				`BEAM_WIDTH_VERTICAL` DOUBLE DEFAULT NULL,
				`DOWN_TILT_MECHANICAL` DOUBLE DEFAULT NULL,
				`DOWN_TILT_ELECTRICAL` DOUBLE DEFAULT NULL,
				`FEEDER_ATTEN` DOUBLE DEFAULT NULL,
				`REFERENCE_SIGNAL_POWER` DOUBLE DEFAULT NULL,
				`ELEVATION` DOUBLE DEFAULT NULL,
				`INDOOR_TYPE` TINYINT(4) DEFAULT NULL,
				`ANTENNA_ID` TINYINT(4) DEFAULT ''1'',
				`PATHLOSS_DISTANCE` FLOAT DEFAULT NULL,
				`ANTENNA_RADIUS` FLOAT DEFAULT NULL,
				`CLOSED_RADIUS` FLOAT DEFAULT NULL,
				`FLAG` SMALLINT(6) DEFAULT NULL,
				KEY `NT_ANTENNA_CURRENT_LTE_IDX1` (`ENODEB_ID`,`CELL_ID`)
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_mme_lte`
				(
				`MME_ID` BIGINT(20) DEFAULT NULL,
				`MME_NAME` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
				`MME_NE_ID` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
				`S_GW_ID` MEDIUMINT(9) DEFAULT NULL,
				`S_GW_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				`USER_LABEL` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				`MCC` VARCHAR(3) DEFAULT NULL,
				`MNC` VARCHAR(2) DEFAULT NULL,
				`VENDOR` VARCHAR(50) DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_mme_current_lte`
				(
				`MME_ID` BIGINT(20) DEFAULT NULL,
				`MME_NAME` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
				`MME_NE_ID` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
				`S_GW_ID` MEDIUMINT(9) DEFAULT NULL,
				`S_GW_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				`USER_LABEL` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				`MCC` VARCHAR(3) DEFAULT NULL,
				`MNC` VARCHAR(2) DEFAULT NULL,
				`VENDOR` VARCHAR(50) DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_nbr_4_2_lte`
				(
				`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
				`CELL_ID` TINYINT(4) DEFAULT NULL,
				`NBR_BSC_ID` MEDIUMINT(9) DEFAULT NULL,
				`NBR_CELL_ID` TINYINT(4) DEFAULT NULL,
				`PRIORITY` TINYINT(4) DEFAULT NULL,
				`ARFCN` MEDIUMINT(9) DEFAULT NULL,
				`BCC` MEDIUMINT(9) DEFAULT NULL,
				`NCC` MEDIUMINT(9) DEFAULT NULL,
				`LAC` MEDIUMINT(9) DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_nbr_4_2_current_lte`
				(
				`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
				`CELL_ID` TINYINT(4) DEFAULT NULL,
				`NBR_BSC_ID` MEDIUMINT(9) DEFAULT NULL,
				`NBR_CELL_ID` TINYINT(4) DEFAULT NULL,
				`PRIORITY` TINYINT(4) DEFAULT NULL,
				`ARFCN` MEDIUMINT(9) DEFAULT NULL,
				`BCC` MEDIUMINT(9) DEFAULT NULL,
				`NCC` MEDIUMINT(9) DEFAULT NULL,
				`LAC` MEDIUMINT(9) DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_nbr_4_3_lte`
				(
				`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
				`CELL_ID` TINYINT(4) DEFAULT NULL,
				`NBR_RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				`NBR_CELL_ID` MEDIUMINT(9) DEFAULT NULL,
				`PRIORITY` TINYINT(4) DEFAULT NULL,
				`PSC` SMALLINT(6) DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_nbr_4_3_current_lte`
				(
				`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
				`CELL_ID` TINYINT(4) DEFAULT NULL,
				`NBR_RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				`NBR_CELL_ID` MEDIUMINT(9) DEFAULT NULL,
				`PRIORITY` TINYINT(4) DEFAULT NULL,
				`PSC` SMALLINT(6) DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	 
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_nbr_4_4_lte`
				(
				`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
				`CELL_ID` TINYINT(4) DEFAULT NULL,
				`NBR_ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
				`NBR_CELL_ID` TINYINT(4) DEFAULT NULL,
				`PRIORITY` TINYINT(4) DEFAULT NULL,
				`NBR_TYPE` SMALLINT(6) DEFAULT NULL,
				`NBR_DISTANCE` DOUBLE DEFAULT NULL,
				`NBR_ANGLE` MEDIUMINT(9) DEFAULT NULL,
				`NBR_AZIMUTH_ANGLE` MEDIUMINT(9) DEFAULT NULL,
				KEY `NT_NBR_4_4_LTE_IDX1` (`ENODEB_ID`, `CELL_ID`, `NBR_ENODEB_ID`, `NBR_CELL_ID`),
				KEY `NT_NBR_4_4_LTE_IDX2` (`NBR_ENODEB_ID`,`NBR_CELL_ID`)
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_nbr_4_4_current_lte`
				(
				`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
				`CELL_ID` TINYINT(4) DEFAULT NULL,
				`NBR_ENODEB_ID` VARCHAR(20) DEFAULT NULL,
				`NBR_CELL_ID` TINYINT(4) DEFAULT NULL,
				`PRIORITY` TINYINT(4) DEFAULT NULL,
				`NBR_TYPE` SMALLINT(6) DEFAULT NULL,
				`NBR_DISTANCE` DOUBLE DEFAULT NULL,
				`NBR_ANGLE` MEDIUMINT(9) DEFAULT NULL,
				`NBR_AZIMUTH_ANGLE` MEDIUMINT(9) DEFAULT NULL,
				KEY `NT_NBR_4_4_CURRENT_LTE_IDX1` (`ENODEB_ID`,`CELL_ID`, `NBR_ENODEB_ID`, `NBR_CELL_ID`),
				KEY `NT_NBR_4_4_CURRENT_LTE_IDX2` (`NBR_ENODEB_ID`,`NBR_CELL_ID`)
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_neighbor_voronoi_lte`
				(
				`ENODEB_ID` VARCHAR(20) DEFAULT NULL,
				`NBR_ENODEB_ID` VARCHAR(20) DEFAULT NULL,
				`ANGLE` DOUBLE DEFAULT NULL,
				`DISTANCE` DOUBLE DEFAULT NULL,
				`INDOOR_TYPE` TINYINT(4) DEFAULT NULL,
				`SITEDENSITY_RANGE` INT(11) DEFAULT NULL,
				`REFINE_DISTANCE` FLOAT DEFAULT NULL,
				KEY `ENODEB_ID_IDX` (`ENODEB_ID`,`NBR_ENODEB_ID`)			   
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`RULE_NT_NBR_ENODEB_LTE`
				(
				`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
				`BL_MCC_TRAGET` VARCHAR(3) DEFAULT NULL,
				`BL_MNC_TARGET` VARCHAR(3) DEFAULT NULL,
				`BL_ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
				`BL_TYPE` VARCHAR(20) DEFAULT NULL,
				KEY `NT_NBR_LTE_BLACKLIST_IDX1` (ENODEB_ID,`BL_ENODEB_ID`)
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`RULE_NT_NBR_CELL_PCI_LTE`
				(
				`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
				`CELL_ID` TINYINT(4) DEFAULT NULL,
				`BL_FREQ_EARFCN` MEDIUMINT(9) DEFAULT NULL,
				`BL_PCI` SMALLINT(6) DEFAULT NULL,
				KEY `NT_NBR_CELL_BLACKLIST_PCI_IDX1` (ENODEB_ID,`CELL_ID`)
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`OPT_PCI_RESULT` 
				(
				  `PU_ID` MEDIUMINT(9) DEFAULT NULL,
				  `ENODEB_ID` MEDIUMINT(9) NOT NULL,
				  `CELL_ID` SMALLINT(6) NOT NULL,
				  `CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `LONGITUDE` DOUBLE NOT NULL,
				  `LATITUDE` DOUBLE NOT NULL,
				  `PCI` INT(11) NOT NULL,
				  `NBR_PU_ID` MEDIUMINT(9) DEFAULT NULL,
				  `NBR_ENODEB_ID` MEDIUMINT(9) NOT NULL,
				  `NBR_CELL_ID` SMALLINT(6) NOT NULL,
				  `NBR_CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `DISTANCE` DOUBLE DEFAULT NULL,
				  `DEPTH` MEDIUMINT(9) DEFAULT NULL,
				  `DEPTH_1_ENODEB` MEDIUMINT(9) DEFAULT NULL,
				  `DEPTH_1_CELL` SMALLINT(6) DEFAULT NULL,
				  `DEPTH_2_ENODEB` MEDIUMINT(9) DEFAULT NULL,
				  `DEPTH_2_CELL` SMALLINT(6) DEFAULT NULL,
				  UNIQUE KEY `ENODEB_ID` (`ENODEB_ID`,`CELL_ID`,`NBR_ENODEB_ID`,`NBR_CELL_ID`)
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`OPT_PCI_SUGGEST` 
				(
				  `PU_ID` MEDIUMINT(9) DEFAULT NULL,
				  `ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
				  `CELL_ID` SMALLINT(6) DEFAULT NULL,
				  `CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `NBR_PU_ID` MEDIUMINT(9) DEFAULT NULL,
				  `NBR_ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
				  `NBR_CELL_ID` SMALLINT(6) DEFAULT NULL,
				  `NBR_CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `PCI_SUGGEST` INT(11) DEFAULT NULL,
				  `DISTANCE` FLOAT(9,2) DEFAULT NULL,
				  `PCI_ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
				  `PCI_CELL_ID` SMALLINT(6) DEFAULT NULL,
				  `PCI_CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;	
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`cell_pu_mapping`
				(		
				  `DATA_DATE` DATE NOT NULL,
				  `DATA_HOUR` TINYINT(4) NOT NULL,
				  `PU_ID` MEDIUMINT(9) NOT NULL,
				  `ENODEB_ID` MEDIUMINT(9) NOT NULL,
				  `CELL_ID` MEDIUMINT(9) NOT NULL,
				  KEY `CELL_PU_MAPPING_ID` (`ENODEB_ID`,`PU_ID`,`CELL_ID`)	   
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`Opt_rsi_result`
				(
					`PU_ID` MEDIUMINT(9) NOT NULL,
					`ENODEB_ID` MEDIUMINT(9)  NOT NULL,
					`CELL_ID` SMALLINT(6) NOT NULL,
					`CELL_NAME` VARCHAR(50) DEFAULT NULL,
					`INDOOR` TINYINT(4) DEFAULT NULL,
					`RSI` SMALLINT(6) NOT NULL,
					`SOFT_CONFLICT` TINYINT(4) DEFAULT NULL,
					`DEPTH` TINYINT(4) DEFAULT NULL,
					`DISTANCE` DOUBLE DEFAULT NULL,
					`NBR_PU_ID` MEDIUMINT(9) DEFAULT NULL,
					`NBR_ENODEB_ID` MEDIUMINT(9) NOT NULL,
					`NBR_CELL_ID` SMALLINT(6) NOT NULL,
					`NBR_CELL_NAME` VARCHAR(50) DEFAULT NULL,
					`NBR_INDOOR` TINYINT(4) DEFAULT NULL,
					`COLLISION_RSI` SMALLINT(6) DEFAULT NULL,
					`RSI_SUGGEST_1` SMALLINT(6) DEFAULT NULL,
					`RSI_SUGGEST_2` SMALLINT(6) DEFAULT NULL,
					`BREAK_RULE` TINYINT(4) NOT NULL DEFAULT ''0'',
					PRIMARY KEY (ENODEB_ID,CELL_ID,NBR_ENODEB_ID,NBR_CELL_ID)
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	CALL gt_gw_main.SP_CreateDB_NT_Schema_Sub(GT_DB);
END$$
DELIMITER ;
