DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_CreateDB_NT_Schema`(IN GT_DB VARCHAR(100))
BEGIN
	DECLARE extarTables VARCHAR(50);
	SELECT LOWER(`value`) INTO extarTables  FROM gt_gw_main.integration_param WHERE gt_group = 'ntparser' AND gt_name = 'extraTables' ;
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_antenna`
				 (
				  `NT_DATE` DATETIME DEFAULT NULL,
				  `RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				  `CELL_ID` MEDIUMINT(9) DEFAULT NULL,
				  `CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `LONGITUDE` DOUBLE DEFAULT NULL,
				  `LATITUDE` DOUBLE DEFAULT NULL,
				  `AZIMUTH` SMALLINT(6) DEFAULT NULL,
				  `ANTENNA_MODEL` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `ANTENNA_TYPE` TINYINT(4) DEFAULT NULL,
				  `HEIGHT` DOUBLE DEFAULT NULL,
				  `BEAMWIDTH_H` DOUBLE DEFAULT NULL,
				  `BEAMWIDTH_V` DOUBLE DEFAULT NULL,
				  `CPICH_POWER` DOUBLE DEFAULT NULL,
				  `EIRP` DOUBLE DEFAULT NULL,
				  `ANTENNA_GAIN` DOUBLE DEFAULT NULL,
				  `FEEDER_LOSS` DOUBLE DEFAULT NULL,
				  `DOWNTILT_EL` DOUBLE DEFAULT NULL,
				  `DOWNTILT_MEC` DOUBLE DEFAULT NULL,
				  `ELEVATION` DOUBLE DEFAULT NULL,
				  `INDOOR_TYPE` TINYINT(4) DEFAULT 0,
				  `REPEATER_TYPE` VARCHAR(20) DEFAULT NULL,
				  `REPEATER_PG_DELAY` SMALLINT(6) DEFAULT NULL,
				  `ANTENNA_ID` TINYINT(4) DEFAULT 1,
				  `PATHLOSS_DISTANCE` FLOAT DEFAULT NULL,
				  `ANTENNA_RADIUS` FLOAT DEFAULT NULL,
				  `CLOSED_RADIUS` FLOAT DEFAULT NULL,
				  `FLAG` SMALLINT(6) DEFAULT NULL,
				  KEY `ID_KEY` (`RNC_ID`,`CELL_ID`)
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_antenna_current`
				(					
				  `NT_DATE` DATETIME DEFAULT NULL,
				  `RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				  `CELL_ID` MEDIUMINT(9) DEFAULT NULL,
				  `CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `LONGITUDE` DOUBLE DEFAULT NULL,
				  `LATITUDE` DOUBLE DEFAULT NULL,
				  `AZIMUTH` SMALLINT(6) DEFAULT NULL,
				  `ANTENNA_MODEL` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `ANTENNA_TYPE` TINYINT(4) DEFAULT NULL,
				  `HEIGHT` DOUBLE DEFAULT NULL,
				  `BEAMWIDTH_H` DOUBLE DEFAULT NULL,
				  `BEAMWIDTH_V` DOUBLE DEFAULT NULL,
				  `CPICH_POWER` DOUBLE DEFAULT NULL,
				  `EIRP` DOUBLE DEFAULT NULL,
				  `ANTENNA_GAIN` DOUBLE DEFAULT NULL,
				  `FEEDER_LOSS` DOUBLE DEFAULT NULL,
				  `DOWNTILT_EL` DOUBLE DEFAULT NULL,
				  `DOWNTILT_MEC` DOUBLE DEFAULT NULL,
				  `ELEVATION` DOUBLE DEFAULT NULL,
				  `INDOOR_TYPE` TINYINT(4) DEFAULT 0,
				  `REPEATER_TYPE` VARCHAR(20) DEFAULT NULL,
				  `REPEATER_PG_DELAY` SMALLINT(6) DEFAULT NULL,
				  `ANTENNA_ID` TINYINT(4) DEFAULT 1,
				  `PATHLOSS_DISTANCE` FLOAT DEFAULT NULL,
				  `ANTENNA_RADIUS` FLOAT DEFAULT NULL,
				  `CLOSED_RADIUS` FLOAT DEFAULT NULL,
				  `FLAG` SMALLINT(6) DEFAULT NULL,
				   KEY `RNC_ID` (`RNC_ID`,`CELL_ID`),
				   KEY `ANTENNA_MODEL`( `ANTENNA_MODEL`)
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_cell`
				 (
				  `NT_DATE` DATETIME DEFAULT NULL,
				  `RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				  `SITE_ID` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `SITE_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `LAC` MEDIUMINT(9) UNSIGNED DEFAULT NULL,
				  `RAC` SMALLINT(6) UNSIGNED DEFAULT NULL,
				  `CELL_ID` MEDIUMINT(9) DEFAULT NULL,
				  `CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `SCRAMBLING_CODE` SMALLINT(6) DEFAULT NULL,
				  `FREQUENCY` SMALLINT(6) DEFAULT NULL,
				  `DL_UARFCN` MEDIUMINT(9) DEFAULT NULL,
				  `LONGITUDE` DOUBLE DEFAULT NULL,
				  `LATITUDE` DOUBLE DEFAULT NULL,
				  `INDOOR` TINYINT(4) DEFAULT NULL,
				  `SITE_TYPE` TINYINT(4) DEFAULT NULL,
				  `ACTIVE_STATUS` VARCHAR(30) DEFAULT NULL,
				  `HSUPA_ACT` VARCHAR(50) DEFAULT NULL,
				  `HSUDPA_ACT` VARCHAR(50) DEFAULT NULL,
				  `CLUSTER_NAME` VARCHAR(100) CHARACTER SET UTF8 DEFAULT NULL,
				  `CLUSTER_NAME_REGION` VARCHAR(100) CHARACTER SET UTF8  DEFAULT NULL,
				  `CLUSTER_NAME_SUB_REGION` VARCHAR(100) CHARACTER SET UTF8  DEFAULT NULL,
				  `CLUSTER_NAME_ZONE` VARCHAR(100) CHARACTER SET UTF8 DEFAULT NULL,
				  `LOCAL_SITE_ID` MEDIUMINT(9) DEFAULT NULL,
				  `LOCAL_SITE_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `NUMHSCODE` SMALLINT(6) DEFAULT NULL,
				  `ADMINSTATE_LOCKED` TINYINT(4) DEFAULT NULL,
				  `OPERSTATE_ENABLE` TINYINT(4) DEFAULT NULL,
				  `WCEL_INDEX` MEDIUMINT(9) DEFAULT NULL,
				  `CLUSTER_ID` MEDIUMINT(9) DEFAULT NULL,
				  `INAFREQ_NBCNT` TINYINT(4) UNSIGNED DEFAULT NULL,
				  `INTFREQ_NBCNT` TINYINT(4) UNSIGNED DEFAULT NULL,
				  `GSM_NBCNT` TINYINT(4) UNSIGNED DEFAULT NULL,
				  `NB_AVG_DISTANCE_VORONOI` DOUBLE DEFAULT NULL,
				  `NB_AVG_DISTANCE_UMTS` DOUBLE DEFAULT NULL,
				  `SITE_DENSITY_TYPE` TINYINT(4) DEFAULT NULL,
				  `FLAG` SMALLINT(6) DEFAULT NULL,
				  `SERVING_AREA` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_current`
				 (
				  `NT_DATE` DATETIME DEFAULT NULL,
				  `RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				  `SITE_ID` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
				  `SITE_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `LAC` MEDIUMINT(9) UNSIGNED DEFAULT NULL,
				  `RAC` SMALLINT(6) UNSIGNED DEFAULT NULL,
				  `CELL_ID` MEDIUMINT(9) DEFAULT NULL,
				  `CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `SCRAMBLING_CODE` SMALLINT(6) DEFAULT NULL,
				  `FREQUENCY` SMALLINT(6) DEFAULT NULL,
				  `DL_UARFCN` MEDIUMINT(9) DEFAULT NULL,
				  `LONGITUDE` DOUBLE DEFAULT NULL,
				  `LATITUDE` DOUBLE DEFAULT NULL,
				  `INDOOR` TINYINT(4) DEFAULT NULL,
				  `SITE_TYPE` TINYINT(4) DEFAULT NULL,
				  `ACTIVE_STATUS` VARCHAR(30) DEFAULT NULL,
				  `HSUPA_ACT` VARCHAR(50) DEFAULT NULL,
				  `HSUDPA_ACT` VARCHAR(50) DEFAULT NULL,
				  `CLUSTER_NAME` VARCHAR(100) CHARACTER SET UTF8 DEFAULT NULL,
				  `CLUSTER_NAME_REGION` VARCHAR(100) CHARACTER SET UTF8  DEFAULT NULL,
				  `CLUSTER_NAME_SUB_REGION` VARCHAR(100) CHARACTER SET UTF8  DEFAULT NULL,
				  `CLUSTER_NAME_ZONE` VARCHAR(100) CHARACTER SET UTF8 DEFAULT NULL,
				  `LOCAL_SITE_ID` MEDIUMINT(9) DEFAULT NULL,
				  `LOCAL_SITE_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `NUMHSCODE` SMALLINT(6) DEFAULT NULL,
				  `ADMINSTATE_LOCKED` TINYINT(4) DEFAULT NULL,
				  `OPERSTATE_ENABLE` TINYINT(4) DEFAULT NULL,
				  `WCEL_INDEX` MEDIUMINT(9) DEFAULT NULL,
				  `CLUSTER_ID` MEDIUMINT(9) DEFAULT NULL,
				  `INAFREQ_NBCNT` TINYINT(4) UNSIGNED DEFAULT NULL,
				  `INTFREQ_NBCNT` TINYINT(4) UNSIGNED DEFAULT NULL,
				  `GSM_NBCNT` TINYINT(4) UNSIGNED DEFAULT NULL,
				  `NB_AVG_DISTANCE_VORONOI` DOUBLE DEFAULT NULL,
				  `NB_AVG_DISTANCE_UMTS` DOUBLE DEFAULT NULL,
				  `SITE_DENSITY_TYPE` TINYINT(4) DEFAULT NULL,
				  `FLAG` SMALLINT(6) DEFAULT NULL,
				  `SERVING_AREA` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
				KEY `NEWINDEX2` (`RNC_ID`,`CELL_ID`),
				KEY `CLUSTER_NAME` (`CLUSTER_NAME`),
				KEY `IX_INDOOR` (`INDOOR`),
				KEY `IX_IDX1` (`SITE_ID`,`RNC_ID`)
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_neighbor`
			(
				  `NT_DATE` DATETIME DEFAULT NULL,
				  `RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				  `CELL_ID` MEDIUMINT(9) DEFAULT NULL,
				  `NBR_RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				  `NBR_RNC_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `NBR_CELL_ID` MEDIUMINT(9) DEFAULT NULL,
				  `NBR_CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `PRIORITY` TINYINT(4) DEFAULT NULL,
				  `NBR_TYPE` TINYINT(4) DEFAULT NULL,
				  `NBR_BCCH_ARFCN` VARCHAR(50) DEFAULT NULL,
				  `NBR_BSIC` VARCHAR(20) DEFAULT NULL,
				  `NBR_DISTANCE` DOUBLE DEFAULT NULL,
				  `NBR_ANGLE` MEDIUMINT(9) DEFAULT NULL,
				  `NBR_AZIMUTH_ANGLE` MEDIUMINT(9) DEFAULT NULL
			) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
			
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_neighbor_current`
			(
				  `NT_DATE` DATETIME DEFAULT NULL,
				  `RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				  `CELL_ID` MEDIUMINT(9) DEFAULT NULL,
				  `NBR_RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				  `NBR_RNC_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `NBR_CELL_ID` MEDIUMINT(9) DEFAULT NULL,
				  `NBR_CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `PRIORITY` TINYINT(4) DEFAULT NULL,
				  `NBR_TYPE` TINYINT(4) DEFAULT NULL,
				  `NBR_BCCH_ARFCN` VARCHAR(50) DEFAULT NULL,
				  `NBR_BSIC` VARCHAR(20) DEFAULT NULL,
				  `NBR_DISTANCE` DOUBLE DEFAULT NULL,
				  `NBR_ANGLE` MEDIUMINT(9) DEFAULT NULL,
				  `NBR_AZIMUTH_ANGLE` MEDIUMINT(9) DEFAULT NULL,
				   KEY `IX_NBR_TYPE` (`CELL_ID`,`RNC_ID`,`NBR_CELL_ID`,`NBR_RNC_ID`,`NBR_TYPE`)
			) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
			
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_rnc`
				(
				  `NT_DATE` DATETIME DEFAULT NULL,
				  `RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				  `RNC_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `MCC` VARCHAR(3) DEFAULT NULL,
				  `MNC` VARCHAR(2) DEFAULT NULL,
				  `TECH_MASK` TINYINT(4) DEFAULT NULL,
				  `VENDOR` VARCHAR(50) DEFAULT NULL,
				  `REGION` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `SUB_REGION` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `RNC_MODEL` VARCHAR(30) DEFAULT NULL,
				  `SITE_CNT` SMALLINT(6) DEFAULT NULL,
				  `CELL_CNT` SMALLINT(6) DEFAULT NULL,
				  `AVG_VORONOI` DOUBLE DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_rnc_current`
			   (	
				  `NT_DATE` DATETIME DEFAULT NULL,
				  `RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				  `RNC_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `MCC` VARCHAR(3) DEFAULT NULL,
				  `MNC` VARCHAR(2) DEFAULT NULL,
				  `TECH_MASK` TINYINT(4) DEFAULT NULL,
				  `VENDOR` VARCHAR(50) DEFAULT NULL,
				  `REGION` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `SUB_REGION` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `RNC_MODEL` VARCHAR(30) DEFAULT NULL,
				  `SITE_CNT` SMALLINT(6) DEFAULT NULL,
				  `CELL_CNT` SMALLINT(6) DEFAULT NULL,
				  `AVG_VORONOI` DOUBLE DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
					
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_cell_attribute`
				(
				`NT_DATE` DATETIME DEFAULT NULL,
				`RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				`CELL_ID` MEDIUMINT(9) DEFAULT NULL,
				`CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				`ATTRIBUTE_NAME` VARCHAR(256) DEFAULT NULL,
				`ATTRIBUTIE_VALUE` TEXT DEFAULT NULL,
				`TYPE` VARCHAR(100) DEFAULT NULL,
				`VENDOR` VARCHAR(50) DEFAULT NULL,
				`P_VALID` TINYINT(4) DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_cell_attribute_current`
				(
				`NT_DATE` DATETIME DEFAULT NULL,
				`RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				`CELL_ID` MEDIUMINT(9) DEFAULT NULL,
				`CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				`ATTRIBUTE_NAME` VARCHAR(256) DEFAULT NULL,
				`ATTRIBUTIE_VALUE` TEXT DEFAULT NULL,
				`TYPE` VARCHAR(100) DEFAULT NULL,
				`VENDOR` VARCHAR(50) DEFAULT NULL,
				`P_VALID` TINYINT(4) DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_sc_code` 
				(
				  `NT_DATE` DATETIME DEFAULT NULL,
				  `RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				  `CELL_ID` MEDIUMINT(9) DEFAULT NULL,
				  `CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `LONGITUDE` DOUBLE DEFAULT NULL,
				  `LATITUDE` DOUBLE DEFAULT NULL,
				  `SCRAMBLING_CODE` SMALLINT(6) DEFAULT NULL,
				  `DL_UARFCN` MEDIUMINT(9) DEFAULT NULL,
				  `VENDOR` VARCHAR(50) DEFAULT NULL,
				  `P_VALID` TINYINT(4) DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_neighbor_voronoi`
				 (
				  `RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				  `SITE_ID` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
				  `NBR_RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				  `NBR_SITE_ID` VARCHAR(20) DEFAULT NULL,
				  `ANGLE` DOUBLE DEFAULT NULL,
				  `DISTANCE` DOUBLE DEFAULT NULL,	
				  `INDOOR_TYPE` TINYINT(4) DEFAULT NULL,
				  `SITEDENSITY_RANGE` INT(11) DEFAULT NULL,
				  `REFINE_DISTANCE` FLOAT DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_neighbor_interfreq` (
				  `NT_DATE` DATE DEFAULT NULL,
				  `RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				  `CELL_ID` MEDIUMINT(9) DEFAULT NULL,
				  `NBR_RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				  `NBR_CELL_ID` MEDIUMINT(9) DEFAULT NULL,
				  `ANGLE` DOUBLE DEFAULT NULL,
				  `DISTANCE` DOUBLE DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_related` (
				  `SOURCE_RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				  `SOURCE_CELL_ID` MEDIUMINT(9) DEFAULT NULL,
				  `SOURCE_SITE_ID` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
				  `TARGET_RNC_ID` MEDIUMINT(9) DEFAULT NULL,
				  `TARGET_CELL_ID` MEDIUMINT(9) DEFAULT NULL,
				  `TARGET_SITE_ID` VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
				  `UARFCN` MEDIUMINT(9) DEFAULT NULL,
				  `DIST` DOUBLE DEFAULT NULL,
				  `ANGLE` MEDIUMINT(9) DEFAULT NULL,
				  `NBR_TYPE` TINYINT(1) DEFAULT NULL,
				  `VORONOI` TINYINT(1) DEFAULT NULL,
				  `THRESHOLD` FLOAT DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`opt_sco_result` (
				  `RNC_ID` INT(11) DEFAULT NULL,
				  `CELL_ID` INT(11) DEFAULT NULL,
				  `SOURCE_CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `LONGITUDE` DOUBLE DEFAULT NULL,
				  `LATITUDE` DOUBLE DEFAULT NULL,
				  `PSC` SMALLINT(6) DEFAULT NULL,
				  `NBR_RNC_ID` INT(11) DEFAULT NULL,
				  `NBR_CELL_ID` INT(11) DEFAULT NULL,
				  `TARGET_CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				  `DISTANCE` DOUBLE DEFAULT NULL,
				  `DEPTH` SMALLINT(6) DEFAULT NULL,
				  `DIS_TILE_CNT` MEDIUMINT(9) DEFAULT ''0'',
				  `UNI_TILE_CNT` MEDIUMINT(9) DEFAULT ''0'',
				  `DEPTH_1_CELL` INT(11) DEFAULT NULL,
				  `DEPTH_1_RNC` INT(11) DEFAULT NULL,
				  `DEPTH_2_CELL` INT(11) DEFAULT NULL,
				  `DEPTH_2_RNC` INT(11) DEFAULT NULL,
				  `CM_ADMIN_STATE` TINYINT(4) DEFAULT NULL,
				  `CM_OPERATION_STATE` TINYINT(4) DEFAULT NULL,
				  `NBR_CM_ADMIN_STATE` TINYINT(4) DEFAULT NULL,
				  `NBR_CM_OPERATION_STATE` TINYINT(4) DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 	
		
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`opt_sco_suggest` (
				  `RNC_ID` INT(11) DEFAULT NULL,
				  `CELL_ID` INT(11) DEFAULT NULL,
				  `NBR_RNC_ID` INT(11) DEFAULT NULL,
				  `NBR_CELL_ID` INT(11) DEFAULT NULL,
				  `PSC_SUGGEST` SMALLINT(6) DEFAULT NULL,
				  `DISTANCE` DOUBLE DEFAULT NULL,
				  `PSC_DEPTH` SMALLINT(6) DEFAULT NULL,
				  `PSC_RNC_ID` VARCHAR(64) DEFAULT NULL,
				  `PSC_CELL_ID` VARCHAR(64) DEFAULT NULL,
				  `SUGGEST_ORDER` INT(11) DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_repeater_current` (
				`NT_DATE` DATETIME DEFAULT NULL,
				`RNC_ID` INT(11) DEFAULT NULL,
				`CELL_ID` INT(11) DEFAULT NULL,
				`CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				`LONGITUDE` DOUBLE DEFAULT NULL,
				`LATITUDE` DOUBLE DEFAULT NULL,
				`AZIMUTH` SMALLINT(6) DEFAULT NULL,
				`ANTENNA_MODEL` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
				`ANTENNA_TYPE` TINYINT(4) DEFAULT NULL,
				`HEIGHT` DOUBLE DEFAULT NULL,
				`BEAMWIDTH_H` DOUBLE DEFAULT NULL,
				`BEAMWIDTH_V` DOUBLE DEFAULT NULL,
				`CPICH_POWER` DOUBLE DEFAULT NULL,
				`EIRP` DOUBLE DEFAULT NULL,
				`ANTENNA_GAIN` DOUBLE DEFAULT NULL,
				`FEEDER_LOSS` DOUBLE DEFAULT NULL,
				`DOWNTILT_EL` DOUBLE DEFAULT NULL,
				`DOWNTILT_MEC` DOUBLE DEFAULT NULL,
				`ELEVATION` DOUBLE DEFAULT NULL,
				`REPEATER_TYPE` VARCHAR(20) DEFAULT NULL,
				`REPEATER_PG_DELAY` VARCHAR(20) DEFAULT NULL, 
				`INDOOR_TYPE` TINYINT(4) DEFAULT NULL,
				`ANTENNA_ID` TINYINT(4) DEFAULT ''1''
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`rule_nt_nbr_umts` (
				`VENDORID` VARCHAR(20) DEFAULT NULL,
				`SOURCEFREQ` SMALLINT(6) DEFAULT NULL,
				`SOURCEUARFCN` MEDIUMINT(9) DEFAULT NULL,
				`TARGETFREQ` SMALLINT(6) DEFAULT NULL,
				`TARGETUARFCN` MEDIUMINT(9) DEFAULT NULL,
				`COSECTOR` SMALLINT(6) DEFAULT NULL,
				`NBRTYPE` TINYINT(4) DEFAULT NULL,
				`ALLOWED` TINYINT(4) DEFAULT NULL,
				`MINNBRCNT` SMALLINT(6) DEFAULT NULL,
				`MAXNBRCNT` SMALLINT(6) DEFAULT NULL,
				`SUPPORTFLAG` TINYINT(4) DEFAULT NULL,
				`BORDER_NBRCNT` SMALLINT(6) DEFAULT NULL,
				`SIB` TINYINT(4) DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT_DROPPED_CELL` (
				`TAC` MEDIUMINT(9) ,
				`ENODEB_ID` MEDIUMINT(9) ,
				`CELL_ID` MEDIUMINT(9) ,
				`LAC` MEDIUMINT(9) ,
				`TECHNOLOGY` CHAR(1),
				`VENDOR` VARCHAR(20) CHARACTER SET UTF8
				)ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT_RNCLIST` (
				`GTGW` VARCHAR(20) CHARACTER SET UTF8,
				`RNC` SMALLINT(6),
				`RNC_NAME` VARCHAR(20) CHARACTER SET UTF8,
				`CELL COUNT` MEDIUMINT(9) ,
				`STATUS` VARCHAR(50) CHARACTER SET UTF8
				)ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	IF extarTables='true' THEN
		SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_extra` (
					NT_DATE DATETIME DEFAULT NULL,
					RNC_ID MEDIUMINT DEFAULT NULL,
					SITE_ID VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
					SITE_NAME VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
					CELL_ID MEDIUMINT DEFAULT NULL,
					CELL_NAME VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
					LAC SMALLINT(6) UNSIGNED DEFAULT NULL,
					MAXIMUM_HSDPA_USERNUMBER SMALLINT(6) DEFAULT NULL,
					ENABLE_HSDPA SMALLINT(6) DEFAULT NULL,
					FEATURE_STATE_16QAM SMALLINT(6) DEFAULT NULL,
					FEATURE_STATE_HSDPA_DYNAMIC_CODE_ALLOCATION SMALLINT(6) DEFAULT NULL,
					FEATURE_STATE_HSDPA_INCREMENTAL_REDUNDANCY SMALLINT(6) DEFAULT NULL,
					FEATURE_STATE_HSDPA_FLEXIBLE_SCHEDULER SMALLINT(6) DEFAULT NULL,
					FEATURE_STATE_HSDPA_IMPROVED_LINK_ADAPTION SMALLINT(6) DEFAULT NULL,
					NUM_HS_SCCH_CODES SMALLINT(6) DEFAULT NULL,
					MAX_NUM_HS_PDSCH_CODES SMALLINT(6) DEFAULT NULL,
					NUM_HS_PDSCH_CODES SMALLINT(6) DEFAULT NULL,
					HS_POWER_MARGIN SMALLINT(6) DEFAULT NULL,
					CODE_THRESHOLD_PDU656 SMALLINT(6) DEFAULT NULL,
					NUM_HS_CODE_RESOURCES SMALLINT(6) DEFAULT NULL,
					FEATURE_STATE_INCR_NUM_HS_CODES SMALLINT(6) DEFAULT NULL,
					STEERED_HS_ALLOCATION VARCHAR(10) DEFAULT NULL,
					FEATURE_STATE_ENHANCED_LAYER2 SMALLINT(6) DEFAULT NULL,
					FEATURE_STATE_64QAM SMALLINT(6) DEFAULT NULL,
					MAXIMUM_HSUPA_USER_NUMBER SMALLINT(6) DEFAULT NULL,
					MAXIMUM_HSUPA_2MS_TTI_USER_NUMBER SMALLINT(6) DEFAULT NULL,
					ENABLE_HSUPA SMALLINT(6) DEFAULT NULL,
					FEATURE_STATE_EUL_10M_TTI SMALLINT(6) DEFAULT NULL,
					NUM_EUL_RESOURCES SMALLINT(6) DEFAULT NULL,
					FEATURE_STATE_EUL_2MS_TTI SMALLINT(6) DEFAULT NULL,
					FEATURE_STATE_PER_HARQ_PROCESS_GRANT SMALLINT(6) DEFAULT NULL,
					AIR_RATE_TYPE_SELECTOR SMALLINT(6) DEFAULT NULL,
					FEATURE_STATE_HSDPA_MC SMALLINT(6) DEFAULT NULL,
					HSDSCH_SUPPORT SMALLINT(6) DEFAULT NULL,
					EDCH_SUPPORT SMALLINT(6) DEFAULT NULL,
					EDCH_TTI2_SUPPORT SMALLINT(6) DEFAULT NULL,
					ENHANCED_L2_SUPPORT SMALLINT(6) DEFAULT NULL,
					FDPCH_SUPPORT SMALLINT(6) DEFAULT NULL,
					MULTI_CARRIER_SUPPORT SMALLINT(6) DEFAULT NULL,
					CPC_SUPPORT SMALLINT(6) DEFAULT NULL,
					QAM64_MIMO_SUPPORT SMALLINT(6) DEFAULT NULL,
					T_CELL SMALLINT(6) DEFAULT NULL,
					LOAD_SHARING_MARGIN SMALLINT(6) DEFAULT NULL,
					HSDPA_USERS_ADM SMALLINT(6) DEFAULT NULL,
					EUL_SERVING_CELL_USERS_ADM SMALLINT(6) DEFAULT NULL,
					PWR_ADM SMALLINT(6) DEFAULT NULL,
					PWR_OFFSET SMALLINT(6) DEFAULT NULL,
					DL_CODE_ADM SMALLINT(6) DEFAULT NULL,
					FACH_MEAS_OCCA_CYC_LEN_COEFF SMALLINT(6) DEFAULT NULL,
					PATHLOSS_THRESHOLD SMALLINT(6) DEFAULT NULL,
					USED_FREQ_THRESH_2D_ECNO SMALLINT(6) DEFAULT NULL,
					USED_FREQ_THRESH_2D_RSCP SMALLINT(6) DEFAULT NULL,
					HO_TYPE SMALLINT(6) DEFAULT NULL,
					USER_ADM SMALLINT(6) DEFAULT NULL,
					QUAL_MEAS_QUANTITY SMALLINT(6) DEFAULT NULL,
					HS_IFLS_MARGIN_USERS SMALLINT(6) DEFAULT NULL,
					HS_IFLS_THRESH_USERS SMALLINT(6) DEFAULT NULL,
					DCH_IFLS_MARGIN_CODE SMALLINT(6) DEFAULT NULL,
					DCH_IFLS_MARGIN_POWER SMALLINT(6) DEFAULT NULL,
					DCH_IFLS_THRESH_CODE SMALLINT(6) DEFAULT NULL,
					DCH_IFLS_THRESH_POWER SMALLINT(6) DEFAULT NULL,
					HS_ONLY_BEST_CELL SMALLINT(6) DEFAULT NULL,
					LOAD_SHARING_RRC_ENABLED SMALLINT(6) DEFAULT NULL
					) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
		
		SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`nt_coverage` (
					NT_DATE DATETIME DEFAULT NULL,
					RNC_ID MEDIUMINT DEFAULT NULL,
					SITE_ID VARCHAR(20) CHARACTER SET UTF8 DEFAULT NULL,
					SITE_NAME VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
					CELL_ID MEDIUMINT DEFAULT NULL,
					CELL_NAME VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
					LAC SMALLINT(6) UNSIGNED DEFAULT NULL,
					COVERAGE_RELATION VARCHAR(50) DEFAULT NULL,
					HS_CELL_SELECTION SMALLINT(6) DEFAULT NULL,
					HS_LOAD_SHARING SMALLINT(6) DEFAULT NULL,
					DCH_LOAD_SHARING SMALLINT(6) DEFAULT NULL,
					COVERAGE_INDICATOR SMALLINT(6) DEFAULT NULL
					) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
	END IF;
	
	CALL gt_gw_main.SP_CreateDB_NT_Schema_Sub(GT_DB);
END$$
DELIMITER ;
