DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Check_IMEI_Miss_Rate`(IN GT_DB VARCHAR(100))
BEGIN
	DECLARE RNC_ID INT;
	SELECT gt_strtok(GT_DB,2,'_') INTO RNC_ID;	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS tmp_imsi_imei;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE `tmp_imsi_imei` (
				`DATA_DATE` DATETIME DEFAULT NULL,
				`IMSI` VARCHAR(20) DEFAULT NULL,
				`IMEI_NEW` VARCHAR(20) DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=latin1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('INSERT INTO tmp_imsi_imei 
				SELECT DATA_DATE,IMSI,IMEI_NEW
				FROM ',GT_DB,'.table_call 
				GROUP BY DATA_DATE,IMSI,IMEI_NEW;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 	
	
	SET @SqlCmd=CONCAT('SELECT ''',RNC_ID,''',DATA_DATE,SUM(CASE WHEN IMEI_NEW IS NULL OR TRIM(IMEI_NEW)='''' THEN 1 ELSE 0 END) AS NULL_CNT
				,COUNT(*) AS ALL_CNT,(SUM(CASE WHEN IMEI_NEW IS NULL OR TRIM(IMEI_NEW)='''' THEN 1 ELSE 0 END))/(COUNT(*)) AS Miss_Rate
				FROM tmp_imsi_imei GROUP BY ''',RNC_ID,''',DATA_DATE;');
        PREPARE Stmt FROM @SqlCmd;
        EXECUTE Stmt;
        DEALLOCATE PREPARE Stmt; 	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS tmp_imsi_imei;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
END$$
DELIMITER ;
