DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_CreateDB_NT2_Schema_LTE`(IN GT_DB VARCHAR(100))
BEGIN
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_NBR_4_2_LTE` (
	`ENODEB_ID` MEDIUMINT(9),
	`CELL_ID` MEDIUMINT(9),
	`NBR_BSC_ID` MEDIUMINT(9),
	`NBR_CELL_ID` MEDIUMINT(9),
	`PRIORITY` TINYINT(4),
	`NBR_BCCH_ARFCN`  MEDIUMINT(9) UNSIGNED,
	`NBR_BSIC`  TINYINT(4) UNSIGNED,
	`NBR_LAC` MEDIUMINT(9),
	`NBR_DISTANCE` FLOAT(9,2),
	`NBR_ANGLE` SMALLINT(6),
	`NBR_AZIMUTH_ANGLE` SMALLINT(6),
	KEY `NT_NBR_4_2_LTE_ID` (`ENODEB_ID`, `CELL_ID`, `NBR_BSC_ID`, `NBR_CELL_ID`)
	)ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_NBR_4_2_LTE_dump` LIKE ',GT_DB,'.`NT2_NBR_4_2_LTE`;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_NBR_4_3_LTE` (
	`ENODEB_ID` MEDIUMINT(9),
	`CELL_ID` MEDIUMINT(9),
	`NBR_RNC_ID` MEDIUMINT(9),
	`NBR_CELL_ID` MEDIUMINT(9),
	`PRIORITY` TINYINT(4),
	`NBR_UARFCN` MEDIUMINT(9),
	`NBR_PSC` SMALLINT(6),
	`NBR_DISTANCE` FLOAT(9,2),
	`NBR_ANGLE` SMALLINT(6),
	`NBR_AZIMUTH_ANGLE` SMALLINT(6),
	KEY `NT_NBR_4_3_LTE_ID` (`ENODEB_ID`, `CELL_ID`, `NBR_RNC_ID`, `NBR_CELL_ID`)
	)ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_NBR_4_3_LTE_DUMP` LIKE ',GT_DB,'.`NT2_NBR_4_3_LTE`;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_NBR_4_4_LTE` (
	`ENODEB_ID` MEDIUMINT(9),
	`CELL_ID` MEDIUMINT(9),
	`NBR_ENODEB_ID` MEDIUMINT(9),
	`NBR_CELL_ID` MEDIUMINT(9),
	`PRIORITY` TINYINT(4),
	`NBR_TYPE` TINYINT(4),
	`NBR_EARFCN` Smallint(6) unsigned,
	`NBR_PCI` SMALLINT(6),
	`NBR_DISTANCE` FLOAT(9,2),
	`NBR_ANGLE` SMALLINT(6),
	`NBR_AZIMUTH_ANGLE` SMALLINT(6),
	KEY `NT_NBR_4_4_LTE_ID1` (`ENODEB_ID`, `CELL_ID`, `NBR_ENODEB_ID`, `NBR_CELL_ID`)
	)ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_NBR_4_4_LTE_DUMP` LIKE ',GT_DB,'.`NT2_NBR_4_4_LTE`;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_ANTENNA_LTE` (
	`ENODEB_ID` MEDIUMINT(9),
	`CELL_ID` MEDIUMINT(9),
	`ANTENNA_ID` TINYINT(4),
	`LONGITUDE` FLOAT(9,6),
	`LATITUDE` FLOAT(9,6),
	`AZIMUTH` SMALLINT(6),
	`ANTENNA_HEIGHT` FLOAT(7,2),
	`REFERENCE_SIGNAL_POWER` FLOAT(7,2),
	`FEEDER_LOSS` FLOAT(7,2),
	`EIRP` FLOAT(7,2),
	`ANTENNA_MODEL` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
	`ANTENNA_TYPE` TINYINT(4),
	`ANTENNA_GAIN` FLOAT(7,2),
	`BEAMWIDTH_H` SMALLINT(6),
	`BEAMWIDTH_V` SMALLINT(6),
	`DOWNTILT_MEC` SMALLINT(6),
	`DOWNTILT_EL` SMALLINT(6),
	`ELEVATION` FLOAT(9,2),
	`REPEATER_IND` TINYINT(4),
	`REPEATER_TYPE` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
	`REPEATER_DELAY` SMALLINT(6),
	`FIELD_TYPE` TINYINT(4),
	`PATHLOSS_DISTANCE` FLOAT(9,2),
	`ANTENNA_RADIUS` FLOAT(9,2),
	`CLOSED_RADIUS` FLOAT(9,2),
	`FLAG` INT(11),
	`PATHLOSS_360` TEXT,
	`ANTENNA_RADIUS_360` TEXT,
	KEY `PRIMARY KEY` (`ENODEB_ID`,`CELL_ID`,`ANTENNA_ID`),
	KEY `ID_KEY` (`ENODEB_ID`,`CELL_ID`)
	)ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_ANTENNA_LTE_DUMP` LIKE ',GT_DB,'.`NT2_ANTENNA_LTE`;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;	
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_CELL_ATTRIBUTE_EXT_LTE` (
	`ENODEB_ID` MEDIUMINT(9),
	`CELL_ID` MEDIUMINT(9),
	`ACTIVE_START_DATE` DATE,
	`ACTIVE_END_DATE` DATE,
	`PLAN_START_DATE` DATE,
	`PLAN_END_DATE` DATE,
	`SLA` CHAR(1),
	`VIP` CHAR(1),
	KEY `NT_CELL_ATTRIBUTE_EXT_ID` (`ENODEB_ID`,`CELL_ID`)
	)ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_CELL_LTE` (
	`ENODEB_ID` MEDIUMINT(9),
	`ENODEB_NAME` VARCHAR(125) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
	`ENODEB_LOC_ID` VARCHAR(20) CHARACTER SET utf8,
	`ENODEB_NE_ID` VARCHAR(20) CHARACTER SET utf8,
	`ENODEB_OSS_NODE_ID` VARCHAR(20) CHARACTER SET utf8,
	`CELL_ID` MEDIUMINT(9),
	`CELL_NAME` VARCHAR(125) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
	`CELL_LOC_ID` VARCHAR(20) CHARACTER SET utf8,
	`CELL_NE_ID` VARCHAR(20) CHARACTER SET utf8,
	`CELL_OSS_NODE_ID` VARCHAR(20) CHARACTER SET utf8,
	`SECTOR_ID` TINYINT(4),
	`BWCHANNEL` FLOAT(6,2),
	`EUTRABAND` MEDIUMINT(9),
	`FREQUENCY` SMALLINT(6),
	`DL_EARFCN` MEDIUMINT(9),
	`UL_EARFCN` MEDIUMINT(9),
	`PCI` SMALLINT(6),
	`RSI` SMALLINT(6),
	`INDOOR` TINYINT(4),
	`ENODEB_TYPE` TINYINT(4),
	`ENODEB_CAPACITY` VARCHAR(20) CHARACTER SET utf8,
	`ENODEB_VENDOR` VARCHAR(50) CHARACTER SET utf8,
	`ENODEB_MODEL` VARCHAR(100) CHARACTER SET utf8,
	`CELL_RADIUS` SMALLINT(6),
	`IP` VARCHAR(20) CHARACTER SET utf8,
	`CLUSTER` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
	`REGION` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
	`SUB_REGION` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
	`ZONE` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
	`MORPHOLOGY` VARCHAR(50) CHARACTER SET utf8,
	`ACTIVE_STATE` VARCHAR(50) CHARACTER SET utf8,
	`CM_ADMIN_STATE` TINYINT(4),
	`CM_OPERATION_STATE` TINYINT(4),
	`VENDOR_ENODEB_INDEX` VARCHAR(50) CHARACTER SET utf8,
	`VENDOR_CELL_INDEX` VARCHAR(50) CHARACTER SET utf8,
	`PU_ID` MEDIUMINT(9),
	`CLUSTER_ID` MEDIUMINT(9),
	`INA_FREQ_NBCNT` SMALLINT(6) UNSIGNED,
	`INT_FREQ_NBCNT` SMALLINT(6) UNSIGNED,
	`UMTS_NBCNT` SMALLINT(6) UNSIGNED,
	`GSM_NBCNT` SMALLINT(6) UNSIGNED,
	`NBR_DISTANCE_CM` FLOAT(9,2),
	`NBR_DISTANCE_CM_MAX` FLOAT(9,2),
	`NBR_DISTANCE_VORONOI` FLOAT(9,2),
	`NBR_DISTANCE_VORONOI_MAX` FLOAT(9,2),
	`SITE_DENSITY_TYPE` TINYINT(4),
	`FLAG` INT(11),
	`SERVING_TYPE` TINYINT(4),
	`NBIOT_TYPE` TINYINT(4),
	KEY `NT_CELL_LTE_ID` (`ENODEB_ID`,`CELL_ID`)
	)ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1;');	
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_CELL_LTE_DUMP` LIKE ',GT_DB,'.`NT2_CELL_LTE`;');	
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;	
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_MME_LTE` (
	`MME_ID` BIGINT(20),
	`MME_NAME` VARCHAR(20) CHARACTER SET utf8,
	`MME_NE_ID` VARCHAR(20) CHARACTER SET utf8,
	`S_GW_ID` MEDIUMINT(9),
	`S_GW_NAME` VARCHAR(50) CHARACTER SET utf8,
	`USER_LABEL` VARCHAR(50) CHARACTER SET utf8,
	`MCC` VARCHAR(3) CHARACTER SET utf8,
	`MNC` VARCHAR(2) CHARACTER SET utf8,
	`VENDOR` VARCHAR(50) CHARACTER SET utf8,
	PRIMARY KEY (`MME_ID`)
	)ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_PU` (
	`PU_ID` MEDIUMINT(9),
	`PU_NAME` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
	`MCC` VARCHAR(3) CHARACTER SET utf8,
	`MNC` VARCHAR(3) CHARACTER SET utf8,
	`VEDNOR` VARCHAR(30) CHARACTER SET utf8,
	`ENODEB_CNT` SMALLINT(6) UNSIGNED,
	`CELL_CNT` SMALLINT(6) UNSIGNED,
	`NBR_DISTANCE_VORONOI` FLOAT(9,2),
	`NBR_DISTANCE_CM` FLOAT(9,2),
	PRIMARY KEY (`PU_ID`)
	)ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_PU_ENODEB_MAPPING` (
	`PU_ID` MEDIUMINT(9),
	`ENODEB_ID` MEDIUMINT(9),
	`ENODEB_NAME` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
	KEY NT_PU_ENODEB_MAPPING_IDX(PU_ID, ENODEB_ID)
	)ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_TAC_CELL_LTE` (
	`ENODEB_ID` MEDIUMINT(9),
	`CELL_ID` MEDIUMINT(9),
	`TAC` MEDIUMINT(9),
	`TAC_TYPE` TINYINT(4),
	 KEY TAC_CELL_LTE_IDX(ENODEB_ID, CELL_ID)
	)ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_NBR_VORONOI_LTE`(		
	`ENODEB_ID` VARCHAR(20) DEFAULT NULL,
	`NBR_ENODEB_ID` VARCHAR(20) DEFAULT NULL,
	`ANGLE` DOUBLE DEFAULT NULL,
	`DISTANCE` DOUBLE DEFAULT NULL,
	`INDOOR_TYPE` TINYINT(4) DEFAULT NULL,
	`SITEDENSITY_RANGE` INT(11) DEFAULT NULL,
	`REFINE_DISTANCE` FLOAT DEFAULT NULL,
	KEY `ENODEB_ID_IDX` (`ENODEB_ID`,`NBR_ENODEB_ID`)			   
	) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
	;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE IF NOT EXISTS ',GT_DB,'.`NT2_LOG_LTE` (
	`ID` MEDIUMINT(9) DEFAULT NULL,
	`CELL_ID` MEDIUMINT(9) DEFAULT NULL,
	`TBL_NAME` VARCHAR(50) DEFAULT NULL,
	`COL_NAME` VARCHAR(50) DEFAULT NULL,
	`LOG_TYPE` TINYINT(4) DEFAULT NULL,
	`DUMP_LOG` VARCHAR(100) DEFAULT NULL
	) ENGINE=MYISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_CLUSTER_LTE` (
	`PU_ID` mediumint(9) DEFAULT NULL,
	`CLUSTER_NAME` varchar(50) DEFAULT NULL,
	`VENDOR` varchar(20) DEFAULT NULL,
	`CLUSTER_ID` mediumint(9) unsigned NOT NULL,
	PRIMARY KEY (`CLUSTER_ID`)
	) ENGINE=MyISAM DEFAULT CHARSET=utf8 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_PU_ENODEB_MISSINGMAP` (
	`ENODEB_ID` MEDIUMINT(9),
	`ENODEB_NAME` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
	`CLUSTER_NAME_REGION` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
	`CLUSTER_NAME_SUB_REGION` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
	`CLUSTER_NAME_STRUCTURE_TYPE` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
	`CLUSTER_NAME_ZONE` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_swedish_ci DEFAULT NULL,
	PRIMARY KEY (`ENODEB_ID`)
	)ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_RULE_NBR_ENODEB_LTE`
	(		
	`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
	`BL_MCC_TRAGET` VARCHAR(3) DEFAULT NULL,
	`BL_MNC_TARGET` VARCHAR(3) DEFAULT NULL,
	`BL_ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
	`BL_TYPE` VARCHAR(20) DEFAULT NULL,
	KEY `NT_NBR_LTE_BLACKLIST_IDX1` (ENODEB_ID,`BL_ENODEB_ID`)
	) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
	;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.`NT2_RULE_NBR_CELL_PCI_LTE`
	(		
	`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
	`CELL_ID` TINYINT(4) DEFAULT NULL,
	`BL_FREQ_EARFCN` MEDIUMINT(9) DEFAULT NULL,
	`BL_PCI` SMALLINT(6) DEFAULT NULL,
	KEY `NT_NBR_CELL_BLACKLIST_PCI_IDX1` (ENODEB_ID,`CELL_ID`)
	) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
	;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	CALL gt_gw_main.SP_Sub_Generate_Sys_Config(GT_DB,'gt_covmo','lte');
	SET @SqlCmd=CONCAT('CREATE TABLE IF NOT EXISTS ',GT_DB,'.`Opt_rsi_result_lte`
	(
	`PU_ID` MEDIUMINT(9) NOT NULL,
	`ENODEB_ID` MEDIUMINT(9)  NOT NULL,
	`CELL_ID` TINYINT(4) NOT NULL,
	`CELL_NAME` VARCHAR(50) DEFAULT NULL,
	`INDOOR` TINYINT(1) DEFAULT NULL,
	`RSI` SMALLINT(6) NOT NULL,
	`DEPTH` SMALLINT(6) DEFAULT NULL,
	`DISTANCE` FLOAT DEFAULT NULL,
	`DEPTH_1_PU` MEDIUMINT(9) DEFAULT NULL,
	`DEPTH_1_ENODEB` MEDIUMINT(9)  DEFAULT NULL,
	`DEPTH_1_CELL` TINYINT(4) DEFAULT NULL,
	`DEPTH_1_CELL_NAME` VARCHAR(50) DEFAULT NULL,
	`DEPTH_2_ENODEB` MEDIUMINT(9)  DEFAULT NULL,
	`DEPTH_2_CELL` TINYINT(4) DEFAULT NULL,
	`DEPTH_2_CELL_NAME` VARCHAR(50) DEFAULT NULL,
	`RSI_SUGGEST_1` SMALLINT(6) DEFAULT NULL,
	`RSI_SUGGEST_2` SMALLINT(6) DEFAULT NULL,
	PRIMARY KEY (`PU_ID`,`ENODEB_ID`,`CELL_ID`,`RSI`)
	) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
	;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	SET @SqlCmd=CONCAT('CREATE TABLE IF NOT EXISTS ',GT_DB,'.`Opt_rsi_soft_result_lte`
	(
	`PU_ID` MEDIUMINT(9) NOT NULL,
	`ENODEB_ID` MEDIUMINT(9)  NOT NULL,
	`CELL_ID` TINYINT(4) NOT NULL,
	`CELL_NAME` VARCHAR(50) DEFAULT NULL,
	`INDOOR` TINYINT(1) DEFAULT NULL,
	`RSI` SMALLINT(6) NOT NULL,
	`DISTANCE` FLOAT DEFAULT NULL,
	`NBR_PU_ID` MEDIUMINT(9) DEFAULT NULL,
	`NBR_ENODEB_ID` MEDIUMINT(9)  DEFAULT NULL,
	`NBR_CELL_ID` TINYINT(4) DEFAULT NULL,
	`NBR_CELL_NAME` VARCHAR(50) DEFAULT NULL,
	`COLLISION_RSI` SMALLINT(6) DEFAULT NULL,
	`RSI_SUGGEST_1` SMALLINT(6) DEFAULT NULL,
	`RSI_SUGGEST_2` SMALLINT(6) DEFAULT NULL,
	PRIMARY KEY (`PU_ID`,`ENODEB_ID`,`CELL_ID`,`RSI`)
	) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1
	;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 			
	SET @SqlCmd=CONCAT('CREATE TABLE IF NOT EXISTS ',GT_DB,'.`opt_pci_result` (
	`PU_ID` MEDIUMINT(9) DEFAULT NULL,
	`ENODEB_ID` INT(11) NOT NULL,
	`CELL_ID` TINYINT(4) NOT NULL,
	`CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
	`LONGITUDE` DOUBLE NOT NULL,
	`LATITUDE` DOUBLE NOT NULL,
	`PCI` INT(11) NOT NULL,
	`NBR_PU_ID` MEDIUMINT(9) DEFAULT NULL,
	`NBR_ENODEB_ID` INT(11) NOT NULL,
	`NBR_CELL_ID` INT(11) NOT NULL,
	`NBR_CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
	`DISTANCE` DOUBLE DEFAULT NULL,
	`DEPTH` MEDIUMINT(9) DEFAULT NULL,
	`DEPTH_1_ENODEB` INT(11) DEFAULT NULL,
	`DEPTH_1_CELL` INT(11) DEFAULT NULL,
	`DEPTH_2_ENODEB` INT(11) DEFAULT NULL,
	`DEPTH_2_CELL` INT(11) DEFAULT NULL,
	UNIQUE KEY `ENODEB_ID` (`ENODEB_ID`,`CELL_ID`,`NBR_ENODEB_ID`,`NBR_CELL_ID`)
	) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('CREATE TABLE IF NOT EXISTS ',GT_DB,'.`opt_pci_suggest` (
	`PU_ID` MEDIUMINT(9) DEFAULT NULL,
	`ENODEB_ID` INT(11) DEFAULT NULL,
	`CELL_ID` INT(11) DEFAULT NULL,
	`CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
	`NBR_PU_ID` MEDIUMINT(9) DEFAULT NULL,
	`NBR_ENODEB_ID` INT(11) DEFAULT NULL,
	`NBR_CELL_ID` INT(11) DEFAULT NULL,
	`NBR_CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL,
	`PCI_SUGGEST` INT(11) DEFAULT NULL,
	`DISTANCE` DOUBLE DEFAULT NULL,
	`PCI_ENODEB_ID` INT(11) DEFAULT NULL,
	`PCI_CELL_ID` INT(11) DEFAULT NULL,
	`PCI_CELL_NAME` VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL
	) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TABLE IF NOT EXISTS ',GT_DB,'.`NT2_CELL_POLYGON_LTE` (
	`PU_ID` MEDIUMINT(9) DEFAULT NULL,
	`ENODEB_ID` MEDIUMINT(9) DEFAULT NULL,
	`CELL_ID` MEDIUMINT(9) DEFAULT NULL,
	POLYGON_STR LONGTEXT CHARACTER SET UTF8 DEFAULT NULL,
	MAPPING_TYPE TINYINT(4) DEFAULT NULL,
	KEY `CELL_POLYGON_LTE_IDX` (ENODEB_ID,`CELL_ID`)
	) ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	
	SET @SqlCmd=CONCAT('CREATE TABLE IF NOT EXISTS ',GT_DB,'.`NT2_ANTENNA_INFO` (
	`ANTENNA_MODEL` VARCHAR(100) CHARACTER SET UTF8,
	`ANTENNA_TYPE` TINYINT(4),
	`GAIN_DBI` FLOAT,
	`DEVIATION` SMALLINT(6) DEFAULT 0,
	`HBW3` SMALLINT(6),
	`HBW3_CL` SMALLINT(6),
	`HBW3_CW` SMALLINT(6),
	`VBW3` SMALLINT(6),
	`VBW3_CL` SMALLINT(6),
	`VBW3_CW` SMALLINT(6),
	`HORIZONTAL_360` TEXT,
	`VERTICAL_360` TEXT,
	`ANTENNA_GROUP` VARCHAR(50) CHARACTER SET UTF8,
	`ELECTRICAL_TILT` FLOAT,
	`MECHANICAL_TILT` FLOAT,
	`CATEGORIZE` VARCHAR(50) CHARACTER SET UTF8,
	`MANUFACTURER` VARCHAR(50) CHARACTER SET UTF8,
	`TILT_TYPE` VARCHAR(20) CHARACTER SET UTF8,
	`FREQUENCY` VARCHAR(20) CHARACTER SET UTF8,
	`COMMENTS` VARCHAR(100) CHARACTER SET UTF8
	)ENGINE=MYISAM DEFAULT CHARSET=LATIN1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	CALL gt_gw_main.SP_Sub_Generate_Sys_Config(GT_DB,'gt_covmo','lte'); 
 
END$$
DELIMITER ;
