DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_CreateDB_Schema_NDC`(IN GT_DB VARCHAR(100))
BEGIN
	DECLARE SH_EH VARCHAR(9) DEFAULT RIGHT(GT_DB,9);
	DECLARE DY_GT_DB VARCHAR(100);
	
	SELECT REPLACE(GT_DB,SH_EH,'0000_0000') INTO DY_GT_DB;
	
	IF SH_EH != '0000_0000' THEN
		SET @SqlCmd=CONCAT('CREATE DATABASE ',GT_DB,';');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt; 
	
		CALL gt_gw_main.SP_CreateDB_Schema_CALL(GT_DB,'');	
	END IF;
END$$
DELIMITER ;
