DELIMITER $$
USE `gt_global_statistic`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Generate_Global_Statistic_imsi_gsm`(IN DATA_DATE DATE,IN DATA_HOUR TINYINT(2),IN PU_ID MEDIUMINT(9),IN TECH_MASK TINYINT(2), IN GT_DB VARCHAR(100),IN IMSI_CELL TINYINT(2))
BEGIN
	DECLARE SP_Process VARCHAR(100) DEFAULT NULL;
	DECLARE WORKER_ID VARCHAR(10) DEFAULT CONNECTION_ID();
	DECLARE ZOOM_LEVEL INT;
	SET @FLAG_IMSI_HR=0;
	SET @FLAG_IMSI_DY=0;
	SET @FLAG_MAKE_HR=0;
	SET @FLAG_MAKE_DY=0;
	INSERT INTO gt_gw_main.sp_log VALUES('gt_gw_main','SP_Generate_Global_Statistic_imsi_gsm',CONCAT(GT_DB,' CREATE TEMPORARY TABLE tmp_materialization_imsi_gsm_',WORKER_ID), NOW());	
	
	SET SESSION group_concat_max_len=102400; 
	
	SET @SqlCmd=CONCAT('SELECT `att_value` INTO @ZOOM_LEVEL FROM gt_covmo.`sys_config` WHERE `group_name`=''system'' AND att_name = ''MapResolution'';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_materialization_imsi_gsm_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,'.tmp_materialization_imsi_gsm_',WORKER_ID,' 
				(
					`IMSI` VARCHAR(20) NOT NULL,
					`DATA_DATE` DATETIME NOT NULL,
					`DATA_HOUR` TINYINT(2) NOT NULL,
					CALL_CNT INT(11) DEFAULT NULL,
					VOICE_MO_CNT INT(11) DEFAULT NULL,
					VOICE_MT_CNT INT(11) DEFAULT NULL,
					DATA_MO_CNT INT(11) DEFAULT NULL,
					DATA_MT_CNT INT(11) DEFAULT NULL,
					SMS_MO_CNT INT(11) DEFAULT NULL,
					SMS_MT_CNT INT(11) DEFAULT NULL,
					SIGNAL_CNT INT(11) DEFAULT NULL,
					CALL_DUR_SUM INT(11) DEFAULT NULL,
					VOICE_DUR_SUM INT(11) DEFAULT NULL,
					DATA_DUR_SUM INT(11) DEFAULT NULL,
					DROP_CNT INT(11) DEFAULT NULL,
					BLOCK_CNT INT(11) DEFAULT NULL,
					DROP_VOICE_CNT INT(11) DEFAULT NULL,
					DROP_GPRS_CNT INT(11) DEFAULT NULL,
					DROP_SMS_CNT INT(11) DEFAULT NULL,
					DROP_SIGNAL_CNT INT(11) DEFAULT NULL,
					DROP_OTHER_CNT INT(11) DEFAULT NULL,					
					BLOCK_VOICE_CNT INT(11) DEFAULT NULL,
					BLOCK_GPRS_CNT INT(11) DEFAULT NULL,
					BLOCK_SMS_CNT INT(11) DEFAULT NULL,
					BLOCK_SMS_MT_CNT INT(11) DEFAULT NULL,
					BLOCK_SMS_MO_CNT INT(11) DEFAULT NULL,
					BLOCK_SIGNAL_CNT INT(11) DEFAULT NULL,
					BLOCK_OTHER_CNT INT(11) DEFAULT NULL,
					HO_ATTEMPT_CNT INT(11) DEFAULT NULL,
					HO_FAILURE_CNT INT(11) DEFAULT NULL,
					MOVING_CALL_CNT INT(11) DEFAULT NULL,
					INDOOR_CALL_CNT INT(11) DEFAULT NULL,
					FIRST_RXLEV_DL_SUM DOUBLE DEFAULT NULL,
					FIRST_RXLEV_DL_CNT INT(11) DEFAULT NULL,
					FIRST_RXQUAL_DL_SUM DOUBLE DEFAULT NULL,
					FIRST_RXQUAL_DL_CNT INT(11) DEFAULT NULL,
					FIRST_RXLEV_UL_SUM DOUBLE DEFAULT NULL,
					FIRST_RXLEV_UL_CNT INT(11) DEFAULT NULL,
					FIRST_RXQUAL_UL_SUM DOUBLE DEFAULT NULL,
					FIRST_RXQUAL_UL_CNT INT(11) DEFAULT NULL,
					CALL_SETUP_TIME_SUM INT(11) DEFAULT NULL,
					CALL_SETUP_TIME_CNT INT(11) DEFAULT NULL,
					CALL_SETUP_TIME_VOICE_SUM int(11) DEFAULT NULL,
					CALL_SETUP_TIME_VOICE_CNT int(11) DEFAULT NULL,
					CALL_SETUP_TIME_SIG_SUM int(11) DEFAULT NULL,
					CALL_SETUP_TIME_SIG_CNT int(11) DEFAULT NULL,
					CALL_SETUP_TIME_SMS_SUM int(11) DEFAULT NULL,
					CALL_SETUP_TIME_SMS_CNT int(11) DEFAULT NULL,
					CALL_SETUP_TIME_GPRS_SUM int(11) DEFAULT NULL,
					CALL_SETUP_TIME_GPRS_CNT int(11) DEFAULT NULL,
					CALL_SETUP_TIME_OTH_SUM int(11) DEFAULT NULL,
					CALL_SETUP_TIME_OTH_CNT int(11) DEFAULT NULL,
					SF_VOICE_CNT INT(11) DEFAULT NULL,
					SF_GPRS_CNT INT(11) DEFAULT NULL,
					SF_SMS_CNT INT(11) DEFAULT NULL,
					SF_SMS_MT_CNT INT(11) DEFAULT NULL,
					SF_SMS_MO_CNT INT(11) DEFAULT NULL,
					SF_SIGNAL_CNT INT(11) DEFAULT NULL,
					SF_OTHER_CNT INT(11) DEFAULT NULL,
					`MAKE_ID` INT(11) DEFAULT NULL,
					`MODEL_ID` INT(11) DEFAULT NULL,
					',CASE WHEN IMSI_CELL=1 THEN '
					`START_TILE_ID` BIGINT(20) DEFAULT NULL,
					`END_TILE_ID` BIGINT(20) DEFAULT NULL,
					`START_CELL_ID` MEDIUMINT(9) DEFAULT NULL,
					`START_SITE_ID` VARCHAR(20) DEFAULT NULL,
					`START_REG_1_ID` BIGINT(20) DEFAULT NULL,
					`START_REG_2_ID` BIGINT(20) DEFAULT NULL,
					`START_REG_3_ID` BIGINT(20) DEFAULT NULL,
					`END_CELL_ID` MEDIUMINT(9) DEFAULT NULL,
					`END_SITE_ID` VARCHAR(20) DEFAULT NULL,
					`END_REG_1_ID` BIGINT(20) DEFAULT NULL,
					`END_REG_2_ID` BIGINT(20) DEFAULT NULL,
					`END_REG_3_ID` BIGINT(20) DEFAULT NULL,' ELSE '' END,'
					`MAKE_MODEL` VARCHAR(200) DEFAULT NULL
-- 					  ,PRIMARY KEY (`IMSI`,`DATA_DATE`,`DATA_HOUR`)
-- 					  ,KEY `IX_MAKE_ID` (`MAKE_ID`,`MODEL_ID`,`DATA_DATE`,`DATA_HOUR`)
				) ENGINE=MYISAM DEFAULT CHARSET=latin1 DELAY_KEY_WRITE=1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES('gt_gw_main','SP_Generate_Global_Statistic_imsi_gsm',CONCAT(GT_DB,' INSERT INTO tbl_',GT_DB,'_',WORKER_ID), NOW());	
	 	
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.tmp_materialization_imsi_gsm_',WORKER_ID,' 
				(
					`IMSI`,
					`DATA_DATE`,
					`DATA_HOUR`,
					CALL_CNT,
					VOICE_MO_CNT,
					VOICE_MT_CNT,
					DATA_MO_CNT,
					DATA_MT_CNT,
					SMS_MO_CNT,
					SMS_MT_CNT,
					SIGNAL_CNT,
					CALL_DUR_SUM,
					VOICE_DUR_SUM,
					DATA_DUR_SUM,
					DROP_CNT,
					BLOCK_CNT,
					DROP_VOICE_CNT,
					DROP_GPRS_CNT,
					DROP_SMS_CNT,
					DROP_SIGNAL_CNT,
					DROP_OTHER_CNT,					
					BLOCK_VOICE_CNT,
					BLOCK_GPRS_CNT,
					BLOCK_SMS_CNT,
					BLOCK_SMS_MT_CNT,
					BLOCK_SMS_MO_CNT,
					BLOCK_SIGNAL_CNT,
					BLOCK_OTHER_CNT,
					HO_ATTEMPT_CNT,
					HO_FAILURE_CNT,
					MOVING_CALL_CNT,
					INDOOR_CALL_CNT,
					FIRST_RXLEV_DL_SUM,
					FIRST_RXLEV_DL_CNT,
					FIRST_RXQUAL_DL_SUM,
					FIRST_RXQUAL_DL_CNT,
					FIRST_RXLEV_UL_SUM,
					FIRST_RXLEV_UL_CNT,
					FIRST_RXQUAL_UL_SUM,
					FIRST_RXQUAL_UL_CNT,
					CALL_SETUP_TIME_SUM,
					CALL_SETUP_TIME_CNT,
					CALL_SETUP_TIME_VOICE_SUM,
					CALL_SETUP_TIME_VOICE_CNT,
					CALL_SETUP_TIME_SIG_SUM,
					CALL_SETUP_TIME_SIG_CNT,
					CALL_SETUP_TIME_SMS_SUM,
					CALL_SETUP_TIME_SMS_CNT,
					CALL_SETUP_TIME_GPRS_SUM,
					CALL_SETUP_TIME_GPRS_CNT,
					CALL_SETUP_TIME_OTH_SUM,
					CALL_SETUP_TIME_OTH_CNT,
					SF_VOICE_CNT,
					SF_GPRS_CNT,
					SF_SMS_CNT,
					SF_SMS_MT_CNT,
					SF_SMS_MO_CNT,
					SF_SIGNAL_CNT,
					SF_OTHER_CNT,
					MAKE_ID,
					MODEL_ID
					',CASE WHEN IMSI_CELL=1 THEN ',
					START_TILE_ID,
 					END_TILE_ID,
					START_CELL_ID,
					START_SITE_ID,
					END_CELL_ID,
					END_SITE_ID' ELSE '' END,'
				)
				SELECT
					`IMSI`,
					`DATA_DATE`,
					`DATA_HOUR`,
					COUNT(*) AS `CALL_CNT`,
 					SUM(IF(CALL_TYPE=10 AND RR_CONN_CAUSE=1,1,0)) AS VOICE_MO_CNT,
					SUM(IF(CALL_TYPE=10 AND RR_CONN_CAUSE=21,1,0)) AS VOICE_MT_CNT,
					SUM(IF(CALL_TYPE=20 AND RR_CONN_CAUSE=3,1,0)) AS DATA_MO_CNT,
					SUM(IF(CALL_TYPE=20 AND RR_CONN_CAUSE=23,1,0)) AS DATA_MT_CNT,
					SUM(IF(CALL_TYPE=16 AND RR_CONN_CAUSE=5,1,0)) AS SMS_MO_CNT,
					SUM(IF(CALL_TYPE=16 AND RR_CONN_CAUSE=25,1,0)) AS SMS_MT_CNT,
					SUM(IF(CALL_TYPE=15,1,0)) AS SIGNAL_CNT,
					SUM(`DURATION`) AS `CALL_DUR_SUM`,
					SUM(IF(CALL_TYPE=10,DURATION,0)) AS `VOICE_DUR_SUM`,
					SUM(IF(CALL_TYPE=20,DURATION,0)) AS `DATA_DUR_SUM`,
					SUM(IF(CALL_STATUS=2,1,0)) AS DROP_CNT,
					SUM(IF(CALL_STATUS=3,1,0)) AS BLOCK_CNT,
					SUM(IF(CALL_STATUS=2 AND CALL_TYPE=10,1,0)) AS DROP_VOICE_CNT,
					SUM(IF(CALL_STATUS=2 AND CALL_TYPE=20,1,0)) AS DROP_GPRS_CNT,
					SUM(IF(CALL_STATUS=2 AND CALL_TYPE=16,1,0)) AS DROP_SMS_CNT,
					SUM(IF(CALL_STATUS=2 AND CALL_TYPE=15,1,0)) AS DROP_SIGNAL_CNT,
					SUM(IF(CALL_STATUS=2 AND CALL_TYPE NOT IN (10,15,16,20),1,0)) AS DROP_OTHER_CNT,					
					SUM(IF(CALL_STATUS=3 AND CALL_TYPE=10,1,0)) AS BLOCK_VOICE_CNT,
					SUM(IF(CALL_STATUS=3 AND CALL_TYPE=20,1,0)) AS BLOCK_GPRS_CNT,
					SUM(IF(CALL_STATUS=3 AND CALL_TYPE=16,1,0)) AS BLOCK_SMS_CNT,
					SUM(IF(CALL_STATUS=3 AND CALL_TYPE=16 AND RR_CONN_CAUSE=25,1,0)) AS BLOCK_SMS_MT_CNT,
					SUM(IF(CALL_STATUS=3 AND CALL_TYPE=16 AND RR_CONN_CAUSE=5,1,0)) AS BLOCK_SMS_MO_CNT, 
					SUM(IF(CALL_STATUS=3 AND CALL_TYPE=15,1,0)) AS BLOCK_SIGNAL_CNT,
					SUM(IF(CALL_STATUS=3 AND CALL_TYPE NOT IN (10,15,16,20),1,0)) AS BLOCK_OTHER_CNT,
					SUM(HO_ATTEMPT_COUNT) AS HO_ATTEMPT_CNT,
					SUM(HO_FAILURE_COUNT) AS HO_FAILURE_CNT,
					SUM(IF(INDOOR=0 AND MOVING=1,1,0)) AS MOVING_CALL_CNT,
					SUM(IF(INDOOR=1,1,0)) AS INDOOR_CALL_CNT,
					SUM(POS_FIRST_RXLEV_FULL_DOWNLINK) AS FIRST_RXLEV_DL_SUM,
					COUNT(POS_FIRST_RXLEV_FULL_DOWNLINK) AS FIRST_RXLEV_DL_CNT,
					SUM(POS_FIRST_RXQUAL_FULL_DOWNLINK) AS FIRST_RXQUAL_DL_SUM,
					COUNT(POS_FIRST_RXQUAL_FULL_DOWNLINK) AS FIRST_RXQUAL_DL_CNT,
 					SUM(POS_FIRST_RXLEV_FULL_UPLINK) AS FIRST_RXLEV_UL_SUM,
					COUNT(POS_FIRST_RXLEV_FULL_UPLINK) AS FIRST_RXLEV_UL_CNT,
					SUM(POS_FIRST_RXQUAL_FULL_UPLINK) AS FIRST_RXQUAL_UL_SUM,
					COUNT(POS_FIRST_RXQUAL_FULL_UPLINK) AS FIRST_RXQUAL_UL_CNT,
					SUM(CALL_SETUP_TIME) AS CALL_SETUP_TIME_SUM,
					SUM(IF(CALL_SETUP_TIME>=0,1,0)) AS CALL_SETUP_TIME_CNT,
					
					IFNULL(SUM(IF(CALL_TYPE =10,CALL_SETUP_TIME,0)),0) AS CALL_SETUP_TIME_VOICE_SUM,
					IFNULL(SUM(IF(CALL_SETUP_TIME>=0 AND CALL_TYPE =10,1,0)),0) AS CALL_SETUP_TIME_VOICE_CNT,
					IFNULL(SUM(IF(CALL_TYPE =15,CALL_SETUP_TIME,0)),0) AS CALL_SETUP_TIME_SIG_SUM,
					IFNULL(SUM(IF(CALL_SETUP_TIME>=0 AND CALL_TYPE =15,1,0)),0) AS CALL_SETUP_TIME_SIG_CNT,
					IFNULL(SUM(IF(CALL_TYPE =16,CALL_SETUP_TIME,0)),0) AS CALL_SETUP_TIME_SMS_SUM,
					IFNULL(SUM(IF(CALL_SETUP_TIME>=0 AND CALL_TYPE =16,1,0)),0) AS CALL_SETUP_TIME_SMS_CNT,
					IFNULL(SUM(IF(CALL_TYPE =20,CALL_SETUP_TIME,0)),0) AS CALL_SETUP_TIME_GPRS_SUM,
					IFNULL(SUM(IF(CALL_SETUP_TIME>=0 AND CALL_TYPE =20,1,0)),0) AS CALL_SETUP_TIME_GPRS_CNT,
					IFNULL(SUM(IF(CALL_TYPE NOT IN (10,15,16,20),CALL_SETUP_TIME,0)),0) AS CALL_SETUP_TIME_OTH_SUM,
					IFNULL(SUM(IF(CALL_SETUP_TIME>=0 AND CALL_TYPE NOT IN (10,15,16,20),1,0)),0) AS CALL_SETUP_TIME_OTH_CNT,
					
					SUM(IF(CALL_STATUS=6 AND CALL_TYPE=10,1,0)) AS SF_VOICE_CNT,
					SUM(IF(CALL_STATUS=6 AND CALL_TYPE=20,1,0)) AS SF_GPRS_CNT,
					SUM(IF(CALL_STATUS=6 AND CALL_TYPE=16,1,0)) AS SF_SMS_CNT,
					SUM(IF(CALL_STATUS=6 AND CALL_TYPE=16 AND RR_CONN_CAUSE=25,1,0)) AS SF_SMS_MT_CNT,
					SUM(IF(CALL_STATUS=6 AND CALL_TYPE=16 AND RR_CONN_CAUSE=5,1,0))  AS SF_SMS_MO_CNT,
					SUM(IF(CALL_STATUS=6 AND CALL_TYPE=15,1,0)) AS SF_SIGNAL_CNT,
					SUM(IF(CALL_STATUS=6 AND CALL_TYPE NOT IN (10,15,16,20),1,0)) AS SF_OTHER_CNT,
					`MAKE_ID`,
					`MODEL_ID`
					',CASE WHEN IMSI_CELL=1 THEN CONCAT(',
					gt_covmo_proj_geohash_to_hex_geohash(POS_FIRST_LOC,',@ZOOM_LEVEL,') AS START_TILE_ID,
 					gt_covmo_proj_geohash_to_hex_geohash(POS_LAST_LOC,',@ZOOM_LEVEL,') AS END_TILE_ID, 					
					POS_FIRST_CELL AS `START_CELL_ID`,
					POS_FIRST_SITE AS `START_SITE_ID`,
					POS_LAST_CELL AS `END_CELL_ID`,
					POS_LAST_SITE AS `END_SITE_ID`') ELSE '' END,'
					FROM ',GT_DB,'.table_call_gsm
					WHERE DATA_HOUR =',DATA_HOUR,' AND IMSI IS NOT NULL AND IMSI<>''0''
					GROUP BY IMSI
					ORDER BY NULL;
				');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('SELECT * FROM ',GT_DB,'.tmp_materialization_imsi_gsm_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_materialization_imsi_gsm_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	INSERT INTO gt_gw_main.sp_log VALUES('gt_gw_main','SP_Generate_Global_Statistic_imsi_gsm',CONCAT(GT_DB,' END'), NOW());
	
END$$
DELIMITER ;
