DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Grant_Specify_User_DB_TBL`(IN USERNAME VARCHAR(100), IN DB VARCHAR(100), IN TBL_NAME VARCHAR(100))
BEGIN
	SELECT COUNT(*) INTO @table_count FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = DB AND `TABLE_NAME` = TBL_NAME;
	
	IF @table_count > 0 THEN
		SET @SqlCmd =CONCAT('GRANT SELECT ON ',DB,'.',TBL_NAME,' TO ',USERNAME,'@''%'' ;');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
	END IF;
	
	FLUSH PRIVILEGES;
END$$
DELIMITER ;
