DELIMITER $$
USE `gt_global_statistic`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Generate_Global_Statistic_ZoomLevel`(IN DB_NAME VARCHAR(100),IN ZL CHAR(2),IN TBL_NAME VARCHAR(100))
BEGIN
	DECLARE REP_NAME VARCHAR(100) DEFAULT 'tile_';
 	DECLARE TARGET_TBL_NAME VARCHAR(100) DEFAULT CONCAT('tile_',ZL,'_');
	SET @SqlCmd=CONCAT('CREATE TABLE ',GT_DB,'.',REPLACE(TBL_NAME,REP_NAME,TARGET_TBL_NAME),' LIKE ',GT_DB,'.',TBL_NAME,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
END$$
DELIMITER ;
