DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Generate_Global_Statistic_tile_lte`(IN DATA_DATE DATE,IN DATA_HOUR TINYINT(2),IN PU_ID MEDIUMINT(9),IN TECH_MASK TINYINT(2), IN GT_DB VARCHAR(100))
BEGIN
	DECLARE WORKER_ID VARCHAR(10) DEFAULT CONNECTION_ID();
	
	DECLARE STR_START_END_LTE MEDIUMTEXT DEFAULT '';
	DECLARE STR_START_SUM_LTE MEDIUMTEXT DEFAULT '';
	DECLARE STR_END_SUM_LTE MEDIUMTEXT DEFAULT '';
	DECLARE STR_SEL_START_LTE MEDIUMTEXT DEFAULT '';
	DECLARE STR_SEL_END_LTE MEDIUMTEXT DEFAULT '';
	
	SET @ZOOM_LEVEL1 = gt_covmo_csv_get('13,16',1);
	SET @ZOOM_LEVEL2 = gt_covmo_csv_get('13,16',2);
	SELECT att_value INTO @ZOOM_LEVEL3 FROM gt_covmo.`sys_config` WHERE `group_name`='system' AND att_name = 'MapResolution';
	
	SET @TILE_ID_LVL1 = CONCAT('TILE_ID_',gt_covmo_csv_get('13,16',1));
	SET @TILE_ID_LVL2 = CONCAT('TILE_ID_',gt_covmo_csv_get('13,16',2));
		
	SET @FLAG_IMSI_HR=0;
	SET @FLAG_IMSI_DY=0;
	SET @FLAG_MAKE_HR=0;
	SET @FLAG_MAKE_DY=0;
	
	SET STR_START_END_LTE=CONCAT('POS_FIRST_TILE,POS_FIRST_LOC,POS_FIRST_S_EARFCN,POS_FIRST_S_EUTRABAND,DATA_DATE,DATA_HOUR,
					CALL_TYPE,CALL_STATUS,POS_FIRST_S_RSRP,POS_FIRST_S_RSRQ,
					POS_LAST_TILE,POS_LAST_LOC,POS_LAST_S_EARFCN,POS_LAST_S_EUTRABAND,`DURATION`,
					`X2_HO_INTER_ATTEMPT`,`S1_HO_INTER_ATTEMPT`,`X2_HO_INTER_FAILURE`,`S1_HO_INTER_FAILURE`,
					`X2_HO_INTRA_ATTEMPT`,`S1_HO_INTRA_ATTEMPT`,`X2_HO_INTRA_FAILURE`,`S1_HO_INTRA_FAILURE`,
					IRAT_TO_UMTS_ATTEMPT,IRAT_TO_UMTS_FAILURE,IRAT_TO_GERAN_ATTEMPT,IRAT_TO_GERAN_FAILURE');
	
	SET STR_START_SUM_LTE=CONCAT('POS_FIRST_TILE AS TILE_ID,
 					gt_geohash_ext(POS_FIRST_LOC,',@ZOOM_LEVEL2,') AS ',@TILE_ID_LVL2,',
 					gt_geohash_ext(POS_FIRST_LOC,',@ZOOM_LEVEL1,') AS ',@TILE_ID_LVL1,',
					POS_FIRST_S_EARFCN AS EARFCN,
					POS_FIRST_S_EUTRABAND AS EUTRABAND ,
					DATA_DATE,
					DATA_HOUR,
					COUNT(*) AS `INIT_CALL_CNT`,
					SUM(IF(CALL_TYPE=22,1,0)) AS `SIGNAL_CNT`,
					SUM(IF(CALL_TYPE=21,1,0)) AS `DATA_CNT`,
					SUM(IF(CALL_TYPE=29,1,0)) AS `UNSPECIFIED_CNT`,
					SUM(IF(CALL_STATUS=3,1,0)) AS `BLOCK_CNT`,
					SUM(POS_FIRST_S_RSRP) AS `RSRP_SUM`,
					COUNT(POS_FIRST_S_RSRP) AS `RSRP_CNT`,
					SUM(POS_FIRST_S_RSRQ) AS `RSRQ_SUM`,
					COUNT(POS_FIRST_S_RSRQ) AS `RSRQ_CNT`');
	SET STR_END_SUM_LTE=CONCAT('POS_LAST_TILE AS TILE_ID,
 					gt_geohash_ext(POS_LAST_LOC,',@ZOOM_LEVEL2,') AS ',@TILE_ID_LVL2,',
 					gt_geohash_ext(POS_LAST_LOC,',@ZOOM_LEVEL1,') AS ',@TILE_ID_LVL1,',
					POS_LAST_S_EARFCN AS EARFCN,
					POS_LAST_S_EUTRABAND AS EUTRABAND ,
					DATA_DATE,
					DATA_HOUR,
					COUNT(*) AS `END_CALL_CNT`,
					SUM(`DURATION`) AS `CALL_DUR_SUM`,
					SUM(IF(CALL_STATUS=2,1,0)) AS `DROP_CNT`,
					SUM(IF(CALL_STATUS=5,1,0)) AS `CSFB_CNT`,
					SUM(IFNULL(`X2_HO_INTER_ATTEMPT`,0)+IFNULL(`S1_HO_INTER_ATTEMPT`,0)) AS `INTER_FREQ_ATTEMPT_CNT`,
					SUM(IFNULL(`X2_HO_INTER_FAILURE`,0)+IFNULL(`S1_HO_INTER_FAILURE`,0)) AS `INTER_FREQ_FAILURE_CNT`,
					SUM(IFNULL(`X2_HO_INTRA_ATTEMPT`,0)+IFNULL(`S1_HO_INTRA_ATTEMPT`,0)) AS `INTRA_FREQ_ATTEMPT_CNT`,
					SUM(IFNULL(`X2_HO_INTRA_FAILURE`,0)+IFNULL(`S1_HO_INTRA_FAILURE`,0)) AS `INTRA_FREQ_FAILURE_CNT`,
					SUM(IRAT_TO_UMTS_ATTEMPT) AS `4G_3G_ATTEMPT_CNT`,
					SUM(IRAT_TO_UMTS_FAILURE) AS `4G_3G_FAILURE_CNT`,
					SUM(IRAT_TO_GERAN_ATTEMPT) AS `4G_2G_ATTEMPT_CNT`,
					SUM(IRAT_TO_GERAN_FAILURE) AS `4G_2G_FAILURE_CNT`,
					SUM(IF(CALL_STATUS=2 AND CALL_TYPE=22,1,0)) AS `DROP_SIGNAL_CNT`,
					SUM(IF(CALL_STATUS=2 AND CALL_TYPE=21,1,0)) AS `DROP_DATA_CNT`,
					SUM(IF(CALL_STATUS=2 AND CALL_TYPE=24,1,0)) AS `DROP_SMS_CNT`,
					SUM(IF(CALL_STATUS=2 AND CALL_TYPE=23,1,0)) AS `DROP_VOLTE_CNT`,
					SUM(IF(CALL_STATUS=2 AND CALL_TYPE=29,1,0)) AS `DROP_UNSPECIFIED_CNT`,
					SUM(IF(CALL_STATUS IN (1,2,4,5),1,0)) AS `END_NON_BLOCK_CALL_CNT`,
					SUM(IF(CALL_STATUS IN (1,2,4,5) AND CALL_TYPE=22,1,0)) AS `END_NON_BLOCK_SIGNAL_CNT`,
					SUM(IF(CALL_STATUS IN (1,2,4,5) AND CALL_TYPE=21,1,0)) AS `END_NON_BLOCK_DATA_CNT`');
					
	INSERT INTO gt_gw_main.sp_log VALUES('gt_gw_main','SP_Generate_Global_Statistic_tile_lte',CONCAT(GT_DB,' CREATE TEMPORARY TABLE tmp_materialization_',WORKER_ID), NOW());	
	
	SET SESSION group_concat_max_len=102400; 
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_materialization_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,'.tmp_materialization_',WORKER_ID,' (
				  `TILE_ID` BIGINT(20) NOT NULL,
				  `',@TILE_ID_LVL2,'` BIGINT(20)  NULL,
				  `',@TILE_ID_LVL1,'` BIGINT(20)  NULL,
				  `EARFCN` MEDIUMINT(9) NOT NULL,
				  `EUTRABAND` SMALLINT(6) NOT NULL,
				  `DATA_DATE` DATETIME NOT NULL,
				  `DATA_HOUR` TINYINT(4) NOT NULL,
				  `INIT_CALL_CNT` INT(11) DEFAULT NULL,
				  `END_CALL_CNT` INT(11) DEFAULT NULL,
				  `SIGNAL_CNT` INT(11) DEFAULT NULL,
				  `DATA_CNT` INT(11) DEFAULT NULL,
				  `UNSPECIFIED_CNT` INT(11) DEFAULT NULL,
				  `CALL_DUR_SUM` DOUBLE DEFAULT NULL,
				  `BLOCK_CNT` INT(11) DEFAULT NULL,
				  `DROP_CNT` INT(11) DEFAULT NULL,
				  `CSFB_CNT` INT(11) DEFAULT NULL,
				  `INTER_FREQ_ATTEMPT_CNT` INT(11) DEFAULT NULL,
				  `INTER_FREQ_FAILURE_CNT` INT(11) DEFAULT NULL,
				  `INTRA_FREQ_ATTEMPT_CNT` INT(11) DEFAULT NULL,
				  `INTRA_FREQ_FAILURE_CNT` INT(11) DEFAULT NULL,
				  `4G_3G_ATTEMPT_CNT` INT(11) DEFAULT NULL,
				  `4G_3G_FAILURE_CNT` INT(11) DEFAULT NULL,
				  `4G_2G_ATTEMPT_CNT` INT(11) DEFAULT NULL,
				  `4G_2G_FAILURE_CNT` INT(11) DEFAULT NULL,
				  `PS_UL_VOLUME_SUM` DOUBLE DEFAULT NULL,
				  `PS_DL_VOLUME_SUM` DOUBLE DEFAULT NULL,
				  `PS_UL_SPEED_MAX` DOUBLE DEFAULT NULL,
				  `PS_DL_SPEED_MAX` DOUBLE DEFAULT NULL,
				  `RSRP_SUM` DOUBLE DEFAULT NULL,
				  `RSRP_CNT` INT(11) DEFAULT NULL,
				  `RSRQ_SUM` DOUBLE DEFAULT NULL,
				  `RSRQ_CNT` INT(11) DEFAULT NULL,
				  `PILOT_DOMINANCE_SUM` INT(11) DEFAULT NULL,
				  `PILOT_DOMINANCE_CNT` INT(11) DEFAULT NULL,
				  `DROP_SIGNAL_CNT` INT(11) DEFAULT NULL,
				  `DROP_DATA_CNT` INT(11) DEFAULT NULL,
				  `DROP_SMS_CNT` INT(11) DEFAULT NULL,
				  `DROP_VOLTE_CNT` INT(11) DEFAULT NULL,
				  `DROP_UNSPECIFIED_CNT` INT(11) DEFAULT NULL,
				  `END_NON_BLOCK_CALL_CNT` INT(11) DEFAULT NULL,
				  `REG_1_ID` BIGINT(20) DEFAULT NULL,
				  `REG_2_ID` BIGINT(20) DEFAULT NULL,
				  `REG_3_ID` BIGINT(20) DEFAULT NULL,
				  `UL_THROUPUT_SUM` DOUBLE DEFAULT NULL,
				  `UL_THROUPUT_CNT` INT(11) DEFAULT NULL,
				  `DL_THROUPUT_SUM` DOUBLE DEFAULT NULL,
				  `DL_THROUPUT_CNT` INT(11) DEFAULT NULL,
				  `END_NON_BLOCK_SIGNAL_CNT` INT(11) DEFAULT NULL,
				  `END_NON_BLOCK_DATA_CNT` INT(11) DEFAULT NULL,
				  `MR_4G_RSRP_SERVING_SUM` DOUBLE DEFAULT NULL,
				  `MR_4G_RSRP_SERVING_CNT` INT(11) DEFAULT NULL,
				  `MR_4G_RSRQ_SERVING_SUM` DOUBLE DEFAULT NULL,
				  `MR_4G_RSRQ_SERVING_CNT` INT(11) DEFAULT NULL
				  ,PRIMARY KEY (`TILE_ID`,`EARFCN`,`EUTRABAND`,`DATA_DATE`,`DATA_HOUR`)
				) ENGINE=MYISAM DEFAULT CHARSET=latin1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES('gt_gw_main','SP_Generate_Global_Statistic_tile_lte',CONCAT(GT_DB,' INSERT INTO tbl_',GT_DB,'_',WORKER_ID), NOW());	
	 
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_tile_start_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,'.tmp_tile_start_',WORKER_ID,' (
				  `TILE_ID` BIGINT(20) NOT NULL,
				  `',@TILE_ID_LVL2,'` BIGINT(20) NOT NULL,
				  `',@TILE_ID_LVL1,'` BIGINT(20) NOT NULL,
				  `EARFCN` MEDIUMINT(9) NOT NULL,
				  `EUTRABAND` SMALLINT(6) NOT NULL,
				  `DATA_DATE` DATETIME NOT NULL,
				  `DATA_HOUR` TINYINT(4) NOT NULL,
				  `INIT_CALL_CNT` INT(11) DEFAULT NULL,
				  `SIGNAL_CNT` INT(11) DEFAULT NULL,
				  `DATA_CNT` INT(11) DEFAULT NULL,
				  `UNSPECIFIED_CNT` INT(11) DEFAULT NULL,
				  `BLOCK_CNT` INT(11) DEFAULT NULL,
				  `RSRP_SUM` DOUBLE DEFAULT NULL,
				  `RSRP_CNT` INT(11) DEFAULT NULL,
				  `RSRQ_SUM` DOUBLE DEFAULT NULL,
				  `RSRQ_CNT` INT(11) DEFAULT NULL
				  ,PRIMARY KEY (`TILE_ID`,`EARFCN`,`EUTRABAND`)
				) ENGINE=MYISAM DEFAULT CHARSET=latin1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_tile_end_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,'.tmp_tile_end_',WORKER_ID,' (
				  `TILE_ID` BIGINT(20) NOT NULL,
				  `',@TILE_ID_LVL2,'` BIGINT(20) NOT NULL,
				  `',@TILE_ID_LVL1,'` BIGINT(20) NOT NULL,
				  `EARFCN` MEDIUMINT(9) NOT NULL,
				  `EUTRABAND` SMALLINT(6) NOT NULL,
				  `DATA_DATE` DATETIME NOT NULL,
				  `DATA_HOUR` TINYINT(4) NOT NULL,
				  `END_CALL_CNT` INT(11) DEFAULT NULL,
				  `CALL_DUR_SUM` DOUBLE DEFAULT NULL,
				  `DROP_CNT` INT(11) DEFAULT NULL,
				  `CSFB_CNT` INT(11) DEFAULT NULL,
				  `INTER_FREQ_ATTEMPT_CNT` INT(11) DEFAULT NULL,
				  `INTER_FREQ_FAILURE_CNT` INT(11) DEFAULT NULL,
				  `INTRA_FREQ_ATTEMPT_CNT` INT(11) DEFAULT NULL,
				  `INTRA_FREQ_FAILURE_CNT` INT(11) DEFAULT NULL,
				  `4G_3G_ATTEMPT_CNT` INT(11) DEFAULT NULL,
				  `4G_3G_FAILURE_CNT` INT(11) DEFAULT NULL,
				  `4G_2G_ATTEMPT_CNT` INT(11) DEFAULT NULL,
				  `4G_2G_FAILURE_CNT` INT(11) DEFAULT NULL,
				  `DROP_SIGNAL_CNT` INT(11) DEFAULT NULL,
				  `DROP_DATA_CNT` INT(11) DEFAULT NULL,
				  `DROP_SMS_CNT` INT(11) DEFAULT NULL,
				  `DROP_VOLTE_CNT` INT(11) DEFAULT NULL,
				  `DROP_UNSPECIFIED_CNT` INT(11) DEFAULT NULL,
				  `END_NON_BLOCK_CALL_CNT` INT(11) DEFAULT NULL,
				  `END_NON_BLOCK_SIGNAL_CNT` INT(11) DEFAULT NULL,
				  `END_NON_BLOCK_DATA_CNT` INT(11) DEFAULT NULL
				  ,PRIMARY KEY (`TILE_ID`,`EARFCN`,`EUTRABAND`)
				) ENGINE=MYISAM DEFAULT CHARSET=latin1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @v_i=DATA_HOUR;
	SET @v_i_Max=DATA_HOUR+1;
	SET @v_j=0;
				
	WHILE @v_i < @v_i_Max DO
	BEGIN	
		WHILE @v_j<60  DO
		BEGIN		
			IF (@v_j=45) THEN 
				SET @UNION=' '; 
			ELSE
				SET @UNION=' UNION '; 
			END IF;	
			SET STR_SEL_START_LTE=CONCAT(STR_SEL_START_LTE,'SELECT ',STR_START_END_LTE,' FROM ',GT_DB,'.table_call_lte',CONCAT('_',LPAD(@v_i,2,'0'),LPAD(@v_j,2,'0')),' WHERE DATA_HOUR=', @v_i,@UNION); 
			SET STR_SEL_END_LTE=CONCAT(STR_SEL_END_LTE,'SELECT ',STR_START_END_LTE,' FROM ',GT_DB,'.table_call_lte',CONCAT('_',LPAD(@v_i,2,'0'),LPAD(@v_j,2,'0')),' WHERE DATA_HOUR=', @v_i,@UNION); 
			SET @v_j=@v_j+15;
		END;
		END WHILE;
			
		SET @v_j=0;
		SET @v_i=@v_i+1;
	END;
	END WHILE;	
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.tmp_tile_start_',WORKER_ID,' 
				(TILE_ID,',@TILE_ID_LVL2,',',@TILE_ID_LVL1,',EARFCN,EUTRABAND,DATA_DATE,DATA_HOUR
					,INIT_CALL_CNT,SIGNAL_CNT,DATA_CNT,UNSPECIFIED_CNT,BLOCK_CNT,RSRP_SUM,RSRP_CNT,RSRQ_SUM,RSRQ_CNT)
				SELECT ',STR_START_SUM_LTE,' 
				FROM (',STR_SEL_START_LTE,') AA
				GROUP BY POS_FIRST_TILE,POS_FIRST_S_EARFCN,POS_FIRST_S_EUTRABAND
				ORDER BY NULL;
				');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.tmp_tile_end_',WORKER_ID,' 
				(TILE_ID,',@TILE_ID_LVL2,',',@TILE_ID_LVL1,',EARFCN,EUTRABAND,DATA_DATE,DATA_HOUR
				,END_CALL_CNT,CALL_DUR_SUM,DROP_CNT,CSFB_CNT
				,`INTER_FREQ_ATTEMPT_CNT`,`INTER_FREQ_FAILURE_CNT`,`INTRA_FREQ_ATTEMPT_CNT`,`INTRA_FREQ_FAILURE_CNT`
				,4G_3G_ATTEMPT_CNT,4G_3G_FAILURE_CNT,4G_2G_ATTEMPT_CNT,4G_2G_FAILURE_CNT
				,DROP_SIGNAL_CNT,DROP_DATA_CNT,DROP_SMS_CNT,DROP_VOLTE_CNT,DROP_UNSPECIFIED_CNT,`END_NON_BLOCK_CALL_CNT`
				,`END_NON_BLOCK_SIGNAL_CNT`,`END_NON_BLOCK_DATA_CNT`
				)
				SELECT ',STR_END_SUM_LTE,' 
				FROM (',STR_SEL_END_LTE,') AA
				GROUP BY POS_LAST_TILE,POS_LAST_S_EARFCN,POS_LAST_S_EUTRABAND
				ORDER BY NULL;
				');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE INDEX `ix_tile_fq` ON ',GT_DB,'.tmp_tile_start_',WORKER_ID,' (TILE_ID,EARFCN,EUTRABAND);');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE INDEX `ix_tile_fq` ON ',GT_DB,'.tmp_tile_end_',WORKER_ID,' (TILE_ID,EARFCN,EUTRABAND);');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.`tmp_materialization_',WORKER_ID,'` 
				(
				`TILE_ID`,
				`',@TILE_ID_LVL2,'`,
				`',@TILE_ID_LVL1,'`,
				`EARFCN`,
				`EUTRABAND`,
				`DATA_DATE`,
				`DATA_HOUR`,
				`MR_4G_RSRP_SERVING_SUM`,
				`MR_4G_RSRP_SERVING_CNT`,
				`MR_4G_RSRQ_SERVING_SUM`,
				`MR_4G_RSRQ_SERVING_CNT`,
				`PS_UL_VOLUME_SUM`,
				`PS_DL_VOLUME_SUM`,
				`PS_UL_SPEED_MAX`,
				`PS_DL_SPEED_MAX`,
				`UL_THROUPUT_SUM`,
				`UL_THROUPUT_CNT`,
				`DL_THROUPUT_SUM`,
				`DL_THROUPUT_CNT`
				)				
				SELECT 
					TILE_ID AS TILE_ID,
 					gt_geohash_ext(`TILE_ID`,16) AS ',@TILE_ID_LVL2,',
 					gt_geohash_ext(`TILE_ID`,13) AS ',@TILE_ID_LVL1,',
					EARFCN AS EARFCN,
					EUTRABAND AS EUTRABAND,
					DATA_DATE,
					DATA_HOUR,
					SUM(MR_4G_RSRP_SERVING_SUM),
					SUM(MR_4G_RSRP_SERVING_CNT),
					SUM(MR_4G_RSRQ_SERVING_SUM),
					SUM(MR_4G_RSRQ_SERVING_CNT),
					SUM(UL_VOLUME_SUM) AS `PS_UL_VOLUME_SUM`,
					SUM(DL_VOLUME_SUM) AS `PS_DL_VOLUME_SUM`,
					MAX((UL_THROUPUT_SUM)/(UL_THROUPUT_CNT)) AS `PS_UL_SPEED_MAX`,
					MAX((DL_THROUPUT_SUM)/(DL_THROUPUT_CNT)) AS `PS_DL_SPEED_MAX`,
					SUM(UL_THROUPUT_SUM) AS `UL_THROUPUT_SUM`,
					SUM(UL_THROUPUT_CNT) AS `UL_THROUPUT_CNT`,
					SUM(DL_THROUPUT_SUM) AS `DL_THROUPUT_SUM`,
					SUM(DL_THROUPUT_CNT) AS `DL_THROUPUT_CNT`
				FROM ',GT_DB,'.rpt_tile_position
				WHERE DATA_HOUR =',DATA_HOUR,' 
				GROUP BY TILE_ID,EARFCN,EUTRABAND
				ORDER BY NULL;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('UPDATE ',GT_DB,'.`tmp_materialization_',WORKER_ID,'` a,',GT_DB,'.`tmp_tile_start_',WORKER_ID,'` B
				SET 
				A.',@TILE_ID_LVL2,'=CASE WHEN A.',@TILE_ID_LVL2,' IS NULL THEN B.',@TILE_ID_LVL2,' ELSE A.',@TILE_ID_LVL2,' END
				,A.',@TILE_ID_LVL1,'=CASE WHEN A.',@TILE_ID_LVL1,' IS NULL THEN B.',@TILE_ID_LVL1,' ELSE A.',@TILE_ID_LVL1,' END
				,A.`INIT_CALL_CNT`=B.INIT_CALL_CNT
				,A.`SIGNAL_CNT`=B.SIGNAL_CNT
				,A.`DATA_CNT`=B.DATA_CNT
				,A.`UNSPECIFIED_CNT`=B.UNSPECIFIED_CNT
				,A.`BLOCK_CNT`=B.BLOCK_CNT
				,A.`RSRP_SUM`=B.RSRP_SUM
				,A.`RSRP_CNT`=B.RSRP_CNT
				,A.`RSRQ_SUM`=B.RSRQ_SUM
				,A.`RSRQ_CNT`=B.RSRQ_CNT
				WHERE A.TILE_ID=B.TILE_ID AND
					A.EARFCN=B.EARFCN AND 
					A.EUTRABAND=B.EUTRABAND
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('UPDATE ',GT_DB,'.`tmp_materialization_',WORKER_ID,'` a,',GT_DB,'.`tmp_tile_end_',WORKER_ID,'` B
				SET
				A.',@TILE_ID_LVL2,'=CASE WHEN A.',@TILE_ID_LVL2,' IS NULL THEN B.',@TILE_ID_LVL2,' ELSE A.',@TILE_ID_LVL2,' END
				,A.',@TILE_ID_LVL1,'=CASE WHEN A.',@TILE_ID_LVL1,' IS NULL THEN B.',@TILE_ID_LVL1,' ELSE A.',@TILE_ID_LVL1,' END
				,A.`END_CALL_CNT`=B.END_CALL_CNT
				,A.`CALL_DUR_SUM`=B.CALL_DUR_SUM
				,A.`DROP_CNT`=B.DROP_CNT
				,A.`CSFB_CNT`=B.CSFB_CNT
				,A.`INTER_FREQ_ATTEMPT_CNT`=B.`INTER_FREQ_ATTEMPT_CNT`
				,A.`INTER_FREQ_FAILURE_CNT`=B.`INTER_FREQ_FAILURE_CNT`
				,A.`INTRA_FREQ_ATTEMPT_CNT`=B.`INTRA_FREQ_ATTEMPT_CNT`
				,A.`INTRA_FREQ_FAILURE_CNT`=B.`INTRA_FREQ_FAILURE_CNT`
				,A.`4G_3G_ATTEMPT_CNT`=B.4G_3G_ATTEMPT_CNT
				,A.`4G_3G_FAILURE_CNT`=B.4G_3G_FAILURE_CNT
				,A.`4G_2G_ATTEMPT_CNT`=B.4G_2G_ATTEMPT_CNT
				,A.`4G_2G_FAILURE_CNT`=B.4G_2G_FAILURE_CNT
				,A.`DROP_SIGNAL_CNT`=B.DROP_SIGNAL_CNT
				,A.`DROP_DATA_CNT`=B.DROP_DATA_CNT
				,A.`END_NON_BLOCK_CALL_CNT`=B.END_NON_BLOCK_CALL_CNT
				,A.`END_NON_BLOCK_SIGNAL_CNT`=B.END_NON_BLOCK_SIGNAL_CNT
				,A.`END_NON_BLOCK_DATA_CNT`=B.END_NON_BLOCK_DATA_CNT
				WHERE A.TILE_ID=B.TILE_ID AND
					A.EARFCN=B.EARFCN AND 
					A.EUTRABAND=B.EUTRABAND
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('SELECT * FROM ',GT_DB,'.tmp_materialization_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_materialization_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_tile_start_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_tile_end_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_tile_fp_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES('gt_gw_main','SP_Generate_Global_Statistic_tile_lte',CONCAT(GT_DB,' END'), NOW());
	
END$$
DELIMITER ;
