DELIMITER $$
USE `gt_global_statistic`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Generate_Global_Statistic_DS_Aggr_ONE`(IN TECH_MASK TINYINT(2),IN WORKER_ID VARCHAR(10),IN exDate VARCHAR(10))
BEGIN
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE STEP_START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE SP_Process VARCHAR(100) DEFAULT NULL;
	DECLARE KPI_ERROR CONDITION FOR SQLSTATE '99999' ;
	DECLARE FIRSTDAY_OF_WEEK TINYINT(4) DEFAULT 6;
	DECLARE v_DATA_DATE VARCHAR(10) DEFAULT NULL;
	DECLARE v_DATA_HOUR TINYINT(2) DEFAULT NULL;
	DECLARE v_PU_ID MEDIUMINT(9) DEFAULT NULL;
	DECLARE v_TECH_MASK TINYINT(2) DEFAULT NULL;
			
	DECLARE TILE_DS_COLUMN_STR VARCHAR(1500) DEFAULT 
		'RSRP_SUM,
		RSRP_CNT,
		RSCP_SUM,
		RSCP_CNT,
		RXLEV_SUM,
		RXLEV_CNT,
		RSRQ_SUM,
		RSRQ_CNT,
		ECNO_SUM,
		ECNO_CNT,
		RXQUAL_SUM,
		RXQUAL_CNT,
		2G_CALL_CNT,
		2G_PS_CALL_CNT,
		2G_VOICE_DROP_CNT,
		2G_GPRS_DROP_CNT,
		2G_SMS_DROP_CNT,
		2G_CS_CALL_DURATION,
		3G_CS_CALL_CNT,
		3G_PS_CALL_CNT,
		3G_VOICE_DROP_CNT,
		3G_PS_DROP_CNT,
-- 		3G_VEDIO_DROP_CNT,
-- 		3G_SMS_DROP_CNT,
-- 		3G_R99_DROP_CNT,
-- 		3G_HSPA_DROP_CNT,
-- 		3G_PS_OTHER_DROP_CNT,
		3G_CS_CALL_DURATION,
		3G_UL_VOLUME,
		3G_DL_VOLUME,
		3G_UL_THROUPUT_SUM,
		3G_UL_THROUPUT_CNT,
		3G_DL_THROUPUT_SUM,
		3G_DL_THROUPUT_CNT,
		4G_CALL_CNT,
		4G_TRAFFIC_DROP_CNT,
		4G_SIGNAL_DROP_CNT,
-- 		4G_VOLTE_DROP_CNT,
		4G_UL_VOLUME,
		4G_DL_VOLUME,
		4G_UL_THROUPUT_SUM,
		4G_UL_THROUPUT_CNT,
		4G_DL_THROUPUT_SUM,
		4G_DL_THROUPUT_CNT';
		  
	DECLARE TILE_DS_COLUMN_IFNULL_STR VARCHAR(3000) DEFAULT 
		'IFNULL(RSRP_SUM,0) AS RSRP_SUM,
		IFNULL(RSRP_CNT,0) AS RSRP_CNT,
		IFNULL(RSCP_SUM,0) AS RSCP_SUM,
		IFNULL(RSCP_CNT,0) AS RSCP_CNT,
		IFNULL(RXLEV_SUM,0) AS RXLEV_SUM,
		IFNULL(RXLEV_CNT,0) AS RXLEV_CNT,
		IFNULL(RSRQ_SUM,0) AS RSRQ_SUM,
		IFNULL(RSRQ_CNT,0) AS RSRQ_CNT,
		IFNULL(ECNO_SUM,0) AS ECNO_SUM,
		IFNULL(ECNO_CNT,0) AS ECNO_CNT,
		IFNULL(RXQUAL_SUM,0) AS RXQUAL_SUM,
		IFNULL(RXQUAL_CNT,0) AS RXQUAL_CNT,
		IFNULL(2G_CALL_CNT,0) AS 2G_CALL_CNT,
		IFNULL(2G_PS_CALL_CNT,0) AS 2G_PS_CALL_CNT,
		IFNULL(2G_VOICE_DROP_CNT,0) AS 2G_VOICE_DROP_CNT,
		IFNULL(2G_GPRS_DROP_CNT,0) AS 2G_GPRS_DROP_CNT,
		IFNULL(2G_SMS_DROP_CNT,0) AS 2G_SMS_DROP_CNT,
		IFNULL(2G_CS_CALL_DURATION,0) AS 2G_CS_CALL_DURATION,
		IFNULL(3G_CS_CALL_CNT,0) AS 3G_CS_CALL_CNT,
		IFNULL(3G_PS_CALL_CNT,0) AS 3G_PS_CALL_CNT,
		IFNULL(3G_VOICE_DROP_CNT,0) AS 3G_VOICE_DROP_CNT,
 		IFNULL(3G_PS_DROP_CNT,0) AS 3G_PS_DROP_CNT,
-- 		IFNULL(3G_VEDIO_DROP_CNT,0) AS 3G_VEDIO_DROP_CNT,
-- 		IFNULL(3G_SMS_DROP_CNT,0) AS 3G_SMS_DROP_CNT,
-- 		IFNULL(3G_R99_DROP_CNT,0) AS 3G_R99_DROP_CNT,
-- 		IFNULL(3G_HSPA_DROP_CNT,0) AS 3G_HSPA_DROP_CNT,
-- 		IFNULL(3G_PS_OTHER_DROP_CNT,0) AS 3G_PS_OTHER_DROP_CNT,
		IFNULL(3G_CS_CALL_DURATION,0) AS 3G_CS_CALL_DURATION,
		IFNULL(3G_UL_VOLUME,0) AS3G_UL_VOLUME ,
		IFNULL(3G_DL_VOLUME,0) AS3G_DL_VOLUME ,
		IFNULL(3G_UL_THROUPUT_SUM,0) AS 3G_UL_THROUPUT_SUM,
		IFNULL(3G_UL_THROUPUT_CNT,0) AS 3G_UL_THROUPUT_CNT,
		IFNULL(3G_DL_THROUPUT_SUM,0) AS 3G_DL_THROUPUT_SUM,
		IFNULL(3G_DL_THROUPUT_CNT,0) AS 3G_DL_THROUPUT_CNT,
		IFNULL(4G_CALL_CNT,0) AS 4G_CALL_CNT,
		IFNULL(4G_TRAFFIC_DROP_CNT,0) AS 4G_TRAFFIC_DROP_CNT,
		IFNULL(4G_SIGNAL_DROP_CNT,0) AS 4G_SIGNAL_DROP_CNT,
-- 		IFNULL(4G_VOLTE_DROP_CNT,0) AS 4G_VOLTE_DROP_CNT,
		IFNULL(4G_UL_VOLUME,0) AS 4G_UL_VOLUME,
		IFNULL(4G_DL_VOLUME,0) AS 4G_DL_VOLUME,
		IFNULL(4G_UL_THROUPUT_SUM,0) AS 4G_UL_THROUPUT_SUM,
		IFNULL(4G_UL_THROUPUT_CNT,0) AS 4G_UL_THROUPUT_CNT,
		IFNULL(4G_DL_THROUPUT_SUM,0) AS 4G_DL_THROUPUT_SUM,
		IFNULL(4G_DL_THROUPUT_CNT,0) AS 4G_DL_THROUPUT_CNT';
		
	DECLARE TILE_DS_COLUMN_SUM_STR VARCHAR(3000) DEFAULT 
		'SUM(IFNULL(RSRP_SUM,0)) AS RSRP_SUM,
		SUM(IFNULL(RSRP_CNT,0)) AS RSRP_CNT,
		SUM(IFNULL(RSCP_SUM,0)) AS RSCP_SUM,
		SUM(IFNULL(RSCP_CNT,0)) AS RSCP_CNT,
		SUM(IFNULL(RXLEV_SUM,0)) AS RXLEV_SUM,
		SUM(IFNULL(RXLEV_CNT,0)) AS RXLEV_CNT,
		SUM(IFNULL(RSRQ_SUM,0)) AS RSRQ_SUM,
		SUM(IFNULL(RSRQ_CNT,0)) AS RSRQ_CNT,
		SUM(IFNULL(ECNO_SUM,0)) AS ECNO_SUM,
		SUM(IFNULL(ECNO_CNT,0)) AS ECNO_CNT,
		SUM(IFNULL(RXQUAL_SUM,0)) AS RXQUAL_SUM,
		SUM(IFNULL(RXQUAL_CNT,0)) AS RXQUAL_CNT,
		SUM(IFNULL(2G_CALL_CNT,0)) AS 2G_CALL_CNT,
		SUM(IFNULL(2G_PS_CALL_CNT,0)) AS 2G_PS_CALL_CNT,
		SUM(IFNULL(2G_VOICE_DROP_CNT,0)) AS 2G_VOICE_DROP_CNT,
		SUM(IFNULL(2G_GPRS_DROP_CNT,0)) AS 2G_GPRS_DROP_CNT,
		SUM(IFNULL(2G_SMS_DROP_CNT,0)) AS 2G_SMS_DROP_CNT,
		SUM(IFNULL(2G_CS_CALL_DURATION,0)) AS 2G_CS_CALL_DURATION,
		SUM(IFNULL(3G_CS_CALL_CNT,0)) AS 3G_CS_CALL_CNT,
		SUM(IFNULL(3G_PS_CALL_CNT,0)) AS 3G_PS_CALL_CNT,
		SUM(IFNULL(3G_VOICE_DROP_CNT,0)) AS 3G_VOICE_DROP_CNT,
 		SUM(IFNULL(3G_PS_DROP_CNT,0)) AS 3G_PS_DROP_CNT,
-- 		SUM(IFNULL(3G_VEDIO_DROP_CNT,0)) AS 3G_VEDIO_DROP_CNT,
-- 		SUM(IFNULL(3G_SMS_DROP_CNT,0)) AS 3G_SMS_DROP_CNT,
-- 		SUM(IFNULL(3G_R99_DROP_CNT,0)) AS 3G_R99_DROP_CNT,
-- 		SUM(IFNULL(3G_HSPA_DROP_CNT,0)) AS 3G_HSPA_DROP_CNT,
-- 		SUM(IFNULL(3G_PS_OTHER_DROP_CNT,0)) AS 3G_PS_OTHER_DROP_CNT,
		SUM(IFNULL(3G_CS_CALL_DURATION,0)) AS 3G_CS_CALL_DURATION,
		SUM(IFNULL(3G_UL_VOLUME,0)) AS3G_UL_VOLUME ,
		SUM(IFNULL(3G_DL_VOLUME,0)) AS3G_DL_VOLUME ,
		SUM(IFNULL(3G_UL_THROUPUT_SUM,0)) AS 3G_UL_THROUPUT_SUM,
		SUM(IFNULL(3G_UL_THROUPUT_CNT,0)) AS 3G_UL_THROUPUT_CNT,
		SUM(IFNULL(3G_DL_THROUPUT_SUM,0)) AS 3G_DL_THROUPUT_SUM,
		SUM(IFNULL(3G_DL_THROUPUT_CNT,0)) AS 3G_DL_THROUPUT_CNT,
		SUM(IFNULL(4G_CALL_CNT,0)) AS 4G_CALL_CNT,
		SUM(IFNULL(4G_TRAFFIC_DROP_CNT,0)) AS 4G_TRAFFIC_DROP_CNT,
		SUM(IFNULL(4G_SIGNAL_DROP_CNT,0)) AS 4G_SIGNAL_DROP_CNT,
-- 		SUM(IFNULL(4G_VOLTE_DROP_CNT,0)) AS 4G_VOLTE_DROP_CNT,
		SUM(IFNULL(4G_UL_VOLUME,0)) AS 4G_UL_VOLUME,
		SUM(IFNULL(4G_DL_VOLUME,0)) AS 4G_DL_VOLUME,
		SUM(IFNULL(4G_UL_THROUPUT_SUM,0)) AS 4G_UL_THROUPUT_SUM,
		SUM(IFNULL(4G_UL_THROUPUT_CNT,0)) AS 4G_UL_THROUPUT_CNT,
		SUM(IFNULL(4G_DL_THROUPUT_SUM,0)) AS 4G_DL_THROUPUT_SUM,
		SUM(IFNULL(4G_DL_THROUPUT_CNT,0)) AS 4G_DL_THROUPUT_CNT';		
			
	DECLARE COLUMN_UPD_STR VARCHAR(10000) DEFAULT 
		'RPT_TABLE_NAME.RXQUAL_CNT=RPT_TABLE_NAME.RXQUAL_CNT+VALUES(RXQUAL_CNT),
		RPT_TABLE_NAME.2G_CALL_CNT=RPT_TABLE_NAME.2G_CALL_CNT+VALUES(2G_CALL_CNT),
		RPT_TABLE_NAME.2G_PS_CALL_CNT=RPT_TABLE_NAME.2G_PS_CALL_CNT+VALUES(2G_PS_CALL_CNT),
		RPT_TABLE_NAME.2G_VOICE_DROP_CNT=RPT_TABLE_NAME.2G_VOICE_DROP_CNT+VALUES(2G_VOICE_DROP_CNT),
		RPT_TABLE_NAME.2G_GPRS_DROP_CNT=RPT_TABLE_NAME.2G_VOICE_DROP_CNT+VALUES(2G_GPRS_DROP_CNT),
		RPT_TABLE_NAME.2G_SMS_DROP_CNT=RPT_TABLE_NAME.2G_SMS_DROP_CNT+VALUES(2G_SMS_DROP_CNT),
		RPT_TABLE_NAME.2G_CS_CALL_DURATION=RPT_TABLE_NAME.2G_CS_CALL_DURATION+VALUES(2G_CS_CALL_DURATION),
		RPT_TABLE_NAME.3G_CS_CALL_CNT=RPT_TABLE_NAME.3G_CS_CALL_CNT+VALUES(3G_CS_CALL_CNT),
		RPT_TABLE_NAME.3G_PS_CALL_CNT=RPT_TABLE_NAME.3G_PS_CALL_CNT+VALUES(3G_PS_CALL_CNT),
		RPT_TABLE_NAME.3G_VOICE_DROP_CNT=RPT_TABLE_NAME.3G_VOICE_DROP_CNT+VALUES(3G_VOICE_DROP_CNT),
		RPT_TABLE_NAME.3G_PS_DROP_CNT=RPT_TABLE_NAME.3G_PS_DROP_CNT+VALUES(3G_PS_DROP_CNT),
	--	RPT_TABLE_NAME.3G_VEDIO_DROP_CNT=RPT_TABLE_NAME.3G_VEDIO_DROP_CNT+VALUES(3G_VEDIO_DROP_CNT),
	--	RPT_TABLE_NAME.3G_SMS_DROP_CNT=RPT_TABLE_NAME.3G_SMS_DROP_CNT+VALUES(3G_SMS_DROP_CNT),
	--	RPT_TABLE_NAME.3G_R99_DROP_CNT=RPT_TABLE_NAME.3G_R99_DROP_CNT+VALUES(3G_R99_DROP_CNT),
	--	RPT_TABLE_NAME.3G_HSPA_DROP_CNT=RPT_TABLE_NAME.3G_HSPA_DROP_CNT+VALUES(3G_HSPA_DROP_CNT),
	--	RPT_TABLE_NAME.3G_PS_OTHER_DROP_CNT=RPT_TABLE_NAME.3G_PS_OTHER_DROP_CNT+VALUES(3G_PS_OTHER_DROP_CNT),
		RPT_TABLE_NAME.3G_CS_CALL_DURATION=RPT_TABLE_NAME.3G_CS_CALL_DURATION+VALUES(3G_CS_CALL_DURATION),
		RPT_TABLE_NAME.3G_UL_VOLUME=RPT_TABLE_NAME.3G_UL_VOLUME+VALUES(3G_UL_VOLUME),
		RPT_TABLE_NAME.3G_DL_VOLUME=RPT_TABLE_NAME.3G_DL_VOLUME+VALUES(3G_DL_VOLUME),
		RPT_TABLE_NAME.3G_UL_THROUPUT_SUM=RPT_TABLE_NAME.3G_UL_THROUPUT_SUM+VALUES(3G_UL_THROUPUT_SUM),
		RPT_TABLE_NAME.3G_UL_THROUPUT_CNT=RPT_TABLE_NAME.3G_UL_THROUPUT_CNT+VALUES(3G_UL_THROUPUT_CNT),
		RPT_TABLE_NAME.3G_DL_THROUPUT_SUM=RPT_TABLE_NAME.3G_DL_THROUPUT_SUM+VALUES(3G_DL_THROUPUT_SUM),
		RPT_TABLE_NAME.3G_DL_THROUPUT_CNT=RPT_TABLE_NAME.3G_DL_THROUPUT_CNT+VALUES(3G_DL_THROUPUT_CNT),
		RPT_TABLE_NAME.4G_CALL_CNT=RPT_TABLE_NAME.4G_CALL_CNT+VALUES(4G_CALL_CNT),
		RPT_TABLE_NAME.4G_TRAFFIC_DROP_CNT=RPT_TABLE_NAME.4G_TRAFFIC_DROP_CNT+VALUES(4G_TRAFFIC_DROP_CNT),
		RPT_TABLE_NAME.4G_SIGNAL_DROP_CNT=RPT_TABLE_NAME.4G_SIGNAL_DROP_CNT+VALUES(4G_SIGNAL_DROP_CNT),
	--	RPT_TABLE_NAME.4G_VOLTE_DROP_CNT=RPT_TABLE_NAME.4G_VOLTE_DROP_CNT+VALUES(4G_VOLTE_DROP_CNT),
		RPT_TABLE_NAME.4G_UL_VOLUME=RPT_TABLE_NAME.4G_UL_VOLUME+VALUES(4G_UL_VOLUME),
		RPT_TABLE_NAME.4G_DL_VOLUME=RPT_TABLE_NAME.4G_DL_VOLUME+VALUES(4G_DL_VOLUME),
		RPT_TABLE_NAME.4G_UL_THROUPUT_SUM=RPT_TABLE_NAME.4G_UL_THROUPUT_SUM+VALUES(4G_UL_THROUPUT_SUM),
		RPT_TABLE_NAME.4G_UL_THROUPUT_CNT=RPT_TABLE_NAME.4G_UL_THROUPUT_CNT+VALUES(4G_UL_THROUPUT_CNT),
		RPT_TABLE_NAME.4G_DL_THROUPUT_SUM=RPT_TABLE_NAME.4G_DL_THROUPUT_SUM+VALUES(4G_DL_THROUPUT_SUM),
		RPT_TABLE_NAME.4G_DL_THROUPUT_CNT=RPT_TABLE_NAME.4G_DL_THROUPUT_CNT+VALUES(4G_DL_THROUPUT_CNT)';
	
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
		SET @SqlCmd=CONCAT('CREATE TABLE IF NOT EXISTS `gt_global_statistic`.`nw_error_log`
				(
				  `TABLE_NAME` VARCHAR(50) NOT NULL,
				  `SP_NAME` VARCHAR(50) DEFAULT NULL,
				  `INSERT_CMD` VARCHAR(100) DEFAULT NULL,
				  `INSERT_TIME` DATETIME DEFAULT NULL
				) ENGINE=MYISAM;');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
	
		INSERT INTO `gt_global_statistic`.`nw_error_log`(`TABLE_NAME`,`SP_NAME`,`INSERT_CMD`,`INSERT_TIME`)
		VALUES (@SOURCE_TABLE_NAME,
			'SP_Generate_Global_Statistic_DS_Aggr_ONE',
			CONCAT('Step ',@ERROR_FLAG,' error'),
			NOW());
	
		SET @SqlCmd=CONCAT('REPAIR TABLE ',@REPAIR_TABLE_NAME,';');				
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
	END;	
	
	SET SESSION max_heap_table_size=8*1024*1024*1024;
	SET SESSION tmp_table_size=8*1024*1024*1024;	
	SET SESSION read_buffer_size=2*1024*1024*1024;
	SET SESSION group_concat_max_len=102400; 
	
	SET @global_db='gt_global_statistic';
	
	SET @FLAG_TILE_19_DS_HR=0;
	SET @FLAG_TILE_16_DS_HR=0;
	SET @FLAG_TILE_13_DS_HR=0;
	SET @FLAG_REG_3_DS_HR=0;
	SET @FLAG_REG_2_DS_HR=0;
	SET @FLAG_REG_1_DS_HR=0;
	
	INSERT INTO gt_gw_main.SP_LOG VALUES('gt_global_statistic','SP_Generate_Global_Statistic_DS_Aggr','START', START_TIME);
	SET STEP_START_TIME := SYSDATE();
	
	SET @SqlCmd=CONCAT('SELECT GROUP_CONCAT(DISTINCT CONCAT(`DATA_DATE`,'','',`DATA_HOUR`) SEPARATOR ''|'' ),
				SUM(IF(TECH_MASK=1,1,0)),SUM(IF(TECH_MASK=2,1,0)),SUM(IF(TECH_MASK=4,1,0)) INTO @PU_STR,@GSM_CNT,@UMTS_CNT,@LTE_CNT
				FROM gt_global_statistic.tmp_table_call_cnt_',WORKER_ID,' 
				GROUP BY `DATA_DATE`,`DATA_HOUR`
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET v_DATA_DATE:=gt_covmo_csv_get(@PU_STR,1);		
	SET v_DATA_HOUR:=gt_covmo_csv_get(@PU_STR,2);
	SELECT `DAY_OF_WEEK`(v_DATA_DATE) INTO @DAY_OF_WEEK;
	SET @FIRST_DAY=gt_strtok(@DAY_OF_WEEK, 1, '|');
	SET @END_DAY=gt_strtok(@DAY_OF_WEEK, 2, '|');
	SET @DATE_WK=CONCAT(DATE_FORMAT(@FIRST_DAY,'%Y%m%d'),'_',DATE_FORMAT(@END_DAY,'%Y%m%d'));
	SET @DATE_MN=DATE_FORMAT(v_DATA_DATE,'%Y%m');
	SET @DATE_DY=DATE_FORMAT(v_DATA_DATE,'%Y%m%d');
	SET @EX_DATE=CONCAT(DATE_FORMAT(v_DATA_DATE,'%Y%m%d_'),v_DATA_HOUR,'_',WORKER_ID);
	
	SET @tmp_tile_ds_umts_hr=CONCAT('`gt_global_statistic`.tmp_tile_ds_umts_hr_',@EX_DATE);
	SET @tmp_tile_ds_lte_hr=CONCAT('`gt_global_statistic`.tmp_tile_ds_lte_hr_',@EX_DATE);
	SET @tmp_tile_ds_gsm_hr=CONCAT('`gt_global_statistic`.tmp_tile_ds_gsm_hr_',@EX_DATE);
	SET @tmp_tile_ds_hr=CONCAT('`gt_global_statistic`.tmp_tile_ds_hr_',@EX_DATE);
	SET @table_tile_19_ds_hr=CONCAT('`gt_global_statistic`.table_tile_19_ds_hr_',@DATE_DY);
	SET @table_tile_16_ds_hr=CONCAT('`gt_global_statistic`.table_tile_16_ds_hr_',@DATE_DY);
	SET @table_tile_13_ds_hr=CONCAT('`gt_global_statistic`.table_tile_13_ds_hr_',@DATE_DY);
		
	SET @table_reg_3_ds_hr=CONCAT('`gt_global_statistic`.table_reg_3_ds_hr_',@DATE_DY);
	SET @table_reg_2_ds_hr=CONCAT('`gt_global_statistic`.table_reg_2_ds_hr_',@DATE_DY);
	SET @table_reg_1_ds_hr=CONCAT('`gt_global_statistic`.table_reg_1_ds_hr_',@DATE_DY);
	SET @SqlCmd=CONCAT('SELECT `att_value` INTO @ZOOM_LEVEL FROM gt_covmo.`sys_config` WHERE `group_name`=''system'' AND att_name = ''MapResolution'';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	SET @SqlCmd=CONCAT('DROP TABLE IF EXISTS ',@tmp_tile_ds_hr,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
			
	SET @SqlCmd=CONCAT('CREATE TABLE ',@tmp_tile_ds_hr,' LIKE ',@global_db,'.table_tile_19_ds_hr_',@DATE_DY,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;	
	
	SET @SOURCE_TABLE_NAME=@tmp_tile_ds_hr;
	SET @ERROR_FLAG='tmp_tile_ds_hr';		
	
	SET @SqlCmd=CONCAT('INSERT INTO ',@tmp_tile_ds_hr,' 
			    (
				`TILE_ID`,
				`DATA_DATE`,
				`DATA_HOUR`,
				',TILE_DS_COLUMN_STR,',
				`TILE_ID_16`,
				`TILE_ID_13`,
				`REG_1_ID`,
				`REG_2_ID`,
				`REG_3_ID`)
			SELECT
				`TILE_ID` AS `TILE_ID`,
				`DATA_DATE`,
				`DATA_HOUR`,
				',TILE_DS_COLUMN_SUM_STR,',
				`TILE_ID_16`,
				`TILE_ID_13`,
				`REG_1_ID`,
				`REG_2_ID`,
				`REG_3_ID`
			FROM 
				(
			');
			
	IF @UMTS_CNT>0 THEN 
		SET @SqlCmd=CONCAT(@SqlCmd,'SELECT
					`TILE_ID`,
					`DATA_DATE`,
					`DATA_HOUR`,
					',TILE_DS_COLUMN_STR,',
					`TILE_ID_16`,
					`TILE_ID_13`,
					`REG_1_ID`,
					`REG_2_ID`,
					`REG_3_ID`
				FROM 
				', @tmp_tile_ds_umts_hr ,'
			');
	END IF;
	IF @LTE_CNT>0 AND @UMTS_CNT>0 THEN 
		SET @SqlCmd=CONCAT(@SqlCmd,'
				UNION
				SELECT
					`TILE_ID`,
					`DATA_DATE`,
					`DATA_HOUR`,
					',TILE_DS_COLUMN_STR,',
					`TILE_ID_16`,
					`TILE_ID_13`,
					`REG_1_ID`,
					`REG_2_ID`,
					`REG_3_ID`
				FROM 
				', @tmp_tile_ds_lte_hr ,'
			');
	ELSEIF @LTE_CNT>0 THEN 
		SET @SqlCmd=CONCAT(@SqlCmd,'
				SELECT
					`TILE_ID`,
					`DATA_DATE`,
					`DATA_HOUR`,
					',TILE_DS_COLUMN_STR,',
					`TILE_ID_16`,
					`TILE_ID_13`,
					`REG_1_ID`,
					`REG_2_ID`,
					`REG_3_ID`
				FROM 
				', @tmp_tile_ds_lte_hr ,'
			');
	END IF;		
	IF (@GSM_CNT>0 AND @UMTS_CNT>0) OR (@GSM_CNT>0 AND @LTE_CNT>0) THEN 	
		SET @SqlCmd=CONCAT(@SqlCmd,'
				UNION
				SELECT
					`TILE_ID`,
					`DATA_DATE`,
					`DATA_HOUR`,
					',TILE_DS_COLUMN_STR,',
					`TILE_ID_16`,
					`TILE_ID_13`,
					`REG_1_ID`,
					`REG_2_ID`,
					`REG_3_ID`
				FROM 
				', @tmp_tile_ds_gsm_hr );
	ELSEIF (@GSM_CNT>0) THEN 	
		SET @SqlCmd=CONCAT(@SqlCmd,'
				SELECT
					`TILE_ID`,
					`DATA_DATE`,
					`DATA_HOUR`,
					',TILE_DS_COLUMN_STR,',
					`TILE_ID_16`,
					`TILE_ID_13`,
					`REG_1_ID`,
					`REG_2_ID`,
					`REG_3_ID`
				FROM 
				', @tmp_tile_ds_gsm_hr );
	END IF;		
		
	SET @SqlCmd=CONCAT(@SqlCmd,'
				) AA
			GROUP BY `TILE_ID`,`DATA_DATE`,`DATA_HOUR`
			ORDER BY NULL;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SOURCE_TABLE_NAME=@table_tile_19_ds_hr;
	SET @REPAIR_TABLE_NAME=@table_tile_19_ds_hr;
	SET @ERROR_FLAG='table_tile_19_ds_hr';
	
	SET @SqlCmd=CONCAT('INSERT INTO ',@table_tile_19_ds_hr,' 
			    (
				`TILE_ID`,
				`DATA_DATE`,
				`DATA_HOUR`,
				',TILE_DS_COLUMN_STR,',
			`REG_1_ID`,
			`REG_2_ID`,
			`REG_3_ID`)
		SELECT
			`TILE_ID` AS `TILE_ID`,
			`DATA_DATE`,
			`DATA_HOUR`,
			',TILE_DS_COLUMN_IFNULL_STR,',
			`REG_1_ID`,
			`REG_2_ID`,
			`REG_3_ID`
		FROM ',@tmp_tile_ds_hr,'
-- 			GROUP BY `TILE_ID`,`DATA_DATE`,`DATA_HOUR`
		ORDER BY NULL
		ON DUPLICATE KEY UPDATE
		',REPLACE(COLUMN_UPD_STR,'RPT_TABLE_NAME',@table_tile_19_ds_hr),'
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @FLAG_TILE_19_ds_hr=1;
	INSERT INTO gt_gw_main.SP_LOG VALUES('gt_global_statistic','SP_Generate_Global_Statistic_DS_Aggr',CONCAT('INSERT INTO ',@table_tile_19_ds_hr,' cost:',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' sec.'), NOW());
	SET STEP_START_TIME := SYSDATE();
	
	SET @SOURCE_TABLE_NAME=@table_tile_16_ds_hr;
	SET @REPAIR_TABLE_NAME=@table_tile_16_ds_hr;
	SET @ERROR_FLAG='table_tile_16_ds_hr';
	
	SET @SqlCmd=CONCAT('INSERT INTO ',@table_tile_16_ds_hr,' 
			    (
				`TILE_ID`,
				`DATA_DATE`,
				`DATA_HOUR`,
				',TILE_DS_COLUMN_STR,',
			`REG_1_ID`,
			`REG_2_ID`,
			`REG_3_ID`)
		SELECT
			`TILE_ID_16` AS `TILE_ID`,
			`DATA_DATE`,
			`DATA_HOUR`,
			',TILE_DS_COLUMN_SUM_STR,',
			`REG_1_ID`,
			`REG_2_ID`,
			`REG_3_ID`
		FROM ',@tmp_tile_ds_hr,'
		GROUP BY `TILE_ID_16`,`DATA_DATE`,`DATA_HOUR`
		ORDER BY NULL
		ON DUPLICATE KEY UPDATE 
		',REPLACE(COLUMN_UPD_STR,'RPT_TABLE_NAME',@table_tile_16_ds_hr),'
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @FLAG_TILE_16_ds_hr=1;
	INSERT INTO gt_gw_main.SP_LOG VALUES('gt_global_statistic','SP_Generate_Global_Statistic_DS_Aggr',CONCAT('INSERT INTO ',@table_tile_16_ds_hr,' cost:',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' sec.'), NOW());
	SET STEP_START_TIME := SYSDATE();
	
	SET @SOURCE_TABLE_NAME=@table_tile_13_ds_hr;
	SET @REPAIR_TABLE_NAME=@table_tile_13_ds_hr;
	SET @ERROR_FLAG='table_tile_13_ds_hr';
	
	SET @SqlCmd=CONCAT('INSERT INTO ',@table_tile_13_ds_hr,' 
			    (
				`TILE_ID`,
				`DATA_DATE`,
				`DATA_HOUR`,
				',TILE_DS_COLUMN_STR,',
				`REG_1_ID`,
				`REG_2_ID`,
				`REG_3_ID`)
		SELECT
			`TILE_ID_13` AS `TILE_ID`,
			`DATA_DATE`,
			`DATA_HOUR`,
			',TILE_DS_COLUMN_SUM_STR,',
			`REG_1_ID`,
			`REG_2_ID`,
			`REG_3_ID`
		FROM ',@tmp_tile_ds_hr,'
		GROUP BY `TILE_ID_13`,`DATA_DATE`,`DATA_HOUR`
		ORDER BY NULL
		ON DUPLICATE KEY UPDATE 
		',REPLACE(COLUMN_UPD_STR,'RPT_TABLE_NAME',@table_tile_13_ds_hr),'
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @FLAG_TILE_13_ds_hr=1;	
	INSERT INTO gt_gw_main.SP_LOG VALUES('gt_global_statistic','SP_Generate_Global_Statistic_DS_Aggr',CONCAT('INSERT INTO ',@table_tile_13_ds_hr,' cost:',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' sec.'), NOW());
	SET STEP_START_TIME := SYSDATE();
	
	SET @SOURCE_TABLE_NAME=@table_reg_3_ds_hr;
	SET @REPAIR_TABLE_NAME=@table_reg_3_ds_hr;
	SET @ERROR_FLAG='table_reg_3_ds_hr';
	
	SET @SqlCmd=CONCAT('INSERT INTO ',@table_reg_3_ds_hr,' 
			    (
				`REG_ID`,
				`DATA_DATE`,
				`DATA_HOUR`,
				',TILE_DS_COLUMN_STR,')
		SELECT
			`REG_3_ID` AS `REG_ID`,
			`DATA_DATE`,
			`DATA_HOUR`,
			',TILE_DS_COLUMN_SUM_STR,'
		FROM ',@tmp_tile_ds_hr,'
		GROUP BY `REG_3_ID`,`DATA_DATE`,`DATA_HOUR`
		ORDER BY NULL
		ON DUPLICATE KEY UPDATE 
		',REPLACE(COLUMN_UPD_STR,'RPT_TABLE_NAME',@table_reg_3_ds_hr),'
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @FLAG_REG_3_ds_hr=1;
	INSERT INTO gt_gw_main.SP_LOG VALUES('gt_global_statistic','SP_Generate_Global_Statistic_DS_Aggr',CONCAT('INSERT INTO ',@table_reg_3_ds_hr,' cost:',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' sec.'), NOW());
	SET STEP_START_TIME := SYSDATE();
	
	SET @SOURCE_TABLE_NAME=@table_reg_2_ds_hr;
	SET @REPAIR_TABLE_NAME=@table_reg_2_ds_hr;
	SET @ERROR_FLAG='table_reg_2_ds_hr';
	
	SET @SqlCmd=CONCAT('INSERT INTO ',@table_reg_2_ds_hr,' 
			    (
				`REG_ID`,
				`DATA_DATE`,
				`DATA_HOUR`,
				',TILE_DS_COLUMN_STR,')
		SELECT
			`REG_2_ID` AS `REG_ID`,
			`DATA_DATE`,
			`DATA_HOUR`,
			',TILE_DS_COLUMN_SUM_STR,'
		FROM ',@tmp_tile_ds_hr,'
		GROUP BY `REG_2_ID`,`DATA_DATE`,`DATA_HOUR`
		ORDER BY NULL
		ON DUPLICATE KEY UPDATE 
		',REPLACE(COLUMN_UPD_STR,'RPT_TABLE_NAME',@table_reg_2_ds_hr),'
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @FLAG_reg_2_ds_hr=1;
	INSERT INTO gt_gw_main.SP_LOG VALUES('gt_global_statistic','SP_Generate_Global_Statistic_DS_Aggr',CONCAT('INSERT INTO ',@table_reg_2_ds_hr,' cost:',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' sec.'), NOW());
	SET STEP_START_TIME := SYSDATE();
	
	SET @SOURCE_TABLE_NAME=@table_reg_1_ds_hr;
	SET @REPAIR_TABLE_NAME=@table_reg_1_ds_hr;
	SET @ERROR_FLAG='table_reg_1_ds_hr';
	
	SET @SqlCmd=CONCAT('INSERT INTO ',@table_reg_1_ds_hr,' 
			    (
				`REG_ID`,
				`DATA_DATE`,
				`DATA_HOUR`,
				',TILE_DS_COLUMN_STR,')
		SELECT
			`REG_1_ID` AS `REG_ID`,
			`DATA_DATE`,
			`DATA_HOUR`,
			',TILE_DS_COLUMN_SUM_STR,'
		FROM ',@tmp_tile_ds_hr,'
		GROUP BY `REG_1_ID`,`DATA_DATE`,`DATA_HOUR`
		ORDER BY NULL
		ON DUPLICATE KEY UPDATE 
		',REPLACE(COLUMN_UPD_STR,'RPT_TABLE_NAME',@table_reg_1_ds_hr),'
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @FLAG_reg_1_ds_hr=1;
	INSERT INTO gt_gw_main.SP_LOG VALUES('gt_global_statistic','SP_Generate_Global_Statistic_DS_Aggr',CONCAT('INSERT INTO ',@table_reg_1_ds_hr,' cost:',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' sec.'), NOW());
	SET STEP_START_TIME := SYSDATE();
	SET @SqlCmd=CONCAT('DROP TABLE IF EXISTS ',@tmp_tile_ds_hr,';');					
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('DROP TABLE IF EXISTS ',@tmp_tile_ds_umts_hr,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('DROP TABLE IF EXISTS ',@tmp_tile_ds_lte_hr,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('DROP TABLE IF EXISTS ',@tmp_tile_ds_gsm_hr,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	INSERT INTO gt_gw_main.SP_LOG VALUES('gt_global_statistic','SP_Generate_Global_Statistic_DS_Aggr',CONCAT(v_DATA_DATE,',',v_DATA_HOUR,',',WORKER_ID,' Done: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());
END$$
DELIMITER ;
