DELIMITER $$
USE `gt_global_statistic`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Generate_Global_Statistic_TileResolution_Insert_MV`(IN TECH_MASK TINYINT(2),IN TBL_NAME VARCHAR(100),IN TMP_TBL_NAME VARCHAR(100),IN TIMETYPE CHAR(2),IN PENDING_FLAG TINYINT(2),IN TileResolution VARCHAR(10),IN GT_AGGREGATE_DB VARCHAR(100),IN GROUP_DB_NAME VARCHAR(100),v_DATA_HOUR TINYINT(2))
BEGIN
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE tile_count SMALLINT(6) DEFAULT 0;
	DECLARE v_j SMALLINT(6);
	DECLARE REP_NAME VARCHAR(100) DEFAULT '_19_';
	DECLARE TARGET_TBL_NAME VARCHAR(100);
	DECLARE ZOOM_TBL_NAME VARCHAR(100);	
	
	DECLARE SHARE_IP VARCHAR(100) DEFAULT NULL;
	DECLARE SHARE_PORT VARCHAR(10) DEFAULT NULL;
	DECLARE SHARE_ACCOUNT VARCHAR(100) DEFAULT NULL;
	DECLARE SHARE_PW VARCHAR(100) DEFAULT NULL;	
	DECLARE SHARE_DB VARCHAR(100) DEFAULT NULL;
	
	DECLARE TILE_UMTS_COLUMN_STR VARCHAR(1500) DEFAULT 
		'`INIT_CALL_CNT`,
		  `END_CALL_CNT`,
		  `VOICE_CNT`,
		  `VIDEO_CNT`,
		  `PS_R99_CNT`,
		  `PS_HSPA_CNT`,
		  `M_RAB_CNT`, 
		  `SIGNAL_CNT`,
		  `SMS_CNT`,
		  `PS_OTHER_CNT`,
		  `CALL_DUR_SUM`,
		  `CS_DUR_SUM`,
		  `DROP_CNT`,
		  `BLOCK_CNT`,
		  `DROP_VOICE_CNT`,
		  `DROP_VIDEO_CNT`,
		  `DROP_PS_R99_CNT`,
		  `DROP_PS_HSPA_CNT`,
		  `DROP_M_RAB_CNT`,
		  `DROP_SIGNAL_CNT`,
		  `DROP_SMS_CNT`,
		  `DROP_PS_OTHER_CNT`,
		  `SHO_ATTEMPT_CNT`,
		  `SHO_FAILURE_CNT`,
		  `IFHO_ATTEMPT_CNT`,
		  `IFHO_FAILURE_CNT`,
		  `IRAT_ATTEMPT_CNT`,
		  `IRAT_FAILURE_CNT`,
		  `PS_UL_VOLUME_SUM`,
		  `PS_DL_VOLUME_SUM`,
		  `PS_UL_SPEED_MAX`,
		  `PS_DL_SPEED_MAX`,
		  `RSCP_SUM`,
		  `RSCP_CNT`,
		  `ECNO_SUM`,
		  `ECNO_CNT`,
		  `ACTIVE_SET_SUM`,
		  `ACTIVE_SET_CNT`,
		  `POLLUTED_PILOT_CNT`,
		  `PILOT_DOM_SUM`,
		  `PILOT_CNT`,
		  `T19_CNT`,
		  `UL_THROUPUT_SUM`,
		  `UL_THROUPUT_CNT`,
		  `DL_THROUPUT_SUM`,
		  `DL_THROUPUT_CNT`,
		  `NON_BLOCK_VOICE_CNT`,
		  `NON_BLOCK_VIDEO_CNT`,
		  `NON_BLOCK_PS_R99_CNT`,
		  `NON_BLOCK_PS_HSPA_CNT`,
		  `NON_BLOCK_M_RAB_CNT`,
		  `NON_BLOCK_SIGNAL_CNT`,
		  `NON_BLOCK_SMS_CNT`,
		  `NON_BLOCK_PS_OTHER_CNT`,
		  `PS_CNT`,
		  `DROP_PS_CNT`,
		  `FP_RSCP_1`,
		  `FP_ECN0_1`,
		  `BEST_CNT`,
		  `UL_THROUPUT_MAX`,
		  `DL_THROUPUT_MAX`';
		  
	DECLARE TILE_UMTS_COLUMN_IFNULL_STR VARCHAR(5000) DEFAULT 
		'IFNULL(INIT_CALL_CNT,0) AS INIT_CALL_CNT,
		IFNULL(END_CALL_CNT,0) AS END_CALL_CNT,
		IFNULL(VOICE_CNT,0) AS VOICE_CNT,
		IFNULL(VIDEO_CNT,0) AS VIDEO_CNT,
		IFNULL(PS_R99_CNT,0) AS PS_R99_CNT,
		IFNULL(PS_HSPA_CNT,0) AS PS_HSPA_CNT,
		IFNULL(M_RAB_CNT,0) AS M_RAB_CNT,
		IFNULL(SIGNAL_CNT,0) AS SIGNAL_CNT,
		IFNULL(SMS_CNT,0) AS SMS_CNT,
		IFNULL(PS_OTHER_CNT,0) AS PS_OTHER_CNT,
		IFNULL(CALL_DUR_SUM,0) AS CALL_DUR_SUM,
		IFNULL(CS_DUR_SUM,0) AS CS_DUR_SUM,
		IFNULL(DROP_CNT,0) AS DROP_CNT,
		IFNULL(BLOCK_CNT,0) AS BLOCK_CNT,
		IFNULL(DROP_VOICE_CNT,0) AS DROP_VOICE_CNT,
		IFNULL(DROP_VIDEO_CNT,0) AS DROP_VIDEO_CNT,
		IFNULL(DROP_PS_R99_CNT,0) AS DROP_PS_R99_CNT,
		IFNULL(DROP_PS_HSPA_CNT,0) AS DROP_PS_HSPA_CNT,
		IFNULL(DROP_M_RAB_CNT,0) AS DROP_M_RAB_CNT,
		IFNULL(DROP_SIGNAL_CNT,0) AS DROP_SIGNAL_CNT,
		IFNULL(DROP_SMS_CNT,0) AS DROP_SMS_CNT,
		IFNULL(DROP_PS_OTHER_CNT,0) AS DROP_PS_OTHER_CNT,
		IFNULL(SHO_ATTEMPT_CNT,0) AS SHO_ATTEMPT_CNT,
		IFNULL(SHO_FAILURE_CNT,0) AS SHO_FAILURE_CNT,
		IFNULL(IFHO_ATTEMPT_CNT,0) AS IFHO_ATTEMPT_CNT,
		IFNULL(IFHO_FAILURE_CNT,0) AS IFHO_FAILURE_CNT,
		IFNULL(IRAT_ATTEMPT_CNT,0) AS IRAT_ATTEMPT_CNT,
		IFNULL(IRAT_FAILURE_CNT,0) AS IRAT_FAILURE_CNT,
		IFNULL(PS_UL_VOLUME_SUM,0) AS PS_UL_VOLUME_SUM,
		IFNULL(PS_DL_VOLUME_SUM,0) AS PS_DL_VOLUME_SUM,
		IFNULL(PS_UL_SPEED_MAX,0) AS PS_UL_SPEED_MAX,
		IFNULL(PS_DL_SPEED_MAX,0) AS PS_DL_SPEED_MAX,
		IFNULL(RSCP_SUM,0) AS RSCP_SUM,
		IFNULL(RSCP_CNT,0) AS RSCP_CNT,
		IFNULL(ECNO_SUM,0) AS ECNO_SUM,
		IFNULL(ECNO_CNT,0) AS ECNO_CNT,
		IFNULL(ACTIVE_SET_SUM,0) AS ACTIVE_SET_SUM,
		IFNULL(ACTIVE_SET_CNT,0) AS ACTIVE_SET_CNT,
		IFNULL(POLLUTED_PILOT_CNT,0) AS POLLUTED_PILOT_CNT,
		IFNULL(PILOT_DOM_SUM,0) AS PILOT_DOM_SUM,
		IFNULL(PILOT_CNT,0) AS PILOT_CNT,
		IFNULL(T19_CNT,0) AS T19_CNT,
		IFNULL(UL_THROUPUT_SUM,0) AS UL_THROUPUT_SUM,
		IFNULL(UL_THROUPUT_CNT,0) AS UL_THROUPUT_CNT,
		IFNULL(DL_THROUPUT_SUM,0) AS DL_THROUPUT_SUM,
		IFNULL(DL_THROUPUT_CNT,0) AS DL_THROUPUT_CNT,
		IFNULL(NON_BLOCK_VOICE_CNT,0) AS NON_BLOCK_VOICE_CNT,
		IFNULL(NON_BLOCK_VIDEO_CNT,0) AS NON_BLOCK_VIDEO_CNT,
		IFNULL(NON_BLOCK_PS_R99_CNT,0) AS NON_BLOCK_PS_R99_CNT,
		IFNULL(NON_BLOCK_PS_HSPA_CNT,0) AS NON_BLOCK_PS_HSPA_CNT,
		IFNULL(NON_BLOCK_M_RAB_CNT,0) AS NON_BLOCK_M_RAB_CNT,
		IFNULL(NON_BLOCK_SIGNAL_CNT,0) AS NON_BLOCK_SIGNAL_CNT,
		IFNULL(NON_BLOCK_SMS_CNT,0) AS NON_BLOCK_SMS_CNT,
		IFNULL(NON_BLOCK_PS_OTHER_CNT,0) AS NON_BLOCK_PS_OTHER_CNT,
		IFNULL(PS_CNT,0) AS PS_CNT,
		IFNULL(DROP_PS_CNT,0) AS DROP_PS_CNT,
  		IFNULL(FP_RSCP_1,0) AS FP_RSCP_1,
  		IFNULL(FP_ECN0_1,0) AS FP_ECN0_1,
  		IFNULL(BEST_CNT,0) AS BEST_CNT,
  		IFNULL(UL_THROUPUT_MAX,0) AS UL_THROUPUT_MAX,
  		IFNULL(DL_THROUPUT_MAX,0) AS DL_THROUPUT_MAX';
		
	DECLARE TILE_UMTS_COLUMN_SUM_STR VARCHAR(5000) DEFAULT 
		'SUM(IFNULL(INIT_CALL_CNT,0)) AS INIT_CALL_CNT,
		SUM(IFNULL(END_CALL_CNT,0)) AS END_CALL_CNT,
		SUM(IFNULL(VOICE_CNT,0)) AS VOICE_CNT,
		SUM(IFNULL(VIDEO_CNT,0)) AS VIDEO_CNT,
		SUM(IFNULL(PS_R99_CNT,0)) AS PS_R99_CNT,
		SUM(IFNULL(PS_HSPA_CNT,0)) AS PS_HSPA_CNT,
		SUM(IFNULL(M_RAB_CNT,0)) AS M_RAB_CNT,
		SUM(IFNULL(SIGNAL_CNT,0)) AS SIGNAL_CNT,
		SUM(IFNULL(SMS_CNT,0)) AS SMS_CNT,
		SUM(IFNULL(PS_OTHER_CNT,0)) AS PS_OTHER_CNT,
		SUM(IFNULL(CALL_DUR_SUM,0)) AS CALL_DUR_SUM,
		SUM(IFNULL(CS_DUR_SUM,0)) AS CS_DUR_SUM,
		SUM(IFNULL(DROP_CNT,0)) AS DROP_CNT,
		SUM(IFNULL(BLOCK_CNT,0)) AS BLOCK_CNT,
		SUM(IFNULL(DROP_VOICE_CNT,0)) AS DROP_VOICE_CNT,
		SUM(IFNULL(DROP_VIDEO_CNT,0)) AS DROP_VIDEO_CNT,
		SUM(IFNULL(DROP_PS_R99_CNT,0)) AS DROP_PS_R99_CNT,
		SUM(IFNULL(DROP_PS_HSPA_CNT,0)) AS DROP_PS_HSPA_CNT,
		SUM(IFNULL(DROP_M_RAB_CNT,0)) AS DROP_M_RAB_CNT,
		SUM(IFNULL(DROP_SIGNAL_CNT,0)) AS DROP_SIGNAL_CNT,
		SUM(IFNULL(DROP_SMS_CNT,0)) AS DROP_SMS_CNT,
		SUM(IFNULL(DROP_PS_OTHER_CNT,0)) AS DROP_PS_OTHER_CNT,
		SUM(IFNULL(SHO_ATTEMPT_CNT,0)) AS SHO_ATTEMPT_CNT,
		SUM(IFNULL(SHO_FAILURE_CNT,0)) AS SHO_FAILURE_CNT,
		SUM(IFNULL(IFHO_ATTEMPT_CNT,0)) AS IFHO_ATTEMPT_CNT,
		SUM(IFNULL(IFHO_FAILURE_CNT,0)) AS IFHO_FAILURE_CNT,
		SUM(IFNULL(IRAT_ATTEMPT_CNT,0)) AS IRAT_ATTEMPT_CNT,
		SUM(IFNULL(IRAT_FAILURE_CNT,0)) AS IRAT_FAILURE_CNT,
		SUM(IFNULL(PS_UL_VOLUME_SUM,0)) AS PS_UL_VOLUME_SUM,
		SUM(IFNULL(PS_DL_VOLUME_SUM,0)) AS PS_DL_VOLUME_SUM,
		MAX(IFNULL(PS_UL_SPEED_MAX,0)) AS PS_UL_SPEED_MAX,
		MAX(IFNULL(PS_DL_SPEED_MAX,0)) AS PS_DL_SPEED_MAX,
		SUM(IFNULL(RSCP_SUM,0)) AS RSCP_SUM,
		SUM(IFNULL(RSCP_CNT,0)) AS RSCP_CNT,
		SUM(IFNULL(ECNO_SUM,0)) AS ECNO_SUM,
		SUM(IFNULL(ECNO_CNT,0)) AS ECNO_CNT,
		SUM(IFNULL(ACTIVE_SET_SUM,0)) AS ACTIVE_SET_SUM,
		SUM(IFNULL(ACTIVE_SET_CNT,0)) AS ACTIVE_SET_CNT,
		SUM(IFNULL(POLLUTED_PILOT_CNT,0)) AS POLLUTED_PILOT_CNT,
		SUM(IFNULL(PILOT_DOM_SUM,0)) AS PILOT_DOM_SUM,
		SUM(IFNULL(PILOT_CNT,0)) AS PILOT_CNT,
		SUM(IFNULL(T19_CNT,0)) AS T19_CNT,
		SUM(IFNULL(UL_THROUPUT_SUM,0)) AS UL_THROUPUT_SUM,
		SUM(IFNULL(UL_THROUPUT_CNT,0)) AS UL_THROUPUT_CNT,
		SUM(IFNULL(DL_THROUPUT_SUM,0)) AS DL_THROUPUT_SUM,
		SUM(IFNULL(DL_THROUPUT_CNT,0)) AS DL_THROUPUT_CNT,
		SUM(IFNULL(NON_BLOCK_VOICE_CNT,0)) AS NON_BLOCK_VOICE_CNT,
		SUM(IFNULL(NON_BLOCK_VIDEO_CNT,0)) AS NON_BLOCK_VIDEO_CNT,
		SUM(IFNULL(NON_BLOCK_PS_R99_CNT,0)) AS NON_BLOCK_PS_R99_CNT,
		SUM(IFNULL(NON_BLOCK_PS_HSPA_CNT,0)) AS NON_BLOCK_PS_HSPA_CNT,
		SUM(IFNULL(NON_BLOCK_M_RAB_CNT,0)) AS NON_BLOCK_M_RAB_CNT,
		SUM(IFNULL(NON_BLOCK_SIGNAL_CNT,0)) AS NON_BLOCK_SIGNAL_CNT,
		SUM(IFNULL(NON_BLOCK_SMS_CNT,0)) AS NON_BLOCK_SMS_CNT,
		SUM(IFNULL(NON_BLOCK_PS_OTHER_CNT,0)) AS NON_BLOCK_PS_OTHER_CNT,
		SUM(IFNULL(PS_CNT,0)) AS PS_CNT,
		SUM(IFNULL(DROP_PS_CNT,0)) AS DROP_PS_CNT,
		SUM(IFNULL(FP_RSCP_1,0)) AS FP_RSCP_1,
		SUM(IFNULL(FP_ECN0_1,0)) AS FP_ECN0_1,
		SUM(IFNULL(BEST_CNT,0)) AS BEST_CNT,
		SUM(IFNULL(UL_THROUPUT_MAX,0)) AS UL_THROUPUT_MAX,
		SUM(IFNULL(DL_THROUPUT_MAX,0)) AS DL_THROUPUT_MAX';
	
	DECLARE TILE_UMTS_COLUMN_UPD_STR VARCHAR(10000) DEFAULT
		'RPT_TABLE_NAME.INIT_CALL_CNT=RPT_TABLE_NAME.INIT_CALL_CNT+VALUES(INIT_CALL_CNT),
		RPT_TABLE_NAME.END_CALL_CNT=RPT_TABLE_NAME.END_CALL_CNT+VALUES(END_CALL_CNT),
		RPT_TABLE_NAME.VOICE_CNT=RPT_TABLE_NAME.VOICE_CNT+VALUES(VOICE_CNT),
		RPT_TABLE_NAME.VIDEO_CNT=RPT_TABLE_NAME.VIDEO_CNT+VALUES(VIDEO_CNT),
		RPT_TABLE_NAME.PS_R99_CNT=RPT_TABLE_NAME.PS_R99_CNT+VALUES(PS_R99_CNT),
		RPT_TABLE_NAME.PS_HSPA_CNT=RPT_TABLE_NAME.PS_HSPA_CNT+VALUES(PS_HSPA_CNT),
		RPT_TABLE_NAME.M_RAB_CNT=RPT_TABLE_NAME.M_RAB_CNT+VALUES(M_RAB_CNT),
		RPT_TABLE_NAME.SIGNAL_CNT=RPT_TABLE_NAME.SIGNAL_CNT+VALUES(SIGNAL_CNT),
		RPT_TABLE_NAME.SMS_CNT=RPT_TABLE_NAME.SMS_CNT+VALUES(SMS_CNT),
		RPT_TABLE_NAME.PS_OTHER_CNT=RPT_TABLE_NAME.PS_OTHER_CNT+VALUES(PS_OTHER_CNT),
		RPT_TABLE_NAME.CALL_DUR_SUM=RPT_TABLE_NAME.CALL_DUR_SUM+VALUES(CALL_DUR_SUM),
		RPT_TABLE_NAME.CS_DUR_SUM=RPT_TABLE_NAME.CS_DUR_SUM+VALUES(CS_DUR_SUM),
		RPT_TABLE_NAME.DROP_CNT=RPT_TABLE_NAME.DROP_CNT+VALUES(DROP_CNT),
		RPT_TABLE_NAME.BLOCK_CNT=RPT_TABLE_NAME.BLOCK_CNT+VALUES(BLOCK_CNT),
		RPT_TABLE_NAME.DROP_VOICE_CNT=RPT_TABLE_NAME.DROP_VOICE_CNT+VALUES(DROP_VOICE_CNT),
		RPT_TABLE_NAME.DROP_VIDEO_CNT=RPT_TABLE_NAME.DROP_VIDEO_CNT+VALUES(DROP_VIDEO_CNT),
		RPT_TABLE_NAME.DROP_PS_R99_CNT=RPT_TABLE_NAME.DROP_PS_R99_CNT+VALUES(DROP_PS_R99_CNT),
		RPT_TABLE_NAME.DROP_PS_HSPA_CNT=RPT_TABLE_NAME.DROP_PS_HSPA_CNT+VALUES(DROP_PS_HSPA_CNT),
		RPT_TABLE_NAME.DROP_M_RAB_CNT=RPT_TABLE_NAME.DROP_M_RAB_CNT+VALUES(DROP_M_RAB_CNT),
		RPT_TABLE_NAME.DROP_SIGNAL_CNT=RPT_TABLE_NAME.DROP_SIGNAL_CNT+VALUES(DROP_SIGNAL_CNT),
		RPT_TABLE_NAME.DROP_SMS_CNT=RPT_TABLE_NAME.DROP_SMS_CNT+VALUES(DROP_SMS_CNT),
		RPT_TABLE_NAME.DROP_PS_OTHER_CNT=RPT_TABLE_NAME.DROP_PS_OTHER_CNT+VALUES(DROP_PS_OTHER_CNT),
		RPT_TABLE_NAME.SHO_ATTEMPT_CNT=RPT_TABLE_NAME.SHO_ATTEMPT_CNT+VALUES(SHO_ATTEMPT_CNT),
		RPT_TABLE_NAME.SHO_FAILURE_CNT=RPT_TABLE_NAME.SHO_FAILURE_CNT+VALUES(SHO_FAILURE_CNT),
		RPT_TABLE_NAME.IFHO_ATTEMPT_CNT=RPT_TABLE_NAME.IFHO_ATTEMPT_CNT+VALUES(IFHO_ATTEMPT_CNT),
		RPT_TABLE_NAME.IFHO_FAILURE_CNT=RPT_TABLE_NAME.IFHO_FAILURE_CNT+VALUES(IFHO_FAILURE_CNT),
		RPT_TABLE_NAME.IRAT_ATTEMPT_CNT=RPT_TABLE_NAME.IRAT_ATTEMPT_CNT+VALUES(IRAT_ATTEMPT_CNT),
		RPT_TABLE_NAME.IRAT_FAILURE_CNT=RPT_TABLE_NAME.IRAT_FAILURE_CNT+VALUES(IRAT_FAILURE_CNT),
		RPT_TABLE_NAME.PS_UL_VOLUME_SUM=RPT_TABLE_NAME.PS_UL_VOLUME_SUM+VALUES(PS_UL_VOLUME_SUM),
		RPT_TABLE_NAME.PS_DL_VOLUME_SUM=RPT_TABLE_NAME.PS_DL_VOLUME_SUM+VALUES(PS_DL_VOLUME_SUM),
		RPT_TABLE_NAME.PS_UL_SPEED_MAX=CASE WHEN RPT_TABLE_NAME.PS_UL_SPEED_MAX > VALUES(PS_UL_SPEED_MAX) THEN RPT_TABLE_NAME.PS_UL_SPEED_MAX ELSE VALUES(PS_UL_SPEED_MAX) END,    
		RPT_TABLE_NAME.PS_DL_SPEED_MAX=CASE WHEN RPT_TABLE_NAME.PS_DL_SPEED_MAX > VALUES(PS_DL_SPEED_MAX) THEN RPT_TABLE_NAME.PS_DL_SPEED_MAX ELSE VALUES(PS_DL_SPEED_MAX) END,
		RPT_TABLE_NAME.RSCP_SUM=RPT_TABLE_NAME.RSCP_SUM+VALUES(RSCP_SUM),
		RPT_TABLE_NAME.RSCP_CNT=RPT_TABLE_NAME.RSCP_CNT+VALUES(RSCP_CNT),
		RPT_TABLE_NAME.ECNO_SUM=RPT_TABLE_NAME.ECNO_SUM+VALUES(ECNO_SUM),
		RPT_TABLE_NAME.ECNO_CNT=RPT_TABLE_NAME.ECNO_CNT+VALUES(ECNO_CNT),
		RPT_TABLE_NAME.ACTIVE_SET_SUM=RPT_TABLE_NAME.ACTIVE_SET_SUM+VALUES(ACTIVE_SET_SUM),
		RPT_TABLE_NAME.ACTIVE_SET_CNT=RPT_TABLE_NAME.ACTIVE_SET_CNT+VALUES(ACTIVE_SET_CNT),
		RPT_TABLE_NAME.POLLUTED_PILOT_CNT=RPT_TABLE_NAME.POLLUTED_PILOT_CNT+VALUES(POLLUTED_PILOT_CNT),
		RPT_TABLE_NAME.PILOT_DOM_SUM=RPT_TABLE_NAME.PILOT_DOM_SUM+VALUES(PILOT_DOM_SUM),
		RPT_TABLE_NAME.PILOT_CNT=RPT_TABLE_NAME.PILOT_CNT+VALUES(PILOT_CNT),
		RPT_TABLE_NAME.T19_CNT=RPT_TABLE_NAME.T19_CNT+VALUES(T19_CNT),
		RPT_TABLE_NAME.UL_THROUPUT_SUM=RPT_TABLE_NAME.UL_THROUPUT_SUM+VALUES(UL_THROUPUT_SUM),
		RPT_TABLE_NAME.UL_THROUPUT_CNT=RPT_TABLE_NAME.UL_THROUPUT_CNT+VALUES(UL_THROUPUT_CNT),
		RPT_TABLE_NAME.DL_THROUPUT_SUM=RPT_TABLE_NAME.DL_THROUPUT_SUM+VALUES(DL_THROUPUT_SUM),
		RPT_TABLE_NAME.DL_THROUPUT_CNT=RPT_TABLE_NAME.DL_THROUPUT_CNT+VALUES(DL_THROUPUT_CNT),
		RPT_TABLE_NAME.NON_BLOCK_VOICE_CNT=RPT_TABLE_NAME.NON_BLOCK_VOICE_CNT+VALUES(NON_BLOCK_VOICE_CNT),
		RPT_TABLE_NAME.NON_BLOCK_VIDEO_CNT=RPT_TABLE_NAME.NON_BLOCK_VIDEO_CNT+VALUES(NON_BLOCK_VIDEO_CNT),
		RPT_TABLE_NAME.NON_BLOCK_PS_R99_CNT=RPT_TABLE_NAME.NON_BLOCK_PS_R99_CNT+VALUES(NON_BLOCK_PS_R99_CNT),
		RPT_TABLE_NAME.NON_BLOCK_PS_HSPA_CNT=RPT_TABLE_NAME.NON_BLOCK_PS_HSPA_CNT+VALUES(NON_BLOCK_PS_HSPA_CNT),
		RPT_TABLE_NAME.NON_BLOCK_M_RAB_CNT=RPT_TABLE_NAME.NON_BLOCK_M_RAB_CNT+VALUES(NON_BLOCK_M_RAB_CNT),
		RPT_TABLE_NAME.NON_BLOCK_SIGNAL_CNT=RPT_TABLE_NAME.NON_BLOCK_SIGNAL_CNT+VALUES(NON_BLOCK_SIGNAL_CNT),
		RPT_TABLE_NAME.NON_BLOCK_SMS_CNT=RPT_TABLE_NAME.NON_BLOCK_SMS_CNT+VALUES(NON_BLOCK_SMS_CNT),
		RPT_TABLE_NAME.NON_BLOCK_PS_OTHER_CNT=RPT_TABLE_NAME.NON_BLOCK_PS_OTHER_CNT+VALUES(NON_BLOCK_PS_OTHER_CNT),
		RPT_TABLE_NAME.PS_CNT=RPT_TABLE_NAME.PS_CNT+VALUES(PS_CNT),
		RPT_TABLE_NAME.DROP_PS_CNT=RPT_TABLE_NAME.DROP_PS_CNT+VALUES(DROP_PS_CNT),
		RPT_TABLE_NAME.FP_RSCP_1=RPT_TABLE_NAME.FP_RSCP_1+VALUES(FP_RSCP_1),
		RPT_TABLE_NAME.FP_ECN0_1=RPT_TABLE_NAME.FP_ECN0_1+VALUES(FP_ECN0_1),
		RPT_TABLE_NAME.BEST_CNT=RPT_TABLE_NAME.BEST_CNT+VALUES(BEST_CNT),
		RPT_TABLE_NAME.UL_THROUPUT_MAX=CASE WHEN RPT_TABLE_NAME.UL_THROUPUT_MAX > VALUES(UL_THROUPUT_MAX) THEN RPT_TABLE_NAME.UL_THROUPUT_MAX ELSE VALUES(UL_THROUPUT_MAX) END,    
		RPT_TABLE_NAME.DL_THROUPUT_MAX=CASE WHEN RPT_TABLE_NAME.DL_THROUPUT_MAX > VALUES(DL_THROUPUT_MAX) THEN RPT_TABLE_NAME.DL_THROUPUT_MAX ELSE VALUES(DL_THROUPUT_MAX) END';
	
	DECLARE TILE_LTE_COLUMN_STR VARCHAR(3000) DEFAULT 
		'`INIT_CALL_CNT`,
		`END_CALL_CNT`,
		`SIGNAL_CNT`,
		`DATA_CNT`,
		`UNSPECIFIED_CNT`,
		`CALL_DUR_SUM`,
		`BLOCK_CNT`,
		`DROP_CNT`,
		`CSFB_CNT`,
		`INTER_FREQ_ATTEMPT_CNT`,
		`INTER_FREQ_FAILURE_CNT`,
		`INTRA_FREQ_ATTEMPT_CNT`,
		`INTRA_FREQ_FAILURE_CNT`,
		`4G_3G_ATTEMPT_CNT`,
		`4G_3G_FAILURE_CNT`,
		`4G_2G_ATTEMPT_CNT`,
		`4G_2G_FAILURE_CNT`,
		`PS_UL_VOLUME_SUM`,
		`PS_DL_VOLUME_SUM`,
		`PS_UL_SPEED_MAX`,
		`PS_DL_SPEED_MAX`,
		`RSRP_SUM`,
		`RSRP_CNT`,
		`RSRQ_SUM`,
		`RSRQ_CNT`,
		`PILOT_DOMINANCE_SUM`,
		`PILOT_DOMINANCE_CNT`,
		`DROP_SIGNAL_CNT`,
		`DROP_DATA_CNT`,
		`END_NON_BLOCK_CALL_CNT`,
		`UL_THROUPUT_SUM`,
		`UL_THROUPUT_CNT`,
		`DL_THROUPUT_SUM`,
		`DL_THROUPUT_CNT`,
		`END_NON_BLOCK_SIGNAL_CNT`,
		`END_NON_BLOCK_DATA_CNT`,
		`MR_4G_RSRP_SERVING_SUM`,
		`MR_4G_RSRP_SERVING_CNT`,
		`MR_4G_RSRQ_SERVING_SUM`,
		`MR_4G_RSRQ_SERVING_CNT`';
		  
	DECLARE TILE_LTE_COLUMN_IFNULL_STR VARCHAR(3000) DEFAULT 
		'IFNULL(`INIT_CALL_CNT`,0) AS INIT_CALL_CNT,
		IFNULL(`END_CALL_CNT`,0) AS END_CALL_CNT,
		IFNULL(`SIGNAL_CNT`,0) AS SIGNAL_CNT,
		IFNULL(`DATA_CNT`,0) AS DATA_CNT,
		IFNULL(`UNSPECIFIED_CNT`,0) AS UNSPECIFIED_CNT,
		IFNULL(`CALL_DUR_SUM`,0) AS CALL_DUR_SUM,
		IFNULL(`BLOCK_CNT`,0) AS BLOCK_CNT,
		IFNULL(`DROP_CNT`,0) AS DROP_CNT,
		IFNULL(`CSFB_CNT`,0) AS CSFB_CNT,
		IFNULL(`INTER_FREQ_ATTEMPT_CNT`,0) AS INTER_FREQ_ATTEMPT_CNT,
		IFNULL(`INTER_FREQ_FAILURE_CNT`,0) AS INTER_FREQ_FAILURE_CNT,
		IFNULL(`INTRA_FREQ_ATTEMPT_CNT`,0) AS INTRA_FREQ_ATTEMPT_CNT,
		IFNULL(`INTRA_FREQ_FAILURE_CNT`,0) AS INTRA_FREQ_FAILURE_CNT,
		IFNULL(`4G_3G_ATTEMPT_CNT`,0) AS 4G_3G_ATTEMPT_CNT,
		IFNULL(`4G_3G_FAILURE_CNT`,0) AS 4G_3G_FAILURE_CNT,
		IFNULL(`4G_2G_ATTEMPT_CNT`,0) AS 4G_2G_ATTEMPT_CNT,
		IFNULL(`4G_2G_FAILURE_CNT`,0) AS 4G_2G_FAILURE_CNT,
		IFNULL(`PS_UL_VOLUME_SUM`,0) AS PS_UL_VOLUME_SUM,
		IFNULL(`PS_DL_VOLUME_SUM`,0) AS PS_DL_VOLUME_SUM,
		IFNULL(`PS_UL_SPEED_MAX`,0) AS PS_UL_SPEED_MAX,
		IFNULL(`PS_DL_SPEED_MAX`,0) AS PS_DL_SPEED_MAX,
		IFNULL(`RSRP_SUM`,0) AS RSRP_SUM,
		IFNULL(`RSRP_CNT`,0) AS RSRP_CNT,
		IFNULL(`RSRQ_SUM`,0) AS RSRQ_SUM,
		IFNULL(`RSRQ_CNT`,0) AS RSRQ_CNT,
		IFNULL(`PILOT_DOMINANCE_SUM`,0) AS PILOT_DOMINANCE_SUM,
		IFNULL(`PILOT_DOMINANCE_CNT`,0) AS PILOT_DOMINANCE_CNT,
		IFNULL(`DROP_SIGNAL_CNT`,0) AS DROP_SIGNAL_CNT,
		IFNULL(`DROP_DATA_CNT`,0) AS DROP_DATA_CNT,
		IFNULL(`END_NON_BLOCK_CALL_CNT`,0) AS END_NON_BLOCK_CALL_CNT,
		IFNULL(`UL_THROUPUT_SUM`,0) AS UL_THROUPUT_SUM,
		IFNULL(`UL_THROUPUT_CNT`,0) AS UL_THROUPUT_CNT,
		IFNULL(`DL_THROUPUT_SUM`,0) AS DL_THROUPUT_SUM,
		IFNULL(`DL_THROUPUT_CNT`,0) AS DL_THROUPUT_CNT,
		IFNULL(`END_NON_BLOCK_SIGNAL_CNT`,0) AS END_NON_BLOCK_SIGNAL_CNT,
		IFNULL(`END_NON_BLOCK_DATA_CNT`,0) AS END_NON_BLOCK_DATA_CNT,
		IFNULL(`MR_4G_RSRP_SERVING_SUM`,0) AS MR_4G_RSRP_SERVING_SUM,
		IFNULL(`MR_4G_RSRP_SERVING_CNT`,0) AS MR_4G_RSRP_SERVING_CNT,
		IFNULL(`MR_4G_RSRQ_SERVING_SUM`,0) AS MR_4G_RSRQ_SERVING_SUM,
		IFNULL(`MR_4G_RSRQ_SERVING_CNT`,0) AS MR_4G_RSRQ_SERVING_CNT';
		
	DECLARE TILE_LTE_COLUMN_SUM_STR VARCHAR(3000) DEFAULT 
		'SUM(IFNULL(`INIT_CALL_CNT`,0)) AS INIT_CALL_CNT,
		SUM(IFNULL(`END_CALL_CNT`,0)) AS END_CALL_CNT,
		SUM(IFNULL(`SIGNAL_CNT`,0)) AS SIGNAL_CNT,
		SUM(IFNULL(`DATA_CNT`,0)) AS DATA_CNT,
		SUM(IFNULL(`UNSPECIFIED_CNT`,0)) AS UNSPECIFIED_CNT,
		SUM(IFNULL(`CALL_DUR_SUM`,0)) AS CALL_DUR_SUM,
		SUM(IFNULL(`BLOCK_CNT`,0)) AS BLOCK_CNT,
		SUM(IFNULL(`DROP_CNT`,0)) AS DROP_CNT,
		SUM(IFNULL(`CSFB_CNT`,0)) AS CSFB_CNT,
		SUM(IFNULL(`INTER_FREQ_ATTEMPT_CNT`,0)) AS INTER_FREQ_ATTEMPT_CNT,
		SUM(IFNULL(`INTER_FREQ_FAILURE_CNT`,0)) AS INTER_FREQ_FAILURE_CNT,
		SUM(IFNULL(`INTRA_FREQ_ATTEMPT_CNT`,0)) AS INTRA_FREQ_ATTEMPT_CNT,
		SUM(IFNULL(`INTRA_FREQ_FAILURE_CNT`,0)) AS INTRA_FREQ_FAILURE_CNT,
		SUM(IFNULL(`4G_3G_ATTEMPT_CNT`,0)) AS 4G_3G_ATTEMPT_CNT,
		SUM(IFNULL(`4G_3G_FAILURE_CNT`,0)) AS 4G_3G_FAILURE_CNT,
		SUM(IFNULL(`4G_2G_ATTEMPT_CNT`,0)) AS 4G_2G_ATTEMPT_CNT,
		SUM(IFNULL(`4G_2G_FAILURE_CNT`,0)) AS 4G_2G_FAILURE_CNT,
		SUM(IFNULL(`PS_UL_VOLUME_SUM`,0)) AS PS_UL_VOLUME_SUM,
		SUM(IFNULL(`PS_DL_VOLUME_SUM`,0)) AS PS_DL_VOLUME_SUM,
		MAX(IFNULL(`PS_UL_SPEED_MAX`,0)) AS PS_UL_SPEED_MAX,
		MAX(IFNULL(`PS_DL_SPEED_MAX`,0)) AS PS_DL_SPEED_MAX,
		SUM(IFNULL(`RSRP_SUM`,0)) AS RSRP_SUM,
		SUM(IFNULL(`RSRP_CNT`,0)) AS RSRP_CNT,
		SUM(IFNULL(`RSRQ_SUM`,0)) AS RSRQ_SUM,
		SUM(IFNULL(`RSRQ_CNT`,0)) AS RSRQ_CNT,
		SUM(IFNULL(`PILOT_DOMINANCE_SUM`,0)) AS PILOT_DOMINANCE_SUM,
		SUM(IFNULL(`PILOT_DOMINANCE_CNT`,0)) AS PILOT_DOMINANCE_CNT,
		SUM(IFNULL(`DROP_SIGNAL_CNT`,0)) AS DROP_SIGNAL_CNT,
		SUM(IFNULL(`DROP_DATA_CNT`,0)) AS DROP_DATA_CNT,
		SUM(IFNULL(`END_NON_BLOCK_CALL_CNT`,0)) AS END_NON_BLOCK_CALL_CNT,
		SUM(IFNULL(`UL_THROUPUT_SUM`,0)) AS UL_THROUPUT_SUM,
		SUM(IFNULL(`UL_THROUPUT_CNT`,0)) AS UL_THROUPUT_CNT,
		SUM(IFNULL(`DL_THROUPUT_SUM`,0)) AS DL_THROUPUT_SUM,
		SUM(IFNULL(`DL_THROUPUT_CNT`,0)) AS DL_THROUPUT_CNT,
		SUM(IFNULL(`END_NON_BLOCK_SIGNAL_CNT`,0)) AS END_NON_BLOCK_SIGNAL_CNT,
		SUM(IFNULL(`END_NON_BLOCK_DATA_CNT`,0)) AS END_NON_BLOCK_DATA_CNT,
		SUM(IFNULL(`MR_4G_RSRP_SERVING_SUM`,0)) AS MR_4G_RSRP_SERVING_SUM,
		SUM(IFNULL(`MR_4G_RSRP_SERVING_CNT`,0)) AS MR_4G_RSRP_SERVING_CNT,
		SUM(IFNULL(`MR_4G_RSRQ_SERVING_SUM`,0)) AS MR_4G_RSRQ_SERVING_SUM,
		SUM(IFNULL(`MR_4G_RSRQ_SERVING_CNT`,0)) AS MR_4G_RSRQ_SERVING_CNT';
		
	DECLARE TILE_LTE_COLUMN_UPD_STR VARCHAR(10000) DEFAULT
		'RPT_TABLE_NAME.INIT_CALL_CNT=RPT_TABLE_NAME.INIT_CALL_CNT+VALUES(INIT_CALL_CNT),
		RPT_TABLE_NAME.END_CALL_CNT=RPT_TABLE_NAME.END_CALL_CNT+VALUES(END_CALL_CNT),
		RPT_TABLE_NAME.SIGNAL_CNT=RPT_TABLE_NAME.SIGNAL_CNT+VALUES(SIGNAL_CNT),
		RPT_TABLE_NAME.DATA_CNT=RPT_TABLE_NAME.DATA_CNT+VALUES(DATA_CNT),
		RPT_TABLE_NAME.UNSPECIFIED_CNT=RPT_TABLE_NAME.UNSPECIFIED_CNT+VALUES(UNSPECIFIED_CNT),
		RPT_TABLE_NAME.CALL_DUR_SUM=RPT_TABLE_NAME.CALL_DUR_SUM+VALUES(CALL_DUR_SUM),
		RPT_TABLE_NAME.BLOCK_CNT=RPT_TABLE_NAME.BLOCK_CNT+VALUES(BLOCK_CNT),
		RPT_TABLE_NAME.DROP_CNT=RPT_TABLE_NAME.DROP_CNT+VALUES(DROP_CNT),
		RPT_TABLE_NAME.CSFB_CNT=RPT_TABLE_NAME.CSFB_CNT+VALUES(CSFB_CNT),
		RPT_TABLE_NAME.INTER_FREQ_ATTEMPT_CNT=RPT_TABLE_NAME.INTER_FREQ_ATTEMPT_CNT+VALUES(INTER_FREQ_ATTEMPT_CNT),
		RPT_TABLE_NAME.INTER_FREQ_FAILURE_CNT=RPT_TABLE_NAME.INTER_FREQ_FAILURE_CNT+VALUES(INTER_FREQ_FAILURE_CNT),
		RPT_TABLE_NAME.INTRA_FREQ_ATTEMPT_CNT=RPT_TABLE_NAME.INTRA_FREQ_ATTEMPT_CNT+VALUES(INTRA_FREQ_ATTEMPT_CNT),
		RPT_TABLE_NAME.INTRA_FREQ_FAILURE_CNT=RPT_TABLE_NAME.INTRA_FREQ_FAILURE_CNT+VALUES(INTRA_FREQ_FAILURE_CNT),
		RPT_TABLE_NAME.4G_3G_ATTEMPT_CNT=RPT_TABLE_NAME.4G_3G_ATTEMPT_CNT+VALUES(4G_3G_ATTEMPT_CNT),
		RPT_TABLE_NAME.4G_3G_FAILURE_CNT=RPT_TABLE_NAME.4G_3G_FAILURE_CNT+VALUES(4G_3G_FAILURE_CNT),
		RPT_TABLE_NAME.4G_2G_ATTEMPT_CNT=RPT_TABLE_NAME.4G_2G_ATTEMPT_CNT+VALUES(4G_2G_ATTEMPT_CNT),
		RPT_TABLE_NAME.4G_2G_FAILURE_CNT=RPT_TABLE_NAME.4G_2G_FAILURE_CNT+VALUES(4G_2G_FAILURE_CNT),
		RPT_TABLE_NAME.PS_UL_VOLUME_SUM=RPT_TABLE_NAME.PS_UL_VOLUME_SUM+VALUES(PS_UL_VOLUME_SUM),
		RPT_TABLE_NAME.PS_DL_VOLUME_SUM=RPT_TABLE_NAME.PS_DL_VOLUME_SUM+VALUES(PS_DL_VOLUME_SUM),
		RPT_TABLE_NAME.PS_UL_SPEED_MAX=CASE WHEN RPT_TABLE_NAME.PS_UL_SPEED_MAX > VALUES(PS_UL_SPEED_MAX) THEN RPT_TABLE_NAME.PS_UL_SPEED_MAX ELSE VALUES(PS_UL_SPEED_MAX) END,    
		RPT_TABLE_NAME.PS_DL_SPEED_MAX=CASE WHEN RPT_TABLE_NAME.PS_DL_SPEED_MAX > VALUES(PS_DL_SPEED_MAX) THEN RPT_TABLE_NAME.PS_DL_SPEED_MAX ELSE VALUES(PS_DL_SPEED_MAX) END,
		RPT_TABLE_NAME.RSRP_SUM=RPT_TABLE_NAME.RSRP_SUM+VALUES(RSRP_SUM),
		RPT_TABLE_NAME.RSRP_CNT=RPT_TABLE_NAME.RSRP_CNT+VALUES(RSRP_CNT),
		RPT_TABLE_NAME.RSRQ_SUM=RPT_TABLE_NAME.RSRQ_SUM+VALUES(RSRQ_SUM),
		RPT_TABLE_NAME.RSRQ_CNT=RPT_TABLE_NAME.RSRQ_CNT+VALUES(RSRQ_CNT),
		RPT_TABLE_NAME.PILOT_DOMINANCE_SUM=RPT_TABLE_NAME.PILOT_DOMINANCE_SUM+VALUES(PILOT_DOMINANCE_SUM),
		RPT_TABLE_NAME.PILOT_DOMINANCE_CNT=RPT_TABLE_NAME.PILOT_DOMINANCE_CNT+VALUES(PILOT_DOMINANCE_CNT),
		RPT_TABLE_NAME.DROP_SIGNAL_CNT=RPT_TABLE_NAME.DROP_SIGNAL_CNT+VALUES(DROP_SIGNAL_CNT),
		RPT_TABLE_NAME.DROP_DATA_CNT=RPT_TABLE_NAME.DROP_DATA_CNT+VALUES(DROP_DATA_CNT),
		RPT_TABLE_NAME.END_NON_BLOCK_CALL_CNT=RPT_TABLE_NAME.END_NON_BLOCK_CALL_CNT+VALUES(END_NON_BLOCK_CALL_CNT),
		RPT_TABLE_NAME.UL_THROUPUT_SUM=RPT_TABLE_NAME.UL_THROUPUT_SUM+VALUES(UL_THROUPUT_SUM),
		RPT_TABLE_NAME.UL_THROUPUT_CNT=RPT_TABLE_NAME.UL_THROUPUT_CNT+VALUES(UL_THROUPUT_CNT),
		RPT_TABLE_NAME.DL_THROUPUT_SUM=RPT_TABLE_NAME.DL_THROUPUT_SUM+VALUES(DL_THROUPUT_SUM),
		RPT_TABLE_NAME.DL_THROUPUT_CNT=RPT_TABLE_NAME.DL_THROUPUT_CNT+VALUES(DL_THROUPUT_CNT),
		RPT_TABLE_NAME.END_NON_BLOCK_SIGNAL_CNT=RPT_TABLE_NAME.END_NON_BLOCK_SIGNAL_CNT+VALUES(END_NON_BLOCK_SIGNAL_CNT),
		RPT_TABLE_NAME.END_NON_BLOCK_DATA_CNT=RPT_TABLE_NAME.END_NON_BLOCK_DATA_CNT+VALUES(END_NON_BLOCK_DATA_CNT),
		RPT_TABLE_NAME.MR_4G_RSRP_SERVING_SUM=RPT_TABLE_NAME.MR_4G_RSRP_SERVING_SUM+VALUES(MR_4G_RSRP_SERVING_SUM),
		RPT_TABLE_NAME.MR_4G_RSRP_SERVING_CNT=RPT_TABLE_NAME.MR_4G_RSRP_SERVING_CNT+VALUES(MR_4G_RSRP_SERVING_CNT),
		RPT_TABLE_NAME.MR_4G_RSRQ_SERVING_SUM=RPT_TABLE_NAME.MR_4G_RSRQ_SERVING_SUM+VALUES(MR_4G_RSRQ_SERVING_SUM),
		RPT_TABLE_NAME.MR_4G_RSRQ_SERVING_CNT=RPT_TABLE_NAME.MR_4G_RSRQ_SERVING_CNT+VALUES(MR_4G_RSRQ_SERVING_CNT)';
		
	DECLARE TILE_GSM_COLUMN_STR VARCHAR(1500) DEFAULT 
		'INIT_CALL_CNT, 
		  END_CALL_CNT,
		  VOICE_CNT,
		  SIGNAL_CNT,
		  SMS_CNT,
		  GPRS_CNT,
		  OTHER_CNT,
		  BLOCK_CNT,
		  DROP_VOICE_CNT,
		  DROP_SIGNAL_CNT,
		  DROP_SMS_CNT,
		  DROP_GPRS_CNT,
		  DROP_OTHER_CNT,
		  NON_BLOCK_VOICE_CNT,
		  NON_BLOCK_SIGNAL_CNT,
		  NON_BLOCK_SMS_CNT,
		  NON_BLOCK_GPRS_CNT,
		  NON_BLOCK_OTHER_CNT,
		  CALL_DUR_SUM,
		  RXLEV_SUM,
		  RXLEV_CNT,
		  RXQUAL_SUM,
		  RXQUAL_CNT';
		
	DECLARE TILE_GSM_COLUMN_IFNULL_STR VARCHAR(2000) DEFAULT 
		'IFNULL(INIT_CALL_CNT,0) AS INIT_CALL_CNT,           
		IFNULL(END_CALL_CNT,0) AS END_CALL_CNT,          
		IFNULL(VOICE_CNT,0) AS VOICE_CNT,           
		IFNULL(SIGNAL_CNT,0) AS SIGNAL_CNT,          
		IFNULL(SMS_CNT,0) AS SMS_CNT,             
		IFNULL(GPRS_CNT,0) AS GPRS_CNT,            
		IFNULL(OTHER_CNT,0) AS OTHER_CNT,           
		IFNULL(BLOCK_CNT,0) AS BLOCK_CNT,           
		IFNULL(DROP_VOICE_CNT,0) AS DROP_VOICE_CNT,      
		IFNULL(DROP_SIGNAL_CNT,0) AS DROP_SIGNAL_CNT,     
		IFNULL(DROP_SMS_CNT,0) AS DROP_SMS_CNT,        
		IFNULL(DROP_GPRS_CNT,0) AS DROP_GPRS_CNT,       
		IFNULL(DROP_OTHER_CNT,0) AS DROP_OTHER_CNT,      
		IFNULL(NON_BLOCK_VOICE_CNT,0) AS NON_BLOCK_VOICE_CNT, 
		IFNULL(NON_BLOCK_SIGNAL_CNT,0) AS NON_BLOCK_SIGNAL_CNT,
		IFNULL(NON_BLOCK_SMS_CNT,0) AS NON_BLOCK_SMS_CNT,   
		IFNULL(NON_BLOCK_GPRS_CNT,0) AS NON_BLOCK_GPRS_CNT,  
		IFNULL(NON_BLOCK_OTHER_CNT,0) AS NON_BLOCK_OTHER_CNT, 
		IFNULL(CALL_DUR_SUM,0) AS CALL_DUR_SUM, 
		IFNULL(RXLEV_SUM,0) AS RXLEV_SUM,           
		IFNULL(RXLEV_CNT,0) AS RXLEV_CNT,           
		IFNULL(RXQUAL_SUM,0) AS RXQUAL_SUM,          
		IFNULL(RXQUAL_CNT,0) AS RXQUAL_CNT';
		
	DECLARE TILE_GSM_COLUMN_SUM_STR VARCHAR(2000) DEFAULT 
		'SUM(IFNULL(INIT_CALL_CNT,0)) AS INIT_CALL_CNT,           
		SUM(IFNULL(END_CALL_CNT,0)) AS END_CALL_CNT,          
		SUM(IFNULL(VOICE_CNT,0)) AS VOICE_CNT,
		SUM(IFNULL(SIGNAL_CNT,0)) AS SIGNAL_CNT,
		SUM(IFNULL(SMS_CNT,0)) AS SMS_CNT,
		SUM(IFNULL(GPRS_CNT,0)) AS GPRS_CNT,
		SUM(IFNULL(OTHER_CNT,0)) AS OTHER_CNT,
		SUM(IFNULL(BLOCK_CNT,0)) AS BLOCK_CNT,
		SUM(IFNULL(DROP_VOICE_CNT,0)) AS DROP_VOICE_CNT,
		SUM(IFNULL(DROP_SIGNAL_CNT,0)) AS DROP_SIGNAL_CNT,
		SUM(IFNULL(DROP_SMS_CNT,0)) AS DROP_SMS_CNT,
		SUM(IFNULL(DROP_GPRS_CNT,0)) AS DROP_GPRS_CNT,
		SUM(IFNULL(DROP_OTHER_CNT,0)) AS DROP_OTHER_CNT,
		SUM(IFNULL(NON_BLOCK_VOICE_CNT,0)) AS NON_BLOCK_VOICE_CNT,
		SUM(IFNULL(NON_BLOCK_SIGNAL_CNT,0)) AS NON_BLOCK_SIGNAL_CNT,
		SUM(IFNULL(NON_BLOCK_SMS_CNT,0)) AS NON_BLOCK_SMS_CNT,
		SUM(IFNULL(NON_BLOCK_GPRS_CNT,0)) AS NON_BLOCK_GPRS_CNT,
		SUM(IFNULL(NON_BLOCK_OTHER_CNT,0)) AS NON_BLOCK_OTHER_CNT,
		SUM(IFNULL(CALL_DUR_SUM,0)) AS CALL_DUR_SUM,
		SUM(IFNULL(RXLEV_SUM,0)) AS RXLEV_SUM,
		SUM(IFNULL(RXLEV_CNT,0)) AS RXLEV_CNT,
		SUM(IFNULL(RXQUAL_SUM,0)) AS RXQUAL_SUM,
		SUM(IFNULL(RXQUAL_CNT,0)) AS RXQUAL_CNT';
		
	DECLARE TILE_GSM_COLUMN_UPD_STR VARCHAR(10000) DEFAULT
		'RPT_TABLE_NAME.INIT_CALL_CNT=RPT_TABLE_NAME.INIT_CALL_CNT+VALUES(INIT_CALL_CNT),
		RPT_TABLE_NAME.END_CALL_CNT=RPT_TABLE_NAME.END_CALL_CNT+VALUES(END_CALL_CNT),
		RPT_TABLE_NAME.VOICE_CNT=RPT_TABLE_NAME.VOICE_CNT+VALUES(VOICE_CNT),
		RPT_TABLE_NAME.SIGNAL_CNT=RPT_TABLE_NAME.SIGNAL_CNT+VALUES(SIGNAL_CNT),
		RPT_TABLE_NAME.SMS_CNT=RPT_TABLE_NAME.SMS_CNT+VALUES(SMS_CNT),
		RPT_TABLE_NAME.GPRS_CNT=RPT_TABLE_NAME.GPRS_CNT+VALUES(GPRS_CNT),
		RPT_TABLE_NAME.OTHER_CNT=RPT_TABLE_NAME.OTHER_CNT+VALUES(OTHER_CNT),
		RPT_TABLE_NAME.BLOCK_CNT=RPT_TABLE_NAME.BLOCK_CNT+VALUES(BLOCK_CNT),
		RPT_TABLE_NAME.DROP_VOICE_CNT=RPT_TABLE_NAME.DROP_VOICE_CNT+VALUES(DROP_VOICE_CNT),
		RPT_TABLE_NAME.DROP_SIGNAL_CNT=RPT_TABLE_NAME.DROP_SIGNAL_CNT+VALUES(DROP_SIGNAL_CNT),
		RPT_TABLE_NAME.DROP_SMS_CNT=RPT_TABLE_NAME.DROP_SMS_CNT+VALUES(DROP_SMS_CNT),
		RPT_TABLE_NAME.DROP_GPRS_CNT=RPT_TABLE_NAME.DROP_GPRS_CNT+VALUES(DROP_GPRS_CNT),
		RPT_TABLE_NAME.DROP_OTHER_CNT=RPT_TABLE_NAME.DROP_OTHER_CNT+VALUES(DROP_OTHER_CNT),
		RPT_TABLE_NAME.NON_BLOCK_VOICE_CNT=RPT_TABLE_NAME.NON_BLOCK_VOICE_CNT+VALUES(NON_BLOCK_VOICE_CNT),
		RPT_TABLE_NAME.NON_BLOCK_SIGNAL_CNT=RPT_TABLE_NAME.NON_BLOCK_SIGNAL_CNT+VALUES(NON_BLOCK_SIGNAL_CNT),
		RPT_TABLE_NAME.NON_BLOCK_SMS_CNT=RPT_TABLE_NAME.NON_BLOCK_SMS_CNT+VALUES(NON_BLOCK_SMS_CNT),
		RPT_TABLE_NAME.NON_BLOCK_GPRS_CNT=RPT_TABLE_NAME.NON_BLOCK_GPRS_CNT+VALUES(NON_BLOCK_GPRS_CNT),
		RPT_TABLE_NAME.NON_BLOCK_OTHER_CNT=RPT_TABLE_NAME.NON_BLOCK_OTHER_CNT+VALUES(NON_BLOCK_OTHER_CNT),
		RPT_TABLE_NAME.CALL_DUR_SUM=RPT_TABLE_NAME.CALL_DUR_SUM+VALUES(CALL_DUR_SUM),
		RPT_TABLE_NAME.RXLEV_SUM=RPT_TABLE_NAME.RXLEV_SUM+VALUES(RXLEV_SUM),
		RPT_TABLE_NAME.RXLEV_CNT=RPT_TABLE_NAME.RXLEV_CNT+VALUES(RXLEV_CNT),
		RPT_TABLE_NAME.RXQUAL_SUM=RPT_TABLE_NAME.RXQUAL_SUM+VALUES(RXQUAL_SUM),
		RPT_TABLE_NAME.RXQUAL_CNT=RPT_TABLE_NAME.RXQUAL_CNT+VALUES(RXQUAL_CNT)';
		
	DECLARE TILE_PU_MAPPING_COLUMN_STR VARCHAR(200) DEFAULT 
		' TILE_ID,PU_ID,DATA_DATE ';
				
	DECLARE TILE_LTE_REG_COLUMN_STR VARCHAR(200) DEFAULT 
		'RPT_TABLE_NAME.REG_1_ID=IF(RPT_TABLE_NAME.REG_1_ID IS NULL,VALUES(REG_1_ID),RPT_TABLE_NAME.REG_1_ID),
		RPT_TABLE_NAME.REG_2_ID=IF(RPT_TABLE_NAME.REG_2_ID IS NULL,VALUES(REG_2_ID),RPT_TABLE_NAME.REG_2_ID),
		RPT_TABLE_NAME.REG_3_ID=IF(RPT_TABLE_NAME.REG_3_ID IS NULL,VALUES(REG_3_ID),RPT_TABLE_NAME.REG_3_ID)';
	DECLARE TILE_UMTS_ROAMER_COLUMN_STR VARCHAR(2000) DEFAULT 
		'`INIT_CALL_CNT`,
		  `END_CALL_CNT`,
		  `VOICE_CNT`,
		  `VIDEO_CNT`,
		  `PS_R99_CNT`,
		  `PS_HSPA_CNT`,
		  `M_RAB_CNT`, 
		  `SIGNAL_CNT`,
		  `SMS_CNT`,
		  `PS_OTHER_CNT`,
		  `CALL_DUR_SUM`,
		  `CS_DUR_SUM`,
		  `DROP_CNT`,
		  `BLOCK_CNT`,
		  `DROP_VOICE_CNT`,
		  `DROP_VIDEO_CNT`,
		  `DROP_PS_R99_CNT`,
		  `DROP_PS_HSPA_CNT`,
		  `DROP_M_RAB_CNT`,
		  `DROP_SIGNAL_CNT`,
		  `DROP_SMS_CNT`,
		  `DROP_PS_OTHER_CNT`,
		  `PS_UL_VOLUME_SUM`,
		  `PS_DL_VOLUME_SUM`,
		  `PS_UL_SPEED_MAX`,
		  `PS_DL_SPEED_MAX`,
		  `UL_THROUPUT_SUM`,
		  `UL_THROUPUT_CNT`,
		  `DL_THROUPUT_SUM`,
		  `DL_THROUPUT_CNT`,
		  `NON_BLOCK_VOICE_CNT`,
		  `NON_BLOCK_VIDEO_CNT`,
		  `NON_BLOCK_PS_R99_CNT`,
		  `NON_BLOCK_PS_HSPA_CNT`,
		  `NON_BLOCK_M_RAB_CNT`,
		  `NON_BLOCK_SIGNAL_CNT`,
		  `NON_BLOCK_SMS_CNT`,
		  `NON_BLOCK_PS_OTHER_CNT`,
		  `PS_CNT`,
		  `DROP_PS_CNT`,
		  `CALL_SETUP_TIME_SUM`,
		  `CALL_SETUP_TIME_CNT`,
		  `CALL_SETUP_TIME_VOICE_SUM`,
		  `CALL_SETUP_TIME_VOICE_CNT`,
		  `CALL_SETUP_TIME_VEDIO_SUM`,
		  `CALL_SETUP_TIME_VEDIO_CNT`,
		  `CALL_SETUP_TIME_R99_SUM`,
		  `CALL_SETUP_TIME_R99_CNT`,
		  `CALL_SETUP_TIME_HSPA_SUM`,
		  `CALL_SETUP_TIME_HSPA_CNT`,
		  `CALL_SETUP_TIME_MRAB_SUM`,
		  `CALL_SETUP_TIME_MRAB_CNT`,
		  `CALL_SETUP_TIME_SIG_SUM`,
		  `CALL_SETUP_TIME_SIG_CNT`,
		  `CALL_SETUP_TIME_OTH_SUM`,
		  `CALL_SETUP_TIME_OTH_CNT`,
		  `CALL_SETUP_TIME_SMS_SUM`,
		  `CALL_SETUP_TIME_SMS_CNT`';
		  
	DECLARE TILE_UMTS_ROAMER_COLUMN_IFNULL_STR VARCHAR(6000) DEFAULT 
		'IFNULL(INIT_CALL_CNT,0) AS INIT_CALL_CNT,
		IFNULL(END_CALL_CNT,0) AS END_CALL_CNT,
		IFNULL(VOICE_CNT,0) AS VOICE_CNT,
		IFNULL(VIDEO_CNT,0) AS VIDEO_CNT,
		IFNULL(PS_R99_CNT,0) AS PS_R99_CNT,
		IFNULL(PS_HSPA_CNT,0) AS PS_HSPA_CNT,
		IFNULL(M_RAB_CNT,0) AS M_RAB_CNT,
		IFNULL(SIGNAL_CNT,0) AS SIGNAL_CNT,
		IFNULL(SMS_CNT,0) AS SMS_CNT,
		IFNULL(PS_OTHER_CNT,0) AS PS_OTHER_CNT,
		IFNULL(CALL_DUR_SUM,0) AS CALL_DUR_SUM,
		IFNULL(CS_DUR_SUM,0) AS CS_DUR_SUM,
		IFNULL(DROP_CNT,0) AS DROP_CNT,
		IFNULL(BLOCK_CNT,0) AS BLOCK_CNT,
		IFNULL(DROP_VOICE_CNT,0) AS DROP_VOICE_CNT,
		IFNULL(DROP_VIDEO_CNT,0) AS DROP_VIDEO_CNT,
		IFNULL(DROP_PS_R99_CNT,0) AS DROP_PS_R99_CNT,
		IFNULL(DROP_PS_HSPA_CNT,0) AS DROP_PS_HSPA_CNT,
		IFNULL(DROP_M_RAB_CNT,0) AS DROP_M_RAB_CNT,
		IFNULL(DROP_SIGNAL_CNT,0) AS DROP_SIGNAL_CNT,
		IFNULL(DROP_SMS_CNT,0) AS DROP_SMS_CNT,
		IFNULL(DROP_PS_OTHER_CNT,0) AS DROP_PS_OTHER_CNT,
		IFNULL(PS_UL_VOLUME_SUM,0) AS PS_UL_VOLUME_SUM,
		IFNULL(PS_DL_VOLUME_SUM,0) AS PS_DL_VOLUME_SUM,
		IFNULL(PS_UL_SPEED_MAX,0) AS PS_UL_SPEED_MAX,
		IFNULL(PS_DL_SPEED_MAX,0) AS PS_DL_SPEED_MAX,
		IFNULL(UL_THROUPUT_SUM,0) AS UL_THROUPUT_SUM,
		IFNULL(UL_THROUPUT_CNT,0) AS UL_THROUPUT_CNT,
		IFNULL(DL_THROUPUT_SUM,0) AS DL_THROUPUT_SUM,
		IFNULL(DL_THROUPUT_CNT,0) AS DL_THROUPUT_CNT,
		IFNULL(NON_BLOCK_VOICE_CNT,0) AS NON_BLOCK_VOICE_CNT,
		IFNULL(NON_BLOCK_VIDEO_CNT,0) AS NON_BLOCK_VIDEO_CNT,
		IFNULL(NON_BLOCK_PS_R99_CNT,0) AS NON_BLOCK_PS_R99_CNT,
		IFNULL(NON_BLOCK_PS_HSPA_CNT,0) AS NON_BLOCK_PS_HSPA_CNT,
		IFNULL(NON_BLOCK_M_RAB_CNT,0) AS NON_BLOCK_M_RAB_CNT,
		IFNULL(NON_BLOCK_SIGNAL_CNT,0) AS NON_BLOCK_SIGNAL_CNT,
		IFNULL(NON_BLOCK_SMS_CNT,0) AS NON_BLOCK_SMS_CNT,
		IFNULL(NON_BLOCK_PS_OTHER_CNT,0) AS NON_BLOCK_PS_OTHER_CNT,
		IFNULL(PS_CNT,0) AS PS_CNT,
		IFNULL(DROP_PS_CNT,0) AS DROP_PS_CNT,
		IFNULL(CALL_SETUP_TIME_SUM,0) AS CALL_SETUP_TIME_SUM,
		IFNULL(CALL_SETUP_TIME_CNT,0) AS CALL_SETUP_TIME_CNT,
		IFNULL(`CALL_SETUP_TIME_VOICE_SUM`,0) AS `CALL_SETUP_TIME_VOICE_SUM`,
		IFNULL(`CALL_SETUP_TIME_VOICE_CNT`,0) AS `CALL_SETUP_TIME_VOICE_CNT`,
		IFNULL(`CALL_SETUP_TIME_VEDIO_SUM`,0) AS `CALL_SETUP_TIME_VEDIO_SUM`,
		IFNULL(`CALL_SETUP_TIME_VEDIO_CNT`,0) AS `CALL_SETUP_TIME_VEDIO_CNT`,
		IFNULL(`CALL_SETUP_TIME_R99_SUM`,0) AS `CALL_SETUP_TIME_R99_SUM`,
		IFNULL(`CALL_SETUP_TIME_R99_CNT`,0) AS `CALL_SETUP_TIME_R99_CNT`,
		IFNULL(`CALL_SETUP_TIME_HSPA_SUM`,0) AS `CALL_SETUP_TIME_HSPA_SUM`,
		IFNULL(`CALL_SETUP_TIME_HSPA_CNT`,0) AS `CALL_SETUP_TIME_HSPA_CNT`,
		IFNULL(`CALL_SETUP_TIME_MRAB_SUM`,0) AS `CALL_SETUP_TIME_MRAB_SUM`,
		IFNULL(`CALL_SETUP_TIME_MRAB_CNT`,0) AS `CALL_SETUP_TIME_MRAB_CNT`,
		IFNULL(`CALL_SETUP_TIME_SIG_SUM`,0) AS `CALL_SETUP_TIME_SIG_SUM`,
		IFNULL(`CALL_SETUP_TIME_SIG_CNT`,0) AS `CALL_SETUP_TIME_SIG_CNT`,
		IFNULL(`CALL_SETUP_TIME_OTH_SUM`,0) AS `CALL_SETUP_TIME_OTH_SUM`,
		IFNULL(`CALL_SETUP_TIME_OTH_CNT`,0) AS `CALL_SETUP_TIME_OTH_CNT`,
		IFNULL(`CALL_SETUP_TIME_SMS_SUM`,0) AS `CALL_SETUP_TIME_SMS_SUM`,
		IFNULL(`CALL_SETUP_TIME_SMS_CNT`,0) AS `CALL_SETUP_TIME_SMS_CNT`';
		
	DECLARE TILE_UMTS_ROAMER_COLUMN_SUM_STR VARCHAR(6000) DEFAULT 
		'SUM(IFNULL(INIT_CALL_CNT,0)) AS INIT_CALL_CNT,
		SUM(IFNULL(END_CALL_CNT,0)) AS END_CALL_CNT,
		SUM(IFNULL(VOICE_CNT,0)) AS VOICE_CNT,
		SUM(IFNULL(VIDEO_CNT,0)) AS VIDEO_CNT,
		SUM(IFNULL(PS_R99_CNT,0)) AS PS_R99_CNT,
		SUM(IFNULL(PS_HSPA_CNT,0)) AS PS_HSPA_CNT,
		SUM(IFNULL(M_RAB_CNT,0)) AS M_RAB_CNT,
		SUM(IFNULL(SIGNAL_CNT,0)) AS SIGNAL_CNT,
		SUM(IFNULL(SMS_CNT,0)) AS SMS_CNT,
		SUM(IFNULL(PS_OTHER_CNT,0)) AS PS_OTHER_CNT,
		SUM(IFNULL(CALL_DUR_SUM,0)) AS CALL_DUR_SUM,
		SUM(IFNULL(CS_DUR_SUM,0)) AS CS_DUR_SUM,
		SUM(IFNULL(DROP_CNT,0)) AS DROP_CNT,
		SUM(IFNULL(BLOCK_CNT,0)) AS BLOCK_CNT,
		SUM(IFNULL(DROP_VOICE_CNT,0)) AS DROP_VOICE_CNT,
		SUM(IFNULL(DROP_VIDEO_CNT,0)) AS DROP_VIDEO_CNT,
		SUM(IFNULL(DROP_PS_R99_CNT,0)) AS DROP_PS_R99_CNT,
		SUM(IFNULL(DROP_PS_HSPA_CNT,0)) AS DROP_PS_HSPA_CNT,
		SUM(IFNULL(DROP_M_RAB_CNT,0)) AS DROP_M_RAB_CNT,
		SUM(IFNULL(DROP_SIGNAL_CNT,0)) AS DROP_SIGNAL_CNT,
		SUM(IFNULL(DROP_SMS_CNT,0)) AS DROP_SMS_CNT,
		SUM(IFNULL(DROP_PS_OTHER_CNT,0)) AS DROP_PS_OTHER_CNT,
		SUM(IFNULL(PS_UL_VOLUME_SUM,0)) AS PS_UL_VOLUME_SUM,
		SUM(IFNULL(PS_DL_VOLUME_SUM,0)) AS PS_DL_VOLUME_SUM,
		MAX(IFNULL(PS_UL_SPEED_MAX,0)) AS PS_UL_SPEED_MAX,
		MAX(IFNULL(PS_DL_SPEED_MAX,0)) AS PS_DL_SPEED_MAX,
		SUM(IFNULL(UL_THROUPUT_SUM,0)) AS UL_THROUPUT_SUM,
		SUM(IFNULL(UL_THROUPUT_CNT,0)) AS UL_THROUPUT_CNT,
		SUM(IFNULL(DL_THROUPUT_SUM,0)) AS DL_THROUPUT_SUM,
		SUM(IFNULL(DL_THROUPUT_CNT,0)) AS DL_THROUPUT_CNT,
		SUM(IFNULL(NON_BLOCK_VOICE_CNT,0)) AS NON_BLOCK_VOICE_CNT,
		SUM(IFNULL(NON_BLOCK_VIDEO_CNT,0)) AS NON_BLOCK_VIDEO_CNT,
		SUM(IFNULL(NON_BLOCK_PS_R99_CNT,0)) AS NON_BLOCK_PS_R99_CNT,
		SUM(IFNULL(NON_BLOCK_PS_HSPA_CNT,0)) AS NON_BLOCK_PS_HSPA_CNT,
		SUM(IFNULL(NON_BLOCK_M_RAB_CNT,0)) AS NON_BLOCK_M_RAB_CNT,
		SUM(IFNULL(NON_BLOCK_SIGNAL_CNT,0)) AS NON_BLOCK_SIGNAL_CNT,
		SUM(IFNULL(NON_BLOCK_SMS_CNT,0)) AS NON_BLOCK_SMS_CNT,
		SUM(IFNULL(NON_BLOCK_PS_OTHER_CNT,0)) AS NON_BLOCK_PS_OTHER_CNT,
		SUM(IFNULL(PS_CNT,0)) AS PS_CNT,
		SUM(IFNULL(DROP_PS_CNT,0)) AS DROP_PS_CNT,
		SUM(IFNULL(CALL_SETUP_TIME_SUM,0)) AS CALL_SETUP_TIME_SUM,
		SUM(IFNULL(CALL_SETUP_TIME_CNT,0)) AS CALL_SETUP_TIME_CNT,
		SUM(IFNULL(`CALL_SETUP_TIME_VOICE_SUM`,0)) AS `CALL_SETUP_TIME_VOICE_SUM`,
		SUM(IFNULL(`CALL_SETUP_TIME_VOICE_CNT`,0)) AS `CALL_SETUP_TIME_VOICE_CNT`,
		SUM(IFNULL(`CALL_SETUP_TIME_VEDIO_SUM`,0)) AS `CALL_SETUP_TIME_VEDIO_SUM`,
		SUM(IFNULL(`CALL_SETUP_TIME_VEDIO_CNT`,0)) AS `CALL_SETUP_TIME_VEDIO_CNT`,
		SUM(IFNULL(`CALL_SETUP_TIME_R99_SUM`,0)) AS `CALL_SETUP_TIME_R99_SUM`,
		SUM(IFNULL(`CALL_SETUP_TIME_R99_CNT`,0)) AS `CALL_SETUP_TIME_R99_CNT`,
		SUM(IFNULL(`CALL_SETUP_TIME_HSPA_SUM`,0)) AS `CALL_SETUP_TIME_HSPA_SUM`,
		SUM(IFNULL(`CALL_SETUP_TIME_HSPA_CNT`,0)) AS `CALL_SETUP_TIME_HSPA_CNT`,
		SUM(IFNULL(`CALL_SETUP_TIME_MRAB_SUM`,0)) AS `CALL_SETUP_TIME_MRAB_SUM`,
		SUM(IFNULL(`CALL_SETUP_TIME_MRAB_CNT`,0)) AS `CALL_SETUP_TIME_MRAB_CNT`,
		SUM(IFNULL(`CALL_SETUP_TIME_SIG_SUM`,0)) AS `CALL_SETUP_TIME_SIG_SUM`,
		SUM(IFNULL(`CALL_SETUP_TIME_SIG_CNT`,0)) AS `CALL_SETUP_TIME_SIG_CNT`,
		SUM(IFNULL(`CALL_SETUP_TIME_OTH_SUM`,0)) AS `CALL_SETUP_TIME_OTH_SUM`,
		SUM(IFNULL(`CALL_SETUP_TIME_OTH_CNT`,0)) AS `CALL_SETUP_TIME_OTH_CNT`,
		SUM(IFNULL(`CALL_SETUP_TIME_SMS_SUM`,0)) AS `CALL_SETUP_TIME_SMS_SUM`,
		SUM(IFNULL(`CALL_SETUP_TIME_SMS_CNT`,0)) AS `CALL_SETUP_TIME_SMS_CNT`';
	
	DECLARE TILE_UMTS_ROAMER_COLUMN_UPD_STR VARCHAR(10000) DEFAULT
		'RPT_TABLE_NAME.INIT_CALL_CNT=RPT_TABLE_NAME.INIT_CALL_CNT+VALUES(INIT_CALL_CNT),
		RPT_TABLE_NAME.END_CALL_CNT=RPT_TABLE_NAME.END_CALL_CNT+VALUES(END_CALL_CNT),
		RPT_TABLE_NAME.VOICE_CNT=RPT_TABLE_NAME.VOICE_CNT+VALUES(VOICE_CNT),
		RPT_TABLE_NAME.VIDEO_CNT=RPT_TABLE_NAME.VIDEO_CNT+VALUES(VIDEO_CNT),
		RPT_TABLE_NAME.PS_R99_CNT=RPT_TABLE_NAME.PS_R99_CNT+VALUES(PS_R99_CNT),
		RPT_TABLE_NAME.PS_HSPA_CNT=RPT_TABLE_NAME.PS_HSPA_CNT+VALUES(PS_HSPA_CNT),
		RPT_TABLE_NAME.M_RAB_CNT=RPT_TABLE_NAME.M_RAB_CNT+VALUES(M_RAB_CNT),
		RPT_TABLE_NAME.SIGNAL_CNT=RPT_TABLE_NAME.SIGNAL_CNT+VALUES(SIGNAL_CNT),
		RPT_TABLE_NAME.SMS_CNT=RPT_TABLE_NAME.SMS_CNT+VALUES(SMS_CNT),
		RPT_TABLE_NAME.PS_OTHER_CNT=RPT_TABLE_NAME.PS_OTHER_CNT+VALUES(PS_OTHER_CNT),
		RPT_TABLE_NAME.CALL_DUR_SUM=RPT_TABLE_NAME.CALL_DUR_SUM+VALUES(CALL_DUR_SUM),
		RPT_TABLE_NAME.CS_DUR_SUM=RPT_TABLE_NAME.CS_DUR_SUM+VALUES(CS_DUR_SUM),
		RPT_TABLE_NAME.DROP_CNT=RPT_TABLE_NAME.DROP_CNT+VALUES(DROP_CNT),
		RPT_TABLE_NAME.BLOCK_CNT=RPT_TABLE_NAME.BLOCK_CNT+VALUES(BLOCK_CNT),
		RPT_TABLE_NAME.DROP_VOICE_CNT=RPT_TABLE_NAME.DROP_VOICE_CNT+VALUES(DROP_VOICE_CNT),
		RPT_TABLE_NAME.DROP_VIDEO_CNT=RPT_TABLE_NAME.DROP_VIDEO_CNT+VALUES(DROP_VIDEO_CNT),
		RPT_TABLE_NAME.DROP_PS_R99_CNT=RPT_TABLE_NAME.DROP_PS_R99_CNT+VALUES(DROP_PS_R99_CNT),
		RPT_TABLE_NAME.DROP_PS_HSPA_CNT=RPT_TABLE_NAME.DROP_PS_HSPA_CNT+VALUES(DROP_PS_HSPA_CNT),
		RPT_TABLE_NAME.DROP_M_RAB_CNT=RPT_TABLE_NAME.DROP_M_RAB_CNT+VALUES(DROP_M_RAB_CNT),
		RPT_TABLE_NAME.DROP_SIGNAL_CNT=RPT_TABLE_NAME.DROP_SIGNAL_CNT+VALUES(DROP_SIGNAL_CNT),
		RPT_TABLE_NAME.DROP_SMS_CNT=RPT_TABLE_NAME.DROP_SMS_CNT+VALUES(DROP_SMS_CNT),
		RPT_TABLE_NAME.DROP_PS_OTHER_CNT=RPT_TABLE_NAME.DROP_PS_OTHER_CNT+VALUES(DROP_PS_OTHER_CNT),
		RPT_TABLE_NAME.PS_UL_VOLUME_SUM=RPT_TABLE_NAME.PS_UL_VOLUME_SUM+VALUES(PS_UL_VOLUME_SUM),
		RPT_TABLE_NAME.PS_DL_VOLUME_SUM=RPT_TABLE_NAME.PS_DL_VOLUME_SUM+VALUES(PS_DL_VOLUME_SUM),
		RPT_TABLE_NAME.PS_UL_SPEED_MAX=CASE WHEN RPT_TABLE_NAME.PS_UL_SPEED_MAX > VALUES(PS_UL_SPEED_MAX) THEN RPT_TABLE_NAME.PS_UL_SPEED_MAX ELSE VALUES(PS_UL_SPEED_MAX) END,    
		RPT_TABLE_NAME.PS_DL_SPEED_MAX=CASE WHEN RPT_TABLE_NAME.PS_DL_SPEED_MAX > VALUES(PS_DL_SPEED_MAX) THEN RPT_TABLE_NAME.PS_DL_SPEED_MAX ELSE VALUES(PS_DL_SPEED_MAX) END,
		RPT_TABLE_NAME.UL_THROUPUT_SUM=RPT_TABLE_NAME.UL_THROUPUT_SUM+VALUES(UL_THROUPUT_SUM),
		RPT_TABLE_NAME.UL_THROUPUT_CNT=RPT_TABLE_NAME.UL_THROUPUT_CNT+VALUES(UL_THROUPUT_CNT),
		RPT_TABLE_NAME.DL_THROUPUT_SUM=RPT_TABLE_NAME.DL_THROUPUT_SUM+VALUES(DL_THROUPUT_SUM),
		RPT_TABLE_NAME.DL_THROUPUT_CNT=RPT_TABLE_NAME.DL_THROUPUT_CNT+VALUES(DL_THROUPUT_CNT),
		RPT_TABLE_NAME.NON_BLOCK_VOICE_CNT=RPT_TABLE_NAME.NON_BLOCK_VOICE_CNT+VALUES(NON_BLOCK_VOICE_CNT),
		RPT_TABLE_NAME.NON_BLOCK_VIDEO_CNT=RPT_TABLE_NAME.NON_BLOCK_VIDEO_CNT+VALUES(NON_BLOCK_VIDEO_CNT),
		RPT_TABLE_NAME.NON_BLOCK_PS_R99_CNT=RPT_TABLE_NAME.NON_BLOCK_PS_R99_CNT+VALUES(NON_BLOCK_PS_R99_CNT),
		RPT_TABLE_NAME.NON_BLOCK_PS_HSPA_CNT=RPT_TABLE_NAME.NON_BLOCK_PS_HSPA_CNT+VALUES(NON_BLOCK_PS_HSPA_CNT),
		RPT_TABLE_NAME.NON_BLOCK_M_RAB_CNT=RPT_TABLE_NAME.NON_BLOCK_M_RAB_CNT+VALUES(NON_BLOCK_M_RAB_CNT),
		RPT_TABLE_NAME.NON_BLOCK_SIGNAL_CNT=RPT_TABLE_NAME.NON_BLOCK_SIGNAL_CNT+VALUES(NON_BLOCK_SIGNAL_CNT),
		RPT_TABLE_NAME.NON_BLOCK_SMS_CNT=RPT_TABLE_NAME.NON_BLOCK_SMS_CNT+VALUES(NON_BLOCK_SMS_CNT),
		RPT_TABLE_NAME.NON_BLOCK_PS_OTHER_CNT=RPT_TABLE_NAME.NON_BLOCK_PS_OTHER_CNT+VALUES(NON_BLOCK_PS_OTHER_CNT),
		RPT_TABLE_NAME.PS_CNT=RPT_TABLE_NAME.PS_CNT+VALUES(PS_CNT),
		RPT_TABLE_NAME.DROP_PS_CNT=RPT_TABLE_NAME.DROP_PS_CNT+VALUES(DROP_PS_CNT),
		RPT_TABLE_NAME.CALL_SETUP_TIME_SUM=RPT_TABLE_NAME.CALL_SETUP_TIME_SUM+VALUES(CALL_SETUP_TIME_SUM),
		RPT_TABLE_NAME.CALL_SETUP_TIME_CNT=RPT_TABLE_NAME.CALL_SETUP_TIME_CNT+VALUES(CALL_SETUP_TIME_CNT),
		RPT_TABLE_NAME.CALL_SETUP_TIME_VOICE_SUM=RPT_TABLE_NAME.CALL_SETUP_TIME_VOICE_SUM+VALUES(CALL_SETUP_TIME_VOICE_SUM),
		RPT_TABLE_NAME.CALL_SETUP_TIME_VOICE_CNT=RPT_TABLE_NAME.CALL_SETUP_TIME_VOICE_CNT+VALUES(CALL_SETUP_TIME_VOICE_CNT),
		RPT_TABLE_NAME.CALL_SETUP_TIME_VEDIO_SUM=RPT_TABLE_NAME.CALL_SETUP_TIME_VEDIO_SUM+VALUES(CALL_SETUP_TIME_VEDIO_SUM),
		RPT_TABLE_NAME.CALL_SETUP_TIME_VEDIO_CNT=RPT_TABLE_NAME.CALL_SETUP_TIME_VEDIO_CNT+VALUES(CALL_SETUP_TIME_VEDIO_CNT),
		RPT_TABLE_NAME.CALL_SETUP_TIME_R99_SUM=RPT_TABLE_NAME.CALL_SETUP_TIME_R99_SUM+VALUES(CALL_SETUP_TIME_R99_SUM),
		RPT_TABLE_NAME.CALL_SETUP_TIME_R99_CNT=RPT_TABLE_NAME.CALL_SETUP_TIME_R99_CNT+VALUES(CALL_SETUP_TIME_R99_CNT),
		RPT_TABLE_NAME.CALL_SETUP_TIME_HSPA_SUM=RPT_TABLE_NAME.CALL_SETUP_TIME_HSPA_SUM+VALUES(CALL_SETUP_TIME_HSPA_SUM),
		RPT_TABLE_NAME.CALL_SETUP_TIME_HSPA_CNT=RPT_TABLE_NAME.CALL_SETUP_TIME_HSPA_CNT+VALUES(CALL_SETUP_TIME_HSPA_CNT),
		RPT_TABLE_NAME.CALL_SETUP_TIME_MRAB_SUM=RPT_TABLE_NAME.CALL_SETUP_TIME_MRAB_SUM+VALUES(CALL_SETUP_TIME_MRAB_SUM),
		RPT_TABLE_NAME.CALL_SETUP_TIME_MRAB_CNT=RPT_TABLE_NAME.CALL_SETUP_TIME_MRAB_CNT+VALUES(CALL_SETUP_TIME_MRAB_CNT),
		RPT_TABLE_NAME.CALL_SETUP_TIME_SIG_SUM=RPT_TABLE_NAME.CALL_SETUP_TIME_SIG_SUM+VALUES(CALL_SETUP_TIME_SIG_SUM),
		RPT_TABLE_NAME.CALL_SETUP_TIME_SIG_CNT=RPT_TABLE_NAME.CALL_SETUP_TIME_SIG_CNT+VALUES(CALL_SETUP_TIME_SIG_CNT),
		RPT_TABLE_NAME.CALL_SETUP_TIME_OTH_SUM=RPT_TABLE_NAME.CALL_SETUP_TIME_OTH_SUM+VALUES(CALL_SETUP_TIME_OTH_SUM),
		RPT_TABLE_NAME.CALL_SETUP_TIME_OTH_CNT=RPT_TABLE_NAME.CALL_SETUP_TIME_OTH_CNT+VALUES(CALL_SETUP_TIME_OTH_CNT),
		RPT_TABLE_NAME.CALL_SETUP_TIME_SMS_SUM=RPT_TABLE_NAME.CALL_SETUP_TIME_SMS_SUM+VALUES(CALL_SETUP_TIME_SMS_SUM),
		RPT_TABLE_NAME.CALL_SETUP_TIME_SMS_CNT=RPT_TABLE_NAME.CALL_SETUP_TIME_SMS_CNT+VALUES(CALL_SETUP_TIME_SMS_CNT)';
	
	DECLARE TILE_LTE_ROAMER_COLUMN_STR VARCHAR(2500) DEFAULT 
		'`INIT_CALL_CNT`,
		`END_CALL_CNT`,
		`SIGNAL_CNT`,
		`DATA_CNT`,
		`UNSPECIFIED_CNT`,
		`CALL_DUR_SUM`,
		`BLOCK_CNT`,
		`DROP_CNT`,
		`CSFB_CNT`,
		`PS_UL_VOLUME_SUM`,
		`PS_DL_VOLUME_SUM`,
		`PS_UL_SPEED_MAX`,
		`PS_DL_SPEED_MAX`,
		`DROP_SIGNAL_CNT`,
		`DROP_DATA_CNT`,
		`END_NON_BLOCK_CALL_CNT`,
		`UL_THROUPUT_SUM`,
		`UL_THROUPUT_CNT`,
		`DL_THROUPUT_SUM`,
		`DL_THROUPUT_CNT`,
		`END_NON_BLOCK_SIGNAL_CNT`,
		`END_NON_BLOCK_DATA_CNT`,
		`CALL_SETUP_TIME_SUM`,
		`CALL_SETUP_TIME_CNT`,
		`CALL_SETUP_TIME_SIG_SUM`,
		`CALL_SETUP_TIME_SIG_CNT`,
		`CALL_SETUP_TIME_DATA_SUM`,
		`CALL_SETUP_TIME_DATA_CNT`,
		`CALL_SETUP_TIME_SMS_SUM`,
		`CALL_SETUP_TIME_SMS_CNT`,
		`CALL_SETUP_TIME_VOLTE_SUM`,
		`CALL_SETUP_TIME_VOLTE_CNT`,
		`CALL_SETUP_TIME_UNSP_SUM`,
		`CALL_SETUP_TIME_UNSP_CNT`';
		  
	DECLARE TILE_LTE_ROAMER_COLUMN_IFNULL_STR VARCHAR(2500) DEFAULT 
		'IFNULL(`INIT_CALL_CNT`,0) AS INIT_CALL_CNT,
		IFNULL(`END_CALL_CNT`,0) AS END_CALL_CNT,
		IFNULL(`SIGNAL_CNT`,0) AS SIGNAL_CNT,
		IFNULL(`DATA_CNT`,0) AS DATA_CNT,
		IFNULL(`UNSPECIFIED_CNT`,0) AS UNSPECIFIED_CNT,
		IFNULL(`CALL_DUR_SUM`,0) AS CALL_DUR_SUM,
		IFNULL(`BLOCK_CNT`,0) AS BLOCK_CNT,
		IFNULL(`DROP_CNT`,0) AS DROP_CNT,
		IFNULL(`CSFB_CNT`,0) AS CSFB_CNT,
		IFNULL(`PS_UL_VOLUME_SUM`,0) AS PS_UL_VOLUME_SUM,
		IFNULL(`PS_DL_VOLUME_SUM`,0) AS PS_DL_VOLUME_SUM,
		IFNULL(`PS_UL_SPEED_MAX`,0) AS PS_UL_SPEED_MAX,
		IFNULL(`PS_DL_SPEED_MAX`,0) AS PS_DL_SPEED_MAX,
		IFNULL(`DROP_SIGNAL_CNT`,0) AS DROP_SIGNAL_CNT,
		IFNULL(`DROP_DATA_CNT`,0) AS DROP_DATA_CNT,
		IFNULL(`END_NON_BLOCK_CALL_CNT`,0) AS END_NON_BLOCK_CALL_CNT,
		IFNULL(`UL_THROUPUT_SUM`,0) AS UL_THROUPUT_SUM,
		IFNULL(`UL_THROUPUT_CNT`,0) AS UL_THROUPUT_CNT,
		IFNULL(`DL_THROUPUT_SUM`,0) AS DL_THROUPUT_SUM,
		IFNULL(`DL_THROUPUT_CNT`,0) AS DL_THROUPUT_CNT,
		IFNULL(`END_NON_BLOCK_SIGNAL_CNT`,0) AS END_NON_BLOCK_SIGNAL_CNT,
		IFNULL(`END_NON_BLOCK_DATA_CNT`,0) AS END_NON_BLOCK_DATA_CNT,
		IFNULL(CALL_SETUP_TIME_SUM,0) AS CALL_SETUP_TIME_SUM,
		IFNULL(CALL_SETUP_TIME_CNT,0) AS CALL_SETUP_TIME_CNT,
		IFNULL(`CALL_SETUP_TIME_SIG_SUM`,0) AS `CALL_SETUP_TIME_SIG_SUM`,
		IFNULL(`CALL_SETUP_TIME_SIG_CNT`,0) AS `CALL_SETUP_TIME_SIG_CNT`,
		IFNULL(`CALL_SETUP_TIME_DATA_SUM`,0) AS `CALL_SETUP_TIME_DATA_SUM`,
		IFNULL(`CALL_SETUP_TIME_DATA_CNT`,0) AS `CALL_SETUP_TIME_DATA_CNT`,
		IFNULL(`CALL_SETUP_TIME_SMS_SUM`,0) AS `CALL_SETUP_TIME_SMS_SUM`,
		IFNULL(`CALL_SETUP_TIME_SMS_CNT`,0) AS `CALL_SETUP_TIME_SMS_CNT`,
		IFNULL(`CALL_SETUP_TIME_VOLTE_SUM`,0) AS `CALL_SETUP_TIME_VOLTE_SUM`,
		IFNULL(`CALL_SETUP_TIME_VOLTE_CNT`,0) AS `CALL_SETUP_TIME_VOLTE_CNT`,
		IFNULL(`CALL_SETUP_TIME_UNSP_SUM`,0) AS `CALL_SETUP_TIME_UNSP_SUM`,
		IFNULL(`CALL_SETUP_TIME_UNSP_CNT`,0) AS `CALL_SETUP_TIME_UNSP_CNT`';
		
	DECLARE TILE_LTE_ROAMER_COLUMN_SUM_STR VARCHAR(2500) DEFAULT 
		'SUM(IFNULL(`INIT_CALL_CNT`,0)) AS INIT_CALL_CNT,
		SUM(IFNULL(`END_CALL_CNT`,0)) AS END_CALL_CNT,
		SUM(IFNULL(`SIGNAL_CNT`,0)) AS SIGNAL_CNT,
		SUM(IFNULL(`DATA_CNT`,0)) AS DATA_CNT,
		SUM(IFNULL(`UNSPECIFIED_CNT`,0)) AS UNSPECIFIED_CNT,
		SUM(IFNULL(`CALL_DUR_SUM`,0)) AS CALL_DUR_SUM,
		SUM(IFNULL(`BLOCK_CNT`,0)) AS BLOCK_CNT,
		SUM(IFNULL(`DROP_CNT`,0)) AS DROP_CNT,
		SUM(IFNULL(`CSFB_CNT`,0)) AS CSFB_CNT,
		SUM(IFNULL(`PS_UL_VOLUME_SUM`,0)) AS PS_UL_VOLUME_SUM,
		SUM(IFNULL(`PS_DL_VOLUME_SUM`,0)) AS PS_DL_VOLUME_SUM,
		MAX(IFNULL(`PS_UL_SPEED_MAX`,0)) AS PS_UL_SPEED_MAX,
		MAX(IFNULL(`PS_DL_SPEED_MAX`,0)) AS PS_DL_SPEED_MAX,
		SUM(IFNULL(`DROP_SIGNAL_CNT`,0)) AS DROP_SIGNAL_CNT,
		SUM(IFNULL(`DROP_DATA_CNT`,0)) AS DROP_DATA_CNT,
		SUM(IFNULL(`END_NON_BLOCK_CALL_CNT`,0)) AS END_NON_BLOCK_CALL_CNT,
		SUM(IFNULL(`UL_THROUPUT_SUM`,0)) AS UL_THROUPUT_SUM,
		SUM(IFNULL(`UL_THROUPUT_CNT`,0)) AS UL_THROUPUT_CNT,
		SUM(IFNULL(`DL_THROUPUT_SUM`,0)) AS DL_THROUPUT_SUM,
		SUM(IFNULL(`DL_THROUPUT_CNT`,0)) AS DL_THROUPUT_CNT,
		SUM(IFNULL(`END_NON_BLOCK_SIGNAL_CNT`,0)) AS END_NON_BLOCK_SIGNAL_CNT,
		SUM(IFNULL(`END_NON_BLOCK_DATA_CNT`,0)) AS END_NON_BLOCK_DATA_CNT,
		SUM(IFNULL(CALL_SETUP_TIME_SUM,0)) AS CALL_SETUP_TIME_SUM,
		SUM(IFNULL(CALL_SETUP_TIME_CNT,0)) AS CALL_SETUP_TIME_CNT,
		SUM(IFNULL(`CALL_SETUP_TIME_SIG_SUM`,0)) AS `CALL_SETUP_TIME_SIG_SUM`,
		SUM(IFNULL(`CALL_SETUP_TIME_SIG_CNT`,0)) AS `CALL_SETUP_TIME_SIG_CNT`,
		SUM(IFNULL(`CALL_SETUP_TIME_DATA_SUM`,0)) AS `CALL_SETUP_TIME_DATA_SUM`,
		SUM(IFNULL(`CALL_SETUP_TIME_DATA_CNT`,0)) AS `CALL_SETUP_TIME_DATA_CNT`,
		SUM(IFNULL(`CALL_SETUP_TIME_SMS_SUM`,0)) AS `CALL_SETUP_TIME_SMS_SUM`,
		SUM(IFNULL(`CALL_SETUP_TIME_SMS_CNT`,0)) AS `CALL_SETUP_TIME_SMS_CNT`,
		SUM(IFNULL(`CALL_SETUP_TIME_VOLTE_SUM`,0)) AS `CALL_SETUP_TIME_VOLTE_SUM`,
		SUM(IFNULL(`CALL_SETUP_TIME_VOLTE_CNT`,0)) AS `CALL_SETUP_TIME_VOLTE_CNT`,
		SUM(IFNULL(`CALL_SETUP_TIME_UNSP_SUM`,0)) AS `CALL_SETUP_TIME_UNSP_SUM`,
		SUM(IFNULL(`CALL_SETUP_TIME_UNSP_CNT`,0)) AS `CALL_SETUP_TIME_UNSP_CNT`';
		
	DECLARE TILE_LTE_ROAMER_COLUMN_UPD_STR VARCHAR(10000) DEFAULT
		'RPT_TABLE_NAME.INIT_CALL_CNT=RPT_TABLE_NAME.INIT_CALL_CNT+VALUES(INIT_CALL_CNT),
		RPT_TABLE_NAME.END_CALL_CNT=RPT_TABLE_NAME.END_CALL_CNT+VALUES(END_CALL_CNT),
		RPT_TABLE_NAME.SIGNAL_CNT=RPT_TABLE_NAME.SIGNAL_CNT+VALUES(SIGNAL_CNT),
		RPT_TABLE_NAME.DATA_CNT=RPT_TABLE_NAME.DATA_CNT+VALUES(DATA_CNT),
		RPT_TABLE_NAME.UNSPECIFIED_CNT=RPT_TABLE_NAME.UNSPECIFIED_CNT+VALUES(UNSPECIFIED_CNT),
		RPT_TABLE_NAME.CALL_DUR_SUM=RPT_TABLE_NAME.CALL_DUR_SUM+VALUES(CALL_DUR_SUM),
		RPT_TABLE_NAME.BLOCK_CNT=RPT_TABLE_NAME.BLOCK_CNT+VALUES(BLOCK_CNT),
		RPT_TABLE_NAME.DROP_CNT=RPT_TABLE_NAME.DROP_CNT+VALUES(DROP_CNT),
		RPT_TABLE_NAME.CSFB_CNT=RPT_TABLE_NAME.CSFB_CNT+VALUES(CSFB_CNT),
		RPT_TABLE_NAME.PS_UL_VOLUME_SUM=RPT_TABLE_NAME.PS_UL_VOLUME_SUM+VALUES(PS_UL_VOLUME_SUM),
		RPT_TABLE_NAME.PS_DL_VOLUME_SUM=RPT_TABLE_NAME.PS_DL_VOLUME_SUM+VALUES(PS_DL_VOLUME_SUM),
		RPT_TABLE_NAME.PS_UL_SPEED_MAX=CASE WHEN RPT_TABLE_NAME.PS_UL_SPEED_MAX > VALUES(PS_UL_SPEED_MAX) THEN RPT_TABLE_NAME.PS_UL_SPEED_MAX ELSE VALUES(PS_UL_SPEED_MAX) END,    
		RPT_TABLE_NAME.PS_DL_SPEED_MAX=CASE WHEN RPT_TABLE_NAME.PS_DL_SPEED_MAX > VALUES(PS_DL_SPEED_MAX) THEN RPT_TABLE_NAME.PS_DL_SPEED_MAX ELSE VALUES(PS_DL_SPEED_MAX) END,
		RPT_TABLE_NAME.DROP_SIGNAL_CNT=RPT_TABLE_NAME.DROP_SIGNAL_CNT+VALUES(DROP_SIGNAL_CNT),
		RPT_TABLE_NAME.DROP_DATA_CNT=RPT_TABLE_NAME.DROP_DATA_CNT+VALUES(DROP_DATA_CNT),
		RPT_TABLE_NAME.END_NON_BLOCK_CALL_CNT=RPT_TABLE_NAME.END_NON_BLOCK_CALL_CNT+VALUES(END_NON_BLOCK_CALL_CNT),
		RPT_TABLE_NAME.UL_THROUPUT_SUM=RPT_TABLE_NAME.UL_THROUPUT_SUM+VALUES(UL_THROUPUT_SUM),
		RPT_TABLE_NAME.UL_THROUPUT_CNT=RPT_TABLE_NAME.UL_THROUPUT_CNT+VALUES(UL_THROUPUT_CNT),
		RPT_TABLE_NAME.DL_THROUPUT_SUM=RPT_TABLE_NAME.DL_THROUPUT_SUM+VALUES(DL_THROUPUT_SUM),
		RPT_TABLE_NAME.DL_THROUPUT_CNT=RPT_TABLE_NAME.DL_THROUPUT_CNT+VALUES(DL_THROUPUT_CNT),
		RPT_TABLE_NAME.END_NON_BLOCK_SIGNAL_CNT=RPT_TABLE_NAME.END_NON_BLOCK_SIGNAL_CNT+VALUES(END_NON_BLOCK_SIGNAL_CNT),
		RPT_TABLE_NAME.END_NON_BLOCK_DATA_CNT=RPT_TABLE_NAME.END_NON_BLOCK_DATA_CNT+VALUES(END_NON_BLOCK_DATA_CNT),
		RPT_TABLE_NAME.CALL_SETUP_TIME_SUM=RPT_TABLE_NAME.CALL_SETUP_TIME_SUM+VALUES(CALL_SETUP_TIME_SUM),
		RPT_TABLE_NAME.CALL_SETUP_TIME_CNT=RPT_TABLE_NAME.CALL_SETUP_TIME_CNT+VALUES(CALL_SETUP_TIME_CNT),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_SIG_SUM`=RPT_TABLE_NAME.`CALL_SETUP_TIME_SIG_SUM`+VALUES(`CALL_SETUP_TIME_SIG_SUM`),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_SIG_CNT`=RPT_TABLE_NAME.`CALL_SETUP_TIME_SIG_CNT`+VALUES(`CALL_SETUP_TIME_SIG_CNT`),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_DATA_SUM`=RPT_TABLE_NAME.`CALL_SETUP_TIME_DATA_SUM`+VALUES(`CALL_SETUP_TIME_DATA_SUM`),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_DATA_CNT`=RPT_TABLE_NAME.`CALL_SETUP_TIME_DATA_CNT`+VALUES(`CALL_SETUP_TIME_DATA_CNT`),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_SMS_SUM`=RPT_TABLE_NAME.`CALL_SETUP_TIME_SMS_SUM`+VALUES(`CALL_SETUP_TIME_SMS_SUM`),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_SMS_CNT`=RPT_TABLE_NAME.`CALL_SETUP_TIME_SMS_CNT`+VALUES(`CALL_SETUP_TIME_SMS_CNT`),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_VOLTE_SUM`=RPT_TABLE_NAME.`CALL_SETUP_TIME_VOLTE_SUM`+VALUES(`CALL_SETUP_TIME_VOLTE_SUM`),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_VOLTE_CNT`=RPT_TABLE_NAME.`CALL_SETUP_TIME_VOLTE_CNT`+VALUES(`CALL_SETUP_TIME_VOLTE_CNT`),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_UNSP_SUM`=RPT_TABLE_NAME.`CALL_SETUP_TIME_UNSP_SUM`+VALUES(`CALL_SETUP_TIME_UNSP_SUM`),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_UNSP_CNT`=RPT_TABLE_NAME.`CALL_SETUP_TIME_UNSP_CNT`+VALUES(`CALL_SETUP_TIME_UNSP_CNT`)';
		
	DECLARE TILE_GSM_ROAMER_COLUMN_STR VARCHAR(2000) DEFAULT 
		'INIT_CALL_CNT, 
		  END_CALL_CNT,
		  VOICE_CNT,
		  SIGNAL_CNT,
		  SMS_CNT,
		  GPRS_CNT,
		  OTHER_CNT,
		  BLOCK_CNT,
		  DROP_VOICE_CNT,
		  DROP_SIGNAL_CNT,
		  DROP_SMS_CNT,
		  DROP_GPRS_CNT,
		  DROP_OTHER_CNT,
		  NON_BLOCK_VOICE_CNT,
		  NON_BLOCK_SIGNAL_CNT,
		  NON_BLOCK_SMS_CNT,
		  NON_BLOCK_GPRS_CNT,
		  NON_BLOCK_OTHER_CNT,
		  CALL_DUR_SUM,
		  CALL_SETUP_TIME_SUM,
		  CALL_SETUP_TIME_CNT,
		  CALL_SETUP_TIME_VOICE_SUM,
		  CALL_SETUP_TIME_VOICE_CNT,
		  CALL_SETUP_TIME_SIG_SUM,
		  CALL_SETUP_TIME_SIG_CNT,
		  CALL_SETUP_TIME_SMS_SUM,
		  CALL_SETUP_TIME_SMS_CNT,
		  CALL_SETUP_TIME_GPRS_SUM,
		  CALL_SETUP_TIME_GPRS_CNT,	
		  CALL_SETUP_TIME_OTH_SUM,
		  CALL_SETUP_TIME_OTH_CNT';
		
	DECLARE TILE_GSM_ROAMER_COLUMN_IFNULL_STR VARCHAR(2500) DEFAULT 
		'IFNULL(INIT_CALL_CNT,0) AS INIT_CALL_CNT,           
		IFNULL(END_CALL_CNT,0) AS END_CALL_CNT,          
		IFNULL(VOICE_CNT,0) AS VOICE_CNT,           
		IFNULL(SIGNAL_CNT,0) AS SIGNAL_CNT,          
		IFNULL(SMS_CNT,0) AS SMS_CNT,             
		IFNULL(GPRS_CNT,0) AS GPRS_CNT,            
		IFNULL(OTHER_CNT,0) AS OTHER_CNT,           
		IFNULL(BLOCK_CNT,0) AS BLOCK_CNT,           
		IFNULL(DROP_VOICE_CNT,0) AS DROP_VOICE_CNT,      
		IFNULL(DROP_SIGNAL_CNT,0) AS DROP_SIGNAL_CNT,     
		IFNULL(DROP_SMS_CNT,0) AS DROP_SMS_CNT,        
		IFNULL(DROP_GPRS_CNT,0) AS DROP_GPRS_CNT,       
		IFNULL(DROP_OTHER_CNT,0) AS DROP_OTHER_CNT,      
		IFNULL(NON_BLOCK_VOICE_CNT,0) AS NON_BLOCK_VOICE_CNT, 
		IFNULL(NON_BLOCK_SIGNAL_CNT,0) AS NON_BLOCK_SIGNAL_CNT,
		IFNULL(NON_BLOCK_SMS_CNT,0) AS NON_BLOCK_SMS_CNT,   
		IFNULL(NON_BLOCK_GPRS_CNT,0) AS NON_BLOCK_GPRS_CNT,  
		IFNULL(NON_BLOCK_OTHER_CNT,0) AS NON_BLOCK_OTHER_CNT, 
		IFNULL(CALL_DUR_SUM,0) AS CALL_DUR_SUM,
		IFNULL(CALL_SETUP_TIME_SUM,0) AS CALL_SETUP_TIME_SUM,
		IFNULL(CALL_SETUP_TIME_CNT,0) AS CALL_SETUP_TIME_CNT,
		IFNULL(`CALL_SETUP_TIME_VOICE_SUM`,0) AS `CALL_SETUP_TIME_VOICE_SUM`,
		IFNULL(`CALL_SETUP_TIME_VOICE_CNT`,0) AS `CALL_SETUP_TIME_VOICE_CNT`,
		IFNULL(`CALL_SETUP_TIME_SIG_SUM`,0) AS `CALL_SETUP_TIME_SIG_SUM`,
		IFNULL(`CALL_SETUP_TIME_SIG_CNT`,0) AS `CALL_SETUP_TIME_SIG_CNT`,
		IFNULL(`CALL_SETUP_TIME_SMS_SUM`,0) AS `CALL_SETUP_TIME_SMS_SUM`,
		IFNULL(`CALL_SETUP_TIME_SMS_CNT`,0) AS `CALL_SETUP_TIME_SMS_CNT`,
		IFNULL(`CALL_SETUP_TIME_GPRS_SUM`,0) AS `CALL_SETUP_TIME_GPRS_SUM`,
		IFNULL(`CALL_SETUP_TIME_GPRS_CNT`,0) AS `CALL_SETUP_TIME_GPRS_CNT`,
		IFNULL(`CALL_SETUP_TIME_OTH_SUM`,0) AS `CALL_SETUP_TIME_OTH_SUM`,
		IFNULL(`CALL_SETUP_TIME_OTH_CNT`,0) AS `CALL_SETUP_TIME_OTH_CNT`';
		
	DECLARE TILE_GSM_ROAMER_COLUMN_SUM_STR VARCHAR(2500) DEFAULT 
		'SUM(IFNULL(INIT_CALL_CNT,0)) AS INIT_CALL_CNT,           
		SUM(IFNULL(END_CALL_CNT,0)) AS END_CALL_CNT,          
		SUM(IFNULL(VOICE_CNT,0)) AS VOICE_CNT,
		SUM(IFNULL(SIGNAL_CNT,0)) AS SIGNAL_CNT,
		SUM(IFNULL(SMS_CNT,0)) AS SMS_CNT,
		SUM(IFNULL(GPRS_CNT,0)) AS GPRS_CNT,
		SUM(IFNULL(OTHER_CNT,0)) AS OTHER_CNT,
		SUM(IFNULL(BLOCK_CNT,0)) AS BLOCK_CNT,
		SUM(IFNULL(DROP_VOICE_CNT,0)) AS DROP_VOICE_CNT,
		SUM(IFNULL(DROP_SIGNAL_CNT,0)) AS DROP_SIGNAL_CNT,
		SUM(IFNULL(DROP_SMS_CNT,0)) AS DROP_SMS_CNT,
		SUM(IFNULL(DROP_GPRS_CNT,0)) AS DROP_GPRS_CNT,
		SUM(IFNULL(DROP_OTHER_CNT,0)) AS DROP_OTHER_CNT,
		SUM(IFNULL(NON_BLOCK_VOICE_CNT,0)) AS NON_BLOCK_VOICE_CNT,
		SUM(IFNULL(NON_BLOCK_SIGNAL_CNT,0)) AS NON_BLOCK_SIGNAL_CNT,
		SUM(IFNULL(NON_BLOCK_SMS_CNT,0)) AS NON_BLOCK_SMS_CNT,
		SUM(IFNULL(NON_BLOCK_GPRS_CNT,0)) AS NON_BLOCK_GPRS_CNT,
		SUM(IFNULL(NON_BLOCK_OTHER_CNT,0)) AS NON_BLOCK_OTHER_CNT,
		SUM(IFNULL(CALL_DUR_SUM,0)) AS CALL_DUR_SUM,
		SUM(IFNULL(CALL_SETUP_TIME_SUM,0)) AS CALL_SETUP_TIME_SUM,
		SUM(IFNULL(CALL_SETUP_TIME_CNT,0)) AS CALL_SETUP_TIME_CNT,
		SUM(IFNULL(`CALL_SETUP_TIME_VOICE_SUM`,0)) AS `CALL_SETUP_TIME_VOICE_SUM`,
		SUM(IFNULL(`CALL_SETUP_TIME_VOICE_CNT`,0)) AS `CALL_SETUP_TIME_VOICE_CNT`,
		SUM(IFNULL(`CALL_SETUP_TIME_SIG_SUM`,0)) AS `CALL_SETUP_TIME_SIG_SUM`,
		SUM(IFNULL(`CALL_SETUP_TIME_SIG_CNT`,0)) AS `CALL_SETUP_TIME_SIG_CNT`,
		SUM(IFNULL(`CALL_SETUP_TIME_SMS_SUM`,0)) AS `CALL_SETUP_TIME_SMS_SUM`,
		SUM(IFNULL(`CALL_SETUP_TIME_SMS_CNT`,0)) AS `CALL_SETUP_TIME_SMS_CNT`,
		SUM(IFNULL(`CALL_SETUP_TIME_GPRS_SUM`,0)) AS `CALL_SETUP_TIME_GPRS_SUM`,
		SUM(IFNULL(`CALL_SETUP_TIME_GPRS_CNT`,0)) AS `CALL_SETUP_TIME_GPRS_CNT`,
		SUM(IFNULL(`CALL_SETUP_TIME_OTH_SUM`,0)) AS `CALL_SETUP_TIME_OTH_SUM`,
		SUM(IFNULL(`CALL_SETUP_TIME_OTH_CNT`,0)) AS `CALL_SETUP_TIME_OTH_CNT`';
		
	DECLARE TILE_GSM_ROAMER_COLUMN_UPD_STR VARCHAR(10000) DEFAULT
		'RPT_TABLE_NAME.INIT_CALL_CNT=RPT_TABLE_NAME.INIT_CALL_CNT+VALUES(INIT_CALL_CNT),
		RPT_TABLE_NAME.END_CALL_CNT=RPT_TABLE_NAME.END_CALL_CNT+VALUES(END_CALL_CNT),
		RPT_TABLE_NAME.VOICE_CNT=RPT_TABLE_NAME.VOICE_CNT+VALUES(VOICE_CNT),
		RPT_TABLE_NAME.SIGNAL_CNT=RPT_TABLE_NAME.SIGNAL_CNT+VALUES(SIGNAL_CNT),
		RPT_TABLE_NAME.SMS_CNT=RPT_TABLE_NAME.SMS_CNT+VALUES(SMS_CNT),
		RPT_TABLE_NAME.GPRS_CNT=RPT_TABLE_NAME.GPRS_CNT+VALUES(GPRS_CNT),
		RPT_TABLE_NAME.OTHER_CNT=RPT_TABLE_NAME.OTHER_CNT+VALUES(OTHER_CNT),
		RPT_TABLE_NAME.BLOCK_CNT=RPT_TABLE_NAME.BLOCK_CNT+VALUES(BLOCK_CNT),
		RPT_TABLE_NAME.DROP_VOICE_CNT=RPT_TABLE_NAME.DROP_VOICE_CNT+VALUES(DROP_VOICE_CNT),
		RPT_TABLE_NAME.DROP_SIGNAL_CNT=RPT_TABLE_NAME.DROP_SIGNAL_CNT+VALUES(DROP_SIGNAL_CNT),
		RPT_TABLE_NAME.DROP_SMS_CNT=RPT_TABLE_NAME.DROP_SMS_CNT+VALUES(DROP_SMS_CNT),
		RPT_TABLE_NAME.DROP_GPRS_CNT=RPT_TABLE_NAME.DROP_GPRS_CNT+VALUES(DROP_GPRS_CNT),
		RPT_TABLE_NAME.DROP_OTHER_CNT=RPT_TABLE_NAME.DROP_OTHER_CNT+VALUES(DROP_OTHER_CNT),
		RPT_TABLE_NAME.NON_BLOCK_VOICE_CNT=RPT_TABLE_NAME.NON_BLOCK_VOICE_CNT+VALUES(NON_BLOCK_VOICE_CNT),
		RPT_TABLE_NAME.NON_BLOCK_SIGNAL_CNT=RPT_TABLE_NAME.NON_BLOCK_SIGNAL_CNT+VALUES(NON_BLOCK_SIGNAL_CNT),
		RPT_TABLE_NAME.NON_BLOCK_SMS_CNT=RPT_TABLE_NAME.NON_BLOCK_SMS_CNT+VALUES(NON_BLOCK_SMS_CNT),
		RPT_TABLE_NAME.NON_BLOCK_GPRS_CNT=RPT_TABLE_NAME.NON_BLOCK_GPRS_CNT+VALUES(NON_BLOCK_GPRS_CNT),
		RPT_TABLE_NAME.NON_BLOCK_OTHER_CNT=RPT_TABLE_NAME.NON_BLOCK_OTHER_CNT+VALUES(NON_BLOCK_OTHER_CNT),
		RPT_TABLE_NAME.CALL_DUR_SUM=RPT_TABLE_NAME.CALL_DUR_SUM+VALUES(CALL_DUR_SUM),
		RPT_TABLE_NAME.CALL_SETUP_TIME_SUM=RPT_TABLE_NAME.CALL_SETUP_TIME_SUM+VALUES(CALL_SETUP_TIME_SUM),
		RPT_TABLE_NAME.CALL_SETUP_TIME_CNT=RPT_TABLE_NAME.CALL_SETUP_TIME_CNT+VALUES(CALL_SETUP_TIME_CNT),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_VOICE_SUM`=RPT_TABLE_NAME.`CALL_SETUP_TIME_VOICE_SUM`+VALUES(`CALL_SETUP_TIME_VOICE_SUM`),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_VOICE_CNT`=RPT_TABLE_NAME.`CALL_SETUP_TIME_VOICE_CNT`+VALUES(`CALL_SETUP_TIME_VOICE_CNT`),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_SIG_SUM`=RPT_TABLE_NAME.`CALL_SETUP_TIME_SIG_SUM`+VALUES(`CALL_SETUP_TIME_SIG_SUM`),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_SIG_CNT`=RPT_TABLE_NAME.`CALL_SETUP_TIME_SIG_CNT`+VALUES(`CALL_SETUP_TIME_SIG_CNT`),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_SMS_SUM`=RPT_TABLE_NAME.`CALL_SETUP_TIME_SMS_SUM`+VALUES(`CALL_SETUP_TIME_SMS_SUM`),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_SMS_CNT`=RPT_TABLE_NAME.`CALL_SETUP_TIME_SMS_CNT`+VALUES(`CALL_SETUP_TIME_SMS_CNT`),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_GPRS_SUM`=RPT_TABLE_NAME.`CALL_SETUP_TIME_GPRS_SUM`+VALUES(`CALL_SETUP_TIME_GPRS_SUM`),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_GPRS_CNT`=RPT_TABLE_NAME.`CALL_SETUP_TIME_GPRS_CNT`+VALUES(`CALL_SETUP_TIME_GPRS_CNT`),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_OTH_SUM`=RPT_TABLE_NAME.`CALL_SETUP_TIME_OTH_SUM`+VALUES(`CALL_SETUP_TIME_OTH_SUM`),
		RPT_TABLE_NAME.`CALL_SETUP_TIME_OTH_CNT`=RPT_TABLE_NAME.`CALL_SETUP_TIME_OTH_CNT`+VALUES(`CALL_SETUP_TIME_OTH_CNT`)';
	
	SET SHARE_IP ='127.0.0.1';
	SELECT `VARIABLE_VALUE` INTO SHARE_PORT FROM `information_schema`.`GLOBAL_VARIABLES` WHERE VARIABLE_NAME = 'port';
	SELECT `value` INTO SHARE_ACCOUNT FROM `gt_gw_main`.`integration_param` WHERE gt_group='system' AND gt_name='apDbUser';
	SELECT `value` INTO SHARE_PW FROM `gt_gw_main`.`integration_param` WHERE gt_group='system' AND gt_name='apDbPass';
	
										
	IF LOCATE('_romer_',TBL_NAME)>0 THEN 
	BEGIN
		IF TECH_MASK=1 THEN 
			SET @TILE_COLUMN_STR=TILE_GSM_ROAMER_COLUMN_STR;
			SET @TILE_COLUMN_SUM_STR=TILE_GSM_ROAMER_COLUMN_SUM_STR;
			SET @TILE_COLUMN_UPD_STR=TILE_GSM_ROAMER_COLUMN_UPD_STR;
		ELSEIF TECH_MASK=2 THEN 
			SET @TILE_COLUMN_STR=TILE_UMTS_ROAMER_COLUMN_STR;
			SET @TILE_COLUMN_SUM_STR=TILE_UMTS_ROAMER_COLUMN_SUM_STR;
			SET @TILE_COLUMN_UPD_STR=TILE_UMTS_ROAMER_COLUMN_UPD_STR;	
		ELSEIF TECH_MASK=4 THEN 
			SET @TILE_COLUMN_STR=TILE_LTE_ROAMER_COLUMN_STR;
			SET @TILE_COLUMN_SUM_STR=TILE_LTE_ROAMER_COLUMN_SUM_STR;
			SET @TILE_COLUMN_UPD_STR=TILE_LTE_ROAMER_COLUMN_UPD_STR;
		ELSE  
			SET @TILE_COLUMN_STR='';
			SET @TILE_COLUMN_SUM_STR='';
			SET @TILE_COLUMN_UPD_STR='';
		END IF;
		SET @COL_KEY='MCC,MNC,';
	END;
	ELSE
	BEGIN
		IF TECH_MASK=1 THEN 
			SET @TILE_COLUMN_STR=TILE_GSM_COLUMN_STR;
			SET @TILE_COLUMN_SUM_STR=TILE_GSM_COLUMN_SUM_STR;
			SET @TILE_COLUMN_UPD_STR=TILE_GSM_COLUMN_UPD_STR;
		ELSEIF TECH_MASK=2 THEN 
			SET @TILE_COLUMN_STR=TILE_UMTS_COLUMN_STR;
			SET @TILE_COLUMN_SUM_STR=TILE_UMTS_COLUMN_SUM_STR;
			SET @TILE_COLUMN_UPD_STR=TILE_UMTS_COLUMN_UPD_STR;	
		ELSEIF TECH_MASK=4 THEN 
			SET @TILE_COLUMN_STR=TILE_LTE_COLUMN_STR;
			SET @TILE_COLUMN_SUM_STR=TILE_LTE_COLUMN_SUM_STR;
			SET @TILE_COLUMN_UPD_STR=TILE_LTE_COLUMN_UPD_STR;
		ELSE  
			SET @TILE_COLUMN_STR='';
			SET @TILE_COLUMN_SUM_STR='';
			SET @TILE_COLUMN_UPD_STR='';
		END IF;
		SET @COL_KEY='';
	END;
	END IF;
	IF TECH_MASK=1 THEN 
		SET @COL_FRQ='`FREQUENCY`,`BCCH_ARFCN`';
	ELSEIF TECH_MASK=2 THEN 
		SET @COL_FRQ='`FREQUENCY`,`UARFCN`';
	ELSEIF TECH_MASK=4 THEN 
		SET @COL_FRQ='`EARFCN`,`EUTRABAND`';
	END IF;
	
	SET @global_db='gt_global_statistic';
	INSERT INTO gt_gw_main.SP_LOG VALUES(@global_db,'SP_Generate_Global_Statistic_TileResolution_Insert','Start', START_TIME);
	
	SET @ZOOM_LEVEL = gt_covmo_csv_get(TileResolution,3);
	SET REP_NAME=CONCAT('_',@ZOOM_LEVEL,'_');
	SET tile_count = gt_covmo_csv_count(TileResolution,',')-1;
	SET v_j=1;
	WHILE v_j <= tile_count DO
	BEGIN	
		SET @zoomlevel = gt_covmo_csv_get(TileResolution,v_j);
		SET TARGET_TBL_NAME=CONCAT('_',@zoomlevel,'_');
		SET ZOOM_TBL_NAME=REPLACE(TBL_NAME,REP_NAME,TARGET_TBL_NAME);
		SET @CNT=NULL;
		SET @SOURCE_TABLE_NAME=ZOOM_TBL_NAME;
		
		IF TIMETYPE='HR' THEN 
			SET @SqlCmd=CONCAT('DROP TABLE IF EXISTS ',GT_AGGREGATE_DB,'.',@SOURCE_TABLE_NAME,';');
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;
	
			SET @SqlCmd=CONCAT('CREATE TABLE ',GT_AGGREGATE_DB,'.',@SOURCE_TABLE_NAME,' LIKE ',GROUP_DB_NAME,'.',TBL_NAME,';');
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;
	
			SET @SqlCmd=CONCAT('INSERT INTO ',GT_AGGREGATE_DB,'.',@SOURCE_TABLE_NAME,' 
					    (`TILE_ID`,',@COL_KEY,@COL_FRQ
					    ,CASE TIMETYPE 
						WHEN 'HR' THEN ',`DATA_DATE`,`DATA_HOUR`'
						WHEN 'DY' THEN ',`DATA_DATE`'
						ELSE '' END,
					     ',',@TILE_COLUMN_STR,')
					SELECT
					  ',CONCAT('TILE_ID_',@zoomlevel),' AS `TILE_ID`,',@COL_KEY,@COL_FRQ
					     ,CASE TIMETYPE 
						WHEN 'HR' THEN ',`DATA_DATE`,`DATA_HOUR`'
						WHEN 'DY' THEN ',`DATA_DATE`'
						ELSE '' END,
					     ',',@TILE_COLUMN_SUM_STR,' 
					FROM ',GT_AGGREGATE_DB,'.',TMP_TBL_NAME,' 
					GROUP BY ',CONCAT('TILE_ID_',@zoomlevel),',',@COL_KEY,@COL_FRQ
						,CASE TIMETYPE 
							WHEN 'HR' THEN ',`DATA_DATE`,`DATA_HOUR`'
							WHEN 'DY' THEN ',`DATA_DATE`'
							ELSE ''	END,
					' ORDER BY NULL '
					,CASE WHEN ((PENDING_FLAG=1 AND TIMETYPE='HR') OR TIMETYPE IN ('DY','WK','MN')) THEN 
						CONCAT(' ON DUPLICATE KEY UPDATE ',REPLACE(@TILE_COLUMN_UPD_STR,'RPT_TABLE_NAME',CONCAT(GT_AGGREGATE_DB,'.',@SOURCE_TABLE_NAME)))
									ELSE '' END
					,';');
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;
	
			SET @SOURCE_TABLE_NAME=CONCAT(@SOURCE_TABLE_NAME,'#P#h',v_DATA_HOUR,'.');
			CALL gt_global_statistic.`SP_Generate_Global_Statistic_db_mv`(SHARE_IP,SHARE_PORT,SHARE_ACCOUNT,SHARE_PW,GROUP_DB_NAME,GT_AGGREGATE_DB,@SOURCE_TABLE_NAME,'');
			
			SET @SqlCmd=CONCAT('DROP TABLE IF EXISTS ',GT_AGGREGATE_DB,'.',@SOURCE_TABLE_NAME,';');
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;
		ELSE 
			CALL gt_global_statistic.`SP_Generate_Global_Statistic_db_cp`(SHARE_IP,SHARE_PORT,SHARE_ACCOUNT,SHARE_PW,GROUP_DB_NAME,GT_AGGREGATE_DB,@SOURCE_TABLE_NAME,'');
			
			SET @SqlCmd=CONCAT('INSERT INTO ',GT_AGGREGATE_DB,'.',@SOURCE_TABLE_NAME,' 
					    (`TILE_ID`,',@COL_KEY,@COL_FRQ
					    ,CASE TIMETYPE 
						WHEN 'HR' THEN ',`DATA_DATE`,`DATA_HOUR`'
						WHEN 'DY' THEN ',`DATA_DATE`'
						ELSE '' END,
					     ',',@TILE_COLUMN_STR,')
					SELECT
					  ',CONCAT('TILE_ID_',@zoomlevel),' AS `TILE_ID`,',@COL_KEY,@COL_FRQ
					     ,CASE TIMETYPE 
						WHEN 'HR' THEN ',`DATA_DATE`,`DATA_HOUR`'
						WHEN 'DY' THEN ',`DATA_DATE`'
						ELSE '' END,
					     ',',@TILE_COLUMN_SUM_STR,' 
					FROM ',GT_AGGREGATE_DB,'.',TMP_TBL_NAME,' 
					GROUP BY ',CONCAT('TILE_ID_',@zoomlevel),',',@COL_KEY,@COL_FRQ
						,CASE TIMETYPE 
							WHEN 'HR' THEN ',`DATA_DATE`,`DATA_HOUR`'
							WHEN 'DY' THEN ',`DATA_DATE`'
							ELSE ''	END,
					' ORDER BY NULL '
					,CASE WHEN ((PENDING_FLAG=1 AND TIMETYPE='HR') OR TIMETYPE IN ('DY','WK','MN')) THEN 
						CONCAT(' ON DUPLICATE KEY UPDATE ',REPLACE(@TILE_COLUMN_UPD_STR,'RPT_TABLE_NAME',CONCAT(GT_AGGREGATE_DB,'.',@SOURCE_TABLE_NAME)))
									ELSE '' END
					,';');
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;
			
			CALL gt_global_statistic.`SP_Generate_Global_Statistic_db_mv`(SHARE_IP,SHARE_PORT,SHARE_ACCOUNT,SHARE_PW,GROUP_DB_NAME,GT_AGGREGATE_DB,@SOURCE_TABLE_NAME,'');
		END IF;
		SET v_j=v_j+1;
		
	END;
	END WHILE;
	INSERT INTO gt_gw_main.SP_LOG VALUES(@global_db,'SP_Generate_Global_Statistic_TileResolution_Insert',CONCAT('Done: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());
	
END$$
DELIMITER ;
