DELIMITER $$
USE `gt_global_statistic`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Generate_Global_Statistic_cell_agg_lte`(IN DATA_DATE DATE,IN DATA_HOUR TINYINT(2),IN PU_ID MEDIUMINT(9),IN TECH_MASK TINYINT(2), IN GT_DB VARCHAR(100))
BEGIN
	DECLARE SP_Process VARCHAR(100) DEFAULT NULL;
	DECLARE WORKER_ID VARCHAR(10) DEFAULT CONNECTION_ID();
	DECLARE Spider_SP_ERROR CONDITION FOR SQLSTATE '99998';
	DECLARE KPI_ERROR CONDITION FOR SQLSTATE '99999' ;
	DECLARE STR_START_END_LTE MEDIUMTEXT DEFAULT '';
	DECLARE STR_START_SUM_LTE MEDIUMTEXT DEFAULT '';
	DECLARE STR_END_SUM_LTE MEDIUMTEXT DEFAULT '';
	DECLARE STR_SEL_START_LTE MEDIUMTEXT DEFAULT '';
	DECLARE STR_SEL_END_LTE MEDIUMTEXT DEFAULT '';
	
	SET @SqlCmd=CONCAT('SELECT `att_value` INTO @ZOOM_LEVEL FROM gt_covmo.`sys_config` WHERE `group_name`=''system'' AND att_name = ''MapResolution'';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
		
	SET @FLAG_IMSI_HR=0;
	SET @FLAG_IMSI_DY=0;
	SET @FLAG_MAKE_HR=0;
	SET @FLAG_MAKE_DY=0;
	
	SET STR_START_END_LTE=CONCAT('POS_FIRST_S_CELL,
					POS_FIRST_S_ENODEB,
					POS_FIRST_S_EARFCN,
					POS_FIRST_S_EUTRABAND,
					DATA_DATE,
					DATA_HOUR,
					',PU_ID,',
					CALL_TYPE,					
					CALL_STATUS,
					POS_FIRST_S_RSRP,
					POS_FIRST_S_RSRQ,
					CALL_SETUP_TIME,
					POS_LAST_S_CELL,
					POS_LAST_S_ENODEB,
					POS_LAST_S_EARFCN,
					POS_LAST_S_EUTRABAND,
					X2_HO_INTER_ATTEMPT,
					S1_HO_INTER_ATTEMPT,
					X2_HO_INTER_FAILURE,
					S1_HO_INTER_FAILURE,
					X2_HO_INTRA_ATTEMPT,
					S1_HO_INTRA_ATTEMPT,
					X2_HO_INTRA_FAILURE,
					S1_HO_INTRA_FAILURE,
					IRAT_TO_UMTS_ATTEMPT,
					IRAT_TO_UMTS_FAILURE,
					IRAT_TO_GERAN_ATTEMPT,
					IRAT_TO_GERAN_FAILURE,
					SRVCC_ATTEMPT,
					SRVCC_FAILURE');
	
	SET STR_START_SUM_LTE=CONCAT('POS_FIRST_S_CELL AS CELL_ID,
					POS_FIRST_S_ENODEB AS ENODEB_ID,
					POS_FIRST_S_EARFCN AS EARFCN,
					POS_FIRST_S_EUTRABAND AS EUTRABAND ,
					DATA_DATE,
					DATA_HOUR,',PU_ID,' AS `PU_ID`,
					COUNT(*) AS `INIT_CALL_CNT`,
					SUM(IF(CALL_TYPE=22,1,0)) AS `SIGNAL_CNT`,
					SUM(IF(CALL_TYPE=21,1,0)) AS `DATA_CNT`,
					SUM(IF(CALL_TYPE=23,1,0)) AS `VOLTE_CNT`,
					SUM(IF(CALL_TYPE=29,1,0)) AS `UNSPECIFIED_CNT`,
					SUM(IF(CALL_TYPE=24,1,0)) AS `SMS_CNT`,
					SUM(IF(CALL_STATUS=3 AND CALL_TYPE=21,1,0)) AS `BLOCK_DATA_CNT`,
					SUM(IF(CALL_STATUS=3 AND CALL_TYPE=22,1,0)) AS `BLOCK_SIGNAL_CNT`,
					SUM(IF(CALL_STATUS=3 AND CALL_TYPE=24,1,0)) AS `BLOCK_SMS_CNT`,
					SUM(IF(CALL_STATUS=3 AND CALL_TYPE=23,1,0)) AS `BLOCK_VOLTE_CNT`,
					SUM(IF(CALL_STATUS=3 AND CALL_TYPE=29,1,0)) AS `BLOCK_UNSPECIFIED_CNT`,
					SUM(POS_FIRST_S_RSRP) AS `RSRP_SUM`,
					COUNT(POS_FIRST_S_RSRP) AS `RSRP_CNT`,
					SUM(POS_FIRST_S_RSRQ) AS `RSRQ_SUM`,
					COUNT(POS_FIRST_S_RSRQ) AS `RSRQ_CNT`,
					SUM(CALL_SETUP_TIME) AS `CALL_SETUP_TIME_SUM`,
					SUM(IF(CALL_SETUP_TIME>=0,1,0)) AS `CALL_SETUP_TIME_CNT`,
	
					IFNULL(SUM(IF(CALL_TYPE =22,CALL_SETUP_TIME,0)),0) AS CALL_SETUP_TIME_SIG_SUM,
					IFNULL(SUM(IF(CALL_SETUP_TIME>=0 AND CALL_TYPE =22,1,0)),0) AS CALL_SETUP_TIME_SIG_CNT,
					IFNULL(SUM(IF(CALL_TYPE =21,CALL_SETUP_TIME,0)),0) AS CALL_SETUP_TIME_DATA_SUM,
					IFNULL(SUM(IF(CALL_SETUP_TIME>=0 AND CALL_TYPE =21,1,0)),0) AS CALL_SETUP_TIME_DATA_CNT,
					IFNULL(SUM(IF(CALL_TYPE =24,CALL_SETUP_TIME,0)),0) AS CALL_SETUP_TIME_SMS_SUM,
					IFNULL(SUM(IF(CALL_SETUP_TIME>=0 AND CALL_TYPE =24,1,0)),0) AS CALL_SETUP_TIME_SMS_CNT,
					IFNULL(SUM(IF(CALL_TYPE =23,CALL_SETUP_TIME,0)),0) AS CALL_SETUP_TIME_VOLTE_SUM,
					IFNULL(SUM(IF(CALL_SETUP_TIME>=0 AND CALL_TYPE =23,1,0)),0) AS CALL_SETUP_TIME_VOLTE_CNT,
					IFNULL(SUM(IF(CALL_TYPE =29,CALL_SETUP_TIME,0)),0) AS CALL_SETUP_TIME_UNSP_SUM,
					IFNULL(SUM(IF(CALL_SETUP_TIME>=0 AND CALL_TYPE =29,1,0)),0) AS CALL_SETUP_TIME_UNSP_CNT,
	
					SUM(IF(CALL_STATUS=6 AND CALL_TYPE=21,1,0)) AS `SF_DATA_CNT`,
					SUM(IF(CALL_STATUS=6 AND CALL_TYPE=22,1,0)) AS `SF_SIGNAL_CNT`,
					SUM(IF(CALL_STATUS=6 AND CALL_TYPE=24,1,0)) AS `SF_SMS_CNT`,
					SUM(IF(CALL_STATUS=6 AND CALL_TYPE=23,1,0)) AS `SF_VOLTE_CNT`,
					SUM(IF(CALL_STATUS=6 AND CALL_TYPE=29,1,0)) AS `SF_UNSPECIFIED_CNT`,
					0 AS `LATENCY_SUM`,
					0 AS `LATENCY_CNT`
-- 					SUM(LATENCY) AS `LATENCY_SUM`,
-- 					SUM(IF(LATENCY>=0,1,0)) AS `LATENCY_CNT`');
	SET STR_END_SUM_LTE=CONCAT('POS_LAST_S_CELL AS CELL_ID,
					POS_LAST_S_ENODEB AS ENODEB_ID,
					POS_LAST_S_EARFCN AS EARFCN,
					POS_LAST_S_EUTRABAND AS EUTRABAND ,
					DATA_DATE,
					DATA_HOUR,',PU_ID,' AS `PU_ID`,
					COUNT(*) AS `END_CALL_CNT`,
					SUM(IF(CALL_TYPE=22,1,0)) AS `END_SIGNAL_CNT`,
					SUM(IF(CALL_TYPE=21,1,0)) AS `END_DATA_CNT`,
					SUM(IF(CALL_TYPE=23,1,0)) AS `END_VOLTE_CNT`,
					SUM(IF(CALL_TYPE=24,1,0)) AS `END_SMS_CNT`,
					SUM(IF(CALL_TYPE=29,1,0)) AS `END_UNSPECIFIED_CNT`,					
					SUM(IF(CALL_STATUS=2 AND CALL_TYPE=21,1,0)) AS `DROP_DATA_CNT`,
					SUM(IF(CALL_STATUS=2 AND CALL_TYPE=22,1,0)) AS `DROP_SIGNAL_CNT`,
					SUM(IF(CALL_STATUS=2 AND CALL_TYPE=24,1,0)) AS `DROP_SMS_CNT`,
					SUM(IF(CALL_STATUS=2 AND CALL_TYPE=23,1,0)) AS `DROP_VOLTE_CNT`,
					SUM(IF(CALL_STATUS=2 AND CALL_TYPE=29,1,0)) AS `DROP_UNSPECIFIED_CNT`,
					SUM(IF(CALL_STATUS IN (1,2,4,5) AND CALL_TYPE=22,1,0)) AS `NON_BLOCK_SIGNAL_CNT`,
					SUM(IF(CALL_STATUS IN (1,2,4,5) AND CALL_TYPE=21,1,0)) AS `NON_BLOCK_DATA_CNT`,
					SUM(IF(CALL_STATUS IN (1,2,4,5) AND CALL_TYPE=24,1,0)) AS `NON_BLOCK_SMS_CNT`,
					SUM(IF(CALL_STATUS IN (1,2,4,5) AND CALL_TYPE=23,1,0)) AS `NON_BLOCK_VOLTE_CNT`,
					SUM(IF(CALL_STATUS IN (1,2,4,5) AND CALL_TYPE=29,1,0)) AS `NON_BLOCK_UNSPECIFIED_CNT`,
					SUM(IFNULL(`X2_HO_INTER_ATTEMPT`,0)+IFNULL(`S1_HO_INTER_ATTEMPT`,0)) AS `INTER_FREQ_ATTEMPT_CNT`,
					SUM(IFNULL(`X2_HO_INTER_FAILURE`,0)+IFNULL(`S1_HO_INTER_FAILURE`,0)) AS `INTER_FREQ_FAILURE_CNT`,
					SUM(IFNULL(`X2_HO_INTRA_ATTEMPT`,0)+IFNULL(`S1_HO_INTRA_ATTEMPT`,0)) AS `INTRA_FREQ_ATTEMPT_CNT`,
					SUM(IFNULL(`X2_HO_INTRA_FAILURE`,0)+IFNULL(`S1_HO_INTRA_FAILURE`,0)) AS `INTRA_FREQ_FAILURE_CNT`,
					SUM(IRAT_TO_UMTS_ATTEMPT) AS `4G_3G_ATTEMPT_CNT`,
					SUM(IRAT_TO_UMTS_FAILURE) AS `4G_3G_FAILURE_CNT`,
					SUM(IRAT_TO_GERAN_ATTEMPT) AS `4G_2G_ATTEMPT_CNT`,
					SUM(IRAT_TO_GERAN_FAILURE) AS `4G_2G_FAILURE_CNT`,
					SUM(SRVCC_ATTEMPT) AS `SRVCC_ATTEMPT_CNT`,
					SUM(SRVCC_FAILURE) AS `SRVCC_FAILURE_CNT`');
	
	INSERT INTO gt_gw_main.sp_log VALUES('gt_gw_main','SP_Generate_Global_Statistic_cell_agg_lte',CONCAT(GT_DB,' CREATE TEMPORARY TABLE tmp_materialization_',WORKER_ID), NOW());	
	
	SET SESSION group_concat_max_len=102400; 
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_materialization_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,'.tmp_materialization_',WORKER_ID,' (
				`DATA_DATE` datetime NOT NULL,
				`DATA_HOUR` tinyint(4) NOT NULL,
				`CELL_ID` tinyint(4) unsigned,
				`ENODEB_ID` mediumint(9) DEFAULT NULL,
				`PU_ID` mediumint(9) NOT NULL,
				`EARFCN`  MEDIUMINT(9) NOT NULL,
				`EUTRABAND` SMALLINT(6) NOT NULL,
				`INIT_CALL_CNT` INT(11) DEFAULT NULL,
				`END_CALL_CNT` INT(11) DEFAULT NULL,
				`SIGNAL_CNT` INT(11) DEFAULT NULL,
				`DATA_CNT` INT(11) DEFAULT NULL,
				`SMS_CNT` INT(11) DEFAULT NULL,
				`VOLTE_CNT` INT(11) DEFAULT NULL,
				`UNSPECIFIED_CNT` INT(11) DEFAULT NULL,
				`END_SIGNAL_CNT` INT(11) DEFAULT NULL,
				`END_DATA_CNT` INT(11) DEFAULT NULL,
				`END_SMS_CNT` INT(11) DEFAULT NULL,
				`END_VOLTE_CNT` INT(11) DEFAULT NULL,
				`END_UNSPECIFIED_CNT` INT(11) DEFAULT NULL,
				`DROP_SIGNAL_CNT` INT(11) DEFAULT NULL,
				`DROP_DATA_CNT` INT(11) DEFAULT NULL,
				`DROP_SMS_CNT` INT(11) DEFAULT NULL,
				`DROP_VOLTE_CNT` INT(11) DEFAULT NULL,
				`DROP_UNSPECIFIED_CNT` INT(11) DEFAULT NULL,
				`BLOCK_SIGNAL_CNT` INT(11) DEFAULT NULL,
				`BLOCK_DATA_CNT` INT(11) DEFAULT NULL,
				`BLOCK_SMS_CNT` INT(11) DEFAULT NULL,
				`BLOCK_VOLTE_CNT` INT(11) DEFAULT NULL,
				`BLOCK_UNSPECIFIED_CNT` INT(11) DEFAULT NULL,
				`CSFB_SIGNAL_CNT` INT(11) DEFAULT NULL,
				`CSFB_DATA_CNT` INT(11) DEFAULT NULL,
				`CSFB_SMS_CNT` INT(11) DEFAULT NULL,
				`CSFB_VOLTE_CNT` INT(11) DEFAULT NULL,
				`CSFB_UNSPECIFIED_CNT` INT(11) DEFAULT NULL,
				`NON_BLOCK_SIGNAL_CNT` INT(11) DEFAULT NULL,
				`NON_BLOCK_DATA_CNT` INT(11) DEFAULT NULL,
				`NON_BLOCK_SMS_CNT` INT(11) DEFAULT NULL,
				`NON_BLOCK_VOLTE_CNT` INT(11) DEFAULT NULL,
				`NON_BLOCK_UNSPECIFIED_CNT` INT(11) DEFAULT NULL,
				`RSRP_SUM` DOUBLE DEFAULT NULL,
				`RSRP_CNT` INT(11) DEFAULT NULL,
				`RSRQ_SUM` DOUBLE DEFAULT NULL,
				`RSRQ_CNT` INT(11) DEFAULT NULL,
				`UL_VOLUME_SUM` DOUBLE DEFAULT NULL,
				`DL_VOLUME_SUM` DOUBLE DEFAULT NULL,
				`UL_THROUPUT_MAX` DOUBLE DEFAULT NULL,
				`DL_THROUPUT_MAX` DOUBLE DEFAULT NULL,
				`UL_THROUPUT_SUM` DOUBLE DEFAULT NULL,
				`UL_THROUPUT_CNT` INT(11) DEFAULT NULL,
				`DL_THROUPUT_SUM` DOUBLE DEFAULT NULL,
				`DL_THROUPUT_CNT` INT(11) DEFAULT NULL,
				`INTER_FREQ_ATTEMPT_CNT` INT(11) DEFAULT NULL,
				`INTER_FREQ_FAILURE_CNT` INT(11) DEFAULT NULL,
				`INTRA_FREQ_ATTEMPT_CNT` INT(11) DEFAULT NULL,
				`INTRA_FREQ_FAILURE_CNT` INT(11) DEFAULT NULL,
				`4G_3G_ATTEMPT_CNT` INT(11) DEFAULT NULL,
				`4G_3G_FAILURE_CNT` INT(11) DEFAULT NULL,
				`4G_2G_ATTEMPT_CNT` INT(11) DEFAULT NULL,
				`4G_2G_FAILURE_CNT` INT(11) DEFAULT NULL,
				`MR_4G_RSRP_SERVING_SUM` DOUBLE DEFAULT NULL,
				`MR_4G_RSRP_SERVING_CNT` INT(11) DEFAULT NULL,
				`MR_4G_RSRQ_SERVING_SUM` DOUBLE DEFAULT NULL,
				`MR_4G_RSRQ_SERVING_CNT` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_SUM` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_CNT` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_SIG_SUM` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_SIG_CNT` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_DATA_SUM` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_DATA_CNT` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_SMS_SUM` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_SMS_CNT` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_VOLTE_SUM` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_VOLTE_CNT` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_UNSP_SUM` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_UNSP_CNT` INT(11) DEFAULT NULL,
				`SF_SIGNAL_CNT` INT(11) DEFAULT NULL,
				`SF_DATA_CNT` INT(11) DEFAULT NULL,
				`SF_SMS_CNT` INT(11) DEFAULT NULL,
				`SF_VOLTE_CNT` INT(11) DEFAULT NULL,
				`SF_UNSPECIFIED_CNT` INT(11) DEFAULT NULL,
				`SRVCC_ATTEMPT_CNT` INT(11) DEFAULT NULL,
				`SRVCC_FAILURE_CNT` INT(11) DEFAULT NULL,
				`S1_HO_ATTEMPT` INT(11) DEFAULT NULL,
				`S1_HO_FAILURE` INT(11) DEFAULT NULL,
				`X2_HO_ATTEMPT` INT(11) DEFAULT NULL,
				`X2_HO_FAILURE` INT(11) DEFAULT NULL,
				`LATENCY_SUM` DOUBLE DEFAULT NULL,
				`LATENCY_CNT` INT(11) DEFAULT NULL
				,PRIMARY KEY (`CELL_ID`,ENODEB_ID,`EARFCN`,`EUTRABAND`,`DATA_DATE`,`DATA_HOUR`)
				) ENGINE=MYISAM DEFAULT CHARSET=latin1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES('gt_gw_main','SP_Generate_Global_Statistic_cell_agg_lte',CONCAT(GT_DB,' INSERT INTO tbl_',GT_DB,'_',WORKER_ID), NOW());	
	 	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_cell_lte_start_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,'.tmp_cell_lte_start_',WORKER_ID,' (
				`CELL_ID` tinyint(4) unsigned NOT NULL,
				`ENODEB_ID` mediumint(9) NOT NULL,
				`PU_ID` mediumint(9) DEFAULT NULL,
				`EARFCN` MEDIUMINT(9) DEFAULT NULL,
				`EUTRABAND` SMALLINT(6) DEFAULT NULL,
				`DATA_DATE` DATETIME NOT NULL,
				`DATA_HOUR` TINYINT(4) NOT NULL,
				`INIT_CALL_CNT`  INT(11) DEFAULT NULL,
				`SIGNAL_CNT` INT(11) DEFAULT NULL,
				`DATA_CNT` INT(11) DEFAULT NULL,
				`SMS_CNT` INT(11) DEFAULT NULL,
				`VOLTE_CNT` INT(11) DEFAULT NULL,
				`UNSPECIFIED_CNT` INT(11) DEFAULT NULL,
				`BLOCK_SIGNAL_CNT` INT(11) DEFAULT NULL,
				`BLOCK_DATA_CNT` INT(11) DEFAULT NULL,
				`BLOCK_SMS_CNT` INT(11) DEFAULT NULL,
				`BLOCK_VOLTE_CNT` INT(11) DEFAULT NULL,
				`BLOCK_UNSPECIFIED_CNT` INT(11) DEFAULT NULL,
				`RSRP_SUM` DOUBLE DEFAULT NULL,
				`RSRP_CNT` INT(11) DEFAULT NULL,
				`RSRQ_SUM` DOUBLE DEFAULT NULL,
				`RSRQ_CNT` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_SUM` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_CNT` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_SIG_SUM` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_SIG_CNT` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_DATA_SUM` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_DATA_CNT` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_SMS_SUM` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_SMS_CNT` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_VOLTE_SUM` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_VOLTE_CNT` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_UNSP_SUM` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_UNSP_CNT` INT(11) DEFAULT NULL,
				`SF_SIGNAL_CNT` INT(11) DEFAULT NULL,
				`SF_DATA_CNT` INT(11) DEFAULT NULL,
				`SF_SMS_CNT` INT(11) DEFAULT NULL,
				`SF_VOLTE_CNT` INT(11) DEFAULT NULL,
				`SF_UNSPECIFIED_CNT` INT(11) DEFAULT NULL,
				`SRVCC_ATTEMPT_CNT` INT(11) DEFAULT NULL,
				`SRVCC_FAILURE_CNT` INT(11) DEFAULT NULL,
				`LATENCY_SUM` DOUBLE DEFAULT NULL,
				`LATENCY_CNT` INT(11) DEFAULT NULL
				,PRIMARY KEY (`CELL_ID`,`ENODEB_ID`,`DATA_DATE`,`DATA_HOUR`)
				) ENGINE=MYISAM DEFAULT CHARSET=latin1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_cell_lte_end_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,'.tmp_cell_lte_end_',WORKER_ID,' (
				`CELL_ID` tinyint(4) unsigned NOT NULL,
				`ENODEB_ID` mediumint(9) NOT NULL,
				`PU_ID` mediumint(9) DEFAULT NULL,
				`EARFCN` MEDIUMINT(9) DEFAULT NULL,
				`EUTRABAND` SMALLINT(6) DEFAULT NULL,
				`DATA_DATE` DATETIME NOT NULL,
				`DATA_HOUR` TINYINT(4) NOT NULL,
				`END_CALL_CNT` INT(11) DEFAULT NULL,
				`END_SIGNAL_CNT` INT(11) DEFAULT NULL,
				`END_DATA_CNT` INT(11) DEFAULT NULL,
				`END_SMS_CNT` INT(11) DEFAULT NULL,
				`END_VOLTE_CNT` INT(11) DEFAULT NULL,
				`END_UNSPECIFIED_CNT` INT(11) DEFAULT NULL,
				`DROP_SIGNAL_CNT` INT(11) DEFAULT NULL,
				`DROP_DATA_CNT` INT(11) DEFAULT NULL,
				`DROP_SMS_CNT` INT(11) DEFAULT NULL,
				`DROP_VOLTE_CNT` INT(11) DEFAULT NULL,
				`DROP_UNSPECIFIED_CNT` INT(11) DEFAULT NULL,
				`NON_BLOCK_SIGNAL_CNT` INT(11) DEFAULT NULL,
				`NON_BLOCK_DATA_CNT` INT(11) DEFAULT NULL,
				`NON_BLOCK_SMS_CNT` INT(11) DEFAULT NULL,
				`NON_BLOCK_VOLTE_CNT` INT(11) DEFAULT NULL,
				`NON_BLOCK_UNSPECIFIED_CNT` INT(11) DEFAULT NULL,
				`INTER_FREQ_ATTEMPT_CNT` INT(11) DEFAULT NULL,
				`INTER_FREQ_FAILURE_CNT` INT(11) DEFAULT NULL,
				`INTRA_FREQ_ATTEMPT_CNT` INT(11) DEFAULT NULL,
				`INTRA_FREQ_FAILURE_CNT` INT(11) DEFAULT NULL,
				`4G_3G_ATTEMPT_CNT` INT(11) DEFAULT NULL,
				`4G_3G_FAILURE_CNT` INT(11) DEFAULT NULL,
				`4G_2G_ATTEMPT_CNT` INT(11) DEFAULT NULL,
				`4G_2G_FAILURE_CNT` INT(11) DEFAULT NULL,
				`SRVCC_ATTEMPT_CNT` INT(11) DEFAULT NULL,
				`SRVCC_FAILURE_CNT` INT(11) DEFAULT NULL
				,PRIMARY KEY (`CELL_ID`,`ENODEB_ID`,`EARFCN`,`EUTRABAND`)
				) ENGINE=MYISAM DEFAULT CHARSET=latin1;');
 	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @v_i=DATA_HOUR;
	SET @v_i_Max=DATA_HOUR+1;
	SET @v_j=0;
				
	WHILE @v_i < @v_i_Max DO
	BEGIN	
		WHILE @v_j<60  DO
		BEGIN		
			IF (@v_j=45) THEN 
				SET @UNION=' '; 
			ELSE
				SET @UNION=' UNION ALL '; 
			END IF;	
			SET STR_SEL_START_LTE=CONCAT(STR_SEL_START_LTE,'SELECT ',STR_START_END_LTE,' FROM ',GT_DB,'.table_call_lte',CONCAT('_',LPAD(@v_i,2,'0'),LPAD(@v_j,2,'0')),' WHERE DATA_HOUR=', @v_i,' AND POS_FIRST_S_CELL IS NOT NULL',@UNION); 
			SET STR_SEL_END_LTE=CONCAT(STR_SEL_END_LTE,'SELECT ',STR_START_END_LTE,' FROM ',GT_DB,'.table_call_lte',CONCAT('_',LPAD(@v_i,2,'0'),LPAD(@v_j,2,'0')),'  WHERE DATA_HOUR=', @v_i,' AND POS_LAST_S_CELL IS NOT NULL',@UNION); 
			SET @v_j=@v_j+15;
		END;
		END WHILE;
			
		SET @v_j=0;
		SET @v_i=@v_i+1;
	END;
	END WHILE;	
	
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.tmp_cell_lte_start_',WORKER_ID,' 
				(`CELL_ID`,`ENODEB_ID`,EARFCN,EUTRABAND,DATA_DATE,DATA_HOUR,`PU_ID`,`INIT_CALL_CNT`,
					`SIGNAL_CNT`,`DATA_CNT`,`VOLTE_CNT`,`UNSPECIFIED_CNT`,`SMS_CNT`,
					`BLOCK_DATA_CNT`,`BLOCK_SIGNAL_CNT`,`BLOCK_SMS_CNT`,`BLOCK_VOLTE_CNT`,`BLOCK_UNSPECIFIED_CNT`,
					`RSRP_SUM`,`RSRP_CNT`,`RSRQ_SUM`,`RSRQ_CNT`,
					`CALL_SETUP_TIME_SUM`,`CALL_SETUP_TIME_CNT`,
					`CALL_SETUP_TIME_SIG_SUM`,`CALL_SETUP_TIME_SIG_CNT`,
					`CALL_SETUP_TIME_DATA_SUM`,`CALL_SETUP_TIME_DATA_CNT`,
					`CALL_SETUP_TIME_SMS_SUM`,`CALL_SETUP_TIME_SMS_CNT`,
					`CALL_SETUP_TIME_VOLTE_SUM`,`CALL_SETUP_TIME_VOLTE_CNT`,
					`CALL_SETUP_TIME_UNSP_SUM`,`CALL_SETUP_TIME_UNSP_CNT`,
					`SF_DATA_CNT`,`SF_SIGNAL_CNT`,`SF_SMS_CNT`,`SF_VOLTE_CNT`,`SF_UNSPECIFIED_CNT`,
					`LATENCY_SUM`,`LATENCY_CNT`
				)
				SELECT ',STR_START_SUM_LTE,' 
				FROM (',STR_SEL_START_LTE,') AA
				GROUP BY POS_FIRST_S_CELL,POS_FIRST_S_ENODEB
				ORDER BY NULL;
				');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.tmp_cell_lte_end_',WORKER_ID,' 
				(`CELL_ID`,`ENODEB_ID`,EARFCN,EUTRABAND,DATA_DATE,DATA_HOUR,`PU_ID`,`END_CALL_CNT`,				
				`END_SIGNAL_CNT`,`END_DATA_CNT`,`END_SMS_CNT`,`END_VOLTE_CNT`,`END_UNSPECIFIED_CNT`,
				`DROP_DATA_CNT`,`DROP_SIGNAL_CNT`,`DROP_SMS_CNT`,`DROP_VOLTE_CNT`,`DROP_UNSPECIFIED_CNT`,
				`NON_BLOCK_SIGNAL_CNT`,`NON_BLOCK_DATA_CNT`,`NON_BLOCK_SMS_CNT`,`NON_BLOCK_VOLTE_CNT`,`NON_BLOCK_UNSPECIFIED_CNT`,
				`INTER_FREQ_ATTEMPT_CNT`,`INTER_FREQ_FAILURE_CNT`,`INTRA_FREQ_ATTEMPT_CNT`,`INTRA_FREQ_FAILURE_CNT`,
				`4G_3G_ATTEMPT_CNT`,`4G_3G_FAILURE_CNT`,`4G_2G_ATTEMPT_CNT`,`4G_2G_FAILURE_CNT`,
				`SRVCC_ATTEMPT_CNT`,`SRVCC_FAILURE_CNT`
				)
				SELECT ',STR_END_SUM_LTE,' 
				FROM (',STR_SEL_END_LTE,') AA
				GROUP BY POS_LAST_S_CELL,POS_LAST_S_ENODEB,POS_LAST_S_EARFCN,POS_LAST_S_EUTRABAND
				ORDER BY NULL;
				');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.`tmp_materialization_',WORKER_ID,'` 
				(CELL_ID,ENODEB_ID,EARFCN,EUTRABAND ,DATA_DATE,DATA_HOUR,`PU_ID`,
				  `CSFB_SIGNAL_CNT`,`CSFB_DATA_CNT`,`CSFB_SMS_CNT`,`CSFB_VOLTE_CNT`,`CSFB_UNSPECIFIED_CNT`,
				  `UL_VOLUME_SUM`,`DL_VOLUME_SUM`,`UL_THROUPUT_MAX`,`DL_THROUPUT_MAX`,
				  `UL_THROUPUT_SUM`,`UL_THROUPUT_CNT`,`DL_THROUPUT_SUM`,`DL_THROUPUT_CNT`,
				  `MR_4G_RSRP_SERVING_SUM`,`MR_4G_RSRP_SERVING_CNT`,`MR_4G_RSRQ_SERVING_SUM`,`MR_4G_RSRQ_SERVING_CNT`,
				  `S1_HO_ATTEMPT`,`S1_HO_FAILURE`,`X2_HO_ATTEMPT`,`X2_HO_FAILURE`)
								
				SELECT 
					CELL_ID,ENODEB_ID,EARFCN,EUTRABAND ,DATA_DATE,DATA_HOUR,',PU_ID,' AS `PU_ID`,
					SUM(IF(CALL_STATUS=5 AND CALL_TYPE=22,1,0)) AS `CSFB_SIGNAL_CNT`,
					SUM(IF(CALL_STATUS=5 AND CALL_TYPE=21,1,0)) AS `CSFB_DATA_CNT`,
					SUM(IF(CALL_STATUS=5 AND CALL_TYPE=24,1,0)) AS `CSFB_SMS_CNT`,
					SUM(IF(CALL_STATUS=5 AND CALL_TYPE=23,1,0)) AS `CSFB_VOLTE_CNT`,
					SUM(IF(CALL_STATUS=5 AND CALL_TYPE=29,1,0)) AS `CSFB_UNSPECIFIED_CNT`,
					SUM(UL_VOLUME_SUM) AS `UL_VOLUME_SUM`,
					SUM(DL_VOLUME_SUM) AS `DL_VOLUME_SUM`,
					MAX((UL_THROUPUT_SUM)/(UL_THROUPUT_CNT)) AS `UL_THROUPUT_MAX`,
					MAX((DL_THROUPUT_SUM)/(DL_THROUPUT_CNT)) AS `DL_THROUPUT_MAX`,
					SUM(UL_THROUPUT_SUM) AS `UL_THROUPUT_SUM`,
					SUM(UL_THROUPUT_CNT) AS `UL_THROUPUT_CNT`,
					SUM(DL_THROUPUT_SUM) AS `DL_THROUPUT_SUM`,
					SUM(DL_THROUPUT_CNT) AS `DL_THROUPUT_CNT`,
					SUM(MR_4G_RSRP_SERVING_SUM) AS `MR_4G_RSRP_SERVING_SUM`,
					SUM(MR_4G_RSRP_SERVING_CNT) AS `MR_4G_RSRP_SERVING_CNT`,
					SUM(MR_4G_RSRQ_SERVING_SUM) AS `MR_4G_RSRQ_SERVING_SUM`,
					SUM(MR_4G_RSRQ_SERVING_CNT) AS `MR_4G_RSRQ_SERVING_CNT`, 
					SUM(HO_4G_S1_INTRA_ATT_CNT+HO_4G_S1_INTER_ATT_CNT) AS `S1_HO_ATTEMPT`,
					SUM(HO_4G_S1_INTRA_FAIL_CNT+HO_4G_S1_INTER_FAIL_CNT) AS `S1_HO_FAILURE`,
					SUM(HO_4G_X2_INTRA_ATT_CNT+HO_4G_X2_INTER_ATT_CNT) AS `X2_HO_ATTEMPT`,
					SUM(HO_4G_X2_INTRA_FAIL_CNT+HO_4G_X2_INTER_FAIL_CNT) AS `X2_HO_FAILURE`
				FROM ',GT_DB,'.rpt_cell_position
				WHERE DATA_HOUR =',DATA_HOUR,' 
				GROUP BY CELL_ID,ENODEB_ID,EARFCN,EUTRABAND
				ORDER BY NULL;
				');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('UPDATE ',GT_DB,'.`tmp_materialization_',WORKER_ID,'` a,',GT_DB,'.`tmp_cell_lte_start_',WORKER_ID,'` B
				SET 
				A.INIT_CALL_CNT=B.INIT_CALL_CNT
				,A.SIGNAL_CNT=B.SIGNAL_CNT
				,A.DATA_CNT=B.DATA_CNT
				,A.VOLTE_CNT=B.VOLTE_CNT
				,A.UNSPECIFIED_CNT=B.UNSPECIFIED_CNT
				,A.SMS_CNT=B.SMS_CNT
				,A.BLOCK_DATA_CNT=B.BLOCK_DATA_CNT
				,A.BLOCK_SIGNAL_CNT=B.BLOCK_SIGNAL_CNT
				,A.BLOCK_SMS_CNT=B.BLOCK_SMS_CNT
				,A.BLOCK_VOLTE_CNT=B.BLOCK_VOLTE_CNT
				,A.BLOCK_UNSPECIFIED_CNT=B.BLOCK_UNSPECIFIED_CNT
				,A.RSRP_SUM=B.RSRP_SUM
				,A.RSRP_CNT=B.RSRP_CNT
				,A.RSRQ_SUM=B.RSRQ_SUM
				,A.RSRQ_CNT=B.RSRQ_CNT
				,A.CALL_SETUP_TIME_SUM=B.CALL_SETUP_TIME_SUM
				,A.CALL_SETUP_TIME_CNT=B.CALL_SETUP_TIME_CNT
				,A.CALL_SETUP_TIME_SIG_SUM=B.CALL_SETUP_TIME_SIG_SUM
				,A.CALL_SETUP_TIME_SIG_CNT=B.CALL_SETUP_TIME_SIG_CNT
				,A.CALL_SETUP_TIME_DATA_SUM=B.CALL_SETUP_TIME_DATA_SUM 
				,A.CALL_SETUP_TIME_DATA_CNT=B.CALL_SETUP_TIME_DATA_CNT
				,A.CALL_SETUP_TIME_SMS_SUM=B.CALL_SETUP_TIME_SMS_SUM
				,A.CALL_SETUP_TIME_SMS_CNT=B.CALL_SETUP_TIME_SMS_CNT
				,A.CALL_SETUP_TIME_VOLTE_SUM=B.CALL_SETUP_TIME_VOLTE_SUM
				,A.CALL_SETUP_TIME_VOLTE_CNT=B.CALL_SETUP_TIME_VOLTE_CNT
				,A.CALL_SETUP_TIME_UNSP_SUM=B.CALL_SETUP_TIME_UNSP_SUM
				,A.CALL_SETUP_TIME_UNSP_CNT=B.CALL_SETUP_TIME_UNSP_CNT
				,A.SF_DATA_CNT=B.SF_DATA_CNT
				,A.SF_SIGNAL_CNT=B.SF_SIGNAL_CNT
				,A.SF_SMS_CNT=B.SF_SMS_CNT
				,A.SF_VOLTE_CNT=B.SF_VOLTE_CNT
				,A.SF_UNSPECIFIED_CNT=B.SF_UNSPECIFIED_CNT
				,A.LATENCY_SUM=B.LATENCY_SUM
				,A.LATENCY_CNT=B.LATENCY_CNT
				WHERE A.CELL_ID=B.CELL_ID AND A.ENODEB_ID=B.ENODEB_ID AND A.PU_ID=B.PU_ID 
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('UPDATE ',GT_DB,'.`tmp_materialization_',WORKER_ID,'` a,',GT_DB,'.`tmp_cell_lte_end_',WORKER_ID,'` B
				SET
				A.END_CALL_CNT=B.END_CALL_CNT
				,A.END_SIGNAL_CNT=B.END_SIGNAL_CNT
				,A.END_DATA_CNT=B.END_DATA_CNT
				,A.END_SMS_CNT=B.END_SMS_CNT
				,A.END_VOLTE_CNT=B.END_VOLTE_CNT
				,A.END_UNSPECIFIED_CNT=B.END_UNSPECIFIED_CNT				
				,A.DROP_DATA_CNT=B.DROP_DATA_CNT
				,A.DROP_SIGNAL_CNT=B.DROP_SIGNAL_CNT
				,A.DROP_SMS_CNT=B.DROP_SMS_CNT
				,A.DROP_VOLTE_CNT=B.DROP_VOLTE_CNT
				,A.DROP_UNSPECIFIED_CNT=B.DROP_UNSPECIFIED_CNT
				,A.NON_BLOCK_SIGNAL_CNT=B.NON_BLOCK_SIGNAL_CNT
				,A.NON_BLOCK_DATA_CNT=B.NON_BLOCK_DATA_CNT
				,A.NON_BLOCK_SMS_CNT=B.NON_BLOCK_SMS_CNT
				,A.NON_BLOCK_VOLTE_CNT=B.NON_BLOCK_VOLTE_CNT
				,A.NON_BLOCK_UNSPECIFIED_CNT=B.NON_BLOCK_UNSPECIFIED_CNT
				,A.INTER_FREQ_ATTEMPT_CNT=B.INTER_FREQ_ATTEMPT_CNT
				,A.INTER_FREQ_FAILURE_CNT=B.INTER_FREQ_FAILURE_CNT
				,A.INTRA_FREQ_ATTEMPT_CNT=B.INTRA_FREQ_ATTEMPT_CNT
				,A.INTRA_FREQ_FAILURE_CNT=B.INTRA_FREQ_FAILURE_CNT
				,A.4G_3G_ATTEMPT_CNT=B.4G_3G_ATTEMPT_CNT
				,A.4G_3G_FAILURE_CNT=B.4G_3G_FAILURE_CNT
				,A.4G_2G_ATTEMPT_CNT=B.4G_2G_ATTEMPT_CNT
				,A.4G_2G_FAILURE_CNT=B.4G_2G_FAILURE_CNT
				,A.SRVCC_ATTEMPT_CNT=B.SRVCC_ATTEMPT_CNT
				,A.SRVCC_FAILURE_CNT=B.SRVCC_FAILURE_CNT
				WHERE A.CELL_ID=B.CELL_ID AND A.ENODEB_ID=B.ENODEB_ID AND A.PU_ID=B.PU_ID 
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('SELECT * FROM ',GT_DB,'.tmp_materialization_',WORKER_ID,' WHERE ENODEB_ID>0;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_materialization_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_cell_lte_start_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_cell_lte_end_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES('gt_gw_main','SP_Generate_Global_Statistic_cell_agg_lte',CONCAT(GT_DB,' END'), NOW());
	
END$$
DELIMITER ;
