DELIMITER $$
USE `gt_global_statistic`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Generate_Global_Statistic_cell_agg_umts`(IN DATA_DATE DATE,IN DATA_HOUR TINYINT(2),IN PU_ID MEDIUMINT(9),IN TECH_MASK TINYINT(2), IN GT_DB VARCHAR(100))
BEGIN
	DECLARE SP_Process VARCHAR(100) DEFAULT NULL;
	DECLARE WORKER_ID VARCHAR(10) DEFAULT CONNECTION_ID();
	DECLARE Spider_SP_ERROR CONDITION FOR SQLSTATE '99998';
	DECLARE KPI_ERROR CONDITION FOR SQLSTATE '99999' ;
	DECLARE ZOOM_LEVEL INT;
	INSERT INTO gt_gw_main.sp_log VALUES('gt_gw_main','SP_Generate_Global_Statistic_cell_agg_umts',CONCAT(GT_DB,' CREATE TEMPORARY TABLE tmp_materialization_',WORKER_ID), NOW());	
	
	SET @SqlCmd=CONCAT('SELECT `att_value` INTO @ZOOM_LEVEL FROM gt_covmo.`sys_config` WHERE `group_name`=''system'' AND att_name = ''MapResolution'';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET SESSION group_concat_max_len=102400; 
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_materialization_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,'.tmp_materialization_',WORKER_ID,' (
				`DATA_DATE` datetime NOT NULL,
				`DATA_HOUR` tinyint(4) NOT NULL,
				`CELL_ID` mediumint(9) NOT NULL,
				`SITE_ID` varchar(20) DEFAULT NULL,
				`CLUSTER_ID` mediumint(9) DEFAULT NULL,
				`RNC_ID` mediumint(9) NOT NULL,
				`FREQUENCY` smallint(6) DEFAULT NULL,
				`UARFCN` smallint(6) DEFAULT NULL,
				`INIT_CALL_CNT` INT(11) DEFAULT NULL,
				`END_CALL_CNT` INT(11) DEFAULT NULL,
				`VOICE_CNT` INT(11) DEFAULT NULL,
				`VIDEO_CNT` INT(11) DEFAULT NULL,
				`PS_R99_CNT` INT(11) DEFAULT NULL,
				`PS_HSPA_CNT` INT(11) DEFAULT NULL,
				`M_RAB_CNT` INT(11) DEFAULT NULL,
				`SIGNAL_CNT` INT(11) DEFAULT NULL,
				`SMS_CNT` INT(11) DEFAULT NULL,
				`PS_OTHER_CNT` INT(11) DEFAULT NULL,
				`END_VOICE_CNT` INT(11) DEFAULT NULL,
				`END_VIDEO_CNT` INT(11) DEFAULT NULL,
				`END_PS_R99_CNT` INT(11) DEFAULT NULL,
				`END_PS_HSPA_CNT` INT(11) DEFAULT NULL,
				`END_M_RAB_CNT` INT(11) DEFAULT NULL,
				`END_SIGNAL_CNT` INT(11) DEFAULT NULL,
				`END_SMS_CNT` INT(11) DEFAULT NULL,
				`END_PS_OTHER_CNT` INT(11) DEFAULT NULL,
				`DROP_VOICE_CNT` INT(11) DEFAULT NULL,
				`DROP_VIDEO_CNT` INT(11) DEFAULT NULL,
				`DROP_PS_R99_CNT` INT(11) DEFAULT NULL,
				`DROP_PS_HSPA_CNT` INT(11) DEFAULT NULL,
				`DROP_M_RAB_CNT` INT(11) DEFAULT NULL,
				`DROP_SIGNAL_CNT` INT(11) DEFAULT NULL,
				`DROP_SMS_CNT` INT(11) DEFAULT NULL,
				`DROP_PS_OTHER_CNT` INT(11) DEFAULT NULL,
				`NON_BLOCK_VOICE_CNT` INT(11) DEFAULT NULL,
				`NON_BLOCK_VIDEO_CNT` INT(11) DEFAULT NULL,
				`NON_BLOCK_PS_R99_CNT` INT(11) DEFAULT NULL,
				`NON_BLOCK_PS_HSPA_CNT` INT(11) DEFAULT NULL,
				`NON_BLOCK_M_RAB_CNT` INT(11) DEFAULT NULL,
				`NON_BLOCK_SIGNAL_CNT` INT(11) DEFAULT NULL,
				`NON_BLOCK_SMS_CNT` INT(11) DEFAULT NULL,
				`NON_BLOCK_PS_OTHER_CNT` INT(11) DEFAULT NULL,
				`BLOCK_VOICE_CNT` INT(11) DEFAULT NULL,
				`BLOCK_VEDIO_CNT` INT(11) DEFAULT NULL,
				`BLOCK_R99_CNT` INT(11) DEFAULT NULL,
				`BLOCK_HSPA_CNT` INT(11) DEFAULT NULL,
				`BLOCK_MRAB_CNT` INT(11) DEFAULT NULL,
				`BLOCK_SIGNAL_CNT` INT(11) DEFAULT NULL,
				`BLOCK_SMS_CNT` INT(11) DEFAULT NULL,
				`BLOCK_PS_OTHER_CNT` INT(11) DEFAULT NULL,
				`RSCP_SUM` DOUBLE DEFAULT NULL,
				`RSCP_CNT` INT(11) DEFAULT NULL,
				`ECN0_SUM` DOUBLE DEFAULT NULL,
				`ECN0_CNT` INT(11) DEFAULT NULL,
				`UL_VOLUME_SUM` DOUBLE DEFAULT NULL,
				`DL_VOLUME_SUM` DOUBLE DEFAULT NULL,
				`UL_THROUPUT_MAX` DOUBLE DEFAULT NULL,
				`DL_THROUPUT_MAX` DOUBLE DEFAULT NULL,
				`UL_THROUPUT_SUM` DOUBLE DEFAULT NULL,
				`UL_THROUPUT_CNT` INT(11) DEFAULT NULL,
				`DL_THROUPUT_SUM` DOUBLE DEFAULT NULL,
				`DL_THROUPUT_CNT` INT(11) DEFAULT NULL,
				`FP_RSCP_1` double DEFAULT NULL,
				`FP_ECN0_1` double DEFAULT NULL,
				`BEST_CNT` INT(11) DEFAULT NULL,
				`CALL_SETUP_TIME_VOICE_SUM` int(11) DEFAULT NULL,
				`CALL_SETUP_TIME_VOICE_CNT` int(11) DEFAULT NULL,
				`CALL_SETUP_TIME_VEDIO_SUM` int(11) DEFAULT NULL,
				`CALL_SETUP_TIME_VEDIO_CNT` int(11) DEFAULT NULL,
				`CALL_SETUP_TIME_R99_SUM` int(11) DEFAULT NULL,
				`CALL_SETUP_TIME_R99_CNT` int(11) DEFAULT NULL,
				`CALL_SETUP_TIME_HSPA_SUM` int(11) DEFAULT NULL,
				`CALL_SETUP_TIME_HSPA_CNT` int(11) DEFAULT NULL,
				`CALL_SETUP_TIME_MRAB_SUM` int(11) DEFAULT NULL,
				`CALL_SETUP_TIME_MRAB_CNT` int(11) DEFAULT NULL,
				`CALL_SETUP_TIME_SIG_SUM` int(11) DEFAULT NULL,
				`CALL_SETUP_TIME_SIG_CNT` int(11) DEFAULT NULL,
				`CALL_SETUP_TIME_OTH_SUM` int(11) DEFAULT NULL,
				`CALL_SETUP_TIME_OTH_CNT` int(11) DEFAULT NULL,
				`CALL_SETUP_TIME_SMS_SUM` int(11) DEFAULT NULL,
				`CALL_SETUP_TIME_SMS_CNT` int(11) DEFAULT NULL,
				`CALL_SETUP_TIME_SUM` int(11) DEFAULT NULL,
				`CALL_SETUP_TIME_CNT` int(11) DEFAULT NULL,
				`SF_VOICE_CNT` int(11) DEFAULT NULL,
				`SF_VEDIO_CNT` int(11) DEFAULT NULL,
				`SF_R99_CNT` int(11) DEFAULT NULL,
				`SF_HSPA_CNT` int(11) DEFAULT NULL,
				`SF_MRAB_CNT` int(11) DEFAULT NULL,
				`SF_OTHER_CNT` int(11) DEFAULT NULL,
				`SF_SMS_CNT` int(11) DEFAULT NULL,
				`SF_SIGNAL_CNT` int(11) DEFAULT NULL,
				`CALL_DUR_SUM` DOUBLE DEFAULT NULL,
				`VOICE_DUR_SUM` DOUBLE DEFAULT NULL,
				`VIDEO_DUR_SUM` DOUBLE DEFAULT NULL,
				`R99_DUR_SUM` DOUBLE DEFAULT NULL,
				`HSPA_DUR_SUM` DOUBLE DEFAULT NULL,
				`MRAB_DUR_SUM` DOUBLE DEFAULT NULL
				,PRIMARY KEY (`CELL_ID`,RNC_ID,`DATA_DATE`,`DATA_HOUR`)
				) ENGINE=MYISAM DEFAULT CHARSET=latin1;');
	
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES('gt_gw_main','SP_Generate_Global_Statistic_cell_agg_umts',CONCAT(GT_DB,' INSERT INTO tbl_',GT_DB,'_',WORKER_ID), NOW());	
	 
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_cell_umts_start_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_cell_umts_end_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_cell_umts_fp_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,'.tmp_cell_umts_start_',WORKER_ID,' ENGINE=MYISAM AS
				SELECT
					POS_FIRST_CELL AS `CELL_ID`
					,POS_FIRST_SITE AS `SITE_ID`
					,POS_FIRST_RNC AS RNC_ID
					,POS_FIRST_CLUSTER AS CLUSTER_ID
					,POS_FIRST_FREQUENCY AS FREQUENCY
					,POS_FIRST_UARFCN AS UARFCN
					,DATA_DATE
					,DATA_HOUR
					,COUNT(*) AS INIT_CALL_CNT			
					,SUM(IF(CALL_TYPE=10,1,0)) AS VOICE_CNT
					,SUM(IF(CALL_TYPE=11,1,0)) AS VIDEO_CNT
					,SUM(IF(CALL_TYPE=12,1,0)) AS PS_R99_CNT
					,SUM(IF(CALL_TYPE=13,1,0)) AS PS_HSPA_CNT
					,SUM(IF(CALL_TYPE=14,1,0)) AS M_RAB_CNT
					,SUM(IF(CALL_TYPE=15,1,0)) AS SIGNAL_CNT
					,SUM(IF(CALL_TYPE=16,1,0)) AS SMS_CNT
					,SUM(IF(CALL_TYPE=18,1,0)) AS PS_OTHER_CNT
					,SUM(IF(CALL_STATUS=3 AND CALL_TYPE=10,1,0)) AS BLOCK_VOICE_CNT
					,SUM(IF(CALL_STATUS=3 AND CALL_TYPE=11,1,0)) AS BLOCK_VEDIO_CNT
					,SUM(IF(CALL_STATUS=3 AND CALL_TYPE=12,1,0)) AS BLOCK_R99_CNT
					,SUM(IF(CALL_STATUS=3 AND CALL_TYPE=13,1,0)) AS BLOCK_HSPA_CNT
					,SUM(IF(CALL_STATUS=3 AND CALL_TYPE=14,1,0)) AS BLOCK_MRAB_CNT
					,SUM(IF(CALL_STATUS=3 AND CALL_TYPE=15,1,0)) AS BLOCK_SIGNAL_CNT
					,SUM(IF(CALL_STATUS=3 AND CALL_TYPE=16,1,0)) AS BLOCK_SMS_CNT
					,SUM(IF(CALL_STATUS=3 AND CALL_TYPE=18,1,0)) AS BLOCK_PS_OTHER_CNT
					,SUM(POS_FIRST_RSCP) AS RSCP_SUM
					,COUNT(POS_FIRST_RSCP) AS RSCP_CNT
					,SUM(POS_FIRST_ECN0) AS ECN0_SUM
					,COUNT(POS_FIRST_ECN0) AS ECN0_CNT
					
					,IFNULL(SUM(IF(CALL_TYPE =10,CALL_SETUP_TIME,0)),0) AS CALL_SETUP_TIME_VOICE_SUM
					,IFNULL(SUM(IF(CALL_SETUP_TIME>=0 AND CALL_TYPE =10,1,0)),0) AS CALL_SETUP_TIME_VOICE_CNT
					,IFNULL(SUM(IF(CALL_TYPE =11,CALL_SETUP_TIME,0)),0) AS CALL_SETUP_TIME_VEDIO_SUM
					,IFNULL(SUM(IF(CALL_SETUP_TIME>=0 AND CALL_TYPE =11,1,0)),0) AS CALL_SETUP_TIME_VEDIO_CNT
					,IFNULL(SUM(IF(CALL_TYPE =12,CALL_SETUP_TIME,0)),0) AS CALL_SETUP_TIME_R99_SUM
					,IFNULL(SUM(IF(CALL_SETUP_TIME>=0 AND CALL_TYPE =12,1,0)),0) AS CALL_SETUP_TIME_R99_CNT
					,IFNULL(SUM(IF(CALL_TYPE =13,CALL_SETUP_TIME,0)),0) AS CALL_SETUP_TIME_HSPA_SUM
					,IFNULL(SUM(IF(CALL_SETUP_TIME>=0 AND CALL_TYPE =13,1,0)),0) AS CALL_SETUP_TIME_HSPA_CNT
					,IFNULL(SUM(IF(CALL_TYPE =14,CALL_SETUP_TIME,0)),0) AS CALL_SETUP_TIME_MRAB_SUM
					,IFNULL(SUM(IF(CALL_SETUP_TIME>=0 AND CALL_TYPE =14,1,0)),0) AS CALL_SETUP_TIME_MRAB_CNT
					,IFNULL(SUM(IF(CALL_TYPE =15,CALL_SETUP_TIME,0)),0) AS CALL_SETUP_TIME_SIG_SUM
					,IFNULL(SUM(IF(CALL_SETUP_TIME>=0 AND CALL_TYPE =15,1,0)),0) AS CALL_SETUP_TIME_SIG_CNT
					,IFNULL(SUM(IF(CALL_TYPE =18,CALL_SETUP_TIME,0)),0) AS CALL_SETUP_TIME_OTH_SUM
					,IFNULL(SUM(IF(CALL_SETUP_TIME>=0 AND CALL_TYPE =18,1,0)),0) AS CALL_SETUP_TIME_OTH_CNT
					,IFNULL(SUM(IF(CALL_TYPE =16,CALL_SETUP_TIME,0)),0) AS CALL_SETUP_TIME_SMS_SUM
					,IFNULL(SUM(IF(CALL_SETUP_TIME>=0 AND CALL_TYPE =16,1,0)),0) AS CALL_SETUP_TIME_SMS_CNT
	
					,SUM(CALL_SETUP_TIME) AS CALL_SETUP_TIME_SUM
					,SUM(IF(CALL_SETUP_TIME>=0,1,0)) AS CALL_SETUP_TIME_CNT
					,SUM(IF(CALL_STATUS=6 AND CALL_TYPE=10,1,0)) AS SF_VOICE_CNT
					,SUM(IF(CALL_STATUS=6 AND CALL_TYPE=11,1,0)) AS SF_VEDIO_CNT
					,SUM(IF(CALL_STATUS=6 AND CALL_TYPE=12,1,0)) AS SF_R99_CNT
					,SUM(IF(CALL_STATUS=6 AND CALL_TYPE=13,1,0)) AS SF_HSPA_CNT
					,SUM(IF(CALL_STATUS=6 AND CALL_TYPE=14,1,0)) AS SF_MRAB_CNT
					,SUM(IF(CALL_STATUS=6 AND CALL_TYPE=18,1,0)) AS SF_OTHER_CNT
					,SUM(IF(CALL_STATUS=6 AND CALL_TYPE=16,1,0)) AS SF_SMS_CNT
					,SUM(IF(CALL_STATUS=6 AND CALL_TYPE=15,1,0)) AS SF_SIGNAL_CNT
					,SUM(RRC_CONNECT_DURATION) AS CALL_DUR_SUM
					,SUM(IF(CALL_TYPE=10,RRC_CONNECT_DURATION,0)) AS VOICE_DUR_SUM
					,SUM(IF(CALL_TYPE=11,RRC_CONNECT_DURATION,0)) AS VIDEO_DUR_SUM
					,SUM(IF(CALL_TYPE=12,RRC_CONNECT_DURATION,0)) AS R99_DUR_SUM
					,SUM(IF(CALL_TYPE=13,RRC_CONNECT_DURATION,0)) AS HSPA_DUR_SUM
					,SUM(IF(CALL_TYPE=14,RRC_CONNECT_DURATION,0)) AS MRAB_DUR_SUM
				FROM ',GT_DB,'.table_call
				WHERE DATA_HOUR =',DATA_HOUR,' AND POS_FIRST_CELL IS NOT NULL AND POS_FIRST_RNC=',PU_ID,' 
				GROUP BY POS_FIRST_RNC,POS_FIRST_CELL
				ORDER BY NULL;
				');
	
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,'.tmp_cell_umts_end_',WORKER_ID,' ENGINE=MYISAM AS
				SELECT
					POS_LAST_CELL AS `CELL_ID`
					,POS_LAST_SITE AS `SITE_ID`
					,POS_LAST_RNC AS RNC_ID
					,POS_LAST_CLUSTER AS CLUSTER_ID
					,POS_LAST_FREQUENCY AS FREQUENCY
					,POS_LAST_UARFCN AS UARFCN
					,DATA_DATE
					,DATA_HOUR
					,COUNT(*) AS END_CALL_CNT
					,SUM(IF(CALL_TYPE=10,1,0)) AS END_VOICE_CNT
					,SUM(IF(CALL_TYPE=11,1,0)) AS END_VIDEO_CNT
					,SUM(IF(CALL_TYPE=12,1,0)) AS END_PS_R99_CNT
					,SUM(IF(CALL_TYPE=13,1,0)) AS END_PS_HSPA_CNT
					,SUM(IF(CALL_TYPE=14,1,0)) AS END_M_RAB_CNT
					,SUM(IF(CALL_TYPE=15,1,0)) AS END_SIGNAL_CNT
					,SUM(IF(CALL_TYPE=16,1,0)) AS END_SMS_CNT
					,SUM(IF(CALL_TYPE=18,1,0)) AS END_PS_OTHER_CNT
					,SUM(IF(CALL_STATUS=2 AND CALL_TYPE=10,1,0)) AS DROP_VOICE_CNT
					,SUM(IF(CALL_STATUS=2 AND CALL_TYPE=11,1,0)) AS DROP_VIDEO_CNT
					,SUM(IF(CALL_STATUS=2 AND CALL_TYPE=12,1,0)) AS DROP_PS_R99_CNT
					,SUM(IF(CALL_STATUS=2 AND CALL_TYPE=13,1,0)) AS DROP_PS_HSPA_CNT
					,SUM(IF(CALL_STATUS=2 AND CALL_TYPE=14,1,0)) AS DROP_M_RAB_CNT
					,SUM(IF(CALL_STATUS=2 AND CALL_TYPE=15,1,0)) AS DROP_SIGNAL_CNT
					,SUM(IF(CALL_STATUS=2 AND CALL_TYPE=16,1,0)) AS DROP_SMS_CNT
					,SUM(IF(CALL_STATUS=2 AND CALL_TYPE=18,1,0)) AS DROP_PS_OTHER_CNT
					,SUM(IF(CALL_STATUS IN (1,2,4,5) AND CALL_TYPE=10,1,0)) AS NON_BLOCK_VOICE_CNT
					,SUM(IF(CALL_STATUS IN (1,2,4,5) AND CALL_TYPE=11,1,0)) AS NON_BLOCK_VIDEO_CNT
					,SUM(IF(CALL_STATUS IN (1,2,4,5) AND CALL_TYPE=12,1,0)) AS NON_BLOCK_PS_R99_CNT
					,SUM(IF(CALL_STATUS IN (1,2,4,5) AND CALL_TYPE=13,1,0)) AS NON_BLOCK_PS_HSPA_CNT
					,SUM(IF(CALL_STATUS IN (1,2,4,5) AND CALL_TYPE=14,1,0)) AS NON_BLOCK_M_RAB_CNT
					,SUM(IF(CALL_STATUS IN (1,2,4,5) AND CALL_TYPE=15,1,0)) AS NON_BLOCK_SIGNAL_CNT
					,SUM(IF(CALL_STATUS IN (1,2,4,5) AND CALL_TYPE=16,1,0)) AS NON_BLOCK_SMS_CNT
					,SUM(IF(CALL_STATUS IN (1,2,4,5) AND CALL_TYPE=18,1,0)) AS NON_BLOCK_PS_OTHER_CNT
				FROM ',GT_DB,'.table_call
				WHERE DATA_HOUR =',DATA_HOUR,' AND POS_LAST_CELL IS NOT NULL AND POS_LAST_RNC=',PU_ID,' 
 				GROUP BY POS_LAST_CELL,POS_LAST_RNC
				ORDER BY NULL;
				');
	
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.`tmp_materialization_',WORKER_ID,'` 
				( `CELL_ID`,`SITE_ID`,`RNC_ID`,CLUSTER_ID,FREQUENCY,UARFCN,DATA_DATE,DATA_HOUR
					,UL_VOLUME_SUM
					,DL_VOLUME_SUM
					,UL_THROUPUT_MAX
					,DL_THROUPUT_MAX
					,UL_THROUPUT_SUM
					,UL_THROUPUT_CNT
					,DL_THROUPUT_SUM
					,DL_THROUPUT_CNT
					,FP_RSCP_1
					,FP_ECN0_1
					,BEST_CNT
				)
				SELECT
					CELL_ID,
					SITE_ID,
					RNC_ID,
					CLUSTER_ID,
					FREQUENCY,
					UARFCN,
					DATA_DATE,
					DATA_HOUR,
					IFNULL(SUM(IF(CALL_TYPE IN (12,13,14,18),UL_TRAFFIC_VOLUME,0)),0) AS `UL_VOLUME_SUM`,
					IFNULL(SUM(IF(CALL_TYPE IN (12,13,14,18),DL_TRAFFIC_VOLUME,0)),0) AS `DL_VOLUME_SUM`,
					MAX(IF(CALL_TYPE IN (12,13,14,18),(UL_THROUGHPUT_SUM/UL_THROUGHPUT_EVENT_CNT),0)) AS UL_THROUPUT_MAX,
					MAX(IF(CALL_TYPE IN (12,13,14,18),(DL_THROUGHPUT_SUM/DL_THROUGHPUT_EVENT_CNT),0)) AS DL_THROUPUT_MAX,
					IFNULL(SUM(IF(CALL_TYPE IN (12,13,14,18),UL_THROUGHPUT_SUM,0)),0) AS UL_THROUPUT_SUM,
					IFNULL(SUM(IF(CALL_TYPE IN (12,13,14,18),UL_THROUGHPUT_EVENT_CNT,0)),0) AS UL_THROUPUT_CNT,
					IFNULL(SUM(IF(CALL_TYPE IN (12,13,14,18),DL_THROUGHPUT_SUM,0)),0) AS DL_THROUPUT_SUM,
					IFNULL(SUM(IF(CALL_TYPE IN (12,13,14,18),DL_THROUGHPUT_EVENT_CNT,0)),0) AS DL_THROUPUT_CNT,
					SUM(`FP_RSCP_1`) AS `FP_RSCP_1`,
					SUM(`FP_ECN0_1`) AS `FP_ECN0_1`,
					SUM(`BEST_CNT`) AS `BEST_CNT`
				FROM ',GT_DB,'.`table_tile_fp_c`
				WHERE DATA_HOUR =',DATA_HOUR,' AND RNC_ID=',PU_ID,'  
				GROUP BY CELL_ID,RNC_ID
 				HAVING SUM(`BEST_CNT`)>1
				ORDER BY NULL;
				');
	
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE INDEX `ix_tile_fq` ON ',GT_DB,'.tmp_cell_umts_start_',WORKER_ID,' (CELL_ID,RNC_ID);');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE INDEX `ix_tile_fq` ON ',GT_DB,'.tmp_cell_umts_end_',WORKER_ID,' (CELL_ID,RNC_ID);');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('UPDATE ',GT_DB,'.`tmp_materialization_',WORKER_ID,'` a,',GT_DB,'.`tmp_cell_umts_start_',WORKER_ID,'` B
				SET 
				A.INIT_CALL_CNT=B.INIT_CALL_CNT
				,A.VOICE_CNT=B.VOICE_CNT
				,A.VIDEO_CNT=B.VIDEO_CNT
				,A.PS_R99_CNT=B.PS_R99_CNT
				,A.PS_HSPA_CNT=B.PS_HSPA_CNT
				,A.M_RAB_CNT=B.M_RAB_CNT
				,A.SIGNAL_CNT=B.SIGNAL_CNT
				,A.SMS_CNT=B.SMS_CNT
				,A.PS_OTHER_CNT=B.PS_OTHER_CNT
				,A.BLOCK_VOICE_CNT=B.BLOCK_VOICE_CNT
				,A.BLOCK_VEDIO_CNT=B.BLOCK_VEDIO_CNT
				,A.BLOCK_R99_CNT=B.BLOCK_R99_CNT
				,A.BLOCK_HSPA_CNT=B.BLOCK_HSPA_CNT
				,A.BLOCK_MRAB_CNT=B.BLOCK_MRAB_CNT
				,A.BLOCK_SIGNAL_CNT=B.BLOCK_SIGNAL_CNT
				,A.BLOCK_SMS_CNT=B.BLOCK_SMS_CNT
				,A.BLOCK_PS_OTHER_CNT=B.BLOCK_PS_OTHER_CNT
				,A.RSCP_SUM=B.RSCP_SUM
				,A.RSCP_CNT=B.RSCP_CNT
				,A.ECN0_SUM=B.ECN0_SUM
				,A.ECN0_CNT=B.ECN0_CNT
	
	
				,A.CALL_SETUP_TIME_VOICE_SUM=B.CALL_SETUP_TIME_VOICE_SUM
				,A.CALL_SETUP_TIME_VOICE_CNT=B.CALL_SETUP_TIME_VOICE_CNT
				,A.CALL_SETUP_TIME_VEDIO_SUM=B.CALL_SETUP_TIME_VEDIO_SUM
				,A.CALL_SETUP_TIME_VEDIO_CNT=B.CALL_SETUP_TIME_VEDIO_CNT
				,A.CALL_SETUP_TIME_R99_SUM=B.CALL_SETUP_TIME_R99_SUM
				,A.CALL_SETUP_TIME_R99_CNT=B.CALL_SETUP_TIME_R99_CNT
				,A.CALL_SETUP_TIME_HSPA_SUM=B.CALL_SETUP_TIME_HSPA_SUM 
				,A.CALL_SETUP_TIME_HSPA_CNT=B.CALL_SETUP_TIME_HSPA_CNT
				,A.CALL_SETUP_TIME_MRAB_SUM=B.CALL_SETUP_TIME_MRAB_SUM
				,A.CALL_SETUP_TIME_MRAB_CNT=B.CALL_SETUP_TIME_MRAB_CNT
				,A.CALL_SETUP_TIME_SIG_SUM=B.CALL_SETUP_TIME_SIG_SUM
				,A.CALL_SETUP_TIME_SIG_CNT=B.CALL_SETUP_TIME_SIG_CNT
				,A.CALL_SETUP_TIME_OTH_SUM=B.CALL_SETUP_TIME_OTH_SUM
				,A.CALL_SETUP_TIME_OTH_CNT=B.CALL_SETUP_TIME_OTH_CNT
				,A.CALL_SETUP_TIME_SMS_SUM=B.CALL_SETUP_TIME_SMS_SUM
				,A.CALL_SETUP_TIME_SMS_CNT=B.CALL_SETUP_TIME_SMS_CNT
	
				,A.CALL_SETUP_TIME_SUM=B.CALL_SETUP_TIME_SUM
				,A.CALL_SETUP_TIME_CNT=B.CALL_SETUP_TIME_CNT
				,A.SF_VOICE_CNT=B.SF_VOICE_CNT
				,A.SF_VEDIO_CNT=B.SF_VEDIO_CNT
				,A.SF_R99_CNT=B.SF_R99_CNT
				,A.SF_HSPA_CNT=B.SF_HSPA_CNT
				,A.SF_MRAB_CNT=B.SF_MRAB_CNT
				,A.SF_OTHER_CNT=B.SF_OTHER_CNT
				,A.SF_SMS_CNT=B.SF_SMS_CNT
				,A.SF_SIGNAL_CNT=B.SF_SIGNAL_CNT
				,A.CALL_DUR_SUM=B.CALL_DUR_SUM
				,A.VOICE_DUR_SUM=B.VOICE_DUR_SUM
				,A.VIDEO_DUR_SUM=B.VIDEO_DUR_SUM
				,A.R99_DUR_SUM=B.R99_DUR_SUM
				,A.HSPA_DUR_SUM=B.HSPA_DUR_SUM
				,A.MRAB_DUR_SUM=B.MRAB_DUR_SUM
				WHERE A.CELL_ID=B.CELL_ID AND A.RNC_ID=B.RNC_ID;');
	
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('UPDATE ',GT_DB,'.`tmp_materialization_',WORKER_ID,'` a,',GT_DB,'.`tmp_cell_umts_end_',WORKER_ID,'` B
				SET
				A.END_CALL_CNT=B.END_CALL_CNT
				,A.END_VOICE_CNT=B.END_VOICE_CNT
				,A.END_VIDEO_CNT=B.END_VIDEO_CNT
				,A.END_PS_R99_CNT=B.END_PS_R99_CNT
				,A.END_PS_HSPA_CNT=B.END_PS_HSPA_CNT
				,A.END_M_RAB_CNT=B.END_M_RAB_CNT
				,A.END_SIGNAL_CNT=B.END_SIGNAL_CNT
				,A.END_SMS_CNT=B.END_SMS_CNT
				,A.END_PS_OTHER_CNT=B.END_PS_OTHER_CNT
				,A.DROP_VOICE_CNT=B.DROP_VOICE_CNT
				,A.DROP_VIDEO_CNT=B.DROP_VIDEO_CNT
				,A.DROP_PS_R99_CNT=B.DROP_PS_R99_CNT
				,A.DROP_PS_HSPA_CNT=B.DROP_PS_HSPA_CNT
				,A.DROP_M_RAB_CNT=B.DROP_M_RAB_CNT
				,A.DROP_SIGNAL_CNT=B.DROP_SIGNAL_CNT
				,A.DROP_SMS_CNT=B.DROP_SMS_CNT
				,A.DROP_PS_OTHER_CNT=B.DROP_PS_OTHER_CNT
				,A.NON_BLOCK_VOICE_CNT=B.NON_BLOCK_VOICE_CNT
				,A.NON_BLOCK_VIDEO_CNT=B.NON_BLOCK_VIDEO_CNT
				,A.NON_BLOCK_PS_R99_CNT=B.NON_BLOCK_PS_R99_CNT
				,A.NON_BLOCK_PS_HSPA_CNT=B.NON_BLOCK_PS_HSPA_CNT
				,A.NON_BLOCK_M_RAB_CNT=B.NON_BLOCK_M_RAB_CNT
				,A.NON_BLOCK_SIGNAL_CNT=B.NON_BLOCK_SIGNAL_CNT
				,A.NON_BLOCK_SMS_CNT=B.NON_BLOCK_SMS_CNT
				,A.NON_BLOCK_PS_OTHER_CNT=B.NON_BLOCK_PS_OTHER_CNT
			WHERE A.CELL_ID=B.CELL_ID AND A.RNC_ID=B.RNC_ID;');
	
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('SELECT * FROM ',GT_DB,'.tmp_materialization_',WORKER_ID,' WHERE CELL_ID >0;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_materialization_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_cell_umts_start_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.tmp_cell_umts_end_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES('gt_gw_main','SP_Generate_Global_Statistic_cell_agg_umts',CONCAT(GT_DB,' END'), NOW());
	
END$$
DELIMITER ;
