DELIMITER $$
USE `gt_global_statistic`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Generate_Global_Statistic_DS_Sub_TmpTbl_Crt`(IN WORKER_ID VARCHAR(10),IN RPT_TYPE TINYINT(2),IN TileResolution VARCHAR(10))
BEGIN
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE STEP_START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE SP_Process VARCHAR(100) DEFAULT NULL;
	DECLARE KPI_ERROR CONDITION FOR SQLSTATE '99999' ;
	DECLARE FIRSTDAY_OF_WEEK TINYINT(4) DEFAULT 6;
	DECLARE v_DATA_DATE VARCHAR(10) DEFAULT NULL;
	DECLARE v_DATA_HOUR TINYINT(2) DEFAULT NULL;
	DECLARE v_PU_ID MEDIUMINT(9) DEFAULT NULL;
	DECLARE v_TECH_MASK TINYINT(2) DEFAULT NULL;
	DECLARE EX_DATE VARCHAR(100) DEFAULT NULL;
	
	SET @global_db='gt_global_statistic';
		
	SET @TILE_ID_LVL1 = CONCAT('TILE_ID_',gt_covmo_csv_get(TileResolution,1));
	SET @TILE_ID_LVL2 = CONCAT('TILE_ID_',gt_covmo_csv_get(TileResolution,2));
	
	SET @SqlCmd=CONCAT('SELECT GROUP_CONCAT(DISTINCT CONCAT(`DATA_DATE`,'','',`DATA_HOUR`,'','',`TECH_MASK`) SEPARATOR ''|'' ) INTO @DIS_DATE
				FROM gt_global_statistic.table_running_task_ds a;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
        	
	SET @v_i=1;
	SET @v_R_Max=gt_covmo_csv_count(@DIS_DATE,'|');
	
	WHILE @v_i <= @v_R_Max DO
	BEGIN	  			
		SET SESSION group_concat_max_len=102400; 
		
		SET v_DATA_DATE:=gt_covmo_csv_get(gt_strtok(@DIS_DATE, @v_i, '|'),1);		
		SET v_DATA_HOUR:=gt_covmo_csv_get(gt_strtok(@DIS_DATE, @v_i, '|'),2);
		SET v_TECH_MASK:=gt_covmo_csv_get(gt_strtok(@DIS_DATE, @v_i, '|'),3);
		SET EX_DATE=CONCAT(DATE_FORMAT(v_DATA_DATE,'%Y%m%d_'),v_DATA_HOUR,'_',WORKER_ID);
		
		IF v_TECH_MASK=2 THEN
			IF (RPT_TYPE & 1)>0 THEN 				
				SET @SqlCmd=CONCAT('CREATE TABLE IF NOT EXISTS ',@global_db,'.tmp_ds_tile_umts_',EX_DATE,' (
							  `TILE_ID` BIGINT(20) NOT NULL,
							  `DATA_DATE` DATETIME NOT NULL,
							  `DATA_HOUR` TINYINT(2) NOT NULL,
							  `',@TILE_ID_LVL2,'` BIGINT(20) DEFAULT NULL,
							  `',@TILE_ID_LVL1,'` BIGINT(20) DEFAULT NULL,
							  `RSCP_SUM` DOUBLE DEFAULT NULL,
							  `RSCP_CNT` INT(11) DEFAULT NULL,
							  `ECNO_SUM` DOUBLE DEFAULT NULL,
							  `ECNO_CNT` INT(11) DEFAULT NULL,
							  `UMTS_CS_CALL_CNT` INT(11) DEFAULT NULL,
							  `UMTS_PS_CALL_CNT` INT(11) DEFAULT NULL,
							  `UMTS_VOICE_DROP_CNT` INT(11) DEFAULT NULL,
							  `UMTS_PS_DROP_CNT` INT(11) DEFAULT NULL,
							  `UMTS_CS_CALL_DURATION` DOUBLE DEFAULT NULL,
							  `UMTS_CS_BLOCK_CNT` INT(11) DEFAULT NULL,
							  `UMTS_PS_BLOCK_CNT` INT(11) DEFAULT NULL,
							  `UMTS_UL_VOLUME` DOUBLE DEFAULT NULL,
							  `UMTS_DL_VOLUME` DOUBLE DEFAULT NULL,
							  `UMTS_UL_THROUPUT_SUM` DOUBLE DEFAULT NULL,
							  `UMTS_UL_THROUPUT_CNT` INT(11) DEFAULT NULL,
							  `UMTS_DL_THROUPUT_SUM` DOUBLE DEFAULT NULL,
							  `UMTS_DL_THROUPUT_CNT` INT(11) DEFAULT NULL,
							  `UMTS_CALL_SETUP_TIME_SUM` double DEFAULT NULL,
							  `UMTS_CALL_SETUP_TIME_CNT` int(11) DEFAULT NULL,
							  `UMTS_CS_CALL_SETUP_TIME_SUM` INT(11) DEFAULT NULL,
							  `UMTS_CS_CALL_SETUP_TIME_CNT` INT(11) DEFAULT NULL,
							  `UMTS_PS_CALL_SETUP_TIME_SUM` INT(11) DEFAULT NULL,
							  `UMTS_PS_CALL_SETUP_TIME_CNT` INT(11) DEFAULT NULL,
							  `UMTS_CS_SETUP_FAILURE_CNT` int(11) DEFAULT NULL,
							  `UMTS_PS_SETUP_FAILURE_CNT` int(11) DEFAULT NULL,
							  `UMTS_MAX_UL_THROUPUT` DOUBLE DEFAULT NULL,
							  `UMTS_MAX_DL_THROUPUT` DOUBLE DEFAULT NULL,
							  `UMTS_IRAT_HO_ATMP` int(11) DEFAULT NULL,
							  `UMTS_IRAT_HO_FAIL` int(11) DEFAULT NULL,
							  `REG_1_ID` BIGINT(20) DEFAULT NULL,
							  `REG_2_ID` BIGINT(20) DEFAULT NULL,
							  `REG_3_ID` BIGINT(20) DEFAULT NULL
							) ENGINE=MYISAM DEFAULT CHARSET=latin1;');
				PREPARE Stmt FROM @SqlCmd;
				EXECUTE Stmt;
				DEALLOCATE PREPARE Stmt;
			END IF;
			INSERT INTO gt_gw_main.SP_LOG VALUES('GT_DB','SP_Generate_Global_Statistic_DS_Sub_TmpTbl_Crt',CONCAT('tmp_lte_',EX_DATE,' CREATE tmp_umts_tables cost:',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' sec.'), NOW());		
		ELSEIF v_TECH_MASK=1 THEN
			IF (RPT_TYPE & 1)>0 THEN 
				SET @SqlCmd=CONCAT('CREATE TABLE IF NOT EXISTS ',@global_db,'.tmp_ds_tile_gsm_',EX_DATE,' (
							  `TILE_ID` BIGINT(20) NOT NULL,
							  `DATA_DATE` DATETIME NOT NULL,
							  `DATA_HOUR` TINYINT(2) NOT NULL,
							  `',@TILE_ID_LVL2,'` BIGINT(20) DEFAULT NULL,
							  `',@TILE_ID_LVL1,'` BIGINT(20) DEFAULT NULL,
							  `RXLEV_SUM` double DEFAULT NULL,
							  `RXLEV_CNT` int(11) DEFAULT NULL,
							  `RXQUAL_SUM` double DEFAULT NULL,
							  `RXQUAL_CNT` int(11) DEFAULT NULL,
							  `GSM_CS_CALL_CNT` int(11) DEFAULT NULL, 
							  `GSM_PS_CALL_CNT` int(11) DEFAULT NULL,
							  `GSM_VOICE_DROP_CNT` int(11) DEFAULT NULL,
							  `GSM_GPRS_DROP_CNT` int(11) DEFAULT NULL,
							  `GSM_SMS_DROP_CNT` int(11) DEFAULT NULL,
							  `GSM_CS_BLOCK_CNT` int(11) DEFAULT NULL,
							  `GSM_PS_BLOCK_CNT` int(11) DEFAULT NULL,
							  `GSM_CS_CALL_DURATION` double DEFAULT NULL,
							  `GSM_CALL_SETUP_TIME_SUM` double DEFAULT NULL,
							  `GSM_CALL_SETUP_TIME_CNT` int(11) DEFAULT NULL,
							  `GSM_CS_CALL_SETUP_TIME_SUM` INT(11) DEFAULT NULL,
							  `GSM_CS_CALL_SETUP_TIME_CNT` INT(11) DEFAULT NULL,
							  `GSM_PS_CALL_SETUP_TIME_SUM` INT(11) DEFAULT NULL,
							  `GSM_PS_CALL_SETUP_TIME_CNT` INT(11) DEFAULT NULL,
							  `GSM_CS_SETUP_FAILURE_CNT` int(11) DEFAULT NULL,
							  `GSM_PS_SETUP_FAILURE_CNT` int(11) DEFAULT NULL,
							  `REG_1_ID` BIGINT(20) DEFAULT NULL,
							  `REG_2_ID` BIGINT(20) DEFAULT NULL,
							  `REG_3_ID` BIGINT(20) DEFAULT NULL
							) ENGINE=MYISAM DEFAULT CHARSET=latin1;');		
				PREPARE Stmt FROM @SqlCmd;
				EXECUTE Stmt;
				DEALLOCATE PREPARE Stmt;
			END IF;
			INSERT INTO gt_gw_main.SP_LOG VALUES('GT_DB','SP_Generate_Global_Statistic_DS_Sub_TmpTbl_Crt',CONCAT('tmp_lte_',EX_DATE,' CREATE tmp_gsm_tables cost:',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' sec.'), NOW());		
		ELSEIF v_TECH_MASK=4 THEN
			IF (RPT_TYPE & 1)>0 THEN 
				SET @SqlCmd=CONCAT('CREATE TABLE IF NOT EXISTS ',@global_db,'.tmp_ds_tile_lte_',EX_DATE,' 
							(
							  `TILE_ID` BIGINT(20) NOT NULL,
							  `DATA_DATE` DATETIME NOT NULL,
							  `DATA_HOUR` TINYINT(4) NOT NULL,
							  `',@TILE_ID_LVL2,'` BIGINT(20) NULL,
							  `',@TILE_ID_LVL1,'` BIGINT(20) NULL,
							  `RSRP_SUM` DOUBLE DEFAULT NULL,
							  `RSRP_CNT` INT(11) DEFAULT NULL,
							  `RSRQ_SUM` DOUBLE DEFAULT NULL,
							  `RSRQ_CNT` INT(11) DEFAULT NULL,
							  `LTE_CALL_CNT` INT(11) DEFAULT NULL,
							  `LTE_DROP_CNT` INT(11) DEFAULT NULL,
							  `LTE_BLOCK_CNT` INT(11) DEFAULT NULL,
							  `LTE_UL_VOLUME` DOUBLE DEFAULT NULL,
							  `LTE_DL_VOLUME` DOUBLE DEFAULT NULL,
							  `LTE_UL_THROUPUT_SUM` DOUBLE DEFAULT NULL,
							  `LTE_UL_THROUPUT_CNT` INT(11) DEFAULT NULL,
							  `LTE_DL_THROUPUT_SUM` DOUBLE DEFAULT NULL,
							  `LTE_DL_THROUPUT_CNT` INT(11) DEFAULT NULL,
							  `LATENCY_SUM` DOUBLE DEFAULT NULL,
							  `LATENCY_CNT` INT(11) DEFAULT NULL,
							  `LTE_CALL_SETUP_TIME_SUM` INT(11) DEFAULT NULL,
							  `LTE_CALL_SETUP_TIME_CNT` INT(11) DEFAULT NULL,
							  `LTE_SETUP_FAILURE_CNT` INT(11) DEFAULT NULL,
							  `SRVCC_ATTEMPT_CNT` INT(11) DEFAULT NULL,
							  `SRVCC_FAILURE_CNT` INT(11) DEFAULT NULL,
							  `S1_HO_ATTEMPT` INT(11) DEFAULT NULL,
							  `S1_HO_FAILURE` INT(11) DEFAULT NULL,
							  `X2_HO_ATTEMPT` INT(11) DEFAULT NULL,
							  `X2_HO_FAILURE` INT(11) DEFAULT NULL,
							  `LTE_MAX_UL_THROUPUT` DOUBLE DEFAULT NULL,
							  `LTE_MAX_DL_THROUPUT` DOUBLE DEFAULT NULL,
							  `LTE_IRAT_TO_UMTS_ATMP` INT(11) DEFAULT NULL,
							  `LTE_IRAT_TO_GERAN_ATMP` INT(11) DEFAULT NULL,
							  `LTE_IRAT_TO_CDMA_ATMP` INT(11) DEFAULT NULL,
							  `LTE_IRAT_TO_UMTS_FAIL` INT(11) DEFAULT NULL,
							  `LTE_IRAT_TO_GERAN_FAIL` INT(11) DEFAULT NULL,
							  `LTE_IRAT_TO_CDMA_FAIL` INT(11) DEFAULT NULL,
							  `REG_1_ID` BIGINT(20) DEFAULT NULL,
							  `REG_2_ID` BIGINT(20) DEFAULT NULL,
							  `REG_3_ID` BIGINT(20) DEFAULT NULL
							) ENGINE=MYISAM DEFAULT CHARSET=latin1;');
		
				PREPARE Stmt FROM @SqlCmd;
				EXECUTE Stmt;
				DEALLOCATE PREPARE Stmt;
			END IF;
		END IF;	
		SET @v_i=@v_i+1;
	END;
	END WHILE;
	INSERT INTO gt_gw_main.SP_LOG VALUES('GT_DB','SP_Generate_Global_Statistic_DS_Sub_TmpTbl_Crt',CONCAT(WORKER_ID,' Done cost:',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' sec.'), NOW());
END$$
DELIMITER ;
