DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Generate_Report_Optimization_GSM`(IN gt_db VARCHAR(100),IN GT_COVMO VARCHAR(100))
BEGIN	
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE IMSI_IMEI_DIFF_FLAG VARCHAR(10);
				 
	INSERT INTO gt_gw_main.SP_LOG VALUES(GT_DB,'SP_Generate_Report_Optimization_GSM','Start', START_TIME);
	SELECT LOWER(`value`) INTO IMSI_IMEI_DIFF_FLAG  FROM gt_gw_main.integration_param WHERE gt_group = 'sp' AND gt_name = 'imsi_imei_diff' ;
	CALL gt_gw_main.SP_Sub_Update_IMSI_CNT_GSM(GT_DB,'','AP','d');
-- 	CALL gt_gw_main.SP_Generate_IMSI_PU_Daily(GT_DB,1);	
	IF IMSI_IMEI_DIFF_FLAG = 'true' THEN 
		CALL gt_gw_main.`SP_Generate_IMSI_IMEI_Daily`(GT_DB,1);
	ELSE
		CALL gt_gw_main.SP_Generate_IMSI_PU_Daily(GT_DB,1);
	END IF;	
	CALL gt_gw_main.SP_Sub_Generate_Pre_NBO_Daily(GT_DB,'opt_nbr_relation_gsm','GSM',
    'DATA_DATE|DATA_HOUR|SERVING_LAC|SERVING_BSC_ID|SERVING_CELL_ID|TARGET_LAC|TARGET_BSC_ID|TARGET_CELL_ID',
    'HO_ALL_CNT|HO_SUCC_CNT|HO_FAIL_CNT|HO_DROP_CNT|MEAS_RXLEV|MEAS_CNT|SERV_RXLEV|SERV_RXLEV_CNT|SERV_RXQUAL|SERV_RXQUAL_CNT','TARGET_ARFCN|TARGET_BSIC|SERVING_SITE_ID|SERVING_CELL_NAME|SERVING_FREQUENCY|SERVING_ARFCN|TARGET_SITE_ID|TARGET_CELL_NAME|TARGET_FREQUENCY');
	CALL GT_GW_MAIN.SP_Sub_Generate_Overshooting_Severity_GSM(GT_DB,GT_COVMO);    
    
	INSERT INTO gt_gw_main.SP_LOG VALUES(GT_DB,'SP_Generate_Report_Optimization_GSM',CONCAT('Done: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());		
END$$
DELIMITER ;
