DELIMITER $$
USE `gt_global_statistic`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Generate_Global_Statistic_Sub_subscriber_Aggr`(IN TECH_MASK TINYINT(2),IN WORKER_ID VARCHAR(10),IN FLAG TINYINT(2),IN exDate VARCHAR(10),IN DS_FLAG TINYINT(2),PENDING_FLAG TINYINT(2))
BEGIN
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE STEP_START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE SP_Process VARCHAR(100) DEFAULT NULL;
	DECLARE FIRSTDAY_OF_WEEK TINYINT(4) DEFAULT 6;
	DECLARE v_DATA_DATE VARCHAR(10) DEFAULT NULL;
	DECLARE v_DATA_HOUR TINYINT(2) DEFAULT NULL;
	DECLARE v_PU_ID MEDIUMINT(9) DEFAULT NULL;
	DECLARE v_TECH_MASK TINYINT(2) DEFAULT NULL;
	DECLARE v_i TINYINT(2) DEFAULT 1;
	DECLARE v_R_Max TINYINT(2) DEFAULT 0;
	DECLARE v_group_db_name VARCHAR(100) DEFAULT '';
	
	DECLARE UMTS_SUBSCRIBER_COLUMN_STR VARCHAR(1500) DEFAULT 
		'`DURATION`,
		`CALL_CNT` ,
		`AVG_LAST_RSCP`,
		`AVG_LAST_ECN0`,
		`REL_CAUSE1`,
		`REL_CAUSE2`,
		`REL_CAUSE3`,
		`REL_CAUSE4`,
		`REL_CAUSE5`,
		`REL_CAUSE6`,
		`REL_CAUSE7`,
		`REL_CAUSE8`,
		`REL_CAUSE9`,
		`REL_CAUSE10`,
		`REL_CAUSE11`,
		`REL_CAUSE12`,
		`REL_CAUSE13`,
		`REL_CAUSE14`,
		`REL_CAUSE15`,
		`REL_CAUSE16`,
		`REL_CAUSE17`';
		
	DECLARE UMTS_SUBSCRIBER_SUM_STR VARCHAR(5000) DEFAULT 
		'SUM(IFNULL(DURATION,0)) AS DURATION,
		SUM(1) AS CALL_CNT, 
		AVG(LAST_RSCP) AS LAST_RSCP,
		AVG(LAST_ECN0) AS LAST_ECN0,
		SUM(IF(DROP_REASON = 15,1,0)) AS REL_CAUSE1,
		SUM(IF(DROP_REASON = 83,1,0)) AS REL_CAUSE2,
		SUM(IF(DROP_REASON = 115,1,0)) AS REL_CAUSE3,
		SUM(IF(DROP_REASON = 46,1,0)) AS REL_CAUSE4,
		SUM(IF(DROP_REASON = 11,1,0)) AS REL_CAUSE5,
		SUM(IF(DROP_REASON = 114,1,0)) AS REL_CAUSE6,
		SUM(IF(DROP_REASON = 40,1,0)) AS REL_CAUSE7,
		SUM(IF(DROP_REASON = 41,1,0)) AS REL_CAUSE8,
		SUM(IF(DROP_REASON = 31,1,0)) AS REL_CAUSE9,
		SUM(IF(DROP_REASON = 14,1,0)) AS REL_CAUSE10,
		SUM(IF(DROP_REASON = 16,1,0)) AS REL_CAUSE11,
		SUM(IF(DROP_REASON = 2,1,0)) AS REL_CAUSE12,
		SUM(IF(DROP_REASON = 18,1,0)) AS REL_CAUSE13,
		SUM(IF(DROP_REASON = 113,1,0)) AS REL_CAUSE14,
		SUM(IF(DROP_REASON = 47,1,0)) AS REL_CAUSE15,
		SUM(IF(DROP_REASON = 28,1,0)) AS REL_CAUSE16,
		SUM(IF(IFNULL(DROP_REASON,1) NOT IN (15,83,115,46,11,114,40,41,31,14,16,2,18,113,47,28),1,0)) AS REL_CAUSE17';
	
	DECLARE UMTS_SUBSCRIBER_UPD_STR VARCHAR(10000) DEFAULT
		'RPT_TABLE_NAME.DURATION=RPT_TABLE_NAME.DURATION+VALUES(DURATION),
		 RPT_TABLE_NAME.CALL_CNT=RPT_TABLE_NAME.CALL_CNT+VALUES(CALL_CNT),
		RPT_TABLE_NAME.REL_CAUSE1=RPT_TABLE_NAME.REL_CAUSE1+VALUES(REL_CAUSE1),
		RPT_TABLE_NAME.REL_CAUSE2=RPT_TABLE_NAME.REL_CAUSE2+VALUES(REL_CAUSE2),
		RPT_TABLE_NAME.REL_CAUSE3=RPT_TABLE_NAME.REL_CAUSE3+VALUES(REL_CAUSE3),
		RPT_TABLE_NAME.REL_CAUSE4=RPT_TABLE_NAME.REL_CAUSE4+VALUES(REL_CAUSE4),
		RPT_TABLE_NAME.REL_CAUSE5=RPT_TABLE_NAME.REL_CAUSE5+VALUES(REL_CAUSE5),
		RPT_TABLE_NAME.REL_CAUSE6=RPT_TABLE_NAME.REL_CAUSE6+VALUES(REL_CAUSE6),
		RPT_TABLE_NAME.REL_CAUSE7=RPT_TABLE_NAME.REL_CAUSE7+VALUES(REL_CAUSE7),
		RPT_TABLE_NAME.REL_CAUSE8=RPT_TABLE_NAME.REL_CAUSE8+VALUES(REL_CAUSE8),
		RPT_TABLE_NAME.REL_CAUSE9=RPT_TABLE_NAME.REL_CAUSE9+VALUES(REL_CAUSE9),
		RPT_TABLE_NAME.REL_CAUSE10=RPT_TABLE_NAME.REL_CAUSE10+VALUES(REL_CAUSE10),
		RPT_TABLE_NAME.REL_CAUSE11=RPT_TABLE_NAME.REL_CAUSE11+VALUES(REL_CAUSE11),
		RPT_TABLE_NAME.REL_CAUSE12=RPT_TABLE_NAME.REL_CAUSE12+VALUES(REL_CAUSE12),
		RPT_TABLE_NAME.REL_CAUSE13=RPT_TABLE_NAME.REL_CAUSE13+VALUES(REL_CAUSE13),
		RPT_TABLE_NAME.REL_CAUSE14=RPT_TABLE_NAME.REL_CAUSE14+VALUES(REL_CAUSE14),
		RPT_TABLE_NAME.REL_CAUSE15=RPT_TABLE_NAME.REL_CAUSE15+VALUES(REL_CAUSE15),
		RPT_TABLE_NAME.REL_CAUSE16=RPT_TABLE_NAME.REL_CAUSE16+VALUES(REL_CAUSE16),
		RPT_TABLE_NAME.REL_CAUSE17=RPT_TABLE_NAME.REL_CAUSE17+VALUES(REL_CAUSE17)';
	
	DECLARE LTE_SUBSCRIBER_COLUMN_STR VARCHAR(1500) DEFAULT 
		'`DURATION`,
		`CALL_CNT`,
		`AVG_LAST_RSRP`,
		`AVG_LAST_RSRQ`,
		`REL_CAUSE1`,
		`REL_CAUSE2`,
		`REL_CAUSE3`,
		`REL_CAUSE4`,
		`REL_CAUSE5`,
		`REL_CAUSE6`,
		`REL_CAUSE7`
		';
		
	DECLARE LTE_SUBSCRIBER_SUM_STR VARCHAR(5000) DEFAULT 
		'SUM(IFNULL(DURATION,0)) AS DURATION,
		SUM(1) AS CALL_CNT, 
		AVG(LAST_RSRP) AS LAST_RSCP,
		AVG(LAST_RSRQ) AS LAST_ECN0,
		SUM(IF(DROP_REASON = 4,1,0)) AS REL_CAUSE1,
		SUM(IF(DROP_REASON = 50,1,0)) AS REL_CAUSE2,
		SUM(IF(DROP_REASON = 53,1,0)) AS REL_CAUSE3,
		SUM(IF(DROP_REASON = 52,1,0)) AS REL_CAUSE4,
		SUM(IF(DROP_REASON = 3,1,0)) AS REL_CAUSE5,
		SUM(IF(DROP_REASON = 7,1,0)) AS REL_CAUSE6,
		SUM(IF(IFNULL(DROP_REASON,1) NOT IN (4,50,53,52,3,7),1,0)) AS REL_CAUSE7
		';
	
	DECLARE LTE_SUBSCRIBER_UPD_STR VARCHAR(10000) DEFAULT
		'RPT_TABLE_NAME.DURATION=RPT_TABLE_NAME.DURATION+VALUES(DURATION),
		 RPT_TABLE_NAME.CALL_CNT=RPT_TABLE_NAME.CALL_CNT+VALUES(CALL_CNT),
		RPT_TABLE_NAME.REL_CAUSE1=RPT_TABLE_NAME.REL_CAUSE1+VALUES(REL_CAUSE1),
		RPT_TABLE_NAME.REL_CAUSE2=RPT_TABLE_NAME.REL_CAUSE2+VALUES(REL_CAUSE2),
		RPT_TABLE_NAME.REL_CAUSE3=RPT_TABLE_NAME.REL_CAUSE3+VALUES(REL_CAUSE3),
		RPT_TABLE_NAME.REL_CAUSE4=RPT_TABLE_NAME.REL_CAUSE4+VALUES(REL_CAUSE4),
		RPT_TABLE_NAME.REL_CAUSE5=RPT_TABLE_NAME.REL_CAUSE5+VALUES(REL_CAUSE5),
		RPT_TABLE_NAME.REL_CAUSE6=RPT_TABLE_NAME.REL_CAUSE6+VALUES(REL_CAUSE6),
		RPT_TABLE_NAME.REL_CAUSE7=RPT_TABLE_NAME.REL_CAUSE7+VALUES(REL_CAUSE7)';
	
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
		SET @SqlCmd=CONCAT('CREATE TABLE IF NOT EXISTS `gt_global_statistic`.`nw_error_log`
				(
				  `TABLE_NAME` VARCHAR(50) NOT NULL,
				  `SP_NAME` VARCHAR(50) DEFAULT NULL,
				  `INSERT_CMD` VARCHAR(100) DEFAULT NULL,
				  `INSERT_TIME` DATETIME DEFAULT NULL
				) ENGINE=MYISAM;');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
	
		INSERT INTO `gt_global_statistic`.`nw_error_log`(`TABLE_NAME`,`SP_NAME`,`INSERT_CMD`,`INSERT_TIME`)
		VALUES (@SOURCE_TABLE_NAME,
			'SP_Generate_Global_Statistic_Sub_subscriber_Aggr',
			CONCAT('Step ',@ERROR_FLAG,' error'),
			NOW());
		SET @SqlCmd=CONCAT('REPAIR TABLE ',@REPAIR_TABLE_NAME,';');				
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
	END;
	
  	CALL gt_gw_main.`SP_Sub_Set_Session_Param_LTE`('');
  	
	SET @global_db='gt_global_statistic';
			
	SET @FLAG_SUBSCRIBER_UMTS_DY=0;
	SET @FLAG_SUBSCRIBER_LTE_DY=0;
	INSERT INTO gt_gw_main.SP_LOG VALUES(@global_db,'SP_Generate_Global_Statistic_Sub_subscriber_Aggr',CONCAT(TECH_MASK,',',WORKER_ID,' START'), START_TIME);
	SET STEP_START_TIME := SYSDATE();
	IF FLAG IN (1,0) THEN 
		SET @SqlCmd=CONCAT('SELECT GROUP_CONCAT(DISTINCT CONCAT(`DATA_DATE`,'','',`DATA_HOUR`,'','',`TECH_MASK`) SEPARATOR ''|'' ) INTO @PU_STR_TECH
					FROM ',@global_db,'.tmp_table_call_cnt_',WORKER_ID,' 
					WHERE TECH_MASK=',TECH_MASK,';');
 		
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
		INSERT INTO gt_gw_main.SP_LOG VALUES(@global_db,'SP_Generate_Global_Statistic_Sub_subscriber_Aggr',@SqlCmd, START_TIME);		
		
		
		SET @SqlCmd=CONCAT('SELECT GROUP_CONCAT(DISTINCT `group_id` ORDER BY `group_id` SEPARATOR ''|'' ) INTO @REG_GROUP FROM ',@global_db,'.`usr_polygon_reg_3`;');
	
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
		
		SET @v_reg_m=1;
		SET @v_reg_Max=gt_covmo_csv_count(@REG_GROUP,'|');
		WHILE @v_reg_m <= @v_reg_Max DO
		BEGIN
			SET v_group_db_name=CONCAT('gt_global_statistic_g',gt_strtok(@REG_GROUP, @v_reg_m, '|'));
		
			SET v_i=1;
			SET v_R_Max=gt_covmo_csv_count(@PU_STR_TECH,'|');
			
			WHILE v_i <= v_R_Max DO
			BEGIN	
				SET v_DATA_DATE:=gt_covmo_csv_get(gt_strtok(@PU_STR_TECH, v_i, '|'),1);
				SET v_DATA_HOUR:=gt_covmo_csv_get(gt_strtok(@PU_STR_TECH, v_i, '|'),2);
				SET v_TECH_MASK:=gt_covmo_csv_get(gt_strtok(@PU_STR_TECH, v_i, '|'),3);
				SELECT `DAY_OF_WEEK`(v_DATA_DATE) INTO @DAY_OF_WEEK;
				SET @FIRST_DAY=gt_strtok(@DAY_OF_WEEK, 1, '|');
				SET @END_DAY=gt_strtok(@DAY_OF_WEEK, 2, '|');
				SET @DATE_WK=CONCAT(DATE_FORMAT(@FIRST_DAY,'%Y%m%d'),'_',DATE_FORMAT(@END_DAY,'%Y%m%d'));
				SET @DATE_MN=DATE_FORMAT(v_DATA_DATE,'%Y%m');
				SET @DATE_DY=DATE_FORMAT(v_DATA_DATE,'%Y%m%d');
				SET @EX_DATE=CONCAT(DATE_FORMAT(v_DATA_DATE,'%Y%m%d_'),v_DATA_HOUR,'_',WORKER_ID);
				
				SET @table_subscriber_umts_dy=CONCAT(v_group_db_name,'.table_subscriber_umts_400days');
				SET @table_subscriber_lte_dy=CONCAT(v_group_db_name,'.table_subscriber_lte_400days');
				
				IF v_TECH_MASK=2 THEN 		
					SET @SOURCE_TABLE_NAME=@table_subscriber_umts_dy;
					set @REPAIR_TABLE_NAME=@table_subscriber_umts_dy;
					SET @ERROR_FLAG='table_subscriber_umts_dy';
					SET @SqlCmd=CONCAT('INSERT INTO ',@table_subscriber_umts_dy,' 
							    (
								`IMSI`,
								`DATA_DATE`,
								`TILE_ID`,
								`CELL_ID`,
								',UMTS_SUBSCRIBER_COLUMN_STR,')
							SELECT
								`IMSI`,
								`DATA_DATE`,
								`TILE_ID`,
								`CELL_ID`,
								',UMTS_SUBSCRIBER_SUM_STR,' 
							FROM ',@global_db,'.tmp_subscriber_umts_',@EX_DATE,'
							GROUP BY `IMSI`,
								`DATA_DATE`,
								`TILE_ID`,
								`CELL_ID`
							ORDER BY NULL
							ON DUPLICATE KEY UPDATE
							',REPLACE(UMTS_SUBSCRIBER_UPD_STR,'RPT_TABLE_NAME',@table_subscriber_umts_dy),'
							;');
					PREPARE Stmt FROM @SqlCmd;
					EXECUTE Stmt;
					DEALLOCATE PREPARE Stmt; 
					
					SET @FLAG_SUBSCRIBER_UMTS_DY=1;
					INSERT INTO gt_gw_main.SP_LOG VALUES(@global_db,'SP_Generate_Global_Statistic_Sub_subscriber_Aggr',CONCAT('INSERT INTO ',@table_subscriber_umts_hr,', cost:',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' sec.'), NOW());
					SET STEP_START_TIME := SYSDATE();
				END IF;
				IF v_TECH_MASK=4 THEN 	
					SET @SOURCE_TABLE_NAME=@table_subscriber_lte_dy;
					SET @REPAIR_TABLE_NAME=@table_subscriber_lte_dy;
					SET @ERROR_FLAG='table_subscriber_lte_dy';	
					SET @SqlCmd=CONCAT('INSERT INTO ',@table_subscriber_lte_dy,' 
							    (
								`IMSI`,
								`DATA_DATE`,
								`TILE_ID`,
								`CELL_ID`,
								',LTE_SUBSCRIBER_COLUMN_STR,')
							SELECT
								`IMSI`,
								`DATA_DATE`,
								`TILE_ID`,
								`CELL_ID`,
								',LTE_SUBSCRIBER_SUM_STR,' 
							FROM ',@global_db,'.tmp_subscriber_lte_',@EX_DATE,'
							GROUP BY `DATA_DATE`,
								`IMSI`,
								`DATA_DATE`,
								`TILE_ID`,
								`CELL_ID`
							ORDER BY NULL
							ON DUPLICATE KEY UPDATE
							',REPLACE(LTE_SUBSCRIBER_UPD_STR,'RPT_TABLE_NAME',@table_subscriber_lte_dy),'
							;');
	
	 			
					PREPARE Stmt FROM @SqlCmd;
					EXECUTE Stmt;
					DEALLOCATE PREPARE Stmt; 
					
					SET @FLAG_SUBSCRIBER_LTE_DY=1;
					INSERT INTO gt_gw_main.SP_LOG VALUES(@global_db,'SP_Generate_Global_Statistic_Sub_subscriber_Aggr',CONCAT('INSERT INTO ',@table_subscriber_lte_hr,', cost:',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' sec.'), NOW());
					SET STEP_START_TIME := SYSDATE();
				END IF;
				SET v_i=v_i+1;
				INSERT INTO gt_gw_main.SP_LOG VALUES(@global_db,'SP_Generate_Global_Statistic_Sub_subscriber_Aggr',CONCAT(v_TECH_MASK,',',WORKER_ID,',',v_i), NOW());
			END;
			END WHILE;
			SET @v_reg_m=@v_reg_m+1;
		END;
		END WHILE;
		
		IF v_TECH_MASK=2 THEN 		
			SET @SqlCmd=CONCAT('DROP TABLE IF EXISTS ',@global_db,'.tmp_subscriber_umts_',@EX_DATE,';');
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;
			INSERT INTO gt_gw_main.SP_LOG VALUES(@global_db,'SP_Generate_Global_Statistic_Sub_subscriber_Aggr',CONCAT('UMTS DROP ',@global_db,'.tmp_subscriber_umts_',@EX_DATE,' ',WORKER_ID,' cost:',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' sec.'), NOW());
			SET STEP_START_TIME := SYSDATE();
						
			SET @SqlCmd=CONCAT('UPDATE `gt_global_statistic`.tmp_table_call_cnt_',WORKER_ID,' A
				SET 
				  A.`FLAG_SUBSCRIBER_DY` = ',@FLAG_SUBSCRIBER_UMTS_DY,'
				WHERE A.`TECH_MASK`=2
				;');
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;
		END IF;
		
		IF v_TECH_MASK=4 THEN 		
			SET @SqlCmd=CONCAT('DROP TABLE IF EXISTS ',@global_db,'.tmp_subscriber_lte_',@EX_DATE,';');
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;
			INSERT INTO gt_gw_main.SP_LOG VALUES(@global_db,'SP_Generate_Global_Statistic_Sub_subscriber_Aggr',CONCAT('LTE DROP ',@global_db,'.tmp_subscriber_lte_',@EX_DATE,' ',WORKER_ID,' cost:',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' sec.'), NOW());
			SET STEP_START_TIME := SYSDATE();
						
			SET @SqlCmd=CONCAT('UPDATE `gt_global_statistic`.tmp_table_call_cnt_',WORKER_ID,' A
				SET 
				  A.`FLAG_SUBSCRIBER_DY` = ',@FLAG_SUBSCRIBER_LTE_DY,'
				WHERE A.`TECH_MASK`=4
				;');
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;
		END IF;
		INSERT INTO gt_gw_main.SP_LOG VALUES(@global_db,'SP_Generate_Global_Statistic_Sub_subscriber_Aggr',CONCAT(v_DATA_DATE,',',v_DATA_HOUR,',',v_TECH_MASK,',',WORKER_ID,' Done: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());
	END IF;
END$$
DELIMITER ;
