DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_KPI_multi_split`(IN KPI_ID INT(11) ,IN SESSION_NAME VARCHAR(100),IN START_HOUR TINYINT(2),IN END_HOUR TINYINT(2), IN SOURCE_TYPE TINYINT(2), IN SERVICE TINYINT(2), IN WORKER_ID VARCHAR(10)
							,IN DATA_QUARTER VARCHAR(10),IN CELL_ID VARCHAR(100),IN TILE_ID VARCHAR(100)
							,IN IMSI MEDIUMTEXT,IN CLUSTER_ID VARCHAR(50),IN CALL_TYPE VARCHAR(50),IN CALL_STATUS VARCHAR(10)
							,IN INDOOR VARCHAR(5),IN MOVING VARCHAR(5)
							,IN CELL_INDOOR VARCHAR(10),IN FREQUENCY VARCHAR(100) ,IN UARFCN VARCHAR(300),IN CELL_LON VARCHAR(50),IN CELL_LAT VARCHAR(50)
							,IN MSISDN VARCHAR(1024),IN IMEI_NEW VARCHAR(5000),IN APN VARCHAR(1024)
							,IN FILTER VARCHAR(1024),IN PID INT(11),IN POS_KIND VARCHAR(10),IN SITE_ID VARCHAR(100)
							,IN MAKE_ID VARCHAR(1024),IN MODEL_ID VARCHAR(1024),IN POLYGON_STR VARCHAR(250),IN WITHDUMP TINYINT(2),IN SPECIAL_IMSI TINYINT(2),IN SUB_REGION_ID VARCHAR(100),IN ENODEB_ID VARCHAR(100),CELL_GID INT(10) 
							,IN GT_COVMO VARCHAR(20),TECH_NAME VARCHAR(10)
							,IN TMP_DB VARCHAR(100),IN TARGET_TABLE VARCHAR(100)
							,IN COLUMN_CRT_STR VARCHAR(3000),IN COLUMN_COL_STR VARCHAR(2500),IN SP_NAME VARCHAR(100),IN IMSI_GID SMALLINT(6),IN DS_AP_IP VARCHAR(20),IN DS_AP_PORT VARCHAR(5)
							,IN DS_AP_USER VARCHAR(32),IN DS_AP_PASSWORD VARCHAR(32)
							)
BEGIN
	DECLARE SP_Process VARCHAR(100) DEFAULT NULL;	
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE KPI_ERROR CONDITION FOR SQLSTATE '99999' ;
	DECLARE WORKER_ID VARCHAR(10) DEFAULT CONNECTION_ID();
	DECLARE IMSI_STR MEDIUMTEXT DEFAULT '';
	DECLARE IMSI_CONCAT MEDIUMTEXT DEFAULT '';
	DECLARE EXIT HANDLER FOR 1146	
	BEGIN
	
		SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS tmp_',WORKER_ID,';');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
		SELECT 'No Table' AS IsSuccess;	
		
		SELECT '{tech:”ALL ”, name:”SP-Report”, status:”2”,message_id: “null”, message: “SP_KPI_multi_split Failed Table does not exist. Check necessary table first”, log_path: “”}' AS message;
	END;		
		
	SET SESSION group_concat_max_len=@@max_allowed_packet;
				
	INSERT INTO gt_gw_main.sp_log VALUES('gt_gw_main','SP_KPI_multi_split',CONCAT(KPI_ID,' Start CREATE TABLE tbl_',SESSION_NAME), NOW());	
	
 	SET IMSI_STR=IMSI;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS tmp_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE tmp_',WORKER_ID,' (',COLUMN_CRT_STR,')'
			,' ENGINE=MYISAM DEFAULT CHARSET=latin1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('SELECT spider_bg_direct_sql(CONCAT(''CALL gt_gw_main.SP_KPI_multi_remote(''''',SESSION_NAME,''''',',KPI_ID,',',START_HOUR,',',END_HOUR,',',SOURCE_TYPE,',',SERVICE,','
				,CASE WHEN DATA_QUARTER='' THEN '''''''''' ELSE DATA_QUARTER END,','
				,CASE WHEN CELL_ID='' THEN '''''''''' ELSE CONCAT('''''',CELL_ID,'''''') END,','
				,CASE WHEN TILE_ID='' THEN '''''''''' ELSE CONCAT('''''',TILE_ID,'''''') END,','
				''''''''','
				,CASE WHEN CLUSTER_ID='' THEN '''''''''' ELSE CLUSTER_ID END,','
				,CASE WHEN CALL_TYPE='' THEN '''''''''' ELSE CONCAT('''''',CALL_TYPE,'''''') END,','
				,CASE WHEN CALL_STATUS='' THEN '''''''''' ELSE CONCAT('''''',CALL_STATUS,'''''') END,','
				,CASE WHEN INDOOR='' THEN '''''''''' ELSE CONCAT('''''',INDOOR,'''''') END,','
				,CASE WHEN MOVING='' THEN '''''''''' ELSE CONCAT('''''',MOVING,'''''') END,','
				,CASE WHEN CELL_INDOOR='' THEN '''''''''' ELSE CELL_INDOOR END,','
				,CASE WHEN FREQUENCY='' THEN '''''''''' ELSE CONCAT('''''',FREQUENCY,'''''') END,','
				,CASE WHEN UARFCN='' THEN '''''''''' ELSE CONCAT('''''',UARFCN,'''''') END,','
				,CASE WHEN CELL_LON='' THEN '''''''''' ELSE CELL_LON END,','
				,CASE WHEN CELL_LAT='' THEN '''''''''' ELSE CELL_LAT END,','
				,CASE WHEN MSISDN='' THEN '''''''''' ELSE CONCAT('''''',MSISDN,'''''') END,','
				,CASE WHEN IMEI_NEW='' THEN '''''''''' ELSE CONCAT('''''',IMEI_NEW,'''''') END,','
				,CASE WHEN APN='' THEN '''''''''' ELSE CONCAT('''''',APN,'''''') END,','
				,CASE WHEN FILTER='' THEN '''''''''' ELSE CONCAT('''''',REPLACE(FILTER,'''',''''''),'''''') END,','
				,CASE WHEN PID='' THEN '''''''''' ELSE PID END,','
				,CASE WHEN POS_KIND='' THEN '''''''''' ELSE CONCAT('''''',POS_KIND,'''''') END,','
				,CASE WHEN SITE_ID='' THEN '''''''''' ELSE CONCAT('''''',SITE_ID,'''''') END,','
				,CASE WHEN MAKE_ID='' THEN '''''''''' ELSE CONCAT('''''',MAKE_ID,'''''') END,','
				,CASE WHEN MODEL_ID='' THEN '''''''''' ELSE CONCAT('''''',MODEL_ID,'''''') END,','
				,CASE WHEN POLYGON_STR='' THEN '''''''''' ELSE CONCAT('''''',POLYGON_STR,'''''') END,','
				,CASE WHEN WITHDUMP='' THEN '''''0''''' ELSE WITHDUMP END,','
				,CASE WHEN GT_COVMO='' THEN '''''gt_covmo''''' ELSE CONCAT('''''',GT_COVMO,'''''') END,','
				,CASE WHEN TECH_NAME='' THEN '''''''''' ELSE CONCAT('''''',TECH_NAME,'''''') END,','
 				,CASE WHEN IMSI_STR='' THEN '''''''''' ELSE CONCAT('''''',IMSI_STR,'''''') END,','
				,CASE WHEN SPECIAL_IMSI='' THEN '''''''''' ELSE CONCAT('''''',SPECIAL_IMSI,'''''') END,','
				,CASE WHEN SUB_REGION_ID='' THEN '''''''''' ELSE CONCAT('''''',SUB_REGION_ID,'''''') END ,','
				,CASE WHEN ENODEB_ID='' THEN '''''''''' ELSE CONCAT('''''',ENODEB_ID,'''''') END ,','
				,CASE WHEN CELL_GID='' THEN '''''''''' ELSE CONCAT('''''',CELL_GID,'''''') END ,','
				,CASE WHEN IMSI_GID='' THEN '''''''''' ELSE CONCAT('''''',IMSI_GID,'''''') END
				,');'') 
	, ''tmp_',WORKER_ID,'''
	, CONCAT(''HOST ''''',DS_AP_IP,''''', PORT ''''',DS_AP_PORT,''''',USER ''''',DS_AP_USER,''''', PASSWORD ''''',DS_AP_PASSWORD,''''''')
	) INTO @bb ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	IF @bb=1 THEN 	
		SET @SqlCmd=CONCAT('INSERT INTO ',TARGET_TABLE,' 
		SELECT ',COLUMN_COL_STR,'
		FROM
		tmp_',WORKER_ID,' ;');
	
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
	ELSE
		INSERT INTO `gt_gw_main`.`tbl_rpt_error` (`PID`,`CreateTime`,`error_str`) VALUES (PID,NOW(),'Spider SP Execute Failed - SP_KPI_multi_split');
		SIGNAL KPI_ERROR
			SET MESSAGE_TEXT = 'Spider SP Execute Failed - SP_KPI_multi_split';
	END IF;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS tmp_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES('gt_gw_main','SP_KPI_multi_split',CONCAT(KPI_ID,' Done: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());	
	
END$$
DELIMITER ;
