DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Sub_Generate_Handset_LTE`(IN GT_DB VARCHAR(50),IN GT_COVMO VARCHAR(100))
BEGIN
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE WORKER_ID VARCHAR(10) DEFAULT CONNECTION_ID();
	
	DECLARE SH_EH VARCHAR(9) DEFAULT RIGHT(GT_DB,9);
	DECLARE GT_DATE VARCHAR(18) DEFAULT RIGHT(GT_DB,18);
	DECLARE STARTHOUR VARCHAR(2) DEFAULT SUBSTRING(RIGHT(GT_DB,18),10,2);
	DECLARE ENDHOUR VARCHAR(2) DEFAULT IF(SUBSTRING(RIGHT(GT_DB,18),15,2)='00','24',SUBSTRING(RIGHT(GT_DB,18),15,2));
	
  	INSERT INTO gt_gw_main.SP_LOG VALUES(GT_DB,'SP_Sub_Generate_Handset_LTE','Start', START_TIME);
  	
	SELECT REPLACE(GT_DB,SH_EH,'0000_0000') INTO GT_DB;
	
	INSERT INTO gt_gw_main.SP_LOG VALUES(GT_DB,'SP_Sub_Generate_Handset_LTE','rpt_with_handset', NOW());
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.rpt_with_handset_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,'.`rpt_with_handset_',WORKER_ID,'` (
					`MAKE_ID` SMALLINT(6) DEFAULT NULL,
					`MODEL_ID` MEDIUMINT(9) DEFAULT NULL,
					`MANUFACTURER` VARCHAR(32) DEFAULT NULL,
					`MODEL` VARCHAR(200) DEFAULT NULL,
					`CALL_TYPE` TINYINT(2) DEFAULT NULL,
					 MOVING TINYINT(4) NOT NULL,
					 INDOOR TINYINT(4) NOT NULL,
					`DATA_DATE` DATE DEFAULT NULL,
					`DATA_HOUR` SMALLINT(6) DEFAULT NULL,
					`DURATION` DECIMAL(45,4) DEFAULT NULL,
					`CALL_STATUS_2` DECIMAL(23,0) DEFAULT NULL,
					`CALL_STATUS_3` DECIMAL(23,0) DEFAULT NULL,
					`END_NON_BLOCK_CALL_CNT` DECIMAL(23,0) DEFAULT NULL,
					`RELEASE_CAUSE_Timer_Expiry_CNT` DECIMAL(23,0) DEFAULT NULL,
					`RELEASE_CAUSE_Eutran_generated_reason_CNT` DECIMAL(23,0) DEFAULT NULL,
					`RELEASE_CAUSE_HO_Related_release_CNT` DECIMAL(23,0) DEFAULT NULL,
					`RELEASE_CAUSE_Others_CNT` DECIMAL(23,0) DEFAULT NULL,
					`RELEASE_CAUSE_Resource_unavailable_CNT` DECIMAL(23,0) DEFAULT NULL,
					`RELEASE_CAUSE_Radio_connection_with_UE_Lost_CNT` DECIMAL(23,0) DEFAULT NULL,
					`RELEASE_CAUSE_Failure_in_the_radio_interface_procedure_CNT` DECIMAL(23,0) DEFAULT NULL,
					`DL_VOLUME_SUM` DOUBLE DEFAULT NULL,
					`UL_VOLUME_SUM` DOUBLE DEFAULT NULL,
					`POS_LAST_RSRP_SUM` DOUBLE DEFAULT NULL,
					`POS_LAST_RSRP_CNT` BIGINT(20) DEFAULT NULL,	
					`POS_LAST_RSRQ_SUM` DOUBLE DEFAULT NULL,
					`POS_LAST_RSRQ_CNT` BIGINT(20) DEFAULT NULL,
					`END_SINR_PUSCH_SUM` DOUBLE DEFAULT NULL,
					`END_SINR_PUCCH_SUM` DOUBLE DEFAULT NULL,
					`MO_SIGNALLING_CNT` MEDIUMINT(9) UNSIGNED DEFAULT NULL,
					`MO_ACCESS_CNT` MEDIUMINT(9) UNSIGNED DEFAULT NULL,
					`MO_DATA_CNT` MEDIUMINT(9) UNSIGNED DEFAULT NULL,
					`MT_ACCESS_CNT` MEDIUMINT(9) UNSIGNED DEFAULT NULL,
					`EMERGENCY_CNT` MEDIUMINT(9) UNSIGNED DEFAULT NULL,
					`HIGHPRIORITYACCESS_CNT` MEDIUMINT(9) UNSIGNED DEFAULT NULL,
					`LTE_UNKNOWN_CNT` MEDIUMINT(9) UNSIGNED DEFAULT NULL,
					`LTE_HANDOVER_SIGNALLING_CNT` MEDIUMINT(9) UNSIGNED DEFAULT NULL,
					`CNT` BIGINT(21) NOT NULL DEFAULT ''0'',
				PRIMARY KEY (`MAKE_ID`,`MODEL_ID`,`CALL_TYPE`,`MOVING`,`INDOOR`,`DATA_DATE`,`DATA_HOUR`)			
			) ENGINE=MYISAM DEFAULT CHARSET=utf8;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
 	
	
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.rpt_with_handset_',WORKER_ID,'
				(MAKE_ID,MODEL_ID,CALL_TYPE,MOVING,INDOOR,DATA_DATE,DATA_HOUR,
				DURATION,CALL_STATUS_2,CALL_STATUS_3,END_NON_BLOCK_CALL_CNT,
				RELEASE_CAUSE_Timer_Expiry_CNT,RELEASE_CAUSE_Eutran_generated_reason_CNT,
				RELEASE_CAUSE_HO_Related_release_CNT,RELEASE_CAUSE_Others_CNT,
				RELEASE_CAUSE_Resource_unavailable_CNT,RELEASE_CAUSE_Radio_connection_with_UE_Lost_CNT,
				RELEASE_CAUSE_Failure_in_the_radio_interface_procedure_CNT,DL_VOLUME_SUM,UL_VOLUME_SUM,
				POS_LAST_RSRP_SUM,POS_LAST_RSRP_CNT,POS_LAST_RSRQ_SUM,POS_LAST_RSRQ_CNT,END_SINR_PUSCH_SUM,END_SINR_PUCCH_SUM,
				MO_SIGNALLING_CNT,MO_ACCESS_CNT,MO_DATA_CNT,MT_ACCESS_CNT,EMERGENCY_CNT,HIGHPRIORITYACCESS_CNT,LTE_UNKNOWN_CNT,LTE_HANDOVER_SIGNALLING_CNT,
				CNT
				)
				SELECT 
					MAKE_ID,MODEL_ID,
					CALL_TYPE,
					IFNULL(MOVING,99) MOVING,
					IFNULL(INDOOR,99) INDOOR,
					DATA_DATE,DATA_HOUR,
					SUM(DURATION)/1000000 AS DURATION,
					SUM(IF(CALL_STATUS=2,1,0)) CALL_STATUS_2,
					SUM(IF(CALL_STATUS=3,1,0)) CALL_STATUS_3,
					SUM(IF(CALL_STATUS IN (1,2,4),1,0)) AS END_NON_BLOCK_CALL_CNT,
					SUM(IF(IFNULL(UE_CONTEXT_RELEASE_CAUSE_REQ,IF(UE_CONTEXT_RELEASE_CAUSE=4,NULL,UE_CONTEXT_RELEASE_CAUSE)) IN (2,9,10,54),1,0))  RELEASE_CAUSE_Timer_Expiry_CNT,
					SUM(IF(IFNULL(UE_CONTEXT_RELEASE_CAUSE_REQ,IF(UE_CONTEXT_RELEASE_CAUSE=4,NULL,UE_CONTEXT_RELEASE_CAUSE))=4,1,0))  RELEASE_CAUSE_Eutran_generated_reason_CNT,
					SUM(IF(IFNULL(UE_CONTEXT_RELEASE_CAUSE_REQ,IF(UE_CONTEXT_RELEASE_CAUSE=4,NULL,UE_CONTEXT_RELEASE_CAUSE)) IN(5,6,7,8,18),1,0))  RELEASE_CAUSE_HO_Related_release_CNT,
					SUM(IF(IFNULL(UE_CONTEXT_RELEASE_CAUSE_REQ,IF(UE_CONTEXT_RELEASE_CAUSE=4,NULL,UE_CONTEXT_RELEASE_CAUSE)) IN(11,12,14,15,16,28,51,62,63,65,70,73,74),1,0)) RELEASE_CAUSE_Others_CNT,
					SUM(IF(IFNULL(UE_CONTEXT_RELEASE_CAUSE_REQ,IF(UE_CONTEXT_RELEASE_CAUSE=4,NULL,UE_CONTEXT_RELEASE_CAUSE)) IN(13,26,41,60,61),1,0))  RELEASE_CAUSE_Resource_unavailable_CNT,
					SUM(IF(IFNULL(UE_CONTEXT_RELEASE_CAUSE_REQ,IF(UE_CONTEXT_RELEASE_CAUSE=4,NULL,UE_CONTEXT_RELEASE_CAUSE)) =22,1,0))  RELEASE_CAUSE_Radio_connection_with_UE_Lost_CNT,
					SUM(IF(IFNULL(UE_CONTEXT_RELEASE_CAUSE_REQ,IF(UE_CONTEXT_RELEASE_CAUSE=4,NULL,UE_CONTEXT_RELEASE_CAUSE))=27,1,0))  RELEASE_CAUSE_Failure_in_the_radio_interface_procedure_CNT,
					SUM(DL_VOLUME)/1024 AS DL_VOLUME_SUM, -- task#5208
					SUM(UL_VOLUME)/1024 AS UL_VOLUME_SUM, -- task#5208
					SUM(POS_LAST_RSRP) AS POS_LAST_RSRP_SUM,
					SUM(IF(POS_LAST_RSRP IS NOT NULL, 1,0)) POS_LAST_RSRP_CNT,
					SUM(POS_LAST_RSRQ) AS POS_LAST_RSRQ_SUM,
					SUM(IF(POS_LAST_RSRQ IS NOT NULL, 1,0)) POS_LAST_RSRQ_CNT,
					SUM(END_SINR_PUSCH) AS END_SINR_PUSCH_SUM,
					SUM(END_SINR_PUCCH) AS END_SINR_PUCCH_SUM,
					SUM(IF(RRC_REQUEST_TYPE=1,1,0)) AS MO_SIGNALLING_CNT,
					SUM(IF(RRC_REQUEST_TYPE=2,1,0)) AS MO_ACCESS_CNT,
					SUM(IF(RRC_REQUEST_TYPE=3,1,0)) AS MO_DATA_CNT,
					SUM(IF(RRC_REQUEST_TYPE=4,1,0)) AS MT_ACCESS_CNT,
					SUM(IF(RRC_REQUEST_TYPE=5,1,0)) AS EMERGENCY_CNT,
					SUM(IF(RRC_REQUEST_TYPE=6,1,0)) AS HIGHPRIORITYACCESS_CNT,
					SUM(IF(RRC_REQUEST_TYPE=7,1,0)) AS LTE_UNKNOWN_CNT,
					SUM(IF(RRC_REQUEST_TYPE=8,1,0)) AS LTE_HANDOVER_SIGNALLING_CNT,
					COUNT(*) CNT 
				FROM ',GT_DB,'.table_call_lte
				WHERE DATA_HOUR >= ',STARTHOUR,' AND DATA_HOUR < ',ENDHOUR,'
				GROUP BY `MAKE_ID`,
					`MODEL_ID`,
					`CALL_TYPE`,
					IFNULL(INDOOR,99),
					IFNULL(MOVING,99),
					`DATA_DATE`,
					`DATA_HOUR`
				ORDER BY NULL;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE INDEX `key_model` ON ',GT_DB,'.rpt_with_handset_',WORKER_ID,' (MAKE_ID,MODEL_ID);');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('UPDATE ',GT_DB,'.rpt_with_handset_',WORKER_ID,' A, ',GT_COVMO,'.dim_handset B
			SET A.MODEL = B.model,
			  A.MANUFACTURER = B.manufacturer
			WHERE A.MAKE_ID = B.MAKE_ID AND A.MODEL_ID = B.MODEL_ID;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.rpt_with_handset
			(MAKE_ID,MODEL_ID,MANUFACTURER,MODEL,CALL_TYPE,MOVING,INDOOR,DATA_DATE,DATA_HOUR,
			DURATION,CALL_STATUS_2,CALL_STATUS_3,END_NON_BLOCK_CALL_CNT,
			RELEASE_CAUSE_Timer_Expiry_CNT,RELEASE_CAUSE_Eutran_generated_reason_CNT,
			RELEASE_CAUSE_HO_Related_release_CNT,RELEASE_CAUSE_Others_CNT,
			RELEASE_CAUSE_Resource_unavailable_CNT,RELEASE_CAUSE_Radio_connection_with_UE_Lost_CNT,
			RELEASE_CAUSE_Failure_in_the_radio_interface_procedure_CNT,DL_VOLUME_SUM,UL_VOLUME_SUM,
			POS_LAST_RSRP_SUM,POS_LAST_RSRP_CNT,POS_LAST_RSRQ_SUM,POS_LAST_RSRQ_CNT,END_SINR_PUSCH_SUM,END_SINR_PUCCH_SUM,
			MO_SIGNALLING_CNT,MO_ACCESS_CNT,MO_DATA_CNT,MT_ACCESS_CNT,EMERGENCY_CNT,HIGHPRIORITYACCESS_CNT,LTE_UNKNOWN_CNT,LTE_HANDOVER_SIGNALLING_CNT,
			CNT
			)
		SELECT
			MAKE_ID,
			MODEL_ID,
			MANUFACTURER,
			MODEL,
			CALL_TYPE,
			MOVING,
			INDOOR,
			DATA_DATE,
			DATA_HOUR,
			IFNULL(DURATION,0) AS DURATION,
			IFNULL(CALL_STATUS_2,0) AS CALL_STATUS_2,
			IFNULL(CALL_STATUS_3,0) AS CALL_STATUS_3,
			IFNULL(END_NON_BLOCK_CALL_CNT,0) AS END_NON_BLOCK_CALL_CNT,
			IFNULL(RELEASE_CAUSE_Timer_Expiry_CNT,0) AS RELEASE_CAUSE_Timer_Expiry_CNT,
			IFNULL(RELEASE_CAUSE_Eutran_generated_reason_CNT,0) AS RELEASE_CAUSE_Eutran_generated_reason_CNT,
			IFNULL(RELEASE_CAUSE_HO_Related_release_CNT,0) AS RELEASE_CAUSE_HO_Related_release_CNT,
			IFNULL(RELEASE_CAUSE_Others_CNT,0) AS RELEASE_CAUSE_Others_CNT,
			IFNULL(RELEASE_CAUSE_Resource_unavailable_CNT,0) AS RELEASE_CAUSE_Resource_unavailable_CNT,
			IFNULL(RELEASE_CAUSE_Radio_connection_with_UE_Lost_CNT,0) AS RELEASE_CAUSE_Radio_connection_with_UE_Lost_CNT,
			IFNULL(RELEASE_CAUSE_Failure_in_the_radio_interface_procedure_CNT,0) AS RELEASE_CAUSE_Failure_in_the_radio_interface_procedure_CNT,
			IFNULL(DL_VOLUME_SUM,0) AS DL_VOLUME_SUM,
			IFNULL(UL_VOLUME_SUM,0) AS UL_VOLUME_SUM,
			IFNULL(POS_LAST_RSRP_SUM,0) AS POS_LAST_RSRP_SUM,
			IFNULL(POS_LAST_RSRP_CNT,0) AS POS_LAST_RSRP_CNT,			
			IFNULL(POS_LAST_RSRQ_SUM,0) AS POS_LAST_RSRQ_SUM,
			IFNULL(POS_LAST_RSRQ_CNT,0) AS POS_LAST_RSRQ_CNT,
			IFNULL(END_SINR_PUSCH_SUM,0) AS END_SINR_PUSCH_SUM,
			IFNULL(END_SINR_PUCCH_SUM,0) AS END_SINR_PUCCH_SUM,
			IFNULL(MO_SIGNALLING_CNT,0) AS MO_SIGNALLING_CNT,
			IFNULL(MO_ACCESS_CNT,0) AS MO_ACCESS_CNT,
			IFNULL(MO_DATA_CNT,0) AS MO_DATA_CNT,
			IFNULL(MT_ACCESS_CNT,0) AS MT_ACCESS_CNT,
			IFNULL(EMERGENCY_CNT,0) AS EMERGENCY_CNT,
			IFNULL(HIGHPRIORITYACCESS_CNT,0) AS HIGHPRIORITYACCESS_CNT,
			IFNULL(LTE_UNKNOWN_CNT,0) AS LTE_UNKNOWN_CNT,
			IFNULL(LTE_HANDOVER_SIGNALLING_CNT,0) AS LTE_HANDOVER_SIGNALLING_CNT,
			IFNULL(CNT,0) AS CNT
		FROM ',GT_DB,'.rpt_with_handset_',WORKER_ID,'
		ON DUPLICATE KEY UPDATE 
			',GT_DB,'.rpt_with_handset.DURATION=',GT_DB,'.rpt_with_handset.DURATION+VALUES(DURATION),
			',GT_DB,'.rpt_with_handset.CALL_STATUS_2=',GT_DB,'.rpt_with_handset.CALL_STATUS_2+VALUES(CALL_STATUS_2),
			',GT_DB,'.rpt_with_handset.CALL_STATUS_3=',GT_DB,'.rpt_with_handset.CALL_STATUS_3+VALUES(CALL_STATUS_3),
			',GT_DB,'.rpt_with_handset.END_NON_BLOCK_CALL_CNT=',GT_DB,'.rpt_with_handset.END_NON_BLOCK_CALL_CNT+VALUES(END_NON_BLOCK_CALL_CNT),
			',GT_DB,'.rpt_with_handset.RELEASE_CAUSE_Timer_Expiry_CNT=',GT_DB,'.rpt_with_handset.RELEASE_CAUSE_Timer_Expiry_CNT+VALUES(RELEASE_CAUSE_Timer_Expiry_CNT),
			',GT_DB,'.rpt_with_handset.RELEASE_CAUSE_Eutran_generated_reason_CNT=',GT_DB,'.rpt_with_handset.RELEASE_CAUSE_Eutran_generated_reason_CNT+VALUES(RELEASE_CAUSE_Eutran_generated_reason_CNT),
			',GT_DB,'.rpt_with_handset.RELEASE_CAUSE_HO_Related_release_CNT=',GT_DB,'.rpt_with_handset.RELEASE_CAUSE_HO_Related_release_CNT+VALUES(RELEASE_CAUSE_HO_Related_release_CNT),
			',GT_DB,'.rpt_with_handset.RELEASE_CAUSE_Others_CNT=',GT_DB,'.rpt_with_handset.RELEASE_CAUSE_Others_CNT+VALUES(RELEASE_CAUSE_Others_CNT),
			',GT_DB,'.rpt_with_handset.RELEASE_CAUSE_Resource_unavailable_CNT=',GT_DB,'.rpt_with_handset.RELEASE_CAUSE_Resource_unavailable_CNT+VALUES(RELEASE_CAUSE_Resource_unavailable_CNT),
			',GT_DB,'.rpt_with_handset.RELEASE_CAUSE_Radio_connection_with_UE_Lost_CNT=',GT_DB,'.rpt_with_handset.RELEASE_CAUSE_Radio_connection_with_UE_Lost_CNT+VALUES(RELEASE_CAUSE_Radio_connection_with_UE_Lost_CNT),
			',GT_DB,'.rpt_with_handset.RELEASE_CAUSE_Failure_in_the_radio_interface_procedure_CNT=',GT_DB,'.rpt_with_handset.RELEASE_CAUSE_Failure_in_the_radio_interface_procedure_CNT+VALUES(RELEASE_CAUSE_Failure_in_the_radio_interface_procedure_CNT),
			',GT_DB,'.rpt_with_handset.DL_VOLUME_SUM=',GT_DB,'.rpt_with_handset.DL_VOLUME_SUM+VALUES(DL_VOLUME_SUM),
			',GT_DB,'.rpt_with_handset.UL_VOLUME_SUM=',GT_DB,'.rpt_with_handset.UL_VOLUME_SUM+VALUES(UL_VOLUME_SUM),
			',GT_DB,'.rpt_with_handset.POS_LAST_RSRP_SUM=',GT_DB,'.rpt_with_handset.POS_LAST_RSRP_SUM+VALUES(POS_LAST_RSRP_SUM),
			',GT_DB,'.rpt_with_handset.POS_LAST_RSRP_CNT=',GT_DB,'.rpt_with_handset.POS_LAST_RSRP_CNT+VALUES(POS_LAST_RSRP_CNT),
			',GT_DB,'.rpt_with_handset.POS_LAST_RSRQ_SUM=',GT_DB,'.rpt_with_handset.POS_LAST_RSRQ_SUM+VALUES(POS_LAST_RSRQ_SUM),
			',GT_DB,'.rpt_with_handset.POS_LAST_RSRQ_CNT=',GT_DB,'.rpt_with_handset.POS_LAST_RSRQ_CNT+VALUES(POS_LAST_RSRQ_CNT),
			',GT_DB,'.rpt_with_handset.END_SINR_PUSCH_SUM=',GT_DB,'.rpt_with_handset.END_SINR_PUSCH_SUM+VALUES(END_SINR_PUSCH_SUM),
			',GT_DB,'.rpt_with_handset.END_SINR_PUCCH_SUM=',GT_DB,'.rpt_with_handset.END_SINR_PUCCH_SUM+VALUES(END_SINR_PUCCH_SUM),	
			',GT_DB,'.rpt_with_handset.MO_SIGNALLING_CNT=',GT_DB,'.rpt_with_handset.MO_SIGNALLING_CNT+VALUES(MO_SIGNALLING_CNT),	
			',GT_DB,'.rpt_with_handset.MO_ACCESS_CNT=',GT_DB,'.rpt_with_handset.MO_ACCESS_CNT+VALUES(MO_ACCESS_CNT),	
			',GT_DB,'.rpt_with_handset.MO_DATA_CNT=',GT_DB,'.rpt_with_handset.MO_DATA_CNT+VALUES(MO_DATA_CNT),	
			',GT_DB,'.rpt_with_handset.MT_ACCESS_CNT=',GT_DB,'.rpt_with_handset.MT_ACCESS_CNT+VALUES(MT_ACCESS_CNT),	
			',GT_DB,'.rpt_with_handset.EMERGENCY_CNT=',GT_DB,'.rpt_with_handset.EMERGENCY_CNT+VALUES(EMERGENCY_CNT),	
			',GT_DB,'.rpt_with_handset.HIGHPRIORITYACCESS_CNT=',GT_DB,'.rpt_with_handset.HIGHPRIORITYACCESS_CNT+VALUES(HIGHPRIORITYACCESS_CNT),	
			',GT_DB,'.rpt_with_handset.LTE_UNKNOWN_CNT=',GT_DB,'.rpt_with_handset.LTE_UNKNOWN_CNT+VALUES(LTE_UNKNOWN_CNT),	
			',GT_DB,'.rpt_with_handset.LTE_HANDOVER_SIGNALLING_CNT=',GT_DB,'.rpt_with_handset.LTE_HANDOVER_SIGNALLING_CNT+VALUES(LTE_HANDOVER_SIGNALLING_CNT),
			',GT_DB,'.rpt_with_handset.CNT=',GT_DB,'.rpt_with_handset.CNT+VALUES(CNT)
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS ',GT_DB,'.rpt_with_handset_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	INSERT INTO gt_gw_main.SP_LOG VALUES(GT_DB,'SP_Sub_Generate_Handset_LTE',CONCAT('Done: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());			
END$$
DELIMITER ;
