DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Sub_Generate_Dashboard_Summary_Tile`(IN GT_DB VARCHAR(100), IN KIND VARCHAR(20), IN VENDOR_SOURCE VARCHAR(20))
BEGIN
	DECLARE RNC_ID INT;
	DECLARE O_GT_DB VARCHAR(100) DEFAULT GT_DB;
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE PARTITION_ID INT DEFAULT SUBSTRING(RIGHT(GT_DB,18),10,2) ;
	DECLARE SH_EH VARCHAR(9) DEFAULT RIGHT(GT_DB,9);
	DECLARE GT_DATE VARCHAR(18) DEFAULT RIGHT(GT_DB,18);
	DECLARE STARTHOUR VARCHAR(2) DEFAULT SUBSTRING(RIGHT(GT_DB,18),10,2);
	DECLARE ENDHOUR VARCHAR(2) DEFAULT IF(SUBSTRING(RIGHT(GT_DB,18),15,2)='00','24',SUBSTRING(RIGHT(GT_DB,18),15,2));
	DECLARE RUN VARCHAR(20);
	DECLARE WORKER_ID VARCHAR(10) DEFAULT CONNECTION_ID();
	INSERT INTO GT_GW_MAIN.SP_LOG VALUES(O_GT_DB,'SP_Sub_Generate_Dashboard_Summary_Tile','INSERT INTO TABLE_DASHBOARD_SUMMARY_TILE ', NOW());
	CALL SP_SUB_SET_SESSION_PARAM(GT_DB);
 	SELECT GT_STRTOK(GT_DB,2,'_') INTO RNC_ID;     
	SELECT REPLACE(GT_DB,SH_EH,'0000_0000') INTO GT_DB;
	IF VENDOR_SOURCE = 'GW' THEN
		IF KIND = 'DAILY' THEN
			SET RUN = '_TMP';
		ELSEIF KIND = 'RERUN' THEN
			SET RUN = '_RERUN';
		END IF;
	ELSEIF VENDOR_SOURCE = 'AP' THEN
		SET RUN = '';
	END IF;
	SET @SQLCMD=CONCAT('ALTER TABLE ',GT_DB,RUN,'.table_dashboard_summary_tile TRUNCATE PARTITION H',PARTITION_ID,';');
	PREPARE STMT FROM @SQLCMD;
	EXECUTE STMT;
	DEALLOCATE PREPARE STMT;
	SET @SQLCMD=CONCAT('CREATE TABLE ',GT_DB,RUN,'.tmp_table_dashboard_summary_tile ENGINE=MYISAM 
				SELECT * FROM ',GT_DB,'.table_dashboard_summary_tile
				WHERE 1<>1;');
	PREPARE STMT FROM @SQLCMD;
	EXECUTE STMT;
	DEALLOCATE PREPARE STMT;
	SET @SQLCMD =CONCAT('INSERT INTO ',GT_DB,RUN,'.tmp_table_dashboard_summary_tile
				 (DATA_DATE,DATA_HOUR,TILE_ID,RNC_ID,NORMAL_CNT,DROP_CNT,BLOCK_CNT,CAll_CNT,RSCP,ECN0,RSCP_CNT,ECN0_CNT)
				 SELECT DATA_DATE,DATA_HOUR,TILE_ID, RNC_ID,
					 SUM(CASE CALL_STATUS WHEN 1 THEN 1 ELSE 0 END) NORMAL_CNT,
					 SUM(CASE CALL_STATUS WHEN 2 THEN 1 ELSE 0 END) DROP_CNT,
					 SUM(CASE CALL_STATUS WHEN 3 THEN 1 ELSE 0 END) BLOCK_CNT,		
					 SUM(CALL_CNT) CALL_CNT,
					 SUM(BEST_RSCP_1) RSCP,
					 SUM(BEST_ECN0_1) ECN0,
					 SUM(POS_LAST_RSCP_CNT) RSCP_CNT,
					 SUM(POS_LAST_RSCP_CNT) ECN0_CNT
				 FROM ',GT_DB,'.table_tile_end 
				 WHERE DATA_HOUR >= ',STARTHOUR,' AND DATA_HOUR < ',ENDHOUR,'
					AND TILE_ID IS NOT NULL 
					AND BEST_RSCP_1 IS NOT NULL AND BEST_ECN0_1 IS NOT NULL
				 GROUP BY DATA_DATE,DATA_HOUR,RNC_ID,TILE_ID;');
	PREPARE STMT FROM @SQLCMD;
	EXECUTE STMT;
	DEALLOCATE PREPARE STMT;
	INSERT INTO GT_GW_MAIN.SP_LOG VALUES(O_GT_DB,'SP_Sub_Generate_Dashboard_Summary_Tile','CREATE TEMP TABLE tmp_table_dashboard_summary_tile_pp FROM table_tile_fp ', NOW());
	SET @SQLCMD =CONCAT('DROP TABLE IF EXISTS ',GT_DB,RUN,'.tmp_table_dashboard_summary_tile_pp;');
	PREPARE STMT FROM @SQLCMD;
	EXECUTE STMT;
	DEALLOCATE PREPARE STMT;		
	SET @SQLCMD =CONCAT('CREATE TABLE ',GT_DB,RUN,'.tmp_table_dashboard_summary_tile_pp ENGINE=MYISAM 
				SELECT DATA_DATE,DATA_HOUR,TILE_ID, RNC_ID,
					SUM(PP_CNT) AS PP_CNT,
					SUM(POLLUTER) AS POLLUTER
				FROM ',GT_DB,'.table_tile_fp 
				WHERE DATA_HOUR >= ',STARTHOUR,' AND DATA_HOUR < ',ENDHOUR,'
				GROUP BY DATA_DATE,DATA_HOUR,RNC_ID,TILE_ID');	 	
	PREPARE STMT FROM @SQLCMD;
	EXECUTE STMT;
	DEALLOCATE PREPARE STMT;		
	INSERT INTO GT_GW_MAIN.SP_LOG VALUES(O_GT_DB,'SP_Sub_Generate_Dashboard_Summary_Tile','CREATE INDEX FOR tmp_table_dashboard_summary_tile_pp', NOW());
	SET @SQLCMD= CONCAT('ALTER TABLE ',GT_DB,RUN,'.tmp_table_dashboard_summary_tile_pp ADD PRIMARY KEY PK_TMP_TABLE_DASHBOARD_SUMMARY_TILE (DATA_DATE,DATA_HOUR,RNC_ID,TILE_ID)');
	PREPARE STMT FROM @SQLCMD;
	EXECUTE STMT;
	DEALLOCATE PREPARE STMT;
	INSERT INTO GT_GW_MAIN.SP_LOG VALUES(GT_DB,'SP_Sub_Generate_Dashboard_Summary_Tile','UPDATE tmp_table_dashboard_summary_tile WITH tmp_table_dashboard_summary_tile_pp ', NOW());	
	SET @SQLCMD =CONCAT(' UPDATE   ',GT_DB,RUN,'.tmp_table_dashboard_summary_tile A ,
				',GT_DB,RUN,'.tmp_table_dashboard_summary_tile_pp B
				SET A.PP_CNT=B.PP_CNT,
					A.POLLUTER=B.POLLUTER
				WHERE A.DATA_DATE=B.DATA_DATE	
				AND A.DATA_HOUR=B.DATA_HOUR
				AND A.RNC_ID=B.RNC_ID
				AND A.TILE_ID=B.TILE_ID;');
	PREPARE STMT FROM @SQLCMD;
	EXECUTE STMT;
	DEALLOCATE PREPARE STMT;
	SET @SQLCMD =CONCAT('INSERT INTO ',GT_DB,RUN,'.table_dashboard_summary_tile
				(`DATA_DATE`,`DATA_HOUR`,`RNC_ID`,`TILE_ID`,`POLLUTER`,`PP_CNT`,
					`NORMAL_CNT`,`DROP_CNT`,`BLOCK_CNT`,`CAll_CNT`,`RSCP`,`ECN0`
					,RSCP_CNT,ECN0_CNT)
				 SELECT `DATA_DATE`,`DATA_HOUR`,`RNC_ID`,`TILE_ID`,`POLLUTER`,`PP_CNT`,
					`NORMAL_CNT`,`DROP_CNT`,`BLOCK_CNT`,`CAll_CNT`,`RSCP`,`ECN0`
					,RSCP_CNT,ECN0_CNT
				 FROM ',GT_DB,RUN,'.tmp_table_dashboard_summary_tile;');
	PREPARE STMT FROM @SQLCMD;
	EXECUTE STMT;
	DEALLOCATE PREPARE STMT;
	
	SET @SQLCMD =CONCAT('DROP TABLE IF EXISTS  ',GT_DB,RUN,'.tmp_table_dashboard_summary_tile_pp;');
	PREPARE STMT FROM @SQLCMD;
	EXECUTE STMT;
	DEALLOCATE PREPARE STMT;
	
	SET @SQLCMD =CONCAT('DROP TABLE IF EXISTS  ',GT_DB,RUN,'.tmp_table_dashboard_summary_tile ');
	PREPARE STMT FROM @SQLCMD;
	EXECUTE STMT;
	DEALLOCATE PREPARE STMT;
	
	INSERT INTO GT_GW_MAIN.SP_LOG VALUES(O_GT_DB,'SP_Sub_Generate_Dashboard_Summary_Tile',CONCAT('DONE: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' SECONDS.'), NOW());
END$$
DELIMITER ;
