DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Sub_Generate_FP_PARALLEL`(IN RPT_TBL_NAME VARCHAR(100),IN TMP_GT_DB VARCHAR(100),IN GT_DB VARCHAR(100),SN TINYINT(2),INSERT_FLAG TINYINT(2))
BEGIN
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE STEP_START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE WORKER_ID VARCHAR(10) DEFAULT CONNECTION_ID();	
	DECLARE KEY_COLUMN_STR VARCHAR(1500) DEFAULT '';
	DECLARE GROUP_STR VARCHAR(1500) DEFAULT '';
	DECLARE GROUP_DEF_STR VARCHAR(1500) DEFAULT '';
	DECLARE v_DATA_HOUR VARCHAR(1500) DEFAULT SUBSTRING(gt_strtok(TMP_GT_DB,4,'_'),1,2);
	DECLARE COLUMN_STR VARCHAR(2000) DEFAULT 
		'FP_RSCP_1,
		FP_ECN0_1,
		FP_RSCP_1_MED,
		FP_ECN0_1_MED,
		FP_RSCP,
		FP_ECN0,
		FP_RSCP_MED,
		FP_ECN0_MED,
		MMR_CNT,
		PILOT_CNT,
		PP_CNT,
		POLLUTER,
		POLLUTER_MAX,
		RSCP_GAP,
		BEST_CNT,
		ACTIVE_CNT,
		MONITOR_CNT,
		MAX_AS_CNT,
		TOTAL_AS_CNT,
		NON_SERVING_PILOT_DOMINANCE,
		EMPHASIZE_PILOT_DOMINANCE,
		BEST_SERVER_RSCP,
		TILE_INTERFERED_CNT,
		CELL_INTERFERED_CNT,
		L3_e1a,
		L3_e1b,
		L3_e1c,
		L3_e1d,
		L3_e1e,
		L3_e1f,
		L3_e2a,
		L3_e2b,
		L3_e2d,
		L3_e2f,
		L3_e3a,
		L3_e4a,
		L3_e4b,
		L3_e6a,
		L3_e6b,
		PSC,
		FP_RSCP_1_POW,
		FP_RSSI_1_POW,
		RSCP_GAP_CNT,
		NON_SERVING_PILOT_DOMINANCE_CNT,
		EMPHASIZE_PILOT_DOMINANCE_CNT,
		BEST_SERVER_RSCP_CNT,
		TOTAL_ACTIVE_CNT,
		DURATION,
		CS_DURATION,
		UL_THROUGHPUT_SUM,
		UL_TRAFFIC_VOLUME,
		UL_THROUGHPUT_EVENT_CNT,
		DL_THROUGHPUT_SUM,
		DL_TRAFFIC_VOLUME,
		DL_THROUGHPUT_EVENT_CNT,
		UL_THROUGHPUT_MAX,
		DL_THROUGHPUT_MAX,
		SHO_ATTEMPT,
		SHO_SUCC,
		SHO_FAIL,
		SOHO_ATTEMPT,
		SOHO_SUCC,
		SOHO_FAIL,
		IFHO_ATTEMPT,
		IFHO_SUCC,
		IFHO_FAIL,
		RRC_FAILURE_CNT,
		NBAP_FAILURE_CNT,
		RANAP_FAILURE_CNT,
		OVER_LOC_CNT,
		NON_OVER_LOC_CNT,
		MAINBEAM_OVER_LOC_CNT,
		MAINBEAM_NON_OVER_LOC_CNT,
		BEST_OVER_LOC_CNT,
		BEST_NON_OVER_LOC_CNT,
		BEST_MAINBEAM_OVER_LOC_CNT,
		BEST_MAINBEAM_NON_OVER_LOC_CNT,
		TILE_MAINBEAM,
		BEST_RSCP_LOWER_SUM,
		BEST_RSCP_LOWER_CNT,
		BEST_ECN0_LOWER_SUM,
		BEST_ECN0_LOWER_CNT
		';
	DECLARE COLUMN_IFNULL_STR VARCHAR(5000) DEFAULT 
		'IFNULL(FP_RSCP_1,0) AS FP_RSCP_1,
		IFNULL(FP_ECN0_1,0) AS FP_ECN0_1,
		IFNULL(FP_RSCP_1_MED,0) AS FP_RSCP_1_MED,
		IFNULL(FP_ECN0_1_MED,0) AS FP_ECN0_1_MED,
		IFNULL(FP_RSCP,0) AS FP_RSCP,
		IFNULL(FP_ECN0,0) AS FP_ECN0,
		IFNULL(FP_RSCP_MED,0) AS FP_RSCP_MED,
		IFNULL(FP_ECN0_MED,0) AS FP_ECN0_MED,
		IFNULL(MMR_CNT,0) AS MMR_CNT,
		IFNULL(PILOT_CNT,0) AS PILOT_CNT,
		IFNULL(PP_CNT,0) AS PP_CNT,
		IFNULL(POLLUTER,0) AS POLLUTER,
		IFNULL(POLLUTER_MAX,0) AS POLLUTER_MAX,
		IFNULL(RSCP_GAP,0) AS RSCP_GAP,
		IFNULL(BEST_CNT,0) AS BEST_CNT,
		IFNULL(ACTIVE_CNT,0) AS ACTIVE_CNT,
		IFNULL(MONITOR_CNT,0) AS MONITOR_CNT,
		IFNULL(MAX_AS_CNT,0) AS MAX_AS_CNT,
		IFNULL(TOTAL_AS_CNT,0) AS  TOTAL_AS_CNT,
		IFNULL(NON_SERVING_PILOT_DOMINANCE,0) AS NON_SERVING_PILOT_DOMINANCE,
		IFNULL(EMPHASIZE_PILOT_DOMINANCE,0) AS EMPHASIZE_PILOT_DOMINANCE,
		IFNULL(BEST_SERVER_RSCP,0) AS BEST_SERVER_RSCP,
		IFNULL(TILE_INTERFERED_CNT,0) AS TILE_INTERFERED_CNT,
		IFNULL(CELL_INTERFERED_CNT,0) AS CELL_INTERFERED_CNT,
		IFNULL(L3_e1a,0) AS L3_e1a,
		IFNULL(L3_e1b,0) AS L3_e1b,
		IFNULL(L3_e1c,0) AS L3_e1c,
		IFNULL(L3_e1d,0) AS L3_e1d,
		IFNULL(L3_e1e,0) AS L3_e1e,
		IFNULL(L3_e1f,0) AS L3_e1f,
		IFNULL(L3_e2a,0) AS L3_e2a,
		IFNULL(L3_e2b,0) AS L3_e2b,
		IFNULL(L3_e2d,0) AS L3_e2d,
		IFNULL(L3_e2f,0) AS L3_e2f,
		IFNULL(L3_e3a,0) AS L3_e3a,
		IFNULL(L3_e4a,0) AS L3_e4a,
		IFNULL(L3_e4b,0) AS L3_e4b,
		IFNULL(L3_e6a,0) AS L3_e6a,
		IFNULL(L3_e6b,0) AS L3_e6b,
		IFNULL(PSC,0) AS PSC,
		IFNULL(FP_RSCP_1_POW,0) AS FP_RSCP_1_POW,
		IFNULL(FP_RSSI_1_POW,0) AS FP_RSSI_1_POW,
		IFNULL(RSCP_GAP_CNT,0) AS RSCP_GAP_CNT,
		IFNULL(NON_SERVING_PILOT_DOMINANCE_CNT,0) AS NON_SERVING_PILOT_DOMINANCE_CNT,
		IFNULL(EMPHASIZE_PILOT_DOMINANCE_CNT,0) AS EMPHASIZE_PILOT_DOMINANCE_CNT,
		IFNULL(BEST_SERVER_RSCP_CNT,0) AS BEST_SERVER_RSCP_CNT,
		IFNULL(TOTAL_ACTIVE_CNT,0) AS TOTAL_ACTIVE_CNT,
		IFNULL(DURATION,0) AS DURATION,
		IFNULL(CS_DURATION,0) AS CS_DURATION,
		IFNULL(UL_THROUGHPUT_SUM,0) AS UL_THROUGHPUT_SUM,
		IFNULL(UL_TRAFFIC_VOLUME,0) AS UL_TRAFFIC_VOLUME,
		IFNULL(UL_THROUGHPUT_EVENT_CNT,0) AS UL_THROUGHPUT_EVENT_CNT,
		IFNULL(DL_THROUGHPUT_SUM,0) AS DL_THROUGHPUT_SUM,
		IFNULL(DL_TRAFFIC_VOLUME,0) AS DL_TRAFFIC_VOLUME,
		IFNULL(DL_THROUGHPUT_EVENT_CNT,0) AS DL_THROUGHPUT_EVENT_CNT,
		IFNULL(UL_THROUGHPUT_MAX,0) AS UL_THROUGHPUT_MAX,
		IFNULL(DL_THROUGHPUT_MAX,0) AS DL_THROUGHPUT_MAX,
		IFNULL(SHO_ATTEMPT,0) AS SHO_ATTEMPT,
		IFNULL(SHO_SUCC,0) AS SHO_SUCC,
		IFNULL(SHO_FAIL,0) AS SHO_FAIL,
		IFNULL(SOHO_ATTEMPT,0) AS SOHO_ATTEMPT,
		IFNULL(SOHO_SUCC,0) AS SOHO_SUCC,
		IFNULL(SOHO_FAIL,0) AS SOHO_FAIL,
		IFNULL(IFHO_ATTEMPT,0) AS IFHO_ATTEMPT,
		IFNULL(IFHO_SUCC,0) AS IFHO_SUCC,
		IFNULL(IFHO_FAIL,0) AS IFHO_FAIL,
		IFNULL(RRC_FAILURE_CNT,0) AS RRC_FAILURE_CNT,
		IFNULL(NBAP_FAILURE_CNT,0) AS NBAP_FAILURE_CNT,
		IFNULL(RANAP_FAILURE_CNT,0) AS RANAP_FAILURE_CNT,
		OVER_LOC_CNT AS OVER_LOC_CNT,
		NON_OVER_LOC_CNT AS NON_OVER_LOC_CNT,
		MAINBEAM_OVER_LOC_CNT AS MAINBEAM_OVER_LOC_CNT,
		MAINBEAM_NON_OVER_LOC_CNT AS MAINBEAM_NON_OVER_LOC_CNT,
		BEST_OVER_LOC_CNT AS BEST_OVER_LOC_CNT,
		BEST_NON_OVER_LOC_CNT AS BEST_NON_OVER_LOC_CNT,
		BEST_MAINBEAM_OVER_LOC_CNT AS BEST_MAINBEAM_OVER_LOC_CNT,
		BEST_MAINBEAM_NON_OVER_LOC_CNT AS BEST_MAINBEAM_NON_OVER_LOC_CNT,
		TILE_MAINBEAM AS TILE_MAINBEAM,
		IFNULL(BEST_RSCP_LOWER_SUM,0) AS BEST_RSCP_LOWER_SUM,
		IFNULL(BEST_RSCP_LOWER_CNT,0) AS BEST_RSCP_LOWER_CNT,
		IFNULL(BEST_ECN0_LOWER_SUM,0) AS BEST_ECN0_LOWER_SUM,
		IFNULL(BEST_ECN0_LOWER_CNT,0) AS BEST_ECN0_LOWER_CNT
	';
	DECLARE COLUMN_SUM_STR VARCHAR(5000) DEFAULT 
		'IFNULL(SUM(FP_RSCP_1),0) AS FP_RSCP_1,
		IFNULL(SUM(FP_ECN0_1),0) AS FP_ECN0_1,
		NULL AS FP_RSCP_1_MED,
		NULL AS FP_ECN0_1_MED,
		IFNULL(SUM(FP_RSCP),0) AS FP_RSCP,
		IFNULL(SUM(FP_ECN0),0) AS FP_ECN0,
		NULL AS FP_RSCP_MED,
		NULL AS FP_ECN0_MED,
		IFNULL(SUM(MMR_CNT),0) AS MMR_CNT,
		IFNULL(SUM(PILOT_CNT),0) AS PILOT_CNT,
		IFNULL(SUM(PP_CNT),0) AS PP_CNT,
		IFNULL(SUM(POLLUTER),0) AS POLLUTER,
		IFNULL(MAX(POLLUTER_MAX),0) AS POLLUTER_MAX,
		IFNULL(SUM(RSCP_GAP),0) AS RSCP_GAP,
		IFNULL(SUM(BEST_CNT),0) AS BEST_CNT,
		IFNULL(SUM(ACTIVE_CNT),0) AS ACTIVE_CNT,
		IFNULL(SUM(MONITOR_CNT),0) AS MONITOR_CNT,
		IFNULL(MAX(MAX_AS_CNT),0) AS MAX_AS_CNT,
		IFNULL(SUM(TOTAL_AS_CNT),0) AS TOTAL_AS_CNT,
		IFNULL(SUM(NON_SERVING_PILOT_DOMINANCE),0) AS NON_SERVING_PILOT_DOMINANCE,
		IFNULL(SUM(EMPHASIZE_PILOT_DOMINANCE),0) AS EMPHASIZE_PILOT_DOMINANCE,
		IFNULL(SUM(BEST_SERVER_RSCP),0) AS BEST_SERVER_RSCP,
		IFNULL(SUM(TILE_INTERFERED_CNT),0) AS TILE_INTERFERED_CNT,
		IFNULL(SUM(CELL_INTERFERED_CNT),0) AS CELL_INTERFERED_CNT,
		IFNULL(SUM(L3_e1a),0) AS L3_e1a,
		IFNULL(SUM(L3_e1b),0) AS L3_e1b,
		IFNULL(SUM(L3_e1c),0) AS L3_e1c,
		IFNULL(SUM(L3_e1d),0) AS L3_e1d,
		IFNULL(SUM(L3_e1e),0) AS L3_e1e,
		IFNULL(SUM(L3_e1f),0) AS L3_e1f,
		IFNULL(SUM(L3_e2a),0) AS L3_e2a,
		IFNULL(SUM(L3_e2b),0) AS L3_e2b,
		IFNULL(SUM(L3_e2d),0) AS L3_e2d,
		IFNULL(SUM(L3_e2f),0) AS L3_e2f,
		IFNULL(SUM(L3_e3a),0) AS L3_e3a,
		IFNULL(SUM(L3_e4a),0) AS L3_e4a,
		IFNULL(SUM(L3_e4b),0) AS L3_e4b,
		IFNULL(SUM(L3_e6a),0) AS L3_e6a,
		IFNULL(SUM(L3_e6b),0) AS L3_e6b,
		IFNULL(MAX(PSC),0) AS PSC,
		IFNULL(SUM(FP_RSCP_1_POW),0) AS FP_RSCP_1_POW,
		IFNULL(SUM(FP_RSSI_1_POW),0) AS FP_RSSI_1_POW,
		IFNULL(SUM(RSCP_GAP_CNT),0) AS RSCP_GAP_CNT,
		IFNULL(SUM(NON_SERVING_PILOT_DOMINANCE_CNT),0) AS NON_SERVING_PILOT_DOMINANCE_CNT,
		IFNULL(SUM(EMPHASIZE_PILOT_DOMINANCE_CNT),0) AS EMPHASIZE_PILOT_DOMINANCE_CNT,
		IFNULL(SUM(BEST_SERVER_RSCP_CNT),0) AS BEST_SERVER_RSCP_CNT,
		IFNULL(SUM(TOTAL_ACTIVE_CNT),0) AS TOTAL_ACTIVE_CNT,
		IFNULL(SUM(DURATION),0) AS DURATION,
		IFNULL(SUM(CS_DURATION),0) AS CS_DURATION,
		IFNULL(SUM(UL_THROUGHPUT_SUM),0) AS UL_THROUGHPUT_SUM,
		IFNULL(SUM(UL_TRAFFIC_VOLUME),0) AS UL_TRAFFIC_VOLUME,
		IFNULL(SUM(UL_THROUGHPUT_EVENT_CNT),0) AS UL_THROUGHPUT_EVENT_CNT,
		IFNULL(SUM(DL_THROUGHPUT_SUM),0) AS DL_THROUGHPUT_SUM,
		IFNULL(SUM(DL_TRAFFIC_VOLUME),0) AS DL_TRAFFIC_VOLUME,
		IFNULL(SUM(DL_THROUGHPUT_EVENT_CNT),0) AS DL_THROUGHPUT_EVENT_CNT,
		IFNULL(MAX(UL_THROUGHPUT_MAX),0) AS UL_THROUGHPUT_MAX,
		IFNULL(MAX(DL_THROUGHPUT_MAX),0) AS DL_THROUGHPUT_MAX,
		IFNULL(SUM(SHO_ATTEMPT),0) AS SHO_ATTEMPT,
		IFNULL(SUM(SHO_SUCC),0) AS SHO_SUCC,
		IFNULL(SUM(SHO_FAIL),0) AS SHO_FAIL,
		IFNULL(SUM(SOHO_ATTEMPT),0) AS SOHO_ATTEMPT,
		IFNULL(SUM(SOHO_SUCC),0) AS SOHO_SUCC,
		IFNULL(SUM(SOHO_FAIL),0) AS SOHO_FAIL,
		IFNULL(SUM(IFHO_ATTEMPT),0) AS IFHO_ATTEMPT,
		IFNULL(SUM(IFHO_SUCC),0) AS IFHO_SUCC,
		IFNULL(SUM(IFHO_FAIL),0) AS IFHO_FAIL,
		IFNULL(SUM(RRC_FAILURE_CNT),0) AS RRC_FAILURE_CNT,
		IFNULL(SUM(NBAP_FAILURE_CNT),0) AS NBAP_FAILURE_CNT,
		IFNULL(SUM(RANAP_FAILURE_CNT),0) AS RANAP_FAILURE_CNT,
		SUM(OVER_LOC_CNT) AS OVER_LOC_CNT,
		SUM(NON_OVER_LOC_CNT) AS NON_OVER_LOC_CNT,
		SUM(MAINBEAM_OVER_LOC_CNT) AS MAINBEAM_OVER_LOC_CNT,
		SUM(MAINBEAM_NON_OVER_LOC_CNT) AS MAINBEAM_NON_OVER_LOC_CNT,
		SUM(BEST_OVER_LOC_CNT) AS BEST_OVER_LOC_CNT,
		SUM(BEST_NON_OVER_LOC_CNT) AS BEST_NON_OVER_LOC_CNT,
		SUM(BEST_MAINBEAM_OVER_LOC_CNT) AS BEST_MAINBEAM_OVER_LOC_CNT,
		SUM(BEST_MAINBEAM_NON_OVER_LOC_CNT) AS BEST_MAINBEAM_NON_OVER_LOC_CNT,
		MAX(TILE_MAINBEAM) AS TILE_MAINBEAM,
		IFNULL(SUM(BEST_RSCP_LOWER_SUM),0) AS BEST_RSCP_LOWER_SUM,
		IFNULL(SUM(BEST_RSCP_LOWER_CNT),0) AS BEST_RSCP_LOWER_CNT,
		IFNULL(SUM(BEST_ECN0_LOWER_SUM),0) AS BEST_ECN0_LOWER_SUM,
		IFNULL(SUM(BEST_ECN0_LOWER_CNT),0) AS BEST_ECN0_LOWER_CNT
	';
	DECLARE COLUMN_UPD_STR VARCHAR(10000) DEFAULT 
		'RPT_TABLE_NAME.FP_RSCP_1=RPT_TABLE_NAME.FP_RSCP_1+VALUES(FP_RSCP_1),
		RPT_TABLE_NAME.FP_ECN0_1=RPT_TABLE_NAME.FP_ECN0_1+VALUES(FP_ECN0_1),
		RPT_TABLE_NAME.FP_RSCP_1_MED=NULL,
		RPT_TABLE_NAME.FP_ECN0_1_MED=NULL,
		RPT_TABLE_NAME.FP_RSCP=RPT_TABLE_NAME.FP_RSCP+VALUES(FP_RSCP),
		RPT_TABLE_NAME.FP_ECN0=RPT_TABLE_NAME.FP_ECN0+VALUES(FP_ECN0),
		RPT_TABLE_NAME.FP_RSCP_MED=NULL,
		RPT_TABLE_NAME.FP_ECN0_MED=NULL,
		RPT_TABLE_NAME.MMR_CNT=RPT_TABLE_NAME.MMR_CNT+VALUES(MMR_CNT),
		RPT_TABLE_NAME.PILOT_CNT=RPT_TABLE_NAME.PILOT_CNT+VALUES(PILOT_CNT),
		RPT_TABLE_NAME.PP_CNT=RPT_TABLE_NAME.PP_CNT+VALUES(PP_CNT),
		RPT_TABLE_NAME.POLLUTER=RPT_TABLE_NAME.POLLUTER+VALUES(POLLUTER),
		RPT_TABLE_NAME.POLLUTER_MAX=IF(RPT_TABLE_NAME.POLLUTER_MAX > VALUES(POLLUTER_MAX),RPT_TABLE_NAME.POLLUTER_MAX,VALUES(POLLUTER_MAX)),
		RPT_TABLE_NAME.RSCP_GAP=RPT_TABLE_NAME.RSCP_GAP+VALUES(RSCP_GAP),
		RPT_TABLE_NAME.BEST_CNT=RPT_TABLE_NAME.BEST_CNT+VALUES(BEST_CNT),
		RPT_TABLE_NAME.ACTIVE_CNT=RPT_TABLE_NAME.ACTIVE_CNT+VALUES(ACTIVE_CNT),
		RPT_TABLE_NAME.MONITOR_CNT=RPT_TABLE_NAME.MONITOR_CNT+VALUES(MONITOR_CNT),
		RPT_TABLE_NAME.MAX_AS_CNT=IF(RPT_TABLE_NAME.MAX_AS_CNT > VALUES(MAX_AS_CNT),RPT_TABLE_NAME.MAX_AS_CNT,VALUES(MAX_AS_CNT)),
		RPT_TABLE_NAME.TOTAL_AS_CNT=RPT_TABLE_NAME.TOTAL_AS_CNT+VALUES(TOTAL_AS_CNT),
		RPT_TABLE_NAME.NON_SERVING_PILOT_DOMINANCE=RPT_TABLE_NAME.NON_SERVING_PILOT_DOMINANCE+VALUES(NON_SERVING_PILOT_DOMINANCE),
		RPT_TABLE_NAME.EMPHASIZE_PILOT_DOMINANCE=RPT_TABLE_NAME.EMPHASIZE_PILOT_DOMINANCE+VALUES(EMPHASIZE_PILOT_DOMINANCE),
		RPT_TABLE_NAME.BEST_SERVER_RSCP=RPT_TABLE_NAME.BEST_SERVER_RSCP+VALUES(BEST_SERVER_RSCP),
		RPT_TABLE_NAME.TILE_INTERFERED_CNT=RPT_TABLE_NAME.TILE_INTERFERED_CNT+VALUES(TILE_INTERFERED_CNT),
		RPT_TABLE_NAME.CELL_INTERFERED_CNT=RPT_TABLE_NAME.CELL_INTERFERED_CNT+VALUES(CELL_INTERFERED_CNT),
		RPT_TABLE_NAME.L3_e1a=RPT_TABLE_NAME.L3_e1a+VALUES(L3_e1a),
		RPT_TABLE_NAME.L3_e1b=RPT_TABLE_NAME.L3_e1b+VALUES(L3_e1b),
		RPT_TABLE_NAME.L3_e1c=RPT_TABLE_NAME.L3_e1c+VALUES(L3_e1c),
		RPT_TABLE_NAME.L3_e1d=RPT_TABLE_NAME.L3_e1d+VALUES(L3_e1d),
		RPT_TABLE_NAME.L3_e1e=RPT_TABLE_NAME.L3_e1e+VALUES(L3_e1e),
		RPT_TABLE_NAME.L3_e1f=RPT_TABLE_NAME.L3_e1f+VALUES(L3_e1f),
		RPT_TABLE_NAME.L3_e2a=RPT_TABLE_NAME.L3_e2a+VALUES(L3_e2a),
		RPT_TABLE_NAME.L3_e2b=RPT_TABLE_NAME.L3_e2b+VALUES(L3_e2b),
		RPT_TABLE_NAME.L3_e2d=RPT_TABLE_NAME.L3_e2d+VALUES(L3_e2d),
		RPT_TABLE_NAME.L3_e2f=RPT_TABLE_NAME.L3_e2f+VALUES(L3_e2f),
		RPT_TABLE_NAME.L3_e3a=RPT_TABLE_NAME.L3_e3a+VALUES(L3_e3a),
		RPT_TABLE_NAME.L3_e4a=RPT_TABLE_NAME.L3_e4a+VALUES(L3_e4a),
		RPT_TABLE_NAME.L3_e4b=RPT_TABLE_NAME.L3_e4b+VALUES(L3_e4b),
		RPT_TABLE_NAME.L3_e6a=RPT_TABLE_NAME.L3_e6a+VALUES(L3_e6a),
		RPT_TABLE_NAME.L3_e6b=RPT_TABLE_NAME.L3_e6b+VALUES(L3_e6b),
		RPT_TABLE_NAME.PSC=IF(RPT_TABLE_NAME.PSC > VALUES(PSC),RPT_TABLE_NAME.PSC,VALUES(PSC)),
		RPT_TABLE_NAME.FP_RSCP_1_POW=RPT_TABLE_NAME.FP_RSCP_1_POW+VALUES(FP_RSCP_1_POW),
		RPT_TABLE_NAME.FP_RSSI_1_POW=RPT_TABLE_NAME.FP_RSSI_1_POW+VALUES(FP_RSSI_1_POW),
		RPT_TABLE_NAME.RSCP_GAP_CNT=RPT_TABLE_NAME.RSCP_GAP_CNT+VALUES(RSCP_GAP_CNT),
		RPT_TABLE_NAME.NON_SERVING_PILOT_DOMINANCE_CNT=RPT_TABLE_NAME.NON_SERVING_PILOT_DOMINANCE_CNT+VALUES(NON_SERVING_PILOT_DOMINANCE_CNT),
		RPT_TABLE_NAME.EMPHASIZE_PILOT_DOMINANCE_CNT=RPT_TABLE_NAME.EMPHASIZE_PILOT_DOMINANCE_CNT+VALUES(EMPHASIZE_PILOT_DOMINANCE_CNT),
		RPT_TABLE_NAME.BEST_SERVER_RSCP_CNT=RPT_TABLE_NAME.BEST_SERVER_RSCP_CNT+VALUES(BEST_SERVER_RSCP_CNT),
		RPT_TABLE_NAME.TOTAL_ACTIVE_CNT=RPT_TABLE_NAME.TOTAL_ACTIVE_CNT+VALUES(TOTAL_ACTIVE_CNT),
		RPT_TABLE_NAME.DURATION=RPT_TABLE_NAME.DURATION+VALUES(DURATION),
		RPT_TABLE_NAME.CS_DURATION=RPT_TABLE_NAME.CS_DURATION+VALUES(CS_DURATION),
		RPT_TABLE_NAME.UL_THROUGHPUT_SUM=RPT_TABLE_NAME.UL_THROUGHPUT_SUM+VALUES(UL_THROUGHPUT_SUM),
		RPT_TABLE_NAME.UL_TRAFFIC_VOLUME=RPT_TABLE_NAME.UL_TRAFFIC_VOLUME+VALUES(UL_TRAFFIC_VOLUME),
		RPT_TABLE_NAME.UL_THROUGHPUT_EVENT_CNT=RPT_TABLE_NAME.UL_THROUGHPUT_EVENT_CNT+VALUES(UL_THROUGHPUT_EVENT_CNT),
		RPT_TABLE_NAME.DL_THROUGHPUT_SUM=RPT_TABLE_NAME.DL_THROUGHPUT_SUM+VALUES(DL_THROUGHPUT_SUM),
		RPT_TABLE_NAME.DL_TRAFFIC_VOLUME=RPT_TABLE_NAME.DL_TRAFFIC_VOLUME+VALUES(DL_TRAFFIC_VOLUME),
		RPT_TABLE_NAME.DL_THROUGHPUT_EVENT_CNT=RPT_TABLE_NAME.DL_THROUGHPUT_EVENT_CNT+VALUES(DL_THROUGHPUT_EVENT_CNT),
		RPT_TABLE_NAME.UL_THROUGHPUT_MAX=IF(RPT_TABLE_NAME.UL_THROUGHPUT_MAX > VALUES(UL_THROUGHPUT_MAX),RPT_TABLE_NAME.UL_THROUGHPUT_MAX,VALUES(UL_THROUGHPUT_MAX)),
		RPT_TABLE_NAME.DL_THROUGHPUT_MAX=IF(RPT_TABLE_NAME.DL_THROUGHPUT_MAX > VALUES(DL_THROUGHPUT_MAX),RPT_TABLE_NAME.DL_THROUGHPUT_MAX,VALUES(DL_THROUGHPUT_MAX)),
		RPT_TABLE_NAME.SHO_ATTEMPT=RPT_TABLE_NAME.SHO_ATTEMPT+VALUES(SHO_ATTEMPT),
		RPT_TABLE_NAME.SHO_SUCC=RPT_TABLE_NAME.SHO_SUCC+VALUES(SHO_SUCC),
		RPT_TABLE_NAME.SHO_FAIL=RPT_TABLE_NAME.SHO_FAIL+VALUES(SHO_FAIL),
		RPT_TABLE_NAME.SOHO_ATTEMPT=RPT_TABLE_NAME.SOHO_ATTEMPT+VALUES(SOHO_ATTEMPT),
		RPT_TABLE_NAME.SOHO_SUCC=RPT_TABLE_NAME.SOHO_SUCC+VALUES(SOHO_SUCC),
		RPT_TABLE_NAME.SOHO_FAIL=RPT_TABLE_NAME.SOHO_FAIL+VALUES(SOHO_FAIL),
		RPT_TABLE_NAME.IFHO_ATTEMPT=RPT_TABLE_NAME.IFHO_ATTEMPT+VALUES(IFHO_ATTEMPT),
		RPT_TABLE_NAME.IFHO_SUCC=RPT_TABLE_NAME.IFHO_SUCC+VALUES(IFHO_SUCC),
		RPT_TABLE_NAME.IFHO_FAIL=RPT_TABLE_NAME.IFHO_FAIL+VALUES(IFHO_FAIL),
		RPT_TABLE_NAME.RRC_FAILURE_CNT=RPT_TABLE_NAME.RRC_FAILURE_CNT+VALUES(RRC_FAILURE_CNT),
		RPT_TABLE_NAME.NBAP_FAILURE_CNT=RPT_TABLE_NAME.NBAP_FAILURE_CNT+VALUES(NBAP_FAILURE_CNT),
		RPT_TABLE_NAME.RANAP_FAILURE_CNT=RPT_TABLE_NAME.RANAP_FAILURE_CNT+VALUES(RANAP_FAILURE_CNT),
		RPT_TABLE_NAME.OVER_LOC_CNT=RPT_TABLE_NAME.OVER_LOC_CNT+VALUES(OVER_LOC_CNT),
		RPT_TABLE_NAME.NON_OVER_LOC_CNT=RPT_TABLE_NAME.NON_OVER_LOC_CNT+VALUES(NON_OVER_LOC_CNT),
		RPT_TABLE_NAME.MAINBEAM_OVER_LOC_CNT=RPT_TABLE_NAME.MAINBEAM_OVER_LOC_CNT+VALUES(MAINBEAM_OVER_LOC_CNT),
		RPT_TABLE_NAME.MAINBEAM_NON_OVER_LOC_CNT=RPT_TABLE_NAME.MAINBEAM_NON_OVER_LOC_CNT+VALUES(MAINBEAM_NON_OVER_LOC_CNT),
		RPT_TABLE_NAME.BEST_OVER_LOC_CNT=RPT_TABLE_NAME.BEST_OVER_LOC_CNT+VALUES(BEST_OVER_LOC_CNT),
		RPT_TABLE_NAME.BEST_NON_OVER_LOC_CNT=RPT_TABLE_NAME.BEST_NON_OVER_LOC_CNT+VALUES(BEST_NON_OVER_LOC_CNT),
		RPT_TABLE_NAME.BEST_MAINBEAM_OVER_LOC_CNT=RPT_TABLE_NAME.BEST_MAINBEAM_OVER_LOC_CNT+VALUES(BEST_MAINBEAM_OVER_LOC_CNT),
		RPT_TABLE_NAME.BEST_MAINBEAM_NON_OVER_LOC_CNT=RPT_TABLE_NAME.BEST_MAINBEAM_NON_OVER_LOC_CNT+VALUES(BEST_MAINBEAM_NON_OVER_LOC_CNT),
		RPT_TABLE_NAME.TILE_MAINBEAM=IF(RPT_TABLE_NAME.TILE_MAINBEAM > VALUES(TILE_MAINBEAM),RPT_TABLE_NAME.DL_THROUGHPUT_MAX,VALUES(TILE_MAINBEAM)),	
		RPT_TABLE_NAME.BEST_RSCP_LOWER_SUM=RPT_TABLE_NAME.BEST_RSCP_LOWER_SUM+VALUES(BEST_RSCP_LOWER_SUM),
		RPT_TABLE_NAME.BEST_RSCP_LOWER_CNT=RPT_TABLE_NAME.BEST_RSCP_LOWER_CNT+VALUES(BEST_RSCP_LOWER_CNT),
		RPT_TABLE_NAME.BEST_ECN0_LOWER_SUM=RPT_TABLE_NAME.BEST_ECN0_LOWER_SUM+VALUES(BEST_ECN0_LOWER_SUM),
		RPT_TABLE_NAME.BEST_ECN0_LOWER_CNT=RPT_TABLE_NAME.BEST_ECN0_LOWER_CNT+VALUES(BEST_ECN0_LOWER_CNT)
	';
	DECLARE EXIT HANDLER FOR 145
	BEGIN 
		SET @SqlCmd=CONCAT('INSERT INTO `gt_gw_main`.`tbl_rpt_error`(`PID`,`CreateTime`,`error_str`)
			VALUES (',WORKER_ID,',''',NOW(),''',''',CONCAT(TMP_GT_DB,',',RPT_TBL_NAME,', is marked as crashed and should be repaired.'),''');');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
		SELECT CONCAT(TMP_GT_DB,',',RPT_TBL_NAME,', table crashed') AS IsSuccess;
		
		SELECT '{tech:”ALL ”, name:”SP-Report”, status:”2”,message_id: “null”, message: “SP_Sub_Generate_FP_PARALLEL Failed is marked as crashed and should be repaired”, log_path: “”}' AS message;		
	END;
	DECLARE EXIT HANDLER FOR 126
	BEGIN 
		SET @SqlCmd=CONCAT('INSERT INTO `gt_gw_main`.`tbl_rpt_error`(`PID`,`CreateTime`,`error_str`)
			VALUES (',WORKER_ID,',''',NOW(),''',''',CONCAT(TMP_GT_DB,',',RPT_TBL_NAME,' Incorrect key file for table.'),''');');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
		SELECT CONCAT(TMP_GT_DB,',',RPT_TBL_NAME,', Incorrect key file for table.') AS IsSuccess;		
	END;
	CALL SP_Sub_Set_Session_Param_LTE(GT_DB);
	SET @TEMP_TABLE=CONCAT(TMP_GT_DB,'.table_tile_fp_update_',SN);
	INSERT INTO gt_gw_main.SP_LOG VALUES(TMP_GT_DB,'SP_Sub_Generate_FP_PARALLEL','Start', START_TIME);
	
	IF RPT_TBL_NAME='table_tile_fp_c' THEN 
		SET @rpt_target_table=CONCAT(TMP_GT_DB,'.',RPT_TBL_NAME,'_',SN);
		SET @rpt_sample_table=CONCAT(TMP_GT_DB,'.',RPT_TBL_NAME);
		SET KEY_COLUMN_STR='RNC_ID,CELL_ID,';
		SET GROUP_STR=CONCAT(' GROUP BY DATA_DATE,DATA_HOUR,INDOOR,MOVING,CALL_TYPE,CALL_STATUS,RNC_ID,CELL_ID');
		SET @SqlCmd=CONCAT('DROP TABLE IF EXISTS ',@rpt_target_table,';');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
		SET @SqlCmd=CONCAT('CREATE TABLE ',@rpt_target_table, ' LIKE ',@rpt_sample_table,';');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
	
		
		INSERT INTO gt_gw_main.SP_LOG VALUES(TMP_GT_DB,'SP_Sub_Generate_FP_PARALLEL',CONCAT('INSERT ',@rpt_target_table,' HOUR Start'), NOW());
		SET STEP_START_TIME := SYSDATE();
		SET @SqlCmd=CONCAT('INSERT INTO ',@rpt_target_table,' 
						(
						`DATA_DATE`,
						`DATA_HOUR`,
						`FREQUENCY`,
						`UARFCN`,
						`INDOOR`,
						`MOVING`,
						`CELL_INDOOR`,
						`CELL_NAME`,
						`CLUSTER_ID`,
						`SITE_ID`,
						`CELL_LON`,
						`CELL_LAT`,
						`CALL_TYPE`,
						`CALL_STATUS`,
						',KEY_COLUMN_STR,COLUMN_STR,')
					SELECT	
						`DATA_DATE`,
						`DATA_HOUR`,
						`FREQUENCY`,
						`UARFCN`,
						`INDOOR`,
						`MOVING`,
						`CELL_INDOOR`,
						`CELL_NAME`,
						`CLUSTER_ID`,
						`SITE_ID`,
						`CELL_LON`,
						`CELL_LAT`,
						`CALL_TYPE`,
						`CALL_STATUS`,
						',KEY_COLUMN_STR,COLUMN_SUM_STR,'
					FROM ',@TEMP_TABLE,GROUP_STR,' 
					;');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
	ELSEIF RPT_TBL_NAME='table_tile_fp' THEN 
		SET @rpt_target_table=CONCAT(RPT_TBL_NAME,'_',v_DATA_HOUR,'_',SN);
		SET KEY_COLUMN_STR='RNC_ID,CELL_ID,TILE_ID,';
		SET GROUP_STR=' ';
		SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.',@rpt_target_table,' 
						(
						`DATA_DATE`,
						`DATA_HOUR`,
						`FREQUENCY`,
						`UARFCN`,
						`INDOOR`,
						`MOVING`,
						`CELL_INDOOR`,
						`CELL_NAME`,
						`CLUSTER_ID`,
						`SITE_ID`,
						`CELL_LON`,
						`CELL_LAT`,
						`CALL_TYPE`,
						`CALL_STATUS`,
						',KEY_COLUMN_STR,COLUMN_STR,')
					SELECT	
						`DATA_DATE`,
						`DATA_HOUR`,
						`FREQUENCY`,
						`UARFCN`,
						`INDOOR`,
						`MOVING`,
						`CELL_INDOOR`,
						`CELL_NAME`,
						`CLUSTER_ID`,
						`SITE_ID`,
						`CELL_LON`,
						`CELL_LAT`,
						`CALL_TYPE`,
						`CALL_STATUS`,
						',KEY_COLUMN_STR,COLUMN_IFNULL_STR,'
					FROM ',@TEMP_TABLE,' 
					ON DUPLICATE KEY UPDATE 
					',REPLACE(COLUMN_UPD_STR,'RPT_TABLE_NAME',CONCAT(GT_DB,'.',@rpt_target_table)),'
					;');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
		INSERT INTO gt_gw_main.SP_LOG VALUES(TMP_GT_DB,'SP_Sub_Generate_FP_PARALLEL',CONCAT(GT_DB,'.',@rpt_target_table,' COST: ',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' seconds.'), NOW());
		SET STEP_START_TIME := SYSDATE();
	ELSEIF RPT_TBL_NAME='table_tile_fp_t' THEN 
		SET @rpt_target_table=CONCAT(RPT_TBL_NAME,'_',v_DATA_HOUR,'_',SN);
		SET @rpt_target_def_table=CONCAT(RPT_TBL_NAME,'_def_',v_DATA_HOUR,'_',SN);
		SET @rpt_sample_def_table=CONCAT(TMP_GT_DB,'.',RPT_TBL_NAME,'_def');
		SET KEY_COLUMN_STR='`RNC_ID`,`TILE_ID`,';
		SET GROUP_STR=CONCAT(' GROUP BY DATA_DATE,DATA_HOUR,INDOOR,MOVING,CALL_TYPE,CALL_STATUS,TILE_ID');
		SET GROUP_DEF_STR=CONCAT(' GROUP BY DATA_DATE,DATA_HOUR,TILE_ID');
	
		SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.',@rpt_target_table,' 
						(
						`DATA_DATE`,
						`DATA_HOUR`,
						`FREQUENCY`,
						`UARFCN`,
						`INDOOR`,
						`MOVING`,
						`CELL_INDOOR`,	
						`CELL_NAME`,
						`CLUSTER_ID`,
						`SITE_ID`,
						`CELL_LON`,
						`CELL_LAT`,
						`CALL_TYPE`,
						`CALL_STATUS`,
						',KEY_COLUMN_STR,COLUMN_STR,')
					SELECT	
						`DATA_DATE`,
						`DATA_HOUR`,
						`FREQUENCY`,
						`UARFCN`,
						`INDOOR`,
						`MOVING`,
						`CELL_INDOOR`,
						`CELL_NAME`,
						`CLUSTER_ID`,
						`SITE_ID`,
						`CELL_LON`,
						`CELL_LAT`,
						`CALL_TYPE`,
						`CALL_STATUS`,
						',KEY_COLUMN_STR,COLUMN_SUM_STR,'
					FROM ',@TEMP_TABLE,GROUP_STR,' 
					ON DUPLICATE KEY UPDATE 
					',REPLACE(COLUMN_UPD_STR,'RPT_TABLE_NAME',CONCAT(GT_DB,'.',@rpt_target_table)),'
					;');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
		INSERT INTO gt_gw_main.SP_LOG VALUES(TMP_GT_DB,'SP_Sub_Generate_FP_PARALLEL',CONCAT(GT_DB,'.',@rpt_target_table,' COST: ',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' seconds.'), NOW());
		SET STEP_START_TIME := SYSDATE();
		SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.',@rpt_target_def_table,' 
						(
						`DATA_DATE`,
						`DATA_HOUR`,
						',KEY_COLUMN_STR,COLUMN_STR,')
					SELECT	
						`DATA_DATE`,
						`DATA_HOUR`,
						',KEY_COLUMN_STR,COLUMN_SUM_STR,'
					FROM ',@TEMP_TABLE,GROUP_DEF_STR,' 
					ON DUPLICATE KEY UPDATE 
					',REPLACE(COLUMN_UPD_STR,'RPT_TABLE_NAME',CONCAT(GT_DB,'.',@rpt_target_def_table)),'
					;');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
		INSERT INTO gt_gw_main.SP_LOG VALUES(TMP_GT_DB,'SP_Sub_Generate_FP_PARALLEL',CONCAT(GT_DB,'.',@rpt_target_def_table,' COST: ',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' seconds.'), NOW());
	ELSEIF RPT_TBL_NAME='table_tile_fp_dy' THEN 
		SET @rpt_target_table=CONCAT(RPT_TBL_NAME,'_',SN);
		SET @TEMP_TABLE1=CONCAT(GT_DB,'.table_tile_fp','_',v_DATA_HOUR,'_',SN);
		SET GROUP_STR=CONCAT(' GROUP BY DATA_DATE,INDOOR,MOVING,CALL_TYPE,CALL_STATUS,RNC_ID,CELL_ID,TILE_ID');
		SET KEY_COLUMN_STR='RNC_ID,CELL_ID,TILE_ID,';
		
		
		SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.',@rpt_target_table,' 
						(
						`DATA_DATE`,
						`FREQUENCY`,
						`UARFCN`,
						`INDOOR`,
						`MOVING`,
						`CELL_INDOOR`,
						`CELL_NAME`,
						`CLUSTER_ID`,
						`SITE_ID`,
						`CELL_LON`,
						`CELL_LAT`,
						`CALL_TYPE`,
						`CALL_STATUS`,
						',KEY_COLUMN_STR,COLUMN_STR,')
					SELECT	
						`DATA_DATE`,
						`FREQUENCY`,
						`UARFCN`,
						`INDOOR`,
						`MOVING`,
						`CELL_INDOOR`,
						`CELL_NAME`,
						`CLUSTER_ID`,
						`SITE_ID`,
						`CELL_LON`,
						`CELL_LAT`,
						`CALL_TYPE`,
						`CALL_STATUS`,
						',KEY_COLUMN_STR,COLUMN_SUM_STR,'
					FROM ',@TEMP_TABLE1,GROUP_STR,'
					ON DUPLICATE KEY UPDATE 
					',REPLACE(COLUMN_UPD_STR,'RPT_TABLE_NAME',CONCAT(GT_DB,'.',@rpt_target_table)),'
					;');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
		INSERT INTO gt_gw_main.SP_LOG VALUES(TMP_GT_DB,'SP_Sub_Generate_FP_PARALLEL',CONCAT(GT_DB,'.',@rpt_target_table,' COST: ',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' seconds.'), NOW());
		
	ELSEIF RPT_TBL_NAME='table_tile_fp_dy_t' THEN 
		SET @rpt_target_table=CONCAT(RPT_TBL_NAME,'_',SN);
		SET @rpt_target_def_table=CONCAT(RPT_TBL_NAME,'_def_',SN);
		SET @rpt_sample_def_table=CONCAT(TMP_GT_DB,'.',RPT_TBL_NAME,'_def');
		SET GROUP_STR=CONCAT(' GROUP BY DATA_DATE,INDOOR,MOVING,CALL_TYPE,CALL_STATUS,TILE_ID');
		SET GROUP_DEF_STR=CONCAT(' GROUP BY TILE_ID,DATA_HOUR');
		SET @TEMP_TABLE1=CONCAT(GT_DB,'.table_tile_fp_t','_',v_DATA_HOUR,'_',SN);
		SET @TEMP_TABLE2=CONCAT(GT_DB,'.table_tile_fp_t_def','_',v_DATA_HOUR,'_',SN);
	
		SET KEY_COLUMN_STR='`RNC_ID`,`TILE_ID`,';
		
		
	
		SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.',@rpt_target_table,' 
						(
						`DATA_DATE`,
						`FREQUENCY`,
						`UARFCN`,
						`INDOOR`,
						`MOVING`,
						`CELL_INDOOR`,
						`CELL_NAME`,
						`CLUSTER_ID`,
						`SITE_ID`,
						`CELL_LON`,
						`CELL_LAT`,
						`CALL_TYPE`,
						`CALL_STATUS`,
						',KEY_COLUMN_STR,COLUMN_STR,')
					SELECT	
						`DATA_DATE`,
						`FREQUENCY`,
						`UARFCN`,
						`INDOOR`,
						`MOVING`,
						`CELL_INDOOR`,
						`CELL_NAME`,
						`CLUSTER_ID`,
						`SITE_ID`,
						`CELL_LON`,
						`CELL_LAT`,
						`CALL_TYPE`,
						`CALL_STATUS`,
						',KEY_COLUMN_STR,COLUMN_SUM_STR,'
					FROM ',@TEMP_TABLE1,GROUP_STR,' 
					ON DUPLICATE KEY UPDATE 
					',REPLACE(COLUMN_UPD_STR,'RPT_TABLE_NAME',CONCAT(GT_DB,'.',@rpt_target_table)),'
					;');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
		INSERT INTO gt_gw_main.SP_LOG VALUES(TMP_GT_DB,'SP_Sub_Generate_FP_PARALLEL',CONCAT(GT_DB,'.',@rpt_target_table,' COST: ',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' seconds.'), NOW());
		SET STEP_START_TIME := SYSDATE();
		SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.',@rpt_target_def_table,' 
						(
						`DATA_DATE`,
						',KEY_COLUMN_STR,COLUMN_STR,')
					SELECT	
						`DATA_DATE`,
						',KEY_COLUMN_STR,COLUMN_SUM_STR,'
					FROM ',@TEMP_TABLE2,GROUP_DEF_STR,' 
					ON DUPLICATE KEY UPDATE 
					',REPLACE(COLUMN_UPD_STR,'RPT_TABLE_NAME',CONCAT(GT_DB,'.',@rpt_target_def_table)),'
					;');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
		INSERT INTO gt_gw_main.SP_LOG VALUES(TMP_GT_DB,'SP_Sub_Generate_FP_PARALLEL',CONCAT(GT_DB,'.',@rpt_target_def_table,' COST: ',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' seconds.'), NOW());
	ELSEIF RPT_TBL_NAME='table_tile_fp_dy_c' THEN 
		SET @rpt_target_table=CONCAT(GT_DB,'.',RPT_TBL_NAME);
		SET @TEMP_TABLE=CONCAT(TMP_GT_DB,'.table_tile_fp_c_mgr');
		SET KEY_COLUMN_STR='RNC_ID,CELL_ID,';
		SET GROUP_STR=CONCAT(' GROUP BY DATA_DATE,INDOOR,MOVING,CALL_TYPE,CALL_STATUS,RNC_ID,CELL_ID');
	
		INSERT INTO gt_gw_main.SP_LOG VALUES(TMP_GT_DB,'SP_Sub_Generate_FP_PARALLEL',CONCAT('INSERT ',@rpt_target_table,' HOUR Start'), NOW());
		SET STEP_START_TIME := SYSDATE();
		SET @SqlCmd=CONCAT('INSERT INTO ',@rpt_target_table,' 
						(
						`DATA_DATE`,
						`FREQUENCY`,
						`UARFCN`,
						`INDOOR`,
						`MOVING`,
						`CELL_INDOOR`,
						`CELL_NAME`,
						`CLUSTER_ID`,
						`SITE_ID`,
						`CELL_LON`,
						`CELL_LAT`,
						`CALL_TYPE`,
						`CALL_STATUS`,
						',KEY_COLUMN_STR,COLUMN_STR,')
					SELECT	
						`DATA_DATE`,
						`FREQUENCY`,
						`UARFCN`,
						`INDOOR`,
						`MOVING`,
						`CELL_INDOOR`,
						`CELL_NAME`,
						`CLUSTER_ID`,
						`SITE_ID`,
						`CELL_LON`,
						`CELL_LAT`,
						`CALL_TYPE`,
						`CALL_STATUS`,
						',KEY_COLUMN_STR,COLUMN_SUM_STR,'
					FROM ',@TEMP_TABLE,GROUP_STR,' 
					ON DUPLICATE KEY UPDATE 
					',REPLACE(COLUMN_UPD_STR,'RPT_TABLE_NAME',CONCAT(GT_DB,'.',RPT_TBL_NAME)),'
					;');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
	ELSEIF RPT_TBL_NAME='table_tile_fp_c_mgr' THEN 
		SET RPT_TBL_NAME = 'table_tile_fp_c';
		SET @rpt_target_table=CONCAT(GT_DB,'.',RPT_TBL_NAME);
		SET @TEMP_TABLE=CONCAT(TMP_GT_DB,'.table_tile_fp_c_mgr');
		SET KEY_COLUMN_STR='RNC_ID,CELL_ID,';
		SET GROUP_STR=CONCAT(' GROUP BY DATA_DATE,DATA_HOUR,INDOOR,MOVING,CALL_TYPE,CALL_STATUS,RNC_ID,CELL_ID');
	
		INSERT INTO gt_gw_main.SP_LOG VALUES(TMP_GT_DB,'SP_Sub_Generate_FP_PARALLEL',CONCAT('INSERT ',@rpt_target_table,' HOUR Start'), NOW());
		SET STEP_START_TIME := SYSDATE();
		SET @SqlCmd=CONCAT('INSERT INTO ',@rpt_target_table,' 
						(
						`DATA_DATE`,
						`DATA_HOUR`,
						`FREQUENCY`,
						`UARFCN`,
						`INDOOR`,
						`MOVING`,
						`CELL_INDOOR`,
						`CELL_NAME`,
						`CLUSTER_ID`,
						`SITE_ID`,
						`CELL_LON`,
						`CELL_LAT`,
						`CALL_TYPE`,
						`CALL_STATUS`,
						',KEY_COLUMN_STR,COLUMN_STR,')
					SELECT	
						`DATA_DATE`,
						`DATA_HOUR`,
						`FREQUENCY`,
						`UARFCN`,
						`INDOOR`,
						`MOVING`,
						`CELL_INDOOR`,
						`CELL_NAME`,
						`CLUSTER_ID`,
						`SITE_ID`,
						`CELL_LON`,
						`CELL_LAT`,
						`CALL_TYPE`,
						`CALL_STATUS`,
						',KEY_COLUMN_STR,COLUMN_SUM_STR,'
					FROM ',@TEMP_TABLE,GROUP_STR,' 
					ON DUPLICATE KEY UPDATE 
					',REPLACE(COLUMN_UPD_STR,'RPT_TABLE_NAME',CONCAT(GT_DB,'.',RPT_TBL_NAME)),'
					;');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
	
	END IF;
	INSERT INTO gt_gw_main.SP_LOG VALUES(TMP_GT_DB,'SP_Sub_Generate_FP_PARALLEL',CONCAT('Done: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());
	
END$$
DELIMITER ;
