DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Sub_Generate_1st_Server_AGR`(IN GT_DB VARCHAR(100), IN KIND VARCHAR(20), IN VENDOR_SOURCE VARCHAR(20),IN GT_COVMO VARCHAR(100))
BEGIN
	DECLARE RNC_ID INT;
	DECLARE O_GT_DB VARCHAR(100) DEFAULT GT_DB;
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE PARTITION_ID INT DEFAULT SUBSTRING(RIGHT(GT_DB,18),10,2);
	DECLARE SH_EH VARCHAR(9) DEFAULT RIGHT(GT_DB,9);
	DECLARE GT_DATE VARCHAR(18) DEFAULT RIGHT(GT_DB,18);
	DECLARE STARTHOUR VARCHAR(2) DEFAULT SUBSTRING(RIGHT(GT_DB,18),10,2);
	DECLARE ENDHOUR VARCHAR(2) DEFAULT IF(SUBSTRING(RIGHT(GT_DB,18),15,2)='00','24',SUBSTRING(RIGHT(GT_DB,18),15,2));
	DECLARE RUN VARCHAR(20);
	DECLARE WORKER_ID VARCHAR(10) DEFAULT CONNECTION_ID();
	DECLARE CURRENT_NT_DB VARCHAR(50) DEFAULT CONCAT('gt_nt_',gt_strtok(GT_DB,3,'_'));
	SELECT gt_strtok(GT_DB,2,'_') INTO RNC_ID;
	
	CALL SP_Sub_Set_Session_Param(GT_DB);
	SELECT REPLACE(GT_DB,SH_EH,'0000_0000') INTO GT_DB;
	IF VENDOR_SOURCE = 'GW' THEN
		IF KIND = 'DAILY' THEN
			SET RUN = '_tmp';
		ELSEIF KIND = 'RERUN' THEN
			SET RUN = '_rerun';
		END IF;
	ELSEIF VENDOR_SOURCE = 'AP' THEN
		SET RUN = '';
	END IF;
	
	SET @SqlCmd=CONCAT('SELECT att_value INTO @SYS_CONFIG_TILE FROM ',CURRENT_NT_DB,'.`sys_config` WHERE `group_name`=''system'' AND att_name = ''MapResolution'';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
		
	IF gt_covmo_csv_count(@SYS_CONFIG_TILE,',') =3 THEN
		
		SET @SqlCmd=CONCAT('SELECT gt_covmo_csv_get(att_value,3) INTO @ZOOM_LEVEL FROM ',CURRENT_NT_DB,'.`sys_config` WHERE `group_name`=''system'' AND att_name = ''MapResolution'';');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
	ELSE 
		SET @SqlCmd=CONCAT('SELECT att_value INTO @ZOOM_LEVEL FROM ',CURRENT_NT_DB,'.`sys_config` WHERE `group_name`=''system'' AND att_name = ''MapResolution'';');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
	END IF;
	
	SET @SqlCmd=CONCAT('ALTER TABLE ',GT_DB,RUN,'.table_tile_1st_server TRUNCATE PARTITION h',PARTITION_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('ALTER TABLE ',GT_DB,RUN,'.table_tile_1st_server_t TRUNCATE PARTITION h',PARTITION_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('ALTER TABLE ',GT_DB,RUN,'.table_tile_1st_server_c TRUNCATE PARTITION h',PARTITION_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('ALTER TABLE ',GT_DB,RUN,'.table_tile_1st_server_def TRUNCATE PARTITION h',PARTITION_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('ALTER TABLE ',GT_DB,RUN,'.table_tile_1st_server_t_def TRUNCATE PARTITION h',PARTITION_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('ALTER TABLE ',GT_DB,RUN,'.table_tile_1st_server_c_def TRUNCATE PARTITION h',PARTITION_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_1st_Server_AGR','Create temp table tmp_table_tile_1st_server ', NOW());
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE  IF EXISTS ',GT_DB,RUN,'.tmp_table_tile_1st_server_',WORKER_ID,';');
	PREPARE stmt FROM @sqlcmd;
	EXECUTE stmt;
	DEALLOCATE PREPARE stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,RUN,'.`tmp_table_tile_1st_server_',WORKER_ID,'` (
					`DATA_DATE` DATE DEFAULT NULL,
					`DATA_HOUR` TINYINT(4) DEFAULT NULL,
					`FREQUENCY` SMALLINT(6) DEFAULT NULL,
					`UARFCN` MEDIUMINT(9) DEFAULT NULL,
					`INDOOR` TINYINT(4) DEFAULT NULL,
					`MOVING` TINYINT(4) DEFAULT NULL,
					`TILE_ID` BIGINT(20) DEFAULT NULL,
					`RNC_ID` MEDIUMINT(9) DEFAULT NULL,
					`CELL_INDOOR` TINYINT(4) DEFAULT NULL,
					`CLUSTER_ID` MEDIUMINT(9) DEFAULT NULL,
					`SITE_ID` VARCHAR(20) DEFAULT NULL,
					`CELL_ID` MEDIUMINT(9) DEFAULT NULL,
					`CALL_TYPE` TINYINT(4) DEFAULT NULL,
					`CALL_STATUS` TINYINT(4) DEFAULT NULL,
					`CALL_CNT` MEDIUMINT(9) DEFAULT ''0'',
					`RSCP` DOUBLE DEFAULT NULL,
					`RSCP_MED` DOUBLE DEFAULT NULL,
					`ECN0` DOUBLE DEFAULT NULL,
					`ECN0_MED` DOUBLE DEFAULT NULL,
					-- CALC FOR TILE AND CELL
					`POS_AS1_RSCP_CNT` DOUBLE DEFAULT NULL,
					`POS_AS1_ECN0_CNT` DOUBLE DEFAULT NULL,
					-- update
					`CELL_LON` DOUBLE DEFAULT NULL,
					`CELL_LAT` DOUBLE DEFAULT NULL,
					`CELL_NAME` VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL
-- 	,
-- 					  CALL_STATUS_BLOCK MEDIUMINT(9) DEFAULT 0,
-- 					  CALL_STATUS_SUCCESS MEDIUMINT(9) DEFAULT 0,
-- 					  CALL_STATUS_DROP MEDIUMINT(9) DEFAULT 0,
-- 					  CALL_TYPE_SMS MEDIUMINT(9) DEFAULT 0,
-- 					  CALL_TYPE_VOICE MEDIUMINT(9) DEFAULT 0,
-- 					  CALL_TYPE_VEDIO MEDIUMINT(9) DEFAULT 0,
-- 					  CALL_TYPE_PS99 MEDIUMINT(9) DEFAULT 0,
-- 					  CALL_TYPE_HSPA MEDIUMINT(9) DEFAULT 0,
-- 					  CALL_TYPE_MRAB MEDIUMINT(9) DEFAULT 0,
-- 					  CALL_TYPE_PSOTHERS MEDIUMINT(9) DEFAULT 0,
-- 					  CALL_TYPE_CS MEDIUMINT(9) DEFAULT 0,
-- 					  CALL_TYPE_PS MEDIUMINT(9) DEFAULT 0
				) ENGINE=MYISAM DEFAULT CHARSET=latin1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt; 
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_1st_Server_AGR','Insert into tmp table_tile_1st_server ', NOW());
	
	SET @SqlCmd=CONCAT(' INSERT INTO  ',GT_DB,RUN,'.`tmp_table_tile_1st_server_',WORKER_ID,'`
			     (DATA_DATE,DATA_HOUR,FREQUENCY,UARFCN,INDOOR,MOVING,TILE_ID,RNC_ID,CELL_INDOOR,CLUSTER_ID,SITE_ID,
				CELL_ID,CELL_NAME,CALL_TYPE,CALL_STATUS,CALL_CNT,RSCP,ECN0, RSCP_MED,ECN0_MED,POS_AS1_RSCP_CNT,POS_AS1_ECN0_CNT
-- 				,CALL_STATUS_BLOCK,CALL_STATUS_SUCCESS,CALL_STATUS_DROP,CALL_TYPE_SMS,CALL_TYPE_VOICE,CALL_TYPE_VEDIO
-- 				,CALL_TYPE_PS99,CALL_TYPE_HSPA,CALL_TYPE_MRAB,CALL_TYPE_PSOTHERS,CALL_TYPE_CS,CALL_TYPE_PS
	)
			    SELECT
					 DATA_DATE
					, DATA_HOUR
					, POS_AS1_FREQUENCY AS FREQUENCY
					, POS_AS1_UARFCN AS UARFCN
					, INDOOR
					, MOVING
					, gt_covmo_proj_geohash_to_hex_geohash(POS_AS_LOC, ',@ZOOM_LEVEL,') AS TILE_ID
					, POS_AS1_RNC AS RNC_ID
					, POS_AS1_CELL_INDOOR AS CELL_INDOOR
					, POS_AS1_CLUSTER AS CLUSTER_ID
					, POS_AS1_SITE AS SITE_ID
					, POS_AS1_CELL AS CELL_ID
					, POS_AS1_CELL_NAME AS CELL_NAME
					, CALL_TYPE 
					, CALL_STATUS
					, COUNT(POS_AS1_CELL) AS CALL_CNT
					, SUM(POS_AS1_RSCP) AS RSCP
					, SUM(POS_AS1_ECN0) AS ECN0
					, median(POS_AS1_RSCP) RSCP_MED
					, median(POS_AS1_ECN0) ECN0_MED
					-- CALC FOR TILE AND CELL
					, COUNT(POS_AS1_RSCP) AS POS_AS1_RSCP_CNT
					, COUNT(POS_AS1_ECN0) AS POS_AS1_ECN0_CNT
-- 					, SUM(IF(CALL_STATUS = 3,1,0)) AS CALL_STATUS_BLOCK
-- 					, SUM(IF(CALL_STATUS IN (1,2,4),1,0)) AS CALL_STATUS_SUCCESS
-- 					, SUM(IF(CALL_STATUS = 2,1,0)) AS CALL_STATUS_DROP
-- 					, SUM(IF(CALL_TYPE = 16,1,0)) AS CALL_TYPE_SMS
-- 					, SUM(IF(CALL_TYPE = 10,1,0)) AS CALL_TYPE_VOICE
-- 					, SUM(IF(CALL_TYPE = 11,1,0)) AS CALL_TYPE_VEDIO
-- 					, SUM(IF(CALL_TYPE = 12,1,0)) AS CALL_TYPE_PS99
-- 					, SUM(IF(CALL_TYPE = 13,1,0)) AS CALL_TYPE_HSPA
-- 					, SUM(IF(CALL_TYPE = 14,1,0)) AS CALL_TYPE_MRAB
-- 					, SUM(IF(CALL_TYPE = 18,1,0)) AS CALL_TYPE_PSOTHERS
-- 					, SUM(IF(CALL_TYPE IN (10,11),1,0)) AS CALL_TYPE_CS
-- 					, SUM(IF(CALL_TYPE IN (12,13,14,18),1,0)) AS CALL_TYPE_PS
				FROM ',GT_DB,RUN,'.table_call
				WHERE POS_AS1_RNC =',RNC_ID,'
				AND DATA_HOUR >= ',STARTHOUR,' AND DATA_HOUR < ',ENDHOUR,'
				AND POS_AS1_RSCP IS NOT NULL
				GROUP BY  DATA_DATE
					, DATA_HOUR
-- 					, POS_AS1_FREQUENCY
-- 					, POS_AS1_UARFCN
					, INDOOR
					, MOVING
					, gt_covmo_proj_geohash_to_hex_geohash(POS_AS_LOC, ',@ZOOM_LEVEL,')
					, POS_AS1_RNC
-- 					, POS_AS1_CELL_INDOOR
-- 					, POS_AS1_CLUSTER
-- 					, POS_AS1_SITE
					, POS_AS1_CELL
					, CALL_TYPE 
					, CALL_STATUS
				ORDER BY NULL');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_1st_Server_AGR','Update CELL_LON, CELL_LAT in table_tile_1st_server ', NOW());
	
	SET @SqlCmd=CONCAT(' UPDATE ',GT_DB,RUN,'.`tmp_table_tile_1st_server_',WORKER_ID,'` A, 
				    ',CURRENT_NT_DB,'.nt_current B
			     SET A.CELL_LON=B.LONGITUDE
				,A.CELL_LAT=B.LATITUDE
				WHERE A.RNC_ID=B.RNC_ID
				AND A.CELL_ID=B.CELL_ID
				AND A.DATA_HOUR >= ',STARTHOUR,' AND A.DATA_HOUR < ',ENDHOUR,';');
	
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
		
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_1st_Server_AGR','Insert Data to table_tile_1st_server', NOW());
	SET @SqlCmd=CONCAT('INSERT INTO  ',GT_DB,RUN,'.`table_tile_1st_server`	
					(DATA_DATE,DATA_HOUR,FREQUENCY,UARFCN,INDOOR,MOVING,TILE_ID,RNC_ID,CELL_INDOOR,CLUSTER_ID,SITE_ID,
					CELL_ID,CELL_NAME,CALL_TYPE,CALL_STATUS,CALL_CNT,RSCP,ECN0, RSCP_MED,ECN0_MED, CELL_LON,CELL_LAT,POS_AS1_RSCP_CNT, POS_AS1_ECN0_CNT
-- 					,CALL_STATUS_BLOCK,CALL_STATUS_SUCCESS,CALL_STATUS_DROP,CALL_TYPE_SMS,CALL_TYPE_VOICE,CALL_TYPE_VEDIO
-- 					,CALL_TYPE_PS99,CALL_TYPE_HSPA,CALL_TYPE_MRAB,CALL_TYPE_PSOTHERS,CALL_TYPE_CS,CALL_TYPE_PS
	)
				SELECT
					 DATA_DATE,DATA_HOUR,FREQUENCY,UARFCN,INDOOR,MOVING,TILE_ID,RNC_ID,CELL_INDOOR,CLUSTER_ID,SITE_ID,
					CELL_ID,CELL_NAME,CALL_TYPE,CALL_STATUS,CALL_CNT,RSCP,ECN0, RSCP_MED,ECN0_MED, CELL_LON,CELL_LAT,POS_AS1_RSCP_CNT, POS_AS1_ECN0_CNT
-- 					,CALL_STATUS_BLOCK,CALL_STATUS_SUCCESS,CALL_STATUS_DROP,CALL_TYPE_SMS,CALL_TYPE_VOICE,CALL_TYPE_VEDIO
-- 					,CALL_TYPE_PS99,CALL_TYPE_HSPA,CALL_TYPE_MRAB,CALL_TYPE_PSOTHERS,CALL_TYPE_CS,CALL_TYPE_PS
				FROM ',GT_DB,RUN,'.`tmp_table_tile_1st_server_',WORKER_ID,'`;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_1st_Server_AGR','Insert Data to table_tile_1st_server_t', NOW());
	SET @SqlCmd=CONCAT(' INSERT INTO  ',GT_DB,RUN,'.`table_tile_1st_server_t`
			     (DATA_DATE,DATA_HOUR,FREQUENCY,UARFCN,INDOOR,MOVING,TILE_ID,RNC_ID,
				CALL_TYPE,CALL_STATUS,CALL_CNT,RSCP,ECN0, RSCP_MED,ECN0_MED,POS_AS1_RSCP_CNT, POS_AS1_ECN0_CNT
-- 				,CALL_STATUS_BLOCK,CALL_STATUS_SUCCESS,CALL_STATUS_DROP,CALL_TYPE_SMS,CALL_TYPE_VOICE,CALL_TYPE_VEDIO
-- 					,CALL_TYPE_PS99,CALL_TYPE_HSPA,CALL_TYPE_MRAB,CALL_TYPE_PSOTHERS,CALL_TYPE_CS,CALL_TYPE_PS
	)
			    SELECT
					 DATA_DATE
					, DATA_HOUR
					, FREQUENCY
					, UARFCN
					, INDOOR
					, MOVING
					, TILE_ID
					, RNC_ID
					#, CELL_INDOOR
					#, CLUSTER_ID
					#, SITE_ID
					#, CELL_ID
					, CALL_TYPE 
					, CALL_STATUS
					, SUM(CALL_CNT) AS CALL_CNT
					,SUM(RSCP) AS RSCP
					,SUM(ECN0) AS ECN0
					, NULL #median(RSCP_MED) 
					, NULL #median(ECN0_MED)
					, SUM(POS_AS1_RSCP_CNT)
					, SUM(POS_AS1_ECN0_CNT)
-- 					,SUM(CALL_STATUS_BLOCK)
-- 					,SUM(CALL_STATUS_SUCCESS)
-- 					,SUM(CALL_STATUS_DROP)
-- 					,SUM(CALL_TYPE_SMS)
-- 					,SUM(CALL_TYPE_VOICE)
-- 					,SUM(CALL_TYPE_VEDIO)
-- 					,SUM(CALL_TYPE_PS99)
-- 					,SUM(CALL_TYPE_HSPA)
-- 					,SUM(CALL_TYPE_MRAB)
-- 					,SUM(CALL_TYPE_PSOTHERS)
-- 					,SUM(CALL_TYPE_CS)
-- 					,SUM(CALL_TYPE_PS)
				FROM ',GT_DB,RUN,'.`tmp_table_tile_1st_server_',WORKER_ID,'`
				GROUP BY  DATA_DATE
					, DATA_HOUR
-- 					, FREQUENCY
-- 					, UARFCN
					, INDOOR
					, MOVING
					, TILE_ID
					, RNC_ID
					#, CELL_INDOOR
					#, CLUSTER_ID
					#, SITE_ID
					#, CELL_ID
					, CALL_TYPE 
					, CALL_STATUS
				ORDER BY NULL');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_1st_Server_AGR','Insert Data to table_tile_1st_server_c', NOW());
	SET @SqlCmd=CONCAT(' INSERT INTO  ',GT_DB,RUN,'.`table_tile_1st_server_c`
			     (DATA_DATE,DATA_HOUR,FREQUENCY,UARFCN,INDOOR,MOVING,RNC_ID,CELL_INDOOR,CLUSTER_ID,SITE_ID,
				CELL_ID,CELL_NAME,CALL_TYPE,CALL_STATUS,CALL_CNT,RSCP,ECN0, RSCP_MED,ECN0_MED, CELL_LON,CELL_LAT,POS_AS1_RSCP_CNT, POS_AS1_ECN0_CNT
-- 				,CALL_STATUS_BLOCK,CALL_STATUS_SUCCESS,CALL_STATUS_DROP,CALL_TYPE_SMS,CALL_TYPE_VOICE,CALL_TYPE_VEDIO
-- 					,CALL_TYPE_PS99,CALL_TYPE_HSPA,CALL_TYPE_MRAB,CALL_TYPE_PSOTHERS,CALL_TYPE_CS,CALL_TYPE_PS
	)
			    SELECT
					 DATA_DATE
					, DATA_HOUR
					, FREQUENCY
					, UARFCN
					, INDOOR
					, MOVING
					#, TILE_ID
					, RNC_ID
					, CELL_INDOOR
					, CLUSTER_ID
					, SITE_ID
					, CELL_ID
					, CELL_NAME
					, CALL_TYPE 
					, CALL_STATUS
					, SUM(CALL_CNT) AS CALL_CNT
					,SUM(RSCP) AS RSCP
					,SUM(ECN0) AS ECN0
					, NULL #median(RSCP_MED) 
					, NULL #median(ECN0_MED) 
					, CELL_LON,CELL_LAT
					, SUM(POS_AS1_RSCP_CNT)
					, SUM(POS_AS1_ECN0_CNT)
-- 					,SUM(CALL_STATUS_BLOCK)
-- 					,SUM(CALL_STATUS_SUCCESS)
-- 					,SUM(CALL_STATUS_DROP)
-- 					,SUM(CALL_TYPE_SMS)
-- 					,SUM(CALL_TYPE_VOICE)
-- 					,SUM(CALL_TYPE_VEDIO)
-- 					,SUM(CALL_TYPE_PS99)
-- 					,SUM(CALL_TYPE_HSPA)
-- 					,SUM(CALL_TYPE_MRAB)
-- 					,SUM(CALL_TYPE_PSOTHERS)
-- 					,SUM(CALL_TYPE_CS)
-- 					,SUM(CALL_TYPE_PS)
				FROM ',GT_DB,RUN,'.`tmp_table_tile_1st_server_',WORKER_ID,'`
				GROUP BY  DATA_DATE
					, DATA_HOUR
-- 					, FREQUENCY
-- 					, UARFCN
					, INDOOR
					, MOVING
					#, TILE_ID
					, RNC_ID
-- 					, CELL_INDOOR
-- 					, CLUSTER_ID
-- 					, SITE_ID
					, CELL_ID
					, CELL_NAME
					, CALL_TYPE 
					, CALL_STATUS
				ORDER BY NULL');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_1st_Server_AGR','Insert Data to table_tile_1st_server_def', NOW());
	SET @SqlCmd=CONCAT(' INSERT INTO  ',GT_DB,RUN,'.`table_tile_1st_server_def`
			     (DATA_DATE,DATA_HOUR,FREQUENCY,UARFCN,TILE_ID,RNC_ID,CELL_INDOOR,CLUSTER_ID,SITE_ID,
				CELL_ID,CELL_NAME,CALL_CNT,RSCP,ECN0, RSCP_MED,ECN0_MED, CELL_LON,CELL_LAT,POS_AS1_RSCP_CNT, POS_AS1_ECN0_CNT
-- 				,CALL_STATUS_BLOCK,CALL_STATUS_SUCCESS,CALL_STATUS_DROP,CALL_TYPE_SMS,CALL_TYPE_VOICE,CALL_TYPE_VEDIO
-- 					,CALL_TYPE_PS99,CALL_TYPE_HSPA,CALL_TYPE_MRAB,CALL_TYPE_PSOTHERS,CALL_TYPE_CS,CALL_TYPE_PS
	)
			    SELECT
					 DATA_DATE
					, DATA_HOUR
					, FREQUENCY
					, UARFCN
					#, INDOOR
					#, MOVING
					, TILE_ID
					, RNC_ID
					, CELL_INDOOR
					, CLUSTER_ID
					, SITE_ID
					, CELL_ID
					, CELL_NAME
					#, CALL_TYPE 
					#, CALL_STATUS
					, SUM(CALL_CNT) AS CALL_CNT
					,SUM(RSCP) AS RSCP
					,SUM(ECN0) AS ECN0
					, NULL #median(RSCP_MED) 
					, NULL #median(ECN0_MED) 
					, CELL_LON,CELL_LAT
					, SUM(POS_AS1_RSCP_CNT)
					, SUM(POS_AS1_ECN0_CNT)
-- 					,SUM(CALL_STATUS_BLOCK)
-- 					,SUM(CALL_STATUS_SUCCESS)
-- 					,SUM(CALL_STATUS_DROP)
-- 					,SUM(CALL_TYPE_SMS)
-- 					,SUM(CALL_TYPE_VOICE)
-- 					,SUM(CALL_TYPE_VEDIO)
-- 					,SUM(CALL_TYPE_PS99)
-- 					,SUM(CALL_TYPE_HSPA)
-- 					,SUM(CALL_TYPE_MRAB)
-- 					,SUM(CALL_TYPE_PSOTHERS)
-- 					,SUM(CALL_TYPE_CS)
-- 					,SUM(CALL_TYPE_PS)
				FROM ',GT_DB,RUN,'.`tmp_table_tile_1st_server_',WORKER_ID,'`
				GROUP BY  DATA_DATE
					, DATA_HOUR
					#, FREQUENCY
					#, UARFCN
					#, INDOOR
					#, MOVING
					, TILE_ID
					, RNC_ID
					#, CELL_INDOOR
					#, CLUSTER_ID
					#, SITE_ID
					, CELL_ID
					#, CALL_TYPE 
					#, CALL_STATUS
				ORDER BY NULL');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_1st_Server_AGR','Insert Data to table_tile_1st_server_t_def', NOW());
	SET @SqlCmd=CONCAT(' INSERT INTO  ',GT_DB,RUN,'.`table_tile_1st_server_t_def`
			     (DATA_DATE,DATA_HOUR,TILE_ID,RNC_ID,
				CALL_CNT,RSCP,ECN0, RSCP_MED,ECN0_MED, CELL_LON,CELL_LAT,POS_AS1_RSCP_CNT, POS_AS1_ECN0_CNT
-- 				,CALL_STATUS_BLOCK,CALL_STATUS_SUCCESS,CALL_STATUS_DROP,CALL_TYPE_SMS,CALL_TYPE_VOICE,CALL_TYPE_VEDIO
-- 					,CALL_TYPE_PS99,CALL_TYPE_HSPA,CALL_TYPE_MRAB,CALL_TYPE_PSOTHERS,CALL_TYPE_CS,CALL_TYPE_PS
	)
			    SELECT
					 DATA_DATE
					, DATA_HOUR
					#, FREQUENCY
					#, UARFCN
					#, INDOOR
					#, MOVING
					, TILE_ID
					, RNC_ID
					#, CELL_INDOOR
					#, CLUSTER_ID
					#, SITE_ID
					#, CELL_ID
					#, CALL_TYPE 
					#, CALL_STATUS
					, SUM(CALL_CNT) AS CALL_CNT
					,SUM(RSCP) AS RSCP
					,SUM(ECN0) AS ECN0
					, NULL #median(RSCP_MED) 
					, NULL #median(ECN0_MED) 
					, CELL_LON,CELL_LAT
					, SUM(POS_AS1_RSCP_CNT)
					, SUM(POS_AS1_ECN0_CNT)
-- 					,SUM(CALL_STATUS_BLOCK)
-- 					,SUM(CALL_STATUS_SUCCESS)
-- 					,SUM(CALL_STATUS_DROP)
-- 					,SUM(CALL_TYPE_SMS)
-- 					,SUM(CALL_TYPE_VOICE)
-- 					,SUM(CALL_TYPE_VEDIO)
-- 					,SUM(CALL_TYPE_PS99)
-- 					,SUM(CALL_TYPE_HSPA)
-- 					,SUM(CALL_TYPE_MRAB)
-- 					,SUM(CALL_TYPE_PSOTHERS)
-- 					,SUM(CALL_TYPE_CS)
-- 					,SUM(CALL_TYPE_PS)
				FROM ',GT_DB,RUN,'.`tmp_table_tile_1st_server_',WORKER_ID,'`
				GROUP BY  DATA_DATE
					, DATA_HOUR
					#, FREQUENCY
					#, UARFCN
					#, INDOOR
					#, MOVING
					, TILE_ID
					, RNC_ID
					#, CELL_INDOOR
					#, CLUSTER_ID
					#, SITE_ID
					#, CELL_ID
					#, CALL_TYPE 
					#, CALL_STATUS
				ORDER BY NULL');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_1st_Server_AGR','Insert Data to table_tile_1st_server_c_def', NOW());
	SET @SqlCmd=CONCAT(' INSERT INTO  ',GT_DB,RUN,'.`table_tile_1st_server_c_def`
			     (DATA_DATE,DATA_HOUR,FREQUENCY,UARFCN,RNC_ID,CELL_INDOOR,CLUSTER_ID,SITE_ID,
				CELL_ID,CELL_NAME,CALL_CNT,RSCP,ECN0, RSCP_MED,ECN0_MED, CELL_LON,CELL_LAT,POS_AS1_RSCP_CNT, POS_AS1_ECN0_CNT
-- 				,CALL_STATUS_BLOCK,CALL_STATUS_SUCCESS,CALL_STATUS_DROP,CALL_TYPE_SMS,CALL_TYPE_VOICE,CALL_TYPE_VEDIO
-- 					,CALL_TYPE_PS99,CALL_TYPE_HSPA,CALL_TYPE_MRAB,CALL_TYPE_PSOTHERS,CALL_TYPE_CS,CALL_TYPE_PS
	)
			    SELECT
					 DATA_DATE
					, DATA_HOUR
					, FREQUENCY
					, UARFCN
					#, INDOOR
					#, MOVING
					#, TILE_ID
					, RNC_ID
					, CELL_INDOOR
					, CLUSTER_ID
					, SITE_ID
					, CELL_ID
					, CELL_NAME
					#, CALL_TYPE 
					#, CALL_STATUS
					, SUM(CALL_CNT) AS CALL_CNT
					,SUM(RSCP) AS RSCP
					,SUM(ECN0) AS ECN0
					, NULL #median(RSCP_MED) 
					, NULL #median(ECN0_MED) 
					, CELL_LON,CELL_LAT
					, SUM(POS_AS1_RSCP_CNT)
					, SUM(POS_AS1_ECN0_CNT)
-- 					,SUM(CALL_STATUS_BLOCK)
-- 					,SUM(CALL_STATUS_SUCCESS)
-- 					,SUM(CALL_STATUS_DROP)
-- 					,SUM(CALL_TYPE_SMS)
-- 					,SUM(CALL_TYPE_VOICE)
-- 					,SUM(CALL_TYPE_VEDIO)
-- 					,SUM(CALL_TYPE_PS99)
-- 					,SUM(CALL_TYPE_HSPA)
-- 					,SUM(CALL_TYPE_MRAB)
-- 					,SUM(CALL_TYPE_PSOTHERS)
-- 					,SUM(CALL_TYPE_CS)
-- 					,SUM(CALL_TYPE_PS)
				FROM ',GT_DB,RUN,'.`tmp_table_tile_1st_server_',WORKER_ID,'`
				GROUP BY  DATA_DATE
					, DATA_HOUR
					#, FREQUENCY
					#, UARFCN
					#, INDOOR
					#, MOVING
					#, TILE_ID
					, RNC_ID
					#, CELL_INDOOR
					#, CLUSTER_ID
					#, SITE_ID
					, CELL_ID
					#, CALL_TYPE 
					#, CALL_STATUS
				ORDER BY NULL');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_1st_Server_AGR','Insert Data to table_tile_1st_server_dy', NOW());
	SET @SqlCmd=CONCAT('REPLACE INTO ',GT_DB,'.table_tile_1st_server_dy
 		(DATA_DATE,FREQUENCY,UARFCN,INDOOR,MOVING,TILE_ID,RNC_ID,CELL_INDOOR,CLUSTER_ID,SITE_ID,
		CELL_ID,CELL_NAME,CALL_TYPE,CALL_STATUS,CALL_CNT,RSCP,ECN0, RSCP_MED,ECN0_MED, CELL_LON,CELL_LAT,POS_AS1_RSCP_CNT, POS_AS1_ECN0_CNT
-- 				,CALL_STATUS_BLOCK,CALL_STATUS_SUCCESS,CALL_STATUS_DROP,CALL_TYPE_SMS,CALL_TYPE_VOICE,CALL_TYPE_VEDIO
-- 					,CALL_TYPE_PS99,CALL_TYPE_HSPA,CALL_TYPE_MRAB,CALL_TYPE_PSOTHERS,CALL_TYPE_CS,CALL_TYPE_PS
	)
 		SELECT
			 B.DATA_DATE
			#, DATA_HOUR
			, B.FREQUENCY
			, B.UARFCN
			, B.INDOOR
			, B.MOVING
			, B.TILE_ID
			, B.RNC_ID
			, B.CELL_INDOOR
			, B.CLUSTER_ID
			, B.SITE_ID
			, B.CELL_ID
			, B.CELL_NAME
			, B.CALL_TYPE 
			, B.CALL_STATUS
			, CASE WHEN A.CALL_CNT IS NULL AND B.CALL_CNT IS NULL THEN NULL ELSE IFNULL(A.CALL_CNT,0) + IFNULL(B.CALL_CNT,0) END AS CALL_CNT
			, CASE WHEN A.RSCP IS NULL AND B.RSCP IS NULL THEN NULL ELSE IFNULL(A.RSCP,0) + IFNULL(B.RSCP,0) END AS RSCP
			, CASE WHEN A.ECN0 IS NULL AND B.ECN0 IS NULL THEN NULL ELSE IFNULL(A.ECN0,0) + IFNULL(B.ECN0,0) END AS ECN0
			, NULL AS RSCP_MED #CASE WHEN A.RSCP_MED IS NULL THEN B.RSCP_MED WHEN B.RSCP_MED IS NULL THEN A.RSCP_MED ELSE (A.RSCP_MED + B.RSCP_MED)/2 END AS RSCP_MED
			, NULL AS ECN0_MED #CASE WHEN A.ECN0_MED IS NULL THEN B.ECN0_MED WHEN B.ECN0_MED IS NULL THEN A.ECN0_MED ELSE (A.ECN0_MED + B.ECN0_MED)/2 END AS ECN0_MED
			, B.CELL_LON,B.CELL_LAT
			, CASE WHEN A.POS_AS1_RSCP_CNT IS NULL AND B.POS_AS1_RSCP_CNT IS NULL THEN NULL ELSE IFNULL(A.POS_AS1_RSCP_CNT,0) + IFNULL(B.POS_AS1_RSCP_CNT,0) END AS POS_AS1_RSCP_CNT
			, CASE WHEN A.POS_AS1_ECN0_CNT IS NULL AND B.POS_AS1_ECN0_CNT IS NULL THEN NULL ELSE IFNULL(A.POS_AS1_ECN0_CNT,0) + IFNULL(B.POS_AS1_ECN0_CNT,0) END AS POS_AS1_ECN0_CNT
-- 			, CASE WHEN A.CALL_STATUS_BLOCK IS NULL AND B.CALL_STATUS_BLOCK IS NULL THEN NULL ELSE IFNULL(A.CALL_STATUS_BLOCK,0) + IFNULL(B.CALL_STATUS_BLOCK,0) END AS CALL_STATUS_BLOCK
-- 			, CASE WHEN A.CALL_STATUS_SUCCESS IS NULL AND B.CALL_STATUS_SUCCESS IS NULL THEN NULL ELSE IFNULL(A.CALL_STATUS_SUCCESS,0) + IFNULL(B.CALL_STATUS_SUCCESS,0) END AS CALL_STATUS_SUCCESS
-- 			, CASE WHEN A.CALL_STATUS_DROP IS NULL AND B.CALL_STATUS_DROP IS NULL THEN NULL ELSE IFNULL(A.CALL_STATUS_DROP,0) + IFNULL(B.CALL_STATUS_DROP,0) END AS CALL_STATUS_DROP
-- 			, CASE WHEN A.CALL_TYPE_SMS IS NULL AND B.CALL_TYPE_SMS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_SMS,0) + IFNULL(B.CALL_TYPE_SMS,0) END AS CALL_TYPE_SMS
-- 			, CASE WHEN A.CALL_TYPE_VOICE IS NULL AND B.CALL_TYPE_VOICE IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_VOICE,0) + IFNULL(B.CALL_TYPE_VOICE,0) END AS CALL_TYPE_VOICE
-- 			, CASE WHEN A.CALL_TYPE_VEDIO IS NULL AND B.CALL_TYPE_VEDIO IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_VEDIO,0) + IFNULL(B.CALL_TYPE_VEDIO,0) END AS CALL_TYPE_VEDIO
-- 			, CASE WHEN A.CALL_TYPE_PS99 IS NULL AND B.CALL_TYPE_PS99 IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_PS99,0) + IFNULL(B.CALL_TYPE_PS99,0) END AS CALL_TYPE_PS99
-- 			, CASE WHEN A.CALL_TYPE_HSPA IS NULL AND B.CALL_TYPE_HSPA IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_HSPA,0) + IFNULL(B.CALL_TYPE_HSPA,0) END AS CALL_TYPE_HSPA
-- 			, CASE WHEN A.CALL_TYPE_MRAB IS NULL AND B.CALL_TYPE_MRAB IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_MRAB,0) + IFNULL(B.CALL_TYPE_MRAB,0) END AS CALL_TYPE_MRAB
-- 			, CASE WHEN A.CALL_TYPE_PSOTHERS IS NULL AND B.CALL_TYPE_PSOTHERS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_PSOTHERS,0) + IFNULL(B.CALL_TYPE_PSOTHERS,0) END AS CALL_TYPE_PSOTHERS
-- 			, CASE WHEN A.CALL_TYPE_CS IS NULL AND B.CALL_TYPE_CS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_CS,0) + IFNULL(B.CALL_TYPE_CS,0) END AS CALL_TYPE_CS
-- 			, CASE WHEN A.CALL_TYPE_PS IS NULL AND B.CALL_TYPE_PS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_PS,0) + IFNULL(B.CALL_TYPE_PS,0) END AS CALL_TYPE_PS
		FROM ',GT_DB,'.table_tile_1st_server_dy a RIGHT JOIN 
		(
		 	SELECT
				 DATA_DATE AS DATA_DATE
				#, DATA_HOUR
				, FREQUENCY AS FREQUENCY
				, UARFCN AS UARFCN
				, INDOOR AS INDOOR
				, MOVING AS MOVING
				, TILE_ID AS TILE_ID
				, RNC_ID AS RNC_ID
				, CELL_INDOOR AS CELL_INDOOR
				, CLUSTER_ID AS CLUSTER_ID
				, SITE_ID AS SITE_ID
				, CELL_ID AS CELL_ID
				, CELL_NAME AS CELL_NAME
				, CALL_TYPE AS CALL_TYPE
				, CALL_STATUS AS CALL_STATUS
				, SUM(CALL_CNT) AS CALL_CNT
				, SUM(RSCP) AS RSCP
				, SUM(ECN0) AS ECN0
				, NULL AS RSCP_MED #median(RSCP_MED) AS RSCP_MED
				, NULL AS ECN0_MED #median(ECN0_MED) AS ECN0_MED
				, CELL_LON,CELL_LAT
				, SUM(POS_AS1_RSCP_CNT) AS POS_AS1_RSCP_CNT
				, SUM(POS_AS1_ECN0_CNT) AS POS_AS1_ECN0_CNT
-- 				,SUM(CALL_STATUS_BLOCK) AS CALL_STATUS_BLOCK
-- 				,SUM(CALL_STATUS_SUCCESS) AS CALL_STATUS_SUCCESS
-- 				,SUM(CALL_STATUS_DROP) AS CALL_STATUS_DROP
-- 				,SUM(CALL_TYPE_SMS) AS CALL_TYPE_SMS     
-- 				,SUM(CALL_TYPE_VOICE) AS CALL_TYPE_VOICE   
-- 				,SUM(CALL_TYPE_VEDIO) AS CALL_TYPE_VEDIO   
-- 				,SUM(CALL_TYPE_PS99) AS CALL_TYPE_PS99    
-- 				,SUM(CALL_TYPE_HSPA) AS CALL_TYPE_HSPA    
-- 				,SUM(CALL_TYPE_MRAB) AS CALL_TYPE_MRAB    
-- 				,SUM(CALL_TYPE_PSOTHERS) AS CALL_TYPE_PSOTHERS
-- 				,SUM(CALL_TYPE_CS) AS CALL_TYPE_CS      
-- 				,SUM(CALL_TYPE_PS) AS CALL_TYPE_PS
			FROM ',GT_DB,RUN,'.`tmp_table_tile_1st_server_',WORKER_ID,'`
			GROUP BY 
				DATA_DATE
				#, DATA_HOUR
				, FREQUENCY
-- 				, UARFCN
-- 				, INDOOR
				, MOVING
				, TILE_ID
				, RNC_ID
-- 				, CELL_INDOOR
-- 				, CLUSTER_ID
-- 				, SITE_ID
				, CELL_ID
				, CALL_TYPE 
				, CALL_STATUS
		) B
		ON  A.DATA_DATE=B.DATA_DATE
		AND A.FREQUENCY=B.FREQUENCY
-- 		AND A.UARFCN=B.UARFCN
-- 		AND A.INDOOR=B.INDOOR
		AND A.MOVING=B.MOVING
		AND A.TILE_ID=B.TILE_ID
		AND A.RNC_ID=B.RNC_ID
-- 		AND A.CELL_INDOOR=B.CELL_INDOOR
-- 		AND A.CLUSTER_ID=B.CLUSTER_ID
-- 		AND A.SITE_ID=B.SITE_ID
		AND A.CELL_ID=B.CELL_ID
		AND A.CALL_TYPE=B.CALL_TYPE
		AND A.CALL_STATUS=B.CALL_STATUS
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_1st_Server_AGR','Insert Data to table_tile_1st_server_dy_t', NOW());
	SET @SqlCmd=CONCAT('REPLACE INTO ',GT_DB,'.table_tile_1st_server_dy_t
 		(DATA_DATE,FREQUENCY,UARFCN,INDOOR,MOVING,TILE_ID,RNC_ID,
		CALL_TYPE,CALL_STATUS,CALL_CNT,RSCP,ECN0, RSCP_MED,ECN0_MED,POS_AS1_RSCP_CNT, POS_AS1_ECN0_CNT
-- 				,CALL_STATUS_BLOCK,CALL_STATUS_SUCCESS,CALL_STATUS_DROP,CALL_TYPE_SMS,CALL_TYPE_VOICE,CALL_TYPE_VEDIO
-- 					,CALL_TYPE_PS99,CALL_TYPE_HSPA,CALL_TYPE_MRAB,CALL_TYPE_PSOTHERS,CALL_TYPE_CS,CALL_TYPE_PS
	)
 		SELECT
			 B.DATA_DATE
			#, DATA_HOUR
			, B.FREQUENCY
			, B.UARFCN
			, B.INDOOR
			, B.MOVING
			, B.TILE_ID
			, B.RNC_ID
			#, B.CELL_INDOOR
			#, B.CLUSTER_ID
			#, B.SITE_ID
			#, B.CELL_ID
			, B.CALL_TYPE 
			, B.CALL_STATUS
			, CASE WHEN A.CALL_CNT IS NULL AND B.CALL_CNT IS NULL THEN NULL ELSE IFNULL(A.CALL_CNT,0) + IFNULL(B.CALL_CNT,0) END AS CALL_CNT
			, CASE WHEN A.RSCP IS NULL AND B.RSCP IS NULL THEN NULL ELSE IFNULL(A.RSCP,0) + IFNULL(B.RSCP,0) END AS RSCP
			, CASE WHEN A.ECN0 IS NULL AND B.ECN0 IS NULL THEN NULL ELSE IFNULL(A.ECN0,0) + IFNULL(B.ECN0,0) END AS ECN0
			, NULL AS RSCP_MED #CASE WHEN A.RSCP_MED IS NULL THEN B.RSCP_MED WHEN B.RSCP_MED IS NULL THEN A.RSCP_MED ELSE (A.RSCP_MED + B.RSCP_MED)/2 END AS RSCP_MED
			, NULL AS ECN0_MED #CASE WHEN A.ECN0_MED IS NULL THEN B.ECN0_MED WHEN B.ECN0_MED IS NULL THEN A.ECN0_MED ELSE (A.ECN0_MED + B.ECN0_MED)/2 END AS ECN0_MED
			, CASE WHEN A.POS_AS1_RSCP_CNT IS NULL AND B.POS_AS1_RSCP_CNT IS NULL THEN NULL ELSE IFNULL(A.POS_AS1_RSCP_CNT,0) + IFNULL(B.POS_AS1_RSCP_CNT,0) END AS POS_AS1_RSCP_CNT
			, CASE WHEN A.POS_AS1_ECN0_CNT IS NULL AND B.POS_AS1_ECN0_CNT IS NULL THEN NULL ELSE IFNULL(A.POS_AS1_ECN0_CNT,0) + IFNULL(B.POS_AS1_ECN0_CNT,0) END AS POS_AS1_ECN0_CNT
-- 			, CASE WHEN A.CALL_STATUS_BLOCK IS NULL AND B.CALL_STATUS_BLOCK IS NULL THEN NULL ELSE IFNULL(A.CALL_STATUS_BLOCK,0) + IFNULL(B.CALL_STATUS_BLOCK,0) END AS CALL_STATUS_BLOCK
-- 			, CASE WHEN A.CALL_STATUS_SUCCESS IS NULL AND B.CALL_STATUS_SUCCESS IS NULL THEN NULL ELSE IFNULL(A.CALL_STATUS_SUCCESS,0) + IFNULL(B.CALL_STATUS_SUCCESS,0) END AS CALL_STATUS_SUCCESS
-- 			, CASE WHEN A.CALL_STATUS_DROP IS NULL AND B.CALL_STATUS_DROP IS NULL THEN NULL ELSE IFNULL(A.CALL_STATUS_DROP,0) + IFNULL(B.CALL_STATUS_DROP,0) END AS CALL_STATUS_DROP
-- 			, CASE WHEN A.CALL_TYPE_SMS IS NULL AND B.CALL_TYPE_SMS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_SMS,0) + IFNULL(B.CALL_TYPE_SMS,0) END AS CALL_TYPE_SMS
-- 			, CASE WHEN A.CALL_TYPE_VOICE IS NULL AND B.CALL_TYPE_VOICE IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_VOICE,0) + IFNULL(B.CALL_TYPE_VOICE,0) END AS CALL_TYPE_VOICE
-- 			, CASE WHEN A.CALL_TYPE_VEDIO IS NULL AND B.CALL_TYPE_VEDIO IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_VEDIO,0) + IFNULL(B.CALL_TYPE_VEDIO,0) END AS CALL_TYPE_VEDIO
-- 			, CASE WHEN A.CALL_TYPE_PS99 IS NULL AND B.CALL_TYPE_PS99 IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_PS99,0) + IFNULL(B.CALL_TYPE_PS99,0) END AS CALL_TYPE_PS99
-- 			, CASE WHEN A.CALL_TYPE_HSPA IS NULL AND B.CALL_TYPE_HSPA IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_HSPA,0) + IFNULL(B.CALL_TYPE_HSPA,0) END AS CALL_TYPE_HSPA
-- 			, CASE WHEN A.CALL_TYPE_MRAB IS NULL AND B.CALL_TYPE_MRAB IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_MRAB,0) + IFNULL(B.CALL_TYPE_MRAB,0) END AS CALL_TYPE_MRAB
-- 			, CASE WHEN A.CALL_TYPE_PSOTHERS IS NULL AND B.CALL_TYPE_PSOTHERS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_PSOTHERS,0) + IFNULL(B.CALL_TYPE_PSOTHERS,0) END AS CALL_TYPE_PSOTHERS
-- 			, CASE WHEN A.CALL_TYPE_CS IS NULL AND B.CALL_TYPE_CS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_CS,0) + IFNULL(B.CALL_TYPE_CS,0) END AS CALL_TYPE_CS
-- 			, CASE WHEN A.CALL_TYPE_PS IS NULL AND B.CALL_TYPE_PS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_PS,0) + IFNULL(B.CALL_TYPE_PS,0) END AS CALL_TYPE_PS
		FROM ',GT_DB,'.table_tile_1st_server_dy_t a RIGHT JOIN 
		(
		 	SELECT
				 DATA_DATE AS DATA_DATE
				#, DATA_HOUR
				, FREQUENCY AS FREQUENCY
				, UARFCN AS UARFCN
				, INDOOR AS INDOOR
				, MOVING AS MOVING
				, TILE_ID AS TILE_ID
				, RNC_ID AS RNC_ID
				#, CELL_INDOOR AS CELL_INDOOR
				#, CLUSTER_ID AS CLUSTER_ID
				#, SITE_ID AS SITE_ID
				#, CELL_ID AS CELL_ID
				, CALL_TYPE AS CALL_TYPE
				, CALL_STATUS AS CALL_STATUS
				, SUM(CALL_CNT) AS CALL_CNT
				, SUM(RSCP) AS RSCP
				, SUM(ECN0) AS ECN0
				, NULL AS RSCP_MED #median(RSCP_MED) AS RSCP_MED
				, NULL AS ECN0_MED #median(ECN0_MED) AS ECN0_MED
				, SUM(POS_AS1_RSCP_CNT) AS POS_AS1_RSCP_CNT
				, SUM(POS_AS1_ECN0_CNT) AS POS_AS1_ECN0_CNT
-- 				,SUM(CALL_STATUS_BLOCK) AS CALL_STATUS_BLOCK
-- 				,SUM(CALL_STATUS_SUCCESS) AS CALL_STATUS_SUCCESS
-- 				,SUM(CALL_STATUS_DROP) AS CALL_STATUS_DROP
-- 				,SUM(CALL_TYPE_SMS) AS CALL_TYPE_SMS     
-- 				,SUM(CALL_TYPE_VOICE) AS CALL_TYPE_VOICE   
-- 				,SUM(CALL_TYPE_VEDIO) AS CALL_TYPE_VEDIO   
-- 				,SUM(CALL_TYPE_PS99) AS CALL_TYPE_PS99    
-- 				,SUM(CALL_TYPE_HSPA) AS CALL_TYPE_HSPA    
-- 				,SUM(CALL_TYPE_MRAB) AS CALL_TYPE_MRAB    
-- 				,SUM(CALL_TYPE_PSOTHERS) AS CALL_TYPE_PSOTHERS
-- 				,SUM(CALL_TYPE_CS) AS CALL_TYPE_CS      
-- 				,SUM(CALL_TYPE_PS) AS CALL_TYPE_PS
			FROM ',GT_DB,RUN,'.`tmp_table_tile_1st_server_',WORKER_ID,'`
			GROUP BY 
				DATA_DATE
				#, DATA_HOUR
-- 				, FREQUENCY
-- 				, UARFCN
				, INDOOR
				, MOVING
				, TILE_ID
				, RNC_ID
				#, CELL_INDOOR
				#, CLUSTER_ID
				#, SITE_ID
				#, CELL_ID
				, CALL_TYPE 
				, CALL_STATUS
		) B
		ON  A.DATA_DATE=B.DATA_DATE
-- 		AND A.FREQUENCY=B.FREQUENCY
-- 		AND A.UARFCN=B.UARFCN
		AND A.INDOOR=B.INDOOR
		AND A.MOVING=B.MOVING
		AND A.TILE_ID=B.TILE_ID
		AND A.RNC_ID=B.RNC_ID
		#AND A.CELL_INDOOR=B.CELL_INDOOR
		#AND A.CLUSTER_ID=B.CLUSTER_ID
		#AND A.SITE_ID=B.SITE_ID
		#AND A.CELL_ID=B.CELL_ID
		AND A.CALL_TYPE=B.CALL_TYPE
		AND A.CALL_STATUS=B.CALL_STATUS
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_1st_Server_AGR','Insert Data to table_tile_1st_server_dy_c', NOW());
	SET @SqlCmd=CONCAT('REPLACE INTO ',GT_DB,'.table_tile_1st_server_dy_c
 		(DATA_DATE,FREQUENCY,UARFCN,INDOOR,MOVING,RNC_ID,CELL_INDOOR,CLUSTER_ID,SITE_ID,
		CELL_ID,CELL_NAME,CALL_TYPE,CALL_STATUS,CALL_CNT,RSCP,ECN0, RSCP_MED,ECN0_MED, CELL_LON,CELL_LAT,POS_AS1_RSCP_CNT, POS_AS1_ECN0_CNT
-- 				,CALL_STATUS_BLOCK,CALL_STATUS_SUCCESS,CALL_STATUS_DROP,CALL_TYPE_SMS,CALL_TYPE_VOICE,CALL_TYPE_VEDIO
-- 					,CALL_TYPE_PS99,CALL_TYPE_HSPA,CALL_TYPE_MRAB,CALL_TYPE_PSOTHERS,CALL_TYPE_CS,CALL_TYPE_PS
	)
 		SELECT
			 B.DATA_DATE
			#, DATA_HOUR
			, B.FREQUENCY
			, B.UARFCN
			, B.INDOOR
			, B.MOVING
			#, B.TILE_ID
			, B.RNC_ID
			, B.CELL_INDOOR
			, B.CLUSTER_ID
			, B.SITE_ID
			, B.CELL_ID
			, B.CELL_NAME
			, B.CALL_TYPE 
			, B.CALL_STATUS
			, CASE WHEN A.CALL_CNT IS NULL AND B.CALL_CNT IS NULL THEN NULL ELSE IFNULL(A.CALL_CNT,0) + IFNULL(B.CALL_CNT,0) END AS CALL_CNT
			, CASE WHEN A.RSCP IS NULL AND B.RSCP IS NULL THEN NULL ELSE IFNULL(A.RSCP,0) + IFNULL(B.RSCP,0) END AS RSCP
			, CASE WHEN A.ECN0 IS NULL AND B.ECN0 IS NULL THEN NULL ELSE IFNULL(A.ECN0,0) + IFNULL(B.ECN0,0) END AS ECN0
			, NULL AS RSCP_MED #CASE WHEN A.RSCP_MED IS NULL THEN B.RSCP_MED WHEN B.RSCP_MED IS NULL THEN A.RSCP_MED ELSE (A.RSCP_MED + B.RSCP_MED)/2 END AS RSCP_MED
			, NULL AS ECN0_MED #CASE WHEN A.ECN0_MED IS NULL THEN B.ECN0_MED WHEN B.ECN0_MED IS NULL THEN A.ECN0_MED ELSE (A.ECN0_MED + B.ECN0_MED)/2 END AS ECN0_MED
			, B.CELL_LON,B.CELL_LAT
			, CASE WHEN A.POS_AS1_RSCP_CNT IS NULL AND B.POS_AS1_RSCP_CNT IS NULL THEN NULL ELSE IFNULL(A.POS_AS1_RSCP_CNT,0) + IFNULL(B.POS_AS1_RSCP_CNT,0) END AS POS_AS1_RSCP_CNT
			, CASE WHEN A.POS_AS1_ECN0_CNT IS NULL AND B.POS_AS1_ECN0_CNT IS NULL THEN NULL ELSE IFNULL(A.POS_AS1_ECN0_CNT,0) + IFNULL(B.POS_AS1_ECN0_CNT,0) END AS POS_AS1_ECN0_CNT
-- 			, CASE WHEN A.CALL_STATUS_BLOCK IS NULL AND B.CALL_STATUS_BLOCK IS NULL THEN NULL ELSE IFNULL(A.CALL_STATUS_BLOCK,0) + IFNULL(B.CALL_STATUS_BLOCK,0) END AS CALL_STATUS_BLOCK
-- 			, CASE WHEN A.CALL_STATUS_SUCCESS IS NULL AND B.CALL_STATUS_SUCCESS IS NULL THEN NULL ELSE IFNULL(A.CALL_STATUS_SUCCESS,0) + IFNULL(B.CALL_STATUS_SUCCESS,0) END AS CALL_STATUS_SUCCESS
-- 			, CASE WHEN A.CALL_STATUS_DROP IS NULL AND B.CALL_STATUS_DROP IS NULL THEN NULL ELSE IFNULL(A.CALL_STATUS_DROP,0) + IFNULL(B.CALL_STATUS_DROP,0) END AS CALL_STATUS_DROP
-- 			, CASE WHEN A.CALL_TYPE_SMS IS NULL AND B.CALL_TYPE_SMS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_SMS,0) + IFNULL(B.CALL_TYPE_SMS,0) END AS CALL_TYPE_SMS
-- 			, CASE WHEN A.CALL_TYPE_VOICE IS NULL AND B.CALL_TYPE_VOICE IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_VOICE,0) + IFNULL(B.CALL_TYPE_VOICE,0) END AS CALL_TYPE_VOICE
-- 			, CASE WHEN A.CALL_TYPE_VEDIO IS NULL AND B.CALL_TYPE_VEDIO IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_VEDIO,0) + IFNULL(B.CALL_TYPE_VEDIO,0) END AS CALL_TYPE_VEDIO
-- 			, CASE WHEN A.CALL_TYPE_PS99 IS NULL AND B.CALL_TYPE_PS99 IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_PS99,0) + IFNULL(B.CALL_TYPE_PS99,0) END AS CALL_TYPE_PS99
-- 			, CASE WHEN A.CALL_TYPE_HSPA IS NULL AND B.CALL_TYPE_HSPA IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_HSPA,0) + IFNULL(B.CALL_TYPE_HSPA,0) END AS CALL_TYPE_HSPA
-- 			, CASE WHEN A.CALL_TYPE_MRAB IS NULL AND B.CALL_TYPE_MRAB IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_MRAB,0) + IFNULL(B.CALL_TYPE_MRAB,0) END AS CALL_TYPE_MRAB
-- 			, CASE WHEN A.CALL_TYPE_PSOTHERS IS NULL AND B.CALL_TYPE_PSOTHERS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_PSOTHERS,0) + IFNULL(B.CALL_TYPE_PSOTHERS,0) END AS CALL_TYPE_PSOTHERS
-- 			, CASE WHEN A.CALL_TYPE_CS IS NULL AND B.CALL_TYPE_CS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_CS,0) + IFNULL(B.CALL_TYPE_CS,0) END AS CALL_TYPE_CS
-- 			, CASE WHEN A.CALL_TYPE_PS IS NULL AND B.CALL_TYPE_PS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_PS,0) + IFNULL(B.CALL_TYPE_PS,0) END AS CALL_TYPE_PS
		FROM ',GT_DB,'.table_tile_1st_server_dy_c a RIGHT JOIN 
		(
		 	SELECT
				 DATA_DATE AS DATA_DATE
				#, DATA_HOUR
				, FREQUENCY AS FREQUENCY
				, UARFCN AS UARFCN
				, INDOOR AS INDOOR
				, MOVING AS MOVING
				#, TILE_ID AS TILE_ID
				, RNC_ID AS RNC_ID
				, CELL_INDOOR AS CELL_INDOOR
				, CLUSTER_ID AS CLUSTER_ID
				, SITE_ID AS SITE_ID
				, CELL_ID AS CELL_ID
				, CELL_NAME AS CELL_NAME
				, CALL_TYPE AS CALL_TYPE
				, CALL_STATUS AS CALL_STATUS
				, SUM(CALL_CNT) AS CALL_CNT
				, SUM(RSCP) AS RSCP
				, SUM(ECN0) AS ECN0
				, NULL AS RSCP_MED #median(RSCP_MED) AS RSCP_MED
				, NULL AS ECN0_MED #median(ECN0_MED) AS ECN0_MED
				, CELL_LON,CELL_LAT
				, SUM(POS_AS1_RSCP_CNT) AS POS_AS1_RSCP_CNT
				, SUM(POS_AS1_ECN0_CNT) AS POS_AS1_ECN0_CNT
-- 				,SUM(CALL_STATUS_BLOCK) AS CALL_STATUS_BLOCK
-- 				,SUM(CALL_STATUS_SUCCESS) AS CALL_STATUS_SUCCESS
-- 				,SUM(CALL_STATUS_DROP) AS CALL_STATUS_DROP
-- 				,SUM(CALL_TYPE_SMS) AS CALL_TYPE_SMS     
-- 				,SUM(CALL_TYPE_VOICE) AS CALL_TYPE_VOICE   
-- 				,SUM(CALL_TYPE_VEDIO) AS CALL_TYPE_VEDIO   
-- 				,SUM(CALL_TYPE_PS99) AS CALL_TYPE_PS99    
-- 				,SUM(CALL_TYPE_HSPA) AS CALL_TYPE_HSPA    
-- 				,SUM(CALL_TYPE_MRAB) AS CALL_TYPE_MRAB    
-- 				,SUM(CALL_TYPE_PSOTHERS) AS CALL_TYPE_PSOTHERS
-- 				,SUM(CALL_TYPE_CS) AS CALL_TYPE_CS      
-- 				,SUM(CALL_TYPE_PS) AS CALL_TYPE_PS
			FROM ',GT_DB,RUN,'.`tmp_table_tile_1st_server_',WORKER_ID,'`
			GROUP BY 
				DATA_DATE
				#, DATA_HOUR
-- 				, FREQUENCY
-- 				, UARFCN
				, INDOOR
				, MOVING
				#, TILE_ID
				, RNC_ID
-- 				, CELL_INDOOR
-- 				, CLUSTER_ID
-- 				, SITE_ID
				, CELL_ID
				, CALL_TYPE 
				, CALL_STATUS
		) B
		ON  A.DATA_DATE=B.DATA_DATE
-- 		AND A.FREQUENCY=B.FREQUENCY
-- 		AND A.UARFCN=B.UARFCN
		AND A.INDOOR=B.INDOOR
		AND A.MOVING=B.MOVING
		#AND A.TILE_ID=B.TILE_ID
		AND A.RNC_ID=B.RNC_ID
-- 		AND A.CELL_INDOOR=B.CELL_INDOOR
-- 		AND A.CLUSTER_ID=B.CLUSTER_ID
-- 		AND A.SITE_ID=B.SITE_ID
		AND A.CELL_ID=B.CELL_ID
		AND A.CALL_TYPE=B.CALL_TYPE
		AND A.CALL_STATUS=B.CALL_STATUS
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_1st_Server_AGR','Insert Data to table_tile_1st_server_dy_def', NOW());
	SET @SqlCmd=CONCAT('REPLACE INTO ',GT_DB,'.table_tile_1st_server_dy_def
 		(DATA_DATE,TILE_ID,FREQUENCY,UARFCN,RNC_ID,CELL_INDOOR,CLUSTER_ID,SITE_ID,
		CELL_ID,CELL_NAME,CALL_CNT,RSCP,ECN0, RSCP_MED,ECN0_MED, CELL_LON,CELL_LAT,POS_AS1_RSCP_CNT, POS_AS1_ECN0_CNT
-- 				,CALL_STATUS_BLOCK,CALL_STATUS_SUCCESS,CALL_STATUS_DROP,CALL_TYPE_SMS,CALL_TYPE_VOICE,CALL_TYPE_VEDIO
-- 					,CALL_TYPE_PS99,CALL_TYPE_HSPA,CALL_TYPE_MRAB,CALL_TYPE_PSOTHERS,CALL_TYPE_CS,CALL_TYPE_PS
	)
 		SELECT
			 B.DATA_DATE
			#, DATA_HOUR
			, B.FREQUENCY
			, B.UARFCN
			#, B.INDOOR
			#, B.MOVING
			, B.TILE_ID
			, B.RNC_ID
			, B.CELL_INDOOR
			, B.CLUSTER_ID
			, B.SITE_ID
			, B.CELL_ID
			, B.CELL_NAME
			#, B.CALL_TYPE 
			#, B.CALL_STATUS
			, CASE WHEN A.CALL_CNT IS NULL AND B.CALL_CNT IS NULL THEN NULL ELSE IFNULL(A.CALL_CNT,0) + IFNULL(B.CALL_CNT,0) END AS CALL_CNT
			, CASE WHEN A.RSCP IS NULL AND B.RSCP IS NULL THEN NULL ELSE IFNULL(A.RSCP,0) + IFNULL(B.RSCP,0) END AS RSCP
			, CASE WHEN A.ECN0 IS NULL AND B.ECN0 IS NULL THEN NULL ELSE IFNULL(A.ECN0,0) + IFNULL(B.ECN0,0) END AS ECN0
			, NULL AS RSCP_MED #CASE WHEN A.RSCP_MED IS NULL THEN B.RSCP_MED WHEN B.RSCP_MED IS NULL THEN A.RSCP_MED ELSE (A.RSCP_MED + B.RSCP_MED)/2 END AS RSCP_MED
			, NULL AS ECN0_MED #CASE WHEN A.ECN0_MED IS NULL THEN B.ECN0_MED WHEN B.ECN0_MED IS NULL THEN A.ECN0_MED ELSE (A.ECN0_MED + B.ECN0_MED)/2 END AS ECN0_MED
			, B.CELL_LON,B.CELL_LAT
			, CASE WHEN A.POS_AS1_RSCP_CNT IS NULL AND B.POS_AS1_RSCP_CNT IS NULL THEN NULL ELSE IFNULL(A.POS_AS1_RSCP_CNT,0) + IFNULL(B.POS_AS1_RSCP_CNT,0) END AS POS_AS1_RSCP_CNT
			, CASE WHEN A.POS_AS1_ECN0_CNT IS NULL AND B.POS_AS1_ECN0_CNT IS NULL THEN NULL ELSE IFNULL(A.POS_AS1_ECN0_CNT,0) + IFNULL(B.POS_AS1_ECN0_CNT,0) END AS POS_AS1_ECN0_CNT
-- 			, CASE WHEN A.CALL_STATUS_BLOCK IS NULL AND B.CALL_STATUS_BLOCK IS NULL THEN NULL ELSE IFNULL(A.CALL_STATUS_BLOCK,0) + IFNULL(B.CALL_STATUS_BLOCK,0) END AS CALL_STATUS_BLOCK
-- 			, CASE WHEN A.CALL_STATUS_SUCCESS IS NULL AND B.CALL_STATUS_SUCCESS IS NULL THEN NULL ELSE IFNULL(A.CALL_STATUS_SUCCESS,0) + IFNULL(B.CALL_STATUS_SUCCESS,0) END AS CALL_STATUS_SUCCESS
-- 			, CASE WHEN A.CALL_STATUS_DROP IS NULL AND B.CALL_STATUS_DROP IS NULL THEN NULL ELSE IFNULL(A.CALL_STATUS_DROP,0) + IFNULL(B.CALL_STATUS_DROP,0) END AS CALL_STATUS_DROP
-- 			, CASE WHEN A.CALL_TYPE_SMS IS NULL AND B.CALL_TYPE_SMS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_SMS,0) + IFNULL(B.CALL_TYPE_SMS,0) END AS CALL_TYPE_SMS
-- 			, CASE WHEN A.CALL_TYPE_VOICE IS NULL AND B.CALL_TYPE_VOICE IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_VOICE,0) + IFNULL(B.CALL_TYPE_VOICE,0) END AS CALL_TYPE_VOICE
-- 			, CASE WHEN A.CALL_TYPE_VEDIO IS NULL AND B.CALL_TYPE_VEDIO IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_VEDIO,0) + IFNULL(B.CALL_TYPE_VEDIO,0) END AS CALL_TYPE_VEDIO
-- 			, CASE WHEN A.CALL_TYPE_PS99 IS NULL AND B.CALL_TYPE_PS99 IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_PS99,0) + IFNULL(B.CALL_TYPE_PS99,0) END AS CALL_TYPE_PS99
-- 			, CASE WHEN A.CALL_TYPE_HSPA IS NULL AND B.CALL_TYPE_HSPA IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_HSPA,0) + IFNULL(B.CALL_TYPE_HSPA,0) END AS CALL_TYPE_HSPA
-- 			, CASE WHEN A.CALL_TYPE_MRAB IS NULL AND B.CALL_TYPE_MRAB IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_MRAB,0) + IFNULL(B.CALL_TYPE_MRAB,0) END AS CALL_TYPE_MRAB
-- 			, CASE WHEN A.CALL_TYPE_PSOTHERS IS NULL AND B.CALL_TYPE_PSOTHERS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_PSOTHERS,0) + IFNULL(B.CALL_TYPE_PSOTHERS,0) END AS CALL_TYPE_PSOTHERS
-- 			, CASE WHEN A.CALL_TYPE_CS IS NULL AND B.CALL_TYPE_CS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_CS,0) + IFNULL(B.CALL_TYPE_CS,0) END AS CALL_TYPE_CS
-- 			, CASE WHEN A.CALL_TYPE_PS IS NULL AND B.CALL_TYPE_PS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_PS,0) + IFNULL(B.CALL_TYPE_PS,0) END AS CALL_TYPE_PS
		FROM ',GT_DB,'.table_tile_1st_server_dy_def a RIGHT JOIN 
		(
		 	SELECT
				 DATA_DATE AS DATA_DATE
				#, DATA_HOUR
				, FREQUENCY AS FREQUENCY
				, UARFCN AS UARFCN
				#, INDOOR AS INDOOR
				#, MOVING AS MOVING
				, TILE_ID AS TILE_ID
				, RNC_ID AS RNC_ID
				, CELL_INDOOR AS CELL_INDOOR
				, CLUSTER_ID AS CLUSTER_ID
				, SITE_ID AS SITE_ID
				, CELL_ID AS CELL_ID
				, CELL_NAME AS CELL_NAME
				#, CALL_TYPE AS CALL_TYPE
				#, CALL_STATUS AS CALL_STATUS
				, SUM(CALL_CNT) AS CALL_CNT
				, SUM(RSCP) AS RSCP
				, SUM(ECN0) AS ECN0
				, NULL AS RSCP_MED #median(RSCP_MED) AS RSCP_MED
				, NULL AS ECN0_MED #median(ECN0_MED) AS ECN0_MED
				, CELL_LON,CELL_LAT
				, SUM(POS_AS1_RSCP_CNT) AS POS_AS1_RSCP_CNT
				, SUM(POS_AS1_ECN0_CNT) AS POS_AS1_ECN0_CNT
-- 				,SUM(CALL_STATUS_BLOCK) AS CALL_STATUS_BLOCK
-- 				,SUM(CALL_STATUS_SUCCESS) AS CALL_STATUS_SUCCESS
-- 				,SUM(CALL_STATUS_DROP) AS CALL_STATUS_DROP
-- 				,SUM(CALL_TYPE_SMS) AS CALL_TYPE_SMS     
-- 				,SUM(CALL_TYPE_VOICE) AS CALL_TYPE_VOICE   
-- 				,SUM(CALL_TYPE_VEDIO) AS CALL_TYPE_VEDIO   
-- 				,SUM(CALL_TYPE_PS99) AS CALL_TYPE_PS99    
-- 				,SUM(CALL_TYPE_HSPA) AS CALL_TYPE_HSPA    
-- 				,SUM(CALL_TYPE_MRAB) AS CALL_TYPE_MRAB    
-- 				,SUM(CALL_TYPE_PSOTHERS) AS CALL_TYPE_PSOTHERS
-- 				,SUM(CALL_TYPE_CS) AS CALL_TYPE_CS      
-- 				,SUM(CALL_TYPE_PS) AS CALL_TYPE_PS
			FROM ',GT_DB,RUN,'.`tmp_table_tile_1st_server_',WORKER_ID,'`
			GROUP BY 
				DATA_DATE
				#, DATA_HOUR
				#, FREQUENCY
				#, UARFCN
				#, INDOOR
				#, MOVING
				, TILE_ID
				, RNC_ID
				#, CELL_INDOOR
				#, CLUSTER_ID
				#, SITE_ID
				, CELL_ID
				#, CALL_TYPE 
				#, CALL_STATUS
		) B
		ON  A.DATA_DATE=B.DATA_DATE
		#AND A.FREQUENCY=B.FREQUENCY
		#AND A.UARFCN=B.UARFCN
		#AND A.INDOOR=B.INDOOR
		#AND A.MOVING=B.MOVING
		AND A.TILE_ID=B.TILE_ID
		AND A.RNC_ID=B.RNC_ID
		#AND A.CELL_INDOOR=B.CELL_INDOOR
		#AND A.CLUSTER_ID=B.CLUSTER_ID
		#AND A.SITE_ID=B.SITE_ID
		AND A.CELL_ID=B.CELL_ID
		#AND A.CALL_TYPE=B.CALL_TYPE
		#AND A.CALL_STATUS=B.CALL_STATUS
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_1st_Server_AGR','Insert Data to table_tile_1st_server_dy_t_def', NOW());
	SET @SqlCmd=CONCAT('REPLACE INTO ',GT_DB,'.table_tile_1st_server_dy_t_def
 		(DATA_DATE,TILE_ID,RNC_ID,
		CALL_CNT,RSCP,ECN0, RSCP_MED,ECN0_MED,POS_AS1_RSCP_CNT,POS_AS1_ECN0_CNT
-- 				,CALL_STATUS_BLOCK,CALL_STATUS_SUCCESS,CALL_STATUS_DROP,CALL_TYPE_SMS,CALL_TYPE_VOICE,CALL_TYPE_VEDIO
-- 					,CALL_TYPE_PS99,CALL_TYPE_HSPA,CALL_TYPE_MRAB,CALL_TYPE_PSOTHERS,CALL_TYPE_CS,CALL_TYPE_PS
	)
 		SELECT
			 B.DATA_DATE
			#, DATA_HOUR
			#, B.FREQUENCY
			#, B.UARFCN
			#, B.INDOOR
			#, B.MOVING
			, B.TILE_ID
			, B.RNC_ID
			#, B.CELL_INDOOR
			#, B.CLUSTER_ID
			#, B.SITE_ID
			#, B.CELL_ID
			#, B.CALL_TYPE 
			#, B.CALL_STATUS
			, CASE WHEN A.CALL_CNT IS NULL AND B.CALL_CNT IS NULL THEN NULL ELSE IFNULL(A.CALL_CNT,0) + IFNULL(B.CALL_CNT,0) END AS CALL_CNT
			, CASE WHEN A.RSCP IS NULL AND B.RSCP IS NULL THEN NULL ELSE IFNULL(A.RSCP,0) + IFNULL(B.RSCP,0) END AS RSCP
			, CASE WHEN A.ECN0 IS NULL AND B.ECN0 IS NULL THEN NULL ELSE IFNULL(A.ECN0,0) + IFNULL(B.ECN0,0) END AS ECN0
			, NULL AS RSCP_MED #CASE WHEN A.RSCP_MED IS NULL THEN B.RSCP_MED WHEN B.RSCP_MED IS NULL THEN A.RSCP_MED ELSE (A.RSCP_MED + B.RSCP_MED)/2 END AS RSCP_MED
			, NULL AS ECN0_MED #CASE WHEN A.ECN0_MED IS NULL THEN B.ECN0_MED WHEN B.ECN0_MED IS NULL THEN A.ECN0_MED ELSE (A.ECN0_MED + B.ECN0_MED)/2 END AS ECN0_MED
			, CASE WHEN A.POS_AS1_RSCP_CNT IS NULL AND B.POS_AS1_RSCP_CNT IS NULL THEN NULL ELSE IFNULL(A.POS_AS1_RSCP_CNT,0) + IFNULL(B.POS_AS1_RSCP_CNT,0) END AS POS_AS1_RSCP_CNT
			, CASE WHEN A.POS_AS1_ECN0_CNT IS NULL AND B.POS_AS1_ECN0_CNT IS NULL THEN NULL ELSE IFNULL(A.POS_AS1_ECN0_CNT,0) + IFNULL(B.POS_AS1_ECN0_CNT,0) END AS POS_AS1_ECN0_CNT
-- 			, CASE WHEN A.CALL_STATUS_BLOCK IS NULL AND B.CALL_STATUS_BLOCK IS NULL THEN NULL ELSE IFNULL(A.CALL_STATUS_BLOCK,0) + IFNULL(B.CALL_STATUS_BLOCK,0) END AS CALL_STATUS_BLOCK
-- 			, CASE WHEN A.CALL_STATUS_SUCCESS IS NULL AND B.CALL_STATUS_SUCCESS IS NULL THEN NULL ELSE IFNULL(A.CALL_STATUS_SUCCESS,0) + IFNULL(B.CALL_STATUS_SUCCESS,0) END AS CALL_STATUS_SUCCESS
-- 			, CASE WHEN A.CALL_STATUS_DROP IS NULL AND B.CALL_STATUS_DROP IS NULL THEN NULL ELSE IFNULL(A.CALL_STATUS_DROP,0) + IFNULL(B.CALL_STATUS_DROP,0) END AS CALL_STATUS_DROP
-- 			, CASE WHEN A.CALL_TYPE_SMS IS NULL AND B.CALL_TYPE_SMS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_SMS,0) + IFNULL(B.CALL_TYPE_SMS,0) END AS CALL_TYPE_SMS
-- 			, CASE WHEN A.CALL_TYPE_VOICE IS NULL AND B.CALL_TYPE_VOICE IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_VOICE,0) + IFNULL(B.CALL_TYPE_VOICE,0) END AS CALL_TYPE_VOICE
-- 			, CASE WHEN A.CALL_TYPE_VEDIO IS NULL AND B.CALL_TYPE_VEDIO IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_VEDIO,0) + IFNULL(B.CALL_TYPE_VEDIO,0) END AS CALL_TYPE_VEDIO
-- 			, CASE WHEN A.CALL_TYPE_PS99 IS NULL AND B.CALL_TYPE_PS99 IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_PS99,0) + IFNULL(B.CALL_TYPE_PS99,0) END AS CALL_TYPE_PS99
-- 			, CASE WHEN A.CALL_TYPE_HSPA IS NULL AND B.CALL_TYPE_HSPA IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_HSPA,0) + IFNULL(B.CALL_TYPE_HSPA,0) END AS CALL_TYPE_HSPA
-- 			, CASE WHEN A.CALL_TYPE_MRAB IS NULL AND B.CALL_TYPE_MRAB IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_MRAB,0) + IFNULL(B.CALL_TYPE_MRAB,0) END AS CALL_TYPE_MRAB
-- 			, CASE WHEN A.CALL_TYPE_PSOTHERS IS NULL AND B.CALL_TYPE_PSOTHERS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_PSOTHERS,0) + IFNULL(B.CALL_TYPE_PSOTHERS,0) END AS CALL_TYPE_PSOTHERS
-- 			, CASE WHEN A.CALL_TYPE_CS IS NULL AND B.CALL_TYPE_CS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_CS,0) + IFNULL(B.CALL_TYPE_CS,0) END AS CALL_TYPE_CS
-- 			, CASE WHEN A.CALL_TYPE_PS IS NULL AND B.CALL_TYPE_PS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_PS,0) + IFNULL(B.CALL_TYPE_PS,0) END AS CALL_TYPE_PS
		FROM ',GT_DB,'.table_tile_1st_server_dy_t_def a RIGHT JOIN 
		(
		 	SELECT
				 DATA_DATE AS DATA_DATE
				#, DATA_HOUR
				#, FREQUENCY AS FREQUENCY
				#, UARFCN AS UARFCN
				#, INDOOR AS INDOOR
				#, MOVING AS MOVING
				, TILE_ID AS TILE_ID
				, RNC_ID AS RNC_ID
				#, CELL_INDOOR AS CELL_INDOOR
				#, CLUSTER_ID AS CLUSTER_ID
				#, SITE_ID AS SITE_ID
				#, CELL_ID AS CELL_ID
				#, CALL_TYPE AS CALL_TYPE
				#, CALL_STATUS AS CALL_STATUS
				, SUM(CALL_CNT) AS CALL_CNT
				, SUM(RSCP) AS RSCP
				, SUM(ECN0) AS ECN0
				, NULL AS RSCP_MED #median(RSCP_MED) AS RSCP_MED
				, NULL AS ECN0_MED #median(ECN0_MED) AS ECN0_MED
				, SUM(POS_AS1_RSCP_CNT) AS POS_AS1_RSCP_CNT
				, SUM(POS_AS1_ECN0_CNT) AS POS_AS1_ECN0_CNT
-- 				,SUM(CALL_STATUS_BLOCK) AS CALL_STATUS_BLOCK
-- 				,SUM(CALL_STATUS_SUCCESS) AS CALL_STATUS_SUCCESS
-- 				,SUM(CALL_STATUS_DROP) AS CALL_STATUS_DROP
-- 				,SUM(CALL_TYPE_SMS) AS CALL_TYPE_SMS     
-- 				,SUM(CALL_TYPE_VOICE) AS CALL_TYPE_VOICE   
-- 				,SUM(CALL_TYPE_VEDIO) AS CALL_TYPE_VEDIO   
-- 				,SUM(CALL_TYPE_PS99) AS CALL_TYPE_PS99    
-- 				,SUM(CALL_TYPE_HSPA) AS CALL_TYPE_HSPA    
-- 				,SUM(CALL_TYPE_MRAB) AS CALL_TYPE_MRAB    
-- 				,SUM(CALL_TYPE_PSOTHERS) AS CALL_TYPE_PSOTHERS
-- 				,SUM(CALL_TYPE_CS) AS CALL_TYPE_CS      
-- 				,SUM(CALL_TYPE_PS) AS CALL_TYPE_PS
			FROM ',GT_DB,RUN,'.`tmp_table_tile_1st_server_',WORKER_ID,'`
			GROUP BY 
				DATA_DATE
				#, DATA_HOUR
				#, FREQUENCY
				#, UARFCN
				#, INDOOR
				#, MOVING
				, TILE_ID
				, RNC_ID
				#, CELL_INDOOR
				#, CLUSTER_ID
				#, SITE_ID
				#, CELL_ID
				#, CALL_TYPE 
				#, CALL_STATUS
		) B
		ON  A.DATA_DATE=B.DATA_DATE
		#AND A.FREQUENCY=B.FREQUENCY
		#AND A.UARFCN=B.UARFCN
		#AND A.INDOOR=B.INDOOR
		#AND A.MOVING=B.MOVING
		AND A.TILE_ID=B.TILE_ID
		AND A.RNC_ID=B.RNC_ID
		#AND A.CELL_INDOOR=B.CELL_INDOOR
		#AND A.CLUSTER_ID=B.CLUSTER_ID
		#AND A.SITE_ID=B.SITE_ID
		#AND A.CELL_ID=B.CELL_ID
		#AND A.CALL_TYPE=B.CALL_TYPE
		#AND A.CALL_STATUS=B.CALL_STATUS
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_1st_Server_AGR','Insert Data to table_tile_1st_server_dy_c_def', NOW());
	SET @SqlCmd=CONCAT('REPLACE INTO ',GT_DB,'.table_tile_1st_server_dy_c_def
 		(DATA_DATE,FREQUENCY,UARFCN,RNC_ID,CELL_INDOOR,CLUSTER_ID,SITE_ID,
		CELL_ID,CELL_NAME,CALL_CNT,RSCP,ECN0, RSCP_MED,ECN0_MED, CELL_LON,CELL_LAT,POS_AS1_RSCP_CNT, POS_AS1_ECN0_CNT
-- 				,CALL_STATUS_BLOCK,CALL_STATUS_SUCCESS,CALL_STATUS_DROP,CALL_TYPE_SMS,CALL_TYPE_VOICE,CALL_TYPE_VEDIO
-- 					,CALL_TYPE_PS99,CALL_TYPE_HSPA,CALL_TYPE_MRAB,CALL_TYPE_PSOTHERS,CALL_TYPE_CS,CALL_TYPE_PS
	)
 		SELECT
			 B.DATA_DATE
			#, DATA_HOUR
			, B.FREQUENCY
			, B.UARFCN
			#, B.INDOOR
			#, B.MOVING
			#, B.TILE_ID
			, B.RNC_ID
			, B.CELL_INDOOR
			, B.CLUSTER_ID
			, B.SITE_ID
			, B.CELL_ID
			, B.CELL_NAME
			#, B.CALL_TYPE 
			#, B.CALL_STATUS
			, CASE WHEN A.CALL_CNT IS NULL AND B.CALL_CNT IS NULL THEN NULL ELSE IFNULL(A.CALL_CNT,0) + IFNULL(B.CALL_CNT,0) END AS CALL_CNT
			, CASE WHEN A.RSCP IS NULL AND B.RSCP IS NULL THEN NULL ELSE IFNULL(A.RSCP,0) + IFNULL(B.RSCP,0) END AS RSCP
			, CASE WHEN A.ECN0 IS NULL AND B.ECN0 IS NULL THEN NULL ELSE IFNULL(A.ECN0,0) + IFNULL(B.ECN0,0) END AS ECN0
			, NULL AS RSCP_MED #CASE WHEN A.RSCP_MED IS NULL THEN B.RSCP_MED WHEN B.RSCP_MED IS NULL THEN A.RSCP_MED ELSE (A.RSCP_MED + B.RSCP_MED)/2 END AS RSCP_MED
			, NULL AS ECN0_MED #CASE WHEN A.ECN0_MED IS NULL THEN B.ECN0_MED WHEN B.ECN0_MED IS NULL THEN A.ECN0_MED ELSE (A.ECN0_MED + B.ECN0_MED)/2 END AS ECN0_MED
			, B.CELL_LON,B.CELL_LAT
			, CASE WHEN A.POS_AS1_RSCP_CNT IS NULL AND B.POS_AS1_RSCP_CNT IS NULL THEN NULL ELSE IFNULL(A.POS_AS1_RSCP_CNT,0) + IFNULL(B.POS_AS1_RSCP_CNT,0) END AS POS_AS1_RSCP_CNT
			, CASE WHEN A.POS_AS1_ECN0_CNT IS NULL AND B.POS_AS1_ECN0_CNT IS NULL THEN NULL ELSE IFNULL(A.POS_AS1_ECN0_CNT,0) + IFNULL(B.POS_AS1_ECN0_CNT,0) END AS POS_AS1_ECN0_CNT
-- 			, CASE WHEN A.CALL_STATUS_BLOCK IS NULL AND B.CALL_STATUS_BLOCK IS NULL THEN NULL ELSE IFNULL(A.CALL_STATUS_BLOCK,0) + IFNULL(B.CALL_STATUS_BLOCK,0) END AS CALL_STATUS_BLOCK
-- 			, CASE WHEN A.CALL_STATUS_SUCCESS IS NULL AND B.CALL_STATUS_SUCCESS IS NULL THEN NULL ELSE IFNULL(A.CALL_STATUS_SUCCESS,0) + IFNULL(B.CALL_STATUS_SUCCESS,0) END AS CALL_STATUS_SUCCESS
-- 			, CASE WHEN A.CALL_STATUS_DROP IS NULL AND B.CALL_STATUS_DROP IS NULL THEN NULL ELSE IFNULL(A.CALL_STATUS_DROP,0) + IFNULL(B.CALL_STATUS_DROP,0) END AS CALL_STATUS_DROP
-- 			, CASE WHEN A.CALL_TYPE_SMS IS NULL AND B.CALL_TYPE_SMS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_SMS,0) + IFNULL(B.CALL_TYPE_SMS,0) END AS CALL_TYPE_SMS
-- 			, CASE WHEN A.CALL_TYPE_VOICE IS NULL AND B.CALL_TYPE_VOICE IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_VOICE,0) + IFNULL(B.CALL_TYPE_VOICE,0) END AS CALL_TYPE_VOICE
-- 			, CASE WHEN A.CALL_TYPE_VEDIO IS NULL AND B.CALL_TYPE_VEDIO IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_VEDIO,0) + IFNULL(B.CALL_TYPE_VEDIO,0) END AS CALL_TYPE_VEDIO
-- 			, CASE WHEN A.CALL_TYPE_PS99 IS NULL AND B.CALL_TYPE_PS99 IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_PS99,0) + IFNULL(B.CALL_TYPE_PS99,0) END AS CALL_TYPE_PS99
-- 			, CASE WHEN A.CALL_TYPE_HSPA IS NULL AND B.CALL_TYPE_HSPA IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_HSPA,0) + IFNULL(B.CALL_TYPE_HSPA,0) END AS CALL_TYPE_HSPA
-- 			, CASE WHEN A.CALL_TYPE_MRAB IS NULL AND B.CALL_TYPE_MRAB IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_MRAB,0) + IFNULL(B.CALL_TYPE_MRAB,0) END AS CALL_TYPE_MRAB
-- 			, CASE WHEN A.CALL_TYPE_PSOTHERS IS NULL AND B.CALL_TYPE_PSOTHERS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_PSOTHERS,0) + IFNULL(B.CALL_TYPE_PSOTHERS,0) END AS CALL_TYPE_PSOTHERS
-- 			, CASE WHEN A.CALL_TYPE_CS IS NULL AND B.CALL_TYPE_CS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_CS,0) + IFNULL(B.CALL_TYPE_CS,0) END AS CALL_TYPE_CS
-- 			, CASE WHEN A.CALL_TYPE_PS IS NULL AND B.CALL_TYPE_PS IS NULL THEN NULL ELSE IFNULL(A.CALL_TYPE_PS,0) + IFNULL(B.CALL_TYPE_PS,0) END AS CALL_TYPE_PS
		FROM ',GT_DB,'.table_tile_1st_server_dy_c_def a RIGHT JOIN 
		(
		 	SELECT
				 DATA_DATE AS DATA_DATE
				#, DATA_HOUR
				, FREQUENCY AS FREQUENCY
				, UARFCN AS UARFCN
				#, INDOOR AS INDOOR
				#, MOVING AS MOVING
				#, TILE_ID AS TILE_ID
				, RNC_ID AS RNC_ID
				, CELL_INDOOR AS CELL_INDOOR
				, CLUSTER_ID AS CLUSTER_ID
				, SITE_ID AS SITE_ID
				, CELL_ID AS CELL_ID
				, CELL_NAME AS CELL_NAME
				#, CALL_TYPE AS CALL_TYPE
				#, CALL_STATUS AS CALL_STATUS
				, SUM(CALL_CNT) AS CALL_CNT
				, SUM(RSCP) AS RSCP
				, SUM(ECN0) AS ECN0
				, NULL AS RSCP_MED #median(RSCP_MED) AS RSCP_MED
				, NULL AS ECN0_MED #median(ECN0_MED) AS ECN0_MED
				, CELL_LON,CELL_LAT
				, SUM(POS_AS1_RSCP_CNT) AS POS_AS1_RSCP_CNT
				, SUM(POS_AS1_ECN0_CNT) AS POS_AS1_ECN0_CNT
-- 				,SUM(CALL_STATUS_BLOCK) AS CALL_STATUS_BLOCK
-- 				,SUM(CALL_STATUS_SUCCESS) AS CALL_STATUS_SUCCESS
-- 				,SUM(CALL_STATUS_DROP) AS CALL_STATUS_DROP
-- 				,SUM(CALL_TYPE_SMS) AS CALL_TYPE_SMS     
-- 				,SUM(CALL_TYPE_VOICE) AS CALL_TYPE_VOICE   
-- 				,SUM(CALL_TYPE_VEDIO) AS CALL_TYPE_VEDIO   
-- 				,SUM(CALL_TYPE_PS99) AS CALL_TYPE_PS99    
-- 				,SUM(CALL_TYPE_HSPA) AS CALL_TYPE_HSPA    
-- 				,SUM(CALL_TYPE_MRAB) AS CALL_TYPE_MRAB    
-- 				,SUM(CALL_TYPE_PSOTHERS) AS CALL_TYPE_PSOTHERS
-- 				,SUM(CALL_TYPE_CS) AS CALL_TYPE_CS      
-- 				,SUM(CALL_TYPE_PS) AS CALL_TYPE_PS
			FROM ',GT_DB,RUN,'.`tmp_table_tile_1st_server_',WORKER_ID,'`
			GROUP BY 
				DATA_DATE
				#, DATA_HOUR
				#, FREQUENCY
				#, UARFCN
				#, INDOOR
				#, MOVING
				#, TILE_ID
				, RNC_ID
				#, CELL_INDOOR
				#, CLUSTER_ID
				#, SITE_ID
				, CELL_ID
				#, CALL_TYPE 
				#, CALL_STATUS
		) B
		ON  A.DATA_DATE=B.DATA_DATE
		#AND A.FREQUENCY=B.FREQUENCY
		#AND A.UARFCN=B.UARFCN
		#AND A.INDOOR=B.INDOOR
		#AND A.MOVING=B.MOVING
		#AND A.TILE_ID=B.TILE_ID
		AND A.RNC_ID=B.RNC_ID
		#AND A.CELL_INDOOR=B.CELL_INDOOR
		#AND A.CLUSTER_ID=B.CLUSTER_ID
		#AND A.SITE_ID=B.SITE_ID
		AND A.CELL_ID=B.CELL_ID
		#AND A.CALL_TYPE=B.CALL_TYPE
		#AND A.CALL_STATUS=B.CALL_STATUS
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE  IF EXISTS ',GT_DB,RUN,'.tmp_table_tile_1st_server_',WORKER_ID,';');
	PREPARE stmt FROM @sqlcmd;
	EXECUTE stmt;
	DEALLOCATE PREPARE stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_1st_Server_AGR',CONCAT('Done: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());
		
END$$
DELIMITER ;
