DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Sub_Generate_CSV`(IN GT_DB VARCHAR(100),IN PATH VARCHAR(100),IN PATH2 VARCHAR(100),IN VENDOR_ID TINYINT(4))
BEGIN
       	DECLARE RNC_ID INT;
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE GT_START_TIME VARCHAR(20);
	DECLARE START_DATE VARCHAR(10) DEFAULT CONCAT(LEFT(gt_strtok(GT_DB,3,'_'),4),'-',SUBSTRING(gt_strtok(GT_DB,3,'_'),5,2),'-',SUBSTRING(gt_strtok(GT_DB,3,'_'),7,2));
	DECLARE START_HH VARCHAR(2) DEFAULT LEFT(gt_strtok(GT_DB,4,'_'),2);
	DECLARE START_MM VARCHAR(2) DEFAULT RIGHT(gt_strtok(GT_DB,4,'_'),2);
	DECLARE WORKER_ID VARCHAR(10) DEFAULT CONNECTION_ID();
	
	DECLARE CURRENT_NT_DB VARCHAR(50) DEFAULT CONCAT('gt_nt_',gt_strtok(GT_DB,3,'_'));
        SET SESSION max_heap_table_size = 1024*1024*1024*4; 
        SET SESSION tmp_table_size = 1024*1024*1024*6; 
        SET SESSION join_buffer_size = 1024*1024*1024*1; 
        SET SESSION sort_buffer_size = 1024*1024*1024*1; 
        SET SESSION read_buffer_size = 1024*1024*1024*1; 
	SET @SqlCmd=CONCAT('SELECT att_value INTO @pilot_rscp FROM ',CURRENT_NT_DB,'.`sys_config` WHERE `group_name`=''pilot'' AND att_name = ''pilot_rscp'';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('SELECT att_value INTO @pilot_ecn0 FROM ',CURRENT_NT_DB,'.`sys_config` WHERE `group_name`=''pilot'' AND att_name = ''pilot_ecn0'';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('SELECT att_value INTO @pilot_rscp_delta FROM ',CURRENT_NT_DB,'.`sys_config` WHERE `group_name`=''pilot'' AND att_name = ''pilot_rscp_delta'';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('SELECT att_value INTO @pilot_pollution_trigger FROM ',CURRENT_NT_DB,'.`sys_config` WHERE `group_name`=''pilot'' AND att_name = ''pilot_pollution_trigger'';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
        SELECT CONCAT(LEFT(gt_strtok(GT_DB,3,'_'),4),'-',SUBSTRING(gt_strtok(GT_DB,3,'_'),5,2),'-',SUBSTRING(gt_strtok(GT_DB,3,'_'),7,2),' ',LEFT(gt_strtok(GT_DB,4,'_'),2),':',RIGHT(gt_strtok(GT_DB,4,'_'),2),':00') INTO GT_START_TIME;
 	SELECT SUBSTRING(SUBSTRING(GT_DB, 4,LENGTH(GT_DB)-4),1, LOCATE('_', SUBSTRING(GT_DB, 4,LENGTH(GT_DB)-4))-1) INTO RNC_ID;
 
	
	
	INSERT INTO gt_gw_main.sp_log VALUES(GT_DB,'SP_Sub_Generate_CSV','Insert data to table_tile_fp_15-Start ', NOW());
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS  ',GT_DB,'.tmp_table_call','_',WORKER_ID,' ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,'.`tmp_table_call','_',WORKER_ID,'`  ENGINE=MYISAM
				SELECT 
				CALL_ID
				,POS_FIRST_RNC
				,POS_FIRST_CELL 
				,CALL_TYPE
				,CALL_STATUS
				,IMSI
				,NULL AS POS_IFHO_RNC
				,NULL AS POS_IFHO_CELL
				,POS_FIRST_RSCP
				,POS_FIRST_ECN0
				,DL_TRAFFIC_VOLUME
				,UL_TRAFFIC_VOLUME
				,DL_THROUGHPUT_AVG
				,UL_THROUGHPUT_AVG
				,SIMULATED
				,POS_AS1_RNC
				,POS_AS1_CELL
				,POS_AS1_RSCP
				,POS_AS1_ECN0
				,POS_LAST_RNC
				,POS_LAST_CELL
				,POS_LAST_RSCP
				,POS_LAST_ECN0
				,IRAT_HHO_ATTEMPT
				,IRAT_HHO_SUCCESS
				,DATA_HOUR
				,DATA_DATE
				,POS_FIRST_FREQUENCY
				,POS_FIRST_UARFCN
				,INDOOR
				,MOVING
				,POS_FIRST_LOC
				,POS_FIRST_CELL_INDOOR
				,POS_FIRST_CLUSTER
				,POS_FIRST_SITE
				,RRC_CONNECT_DURATION
				,POS_LAST_LOC
				,POS_LAST_CELL_INDOOR
				,POS_LAST_CLUSTER
				,POS_LAST_SITE
				,POS_LAST_FREQUENCY
				,POS_LAST_UARFCN
				,IU_RELEASE_CAUSE
				FROM ',GT_DB,'.table_call;
				');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE INDEX CALL_ID on ',GT_DB,'.`tmp_table_call','_',WORKER_ID,'` (CALL_ID)   ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(GT_DB,'SP_Sub_Generate_CSV','step 1', NOW());
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS  ',GT_DB,'.`tmp_table_first','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;	
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,'.`tmp_table_first','_',WORKER_ID,'` ENGINE=MYISAM
				SELECT POS_FIRST_RNC RNC_ID 
				,POS_FIRST_CELL CELL_ID 
				,CASE WHEN CALL_TYPE IN (10) THEN ''Voice'' WHEN CALL_TYPE IN (12,13,14,18) THEN ''Data'' WHEN CALL_TYPE =16 THEN ''SMS'' END AS SERVICETYPE
				,COUNT(DISTINCT IMSI) AS subscriber
				,COUNT(POS_FIRST_CELL) AS init_call_count
				,AVG(POS_FIRST_RSCP) AS init_rscp
				,AVG(POS_FIRST_ECN0) AS init_ecn0
				,SUM(DL_TRAFFIC_VOLUME) AS dl_vol
				,SUM(UL_TRAFFIC_VOLUME) AS ul_vol
				,SUM(CASE WHEN CALL_TYPE IN (12,13,14,18) THEN 1 ELSE 0 END) AS ps_call_count
				,AVG(CASE WHEN CALL_TYPE IN (12,13,14,18) THEN DL_THROUGHPUT_AVG ELSE NULL END) AS dl_thro
				,AVG(CASE WHEN CALL_TYPE IN (12,13,14,18) THEN UL_THROUGHPUT_AVG ELSE NULL END) AS ul_thro
				,MAX(DL_THROUGHPUT_AVG) AS max_dl_thro
				,MAX(UL_THROUGHPUT_AVG) AS max_ul_thro
				,SUM(CASE CALL_STATUS WHEN 3 THEN 1 ELSE 0 END) AS block
				,AVG(CASE `SIMULATED` WHEN 0 THEN POS_FIRST_RSCP ELSE NULL END) AS init_pilot_rscp
				,AVG(CASE `SIMULATED` WHEN 0 THEN POS_FIRST_ECN0 ELSE NULL END) AS init_pilot_ecn0
				FROM ',GT_DB,'.`tmp_table_call','_',WORKER_ID,'`
				WHERE POS_FIRST_CELL IS NOT NULL AND POS_FIRST_RSCP IS NOT NULL AND DATA_HOUR=',START_HH,'
				GROUP BY POS_FIRST_RNC,POS_FIRST_CELL,SERVICETYPE;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(GT_DB,'SP_Sub_Generate_CSV','step 2', NOW());
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS  ',GT_DB,'.`tmp_table_ifho','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;	
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,'.`tmp_table_ifho','_',WORKER_ID,'` ENGINE=MYISAM
				SELECT 
				POS_IFHO_RNC RNC_ID 
				,POS_IFHO_CELL CELL_ID 
				,CASE WHEN CALL_TYPE IN (10) THEN ''Voice'' WHEN CALL_TYPE IN (12,13,14,18) THEN ''Data'' WHEN CALL_TYPE =16 THEN ''SMS'' END AS SERVICETYPE
				,COUNT(POS_IFHO_CELL) AS IFHO_COUNT
				FROM ',GT_DB,'.`tmp_table_call','_',WORKER_ID,'`
				WHERE POS_IFHO_RNC =',RNC_ID,' AND DATA_HOUR=',START_HH,'
				GROUP BY POS_IFHO_RNC,POS_IFHO_CELL,SERVICETYPE;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(GT_DB,'SP_Sub_Generate_CSV','step 2', NOW());
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS  ',GT_DB,'.`tmp_table_as1','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,'.`tmp_table_as1','_',WORKER_ID,'` ENGINE=MYISAM
				SELECT POS_AS1_RNC RNC_ID
					,POS_AS1_CELL CELL_ID
					,CASE WHEN CALL_TYPE IN (10) THEN ''Voice'' WHEN CALL_TYPE IN (12,13,14,18) THEN ''Data'' WHEN CALL_TYPE =16 THEN ''SMS'' END AS SERVICETYPE
					,COUNT(POS_AS1_RSCP) AS act_call_count
					,AVG(POS_AS1_RSCP) AS init_serv_rscp
					,AVG(POS_AS1_ECN0) AS init_serv_ecn0
				FROM ',GT_DB,'.`tmp_table_call','_',WORKER_ID,'`
				WHERE POS_AS1_CELL IS NOT NULL AND POS_AS1_RSCP IS NOT NULL AND DATA_HOUR=',START_HH,'
				GROUP BY POS_AS1_RNC,POS_AS1_CELL,SERVICETYPE;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(GT_DB,'SP_Sub_Generate_CSV','step 3', NOW());
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS  ',GT_DB,'.`tmp_table_last','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,'.`tmp_table_last','_',WORKER_ID,'` ENGINE=MYISAM
				SELECT POS_LAST_RNC AS RNC_ID 
					,POS_LAST_CELL AS CELL_ID 
					,CASE WHEN CALL_TYPE IN (10) THEN ''Voice'' WHEN CALL_TYPE IN (12,13,14,18) THEN ''Data'' WHEN CALL_TYPE =16 THEN ''SMS'' END AS SERVICETYPE
					,COUNT(POS_LAST_CELL) AS end_call_count
					,AVG(POS_LAST_RSCP) AS end_pilot_rscp
					,AVG(POS_LAST_ECN0) AS end_pilot_ecn0
					,SUM(IRAT_HHO_ATTEMPT) AS irat_att
					,SUM(IRAT_HHO_SUCCESS) AS irat_success
				FROM ',GT_DB,'.`tmp_table_call','_',WORKER_ID,'`
				WHERE POS_LAST_CELL IS NOT NULL AND DATA_HOUR=',START_HH,'
				GROUP BY POS_LAST_RNC,POS_LAST_CELL,SERVICETYPE;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(GT_DB,'SP_Sub_Generate_CSV','step 4', NOW());
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS  ',GT_DB,'.`tmp_table_fp','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,'.`tmp_table_fp','_',WORKER_ID,'` ENGINE=MYISAM
				SELECT  gt_covmo_csv_get(RNC_ID,1) RNC_ID
					, gt_covmo_csv_get(CELL_ID,1) CELL_ID
					,CASE WHEN A.CALL_TYPE IN (10) THEN ''Voice'' WHEN A.CALL_TYPE IN (12,13,14,18) THEN ''Data'' WHEN A.CALL_TYPE =16 THEN ''SMS'' END AS SERVICETYPE
					, COUNT(*) AS mr_count
					, AVG(gt_covmo_csv_get(RSCP,1)) AS fp_pilot_rscp
					, AVG(gt_covmo_csv_get(ECN0,1)) AS fp_pilot_ecn0
					, AVG(gt_covmo_csv_count(ACTIVE_SET_CELL_ID, '','')) AS as_count
					, SUM(IF(gt_covmo_polluter(RSCP, ECN0,',@pilot_rscp,',',@pilot_ecn0,',',@pilot_rscp_delta,')>',@pilot_pollution_trigger,',gt_covmo_polluter(RSCP, ECN0,',@pilot_rscp,',',@pilot_ecn0,',',@pilot_rscp_delta,')-',@pilot_pollution_trigger,',0)) AS POLLUTER
					, SUM(IF(gt_covmo_polluter(RSCP, ECN0,',@pilot_rscp,',',@pilot_ecn0,',',@pilot_rscp_delta,')>',@pilot_pollution_trigger,',1,0)) AS polluted_mr	
				FROM ',GT_DB,'.`tmp_table_call','_',WORKER_ID,'` A  FORCE INDEX (CALL_ID), ',GT_DB,'.table_position B FORCE INDEX (CALL_ID)
				WHERE A.CALL_ID=B.CALL_ID
				AND gt_covmo_csv_getnum(B.RNC_ID,1)=',RNC_ID,'
				AND RSCP IS NOT NULL AND A.DATA_HOUR=',START_HH,' AND B.DATA_HOUR=',START_HH,'
				GROUP BY gt_covmo_csv_get(RNC_ID,1),gt_covmo_csv_get(CELL_ID,1),SERVICETYPE
				ORDER BY NULL;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(GT_DB,'SP_Sub_Generate_CSV','step 5', NOW());
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS  ',GT_DB,'.`tmp_huawei_csv','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,'.`tmp_huawei_csv','_',WORKER_ID,'`
				(
					RNC_ID	VARCHAR(50)  DEFAULT NULL,
					CELL_ID	VARCHAR(50)  DEFAULT NULL,
					SAI	VARCHAR(50)  DEFAULT NULL,
					`TIMESTAMP` BIGINT(20) DEFAULT NULL,
					INIT_CALL_COUNT	INT  DEFAULT NULL,
					INIT_RSCP	DOUBLE  DEFAULT NULL,
					INIT_PILOT_RSCP	DOUBLE  DEFAULT NULL,
					INIT_ECN0	DOUBLE  DEFAULT NULL,
					INIT_PILOT_ECN0	DOUBLE  DEFAULT NULL,
					DL_VOL	DOUBLE  DEFAULT NULL,
					UL_VOL	DOUBLE  DEFAULT NULL,
					PS_CALL_COUNT	INT  DEFAULT NULL,
					DL_THRO	DOUBLE  DEFAULT NULL,
					UL_THRO	DOUBLE  DEFAULT NULL,
					MAX_DL_THRO	DOUBLE  DEFAULT NULL,
					MAX_UL_THRO	DOUBLE  DEFAULT NULL,
					SUBSCRIBER	INT  DEFAULT NULL,
					BLOCK_RATE	DOUBLE  DEFAULT NULL,
					RRC_SUCCESS_RATE	INT  DEFAULT NULL,
					ACT_CALL_COUNT	INT  DEFAULT NULL,
					INIT_SERV_RSCP	DOUBLE  DEFAULT NULL,
					INIT_SERV_ECN0	DOUBLE  DEFAULT NULL,
					IFHO_COUNT	INT  DEFAULT NULL,
					IFHO_RATE	DOUBLE  DEFAULT NULL,
					END_CALL_COUNT	INT  DEFAULT NULL,
					END_PILOT_RSCP	DOUBLE  DEFAULT NULL,
					END_PILOT_ECN0	DOUBLE  DEFAULT NULL,
					IRAT_ATT	INT  DEFAULT NULL,
					IRAT_SUCCESS_RATE	DOUBLE  DEFAULT NULL,
					MR_COUNT	INT  DEFAULT NULL,
					FP_PILOT_RSCP	DOUBLE  DEFAULT NULL,
					FP_PILOT_ECN0	DOUBLE  DEFAULT NULL,
					POLLUTED_MR	DOUBLE  DEFAULT NULL,
					POLLUTER	DOUBLE  DEFAULT NULL,
					AS_COUNT	DOUBLE  DEFAULT NULL,
					RNC_ID_NEW	VARCHAR(50)  DEFAULT NULL,
					SERVICETYPE	CHAR(5)  DEFAULT NULL,
					RESERVED1	VARCHAR(20)  DEFAULT NULL,
					RESERVED2	VARCHAR(20)  DEFAULT NULL,
					RESERVED3	VARCHAR(20)  DEFAULT NULL,
					RESERVED4	VARCHAR(20)  DEFAULT NULL,
					RESERVED5	VARCHAR(20)  DEFAULT NULL,
					RESERVED6	DOUBLE  DEFAULT NULL,
					RESERVED7	DOUBLE  DEFAULT NULL,
					RESERVED8	DOUBLE  DEFAULT NULL,
					RESERVED9	DOUBLE  DEFAULT NULL,
					RESERVED10	DOUBLE  DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(GT_DB,'SP_Sub_Generate_CSV','step 6', NOW());
	
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.`tmp_huawei_csv','_',WORKER_ID,'` ( RNC_ID,CELL_ID,SERVICETYPE,`TIMESTAMP`)
				SELECT RNC_ID,CELL_ID,SERVICETYPE,UNIX_TIMESTAMP(''',GT_START_TIME,''')
				FROM 
				(
					SELECT RNC_ID,CELL_ID,SERVICETYPE FROM ',GT_DB,'.`tmp_table_first','_',WORKER_ID,'`
					UNION 
					SELECT RNC_ID,CELL_ID,SERVICETYPE FROM ',GT_DB,'.`tmp_table_ifho','_',WORKER_ID,'`
					UNION 
					SELECT RNC_ID,CELL_ID,SERVICETYPE FROM ',GT_DB,'.`tmp_table_as1','_',WORKER_ID,'`
					UNION 
					SELECT RNC_ID,CELL_ID,SERVICETYPE FROM ',GT_DB,'.`tmp_table_last','_',WORKER_ID,'`
					UNION 
					SELECT RNC_ID,CELL_ID,SERVICETYPE FROM ',GT_DB,'.`tmp_table_fp','_',WORKER_ID,'`
				) AA;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(GT_DB,'SP_Sub_Generate_CSV','step 7', NOW());
	
	SET @SqlCmd=CONCAT('UPDATE ',GT_DB,'.`tmp_huawei_csv','_',WORKER_ID,'` a,',GT_DB,'.`tmp_table_first','_',WORKER_ID,'` B
				SET A.SUBSCRIBER=B.SUBSCRIBER
					,A.INIT_CALL_COUNT=B.INIT_CALL_COUNT
					,A.INIT_RSCP=B.INIT_RSCP
					,A.INIT_ECN0=B.INIT_ECN0
					,A.DL_VOL=B.DL_VOL
					,A.UL_VOL=B.UL_VOL
					,A.PS_CALL_COUNT=B.PS_CALL_COUNT
					,A.DL_THRO=B.DL_THRO
					,A.UL_THRO=B.UL_THRO
					,A.MAX_DL_THRO=B.MAX_DL_THRO
					,A.MAX_UL_THRO=B.MAX_UL_THRO
					,A.BLOCK_RATE=B.BLOCK/B.INIT_CALL_COUNT
					,A.INIT_PILOT_RSCP=B.INIT_PILOT_RSCP
					,A.INIT_PILOT_ECN0=B.INIT_PILOT_ECN0
					,A.RRC_SUCCESS_RATE=1-(B.BLOCK/B.INIT_CALL_COUNT)
				WHERE A.RNC_ID=B.RNC_ID AND A.CELL_ID=B.CELL_ID AND A.SERVICETYPE=B.SERVICETYPE;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('UPDATE ',GT_DB,'.`tmp_huawei_csv','_',WORKER_ID,'` a,',GT_DB,'.`tmp_table_ifho','_',WORKER_ID,'` B
				SET 
					A.IFHO_COUNT=B.IFHO_COUNT
				WHERE A.RNC_ID=B.RNC_ID AND A.CELL_ID=B.CELL_ID AND A.SERVICETYPE=B.SERVICETYPE;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('UPDATE ',GT_DB,'.`tmp_huawei_csv','_',WORKER_ID,'`
				SET 
					IFHO_RATE=IFHO_COUNT/INIT_CALL_COUNT
				WHERE IFHO_COUNT IS NOT NULL AND INIT_CALL_COUNT IS NOT NULL;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('UPDATE ',GT_DB,'.`tmp_huawei_csv','_',WORKER_ID,'` a,',GT_DB,'.`tmp_table_as1','_',WORKER_ID,'` B
				SET A.INIT_SERV_RSCP=B.INIT_SERV_RSCP
					,A.INIT_SERV_ECN0=B.INIT_SERV_ECN0
					,A.ACT_CALL_COUNT=B.ACT_CALL_COUNT
				WHERE A.RNC_ID=B.RNC_ID AND A.CELL_ID=B.CELL_ID AND A.SERVICETYPE=B.SERVICETYPE;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('UPDATE ',GT_DB,'.`tmp_huawei_csv','_',WORKER_ID,'` a,',GT_DB,'.`tmp_table_last','_',WORKER_ID,'` B
				SET A.END_CALL_COUNT=B.END_CALL_COUNT
					,A.END_PILOT_RSCP=B.END_PILOT_RSCP
					,A.END_PILOT_ECN0=B.END_PILOT_ECN0
					,A.IRAT_ATT=B.IRAT_ATT
					,A.IRAT_SUCCESS_RATE=(B.IRAT_SUCCESS/B.IRAT_ATT)
				WHERE A.RNC_ID=B.RNC_ID AND A.CELL_ID=B.CELL_ID AND A.SERVICETYPE=B.SERVICETYPE;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('UPDATE ',GT_DB,'.`tmp_huawei_csv','_',WORKER_ID,'` a,',GT_DB,'.`tmp_table_fp','_',WORKER_ID,'` B
				SET A.MR_COUNT=B.MR_COUNT
					,A.FP_PILOT_RSCP=B.FP_PILOT_RSCP
					,A.FP_PILOT_ECN0=B.FP_PILOT_ECN0
					,A.AS_COUNT=B.AS_COUNT
					,A.POLLUTER=B.POLLUTER
					,A.POLLUTED_MR=B.POLLUTED_MR
				WHERE A.RNC_ID=B.RNC_ID AND A.CELL_ID=B.CELL_ID AND A.SERVICETYPE=B.SERVICETYPE;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('UPDATE ',GT_DB,'.`tmp_huawei_csv','_',WORKER_ID,'` a
				JOIN  ',GT_DB,'.NT_CURRENT c
				ON A.RNC_ID=c.RNC_ID AND A.CELL_ID=c.CELL_ID
				JOIN ',GT_DB,'.NT_RNC_CURRENT B
				ON c.RNC_ID=B.RNC_ID				
				SET A.SAI=CONCAT(CONVERT(MCC USING utf8) ,CONVERT(B.MNC USING utf8) ,RIGHT(CONCAT(''0000'',HEX(c.LAC)),4),RIGHT(CONCAT(''0000'',HEX(c.CELL_ID)),4))
					,RNC_ID_NEW=CONCAT(CONVERT(MCC USING utf8),''-'' ,CONVERT(B.MNC USING utf8),''-'' ,RIGHT(CONCAT(''00000'',A.RNC_ID),5)) ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(GT_DB,'SP_Sub_Generate_CSV','step 8', NOW());
	
	SET @SqlCmd=CONCAT('SELECT ''RNC_ID'',''CELL_ID'',''SAI'',''TIMESTAMP'',
				''INIT_CALL_COUNT'',''INIT_RSCP'',''INIT_PILOT_RSCP'',''INIT_ECN0'',''INIT_PILOT_ECN0'',
				''DL_VOL'',''UL_VOL'',''PS_CALL_COUNT'',''DL_THRO'',''UL_THRO'',''MAX_DL_THRO'',''MAX_UL_THRO'',
				''SUBSCRIBER'',''BLOCK_RATE'',''RRC_SUCCESS_RATE'',''ACT_CALL_COUNT'',''INIT_SERV_RSCP'',''INIT_SERV_ECN0'',
				''IFHO_COUNT'',''IFHO_RATE'',''END_CALL_COUNT'',''END_PILOT_RSCP'',''END_PILOT_ECN0'',''IRAT_ATT'',''IRAT_SUCCESS_RATE'',
				''MR_COUNT'',''FP_PILOT_RSCP'',''FP_PILOT_ECN0'',''POLLUTED_MR'',''POLLUTER'',''AS_COUNT'',
				''SERVICETYPE'',''RESERVED1'',''RESERVED2'',''RESERVED3'',''RESERVED4'',''RESERVED5'',
				''RESERVED6'',''RESERVED7'',''RESERVED8'',''RESERVED9'',''RESERVED10''
			    UNION 
			    SELECT `RNC_ID_NEW`,`CELL_ID`,`SAI`,`TIMESTAMP`,
				IFNULL(`INIT_CALL_COUNT`,''NULL''),
				IFNULL(`INIT_RSCP`,''NULL''),
				IFNULL(`INIT_PILOT_RSCP`,''NULL''),
				IFNULL(`INIT_ECN0`,''NULL''),
				IFNULL(`INIT_PILOT_ECN0`,''NULL''),
				IFNULL(`DL_VOL`,''NULL''),
				IFNULL(`UL_VOL`,''NULL''),
				IFNULL(`PS_CALL_COUNT`,''NULL''),
				IFNULL(`DL_THRO`,''NULL''),
				IFNULL(`UL_THRO`,''NULL''),
				IFNULL(`MAX_DL_THRO`,''NULL''),
				IFNULL(`MAX_UL_THRO`,''NULL''),
				IFNULL(`SUBSCRIBER`,''NULL''),
				IFNULL(`BLOCK_RATE`,''NULL''),
				IFNULL(`RRC_SUCCESS_RATE`,''NULL''),
				IFNULL(`ACT_CALL_COUNT`,''NULL''),
				IFNULL(`INIT_SERV_RSCP`,''NULL''),
				IFNULL(`INIT_SERV_ECN0`,''NULL''),
				IFNULL(`IFHO_COUNT`,''NULL''),
				IFNULL(`IFHO_RATE`,''NULL''),
				IFNULL(`END_CALL_COUNT`,''NULL''),
				IFNULL(`END_PILOT_RSCP`,''NULL''),
				IFNULL(`END_PILOT_ECN0`,''NULL''),
				IFNULL(`IRAT_ATT`,''NULL''),
				IFNULL(`IRAT_SUCCESS_RATE`,''NULL''),
				IFNULL(`MR_COUNT`,''NULL''),
				IFNULL(`FP_PILOT_RSCP`,''NULL''),
				IFNULL(`FP_PILOT_ECN0`,''NULL''),
				IFNULL(`POLLUTED_MR`,''NULL''),
				IFNULL(`POLLUTER`,''NULL''),
				IFNULL(`AS_COUNT`,''NULL''),
				IFNULL(`SERVICETYPE`,''NULL''),
				IFNULL(`RESERVED1`,''NULL''),
				IFNULL(`RESERVED2`,''NULL''),
				IFNULL(`RESERVED3`,''NULL''),
				IFNULL(`RESERVED4`,''NULL''),
				IFNULL(`RESERVED5`,''NULL''),
				IFNULL(`RESERVED6`,''NULL''),
				IFNULL(`RESERVED7`,''NULL''),
				IFNULL(`RESERVED8`,''NULL''),
				IFNULL(`RESERVED9`,''NULL''),
				IFNULL(`RESERVED10`,''NULL'')
			    FROM ',GT_DB,'.`tmp_huawei_csv','_',WORKER_ID,'`
			    WHERE `RNC_ID`=',RNC_ID,' AND RNC_ID_NEW IS NOT NULL
			    INTO OUTFILE ''',PATH,'/',CASE VENDOR_ID 
					WHEN 1 THEN 'Ericsson'
					WHEN 2 THEN 'Huawei'
					WHEN 3 THEN 'Huawei'
					WHEN 7 THEN 'NSN'
				 END 
				,'-',RNC_ID,'-',START_DATE,'-',START_HH,'-'
				,CASE START_MM 
					WHEN '00' THEN '1'
					WHEN '15' THEN '2'
					WHEN '30' THEN '3'
					WHEN '45' THEN '4'
				 END 
				,'.csv.tmp''
			    FIELDS TERMINATED BY '',''
			    LINES TERMINATED BY ''\\n''
			    ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE ',GT_DB,'.`tmp_table_first','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE ',GT_DB,'.`tmp_table_as1','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE ',GT_DB,'.`tmp_table_last','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;	
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE ',GT_DB,'.`tmp_table_fp','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;		
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE ',GT_DB,'.`tmp_huawei_csv','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;	
	
	CALL GT_GW_MAIN.SP_Sub_Generate_Special_Report_Quarter(GT_DB,PATH2,VENDOR_ID);
	
	INSERT INTO gt_gw_main.SP_LOG VALUES(GT_DB,'SP_Sub_Generate_CSV',CONCAT('Done: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());	
	
        SET SESSION max_heap_table_size = 1024*1024*128; 
        SET SESSION tmp_table_size = 1024*1024*128; 
        SET SESSION join_buffer_size = 1024*1024*128; 
        SET SESSION sort_buffer_size = 1024*1024*128; 
        SET SESSION read_buffer_size = 1024*1024*128; 
	
END$$
DELIMITER ;
