DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Sub_Generate_Special_Report_Hourly`(IN GT_DB VARCHAR(100),IN PATH VARCHAR(100),IN VENDOR_ID TINYINT(4))
BEGIN
       	DECLARE RNC_ID INT;
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE GT_START_TIME VARCHAR(20);
	DECLARE START_DATE VARCHAR(10) DEFAULT CONCAT(LEFT(gt_strtok(GT_DB,3,'_'),4),'-',SUBSTRING(gt_strtok(GT_DB,3,'_'),5,2),'-',SUBSTRING(gt_strtok(GT_DB,3,'_'),7,2));
	DECLARE START_HH VARCHAR(2) DEFAULT LEFT(gt_strtok(GT_DB,4,'_'),2);
	DECLARE START_MM VARCHAR(2) DEFAULT RIGHT(gt_strtok(GT_DB,4,'_'),2);
	DECLARE WORKER_ID VARCHAR(10) DEFAULT CONNECTION_ID();
	DECLARE GT_DB_START_MIN VARCHAR(10) DEFAULT SUBSTRING(RIGHT(GT_DB,18),12,2);
	DECLARE O_GT_DB VARCHAR(100) DEFAULT GT_DB;
	DECLARE SH_EH VARCHAR(9) DEFAULT RIGHT(GT_DB,9);
	DECLARE SH VARCHAR(4) DEFAULT gt_strtok(SH_EH,1,'_');
	DECLARE DY_GT_DB VARCHAR(100);
	#DECLARE pilot_rscp SMALLINT;
	#DECLARE pilot_ecn0 SMALLINT;
	#DECLARE pilot_rscp_delta SMALLINT;
	#DECLARE pilot_pollution_trigger SMALLINT;
	DECLARE interfere_rscp SMALLINT;
	DECLARE interfere_ecn0 SMALLINT;
	DECLARE CURRENT_NT_DB VARCHAR(50) DEFAULT CONCAT('gt_nt_',DATE_FORMAT(START_DATE,'%Y%m%d'));
		
        SET SESSION max_heap_table_size = 1024*1024*1024*4; 
        SET SESSION tmp_table_size = 1024*1024*1024*6; 
        SET SESSION join_buffer_size = 1024*1024*1024*1; 
        SET SESSION sort_buffer_size = 1024*1024*1024*1; 
        SET SESSION read_buffer_size = 1024*1024*1024*1; 
	/*SELECT att_value INTO pilot_rscp FROM CURRENT_NT_DB.`sys_config` WHERE `group_name`='pilot' AND att_name = 'pilot_rscp';
	SELECT att_value INTO pilot_ecn0 FROM CURRENT_NT_DB.`sys_config` WHERE `group_name`='pilot' AND att_name ='pilot_ecn0';
	SELECT att_value INTO pilot_rscp_delta FROM CURRENT_NT_DB.`sys_config` WHERE `group_name`='pilot' AND att_name ='pilot_rscp_delta';
	SELECT att_value INTO pilot_pollution_trigger FROM CURRENT_NT_DB.`sys_config` WHERE `group_name`='pilot' AND att_name ='pilot_pollution_trigger';*/
        SET @SqlCmd=CONCAT('SELECT att_value INTO @pilot_rscp FROM ',CURRENT_NT_DB,'.`sys_config` WHERE `group_name`=''pilot'' AND att_name = ''pilot_rscp'';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('SELECT att_value INTO @pilot_ecn0 FROM ',CURRENT_NT_DB,'.`sys_config` WHERE `group_name`=''pilot'' AND att_name =''pilot_ecn0'';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('SELECT att_value INTO @pilot_rscp_delta FROM ',CURRENT_NT_DB,'.`sys_config` WHERE `group_name`=''pilot'' AND att_name =''pilot_rscp_delta'';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('SELECT att_value INTO @pilot_pollution_trigger FROM ',CURRENT_NT_DB,'.`sys_config` WHERE `group_name`=''pilot'' AND att_name =''pilot_pollution_trigger'';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
        SELECT CONCAT(LEFT(gt_strtok(GT_DB,3,'_'),4),'-',SUBSTRING(gt_strtok(GT_DB,3,'_'),5,2),'-',SUBSTRING(gt_strtok(GT_DB,3,'_'),7,2),' ',LEFT(gt_strtok(GT_DB,4,'_'),2),':',RIGHT(gt_strtok(GT_DB,4,'_'),2),':00') INTO GT_START_TIME;
 	SELECT SUBSTRING(SUBSTRING(GT_DB, 4,LENGTH(GT_DB)-4),1, LOCATE('_', SUBSTRING(GT_DB, 4,LENGTH(GT_DB)-4))-1) INTO RNC_ID;
 
	SELECT REPLACE(GT_DB,SH_EH,'0000_0000') INTO DY_GT_DB;
 
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_Special_Report_Hourly','Start ', NOW());
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS  ',DY_GT_DB,'.tmp_table_call','_',WORKER_ID,' ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',DY_GT_DB,'.`tmp_table_call','_',WORKER_ID,'`  ENGINE=MYISAM
				SELECT  * FROM ',DY_GT_DB,'.table_call_',START_HH,';
				');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE INDEX CALL_ID on ',DY_GT_DB,'.`tmp_table_call','_',WORKER_ID,'` (CALL_ID)   ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_Special_Report_Hourly','step 1', NOW());
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS  ',DY_GT_DB,'.`tmp_sh_table_first','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',DY_GT_DB,'.`tmp_sh_table_first','_',WORKER_ID,'` ENGINE=MYISAM
				SELECT POS_FIRST_RNC RNC_ID 
					,POS_FIRST_CELL CELL_ID 
					,SUM(CASE WHEN CALL_TYPE IN (10) THEN 1 ELSE 0 END) AS VOICE
					,SUM(CASE WHEN CALL_TYPE IN (12) THEN 1 ELSE 0 END) AS PS_99
					,SUM(CASE WHEN CALL_TYPE IN (13) THEN 1 ELSE 0 END) AS PS_HSPA
					,SUM(CASE WHEN CALL_TYPE IN (18) THEN 1 ELSE 0 END) AS PS_OTHER
					,SUM(CASE WHEN CALL_TYPE IN (14) THEN 1 ELSE 0 END) AS MULTI_RAB
					,SUM(CASE WHEN CALL_TYPE IN (16) THEN 1 ELSE 0 END) AS SMS
					,SUM(CASE WHEN CALL_STATUS IN (1) THEN 1 ELSE 0 END) AS NORMAL_CALL_COUNT
					,SUM(CASE WHEN CALL_STATUS IN (2) THEN 1 ELSE 0 END) AS DROP_CALL_COUNT
					,SUM(CASE WHEN CALL_STATUS IN (3) THEN 1 ELSE 0 END) AS BLOCK_CALL_COUNT
					,SUM(RRC_CONNECT_DURATION) AS TOTAL_CALL_DURATION
					,SUM(CASE WHEN CALL_TYPE IN (12) THEN DL_TRAFFIC_VOLUME ELSE 0 END)/1024 AS PS_R99_DL_TRAFFIC_VOLUME
					,SUM(CASE WHEN CALL_TYPE IN (13) THEN DL_TRAFFIC_VOLUME ELSE 0 END)/1024 AS PS_HSPA_DL_TRAFFIC_VOLUME
					,SUM(CASE WHEN CALL_TYPE IN (18) THEN DL_TRAFFIC_VOLUME ELSE 0 END)/1024 AS PS_OTHER_DL_TRAFFIC_VOLUME
					,SUM(CASE WHEN CALL_TYPE IN (12) THEN UL_TRAFFIC_VOLUME ELSE 0 END)/1024 AS PS_R99_UL_TRAFFIC_VOLUME
					,SUM(CASE WHEN CALL_TYPE IN (13) THEN UL_TRAFFIC_VOLUME ELSE 0 END)/1024 AS PS_HSPA_UL_TRAFFIC_VOLUME
					,SUM(CASE WHEN CALL_TYPE IN (18) THEN UL_TRAFFIC_VOLUME ELSE 0 END)/1024 AS PS_OTHER_UL_TRAFFIC_VOLUME
					,SUM(CASE WHEN CALL_TYPE IN (10,11) THEN RRC_CONNECT_DURATION ELSE 0 END)/3600 AS CS_ERLANG
				FROM ',DY_GT_DB,'.`tmp_table_call','_',WORKER_ID,'`
				WHERE POS_FIRST_CELL IS NOT NULL AND DATA_HOUR=',START_HH,'
				GROUP BY POS_FIRST_RNC,POS_FIRST_CELL;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_Special_Report_Hourly','step 2', NOW());
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS  ',DY_GT_DB,'.`tmp_sh_table_start','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;	
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',DY_GT_DB,'.`tmp_sh_table_start','_',WORKER_ID,'` ENGINE=MYISAM
				SELECT 
					RNC_ID,CELL_ID
					#,SUM(IF((CALL_TYPE=13 OR CALL_TYPE=12 OR CALL_TYPE=14 OR CALL_TYPE=18),DL_DATA_THRU*CALL_CNT, 0))/SUM(IF((CALL_TYPE=13 OR CALL_TYPE=12 OR CALL_TYPE=14 OR CALL_TYPE=18),CALL_CNT, 0)) AS DL_THROUGHPUT
					#,SUM(IF((CALL_TYPE=13 OR CALL_TYPE=12 OR CALL_TYPE=14 OR CALL_TYPE=18),UL_DATA_THRU*CALL_CNT, 0))/SUM(IF((CALL_TYPE=13 OR CALL_TYPE=12 OR CALL_TYPE=14 OR CALL_TYPE=18),CALL_CNT, 0)) AS UL_THROUGHPUT
					,SUM(IF((CALL_TYPE=13 OR CALL_TYPE=12 OR CALL_TYPE=14 OR CALL_TYPE=18),DL_DATA_THRU, 0)) AS DL_THROUGHPUT
					,SUM(IF((CALL_TYPE=13 OR CALL_TYPE=12 OR CALL_TYPE=14 OR CALL_TYPE=18),UL_DATA_THRU, 0)) AS UL_THROUGHPUT
				FROM (
				    SELECT
						 DATA_DATE
						, DATA_HOUR
						, POS_FIRST_FREQUENCY AS FREQUENCY
						, POS_FIRST_UARFCN AS UARFCN
						, INDOOR
						, MOVING
						, gt_covmo_proj_geohash_to_hex_geohash(POS_FIRST_LOC)  AS TILE_ID
						, POS_FIRST_RNC AS RNC_ID
						, POS_FIRST_CELL_INDOOR AS CELL_INDOOR
						, POS_FIRST_CLUSTER AS CLUSTER_ID
						, POS_FIRST_SITE AS SITE_ID
						, POS_FIRST_CELL AS CELL_ID
						, CALL_TYPE 
						, CALL_STATUS
						, COUNT(POS_FIRST_CELL) AS CALL_CNT
						, SUM(RRC_CONNECT_DURATION/1000)/3600 AS ERLANG
						, SUM(DL_TRAFFIC_VOLUME)*8/3600 AS DL_DATA_THRU
						, SUM(UL_TRAFFIC_VOLUME)*8/3600 AS UL_DATA_THRU
					FROM ',DY_GT_DB,'.`tmp_table_call','_',WORKER_ID,'`
					#FROM ',DY_GT_DB,'.`table_call`
					WHERE POS_FIRST_RNC =',RNC_ID,'
					AND POS_FIRST_RSCP IS NOT NULL
					AND DATA_HOUR=',START_HH,'
					GROUP BY  DATA_DATE
						, DATA_HOUR
						, POS_FIRST_FREQUENCY 
						, POS_FIRST_UARFCN 
						, INDOOR
						, MOVING
						, gt_covmo_proj_geohash_to_hex_geohash(POS_FIRST_LOC)
						, POS_FIRST_RNC
						, POS_FIRST_CELL_INDOOR
						, POS_FIRST_CLUSTER
						, POS_FIRST_SITE
						, POS_FIRST_CELL
						, CALL_TYPE 
						, CALL_STATUS
				) A
				GROUP BY RNC_ID,CELL_ID HAVING 1
				;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_Special_Report_Hourly','step 4', NOW());
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS  ',DY_GT_DB,'.`tmp_sh_table_last','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',DY_GT_DB,'.`tmp_sh_table_last','_',WORKER_ID,'` ENGINE=MYISAM
				SELECT POS_LAST_RNC AS RNC_ID 
					,POS_LAST_CELL AS CELL_ID 
					,SUM(IRAT_HHO_ATTEMPT) AS IRHO_ATTEMPT
					,SUM(IRAT_HHO_SUCCESS) AS IRHO_SUCCESS
				FROM ',DY_GT_DB,'.`tmp_table_call','_',WORKER_ID,'`
				WHERE POS_LAST_CELL IS NOT NULL AND DATA_HOUR=',START_HH,'
				GROUP BY POS_LAST_RNC,POS_LAST_CELL;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_Special_Report_Hourly','step 5', NOW());
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS  ',DY_GT_DB,'.`tmp_sh_table_fp','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',DY_GT_DB,'.`tmp_sh_table_fp','_',WORKER_ID,'` ENGINE=MYISAM
				SELECT  gt_covmo_csv_get(RNC_ID,1) RNC_ID
					, gt_covmo_csv_get(CELL_ID,1) CELL_ID
					,SUM(IF(gt_covmo_polluter(RSCP, ECN0,',@pilot_rscp,',',@pilot_ecn0,',',@pilot_rscp_delta,')>',@pilot_pollution_trigger,',1,0)) as  PP_CNT
					,SUM(IF(gt_covmo_polluter(RSCP, ECN0,',@pilot_rscp,',',@pilot_ecn0,',',@pilot_rscp_delta,')>',@pilot_pollution_trigger,',gt_covmo_polluter(RSCP, ECN0,',@pilot_rscp,',',@pilot_ecn0,',',@pilot_rscp_delta,')-',@pilot_pollution_trigger,',0)) AS POLLUTER
					,SUM(IF(gt_covmo_polluter(RSCP, ECN0,',@pilot_rscp,',',@pilot_ecn0,',',@pilot_rscp_delta,')>',@pilot_pollution_trigger,',1,0)) AS polluted_mr	
				FROM ',DY_GT_DB,'.`tmp_table_call','_',WORKER_ID,'` A  FORCE INDEX (CALL_ID), ',DY_GT_DB,'.table_position B FORCE INDEX (CALL_ID)
				WHERE A.CALL_ID=B.CALL_ID
				AND gt_covmo_csv_getnum(B.RNC_ID,1)=',RNC_ID,'
				AND RSCP IS NOT NULL 
				AND A.DATA_HOUR=',START_HH,' AND B.DATA_HOUR=',START_HH,'
				AND EVENT_ID NOT IN (''20'',''21'',''22'',''23'',''24'',''25'',''26'',''27'',''28'')
				GROUP BY gt_covmo_csv_get(RNC_ID,1),gt_covmo_csv_get(CELL_ID,1)
				ORDER BY NULL;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_Special_Report_Hourly','step 6', NOW());
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS  ',DY_GT_DB,'.`tmp_sh_table_status2','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',DY_GT_DB,'.`tmp_sh_table_status2','_',WORKER_ID,'` ENGINE=MYISAM
				SELECT  POS_LAST_RNC RNC_ID
					,POS_LAST_CELL CELL_ID
					,SUM(CASE WHEN CALL_STATUS IN (1) THEN 1 ELSE 0 END) AS NORMAL_CALL_COUNT
					,SUM(CASE WHEN CALL_STATUS IN (2) THEN 1 ELSE 0 END) AS DROP_CALL_COUNT
					,SUM(CASE WHEN CALL_STATUS IN (2) AND IU_RELEASE_CAUSE = 14 THEN 1 ELSE 0 END) AS FAILURE_IN_THE_RADIO_INTERFACE_PROCEDURE
					,SUM(CASE WHEN CALL_STATUS IN (2) AND IU_RELEASE_CAUSE = 15 THEN 1 ELSE 0 END) AS UTRAN_QENERATED_REASON
					,SUM(CASE WHEN CALL_STATUS IN (2) AND IU_RELEASE_CAUSE = 46 THEN 1 ELSE 0 END) AS RADIO_CONNECTION_WITH_UE_LOST
					,SUM(CASE WHEN CALL_STATUS IN (2) AND IU_RELEASE_CAUSE = 115 THEN 1 ELSE 0 END) AS UNSPECIFIED_FAILURE
					,SUM(CASE WHEN CALL_STATUS IN (2) AND IU_RELEASE_CAUSE NOT IN (14,15,46,115) THEN 1 ELSE 0 END) AS OTHER
				FROM ',DY_GT_DB,'.`tmp_table_call','_',WORKER_ID,'`
				WHERE POS_LAST_RNC IS NOT NULL AND POS_LAST_CELL IS NOT NULL AND DATA_HOUR=',START_HH,'
				GROUP BY POS_LAST_RNC,POS_LAST_CELL
				ORDER BY NULL;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_Special_Report_Hourly','step 7', NOW());
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS  ',DY_GT_DB,'.`tmp_sh_table_event','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',DY_GT_DB,'.`tmp_sh_table_event','_',WORKER_ID,'` ENGINE=MYISAM
				SELECT 
				  RNC_ID,CELL_ID,
				  SUM(L3_E1A) AS e1a,
				  SUM(L3_E1B) AS e1b,
				  SUM(L3_E1C) AS e1c,
				  SUM(L3_E1D) AS e1d,
				  SUM(L3_E1E) AS e1e,
				  SUM(L3_E1F) AS e1f,
				  SUM(L3_E2A) AS e2a,
				  SUM(L3_E2B) AS e2b,
				  SUM(L3_E2D) AS e2d,
				  SUM(L3_E2F) AS e2f,
				  SUM(L3_E3A) AS e3a,
				  SUM(L3_E4A) AS e4a,
				  SUM(L3_E4B) AS e4b,
				  SUM(L3_E6A) AS e6a
				FROM
				  ',DY_GT_DB,'.table_tile_fp
				WHERE CELL_ID IS NOT NULL
				  AND DATA_DATE =  ''',START_DATE,''' 
				  AND DATA_HOUR = ',START_HH,'
				  AND RNC_ID = ',RNC_ID,' 
				GROUP BY RNC_ID,  CELL_ID 
	;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_Special_Report_Hourly','step 8', NOW());
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS  ',DY_GT_DB,'.`tmp_sh_table_fp2','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',DY_GT_DB,'.`tmp_sh_table_fp2','_',WORKER_ID,'` ENGINE=MYISAM
				SELECT  
					RNC_ID
					,CELL_ID
					,SUM(TOTAL_AS_CNT)/SUM(BEST_CNT) AS AVERAGE_NUMBER_OF_ACTIVE_SET
				FROM ',DY_GT_DB,'.`table_tile_fp`
				WHERE 
					CELL_ID IS NOT NULL  AND 
					TOTAL_AS_CNT IS NOT NULL AND  
					DATA_DATE = ''',START_DATE,''' AND 
					DATA_HOUR = ',START_HH,' AND 
					RNC_ID = ',RNC_ID,'	
				GROUP BY RNC_ID,CELL_ID
				ORDER BY NULL;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_Special_Report_Hourly','step 9', NOW());
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE IF EXISTS  ',DY_GT_DB,'.`tmp_special_hourly_report_csv','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',DY_GT_DB,'.`tmp_special_hourly_report_csv','_',WORKER_ID,'`
				(
				  `DATA_DATE` DATE DEFAULT NULL,
				  `DATA_HOUR` TINYINT(4) DEFAULT NULL,
				  `RNC_ID` VARCHAR(50) DEFAULT NULL,
				  `CELL_ID` VARCHAR(50) DEFAULT NULL,
				  `VOICE` INT(11) DEFAULT NULL,
				  `PS_99` INT(11) DEFAULT NULL,
				  `PS_HSPA` INT(11) DEFAULT NULL,
				  `PS_OTHER` INT(11) DEFAULT NULL,
				  `MULTI_RAB` INT(11) DEFAULT NULL,
				  `SMS` INT(11) DEFAULT NULL,
				  `TOTAL_CALL_COUNT` INT(11) DEFAULT NULL,
				  `NORMAL_CALL_COUNT` INT(11) DEFAULT NULL,
				  `BLOCK_CALL_COUNT` INT(11) DEFAULT NULL,
				  `DROP_CALL_COUNT` INT(11) DEFAULT NULL,
				  `FAILURE_IN_THE_RADIO_INTERFACE_PROCEDURE` INT(11) DEFAULT NULL,
				  `UTRAN_QENERATED_REASON` INT(11) DEFAULT NULL,
				  `RADIO_CONNECTION_WITH_UE_LOST` INT(11) DEFAULT NULL,
				  `UNSPECIFIED_FAILURE` INT(11) DEFAULT NULL,
				  `OTHER` INT(11) DEFAULT NULL,
				  `BLOCK_RATE` DOUBLE DEFAULT NULL,
				  `DROP_RATE` DOUBLE DEFAULT NULL,
				  `TOTAL_CALL_DURATION` BIGINT(20) DEFAULT NULL,
				  `CS_ERLANG` DOUBLE DEFAULT NULL,
				  `PS_R99_DL_TRAFFIC_VOLUME` DOUBLE DEFAULT NULL,
				  `PS_HSPA_DL_TRAFFIC_VOLUME` DOUBLE DEFAULT NULL,
				  `PS_OTHER_DL_TRAFFIC_VOLUME` DOUBLE DEFAULT NULL,
				  `PS_R99_UL_TRAFFIC_VOLUME` DOUBLE DEFAULT NULL,
				  `PS_HSPA_UL_TRAFFIC_VOLUME` DOUBLE DEFAULT NULL,
				  `PS_OTHER_UL_TRAFFIC_VOLUME` DOUBLE DEFAULT NULL,
				  `DL_THROUGHPUT` DOUBLE DEFAULT NULL,
				  `UL_THROUGHPUT` DOUBLE DEFAULT NULL,
				  `e1a` INT(11) DEFAULT NULL,
				  `e1b` INT(11) DEFAULT NULL,
				  `e1c` INT(11) DEFAULT NULL,
				  `e1d` INT(11) DEFAULT NULL,
				  `e1e` INT(11) DEFAULT NULL,
				  `e1f` INT(11) DEFAULT NULL,
				  `e2a` INT(11) DEFAULT NULL,
				  `e2b` INT(11) DEFAULT NULL,
				  `e2d` INT(11) DEFAULT NULL,
				  `e2f` INT(11) DEFAULT NULL,
				  `e3a` INT(11) DEFAULT NULL,
				  `e4a` INT(11) DEFAULT NULL,
				  `e4b` INT(11) DEFAULT NULL,
				  `e6a` INT(11) DEFAULT NULL,
				  `POLLUTED_MR` DOUBLE DEFAULT NULL,
				  `AVERAGE_POLLUTER` DOUBLE DEFAULT NULL,
				  `AVERAGE_NUMBER_OF_ACTIVE_SET` DOUBLE DEFAULT NULL,
				  `IRHO_ATTEMPT` SMALLINT(6) DEFAULT NULL,
				  `IRHO_SUCCESS` SMALLINT(6) DEFAULT NULL,
				  `IFHO_CALL_COUNT` INT(11) DEFAULT NULL
				) ENGINE=MYISAM DEFAULT CHARSET=LATIN1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_Special_Report_Hourly','step 10', NOW());
	
	SET @SqlCmd=CONCAT('INSERT INTO ',DY_GT_DB,'.`tmp_special_hourly_report_csv','_',WORKER_ID,'` ( RNC_ID,CELL_ID)
				SELECT RNC_ID,CELL_ID
				FROM 
				(
					SELECT RNC_ID,CELL_ID FROM ',DY_GT_DB,'.`tmp_sh_table_first','_',WORKER_ID,'`
					UNION 
					SELECT RNC_ID,CELL_ID FROM ',DY_GT_DB,'.`tmp_sh_table_start','_',WORKER_ID,'`
					UNION 
-- 					SELECT RNC_ID,CELL_ID FROM ',DY_GT_DB,'.`tmp_sh_table_ifho','_',WORKER_ID,'`
-- 					UNION
					SELECT RNC_ID,CELL_ID FROM ',DY_GT_DB,'.`tmp_sh_table_last','_',WORKER_ID,'`
					UNION 
					SELECT RNC_ID,CELL_ID FROM ',DY_GT_DB,'.`tmp_sh_table_fp','_',WORKER_ID,'`
					UNION 
					SELECT RNC_ID,CELL_ID FROM ',DY_GT_DB,'.`tmp_sh_table_event','_',WORKER_ID,'`
					UNION 
					SELECT RNC_ID,CELL_ID FROM ',DY_GT_DB,'.`tmp_sh_table_fp2','_',WORKER_ID,'`
				) AA;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_Special_Report_Hourly','step 11', NOW());
	
	SET @SqlCmd=CONCAT('UPDATE ',DY_GT_DB,'.`tmp_special_hourly_report_csv','_',WORKER_ID,'` a ,',DY_GT_DB,'.`tmp_sh_table_first','_',WORKER_ID,'` B
				SET 
					A.VOICE=B.VOICE
					,A.PS_99=B.PS_99
					,A.PS_HSPA=B.PS_HSPA
					,A.PS_OTHER=B.PS_OTHER
					,A.MULTI_RAB=B.MULTI_RAB
					,A.SMS=B.SMS
					,A.TOTAL_CALL_COUNT=B.NORMAL_CALL_COUNT + B.BLOCK_CALL_COUNT + B.DROP_CALL_COUNT
					,A.NORMAL_CALL_COUNT=B.NORMAL_CALL_COUNT
					,A.BLOCK_CALL_COUNT=B.BLOCK_CALL_COUNT
					,A.BLOCK_RATE=B.BLOCK_CALL_COUNT/(B.NORMAL_CALL_COUNT + B.BLOCK_CALL_COUNT + B.DROP_CALL_COUNT)
					,A.TOTAL_CALL_DURATION=B.TOTAL_CALL_DURATION
					,A.PS_R99_DL_TRAFFIC_VOLUME=B.PS_R99_DL_TRAFFIC_VOLUME
					,A.PS_HSPA_DL_TRAFFIC_VOLUME=B.PS_HSPA_DL_TRAFFIC_VOLUME
					,A.PS_OTHER_DL_TRAFFIC_VOLUME=B.PS_OTHER_DL_TRAFFIC_VOLUME
					,A.PS_R99_UL_TRAFFIC_VOLUME=B.PS_R99_UL_TRAFFIC_VOLUME
					,A.PS_HSPA_UL_TRAFFIC_VOLUME=B.PS_HSPA_UL_TRAFFIC_VOLUME
					,A.PS_OTHER_UL_TRAFFIC_VOLUME=B.PS_OTHER_UL_TRAFFIC_VOLUME
					,A.CS_ERLANG=B.CS_ERLANG
					,A.PS_OTHER=B.PS_OTHER
					,A.PS_OTHER_DL_TRAFFIC_VOLUME=B.PS_OTHER_DL_TRAFFIC_VOLUME
					,A.PS_OTHER_UL_TRAFFIC_VOLUME=B.PS_OTHER_UL_TRAFFIC_VOLUME
				WHERE A.RNC_ID=B.RNC_ID AND A.CELL_ID=B.CELL_ID;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	SET @SqlCmd=CONCAT('UPDATE ',DY_GT_DB,'.`tmp_special_hourly_report_csv','_',WORKER_ID,'` a,',DY_GT_DB,'.`tmp_sh_table_start','_',WORKER_ID,'` B
				SET 
					A.DL_THROUGHPUT=B.DL_THROUGHPUT
					,A.UL_THROUGHPUT=B.UL_THROUGHPUT
				WHERE A.RNC_ID=B.RNC_ID AND A.CELL_ID=B.CELL_ID;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('UPDATE ',DY_GT_DB,'.`tmp_special_hourly_report_csv','_',WORKER_ID,'` a,',DY_GT_DB,'.`tmp_sh_table_status2','_',WORKER_ID,'` B
				SET 
					A.DROP_CALL_COUNT=B.DROP_CALL_COUNT
					,A.FAILURE_IN_THE_RADIO_INTERFACE_PROCEDURE=B.FAILURE_IN_THE_RADIO_INTERFACE_PROCEDURE
					,A.UTRAN_QENERATED_REASON=B.UTRAN_QENERATED_REASON
					,A.RADIO_CONNECTION_WITH_UE_LOST=B.RADIO_CONNECTION_WITH_UE_LOST
					,A.UNSPECIFIED_FAILURE=B.UNSPECIFIED_FAILURE
					,A.OTHER=B.OTHER
					,A.DROP_RATE=B.DROP_CALL_COUNT/(B.NORMAL_CALL_COUNT+B.DROP_CALL_COUNT)
				WHERE A.RNC_ID=B.RNC_ID AND A.CELL_ID=B.CELL_ID;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('UPDATE ',DY_GT_DB,'.`tmp_special_hourly_report_csv','_',WORKER_ID,'` a,',DY_GT_DB,'.`tmp_sh_table_last','_',WORKER_ID,'` B
				SET 	A.IRHO_ATTEMPT=B.IRHO_ATTEMPT
					,A.IRHO_SUCCESS=B.IRHO_SUCCESS
				WHERE A.RNC_ID=B.RNC_ID AND A.CELL_ID=B.CELL_ID ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('UPDATE ',DY_GT_DB,'.`tmp_special_hourly_report_csv','_',WORKER_ID,'` a,',DY_GT_DB,'.`tmp_sh_table_fp','_',WORKER_ID,'` B
				SET 
					A.AVERAGE_POLLUTER=B.POLLUTER/PP_CNT
					,A.POLLUTED_MR=B.POLLUTED_MR
				WHERE A.RNC_ID=B.RNC_ID AND A.CELL_ID=B.CELL_ID ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('UPDATE ',DY_GT_DB,'.`tmp_special_hourly_report_csv','_',WORKER_ID,'` a,',DY_GT_DB,'.`tmp_sh_table_event','_',WORKER_ID,'` B
				SET 
					A.e1a=B.e1a
					,A.e1b=B.e1b
					,A.e1c=B.e1c
					,A.e1d=B.e1d
					,A.e1e=B.e1e
					,A.e1f=B.e1f
					,A.e2a=B.e2a
					,A.e2b=B.e2b
					,A.e2d=B.e2d
					,A.e2f=B.e2f
					,A.e3a=B.e3a
					,A.e4a=B.e4a
					,A.e4b=B.e4b
					,A.e6a=B.e6a
				WHERE A.RNC_ID=B.RNC_ID AND A.CELL_ID=B.CELL_ID ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('UPDATE ',DY_GT_DB,'.`tmp_special_hourly_report_csv','_',WORKER_ID,'` a,',DY_GT_DB,'.`tmp_sh_table_fp2','_',WORKER_ID,'` B
				SET 
					A.AVERAGE_NUMBER_OF_ACTIVE_SET=B.AVERAGE_NUMBER_OF_ACTIVE_SET
				WHERE A.RNC_ID=B.RNC_ID AND A.CELL_ID=B.CELL_ID ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_Special_Report_Hourly','step 12', NOW());
	
	SET @SqlCmd=CONCAT('SELECT
				''DATA_DATE'',
				''DATA_HOUR'',
				''RNC_ID'',
				''CELL_ID'',
				''VOICE'',
				''PS_99'',
				''PS_HSPA'',
				''PS_OTHER'',
				''MULTI_RAB'',
				''SMS'',
				''TOTAL_CALL_COUNT'',
				''NORMAL_CALL_COUNT'',
				''BLOCK_CALL_COUNT'',
				''DROP_CALL_COUNT'',
				''FAILURE_IN_THE_RADIO_INTERFACE_PROCEDURE'',
				''UTRAN_QENERATED_REASON'',
				''RADIO_CONNECTION_WITH_UE_LOST'',
				''UNSPECIFIED_FAILURE'',
				''OTHER'',
				''BLOCK_RATE'',
				''DROP_RATE'',
				''TOTAL_CALL_DURATION'',
				''CS_ERLANG'',
				''PS_R99_DL_TRAFFIC_VOLUME'',
				''PS_HSPA_DL_TRAFFIC_VOLUME'',
				''PS_OTHER_DL_TRAFFIC_VOLUME'',
				''PS_R99_UL_TRAFFIC_VOLUME'',
				''PS_HSPA_UL_TRAFFIC_VOLUME'',
				''PS_OTHER_UL_TRAFFIC_VOLUME'',
				''DL_THROUGHPUT'',
				''UL_THROUGHPUT'',
				''e1a'',
				''e1b'',
				''e1c'',
				''e1d'',
				''e1e'',
				''e1f'',
				''e2a'',
				''e2b'',
				''e2d'',
				''e2f'',
				''e3a'',
				''e4a'',
				''e4b'',
				''e6a'',
				''POLLUTED_MR'',
				''AVERAGE_POLLUTER'',
				''AVERAGE_NUMBER_OF_ACTIVE_SET'',
				''IRHO_ATTEMPT'',
				''IRHO_SUCCESS'',
				''IFHO_CALL_COUNT''
			    UNION 
			    SELECT 
				''',START_DATE,''',
				''',START_HH,''',
				`RNC_ID`,
				`CELL_ID`,
				COALESCE(`VOICE`),
				COALESCE(`PS_99`),
				COALESCE(`PS_HSPA`),
				COALESCE(`PS_OTHER`),
				COALESCE(`MULTI_RAB`),
				COALESCE(`SMS`),
				COALESCE(`TOTAL_CALL_COUNT`),
				COALESCE(`NORMAL_CALL_COUNT`),
				COALESCE(`BLOCK_CALL_COUNT`),
				COALESCE(`DROP_CALL_COUNT`),
				COALESCE(`FAILURE_IN_THE_RADIO_INTERFACE_PROCEDURE`),
				COALESCE(`UTRAN_QENERATED_REASON`),
				COALESCE(`RADIO_CONNECTION_WITH_UE_LOST`),
				COALESCE(`UNSPECIFIED_FAILURE`),
				COALESCE(`OTHER`),
				COALESCE(`BLOCK_RATE`),
				COALESCE(`DROP_RATE`),
				COALESCE(`TOTAL_CALL_DURATION`),
				COALESCE(`CS_ERLANG`),
				COALESCE(`PS_R99_DL_TRAFFIC_VOLUME`),
				COALESCE(`PS_HSPA_DL_TRAFFIC_VOLUME`),
				COALESCE(`PS_OTHER_DL_TRAFFIC_VOLUME`),
				COALESCE(`PS_R99_UL_TRAFFIC_VOLUME`),
				COALESCE(`PS_HSPA_UL_TRAFFIC_VOLUME`),
				COALESCE(`PS_OTHER_UL_TRAFFIC_VOLUME`),
				COALESCE(`DL_THROUGHPUT`),
				COALESCE(`UL_THROUGHPUT`),
				COALESCE(`e1a`),
				COALESCE(`e1b`),
				COALESCE(`e1c`),
				COALESCE(`e1d`),
				COALESCE(`e1e`),
				COALESCE(`e1f`),
				COALESCE(`e2a`),
				COALESCE(`e2b`),
				COALESCE(`e2d`),
				COALESCE(`e2f`),
				COALESCE(`e3a`),
				COALESCE(`e4a`),
				COALESCE(`e4b`),
				COALESCE(`e6a`),
				COALESCE(`POLLUTED_MR`),
				COALESCE(`AVERAGE_POLLUTER`),
				COALESCE(`AVERAGE_NUMBER_OF_ACTIVE_SET`),
				COALESCE(`IRHO_ATTEMPT`),
				COALESCE(`IRHO_SUCCESS`),
				COALESCE(`IFHO_CALL_COUNT`)
			    FROM ',DY_GT_DB,'.`tmp_special_hourly_report_csv','_',WORKER_ID,'`
			    WHERE `RNC_ID`=',RNC_ID,' 
			    INTO OUTFILE ''',PATH,'/',CASE VENDOR_ID 
					WHEN 1 THEN 'Ericsson'
					WHEN 2 THEN 'Huawei'
					WHEN 3 THEN 'Huawei'
					WHEN 7 THEN 'NSN'
				 END 
				,'-',RNC_ID,'-',START_DATE,'-',START_HH,'-'
				,CASE START_MM 
					WHEN '00' THEN '1'
					WHEN '15' THEN '2'
					WHEN '30' THEN '3'
					WHEN '45' THEN '4'
				 END 
				,'_SPECIAL_HOURLY.csv''
			    FIELDS TERMINATED BY '',''
			    LINES TERMINATED BY ''\n''
			    ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE ',DY_GT_DB,'.`tmp_sh_table_first','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE ',DY_GT_DB,'.`tmp_sh_table_last','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;	
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE ',DY_GT_DB,'.`tmp_sh_table_fp','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;		
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE ',DY_GT_DB,'.`tmp_special_hourly_report_csv','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;		
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE ',DY_GT_DB,'.`tmp_sh_table_status2','_',WORKER_ID,'` ;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;	
	
	INSERT INTO gt_gw_main.SP_LOG VALUES(O_GT_DB,'SP_Sub_Generate_Special_Report_Hourly',CONCAT('Done: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());	
	
        SET SESSION max_heap_table_size = 1024*1024*128; 
        SET SESSION tmp_table_size = 1024*1024*128; 
        SET SESSION join_buffer_size = 1024*1024*128; 
        SET SESSION sort_buffer_size = 1024*1024*128; 
        SET SESSION read_buffer_size = 1024*1024*128; 
	
END$$
DELIMITER ;
