DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Sub_Gen_CELL_LTE_PARALLEL_AWK`(IN RPT_TBL_NAME VARCHAR(100),IN TMP_GT_DB VARCHAR(100),IN GT_DB VARCHAR(100),FLAG VARCHAR(100),SN TINYINT(2),INSERT_FLAG TINYINT(2))
BEGIN
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE STEP_START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE WORKER_ID VARCHAR(10) DEFAULT CONNECTION_ID();	
	DECLARE KEY_COLUMN_STR VARCHAR(1500) DEFAULT '';
	DECLARE GROUP_STR VARCHAR(1500) DEFAULT '';
	DECLARE GROUP_DEF_STR VARCHAR(1500) DEFAULT '';
	DECLARE DATA_HR VARCHAR(1500) DEFAULT SUBSTRING(gt_strtok(TMP_GT_DB,4,'_'),1,2);
	DECLARE DATA_QR1 VARCHAR(1500) DEFAULT CONCAT(DATA_HR,'00');
	DECLARE DATA_QR2 VARCHAR(1500) DEFAULT CONCAT(DATA_HR,'15');
	DECLARE DATA_QR3 VARCHAR(1500) DEFAULT CONCAT(DATA_HR,'30');
	DECLARE DATA_QR4 VARCHAR(1500) DEFAULT CONCAT(DATA_HR,'45');
	DECLARE FILEDATE VARCHAR(30) ;
	DECLARE PU_ID VARCHAR(10);
	DECLARE COLUMN_STR VARCHAR(3000) DEFAULT 
		'RRC_CONN_SETUP_ATTEMPT,
		RRC_CONN_SETUP_REJECT,
		RRC_CONN_SETUP_MISSING_COMPLETE,
		ERAB_SETUP_ATTEMPT,
		ERAB_SETUP_REJECT,
		ERAB_SETUP_ACCS_DELAY,
		UE_CNXT_DROP_SETUP,
		UE_CNXT_DROP_DROP,
		RRC_RE_ESTABLISHMENT_ATTEMPT,
		RRC_RE_ESTABLISHMENT_FAILURE,
		MIMO_USAGE_RATIO_NUM,
		MIMO_USAGE_RATIO_DEN,
		SUBSC_PET_CELL_PER_HR,
		CALL_DURATION_SUM,
		CALL_DURATION_CNT,
		COVMO_DATA_AVAILABILITY,
		4G_4G_HO_ATTEMPT,
		4G_4G_HO_FAILURE,
		RRC_RECONFIGURATION_ATTEMPT,
		RRC_RECONFIGURATION_FAILURE,
		CSFB_EXECUTIONS,
		UE_CNXT_REL_TOT,
		IRAT_PING_PONG,
		IRAT_RSRP,
		IRAT_RSRQ,
		IRAT_TA,
		IRAT_RSCP,
		IRAT_ECN0,
		IRAT_RSSI,
		4G_3G_HO_ATTEMPT,	
		4G_3G_HO_FAILURE,
		4G_2G_HO_ATTEMPT,
		4G_2G_HO_FAILURE,
		BLIND_REDIR_4G_3G,
	 	BLIND_REDIR_4G_2G,
		4G_3G_CSFB_HO_ATT,
		4G_3G_CSFB_HO_SUCC,
		4G_3G_CSFB_HO_FAILURE,
		VOLTE_ATTEMPT,
		VOLTE_SUCCESS,
		VOLTE_FAILURE,
		PROCEDURE_TIME_SUM,
		PROCEDURE_TIME_CNT,
		ACCESSIBILITY_TIME_SUM,
		ACCESSIBILITY_TIME_CNT,
		IRAT_RSRP_CNT,
		IRAT_RSRQ_CNT,
		IRAT_TA_CNT,
		IRAT_RSCP_CNT,
		IRAT_ECN0_CNT,
		IRAT_RSSI_CNT,
		PEAK_SUBSCRIBER,
		PEAK_QUARTER,
		VOLTE_DROP,
		VOLTE_END,
		DL_VOLUME_SUM,
		UL_VOLUME_SUM,
		DL_THROUGHPUT_SUM,
		DL_THROUGHPUT_CNT,
		UL_THROUGHPUT_SUM,
		UL_THROUGHPUT_CNT,
		DL_THROUGHPUT_MAX,
		UL_THROUGHPUT_MAX,
		DL_TRAFFIC_DUR,
		UL_TRAFFIC_DUR';
		
	DECLARE COLUMN_IFNULL_STR VARCHAR(5000) DEFAULT 
		'IFNULL(RRC_CONN_SETUP_ATTEMPT,0) AS RRC_CONN_SETUP_ATTEMPT,
		IFNULL(RRC_CONN_SETUP_REJECT,0) AS RRC_CONN_SETUP_REJECT,
 		IFNULL(RRC_CONN_SETUP_MISSING_COMPLETE,0) AS RRC_CONN_SETUP_MISSING_COMPLETE,
		IFNULL(ERAB_SETUP_ATTEMPT,0) AS ERAB_SETUP_ATTEMPT,
		IFNULL(ERAB_SETUP_REJECT,0) AS ERAB_SETUP_REJECT,
 		IFNULL(ERAB_SETUP_ACCS_DELAY,0) AS ERAB_SETUP_ACCS_DELAY,
		IFNULL(UE_CNXT_DROP_SETUP,0) AS UE_CNXT_DROP_SETUP,
		IFNULL(UE_CNXT_DROP_DROP,0) AS UE_CNXT_DROP_DROP,
		IFNULL(RRC_RE_ESTABLISHMENT_ATTEMPT,0) AS RRC_RE_ESTABLISHMENT_ATTEMPT,
		IFNULL(RRC_RE_ESTABLISHMENT_FAILURE,0) AS RRC_RE_ESTABLISHMENT_FAILURE,
		IFNULL(MIMO_USAGE_RATIO_NUM,0) AS MIMO_USAGE_RATIO_NUM,
		IFNULL(MIMO_USAGE_RATIO_DEN,0) AS MIMO_USAGE_RATIO_DEN,
		IFNULL(SUBSC_PET_CELL_PER_HR,0) AS SUBSC_PET_CELL_PER_HR,
		IFNULL(CALL_DURATION_SUM,0) AS CALL_DURATION_SUM,
		IFNULL(CALL_DURATION_CNT,0) AS CALL_DURATION_CNT,
		IFNULL(COVMO_DATA_AVAILABILITY,1) AS COVMO_DATA_AVAILABILITY,
		IFNULL(4G_4G_HO_ATTEMPT,0) AS 4G_4G_HO_ATTEMPT,
		IFNULL(4G_4G_HO_FAILURE,0) AS 4G_4G_HO_FAILURE,
		IFNULL(RRC_RECONFIGURATION_ATTEMPT,0) AS RRC_RECONFIGURATION_ATTEMPT,
		IFNULL(RRC_RECONFIGURATION_FAILURE,0) AS RRC_RECONFIGURATION_FAILURE,
		IFNULL(CSFB_EXECUTIONS,0) AS CSFB_EXECUTIONS,
		IFNULL(UE_CNXT_REL_TOT,0) AS UE_CNXT_REL_TOT,
		IFNULL(IRAT_PING_PONG,0) AS IRAT_PING_PONG,
		IFNULL(IRAT_RSRP,0) AS IRAT_RSRP,
		IFNULL(IRAT_RSRQ,0) AS IRAT_RSRQ,
		IFNULL(IRAT_TA,0) AS IRAT_TA,
		IFNULL(IRAT_RSCP,0) AS IRAT_RSCP,
		IFNULL(IRAT_ECN0,0) AS IRAT_ECN0,
		IFNULL(IRAT_RSSI,0) AS IRAT_RSSI,
		IFNULL(4G_3G_HO_ATTEMPT,0) AS 	4G_3G_HO_ATTEMPT,
		IFNULL(4G_3G_HO_FAILURE,0) AS 4G_3G_HO_FAILURE,
		IFNULL(4G_2G_HO_ATTEMPT,0) AS 4G_2G_HO_ATTEMPT,
		IFNULL(4G_2G_HO_FAILURE,0) AS 4G_2G_HO_FAILURE,
		IFNULL(BLIND_REDIR_4G_3G,0) AS BLIND_REDIR_4G_3G,
		IFNULL(BLIND_REDIR_4G_2G,0) AS BLIND_REDIR_4G_2G,
		IFNULL(4G_3G_CSFB_HO_ATT,0) AS 4G_3G_CSFB_HO_ATT,
		IFNULL(4G_3G_CSFB_HO_SUCC,0) AS 4G_3G_CSFB_HO_SUCC,
		IFNULL(4G_3G_CSFB_HO_FAILURE,0) AS 4G_3G_CSFB_HO_FAILURE,
		IFNULL(VOLTE_ATTEMPT,0) AS VOLTE_ATTEMPT,
		IFNULL(VOLTE_SUCCESS,0) AS VOLTE_SUCCESS,
		IFNULL(VOLTE_FAILURE,0) AS VOLTE_FAILURE,
		IFNULL(PROCEDURE_TIME_SUM,0) AS PROCEDURE_TIME_SUM,
		IFNULL(PROCEDURE_TIME_CNT,0) AS PROCEDURE_TIME_CNT,
		IFNULL(ACCESSIBILITY_TIME_SUM,0) AS ACCESSIBILITY_TIME_SUM,
		IFNULL(ACCESSIBILITY_TIME_CNT,0) AS ACCESSIBILITY_TIME_CNT,
		IFNULL(IRAT_RSRP_CNT,0) AS IRAT_RSRP_CNT,
		IFNULL(IRAT_RSRQ_CNT,0) AS IRAT_RSRQ_CNT,
		IFNULL(IRAT_TA_CNT,0) AS IRAT_TA_CNT,
		IFNULL(IRAT_RSCP_CNT,0) AS IRAT_RSCP_CNT,
		IFNULL(IRAT_ECN0_CNT,0) AS IRAT_ECN0_CNT,
		IFNULL(IRAT_RSSI_CNT,0) AS IRAT_RSSI_CNT,
		IFNULL(PEAK_SUBSCRIBER,0) AS PEAK_SUBSCRIBER,
		IFNULL(PEAK_QUARTER,0) AS PEAK_QUARTER,
		IFNULL(VOLTE_DROP,0) AS VOLTE_DROP,
		IFNULL(VOLTE_END,0) AS VOLTE_END,
		IFNULL(DL_VOLUME_SUM,0) AS DL_VOLUME_SUM,
		IFNULL(UL_VOLUME_SUM,0) AS UL_VOLUME_SUM,
		IFNULL(DL_THROUGHPUT_SUM,0) AS DL_THROUGHPUT_SUM,
		IFNULL(DL_THROUGHPUT_CNT,0) AS DL_THROUGHPUT_CNT,
		IFNULL(UL_THROUGHPUT_SUM,0) AS UL_THROUGHPUT_SUM,
		IFNULL(UL_THROUGHPUT_CNT,0) AS UL_THROUGHPUT_CNT,
		IFNULL(DL_THROUGHPUT_MAX,0) AS DL_THROUGHPUT_MAX,
		IFNULL(UL_THROUGHPUT_MAX,0) AS UL_THROUGHPUT_MAX,
		IFNULL(DL_TRAFFIC_DUR,0) AS DL_TRAFFIC_DUR,
		IFNULL(UL_TRAFFIC_DUR,0) AS UL_TRAFFIC_DUR';
	
	DECLARE COLUMN_SUM_STR VARCHAR(5000) DEFAULT 
		'SUM(IFNULL(RRC_CONN_REQ,0)) AS RRC_CONN_SETUP_ATTEMPT,
		SUM(IFNULL(RRC_CONN_REJ,0)) AS RRC_CONN_SETUP_REJECT,
		SUM(IFNULL(RRC_CONN_SETUP,0) - IFNULL(RRC_CONN_SETUP_COMPLETE,0)) AS RRC_CONN_SETUP_MISSING_COMPLETE,
		SUM(IFNULL(ERAB_SETUP_ATT,0) +IFNULL(INIT_CNXT_SETUP_ATT,0)) AS ERAB_SETUP_ATTEMPT,
		SUM(IFNULL(ERAB_SETUP_FAIL,0) + IFNULL(INIT_CNXT_SETUP_FAIL,0)) AS ERAB_SETUP_REJECT,
		SUM(IFNULL(ERAB_ACCESS_DELAY,0)) AS ERAB_SETUP_ACCS_DELAY,
		SUM(IFNULL(UE_CNXT_REL_NORMAL,0)+IFNULL(UE_CNXT_REL_ABNORMAL,0)) AS UE_CNXT_DROP_SETUP,
		SUM(IFNULL(UE_CNXT_REL_ABNORMAL,0)) AS UE_CNXT_DROP_DROP,
		SUM(IFNULL(RRC_CONN_REEST_ATT,0)) AS RRC_RE_ESTABLISHMENT_ATTEMPT,
		SUM(IFNULL(RRC_CONN_REEST_FAIL,0)) AS RRC_RE_ESTABLISHMENT_FAILURE,
		SUM((IFNULL(Rrc_Conn_Reconfig_MIMO,0) + IFNULL(Rrc_Conn_Setup_MIMO,0))) AS MIMO_USAGE_RATIO_NUM,
		SUM((IFNULL(RRC_CONN_RECONFIG_NOT_MIMO,0) + IFNULL(Rrc_Conn_Setup_Not_MIMO,0) +IFNULL(Rrc_Conn_Reconfig_MIMO,0) + IFNULL(Rrc_Conn_Setup_MIMO,0))) AS MIMO_USAGE_RATIO_DEN,
		SUM(IFNULL(SUBSCRIBER,0)) AS SUBSC_PET_CELL_PER_HR,
		SUM(IFNULL(CALL_DURATION_SUM,0)) AS CALL_DURATION_SUM,
		SUM(IFNULL(CALL_DURATION_CNT,0)) AS CALL_DURATION_CNT, 
		SUM(IFNULL(4G_4G_HO_S1_ATT,0)+IFNULL(4G_4G_HO_X2_ATT,0)) AS 4G_4G_HO_ATTEMPT,
		SUM(IFNULL(4G_4G_HO_S1_FAIL,0)+IFNULL(4G_4G_HO_X2_FAIL,0)) AS 4G_4G_HO_FAILURE,
		SUM(RRC_CONN_RECONFIG_ATT) AS RRC_RECONFIGURATION_ATTEMPT,
		SUM(RRC_CONN_RECONFIG_FAIL) AS RRC_RECONFIGURATION_FAILURE,
		SUM(UE_CNXT_REL_CSFB) AS CSFB_EXECUTIONS,
		SUM(UE_CNXT_REL_TOT) AS UE_CNXT_REL_TOT,
		SUM(IRAT_PING_PONG) AS IRAT_PING_PONG,
		SUM(RSRP_IRAT) AS IRAT_RSRP,	
		SUM(RSRQ_IRAT) AS IRAT_RSRQ,
		SUM(TA) AS IRAT_TA,
		SUM(RSCP_IRAT) AS IRAT_RSCP,
		SUM(ECNO_IRAT) AS IRAT_ECN0,
		SUM(RSSI_IRAT) AS IRAT_RSSI,
		SUM(4G_3G_HO_ATT) AS 4G_3G_HO_ATTEMPT,
		SUM(4G_3G_HO_FAIL) AS 4G_3G_HO_FAILURE,
		SUM(4G_2G_HO_ATT) AS 4G_2G_HO_ATTEMPT,
		SUM(4G_2G_HO_FAIL) AS 4G_2G_HO_FAILURE,
		SUM(BLIND_REDIR_4G_3G) AS BLIND_REDIR_4G_3G,
		SUM(BLIND_REDIR_4G_2G) AS BLIND_REDIR_4G_2G,
		SUM(4G_3G_CSFB_HO_ATT) AS 4G_3G_CSFB_HO_ATT,
		SUM(4G_3G_CSFB_HO_SUCC) AS 4G_3G_CSFB_HO_SUCC,
		SUM(4G_3G_CSFB_HO_FAILURE) AS 4G_3G_CSFB_HO_FAILURE,
		SUM(VOLTE_ATTEMPT) AS VOLTE_ATTEMPT,
		SUM(VOLTE_SUCCESS) AS VOLTE_SUCCESS,
		SUM(VOLTE_FAILURE) AS VOLTE_FAILURE,
		SUM(PROCEDURE_TIME_SUM) AS PROCEDURE_TIME_SUM,
		SUM(PROCEDURE_TIME_CNT) AS PROCEDURE_TIME_CNT,
		SUM(ACCESSIBILITY_TIME_SUM) AS ACCESSIBILITY_TIME_SUM,
		SUM(ACCESSIBILITY_TIME_CNT) AS ACCESSIBILITY_TIME_CNT,
		SUM(IRAT_RSRP_CNT) AS IRAT_RSRP_CNT,	
		SUM(IRAT_RSRQ_CNT) AS IRAT_RSRQ_CNT,
		COUNT(TA) AS IRAT_TA_CNT,
		SUM(IRAT_RSCP_CNT) AS IRAT_RSCP_CNT,
		SUM(IRAT_ECN0_CNT) AS IRAT_ECN0_CNT,
		SUM(IRAT_RSSI_CNT) AS IRAT_RSSI_CNT,
		MAX(SUBSCRIBER) AS PEAK_SUBSCRIBER';
		
	DECLARE COLUMN_UPD_STR VARCHAR(13000) DEFAULT 
		'RPT_TABLE_NAME.RRC_CONN_SETUP_ATTEMPT=RPT_TABLE_NAME.RRC_CONN_SETUP_ATTEMPT+VALUES(RRC_CONN_SETUP_ATTEMPT),
		RPT_TABLE_NAME.RRC_CONN_SETUP_REJECT=RPT_TABLE_NAME.RRC_CONN_SETUP_REJECT+VALUES(RRC_CONN_SETUP_REJECT),
	    RPT_TABLE_NAME.RRC_CONN_SETUP_MISSING_COMPLETE=RPT_TABLE_NAME.RRC_CONN_SETUP_MISSING_COMPLETE+VALUES(RRC_CONN_SETUP_MISSING_COMPLETE),
		RPT_TABLE_NAME.ERAB_SETUP_ATTEMPT=RPT_TABLE_NAME.ERAB_SETUP_ATTEMPT+VALUES(ERAB_SETUP_ATTEMPT),
		RPT_TABLE_NAME.ERAB_SETUP_REJECT=RPT_TABLE_NAME.ERAB_SETUP_REJECT+VALUES(ERAB_SETUP_REJECT),
		RPT_TABLE_NAME.ERAB_SETUP_ACCS_DELAY=RPT_TABLE_NAME.ERAB_SETUP_ACCS_DELAY+VALUES(ERAB_SETUP_ACCS_DELAY),
		RPT_TABLE_NAME.UE_CNXT_DROP_SETUP=RPT_TABLE_NAME.UE_CNXT_DROP_SETUP+VALUES(UE_CNXT_DROP_SETUP),
		RPT_TABLE_NAME.UE_CNXT_DROP_DROP=RPT_TABLE_NAME.UE_CNXT_DROP_DROP+VALUES(UE_CNXT_DROP_DROP),
		RPT_TABLE_NAME.RRC_RE_ESTABLISHMENT_ATTEMPT=RPT_TABLE_NAME.RRC_RE_ESTABLISHMENT_ATTEMPT+VALUES(RRC_RE_ESTABLISHMENT_ATTEMPT),
		RPT_TABLE_NAME.RRC_RE_ESTABLISHMENT_FAILURE=RPT_TABLE_NAME.RRC_RE_ESTABLISHMENT_FAILURE+VALUES(RRC_RE_ESTABLISHMENT_FAILURE),
		RPT_TABLE_NAME.MIMO_USAGE_RATIO_NUM=RPT_TABLE_NAME.MIMO_USAGE_RATIO_NUM+VALUES(MIMO_USAGE_RATIO_NUM),
		RPT_TABLE_NAME.MIMO_USAGE_RATIO_DEN=RPT_TABLE_NAME.MIMO_USAGE_RATIO_DEN+VALUES(MIMO_USAGE_RATIO_DEN),
		RPT_TABLE_NAME.SUBSC_PET_CELL_PER_HR=RPT_TABLE_NAME.SUBSC_PET_CELL_PER_HR+VALUES(SUBSC_PET_CELL_PER_HR),
		RPT_TABLE_NAME.CALL_DURATION_SUM=RPT_TABLE_NAME.CALL_DURATION_SUM+VALUES(CALL_DURATION_SUM),
		RPT_TABLE_NAME.CALL_DURATION_CNT=RPT_TABLE_NAME.CALL_DURATION_CNT+VALUES(CALL_DURATION_CNT),
		RPT_TABLE_NAME.COVMO_DATA_AVAILABILITY=VALUES(COVMO_DATA_AVAILABILITY),
		RPT_TABLE_NAME.4G_4G_HO_ATTEMPT=RPT_TABLE_NAME.4G_4G_HO_ATTEMPT+VALUES(4G_4G_HO_ATTEMPT),
		RPT_TABLE_NAME.4G_4G_HO_FAILURE=RPT_TABLE_NAME.4G_4G_HO_FAILURE+VALUES(4G_4G_HO_FAILURE),
		RPT_TABLE_NAME.RRC_RECONFIGURATION_ATTEMPT=RPT_TABLE_NAME.RRC_RECONFIGURATION_ATTEMPT+VALUES(RRC_RECONFIGURATION_ATTEMPT),
		RPT_TABLE_NAME.RRC_RECONFIGURATION_FAILURE=RPT_TABLE_NAME.RRC_RECONFIGURATION_FAILURE+VALUES(RRC_RECONFIGURATION_FAILURE),
		RPT_TABLE_NAME.CSFB_EXECUTIONS=RPT_TABLE_NAME.CSFB_EXECUTIONS+VALUES(CSFB_EXECUTIONS),
		RPT_TABLE_NAME.UE_CNXT_REL_TOT=RPT_TABLE_NAME.UE_CNXT_REL_TOT+VALUES(UE_CNXT_REL_TOT),
		RPT_TABLE_NAME.IRAT_PING_PONG=RPT_TABLE_NAME.IRAT_PING_PONG+VALUES(IRAT_PING_PONG),
		RPT_TABLE_NAME.IRAT_RSRP=RPT_TABLE_NAME.IRAT_RSRP+VALUES(IRAT_RSRP),
		RPT_TABLE_NAME.IRAT_RSRQ=RPT_TABLE_NAME.IRAT_RSRQ+VALUES(IRAT_RSRQ),
		RPT_TABLE_NAME.IRAT_TA=RPT_TABLE_NAME.IRAT_TA+VALUES(IRAT_TA),
		RPT_TABLE_NAME.IRAT_RSCP=RPT_TABLE_NAME.IRAT_RSCP+VALUES(IRAT_RSCP),
		RPT_TABLE_NAME.IRAT_ECN0=RPT_TABLE_NAME.IRAT_ECN0+VALUES(IRAT_ECN0),
		RPT_TABLE_NAME.IRAT_RSSI=RPT_TABLE_NAME.IRAT_RSSI+VALUES(IRAT_RSSI),
		RPT_TABLE_NAME.4G_3G_HO_ATTEMPT=RPT_TABLE_NAME.4G_3G_HO_ATTEMPT+VALUES(4G_3G_HO_ATTEMPT),
		RPT_TABLE_NAME.4G_3G_HO_FAILURE=RPT_TABLE_NAME.4G_3G_HO_FAILURE+VALUES(4G_3G_HO_FAILURE),
		RPT_TABLE_NAME.4G_2G_HO_ATTEMPT=RPT_TABLE_NAME.4G_2G_HO_ATTEMPT+VALUES(4G_2G_HO_ATTEMPT),
		RPT_TABLE_NAME.4G_2G_HO_FAILURE=RPT_TABLE_NAME.4G_2G_HO_FAILURE+VALUES(4G_2G_HO_FAILURE),
		RPT_TABLE_NAME.BLIND_REDIR_4G_3G=RPT_TABLE_NAME.BLIND_REDIR_4G_3G+VALUES(BLIND_REDIR_4G_3G),
		RPT_TABLE_NAME.BLIND_REDIR_4G_2G=RPT_TABLE_NAME.BLIND_REDIR_4G_2G+VALUES(BLIND_REDIR_4G_2G),
		RPT_TABLE_NAME.4G_3G_CSFB_HO_ATT=RPT_TABLE_NAME.4G_3G_CSFB_HO_ATT+VALUES(4G_3G_CSFB_HO_ATT),
		RPT_TABLE_NAME.4G_3G_CSFB_HO_SUCC=RPT_TABLE_NAME.4G_3G_CSFB_HO_SUCC+VALUES(4G_3G_CSFB_HO_SUCC),
		RPT_TABLE_NAME.4G_3G_CSFB_HO_FAILURE=RPT_TABLE_NAME.4G_3G_CSFB_HO_FAILURE+VALUES(4G_3G_CSFB_HO_FAILURE),
		RPT_TABLE_NAME.VOLTE_ATTEMPT=RPT_TABLE_NAME.VOLTE_ATTEMPT+VALUES(VOLTE_ATTEMPT),
		RPT_TABLE_NAME.VOLTE_SUCCESS=RPT_TABLE_NAME.VOLTE_SUCCESS+VALUES(VOLTE_SUCCESS),
		RPT_TABLE_NAME.VOLTE_FAILURE=RPT_TABLE_NAME.VOLTE_FAILURE+VALUES(VOLTE_FAILURE),
		RPT_TABLE_NAME.PROCEDURE_TIME_SUM=RPT_TABLE_NAME.PROCEDURE_TIME_SUM+VALUES(PROCEDURE_TIME_SUM),
		RPT_TABLE_NAME.PROCEDURE_TIME_CNT=RPT_TABLE_NAME.PROCEDURE_TIME_CNT+VALUES(PROCEDURE_TIME_CNT),
		RPT_TABLE_NAME.ACCESSIBILITY_TIME_SUM=RPT_TABLE_NAME.ACCESSIBILITY_TIME_SUM+VALUES(ACCESSIBILITY_TIME_SUM),
		RPT_TABLE_NAME.ACCESSIBILITY_TIME_CNT=RPT_TABLE_NAME.ACCESSIBILITY_TIME_CNT+VALUES(ACCESSIBILITY_TIME_CNT),
		RPT_TABLE_NAME.IRAT_RSRP_CNT=RPT_TABLE_NAME.IRAT_RSRP_CNT+VALUES(IRAT_RSRP_CNT),
		RPT_TABLE_NAME.IRAT_RSRQ_CNT=RPT_TABLE_NAME.IRAT_RSRQ_CNT+VALUES(IRAT_RSRQ_CNT),
		RPT_TABLE_NAME.IRAT_TA_CNT=RPT_TABLE_NAME.IRAT_TA_CNT+VALUES(IRAT_TA_CNT),
		RPT_TABLE_NAME.IRAT_RSCP_CNT=RPT_TABLE_NAME.IRAT_RSCP_CNT+VALUES(IRAT_RSCP_CNT),
		RPT_TABLE_NAME.IRAT_ECN0_CNT=RPT_TABLE_NAME.IRAT_ECN0_CNT+VALUES(IRAT_ECN0_CNT),
		RPT_TABLE_NAME.IRAT_RSSI_CNT=RPT_TABLE_NAME.IRAT_RSSI_CNT+VALUES(IRAT_RSSI_CNT),
		RPT_TABLE_NAME.PEAK_QUARTER = IF(VALUES(PEAK_SUBSCRIBER) > RPT_TABLE_NAME.PEAK_SUBSCRIBER,VALUES(PEAK_QUARTER) ,RPT_TABLE_NAME.PEAK_QUARTER),
		RPT_TABLE_NAME.PEAK_SUBSCRIBER = IF(VALUES(PEAK_SUBSCRIBER) > RPT_TABLE_NAME.PEAK_SUBSCRIBER, VALUES(PEAK_SUBSCRIBER), RPT_TABLE_NAME.PEAK_SUBSCRIBER),
		RPT_TABLE_NAME.VOLTE_DROP=RPT_TABLE_NAME.VOLTE_DROP+VALUES(VOLTE_DROP),
		RPT_TABLE_NAME.VOLTE_END=RPT_TABLE_NAME.VOLTE_END+VALUES(VOLTE_END),
		RPT_TABLE_NAME.DL_VOLUME_SUM=RPT_TABLE_NAME.DL_VOLUME_SUM+VALUES(DL_VOLUME_SUM),
		RPT_TABLE_NAME.UL_VOLUME_SUM=RPT_TABLE_NAME.UL_VOLUME_SUM+VALUES(UL_VOLUME_SUM),
		RPT_TABLE_NAME.DL_THROUGHPUT_SUM=RPT_TABLE_NAME.DL_THROUGHPUT_SUM+VALUES(DL_THROUGHPUT_SUM),
		RPT_TABLE_NAME.DL_THROUGHPUT_CNT=RPT_TABLE_NAME.DL_THROUGHPUT_CNT+VALUES(DL_THROUGHPUT_CNT),
		RPT_TABLE_NAME.UL_THROUGHPUT_SUM=RPT_TABLE_NAME.UL_THROUGHPUT_SUM+VALUES(UL_THROUGHPUT_SUM),
		RPT_TABLE_NAME.UL_THROUGHPUT_CNT=RPT_TABLE_NAME.UL_THROUGHPUT_CNT+VALUES(UL_THROUGHPUT_CNT),
		RPT_TABLE_NAME.DL_THROUGHPUT_MAX = IF(VALUES(DL_THROUGHPUT_MAX) > RPT_TABLE_NAME.DL_THROUGHPUT_MAX,VALUES(DL_THROUGHPUT_MAX) ,RPT_TABLE_NAME.DL_THROUGHPUT_MAX),
		RPT_TABLE_NAME.UL_THROUGHPUT_MAX = IF(VALUES(UL_THROUGHPUT_MAX) > RPT_TABLE_NAME.UL_THROUGHPUT_MAX,VALUES(UL_THROUGHPUT_MAX) ,RPT_TABLE_NAME.UL_THROUGHPUT_MAX),
		RPT_TABLE_NAME.DL_TRAFFIC_DUR=RPT_TABLE_NAME.DL_TRAFFIC_DUR+VALUES(DL_TRAFFIC_DUR),
		RPT_TABLE_NAME.UL_TRAFFIC_DUR=RPT_TABLE_NAME.UL_TRAFFIC_DUR+VALUES(UL_TRAFFIC_DUR)';
		
	DECLARE NT_DB VARCHAR(100);
	DECLARE v_DATA_DATE VARCHAR(30);
	DECLARE WeekStart CHAR(20);
	DECLARE WeekEnd CHAR(20);
	DECLARE	WEEK_DB VARCHAR(50);
	SET PU_ID = gt_strtok(GT_DB,2,'_');
	SET v_DATA_DATE = STR_TO_DATE(gt_strtok(GT_DB,3,'_'),'%Y%m%d');
	SET WeekStart = FIRST_DAY_OF_WEEK(v_DATA_DATE);
	SET WeekEnd = LAST_DAY_OF_WEEK(v_DATA_DATE);
	SET WEEK_DB=CONCAT('gt_',PU_ID,'_',DATE_FORMAT(WeekStart,'%Y%m%d'),'_',DATE_FORMAT(WeekEnd,'%Y%m%d'));
	SET @TEMP_TABLE=CONCAT(GT_DB,'.tmp_',RPT_TBL_NAME);
	
	INSERT INTO gt_gw_main.SP_LOG VALUES(TMP_GT_DB,'SP_Sub_Gen_CELL_LTE_PARALLEL_AWK','START', START_TIME);
	IF FLAG='HOUR' THEN 
		BEGIN
			SET @rpt_target_table=CONCAT(GT_DB,'.',RPT_TBL_NAME,'_',DATA_HR);
			SET @rpt_target_def_table=CONCAT(GT_DB,'.',RPT_TBL_NAME,'_def','_',DATA_HR);
			SET KEY_COLUMN_STR='`CELL_ID`,`ENODEB_ID`,`PU_ID`,`CELL_NAME`,`SUB_REGION_ID`,`EUTRABAND`,`EARFCN`,`CELL_OSS_NODE_ID`,';
			SET NT_DB =CONCAT('gt_nt_',gt_strtok(GT_DB,3,'_'));
			
			SET @SqlCmd=CONCAT('DROP TABLE IF EXISTS ',@TEMP_TABLE, ';');
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;
			
			SET @SqlCmd=CONCAT('CREATE TABLE ',@TEMP_TABLE, ' LIKE ',CONCAT(GT_DB,'.',RPT_TBL_NAME,'_',DATA_HR));
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;
			
			SET @SqlCmd=CONCAT('INSERT INTO ',@TEMP_TABLE,'( 
					DATA_DATE, 
					DATA_HOUR,
					ENODEB_ID,
					CELL_ID,
					CELL_NAME,
					PU_ID, 
					EUTRABAND,
					EARFCN,
					RRC_CONN_SETUP_ATTEMPT,
					RRC_CONN_SETUP_REJECT,
					RRC_CONN_SETUP_MISSING_COMPLETE,
					ERAB_SETUP_ATTEMPT,
					ERAB_SETUP_REJECT,
					ERAB_SETUP_ACCS_DELAY,
					UE_CNXT_DROP_SETUP,
					UE_CNXT_DROP_DROP,
					RRC_RE_ESTABLISHMENT_ATTEMPT,
					RRC_RE_ESTABLISHMENT_FAILURE,
					MIMO_USAGE_RATIO_NUM,
					MIMO_USAGE_RATIO_DEN,
					SUBSC_PET_CELL_PER_HR,
					CALL_DURATION_SUM,
					CALL_DURATION_CNT,
					4G_4G_HO_ATTEMPT,
					4G_4G_HO_FAILURE,
					RRC_RECONFIGURATION_ATTEMPT,
					RRC_RECONFIGURATION_FAILURE,
					CSFB_EXECUTIONS,
					UE_CNXT_REL_TOT,
					IRAT_PING_PONG,
					IRAT_RSRP,
					IRAT_RSRQ,
					IRAT_TA,
					IRAT_RSCP,
					IRAT_ECN0,
					IRAT_RSSI,
					4G_3G_HO_ATTEMPT,	
					4G_3G_HO_FAILURE,
					4G_2G_HO_ATTEMPT,
					4G_2G_HO_FAILURE,
					BLIND_REDIR_4G_3G,
					BLIND_REDIR_4G_2G,
					4G_3G_CSFB_HO_ATT,
					4G_3G_CSFB_HO_SUCC,
					4G_3G_CSFB_HO_FAILURE,
					VOLTE_ATTEMPT,
					VOLTE_SUCCESS,
					VOLTE_FAILURE,
					PROCEDURE_TIME_SUM,
					PROCEDURE_TIME_CNT,
					ACCESSIBILITY_TIME_SUM,
					ACCESSIBILITY_TIME_CNT,
					IRAT_RSRP_CNT,
					IRAT_RSRQ_CNT,
					IRAT_TA_CNT,
					IRAT_RSCP_CNT,
					IRAT_ECN0_CNT,
					IRAT_RSSI_CNT,
					PEAK_SUBSCRIBER,
					PEAK_QUARTER,
					VOLTE_DROP,
					VOLTE_END)	
				SELECT
					DATA_DATE, 
					DATA_HOUR,
					ENODEB_ID,
					CELL_ID,
					CELL_NAME,
					PU_ID, 
					EUTRABAND,
					EARFCN,
					SUM(RRC_CONN_SETUP_ATTEMPT) AS RRC_CONN_SETUP_ATTEMPT,
					SUM(RRC_CONN_SETUP_REJECT) AS RRC_CONN_SETUP_REJECT,
					SUM(RRC_CONN_SETUP_MISSING_COMPLETE) AS RRC_CONN_SETUP_MISSING_COMPLETE,
					SUM(ERAB_SETUP_ATTEMPT) AS ERAB_SETUP_ATTEMPT,
					SUM(ERAB_SETUP_REJECT) AS ERAB_SETUP_REJECT,
					SUM(ERAB_SETUP_ACCS_DELAY) AS ERAB_SETUP_ACCS_DELAY,
					SUM(UE_CNXT_DROP_SETUP) AS UE_CNXT_DROP_SETUP,
					SUM(UE_CNXT_DROP_DROP) AS UE_CNXT_DROP_DROP,
					SUM(RRC_RE_ESTABLISHMENT_ATTEMPT) AS RRC_RE_ESTABLISHMENT_ATTEMPT,
					SUM(RRC_RE_ESTABLISHMENT_FAILURE) AS RRC_RE_ESTABLISHMENT_FAILURE,
					SUM(MIMO_USAGE_RATIO_NUM) AS MIMO_USAGE_RATIO_NUM,
					SUM(MIMO_USAGE_RATIO_DEN) AS MIMO_USAGE_RATIO_DEN,
					SUM(SUBSC_PET_CELL_PER_HR) AS SUBSC_PET_CELL_PER_HR,
					SUM(CALL_DURATION_SUM) AS CALL_DURATION_SUM,
					SUM(CALL_DURATION_CNT) AS CALL_DURATION_CNT,
					SUM(4G_4G_HO_ATTEMPT) AS 4G_4G_HO_ATTEMPT,
					SUM(4G_4G_HO_FAILURE) AS 4G_4G_HO_FAILURE,
					SUM(RRC_RECONFIGURATION_ATTEMPT) AS RRC_RECONFIGURATION_ATTEMPT,
					SUM(RRC_RECONFIGURATION_FAILURE) AS RRC_RECONFIGURATION_FAILURE,
					SUM(CSFB_EXECUTIONS) AS CSFB_EXECUTIONS,
					SUM(UE_CNXT_REL_TOT) AS UE_CNXT_REL_TOT,
					SUM(IRAT_PING_PONG) AS IRAT_PING_PONG,
					SUM(IRAT_RSRP) AS IRAT_RSRP,
					SUM(IRAT_RSRQ) AS IRAT_RSRQ,
					SUM(IRAT_TA) AS IRAT_TA,
					SUM(IRAT_RSCP) AS IRAT_RSCP,
					SUM(IRAT_ECN0) AS IRAT_ECN0,
					SUM(IRAT_RSSI) AS IRAT_RSSI,
					SUM(4G_3G_HO_ATTEMPT) AS 4G_3G_HO_ATTEMPT,	
					SUM(4G_3G_HO_FAILURE) AS 4G_3G_HO_FAILURE,
					SUM(4G_2G_HO_ATTEMPT) AS 4G_2G_HO_ATTEMPT,
					SUM(4G_2G_HO_FAILURE) AS 4G_2G_HO_FAILURE,
					SUM(BLIND_REDIR_4G_3G) AS BLIND_REDIR_4G_3G,
					SUM(BLIND_REDIR_4G_2G) AS BLIND_REDIR_4G_2G,
					SUM(4G_3G_CSFB_HO_ATT) AS 4G_3G_CSFB_HO_ATT,
					SUM(4G_3G_CSFB_HO_SUCC) AS 4G_3G_CSFB_HO_SUCC,
					SUM(4G_3G_CSFB_HO_FAILURE) AS 4G_3G_CSFB_HO_FAILURE,
					SUM(VOLTE_ATTEMPT) AS VOLTE_ATTEMPT,
					SUM(VOLTE_SUCCESS) AS VOLTE_SUCCESS,
					SUM(VOLTE_FAILURE) AS VOLTE_FAILURE,
					SUM(PROCEDURE_TIME_SUM) AS PROCEDURE_TIME_SUM,
					SUM(PROCEDURE_TIME_CNT) AS PROCEDURE_TIME_CNT,
					SUM(ACCESSIBILITY_TIME_SUM) AS ACCESSIBILITY_TIME_SUM,
					SUM(ACCESSIBILITY_TIME_CNT) AS ACCESSIBILITY_TIME_CNT,
					SUM(IRAT_RSRP_CNT) AS IRAT_RSRP_CNT,
					SUM(IRAT_RSRQ_CNT) AS IRAT_RSRQ_CNT,
					SUM(IRAT_TA_CNT) AS IRAT_TA_CNT,
					SUM(IRAT_RSCP_CNT) AS IRAT_RSCP_CNT,
					SUM(IRAT_ECN0_CNT) AS IRAT_ECN0_CNT,
					SUM(IRAT_RSSI_CNT) AS IRAT_RSSI_CNT,
					SUM(PEAK_SUBSCRIBER) AS PEAK_SUBSCRIBER,
					MAX(PEAK_QUARTER),
					SUM(VOLTE_DROP) AS VOLTE_DROP,
					SUM(VOLTE_END) AS VOLTE_END
					FROM	
					(
						SELECT 
							`DATA_DATE`,
							`DATA_HOUR`,
							`ENODEB_ID`,
							`CELL_ID`,
							`CELL_NAME`,
							`PU_ID`,
							`EUTRABAND`,
							`EARFCN`,
							',COLUMN_SUM_STR,',
							''',DATA_QR1,''' AS PEAK_QUARTER,
							SUM(VOLTE_DROP) AS VOLTE_DROP,
							SUM(VOLTE_END) AS VOLTE_END
						FROM ',GT_DB,'.table_cell_lte_',DATA_QR1,' 
						WHERE  
							 ((RRC_CONN_REQ > 0) 
							  OR ( RRC_CONN_REQ =0 AND (RRC_CONN_REJ > 0 OR ERAB_SETUP_ATT > 0 OR ERAB_SETUP_SUCC > 0 OR ERAB_SETUP_SUCC > 0
							  OR INIT_CNXT_SETUP_ATT > 0 OR INIT_CNXT_SETUP_SUCC > 0 OR INIT_CNXT_SETUP_FAIL > 0
							  OR RRC_CONN_REEST_FAIL > 0 OR 4G_4G_HO_S1_ATT > 0 OR 4G_4G_HO_S1_FAIL > 0
							  OR 4G_4G_HO_X2_ATT > 0 OR 4G_4G_HO_X2_FAIL > 0 OR RSCP_IRAT > 0
							  OR ECNO_IRAT > 0 OR RSSI_IRAT > 0 OR 4G_3G_HO_ATT > 0 OR 4G_3G_HO_FAIL > 0
							  OR 4G_2G_HO_ATT > 0 OR 4G_2G_HO_FAIL > 0 OR ERAB_SETUP_FAIL > 0) ))
						GROUP BY ENODEB_ID,CELL_ID,DATA_DATE,DATA_HOUR
						
						UNION
						
						SELECT 
							`DATA_DATE`,
							`DATA_HOUR`,
							`ENODEB_ID`,
							`CELL_ID`,
							`CELL_NAME`,
							`PU_ID`,
							`EUTRABAND`,
							`EARFCN`,
							',COLUMN_SUM_STR,',
							''',DATA_QR2,''' AS PEAK_QUARTER,
							SUM(VOLTE_DROP) AS VOLTE_DROP,
							SUM(VOLTE_END) AS VOLTE_END
						FROM ',GT_DB,'.table_cell_lte_',DATA_QR2,' 
						WHERE  
							 ((RRC_CONN_REQ > 0) 
							  OR ( RRC_CONN_REQ =0 AND (RRC_CONN_REJ > 0 OR ERAB_SETUP_ATT > 0 OR ERAB_SETUP_SUCC > 0 OR ERAB_SETUP_SUCC > 0
							  OR INIT_CNXT_SETUP_ATT > 0 OR INIT_CNXT_SETUP_SUCC > 0 OR INIT_CNXT_SETUP_FAIL > 0
							  OR RRC_CONN_REEST_FAIL > 0 OR 4G_4G_HO_S1_ATT > 0 OR 4G_4G_HO_S1_FAIL > 0
							  OR 4G_4G_HO_X2_ATT > 0 OR 4G_4G_HO_X2_FAIL > 0 OR RSCP_IRAT > 0
							  OR ECNO_IRAT > 0 OR RSSI_IRAT > 0 OR 4G_3G_HO_ATT > 0 OR 4G_3G_HO_FAIL > 0
							  OR 4G_2G_HO_ATT > 0 OR 4G_2G_HO_FAIL > 0 OR ERAB_SETUP_FAIL > 0) ))
						GROUP BY ENODEB_ID,CELL_ID,DATA_DATE,DATA_HOUR
						
						UNION
						
						SELECT 
							`DATA_DATE`,
							`DATA_HOUR`,
							`ENODEB_ID`,
							`CELL_ID`,
							`CELL_NAME`,
							`PU_ID`,
							`EUTRABAND`,
							`EARFCN`,
							',COLUMN_SUM_STR,',
							''',DATA_QR3,''' AS PEAK_QUARTER,
							SUM(VOLTE_DROP) AS VOLTE_DROP,
							SUM(VOLTE_END) AS VOLTE_END
						FROM ',GT_DB,'.table_cell_lte_',DATA_QR3,' 
						WHERE  
							 ((RRC_CONN_REQ > 0) 
							  OR ( RRC_CONN_REQ =0 AND (RRC_CONN_REJ > 0 OR ERAB_SETUP_ATT > 0 OR ERAB_SETUP_SUCC > 0 OR ERAB_SETUP_SUCC > 0
							  OR INIT_CNXT_SETUP_ATT > 0 OR INIT_CNXT_SETUP_SUCC > 0 OR INIT_CNXT_SETUP_FAIL > 0
							  OR RRC_CONN_REEST_FAIL > 0 OR 4G_4G_HO_S1_ATT > 0 OR 4G_4G_HO_S1_FAIL > 0
							  OR 4G_4G_HO_X2_ATT > 0 OR 4G_4G_HO_X2_FAIL > 0 OR RSCP_IRAT > 0
							  OR ECNO_IRAT > 0 OR RSSI_IRAT > 0 OR 4G_3G_HO_ATT > 0 OR 4G_3G_HO_FAIL > 0
							  OR 4G_2G_HO_ATT > 0 OR 4G_2G_HO_FAIL > 0 OR ERAB_SETUP_FAIL > 0) ))
						GROUP BY ENODEB_ID,CELL_ID,DATA_DATE,DATA_HOUR
						
						UNION
						
						SELECT 
							`DATA_DATE`,
							`DATA_HOUR`,
							`ENODEB_ID`,
							`CELL_ID`,
							`CELL_NAME`,
							`PU_ID`,
							`EUTRABAND`,
							`EARFCN`,
							',COLUMN_SUM_STR,',
							''',DATA_QR4,''' AS PEAK_QUARTER,
							SUM(VOLTE_DROP) AS VOLTE_DROP,
							SUM(VOLTE_END) AS VOLTE_END
						FROM ',GT_DB,'.table_cell_lte_',DATA_QR4,' 
						WHERE  
							 ((RRC_CONN_REQ > 0) 
							  OR ( RRC_CONN_REQ =0 AND (RRC_CONN_REJ > 0 OR ERAB_SETUP_ATT > 0 OR ERAB_SETUP_SUCC > 0 OR ERAB_SETUP_SUCC > 0
							  OR INIT_CNXT_SETUP_ATT > 0 OR INIT_CNXT_SETUP_SUCC > 0 OR INIT_CNXT_SETUP_FAIL > 0
							  OR RRC_CONN_REEST_FAIL > 0 OR 4G_4G_HO_S1_ATT > 0 OR 4G_4G_HO_S1_FAIL > 0
							  OR 4G_4G_HO_X2_ATT > 0 OR 4G_4G_HO_X2_FAIL > 0 OR RSCP_IRAT > 0
							  OR ECNO_IRAT > 0 OR RSSI_IRAT > 0 OR 4G_3G_HO_ATT > 0 OR 4G_3G_HO_FAIL > 0
							  OR 4G_2G_HO_ATT > 0 OR 4G_2G_HO_FAIL > 0 OR ERAB_SETUP_FAIL > 0) ))
						GROUP BY ENODEB_ID,CELL_ID,DATA_DATE,DATA_HOUR
					) t
					GROUP BY ENODEB_ID,CELL_ID,PU_ID,DATA_HOUR
					ORDER BY NULL;');
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt; 	
	
			SET @SqlCmd=CONCAT('UPDATE ',@TEMP_TABLE,' a,',NT_DB,'.nt_cell_current_lte b
				SET  
				a.SUB_REGION_ID = b.SUB_REGION_ID,
				a.CELL_OSS_NODE_ID = b.CELL_OSS_NODE_ID
				WHERE a.CELL_ID =b.CELL_ID
				AND a.ENODEB_ID =b.ENODEB_ID;');
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;	
			
			SET @SqlCmd=CONCAT('UPDATE ',@TEMP_TABLE,' a,',GT_DB,'.rpt_cell_position_def_',DATA_HR,' b
				SET  
				a.DL_VOLUME_SUM = b.DL_VOLUME_SUM,
				a.UL_VOLUME_SUM = b.UL_VOLUME_SUM,
				a.DL_THROUGHPUT_SUM = b.DL_THROUPUT_SUM,
				a.DL_THROUGHPUT_CNT = b.DL_THROUPUT_CNT,
				a.UL_THROUGHPUT_SUM = b.UL_THROUPUT_SUM,
				a.UL_THROUGHPUT_CNT = b.UL_THROUPUT_CNT,
				a.DL_THROUGHPUT_MAX = b.DL_THROUPUT_MAX,
				a.UL_THROUGHPUT_MAX = b.UL_THROUPUT_MAX,
				a.DL_TRAFFIC_DUR = b.DL_TRAFFIC_DUR,
				a.UL_TRAFFIC_DUR = b.UL_TRAFFIC_DUR
				
				WHERE a.CELL_ID =b.CELL_ID
				AND a.ENODEB_ID =b.ENODEB_ID;');
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;
			
			INSERT INTO gt_gw_main.SP_LOG VALUES(TMP_GT_DB,'SP_Sub_Gen_CELL_LTE_PARALLEL_AWK',CONCAT('INSERT ',@rpt_target_table,' HOUR START'), NOW());
			SET STEP_START_TIME := SYSDATE();
			SET @SqlCmd=CONCAT('INSERT INTO ',@rpt_target_table,' 
						(
							DATA_DATE, 
							DATA_HOUR,
							',KEY_COLUMN_STR,COLUMN_STR,'
						)
						SELECT	
							`DATA_DATE`,
							`DATA_HOUR`,
							',KEY_COLUMN_STR,COLUMN_IFNULL_STR,'
						FROM ',@TEMP_TABLE,' 
						ON DUPLICATE KEY UPDATE 
						',REPLACE(COLUMN_UPD_STR,'RPT_TABLE_NAME',CONCAT(@rpt_target_table)),'
						;');
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;
	
			
			INSERT INTO gt_gw_main.SP_LOG VALUES(TMP_GT_DB,'SP_Sub_Gen_CELL_LTE_PARALLEL_AWK',CONCAT('INSERT ',@rpt_target_table,' HOUR COST: ',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' seconds.'), NOW());
			SET STEP_START_TIME := SYSDATE();
			
			INSERT INTO gt_gw_main.SP_LOG VALUES(TMP_GT_DB,'SP_Sub_Gen_CELL_LTE_PARALLEL_AWK',CONCAT('INSERT ',@rpt_target_def_table,' HOUR COST: ',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' seconds.'), NOW());
			
			INSERT INTO gt_gw_main.SP_LOG VALUES(TMP_GT_DB,'SP_Sub_Gen_CELL_LTE_PARALLEL_AWK',CONCAT('HR Done: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());
		END;

	ELSEIF FLAG='DAILY' THEN		
		BEGIN
			SET @rpt_target_table=CONCAT(GT_DB,'.',RPT_TBL_NAME,'_dy');
			SET @rpt_target_def_table=CONCAT(GT_DB,'.',RPT_TBL_NAME,'_dy_def');
			SET KEY_COLUMN_STR='`CELL_ID`,`ENODEB_ID`,`PU_ID`,cell_name,`SUB_REGION_ID`,`EUTRABAND`,`EARFCN`,CELL_OSS_NODE_ID,';
						
			INSERT INTO gt_gw_main.SP_LOG VALUES(GT_DB,'SP_Sub_Gen_CELL_LTE_PARALLEL_AWK',CONCAT('INSERT ',@rpt_target_table,' Daily START'), NOW());
			SET STEP_START_TIME := SYSDATE();
			
			SET @SqlCmd=CONCAT('INSERT INTO ',@rpt_target_table,' 
						(
							DATA_DATE,
							',KEY_COLUMN_STR,COLUMN_STR,'
						)
						SELECT	
							`DATA_DATE`,
							',KEY_COLUMN_STR,COLUMN_IFNULL_STR,'
						FROM ',@TEMP_TABLE,' 
						ON DUPLICATE KEY UPDATE 
						',REPLACE(COLUMN_UPD_STR,'RPT_TABLE_NAME',CONCAT(@rpt_target_table)),'
						;');
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;
			INSERT INTO gt_gw_main.SP_LOG VALUES(GT_DB,'SP_Sub_Gen_CELL_LTE_PARALLEL_AWK',CONCAT('INSERT ',@rpt_target_table,' Daily COST: ',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' seconds.'), NOW());
			SET STEP_START_TIME := SYSDATE();
			
			INSERT INTO gt_gw_main.SP_LOG VALUES(TMP_GT_DB,'SP_Sub_Gen_CELL_LTE_PARALLEL_AWK',CONCAT('INSERT ',@rpt_target_def_table,' Daily COST: ',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' seconds.'), NOW());
			
			SET @SqlCmd=CONCAT('DROP TABLE IF EXISTS ',@TEMP_TABLE, ';');
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;
	
			INSERT INTO gt_gw_main.SP_LOG VALUES(TMP_GT_DB,'SP_Sub_Gen_CELL_LTE_PARALLEL_AWK',CONCAT('DY Done: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());
		END;
		
	ELSEIF FLAG='WEEK' THEN		
		BEGIN
			SET @TEMP_TABLE=CONCAT(WEEK_DB,'.tmp_',RPT_TBL_NAME);
			SET @rpt_target_table=CONCAT(WEEK_DB,'.',RPT_TBL_NAME,'_wk');
	
			SET KEY_COLUMN_STR='`CELL_ID`,`ENODEB_ID`,`PU_ID`,cell_name,`SUB_REGION_ID`,`EUTRABAND`,`EARFCN`,';
	
			SET @SqlCmd=CONCAT('DROP TABLE IF EXISTS ',@TEMP_TABLE, ';');
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;
			
			SET @SqlCmd=CONCAT('CREATE TABLE ',@TEMP_TABLE, ' LIKE ',CONCAT(GT_DB,'.rpt_cell_lte_dy'));
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;
			
			SET @SqlCmd=CONCAT('INSERT INTO ',@TEMP_TABLE,'( 
						DATA_DATE,
						',KEY_COLUMN_STR,COLUMN_STR,')	
					SELECT	
						FIRST_DAY_OF_WEEK(`DATA_DATE`),
						',KEY_COLUMN_STR,COLUMN_IFNULL_STR,'
					FROM ',GT_DB,'.rpt_cell_lte_dy;');
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt; 	
	
						
			INSERT INTO gt_gw_main.SP_LOG VALUES(GT_DB,'SP_Sub_Gen_CELL_LTE_PARALLEL_AWK',CONCAT('INSERT ',@rpt_target_table,' Daily START'), NOW());
			SET STEP_START_TIME := SYSDATE();
			
			SET @SqlCmd=CONCAT('INSERT INTO ',@rpt_target_table,' 
						(
							DATA_DATE,
							',KEY_COLUMN_STR,COLUMN_STR,'
						)
						SELECT	
							`DATA_DATE`,
							',KEY_COLUMN_STR,COLUMN_IFNULL_STR,'
						FROM ',@TEMP_TABLE,' 
						ON DUPLICATE KEY UPDATE 
						',REPLACE(COLUMN_UPD_STR,'RPT_TABLE_NAME',CONCAT(@rpt_target_table)),'
						;');
	
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;
	
			INSERT INTO gt_gw_main.SP_LOG VALUES(GT_DB,'SP_Sub_Gen_CELL_LTE_PARALLEL_AWK',CONCAT('INSERT ',@rpt_target_table,' Daily COST: ',TIMESTAMPDIFF(SECOND,STEP_START_TIME,SYSDATE()),' seconds.'), NOW());
			SET STEP_START_TIME := SYSDATE();
			
		
			SET @SqlCmd=CONCAT('DROP TABLE IF EXISTS ',@TEMP_TABLE, ';');
			PREPARE Stmt FROM @SqlCmd;
			EXECUTE Stmt;
			DEALLOCATE PREPARE Stmt;
			INSERT INTO gt_gw_main.SP_LOG VALUES(TMP_GT_DB,'SP_Sub_Gen_CELL_LTE_PARALLEL_AWK',CONCAT('DY Done: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());
		END;
	END IF;	
END$$
DELIMITER ;
