DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Sub_Generate_End_GSM`(IN GT_DB VARCHAR(100), IN KIND VARCHAR(20), IN VENDOR_SOURCE VARCHAR(20),IN GT_COVMO VARCHAR(100))
BEGIN
	DECLARE BSC_ID INT;
	DECLARE O_GT_DB VARCHAR(100) DEFAULT GT_DB;
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE PARTITION_ID INT DEFAULT SUBSTRING(RIGHT(GT_DB,18),10,2) ;
	DECLARE SH_EH VARCHAR(9) DEFAULT RIGHT(GT_DB,9);
	DECLARE GT_DATE VARCHAR(18) DEFAULT RIGHT(GT_DB,18);
	DECLARE STARTHOUR VARCHAR(2) DEFAULT SUBSTRING(RIGHT(GT_DB,18),10,2);
	DECLARE ENDHOUR VARCHAR(2) DEFAULT IF(SUBSTRING(RIGHT(GT_DB,18),15,2)='00','24',SUBSTRING(RIGHT(GT_DB,18),15,2));
	DECLARE RUN VARCHAR(20);
	DECLARE WORKER_ID VARCHAR(10) DEFAULT CONNECTION_ID();
	DECLARE CURRENT_NT_DB VARCHAR(50) DEFAULT CONCAT('gt_nt_',gt_strtok(GT_DB,3,'_'));
	SET SESSION group_concat_max_len = 100000;
	
	SET SESSION max_heap_table_size=4*1024*1024*1024;
	SET SESSION tmp_table_size=4*1024*1024*1024;
	SET SESSION sort_buffer_size = 1024*1024*1024; 
	SET SESSION read_buffer_size=1024*1024*1024;
	
	SELECT gt_strtok(GT_DB,2,'_') INTO BSC_ID;
	
	SELECT REPLACE(GT_DB,SH_EH,'0000_0000') INTO GT_DB;
	
	IF VENDOR_SOURCE = 'GW' THEN
		IF KIND = 'DAILY' THEN
			SET RUN = '_tmp';
		ELSEIF KIND = 'RERUN' THEN
			SET RUN = '_rerun';
		END IF;
	ELSEIF VENDOR_SOURCE = 'AP' THEN
		SET RUN = '';
	END IF;
	
	SET @SqlCmd=CONCAT('SELECT att_value INTO @SYS_CONFIG_TILE FROM ',CURRENT_NT_DB,'.`sys_config` WHERE `group_name`=''system'' AND att_name = ''MapResolution'';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
		
	IF gt_covmo_csv_count(@SYS_CONFIG_TILE,',') =3 THEN
		
		SET @SqlCmd=CONCAT('SELECT gt_covmo_csv_get(att_value,3) INTO @ZOOM_LEVEL FROM ',CURRENT_NT_DB,'.`sys_config` WHERE `group_name`=''system'' AND att_name = ''MapResolution'';');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
	ELSE 
		SET @SqlCmd=CONCAT('SELECT att_value INTO @ZOOM_LEVEL FROM ',CURRENT_NT_DB,'.`sys_config` WHERE `group_name`=''system'' AND att_name = ''MapResolution'';');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;
	END IF;
	
	SET @SqlCmd=CONCAT('ALTER TABLE ',GT_DB,RUN,'.table_tile_end_gsm TRUNCATE PARTITION h',PARTITION_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('ALTER TABLE ',GT_DB,RUN,'.table_tile_end_gsm_t TRUNCATE PARTITION h',PARTITION_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('ALTER TABLE ',GT_DB,RUN,'.table_tile_end_gsm_c TRUNCATE PARTITION h',PARTITION_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('ALTER TABLE ',GT_DB,RUN,'.table_tile_end_gsm_t_def TRUNCATE PARTITION h',PARTITION_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('ALTER TABLE ',GT_DB,RUN,'.table_tile_end_gsm_c_def TRUNCATE PARTITION h',PARTITION_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_End_GSM','Create temp table tmp_table_tile_end_gsm ', NOW());
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE  IF EXISTS ',GT_DB,RUN,'.tmp_table_tile_end_gsm_',WORKER_ID,';');
	PREPARE stmt FROM @sqlcmd;
	EXECUTE stmt;
	DEALLOCATE PREPARE stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,RUN,'.tmp_table_tile_end_gsm_',WORKER_ID,' 
			SELECT * FROM ',GT_DB,RUN,'.table_tile_end_gsm WHERE 1<>1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_End_GSM','Insert into tmp_table_tile_end_gsm ', NOW());
	
	SET @SqlCmd=CONCAT('INSERT INTO  ',GT_DB,RUN,'.tmp_table_tile_end_gsm_',WORKER_ID,'
				(
				DATA_DATE,
				DATA_HOUR,
				INDOOR,
				MOVING,
				TILE_ID,
				BSC_ID,
				CELL_ID,
				CALL_TYPE,
				CALL_STATUS,
				BANDINDEX,
				CELL_INDOOR,
				CLUSTER_ID,
				LAC,
				SITE_ID,
				CELL_LON,
				CELL_LAT,
				BCCH_ARFCN,
				CELL_NAME,
				CALL_CNT,
				RXLEV_FULL_DOWNLINK_CNT,
				RXLEV_FULL_DOWNLINK_SUM,
				RXQUAL_FULL_DOWNLINK_CNT,
				RXQUAL_FULL_DOWNLINK_SUM,
				RXLEV_FULL_UPLINK_SUM,
				RXQUAL_FULL_UPLINK_SUM,
				RXLEV_FULL_UPLINK_CNT,
				RXQUAL_FULL_UPLINK_CNT,
				RXLEV_FULL_UPLINK_MED_AVG,
				RXQUAL_FULL_UPLINK_MED_AVG,
				BSSMAP_11,
				BSSMAP_12,
				BSSMAP_13,
				BSSMAP_14,
				BSSMAP_15,
				BSSMAP_16,
				BSSMAP_17,
				BSSMAP_18,
				RSL_21,
				RSL_22,
				RSL_23,
				RR_31,
				RR_32,
				RR_33,
				RR_34,
				RR_35,
				RR_36
				)
			SELECT
				DATA_DATE
				,DATA_HOUR
				,INDOOR
				,MOVING
				,gt_covmo_proj_geohash_to_hex_geohash(POS_LAST_LOC, ',@ZOOM_LEVEL,') AS TILE_ID
				,POS_LAST_BSC
				,POS_LAST_CELL
				,CALL_TYPE
				,CALL_STATUS
				,POS_LAST_BANDINDEX
				,POS_LAST_CELL_INDOOR
				,NULL AS CLUSTER_ID
				,POS_LAST_LAC
				,POS_LAST_SITE
				,NULL AS CELL_LON
				,NULL AS CELL_LAT
				,POS_LAST_BCCH_ARFCN
				,NULL AS CELL_NAME
				,COUNT(*) AS CALL_CNT
				,COUNT(POS_LAST_RXLEV_FULL_DOWNLINK) AS RXLEV_FULL_DOWNLINK_CNT
				,SUM(POS_LAST_RXLEV_FULL_DOWNLINK) AS RXLEV_FULL_DOWNLINK_SUM
				,COUNT(POS_LAST_RXQUAL_FULL_DOWNLINK) AS RXQUAL_FULL_DOWNLINK_CNT
				,SUM(POS_LAST_RXQUAL_FULL_DOWNLINK) AS RXQUAL_FULL_DOWNLINK_SUM
				,SUM(POS_LAST_RXLEV_FULL_UPLINK) AS RXLEV_FULL_UPLINK_SUM
				,SUM(POS_LAST_RXQUAL_FULL_UPLINK) AS RXQUAL_FULL_UPLINK_SUM
				,COUNT(POS_LAST_RXLEV_FULL_UPLINK) AS RXLEV_FULL_UPLINK_CNT
				,COUNT(POS_LAST_RXQUAL_FULL_UPLINK) AS RXQUAL_FULL_UPLINK_CNT
				,AVG(POS_LAST_RXLEV_FULL_UPLINK) AS RXLEV_FULL_UPLINK_MED_AVG
				,AVG(POS_LAST_RXQUAL_FULL_UPLINK) AS RXQUAL_FULL_UPLINK_MED_AVG
				,SUM(IF(BSSMAP_FAILURE_CAUSE_LAST=11,1,0)) AS BSSMAP_11
				,SUM(IF(BSSMAP_FAILURE_CAUSE_LAST=12,1,0)) AS BSSMAP_12
				,SUM(IF(BSSMAP_FAILURE_CAUSE_LAST=13,1,0)) AS BSSMAP_13
				,SUM(IF(BSSMAP_FAILURE_CAUSE_LAST=14,1,0)) AS BSSMAP_14
				,SUM(IF(BSSMAP_FAILURE_CAUSE_LAST=15,1,0)) AS BSSMAP_15
				,SUM(IF(BSSMAP_FAILURE_CAUSE_LAST=16,1,0)) AS BSSMAP_16
				,SUM(IF(BSSMAP_FAILURE_CAUSE_LAST=17,1,0)) AS BSSMAP_17
				,SUM(IF(BSSMAP_FAILURE_CAUSE_LAST=18,1,0)) AS BSSMAP_18
				,SUM(IF(RSL_FAILURE_CAUSE_LAST=21,1,0)) AS RSL_21
				,SUM(IF(RSL_FAILURE_CAUSE_LAST=22,1,0)) AS RSL_22
				,SUM(IF(RSL_FAILURE_CAUSE_LAST=23,1,0)) AS RSL_23
				,SUM(IF(RR_DTAP_FAILURE_CAUSE_LAST=31,1,0)) AS RR_31
				,SUM(IF(RR_DTAP_FAILURE_CAUSE_LAST=32,1,0)) AS RR_32
				,SUM(IF(RR_DTAP_FAILURE_CAUSE_LAST=33,1,0)) AS RR_33
				,SUM(IF(RR_DTAP_FAILURE_CAUSE_LAST=34,1,0)) AS RR_34
				,SUM(IF(RR_DTAP_FAILURE_CAUSE_LAST=35,1,0)) AS RR_35
				,SUM(IF(RR_DTAP_FAILURE_CAUSE_LAST=36,1,0)) AS RR_36
			FROM ',GT_DB,RUN,'.table_call_gsm
			WHERE POS_LAST_BSC =',BSC_ID,'
			#AND POS_LAST_RXLEV_FULL_DOWNLINK IS NOT NULL
			AND DATA_HOUR >= ',STARTHOUR,' AND DATA_HOUR < ',ENDHOUR,'
			GROUP BY  
				DATA_DATE
				,DATA_HOUR
				,CALL_TYPE
				,CALL_STATUS
				,MOVING
				,INDOOR
				,POS_LAST_BSC
				,POS_LAST_CELL
				,gt_covmo_proj_geohash_to_hex_geohash(POS_LAST_LOC, ',@ZOOM_LEVEL,')
			ORDER BY NULL');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_End_GSM','Update CELL_LON, CELL_LAT, CELL_NAME in table_tile_end_gsm ', NOW());
	SET @SqlCmd=CONCAT('CREATE INDEX IX_KEY ON ',GT_DB,RUN,'.tmp_table_tile_end_gsm_',WORKER_ID,' (BSC_ID,CELL_ID);');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE  IF EXISTS ',GT_DB,RUN,'.tmp_nt_',WORKER_ID,';');
	PREPARE stmt FROM @sqlcmd;
	EXECUTE stmt;
	DEALLOCATE PREPARE stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,RUN,'.tmp_nt_',WORKER_ID,' 
			SELECT BSC_ID,CELL_ID,CLUSTER_ID,CELL_NAME,LATITUDE,LONGITUDE FROM ',CURRENT_NT_DB,'.nt_cell_current_gsm;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('CREATE INDEX IX_KEY ON ',GT_DB,RUN,'.tmp_nt_',WORKER_ID,'  (BSC_ID,CELL_ID);');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_End_GSM','Update CELL_LON, CELL_LAT, CELL_NAME in table_tile_end_gsm ', NOW());
	SET @SqlCmd=CONCAT(' UPDATE ',GT_DB,RUN,'.tmp_table_tile_end_gsm_',WORKER_ID,' A, 
				    ',GT_DB,RUN,'.tmp_nt_',WORKER_ID,'  B
			     SET A.CELL_LON=B.LONGITUDE
				,A.CELL_LAT=B.LATITUDE
				,A.CELL_NAME=B.CELL_NAME
				,A.CLUSTER_ID=B.CLUSTER_ID
				WHERE A.BSC_ID=B.BSC_ID
				AND A.CELL_ID=B.CELL_ID;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
		
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_End_GSM','Insert into table_tile_end_gsm ', NOW());
	
	SET @SqlCmd=CONCAT('INSERT INTO  ',GT_DB,RUN,'.table_tile_end_gsm
				(
				DATA_DATE,
				DATA_HOUR,
				INDOOR,
				MOVING,
				TILE_ID,
				BSC_ID,
				CELL_ID,
				CALL_TYPE,
				CALL_STATUS,
				BANDINDEX,
				CELL_INDOOR,
				CLUSTER_ID,
				LAC,
				SITE_ID,
				CELL_LON,
				CELL_LAT,
				BCCH_ARFCN,
				CELL_NAME,
				CALL_CNT,
				RXLEV_FULL_DOWNLINK_CNT,
				RXLEV_FULL_DOWNLINK_SUM,
				RXQUAL_FULL_DOWNLINK_CNT,
				RXQUAL_FULL_DOWNLINK_SUM,
				RXLEV_FULL_UPLINK_SUM,
				RXQUAL_FULL_UPLINK_SUM,
				RXLEV_FULL_UPLINK_CNT,
				RXQUAL_FULL_UPLINK_CNT,
				RXLEV_FULL_UPLINK_MED_AVG,
				RXQUAL_FULL_UPLINK_MED_AVG,
				BSSMAP_11,
				BSSMAP_12,
				BSSMAP_13,
				BSSMAP_14,
				BSSMAP_15,
				BSSMAP_16,
				BSSMAP_17,
				BSSMAP_18,
				RSL_21,
				RSL_22,
				RSL_23,
				RR_31,
				RR_32,
				RR_33,
				RR_34,
				RR_35,
				RR_36
				)
			SELECT 
				DATA_DATE,
				DATA_HOUR,
				INDOOR,
				MOVING,
				TILE_ID,
				BSC_ID,
				CELL_ID,
				CALL_TYPE,
				CALL_STATUS,
				BANDINDEX,
				CELL_INDOOR,
				CLUSTER_ID,
				LAC,
				SITE_ID,
				CELL_LON,
				CELL_LAT,
				BCCH_ARFCN,
				CELL_NAME,
				CALL_CNT,
				RXLEV_FULL_DOWNLINK_CNT,
				RXLEV_FULL_DOWNLINK_SUM,
				RXQUAL_FULL_DOWNLINK_CNT,
				RXQUAL_FULL_DOWNLINK_SUM,
				RXLEV_FULL_UPLINK_SUM,
				RXQUAL_FULL_UPLINK_SUM,
				RXLEV_FULL_UPLINK_CNT,
				RXQUAL_FULL_UPLINK_CNT,
				RXLEV_FULL_UPLINK_MED_AVG,
				RXQUAL_FULL_UPLINK_MED_AVG,
				BSSMAP_11,
				BSSMAP_12,
				BSSMAP_13,
				BSSMAP_14,
				BSSMAP_15,
				BSSMAP_16,
				BSSMAP_17,
				BSSMAP_18,
				RSL_21,
				RSL_22,
				RSL_23,
				RR_31,
				RR_32,
				RR_33,
				RR_34,
				RR_35,
				RR_36
			FROM ',GT_DB,RUN,'.tmp_table_tile_end_gsm_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_End_GSM','Insert into table_tile_end_gsm_t ', NOW());
	SET @SqlCmd=CONCAT('INSERT INTO  ',GT_DB,RUN,'.table_tile_end_gsm_t
				(
				DATA_DATE,
				DATA_HOUR,
				INDOOR,
				MOVING,
				TILE_ID,
				CALL_TYPE,
				CALL_STATUS,
				CALL_CNT,
				RXLEV_FULL_DOWNLINK_CNT,
				RXLEV_FULL_DOWNLINK_SUM,
				RXQUAL_FULL_DOWNLINK_CNT,
				RXQUAL_FULL_DOWNLINK_SUM,
				RXLEV_FULL_UPLINK_SUM,
				RXQUAL_FULL_UPLINK_SUM,
				RXLEV_FULL_UPLINK_CNT,
				RXQUAL_FULL_UPLINK_CNT,
				RXLEV_FULL_UPLINK_MED_AVG,
				RXQUAL_FULL_UPLINK_MED_AVG,
				BSSMAP_11,
				BSSMAP_12,
				BSSMAP_13,
				BSSMAP_14,
				BSSMAP_15,
				BSSMAP_16,
				BSSMAP_17,
				BSSMAP_18,
				RSL_21,
				RSL_22,
				RSL_23,
				RR_31,
				RR_32,
				RR_33,
				RR_34,
				RR_35,
				RR_36
				)
			    SELECT
				DATA_DATE
				,DATA_HOUR
				,INDOOR
				,MOVING
				,TILE_ID
				,CALL_TYPE
				,CALL_STATUS
				,IFNULL(SUM(CALL_CNT),0) AS CALL_CNT
				,IFNULL(SUM(RXLEV_FULL_DOWNLINK_CNT),0) AS RXLEV_FULL_DOWNLINK_CNT
				,IFNULL(SUM(RXLEV_FULL_DOWNLINK_SUM),0) AS RXLEV_FULL_DOWNLINK_SUM
				,IFNULL(SUM(RXQUAL_FULL_DOWNLINK_CNT),0) AS RXQUAL_FULL_DOWNLINK_CNT
				,IFNULL(SUM(RXQUAL_FULL_DOWNLINK_SUM),0) AS RXQUAL_FULL_DOWNLINK_SUM
				,IFNULL(SUM(RXLEV_FULL_UPLINK_SUM),0) AS RXLEV_FULL_UPLINK_SUM
				,IFNULL(SUM(RXQUAL_FULL_UPLINK_SUM),0) AS RXQUAL_FULL_UPLINK_SUM
				,IFNULL(SUM(RXLEV_FULL_UPLINK_CNT),0) AS RXLEV_FULL_UPLINK_CNT
				,IFNULL(SUM(RXQUAL_FULL_UPLINK_CNT),0) AS RXQUAL_FULL_UPLINK_CNT
				,IFNULL(AVG(RXLEV_FULL_UPLINK_MED_AVG),0) AS RXLEV_FULL_UPLINK_MED_AVG
				,IFNULL(AVG(RXQUAL_FULL_UPLINK_MED_AVG),0) AS RXQUAL_FULL_UPLINK_MED_AVG
				,IFNULL(SUM(BSSMAP_11),0) AS BSSMAP_11
				,IFNULL(SUM(BSSMAP_12),0) AS BSSMAP_12
				,IFNULL(SUM(BSSMAP_13),0) AS BSSMAP_13
				,IFNULL(SUM(BSSMAP_14),0) AS BSSMAP_14
				,IFNULL(SUM(BSSMAP_15),0) AS BSSMAP_15
				,IFNULL(SUM(BSSMAP_16),0) AS BSSMAP_16
				,IFNULL(SUM(BSSMAP_17),0) AS BSSMAP_17
				,IFNULL(SUM(BSSMAP_18),0) AS BSSMAP_18
				,IFNULL(SUM(RSL_21),0) AS RSL_21
				,IFNULL(SUM(RSL_22),0) AS RSL_22
				,IFNULL(SUM(RSL_23),0) AS RSL_23
				,IFNULL(SUM(RR_31),0) AS RR_31
				,IFNULL(SUM(RR_32),0) AS RR_32
				,IFNULL(SUM(RR_33),0) AS RR_33
				,IFNULL(SUM(RR_34),0) AS RR_34
				,IFNULL(SUM(RR_35),0) AS RR_35
				,IFNULL(SUM(RR_36),0) AS RR_36
			FROM ',GT_DB,RUN,'.tmp_table_tile_end_gsm_',WORKER_ID,'
			GROUP BY   
				DATA_DATE
				,DATA_HOUR
				,INDOOR
				,MOVING
				,TILE_ID
				,CALL_TYPE
				,CALL_STATUS
			ORDER BY NULL;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_End_GSM','Insert into table_tile_end_gsm_c ', NOW());
	SET @SqlCmd=CONCAT('INSERT INTO  ',GT_DB,RUN,'.table_tile_end_gsm_c
				(
				DATA_DATE,
				DATA_HOUR,
				INDOOR,
				MOVING,
				BSC_ID,
				CELL_ID,
				CALL_TYPE,
				CALL_STATUS,
				BANDINDEX,
				CELL_INDOOR,
				CLUSTER_ID,
				LAC,
				SITE_ID,
				CELL_LON,
				CELL_LAT,
				BCCH_ARFCN,
				CELL_NAME,
				CALL_CNT,
				RXLEV_FULL_DOWNLINK_CNT,
				RXLEV_FULL_DOWNLINK_SUM,
				RXQUAL_FULL_DOWNLINK_CNT,
				RXQUAL_FULL_DOWNLINK_SUM,
				RXLEV_FULL_UPLINK_SUM,
				RXQUAL_FULL_UPLINK_SUM,
				RXLEV_FULL_UPLINK_CNT,
				RXQUAL_FULL_UPLINK_CNT,
				RXLEV_FULL_UPLINK_MED_AVG,
				RXQUAL_FULL_UPLINK_MED_AVG,
				BSSMAP_11,
				BSSMAP_12,
				BSSMAP_13,
				BSSMAP_14,
				BSSMAP_15,
				BSSMAP_16,
				BSSMAP_17,
				BSSMAP_18,
				RSL_21,
				RSL_22,
				RSL_23,
				RR_31,
				RR_32,
				RR_33,
				RR_34,
				RR_35,
				RR_36
				)
			    SELECT
				DATA_DATE
				,DATA_HOUR
				,INDOOR
				,MOVING
				,BSC_ID
				,CELL_ID
				,CALL_TYPE
				,CALL_STATUS
				,BANDINDEX
				,CELL_INDOOR
				,CLUSTER_ID
				,LAC
				,SITE_ID
				,CELL_LON
				,CELL_LAT
				,BCCH_ARFCN
				,CELL_NAME
				,IFNULL(SUM(CALL_CNT),0) AS CALL_CNT
				,IFNULL(SUM(RXLEV_FULL_DOWNLINK_CNT),0) AS RXLEV_FULL_DOWNLINK_CNT
				,IFNULL(SUM(RXLEV_FULL_DOWNLINK_SUM),0) AS RXLEV_FULL_DOWNLINK_SUM
				,IFNULL(SUM(RXQUAL_FULL_DOWNLINK_CNT),0) AS RXQUAL_FULL_DOWNLINK_CNT
				,IFNULL(SUM(RXQUAL_FULL_DOWNLINK_SUM),0) AS RXQUAL_FULL_DOWNLINK_SUM
				,IFNULL(SUM(RXLEV_FULL_UPLINK_SUM),0) AS RXLEV_FULL_UPLINK_SUM
				,IFNULL(SUM(RXQUAL_FULL_UPLINK_SUM),0) AS RXQUAL_FULL_UPLINK_SUM
				,IFNULL(SUM(RXLEV_FULL_UPLINK_CNT),0) AS RXLEV_FULL_UPLINK_CNT
				,IFNULL(SUM(RXQUAL_FULL_UPLINK_CNT),0) AS RXQUAL_FULL_UPLINK_CNT
				,IFNULL(AVG(RXLEV_FULL_UPLINK_MED_AVG),0) AS RXLEV_FULL_UPLINK_MED_AVG
				,IFNULL(AVG(RXQUAL_FULL_UPLINK_MED_AVG),0) AS RXQUAL_FULL_UPLINK_MED_AVG
				,IFNULL(SUM(BSSMAP_11),0) AS BSSMAP_11
				,IFNULL(SUM(BSSMAP_12),0) AS BSSMAP_12
				,IFNULL(SUM(BSSMAP_13),0) AS BSSMAP_13
				,IFNULL(SUM(BSSMAP_14),0) AS BSSMAP_14
				,IFNULL(SUM(BSSMAP_15),0) AS BSSMAP_15
				,IFNULL(SUM(BSSMAP_16),0) AS BSSMAP_16
				,IFNULL(SUM(BSSMAP_17),0) AS BSSMAP_17
				,IFNULL(SUM(BSSMAP_18),0) AS BSSMAP_18
				,IFNULL(SUM(RSL_21),0) AS RSL_21
				,IFNULL(SUM(RSL_22),0) AS RSL_22
				,IFNULL(SUM(RSL_23),0) AS RSL_23
				,IFNULL(SUM(RR_31),0) AS RR_31
				,IFNULL(SUM(RR_32),0) AS RR_32
				,IFNULL(SUM(RR_33),0) AS RR_33
				,IFNULL(SUM(RR_34),0) AS RR_34
				,IFNULL(SUM(RR_35),0) AS RR_35
				,IFNULL(SUM(RR_36),0) AS RR_36
			FROM ',GT_DB,RUN,'.tmp_table_tile_end_gsm_',WORKER_ID,'
			GROUP BY   
				DATA_DATE
				,DATA_HOUR
				,INDOOR
				,MOVING
				,BSC_ID
				,CELL_ID
				,CALL_TYPE
				,CALL_STATUS
			ORDER BY NULL;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_End_GSM','Insert into table_tile_end_gsm_t_def ', NOW());
	SET @SqlCmd=CONCAT('INSERT INTO  ',GT_DB,RUN,'.table_tile_end_gsm_t_def
				(
				DATA_DATE,
				DATA_HOUR,
				TILE_ID,
				CALL_CNT,
				RXLEV_FULL_DOWNLINK_CNT,
				RXLEV_FULL_DOWNLINK_SUM,
				RXQUAL_FULL_DOWNLINK_CNT,
				RXQUAL_FULL_DOWNLINK_SUM,
				RXLEV_FULL_UPLINK_SUM,
				RXQUAL_FULL_UPLINK_SUM,
				RXLEV_FULL_UPLINK_CNT,
				RXQUAL_FULL_UPLINK_CNT,
				RXLEV_FULL_UPLINK_MED_AVG,
				RXQUAL_FULL_UPLINK_MED_AVG,
				BSSMAP_11,
				BSSMAP_12,
				BSSMAP_13,
				BSSMAP_14,
				BSSMAP_15,
				BSSMAP_16,
				BSSMAP_17,
				BSSMAP_18,
				RSL_21,
				RSL_22,
				RSL_23,
				RR_31,
				RR_32,
				RR_33,
				RR_34,
				RR_35,
				RR_36
				)
			    SELECT
				DATA_DATE
				,DATA_HOUR
				,TILE_ID
				,IFNULL(SUM(CALL_CNT),0) AS CALL_CNT
				,IFNULL(SUM(RXLEV_FULL_DOWNLINK_CNT),0) AS RXLEV_FULL_DOWNLINK_CNT
				,IFNULL(SUM(RXLEV_FULL_DOWNLINK_SUM),0) AS RXLEV_FULL_DOWNLINK_SUM
				,IFNULL(SUM(RXQUAL_FULL_DOWNLINK_CNT),0) AS RXQUAL_FULL_DOWNLINK_CNT
				,IFNULL(SUM(RXQUAL_FULL_DOWNLINK_SUM),0) AS RXQUAL_FULL_DOWNLINK_SUM
				,IFNULL(SUM(RXLEV_FULL_UPLINK_SUM),0) AS RXLEV_FULL_UPLINK_SUM
				,IFNULL(SUM(RXQUAL_FULL_UPLINK_SUM),0) AS RXQUAL_FULL_UPLINK_SUM
				,IFNULL(SUM(RXLEV_FULL_UPLINK_CNT),0) AS RXLEV_FULL_UPLINK_CNT
				,IFNULL(SUM(RXQUAL_FULL_UPLINK_CNT),0) AS RXQUAL_FULL_UPLINK_CNT
				,IFNULL(AVG(RXLEV_FULL_UPLINK_MED_AVG),0) AS RXLEV_FULL_UPLINK_MED_AVG
				,IFNULL(AVG(RXQUAL_FULL_UPLINK_MED_AVG),0) AS RXQUAL_FULL_UPLINK_MED_AVG
				,IFNULL(SUM(BSSMAP_11),0) AS BSSMAP_11
				,IFNULL(SUM(BSSMAP_12),0) AS BSSMAP_12
				,IFNULL(SUM(BSSMAP_13),0) AS BSSMAP_13
				,IFNULL(SUM(BSSMAP_14),0) AS BSSMAP_14
				,IFNULL(SUM(BSSMAP_15),0) AS BSSMAP_15
				,IFNULL(SUM(BSSMAP_16),0) AS BSSMAP_16
				,IFNULL(SUM(BSSMAP_17),0) AS BSSMAP_17
				,IFNULL(SUM(BSSMAP_18),0) AS BSSMAP_18
				,IFNULL(SUM(RSL_21),0) AS RSL_21
				,IFNULL(SUM(RSL_22),0) AS RSL_22
				,IFNULL(SUM(RSL_23),0) AS RSL_23
				,IFNULL(SUM(RR_31),0) AS RR_31
				,IFNULL(SUM(RR_32),0) AS RR_32
				,IFNULL(SUM(RR_33),0) AS RR_33
				,IFNULL(SUM(RR_34),0) AS RR_34
				,IFNULL(SUM(RR_35),0) AS RR_35
				,IFNULL(SUM(RR_36),0) AS RR_36
			FROM ',GT_DB,RUN,'.tmp_table_tile_end_gsm_',WORKER_ID,'
			GROUP BY   
				DATA_DATE
				,DATA_HOUR
				,TILE_ID
			ORDER BY NULL;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_End_GSM','Insert into table_tile_end_gsm_c_def ', NOW());
	SET @SqlCmd=CONCAT('INSERT INTO  ',GT_DB,RUN,'.table_tile_end_gsm_c_def
				(
				DATA_DATE,
				DATA_HOUR,
				BSC_ID,
				CELL_ID,
				CELL_LON,
				CELL_LAT,
				CELL_NAME,
				CALL_CNT,
				RXLEV_FULL_DOWNLINK_CNT,
				RXLEV_FULL_DOWNLINK_SUM,
				RXQUAL_FULL_DOWNLINK_CNT,
				RXQUAL_FULL_DOWNLINK_SUM,
				RXLEV_FULL_UPLINK_SUM,
				RXQUAL_FULL_UPLINK_SUM,
				RXLEV_FULL_UPLINK_CNT,
				RXQUAL_FULL_UPLINK_CNT,
				RXLEV_FULL_UPLINK_MED_AVG,
				RXQUAL_FULL_UPLINK_MED_AVG,
				BSSMAP_11,
				BSSMAP_12,
				BSSMAP_13,
				BSSMAP_14,
				BSSMAP_15,
				BSSMAP_16,
				BSSMAP_17,
				BSSMAP_18,
				RSL_21,
				RSL_22,
				RSL_23,
				RR_31,
				RR_32,
				RR_33,
				RR_34,
				RR_35,
				RR_36
				)
			    SELECT
				DATA_DATE
				,DATA_HOUR
				,BSC_ID
				,CELL_ID
				,CELL_LON
				,CELL_LAT
				,CELL_NAME
				,IFNULL(SUM(CALL_CNT),0) AS CALL_CNT
				,IFNULL(SUM(RXLEV_FULL_DOWNLINK_CNT),0) AS RXLEV_FULL_DOWNLINK_CNT
				,IFNULL(SUM(RXLEV_FULL_DOWNLINK_SUM),0) AS RXLEV_FULL_DOWNLINK_SUM
				,IFNULL(SUM(RXQUAL_FULL_DOWNLINK_CNT),0) AS RXQUAL_FULL_DOWNLINK_CNT
				,IFNULL(SUM(RXQUAL_FULL_DOWNLINK_SUM),0) AS RXQUAL_FULL_DOWNLINK_SUM
				,IFNULL(SUM(RXLEV_FULL_UPLINK_SUM),0) AS RXLEV_FULL_UPLINK_SUM
				,IFNULL(SUM(RXQUAL_FULL_UPLINK_SUM),0) AS RXQUAL_FULL_UPLINK_SUM
				,IFNULL(SUM(RXLEV_FULL_UPLINK_CNT),0) AS RXLEV_FULL_UPLINK_CNT
				,IFNULL(SUM(RXQUAL_FULL_UPLINK_CNT),0) AS RXQUAL_FULL_UPLINK_CNT
				,IFNULL(AVG(RXLEV_FULL_UPLINK_MED_AVG),0) AS RXLEV_FULL_UPLINK_MED_AVG
				,IFNULL(AVG(RXQUAL_FULL_UPLINK_MED_AVG),0) AS RXQUAL_FULL_UPLINK_MED_AVG
				,IFNULL(SUM(BSSMAP_11),0) AS BSSMAP_11
				,IFNULL(SUM(BSSMAP_12),0) AS BSSMAP_12
				,IFNULL(SUM(BSSMAP_13),0) AS BSSMAP_13
				,IFNULL(SUM(BSSMAP_14),0) AS BSSMAP_14
				,IFNULL(SUM(BSSMAP_15),0) AS BSSMAP_15
				,IFNULL(SUM(BSSMAP_16),0) AS BSSMAP_16
				,IFNULL(SUM(BSSMAP_17),0) AS BSSMAP_17
				,IFNULL(SUM(BSSMAP_18),0) AS BSSMAP_18
				,IFNULL(SUM(RSL_21),0) AS RSL_21
				,IFNULL(SUM(RSL_22),0) AS RSL_22
				,IFNULL(SUM(RSL_23),0) AS RSL_23
				,IFNULL(SUM(RR_31),0) AS RR_31
				,IFNULL(SUM(RR_32),0) AS RR_32
				,IFNULL(SUM(RR_33),0) AS RR_33
				,IFNULL(SUM(RR_34),0) AS RR_34
				,IFNULL(SUM(RR_35),0) AS RR_35
				,IFNULL(SUM(RR_36),0) AS RR_36
			FROM ',GT_DB,RUN,'.tmp_table_tile_end_gsm_',WORKER_ID,'
			GROUP BY   
				DATA_DATE
				,DATA_HOUR
				,BSC_ID
				,CELL_ID
			ORDER BY NULL;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_End_GSM','Insert into table_tile_end_gsm_dy ', NOW());
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.table_tile_end_gsm_dy
				(
				DATA_DATE,
				INDOOR,
				MOVING,
				TILE_ID,
				BSC_ID,
				CELL_ID,
				CALL_TYPE,
				CALL_STATUS,
				BANDINDEX,
				CELL_INDOOR,
				CLUSTER_ID,
				LAC,
				SITE_ID,
				CELL_LON,
				CELL_LAT,
				BCCH_ARFCN,
				CELL_NAME,
				CALL_CNT,
				RXLEV_FULL_DOWNLINK_CNT,
				RXLEV_FULL_DOWNLINK_SUM,
				RXQUAL_FULL_DOWNLINK_CNT,
				RXQUAL_FULL_DOWNLINK_SUM,
				RXLEV_FULL_UPLINK_SUM,
				RXQUAL_FULL_UPLINK_SUM,
				RXLEV_FULL_UPLINK_CNT,
				RXQUAL_FULL_UPLINK_CNT,
				RXLEV_FULL_UPLINK_MED_AVG,
				RXQUAL_FULL_UPLINK_MED_AVG,
				BSSMAP_11,
				BSSMAP_12,
				BSSMAP_13,
				BSSMAP_14,
				BSSMAP_15,
				BSSMAP_16,
				BSSMAP_17,
				BSSMAP_18,
				RSL_21,
				RSL_22,
				RSL_23,
				RR_31,
				RR_32,
				RR_33,
				RR_34,
				RR_35,
				RR_36
				)
		 	SELECT
				DATA_DATE
				,INDOOR
				,MOVING
				,TILE_ID
				,BSC_ID
				,CELL_ID
				,CALL_TYPE
				,CALL_STATUS
				,BANDINDEX
				,CELL_INDOOR
				,CLUSTER_ID
				,LAC
				,SITE_ID
				,CELL_LON
				,CELL_LAT
				,BCCH_ARFCN
				,CELL_NAME
				,IFNULL(CALL_CNT,0) AS CALL_CNT
				,IFNULL(RXLEV_FULL_DOWNLINK_CNT,0) AS RXLEV_FULL_DOWNLINK_CNT
				,IFNULL(RXLEV_FULL_DOWNLINK_SUM,0) AS RXLEV_FULL_DOWNLINK_SUM
				,IFNULL(RXQUAL_FULL_DOWNLINK_CNT,0) AS RXQUAL_FULL_DOWNLINK_CNT
				,IFNULL(RXQUAL_FULL_DOWNLINK_SUM,0) AS RXQUAL_FULL_DOWNLINK_SUM
				,IFNULL(RXLEV_FULL_UPLINK_SUM,0) AS RXLEV_FULL_UPLINK_SUM
				,IFNULL(RXQUAL_FULL_UPLINK_SUM,0) AS RXQUAL_FULL_UPLINK_SUM
				,IFNULL(RXLEV_FULL_UPLINK_CNT,0) AS RXLEV_FULL_UPLINK_CNT
				,IFNULL(RXQUAL_FULL_UPLINK_CNT,0) AS RXQUAL_FULL_UPLINK_CNT
				,IFNULL(RXLEV_FULL_UPLINK_MED_AVG,0) AS RXLEV_FULL_UPLINK_MED_AVG
				,IFNULL(RXQUAL_FULL_UPLINK_MED_AVG,0) AS RXQUAL_FULL_UPLINK_MED_AVG
				,IFNULL(BSSMAP_11,0) AS BSSMAP_11
				,IFNULL(BSSMAP_12,0) AS BSSMAP_12
				,IFNULL(BSSMAP_13,0) AS BSSMAP_13
				,IFNULL(BSSMAP_14,0) AS BSSMAP_14
				,IFNULL(BSSMAP_15,0) AS BSSMAP_15
				,IFNULL(BSSMAP_16,0) AS BSSMAP_16
				,IFNULL(BSSMAP_17,0) AS BSSMAP_17
				,IFNULL(BSSMAP_18,0) AS BSSMAP_18
				,IFNULL(RSL_21,0) AS RSL_21
				,IFNULL(RSL_22,0) AS RSL_22
				,IFNULL(RSL_23,0) AS RSL_23
				,IFNULL(RR_31,0) AS RR_31
				,IFNULL(RR_32,0) AS RR_32
				,IFNULL(RR_33,0) AS RR_33
				,IFNULL(RR_34,0) AS RR_34
				,IFNULL(RR_35,0) AS RR_35
				,IFNULL(RR_36,0) AS RR_36
			FROM ',GT_DB,RUN,'.tmp_table_tile_end_gsm_',WORKER_ID,'
-- 			GROUP BY 
-- 				DATA_DATE
-- 				,INDOOR
-- 				,MOVING
-- 				,TILE_ID
-- 				,BSC_ID
-- 				,CELL_ID
-- 				,CALL_TYPE
-- 				,CALL_STATUS
			ON DUPLICATE KEY UPDATE
				',GT_DB,'.table_tile_end_gsm_dy.CALL_CNT=',GT_DB,'.table_tile_end_gsm_dy.CALL_CNT+VALUES(CALL_CNT),
				',GT_DB,'.table_tile_end_gsm_dy.RXLEV_FULL_DOWNLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy.RXLEV_FULL_DOWNLINK_CNT+VALUES(RXLEV_FULL_DOWNLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy.RXLEV_FULL_DOWNLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy.RXLEV_FULL_DOWNLINK_SUM+VALUES(RXLEV_FULL_DOWNLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy.RXQUAL_FULL_DOWNLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy.RXQUAL_FULL_DOWNLINK_CNT+VALUES(RXQUAL_FULL_DOWNLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy.RXQUAL_FULL_DOWNLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy.RXQUAL_FULL_DOWNLINK_SUM+VALUES(RXQUAL_FULL_DOWNLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy.RXLEV_FULL_UPLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy.RXLEV_FULL_UPLINK_SUM+VALUES(RXLEV_FULL_UPLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy.RXQUAL_FULL_UPLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy.RXQUAL_FULL_UPLINK_SUM+VALUES(RXQUAL_FULL_UPLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy.RXLEV_FULL_UPLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy.RXLEV_FULL_UPLINK_CNT+VALUES(RXLEV_FULL_UPLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy.RXQUAL_FULL_UPLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy.RXQUAL_FULL_UPLINK_CNT+VALUES(RXQUAL_FULL_UPLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy.RXLEV_FULL_UPLINK_MED_AVG=(',GT_DB,'.table_tile_end_gsm_dy.RXLEV_FULL_UPLINK_MED_AVG+VALUES(RXLEV_FULL_UPLINK_MED_AVG))/2,
				',GT_DB,'.table_tile_end_gsm_dy.RXQUAL_FULL_UPLINK_MED_AVG=(',GT_DB,'.table_tile_end_gsm_dy.RXQUAL_FULL_UPLINK_MED_AVG+VALUES(RXQUAL_FULL_UPLINK_MED_AVG))/2,
				',GT_DB,'.table_tile_end_gsm_dy.BSSMAP_11=',GT_DB,'.table_tile_end_gsm_dy.BSSMAP_11+VALUES(BSSMAP_11),
				',GT_DB,'.table_tile_end_gsm_dy.BSSMAP_12=',GT_DB,'.table_tile_end_gsm_dy.BSSMAP_12+VALUES(BSSMAP_12),
				',GT_DB,'.table_tile_end_gsm_dy.BSSMAP_13=',GT_DB,'.table_tile_end_gsm_dy.BSSMAP_13+VALUES(BSSMAP_13),
				',GT_DB,'.table_tile_end_gsm_dy.BSSMAP_14=',GT_DB,'.table_tile_end_gsm_dy.BSSMAP_14+VALUES(BSSMAP_14),
				',GT_DB,'.table_tile_end_gsm_dy.BSSMAP_15=',GT_DB,'.table_tile_end_gsm_dy.BSSMAP_15+VALUES(BSSMAP_15),
				',GT_DB,'.table_tile_end_gsm_dy.BSSMAP_16=',GT_DB,'.table_tile_end_gsm_dy.BSSMAP_16+VALUES(BSSMAP_16),
				',GT_DB,'.table_tile_end_gsm_dy.BSSMAP_17=',GT_DB,'.table_tile_end_gsm_dy.BSSMAP_17+VALUES(BSSMAP_17),
				',GT_DB,'.table_tile_end_gsm_dy.BSSMAP_18=',GT_DB,'.table_tile_end_gsm_dy.BSSMAP_18+VALUES(BSSMAP_18),
				',GT_DB,'.table_tile_end_gsm_dy.RSL_21=',GT_DB,'.table_tile_end_gsm_dy.RSL_21+VALUES(RSL_21),
				',GT_DB,'.table_tile_end_gsm_dy.RSL_22=',GT_DB,'.table_tile_end_gsm_dy.RSL_22+VALUES(RSL_22),
				',GT_DB,'.table_tile_end_gsm_dy.RSL_23=',GT_DB,'.table_tile_end_gsm_dy.RSL_23+VALUES(RSL_23),
				',GT_DB,'.table_tile_end_gsm_dy.RR_31=',GT_DB,'.table_tile_end_gsm_dy.RR_31+VALUES(RR_31),
				',GT_DB,'.table_tile_end_gsm_dy.RR_32=',GT_DB,'.table_tile_end_gsm_dy.RR_32+VALUES(RR_32),
				',GT_DB,'.table_tile_end_gsm_dy.RR_33=',GT_DB,'.table_tile_end_gsm_dy.RR_33+VALUES(RR_33),
				',GT_DB,'.table_tile_end_gsm_dy.RR_34=',GT_DB,'.table_tile_end_gsm_dy.RR_34+VALUES(RR_34),
				',GT_DB,'.table_tile_end_gsm_dy.RR_35=',GT_DB,'.table_tile_end_gsm_dy.RR_35+VALUES(RR_35),
				',GT_DB,'.table_tile_end_gsm_dy.RR_36=',GT_DB,'.table_tile_end_gsm_dy.RR_36+VALUES(RR_36)
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_End_GSM','Insert into table_tile_end_gsm_dy_t ', NOW());
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.table_tile_end_gsm_dy_t
				(
				DATA_DATE,
				INDOOR,
				MOVING,
				TILE_ID,
				CALL_TYPE,
				CALL_STATUS,
				CALL_CNT,
				RXLEV_FULL_DOWNLINK_CNT,
				RXLEV_FULL_DOWNLINK_SUM,
				RXQUAL_FULL_DOWNLINK_CNT,
				RXQUAL_FULL_DOWNLINK_SUM,
				RXLEV_FULL_UPLINK_SUM,
				RXQUAL_FULL_UPLINK_SUM,
				RXLEV_FULL_UPLINK_CNT,
				RXQUAL_FULL_UPLINK_CNT,
				RXLEV_FULL_UPLINK_MED_AVG,
				RXQUAL_FULL_UPLINK_MED_AVG,
				BSSMAP_11,
				BSSMAP_12,
				BSSMAP_13,
				BSSMAP_14,
				BSSMAP_15,
				BSSMAP_16,
				BSSMAP_17,
				BSSMAP_18,
				RSL_21,
				RSL_22,
				RSL_23,
				RR_31,
				RR_32,
				RR_33,
				RR_34,
				RR_35,
				RR_36
				)
		 	SELECT
				DATA_DATE
				,INDOOR
				,MOVING
				,TILE_ID
				,CALL_TYPE
				,CALL_STATUS
				,IFNULL(SUM(CALL_CNT),0) AS CALL_CNT
				,IFNULL(SUM(RXLEV_FULL_DOWNLINK_CNT),0) AS RXLEV_FULL_DOWNLINK_CNT
				,IFNULL(SUM(RXLEV_FULL_DOWNLINK_SUM),0) AS RXLEV_FULL_DOWNLINK_SUM
				,IFNULL(SUM(RXQUAL_FULL_DOWNLINK_CNT),0) AS RXQUAL_FULL_DOWNLINK_CNT
				,IFNULL(SUM(RXQUAL_FULL_DOWNLINK_SUM),0) AS RXQUAL_FULL_DOWNLINK_SUM
				,IFNULL(SUM(RXLEV_FULL_UPLINK_SUM),0) AS RXLEV_FULL_UPLINK_SUM
				,IFNULL(SUM(RXQUAL_FULL_UPLINK_SUM),0) AS RXQUAL_FULL_UPLINK_SUM
				,IFNULL(SUM(RXLEV_FULL_UPLINK_CNT),0) AS RXLEV_FULL_UPLINK_CNT
				,IFNULL(SUM(RXQUAL_FULL_UPLINK_CNT),0) AS RXQUAL_FULL_UPLINK_CNT
				,IFNULL(AVG(RXLEV_FULL_UPLINK_MED_AVG),0) AS RXLEV_FULL_UPLINK_MED_AVG
				,IFNULL(AVG(RXQUAL_FULL_UPLINK_MED_AVG),0) AS RXQUAL_FULL_UPLINK_MED_AVG
				,IFNULL(SUM(BSSMAP_11),0) AS BSSMAP_11
				,IFNULL(SUM(BSSMAP_12),0) AS BSSMAP_12
				,IFNULL(SUM(BSSMAP_13),0) AS BSSMAP_13
				,IFNULL(SUM(BSSMAP_14),0) AS BSSMAP_14
				,IFNULL(SUM(BSSMAP_15),0) AS BSSMAP_15
				,IFNULL(SUM(BSSMAP_16),0) AS BSSMAP_16
				,IFNULL(SUM(BSSMAP_17),0) AS BSSMAP_17
				,IFNULL(SUM(BSSMAP_18),0) AS BSSMAP_18
				,IFNULL(SUM(RSL_21),0) AS RSL_21
				,IFNULL(SUM(RSL_22),0) AS RSL_22
				,IFNULL(SUM(RSL_23),0) AS RSL_23
				,IFNULL(SUM(RR_31),0) AS RR_31
				,IFNULL(SUM(RR_32),0) AS RR_32
				,IFNULL(SUM(RR_33),0) AS RR_33
				,IFNULL(SUM(RR_34),0) AS RR_34
				,IFNULL(SUM(RR_35),0) AS RR_35
				,IFNULL(SUM(RR_36),0) AS RR_36
			FROM ',GT_DB,RUN,'.tmp_table_tile_end_gsm_',WORKER_ID,'
			GROUP BY 
				DATA_DATE
				,INDOOR
				,MOVING
				,TILE_ID
				,CALL_TYPE
				,CALL_STATUS
			ORDER BY NULL
			ON DUPLICATE KEY UPDATE
				',GT_DB,'.table_tile_end_gsm_dy_t.CALL_CNT=',GT_DB,'.table_tile_end_gsm_dy_t.CALL_CNT+VALUES(CALL_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_t.RXLEV_FULL_DOWNLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy_t.RXLEV_FULL_DOWNLINK_CNT+VALUES(RXLEV_FULL_DOWNLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_t.RXLEV_FULL_DOWNLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy_t.RXLEV_FULL_DOWNLINK_SUM+VALUES(RXLEV_FULL_DOWNLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy_t.RXQUAL_FULL_DOWNLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy_t.RXQUAL_FULL_DOWNLINK_CNT+VALUES(RXQUAL_FULL_DOWNLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_t.RXQUAL_FULL_DOWNLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy_t.RXQUAL_FULL_DOWNLINK_SUM+VALUES(RXQUAL_FULL_DOWNLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy_t.RXLEV_FULL_UPLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy_t.RXLEV_FULL_UPLINK_SUM+VALUES(RXLEV_FULL_UPLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy_t.RXQUAL_FULL_UPLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy_t.RXQUAL_FULL_UPLINK_SUM+VALUES(RXQUAL_FULL_UPLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy_t.RXLEV_FULL_UPLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy_t.RXLEV_FULL_UPLINK_CNT+VALUES(RXLEV_FULL_UPLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_t.RXQUAL_FULL_UPLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy_t.RXQUAL_FULL_UPLINK_CNT+VALUES(RXQUAL_FULL_UPLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_t.RXLEV_FULL_UPLINK_MED_AVG=(',GT_DB,'.table_tile_end_gsm_dy_t.RXLEV_FULL_UPLINK_MED_AVG+VALUES(RXLEV_FULL_UPLINK_MED_AVG))/2,
				',GT_DB,'.table_tile_end_gsm_dy_t.RXQUAL_FULL_UPLINK_MED_AVG=(',GT_DB,'.table_tile_end_gsm_dy_t.RXQUAL_FULL_UPLINK_MED_AVG+VALUES(RXQUAL_FULL_UPLINK_MED_AVG))/2,
				',GT_DB,'.table_tile_end_gsm_dy_t.BSSMAP_11=',GT_DB,'.table_tile_end_gsm_dy_t.BSSMAP_11+VALUES(BSSMAP_11),
				',GT_DB,'.table_tile_end_gsm_dy_t.BSSMAP_12=',GT_DB,'.table_tile_end_gsm_dy_t.BSSMAP_12+VALUES(BSSMAP_12),
				',GT_DB,'.table_tile_end_gsm_dy_t.BSSMAP_13=',GT_DB,'.table_tile_end_gsm_dy_t.BSSMAP_13+VALUES(BSSMAP_13),
				',GT_DB,'.table_tile_end_gsm_dy_t.BSSMAP_14=',GT_DB,'.table_tile_end_gsm_dy_t.BSSMAP_14+VALUES(BSSMAP_14),
				',GT_DB,'.table_tile_end_gsm_dy_t.BSSMAP_15=',GT_DB,'.table_tile_end_gsm_dy_t.BSSMAP_15+VALUES(BSSMAP_15),
				',GT_DB,'.table_tile_end_gsm_dy_t.BSSMAP_16=',GT_DB,'.table_tile_end_gsm_dy_t.BSSMAP_16+VALUES(BSSMAP_16),
				',GT_DB,'.table_tile_end_gsm_dy_t.BSSMAP_17=',GT_DB,'.table_tile_end_gsm_dy_t.BSSMAP_17+VALUES(BSSMAP_17),
				',GT_DB,'.table_tile_end_gsm_dy_t.BSSMAP_18=',GT_DB,'.table_tile_end_gsm_dy_t.BSSMAP_18+VALUES(BSSMAP_18),
				',GT_DB,'.table_tile_end_gsm_dy_t.RSL_21=',GT_DB,'.table_tile_end_gsm_dy_t.RSL_21+VALUES(RSL_21),
				',GT_DB,'.table_tile_end_gsm_dy_t.RSL_22=',GT_DB,'.table_tile_end_gsm_dy_t.RSL_22+VALUES(RSL_22),
				',GT_DB,'.table_tile_end_gsm_dy_t.RSL_23=',GT_DB,'.table_tile_end_gsm_dy_t.RSL_23+VALUES(RSL_23),
				',GT_DB,'.table_tile_end_gsm_dy_t.RR_31=',GT_DB,'.table_tile_end_gsm_dy_t.RR_31+VALUES(RR_31),
				',GT_DB,'.table_tile_end_gsm_dy_t.RR_32=',GT_DB,'.table_tile_end_gsm_dy_t.RR_32+VALUES(RR_32),
				',GT_DB,'.table_tile_end_gsm_dy_t.RR_33=',GT_DB,'.table_tile_end_gsm_dy_t.RR_33+VALUES(RR_33),
				',GT_DB,'.table_tile_end_gsm_dy_t.RR_34=',GT_DB,'.table_tile_end_gsm_dy_t.RR_34+VALUES(RR_34),
				',GT_DB,'.table_tile_end_gsm_dy_t.RR_35=',GT_DB,'.table_tile_end_gsm_dy_t.RR_35+VALUES(RR_35),
				',GT_DB,'.table_tile_end_gsm_dy_t.RR_36=',GT_DB,'.table_tile_end_gsm_dy_t.RR_36+VALUES(RR_36)
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_End_GSM','Insert into table_tile_end_gsm_dy_c ', NOW());
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.table_tile_end_gsm_dy_c
			(
				DATA_DATE,
				INDOOR,
				MOVING,
				BSC_ID,
				CELL_ID,
				CALL_TYPE,
				CALL_STATUS,
				BANDINDEX,
				CELL_INDOOR,
				CLUSTER_ID,
				LAC,
				SITE_ID,
				CELL_LON,
				CELL_LAT,
				BCCH_ARFCN,
				CELL_NAME,
				CALL_CNT,
				RXLEV_FULL_DOWNLINK_CNT,
				RXLEV_FULL_DOWNLINK_SUM,
				RXQUAL_FULL_DOWNLINK_CNT,
				RXQUAL_FULL_DOWNLINK_SUM,
				RXLEV_FULL_UPLINK_SUM,
				RXQUAL_FULL_UPLINK_SUM,
				RXLEV_FULL_UPLINK_CNT,
				RXQUAL_FULL_UPLINK_CNT,
				RXLEV_FULL_UPLINK_MED_AVG,
				RXQUAL_FULL_UPLINK_MED_AVG,
				BSSMAP_11,
				BSSMAP_12,
				BSSMAP_13,
				BSSMAP_14,
				BSSMAP_15,
				BSSMAP_16,
				BSSMAP_17,
				BSSMAP_18,
				RSL_21,
				RSL_22,
				RSL_23,
				RR_31,
				RR_32,
				RR_33,
				RR_34,
				RR_35,
				RR_36
			)
		 	SELECT
				DATA_DATE
				,INDOOR
				,MOVING
				,BSC_ID
				,CELL_ID
				,CALL_TYPE
				,CALL_STATUS
				,BANDINDEX
				,CELL_INDOOR
				,CLUSTER_ID
				,LAC
				,SITE_ID
				,CELL_LON
				,CELL_LAT
				,BCCH_ARFCN
				,CELL_NAME
				,IFNULL(SUM(CALL_CNT),0) AS CALL_CNT
				,IFNULL(SUM(RXLEV_FULL_DOWNLINK_CNT),0) AS RXLEV_FULL_DOWNLINK_CNT
				,IFNULL(SUM(RXLEV_FULL_DOWNLINK_SUM),0) AS RXLEV_FULL_DOWNLINK_SUM
				,IFNULL(SUM(RXQUAL_FULL_DOWNLINK_CNT),0) AS RXQUAL_FULL_DOWNLINK_CNT
				,IFNULL(SUM(RXQUAL_FULL_DOWNLINK_SUM),0) AS RXQUAL_FULL_DOWNLINK_SUM
				,IFNULL(SUM(RXLEV_FULL_UPLINK_SUM),0) AS RXLEV_FULL_UPLINK_SUM
				,IFNULL(SUM(RXQUAL_FULL_UPLINK_SUM),0) AS RXQUAL_FULL_UPLINK_SUM
				,IFNULL(SUM(RXLEV_FULL_UPLINK_CNT),0) AS RXLEV_FULL_UPLINK_CNT
				,IFNULL(SUM(RXQUAL_FULL_UPLINK_CNT),0) AS RXQUAL_FULL_UPLINK_CNT
				,IFNULL(AVG(RXLEV_FULL_UPLINK_MED_AVG),0) AS RXLEV_FULL_UPLINK_MED_AVG
				,IFNULL(AVG(RXQUAL_FULL_UPLINK_MED_AVG),0) AS RXQUAL_FULL_UPLINK_MED_AVG
				,IFNULL(SUM(BSSMAP_11),0) AS BSSMAP_11
				,IFNULL(SUM(BSSMAP_12),0) AS BSSMAP_12
				,IFNULL(SUM(BSSMAP_13),0) AS BSSMAP_13
				,IFNULL(SUM(BSSMAP_14),0) AS BSSMAP_14
				,IFNULL(SUM(BSSMAP_15),0) AS BSSMAP_15
				,IFNULL(SUM(BSSMAP_16),0) AS BSSMAP_16
				,IFNULL(SUM(BSSMAP_17),0) AS BSSMAP_17
				,IFNULL(SUM(BSSMAP_18),0) AS BSSMAP_18
				,IFNULL(SUM(RSL_21),0) AS RSL_21
				,IFNULL(SUM(RSL_22),0) AS RSL_22
				,IFNULL(SUM(RSL_23),0) AS RSL_23
				,IFNULL(SUM(RR_31),0) AS RR_31
				,IFNULL(SUM(RR_32),0) AS RR_32
				,IFNULL(SUM(RR_33),0) AS RR_33
				,IFNULL(SUM(RR_34),0) AS RR_34
				,IFNULL(SUM(RR_35),0) AS RR_35
				,IFNULL(SUM(RR_36),0) AS RR_36
			FROM ',GT_DB,RUN,'.tmp_table_tile_end_gsm_',WORKER_ID,'
			GROUP BY
				DATA_DATE
				,INDOOR
				,MOVING
				,BSC_ID
				,CELL_ID
				,CALL_TYPE
				,CALL_STATUS
			ORDER BY NULL
			ON DUPLICATE KEY UPDATE
				',GT_DB,'.table_tile_end_gsm_dy_c.CALL_CNT=',GT_DB,'.table_tile_end_gsm_dy_c.CALL_CNT+VALUES(CALL_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_c.RXLEV_FULL_DOWNLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy_c.RXLEV_FULL_DOWNLINK_CNT+VALUES(RXLEV_FULL_DOWNLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_c.RXLEV_FULL_DOWNLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy_c.RXLEV_FULL_DOWNLINK_SUM+VALUES(RXLEV_FULL_DOWNLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy_c.RXQUAL_FULL_DOWNLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy_c.RXQUAL_FULL_DOWNLINK_CNT+VALUES(RXQUAL_FULL_DOWNLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_c.RXQUAL_FULL_DOWNLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy_c.RXQUAL_FULL_DOWNLINK_SUM+VALUES(RXQUAL_FULL_DOWNLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy_c.RXLEV_FULL_UPLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy_c.RXLEV_FULL_UPLINK_SUM+VALUES(RXLEV_FULL_UPLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy_c.RXQUAL_FULL_UPLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy_c.RXQUAL_FULL_UPLINK_SUM+VALUES(RXQUAL_FULL_UPLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy_c.RXLEV_FULL_UPLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy_c.RXLEV_FULL_UPLINK_CNT+VALUES(RXLEV_FULL_UPLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_c.RXQUAL_FULL_UPLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy_c.RXQUAL_FULL_UPLINK_CNT+VALUES(RXQUAL_FULL_UPLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_c.RXLEV_FULL_UPLINK_MED_AVG=(',GT_DB,'.table_tile_end_gsm_dy_c.RXLEV_FULL_UPLINK_MED_AVG+VALUES(RXLEV_FULL_UPLINK_MED_AVG))/2,
				',GT_DB,'.table_tile_end_gsm_dy_c.RXQUAL_FULL_UPLINK_MED_AVG=(',GT_DB,'.table_tile_end_gsm_dy_c.RXQUAL_FULL_UPLINK_MED_AVG+VALUES(RXQUAL_FULL_UPLINK_MED_AVG))/2,
				',GT_DB,'.table_tile_end_gsm_dy_c.BSSMAP_11=',GT_DB,'.table_tile_end_gsm_dy_c.BSSMAP_11+VALUES(BSSMAP_11),
				',GT_DB,'.table_tile_end_gsm_dy_c.BSSMAP_12=',GT_DB,'.table_tile_end_gsm_dy_c.BSSMAP_12+VALUES(BSSMAP_12),
				',GT_DB,'.table_tile_end_gsm_dy_c.BSSMAP_13=',GT_DB,'.table_tile_end_gsm_dy_c.BSSMAP_13+VALUES(BSSMAP_13),
				',GT_DB,'.table_tile_end_gsm_dy_c.BSSMAP_14=',GT_DB,'.table_tile_end_gsm_dy_c.BSSMAP_14+VALUES(BSSMAP_14),
				',GT_DB,'.table_tile_end_gsm_dy_c.BSSMAP_15=',GT_DB,'.table_tile_end_gsm_dy_c.BSSMAP_15+VALUES(BSSMAP_15),
				',GT_DB,'.table_tile_end_gsm_dy_c.BSSMAP_16=',GT_DB,'.table_tile_end_gsm_dy_c.BSSMAP_16+VALUES(BSSMAP_16),
				',GT_DB,'.table_tile_end_gsm_dy_c.BSSMAP_17=',GT_DB,'.table_tile_end_gsm_dy_c.BSSMAP_17+VALUES(BSSMAP_17),
				',GT_DB,'.table_tile_end_gsm_dy_c.BSSMAP_18=',GT_DB,'.table_tile_end_gsm_dy_c.BSSMAP_18+VALUES(BSSMAP_18),
				',GT_DB,'.table_tile_end_gsm_dy_c.RSL_21=',GT_DB,'.table_tile_end_gsm_dy_c.RSL_21+VALUES(RSL_21),
				',GT_DB,'.table_tile_end_gsm_dy_c.RSL_22=',GT_DB,'.table_tile_end_gsm_dy_c.RSL_22+VALUES(RSL_22),
				',GT_DB,'.table_tile_end_gsm_dy_c.RSL_23=',GT_DB,'.table_tile_end_gsm_dy_c.RSL_23+VALUES(RSL_23),
				',GT_DB,'.table_tile_end_gsm_dy_c.RR_31=',GT_DB,'.table_tile_end_gsm_dy_c.RR_31+VALUES(RR_31),
				',GT_DB,'.table_tile_end_gsm_dy_c.RR_32=',GT_DB,'.table_tile_end_gsm_dy_c.RR_32+VALUES(RR_32),
				',GT_DB,'.table_tile_end_gsm_dy_c.RR_33=',GT_DB,'.table_tile_end_gsm_dy_c.RR_33+VALUES(RR_33),
				',GT_DB,'.table_tile_end_gsm_dy_c.RR_34=',GT_DB,'.table_tile_end_gsm_dy_c.RR_34+VALUES(RR_34),
				',GT_DB,'.table_tile_end_gsm_dy_c.RR_35=',GT_DB,'.table_tile_end_gsm_dy_c.RR_35+VALUES(RR_35),
				',GT_DB,'.table_tile_end_gsm_dy_c.RR_36=',GT_DB,'.table_tile_end_gsm_dy_c.RR_36+VALUES(RR_36)
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_End_GSM','Insert into table_tile_end_gsm_dy_t_def ', NOW());
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.table_tile_end_gsm_dy_t_def
			(
				DATA_DATE,
				TILE_ID,
				CALL_CNT,
				RXLEV_FULL_DOWNLINK_CNT,
				RXLEV_FULL_DOWNLINK_SUM,
				RXQUAL_FULL_DOWNLINK_CNT,
				RXQUAL_FULL_DOWNLINK_SUM,
				RXLEV_FULL_UPLINK_SUM,
				RXQUAL_FULL_UPLINK_SUM,
				RXLEV_FULL_UPLINK_CNT,
				RXQUAL_FULL_UPLINK_CNT,
				RXLEV_FULL_UPLINK_MED_AVG,
				RXQUAL_FULL_UPLINK_MED_AVG,
				BSSMAP_11,
				BSSMAP_12,
				BSSMAP_13,
				BSSMAP_14,
				BSSMAP_15,
				BSSMAP_16,
				BSSMAP_17,
				BSSMAP_18,
				RSL_21,
				RSL_22,
				RSL_23,
				RR_31,
				RR_32,
				RR_33,
				RR_34,
				RR_35,
				RR_36
			)
			SELECT
				DATA_DATE
				,TILE_ID
				,IFNULL(SUM(CALL_CNT),0) AS CALL_CNT
				,IFNULL(SUM(RXLEV_FULL_DOWNLINK_CNT),0) AS RXLEV_FULL_DOWNLINK_CNT
				,IFNULL(SUM(RXLEV_FULL_DOWNLINK_SUM),0) AS RXLEV_FULL_DOWNLINK_SUM
				,IFNULL(SUM(RXQUAL_FULL_DOWNLINK_CNT),0) AS RXQUAL_FULL_DOWNLINK_CNT
				,IFNULL(SUM(RXQUAL_FULL_DOWNLINK_SUM),0) AS RXQUAL_FULL_DOWNLINK_SUM
				,IFNULL(SUM(RXLEV_FULL_UPLINK_SUM),0) AS RXLEV_FULL_UPLINK_SUM
				,IFNULL(SUM(RXQUAL_FULL_UPLINK_SUM),0) AS RXQUAL_FULL_UPLINK_SUM
				,IFNULL(SUM(RXLEV_FULL_UPLINK_CNT),0) AS RXLEV_FULL_UPLINK_CNT
				,IFNULL(SUM(RXQUAL_FULL_UPLINK_CNT),0) AS RXQUAL_FULL_UPLINK_CNT
				,IFNULL(AVG(RXLEV_FULL_UPLINK_MED_AVG),0) AS RXLEV_FULL_UPLINK_MED_AVG
				,IFNULL(AVG(RXQUAL_FULL_UPLINK_MED_AVG),0) AS RXQUAL_FULL_UPLINK_MED_AVG
				,IFNULL(SUM(BSSMAP_11),0) AS BSSMAP_11
				,IFNULL(SUM(BSSMAP_12),0) AS BSSMAP_12
				,IFNULL(SUM(BSSMAP_13),0) AS BSSMAP_13
				,IFNULL(SUM(BSSMAP_14),0) AS BSSMAP_14
				,IFNULL(SUM(BSSMAP_15),0) AS BSSMAP_15
				,IFNULL(SUM(BSSMAP_16),0) AS BSSMAP_16
				,IFNULL(SUM(BSSMAP_17),0) AS BSSMAP_17
				,IFNULL(SUM(BSSMAP_18),0) AS BSSMAP_18
				,IFNULL(SUM(RSL_21),0) AS RSL_21
				,IFNULL(SUM(RSL_22),0) AS RSL_22
				,IFNULL(SUM(RSL_23),0) AS RSL_23
				,IFNULL(SUM(RR_31),0) AS RR_31
				,IFNULL(SUM(RR_32),0) AS RR_32
				,IFNULL(SUM(RR_33),0) AS RR_33
				,IFNULL(SUM(RR_34),0) AS RR_34
				,IFNULL(SUM(RR_35),0) AS RR_35
				,IFNULL(SUM(RR_36),0) AS RR_36
			FROM ',GT_DB,RUN,'.tmp_table_tile_end_gsm_',WORKER_ID,'
			GROUP BY 
				DATA_DATE
				, TILE_ID
			ORDER BY NULL
			ON DUPLICATE KEY UPDATE
				',GT_DB,'.table_tile_end_gsm_dy_t_def.CALL_CNT=',GT_DB,'.table_tile_end_gsm_dy_t_def.CALL_CNT+VALUES(CALL_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.RXLEV_FULL_DOWNLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy_t_def.RXLEV_FULL_DOWNLINK_CNT+VALUES(RXLEV_FULL_DOWNLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.RXLEV_FULL_DOWNLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy_t_def.RXLEV_FULL_DOWNLINK_SUM+VALUES(RXLEV_FULL_DOWNLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.RXQUAL_FULL_DOWNLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy_t_def.RXQUAL_FULL_DOWNLINK_CNT+VALUES(RXQUAL_FULL_DOWNLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.RXQUAL_FULL_DOWNLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy_t_def.RXQUAL_FULL_DOWNLINK_SUM+VALUES(RXQUAL_FULL_DOWNLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.RXLEV_FULL_UPLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy_t_def.RXLEV_FULL_UPLINK_SUM+VALUES(RXLEV_FULL_UPLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.RXQUAL_FULL_UPLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy_t_def.RXQUAL_FULL_UPLINK_SUM+VALUES(RXQUAL_FULL_UPLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.RXLEV_FULL_UPLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy_t_def.RXLEV_FULL_UPLINK_CNT+VALUES(RXLEV_FULL_UPLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.RXQUAL_FULL_UPLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy_t_def.RXQUAL_FULL_UPLINK_CNT+VALUES(RXQUAL_FULL_UPLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.RXLEV_FULL_UPLINK_MED_AVG=(',GT_DB,'.table_tile_end_gsm_dy_t_def.RXLEV_FULL_UPLINK_MED_AVG+VALUES(RXLEV_FULL_UPLINK_MED_AVG))/2,
				',GT_DB,'.table_tile_end_gsm_dy_t_def.RXQUAL_FULL_UPLINK_MED_AVG=(',GT_DB,'.table_tile_end_gsm_dy_t_def.RXQUAL_FULL_UPLINK_MED_AVG+VALUES(RXQUAL_FULL_UPLINK_MED_AVG))/2,
				',GT_DB,'.table_tile_end_gsm_dy_t_def.BSSMAP_11=',GT_DB,'.table_tile_end_gsm_dy_t_def.BSSMAP_11+VALUES(BSSMAP_11),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.BSSMAP_12=',GT_DB,'.table_tile_end_gsm_dy_t_def.BSSMAP_12+VALUES(BSSMAP_12),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.BSSMAP_13=',GT_DB,'.table_tile_end_gsm_dy_t_def.BSSMAP_13+VALUES(BSSMAP_13),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.BSSMAP_14=',GT_DB,'.table_tile_end_gsm_dy_t_def.BSSMAP_14+VALUES(BSSMAP_14),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.BSSMAP_15=',GT_DB,'.table_tile_end_gsm_dy_t_def.BSSMAP_15+VALUES(BSSMAP_15),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.BSSMAP_16=',GT_DB,'.table_tile_end_gsm_dy_t_def.BSSMAP_16+VALUES(BSSMAP_16),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.BSSMAP_17=',GT_DB,'.table_tile_end_gsm_dy_t_def.BSSMAP_17+VALUES(BSSMAP_17),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.BSSMAP_18=',GT_DB,'.table_tile_end_gsm_dy_t_def.BSSMAP_18+VALUES(BSSMAP_18),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.RSL_21=',GT_DB,'.table_tile_end_gsm_dy_t_def.RSL_21+VALUES(RSL_21),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.RSL_22=',GT_DB,'.table_tile_end_gsm_dy_t_def.RSL_22+VALUES(RSL_22),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.RSL_23=',GT_DB,'.table_tile_end_gsm_dy_t_def.RSL_23+VALUES(RSL_23),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.RR_31=',GT_DB,'.table_tile_end_gsm_dy_t_def.RR_31+VALUES(RR_31),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.RR_32=',GT_DB,'.table_tile_end_gsm_dy_t_def.RR_32+VALUES(RR_32),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.RR_33=',GT_DB,'.table_tile_end_gsm_dy_t_def.RR_33+VALUES(RR_33),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.RR_34=',GT_DB,'.table_tile_end_gsm_dy_t_def.RR_34+VALUES(RR_34),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.RR_35=',GT_DB,'.table_tile_end_gsm_dy_t_def.RR_35+VALUES(RR_35),
				',GT_DB,'.table_tile_end_gsm_dy_t_def.RR_36=',GT_DB,'.table_tile_end_gsm_dy_t_def.RR_36+VALUES(RR_36)
			;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_End_GSM','Insert into table_tile_end_gsm_dy_c_def ', NOW());
		SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.table_tile_end_gsm_dy_c_def
			(
				DATA_DATE,
				BSC_ID,
				CELL_ID,
				CELL_LON,
				CELL_LAT,
				CELL_NAME,
				CALL_CNT,
				RXLEV_FULL_DOWNLINK_CNT,
				RXLEV_FULL_DOWNLINK_SUM,
				RXQUAL_FULL_DOWNLINK_CNT,
				RXQUAL_FULL_DOWNLINK_SUM,
				RXLEV_FULL_UPLINK_SUM,
				RXQUAL_FULL_UPLINK_SUM,
				RXLEV_FULL_UPLINK_CNT,
				RXQUAL_FULL_UPLINK_CNT,
				RXLEV_FULL_UPLINK_MED_AVG,
				RXQUAL_FULL_UPLINK_MED_AVG,
				BSSMAP_11,
				BSSMAP_12,
				BSSMAP_13,
				BSSMAP_14,
				BSSMAP_15,
				BSSMAP_16,
				BSSMAP_17,
				BSSMAP_18,
				RSL_21,
				RSL_22,
				RSL_23,
				RR_31,
				RR_32,
				RR_33,
				RR_34,
				RR_35,
				RR_36
			)
			SELECT
				DATA_DATE
				,BSC_ID
				,CELL_ID
				,CELL_LON
				,CELL_LAT
				,CELL_NAME
				,IFNULL(SUM(CALL_CNT),0) AS CALL_CNT
				,IFNULL(SUM(RXLEV_FULL_DOWNLINK_CNT),0) AS RXLEV_FULL_DOWNLINK_CNT
				,IFNULL(SUM(RXLEV_FULL_DOWNLINK_SUM),0) AS RXLEV_FULL_DOWNLINK_SUM
				,IFNULL(SUM(RXQUAL_FULL_DOWNLINK_CNT),0) AS RXQUAL_FULL_DOWNLINK_CNT
				,IFNULL(SUM(RXQUAL_FULL_DOWNLINK_SUM),0) AS RXQUAL_FULL_DOWNLINK_SUM
				,IFNULL(SUM(RXLEV_FULL_UPLINK_SUM),0) AS RXLEV_FULL_UPLINK_SUM
				,IFNULL(SUM(RXQUAL_FULL_UPLINK_SUM),0) AS RXQUAL_FULL_UPLINK_SUM
				,IFNULL(SUM(RXLEV_FULL_UPLINK_CNT),0) AS RXLEV_FULL_UPLINK_CNT
				,IFNULL(SUM(RXQUAL_FULL_UPLINK_CNT),0) AS RXQUAL_FULL_UPLINK_CNT
				,IFNULL(AVG(RXLEV_FULL_UPLINK_MED_AVG),0) AS RXLEV_FULL_UPLINK_MED_AVG
				,IFNULL(AVG(RXQUAL_FULL_UPLINK_MED_AVG),0) AS RXQUAL_FULL_UPLINK_MED_AVG
				,IFNULL(SUM(BSSMAP_11),0) AS BSSMAP_11
				,IFNULL(SUM(BSSMAP_12),0) AS BSSMAP_12
				,IFNULL(SUM(BSSMAP_13),0) AS BSSMAP_13
				,IFNULL(SUM(BSSMAP_14),0) AS BSSMAP_14
				,IFNULL(SUM(BSSMAP_15),0) AS BSSMAP_15
				,IFNULL(SUM(BSSMAP_16),0) AS BSSMAP_16
				,IFNULL(SUM(BSSMAP_17),0) AS BSSMAP_17
				,IFNULL(SUM(BSSMAP_18),0) AS BSSMAP_18
				,IFNULL(SUM(RSL_21),0) AS RSL_21
				,IFNULL(SUM(RSL_22),0) AS RSL_22
				,IFNULL(SUM(RSL_23),0) AS RSL_23
				,IFNULL(SUM(RR_31),0) AS RR_31
				,IFNULL(SUM(RR_32),0) AS RR_32
				,IFNULL(SUM(RR_33),0) AS RR_33
				,IFNULL(SUM(RR_34),0) AS RR_34
				,IFNULL(SUM(RR_35),0) AS RR_35
				,IFNULL(SUM(RR_36),0) AS RR_36
			FROM ',GT_DB,RUN,'.tmp_table_tile_end_gsm_',WORKER_ID,'
			GROUP BY 
				DATA_DATE
				,BSC_ID
				,CELL_ID
			ORDER BY NULL
			ON DUPLICATE KEY UPDATE
				',GT_DB,'.table_tile_end_gsm_dy_c_def.CALL_CNT=',GT_DB,'.table_tile_end_gsm_dy_c_def.CALL_CNT+VALUES(CALL_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.RXLEV_FULL_DOWNLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy_c_def.RXLEV_FULL_DOWNLINK_CNT+VALUES(RXLEV_FULL_DOWNLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.RXLEV_FULL_DOWNLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy_c_def.RXLEV_FULL_DOWNLINK_SUM+VALUES(RXLEV_FULL_DOWNLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.RXQUAL_FULL_DOWNLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy_c_def.RXQUAL_FULL_DOWNLINK_CNT+VALUES(RXQUAL_FULL_DOWNLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.RXQUAL_FULL_DOWNLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy_c_def.RXQUAL_FULL_DOWNLINK_SUM+VALUES(RXQUAL_FULL_DOWNLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.RXLEV_FULL_UPLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy_c_def.RXLEV_FULL_UPLINK_SUM+VALUES(RXLEV_FULL_UPLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.RXQUAL_FULL_UPLINK_SUM=',GT_DB,'.table_tile_end_gsm_dy_c_def.RXQUAL_FULL_UPLINK_SUM+VALUES(RXQUAL_FULL_UPLINK_SUM),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.RXLEV_FULL_UPLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy_c_def.RXLEV_FULL_UPLINK_CNT+VALUES(RXLEV_FULL_UPLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.RXQUAL_FULL_UPLINK_CNT=',GT_DB,'.table_tile_end_gsm_dy_c_def.RXQUAL_FULL_UPLINK_CNT+VALUES(RXQUAL_FULL_UPLINK_CNT),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.RXLEV_FULL_UPLINK_MED_AVG=(',GT_DB,'.table_tile_end_gsm_dy_c_def.RXLEV_FULL_UPLINK_MED_AVG+VALUES(RXLEV_FULL_UPLINK_MED_AVG))/2,
				',GT_DB,'.table_tile_end_gsm_dy_c_def.RXQUAL_FULL_UPLINK_MED_AVG=(',GT_DB,'.table_tile_end_gsm_dy_c_def.RXQUAL_FULL_UPLINK_MED_AVG+VALUES(RXQUAL_FULL_UPLINK_MED_AVG))/2,
				',GT_DB,'.table_tile_end_gsm_dy_c_def.BSSMAP_11=',GT_DB,'.table_tile_end_gsm_dy_c_def.BSSMAP_11+VALUES(BSSMAP_11),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.BSSMAP_12=',GT_DB,'.table_tile_end_gsm_dy_c_def.BSSMAP_12+VALUES(BSSMAP_12),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.BSSMAP_13=',GT_DB,'.table_tile_end_gsm_dy_c_def.BSSMAP_13+VALUES(BSSMAP_13),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.BSSMAP_14=',GT_DB,'.table_tile_end_gsm_dy_c_def.BSSMAP_14+VALUES(BSSMAP_14),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.BSSMAP_15=',GT_DB,'.table_tile_end_gsm_dy_c_def.BSSMAP_15+VALUES(BSSMAP_15),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.BSSMAP_16=',GT_DB,'.table_tile_end_gsm_dy_c_def.BSSMAP_16+VALUES(BSSMAP_16),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.BSSMAP_17=',GT_DB,'.table_tile_end_gsm_dy_c_def.BSSMAP_17+VALUES(BSSMAP_17),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.BSSMAP_18=',GT_DB,'.table_tile_end_gsm_dy_c_def.BSSMAP_18+VALUES(BSSMAP_18),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.RSL_21=',GT_DB,'.table_tile_end_gsm_dy_c_def.RSL_21+VALUES(RSL_21),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.RSL_22=',GT_DB,'.table_tile_end_gsm_dy_c_def.RSL_22+VALUES(RSL_22),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.RSL_23=',GT_DB,'.table_tile_end_gsm_dy_c_def.RSL_23+VALUES(RSL_23),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.RR_31=',GT_DB,'.table_tile_end_gsm_dy_c_def.RR_31+VALUES(RR_31),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.RR_32=',GT_DB,'.table_tile_end_gsm_dy_c_def.RR_32+VALUES(RR_32),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.RR_33=',GT_DB,'.table_tile_end_gsm_dy_c_def.RR_33+VALUES(RR_33),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.RR_34=',GT_DB,'.table_tile_end_gsm_dy_c_def.RR_34+VALUES(RR_34),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.RR_35=',GT_DB,'.table_tile_end_gsm_dy_c_def.RR_35+VALUES(RR_35),
				',GT_DB,'.table_tile_end_gsm_dy_c_def.RR_36=',GT_DB,'.table_tile_end_gsm_dy_c_def.RR_36+VALUES(RR_36)
			;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_End_GSM',CONCAT('Done: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());
	
		
END$$
DELIMITER ;
