DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Sub_Update_APN`(IN GT_DB VARCHAR(100),IN GT_COVMO VARCHAR(100))
BEGIN
	DECLARE GT_SESSION_ID INT;
	DECLARE WORKER_ID VARCHAR(10) DEFAULT CONNECTION_ID();
	DECLARE SH_EH VARCHAR(9) DEFAULT RIGHT(GT_DB,9);
	DECLARE SH VARCHAR(4) DEFAULT gt_strtok(SH_EH,1,'_');
	DECLARE FROM_GT_DB VARCHAR(100) DEFAULT GT_DB;
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	
	SELECT REPLACE(GT_DB,SH_EH,'0000_0000') INTO GT_DB;
	
	SET @SqlCmd=CONCAT('SELECT APN_ID INTO @NULL_ID FROM ',GT_COVMO,'.dim_apn WHERE `APN`=''Other'';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
 	SELECT SESSION_ID INTO GT_Session_ID FROM gt_gw_main.session_information WHERE SESSION_DB=GT_DB;
	INSERT INTO gt_gw_main.sp_log VALUES(FROM_GT_DB,'SP_Sub_Update_APN','Step1', NOW());
	SET @SqlCmd=CONCAT('UPDATE ',GT_DB,'.`table_call_',SH,'` A FORCE INDEX(APN)
					,  ',GT_COVMO,'.dim_apn B
				SET A.APN = B.APN_ID 
				WHERE A.ACCESS_POINT_NAME = B.APN;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	INSERT INTO gt_gw_main.sp_log VALUES(FROM_GT_DB,'SP_Sub_Update_APN','Step2', NOW());
	SET @SqlCmd=CONCAT('INSERT INTO `gt_gw_main`.`dim_imsi_apn`
				    (`SESSION_ID`,`DATA_TIME`,`IMSI`,`APN_ID`,`APN`)
				SELECT
					', GT_Session_ID,'
					,B.START_TIME
					,B.IMSI
					,B.APN
					,B.ACCESS_POINT_NAME
					FROM ',GT_DB,'.`table_call_',SH,'` B
				WHERE 
					B.CALL_TYPE IN (12,13,14,18) 
					AND B.IMSI IS NOT NULL 
					AND TRIM(B.IMSI) <> '''' 
					AND B.APN IS NOT NULL
					AND B.ACCESS_POINT_NAME IS NOT NULL 
					AND TRIM(B.ACCESS_POINT_NAME) <> '''' 
					AND LEFT(B.ACCESS_POINT_NAME,3) <> ''mms''
				ON DUPLICATE KEY UPDATE 
					dim_imsi_apn.APN_ID=B.APN
					,dim_imsi_apn.APN=B.ACCESS_POINT_NAME;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	INSERT INTO gt_gw_main.sp_log VALUES(FROM_GT_DB,'SP_Sub_Update_APN','Step3', NOW());	
	SET @SqlCmd=CONCAT('UPDATE ',GT_DB,'.`table_call_',SH,'` A FORCE INDEX(IMSI), `gt_gw_main`.`dim_imsi_apn` B
				SET A.ACCESS_POINT_NAME = B.APN
					,A.APN = B.APN_ID
				WHERE A.IMSI=B.IMSI and A.ACCESS_POINT_NAME IS NULL AND A.CALL_TYPE IN (12,13,14,18);');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(FROM_GT_DB,'SP_Sub_Update_APN','Step4', NOW());
	SET @SqlCmd=CONCAT('UPDATE ',GT_DB,'.`table_call_',SH,'`
				SET APN = ',@NULL_ID,'
				WHERE CALL_TYPE IN (12,13,14,18) AND ACCESS_POINT_NAME IS NOT NULL AND APN IS NULL;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	INSERT INTO gt_gw_main.sp_log VALUES(FROM_GT_DB,'SP_Sub_Update_APN',CONCAT('Done: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());
	
END$$
DELIMITER ;
