DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Sub_Generate_FP_GSM`(IN GT_DB VARCHAR(100), IN KIND VARCHAR(20), IN VENDOR_SOURCE VARCHAR(20),IN GT_COVMO VARCHAR(100))
BEGIN
	DECLARE BSC_ID INT;
	DECLARE O_GT_DB VARCHAR(100) DEFAULT GT_DB;
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE PARTITION_ID INT DEFAULT SUBSTRING(RIGHT(GT_DB,18),10,2) ;
	DECLARE SH_EH VARCHAR(9) DEFAULT RIGHT(GT_DB,9);
	DECLARE GT_DATE VARCHAR(18) DEFAULT RIGHT(GT_DB,18);
	DECLARE STARTHOUR VARCHAR(2) DEFAULT SUBSTRING(RIGHT(GT_DB,18),10,2);
	DECLARE ENDHOUR VARCHAR(2) DEFAULT IF(SUBSTRING(RIGHT(GT_DB,18),15,2)='00','24',SUBSTRING(RIGHT(GT_DB,18),15,2));
	DECLARE RUN VARCHAR(20);
	DECLARE WORKER_ID VARCHAR(10) DEFAULT CONNECTION_ID();
	DECLARE CURRENT_NT_DB VARCHAR(50) DEFAULT CONCAT('gt_nt_',gt_strtok(GT_DB,3,'_'));
	SET SESSION group_concat_max_len = 100000;
	SET SESSION max_heap_table_size=4*1024*1024*1024;
	SET SESSION tmp_table_size=4*1024*1024*1024;
	SET SESSION sort_buffer_size = 1024*1024*1024; 
	SET SESSION read_buffer_size=1024*1024*1024;
	
	SELECT gt_strtok(GT_DB,2,'_') INTO BSC_ID;
	
	SELECT REPLACE(GT_DB,SH_EH,'0000_0000') INTO GT_DB;
	
	IF VENDOR_SOURCE = 'GW' THEN
		IF KIND = 'DAILY' THEN
			SET RUN = '_tmp';
		ELSEIF KIND = 'RERUN' THEN
			SET RUN = '_rerun';
		END IF;
	ELSEIF VENDOR_SOURCE = 'AP' THEN
		SET RUN = '';
	END IF;
	
	SET @SqlCmd=CONCAT('SELECT att_value INTO @ZOOM_LEVEL FROM ',GT_DB,RUN,'.sys_config WHERE group_name=''system'' AND att_name = ''MapResolution'';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('ALTER TABLE ',GT_DB,RUN,'.table_tile_fp_gsm TRUNCATE PARTITION h',PARTITION_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('ALTER TABLE ',GT_DB,RUN,'.table_tile_fp_gsm_t TRUNCATE PARTITION h',PARTITION_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('ALTER TABLE ',GT_DB,RUN,'.table_tile_fp_gsm_c TRUNCATE PARTITION h',PARTITION_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('ALTER TABLE ',GT_DB,RUN,'.table_tile_fp_gsm_t_def TRUNCATE PARTITION h',PARTITION_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('ALTER TABLE ',GT_DB,RUN,'.table_tile_fp_gsm_c_def TRUNCATE PARTITION h',PARTITION_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_FP_GSM','CREATE temp TABLE tmp_table_tile_fp_gsm ', NOW());
	
	SET @SqlCmd=CONCAT('DROP TEMPORARY TABLE  IF EXISTS ',GT_DB,RUN,'.tmp_table_tile_fp_gsm_',WORKER_ID,';');
	PREPARE stmt FROM @sqlcmd;
	EXECUTE stmt;
	DEALLOCATE PREPARE stmt;
	
	SET @SqlCmd=CONCAT('CREATE TEMPORARY TABLE ',GT_DB,RUN,'.tmp_table_tile_fp_gsm_',WORKER_ID,' 
			SELECT * FROM ',GT_DB,RUN,'.table_tile_fp_gsm WHERE 1<>1;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_FP_GSM','INSERT INTO tmp_table_tile_fp_gsm ', NOW());
	
	SET @SqlCmd=CONCAT('INSERT INTO  ',GT_DB,RUN,'.tmp_table_tile_fp_gsm_',WORKER_ID,'
				(
				DATA_DATE,
				DATA_HOUR,
				INDOOR,
				MOVING,
				TILE_ID,
				BSC_ID,
				CELL_ID,
				CALL_TYPE,
				CALL_STATUS,
				BANDINDEX,
				CELL_INDOOR,
				CLUSTER_ID,
				LAC,
				SITE_ID,
				CELL_LON,
				CELL_LAT,
				BCCH_ARFCN,
				CELL_NAME,
				FP_RxLev_BEST_SUM,
				FP_RxQual_BEST_SUM,
				FP_RxLev_BEST_MED_AVG,
				FP_RxQual_BEST_MED_AVG,
				FP_RxLev_ALL_SUM,
				FP_RxQual_ALL_SUM,
				FP_RxLev_ALL_MED_AVG,
				FP_RxQual_ALL_MED_AVG,
				MMR_CNT,
				BEST_CNT,
				BEST_SERVING_CNT,
				SERVING_CNT,
				RXLEV_GAP_SUM,
				RXLEV_GAP_CNT,
				SERVING_RXLEV_BETTER_GAP_SUM,
				SERVING_RXLEV_BETTER_GAP_CNT,
				SERVING_RXLEV_WORSE_GAP_SUM,
				SERVING_RXLEV_WORSE_GAP_CNT,
				INTERFERED_CNT,
				MS_POWER_SUM,
				MS_POWER_CNT,
				TOTAL_SERVING_CNT
				)
			SELECT
				DATA_DATE
				,DATA_HOUR
				,INDOOR
				,MOVING
				,TILE_ID
				,BSC_ID
				,CELL_ID
				,CALL_TYPE
				,CALL_STATUS
				,BANDINDEX
				,CELL_INDOOR
				,NULL AS CLUSTER_ID
				,LAC
				,SITE_ID
				,NULL AS CELL_LON
				,NULL AS CELL_LAT
				,BCCH_ARFCN
				,NULL AS CELL_NAME
				,IFNULL(SUM(FP_RxLev_BEST_SUM),0) AS FP_RxLev_BEST_SUM
				,IFNULL(SUM(FP_RxQual_BEST_SUM),0) AS FP_RxQual_BEST_SUM
				,IFNULL(AVG(FP_RxLev_BEST_MED_AVG),0) AS FP_RxLev_BEST_MED_AVG
				,IFNULL(AVG(FP_RxQual_BEST_MED_AVG),0) AS FP_RxQual_BEST_MED_AVG
				,IFNULL(SUM(FP_RxLev_ALL_SUM),0) AS FP_RxLev_ALL_SUM
				,IFNULL(SUM(FP_RxQual_ALL_SUM),0) AS FP_RxQual_ALL_SUM
				,IFNULL(AVG(FP_RxLev_ALL_MED_AVG),0) AS FP_RxLev_ALL_MED_AVG
				,IFNULL(AVG(FP_RxQual_ALL_MED_AVG),0) AS FP_RxQual_ALL_MED_AVG
				,IFNULL(SUM(MMR_CNT),0) AS MMR_CNT
				,IFNULL(SUM(BEST_CNT),0) AS BEST_CNT
				,IFNULL(SUM(BEST_SERVING_CNT),0) AS BEST_SERVING_CNT
				,IFNULL(SUM(SERVING_CNT),0) AS SERVING_CNT
				,IFNULL(SUM(RXLEV_GAP_SUM),0) AS RXLEV_GAP_SUM
				,IFNULL(SUM(RXLEV_GAP_CNT),0) AS RXLEV_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_SUM),0) AS SERVING_RXLEV_BETTER_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_CNT),0) AS SERVING_RXLEV_BETTER_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_SUM),0) AS SERVING_RXLEV_WORSE_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_CNT),0) AS SERVING_RXLEV_WORSE_GAP_CNT
				,IFNULL(SUM(INTERFERED_CNT),0) AS INTERFERED_CNT
				,IFNULL(SUM(MS_POWER_SUM),0) AS MS_POWER_SUM
				,IFNULL(SUM(MS_POWER_CNT),0) AS MS_POWER_CNT
				,IFNULL(SUM(TOTAL_SERVING_CNT),0) AS TOTAL_SERVING_CNT
			FROM ',GT_DB,RUN,'.table_tile_fp_gsm_update
			WHERE DATA_HOUR >= ',STARTHOUR,' AND DATA_HOUR < ',ENDHOUR,'
			GROUP BY  
				DATA_DATE
				,DATA_HOUR
				,CALL_TYPE
				,CALL_STATUS
				,MOVING
				,INDOOR
				,BSC_ID
				,CELL_ID
				,TILE_ID
			ORDER BY NULL');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_FP_GSM','UPDATE CELL_LON, CELL_LAT, CELL_NAME IN table_tile_fp_gsm ', NOW());
	SET @SqlCmd=CONCAT(' UPDATE ',GT_DB,RUN,'.tmp_table_tile_fp_gsm_',WORKER_ID,' A, 
				    ',CURRENT_NT_DB,'.nt_cell_current_gsm B
			     SET A.CELL_LON=B.LONGITUDE
				,A.CELL_LAT=B.LATITUDE
				,A.CELL_NAME=B.CELL_NAME
				,A.CLUSTER_ID=B.CLUSTER_ID
				WHERE A.BSC_ID=B.BSC_ID
				AND A.CELL_ID=B.CELL_ID;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
		
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_FP_GSM','INSERT INTO table_tile_fp_gsm ', NOW());
	
	SET @SqlCmd=CONCAT('INSERT INTO  ',GT_DB,RUN,'.table_tile_fp_gsm
				(
				DATA_DATE,
				DATA_HOUR,
				INDOOR,
				MOVING,
				TILE_ID,
				BSC_ID,
				CELL_ID,
				CALL_TYPE,
				CALL_STATUS,
				BANDINDEX,
				CELL_INDOOR,
				CLUSTER_ID,
				LAC,
				SITE_ID,
				CELL_LON,
				CELL_LAT,
				BCCH_ARFCN,
				CELL_NAME,
				FP_RxLev_BEST_SUM,
				FP_RxQual_BEST_SUM,
				FP_RxLev_BEST_MED_AVG,
				FP_RxQual_BEST_MED_AVG,
				FP_RxLev_ALL_SUM,
				FP_RxQual_ALL_SUM,
				FP_RxLev_ALL_MED_AVG,
				FP_RxQual_ALL_MED_AVG,
				MMR_CNT,
				BEST_CNT,
				BEST_SERVING_CNT,
				SERVING_CNT,
				RXLEV_GAP_SUM,
				RXLEV_GAP_CNT,
				SERVING_RXLEV_BETTER_GAP_SUM,
				SERVING_RXLEV_BETTER_GAP_CNT,
				SERVING_RXLEV_WORSE_GAP_SUM,
				SERVING_RXLEV_WORSE_GAP_CNT,
				INTERFERED_CNT,
				MS_POWER_SUM,
				MS_POWER_CNT,
				TOTAL_SERVING_CNT
				)
			SELECT 
				DATA_DATE,
				DATA_HOUR,
				INDOOR,
				MOVING,
				TILE_ID,
				BSC_ID,
				CELL_ID,
				CALL_TYPE,
				CALL_STATUS,
				BANDINDEX,
				CELL_INDOOR,
				CLUSTER_ID,
				LAC,
				SITE_ID,
				CELL_LON,
				CELL_LAT,
				BCCH_ARFCN,
				CELL_NAME,
				FP_RxLev_BEST_SUM,
				FP_RxQual_BEST_SUM,
				FP_RxLev_BEST_MED_AVG,
				FP_RxQual_BEST_MED_AVG,
				FP_RxLev_ALL_SUM,
				FP_RxQual_ALL_SUM,
				FP_RxLev_ALL_MED_AVG,
				FP_RxQual_ALL_MED_AVG,
				MMR_CNT,
				BEST_CNT,
				BEST_SERVING_CNT,
				SERVING_CNT,
				RXLEV_GAP_SUM,
				RXLEV_GAP_CNT,
				SERVING_RXLEV_BETTER_GAP_SUM,
				SERVING_RXLEV_BETTER_GAP_CNT,
				SERVING_RXLEV_WORSE_GAP_SUM,
				SERVING_RXLEV_WORSE_GAP_CNT,
				INTERFERED_CNT,
				MS_POWER_SUM,
				MS_POWER_CNT,
				TOTAL_SERVING_CNT
			FROM ',GT_DB,RUN,'.tmp_table_tile_fp_gsm_',WORKER_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_FP_GSM','INSERT INTO table_tile_fp_gsm_t ', NOW());
	SET @SqlCmd=CONCAT('INSERT INTO  ',GT_DB,RUN,'.table_tile_fp_gsm_t
				(
				DATA_DATE,
				DATA_HOUR,
				INDOOR,
				MOVING,
				TILE_ID,
				CALL_TYPE,
				CALL_STATUS,
				FP_RxLev_BEST_SUM,
				FP_RxQual_BEST_SUM,
				FP_RxLev_BEST_MED_AVG,
				FP_RxQual_BEST_MED_AVG,
				FP_RxLev_ALL_SUM,
				FP_RxQual_ALL_SUM,
				FP_RxLev_ALL_MED_AVG,
				FP_RxQual_ALL_MED_AVG,
				MMR_CNT,
				BEST_CNT,
				BEST_SERVING_CNT,
				SERVING_CNT,
				RXLEV_GAP_SUM,
				RXLEV_GAP_CNT,
				SERVING_RXLEV_BETTER_GAP_SUM,
				SERVING_RXLEV_BETTER_GAP_CNT,
				SERVING_RXLEV_WORSE_GAP_SUM,
				SERVING_RXLEV_WORSE_GAP_CNT,
				INTERFERED_CNT,
				MS_POWER_SUM,
				MS_POWER_CNT,
				TOTAL_SERVING_CNT
				)
			    SELECT
				DATA_DATE
				,DATA_HOUR
				,INDOOR
				,MOVING
				,TILE_ID
				,CALL_TYPE
				,CALL_STATUS
				,IFNULL(SUM(FP_RxLev_BEST_SUM),0) AS FP_RxLev_BEST_SUM
				,IFNULL(SUM(FP_RxQual_BEST_SUM),0) AS FP_RxQual_BEST_SUM
				,IFNULL(AVG(FP_RxLev_BEST_MED_AVG),0) AS FP_RxLev_BEST_MED_AVG
				,IFNULL(AVG(FP_RxQual_BEST_MED_AVG),0) AS FP_RxQual_BEST_MED_AVG
				,IFNULL(SUM(FP_RxLev_ALL_SUM),0) AS FP_RxLev_ALL_SUM
				,IFNULL(SUM(FP_RxQual_ALL_SUM),0) AS FP_RxQual_ALL_SUM
				,IFNULL(AVG(FP_RxLev_ALL_MED_AVG),0) AS FP_RxLev_ALL_MED_AVG
				,IFNULL(AVG(FP_RxQual_ALL_MED_AVG),0) AS FP_RxQual_ALL_MED_AVG
				,IFNULL(SUM(MMR_CNT),0) AS MMR_CNT
				,IFNULL(SUM(BEST_CNT),0) AS BEST_CNT
				,IFNULL(SUM(BEST_SERVING_CNT),0) AS BEST_SERVING_CNT
				,IFNULL(SUM(SERVING_CNT),0) AS SERVING_CNT
				,IFNULL(SUM(RXLEV_GAP_SUM),0) AS RXLEV_GAP_SUM
				,IFNULL(SUM(RXLEV_GAP_CNT),0) AS RXLEV_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_SUM),0) AS SERVING_RXLEV_BETTER_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_CNT),0) AS SERVING_RXLEV_BETTER_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_SUM),0) AS SERVING_RXLEV_WORSE_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_CNT),0) AS SERVING_RXLEV_WORSE_GAP_CNT
				,IFNULL(SUM(INTERFERED_CNT),0) AS INTERFERED_CNT
				,IFNULL(SUM(MS_POWER_SUM),0) AS MS_POWER_SUM
				,IFNULL(SUM(MS_POWER_CNT),0) AS MS_POWER_CNT
				,IFNULL(SUM(TOTAL_SERVING_CNT),0) AS TOTAL_SERVING_CNT
			FROM ',GT_DB,RUN,'.tmp_table_tile_fp_gsm_',WORKER_ID,'
			GROUP BY   
				DATA_DATE
				,DATA_HOUR
				,INDOOR
				,MOVING
				,TILE_ID
				,CALL_TYPE
				,CALL_STATUS
			ORDER BY NULL;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_FP_GSM','INSERT INTO table_tile_fp_gsm_c ', NOW());
	SET @SqlCmd=CONCAT('INSERT INTO  ',GT_DB,RUN,'.table_tile_fp_gsm_c
				(
				DATA_DATE,
				DATA_HOUR,
				INDOOR,
				MOVING,
				BSC_ID,
				CELL_ID,
				CALL_TYPE,
				CALL_STATUS,
				BANDINDEX,
				CELL_INDOOR,
				CLUSTER_ID,
				LAC,
				SITE_ID,
				CELL_LON,
				CELL_LAT,
				BCCH_ARFCN,
				CELL_NAME,
				FP_RxLev_BEST_SUM,
				FP_RxQual_BEST_SUM,
				FP_RxLev_BEST_MED_AVG,
				FP_RxQual_BEST_MED_AVG,
				FP_RxLev_ALL_SUM,
				FP_RxQual_ALL_SUM,
				FP_RxLev_ALL_MED_AVG,
				FP_RxQual_ALL_MED_AVG,
				MMR_CNT,
				BEST_CNT,
				BEST_SERVING_CNT,
				SERVING_CNT,
				RXLEV_GAP_SUM,
				RXLEV_GAP_CNT,
				SERVING_RXLEV_BETTER_GAP_SUM,
				SERVING_RXLEV_BETTER_GAP_CNT,
				SERVING_RXLEV_WORSE_GAP_SUM,
				SERVING_RXLEV_WORSE_GAP_CNT,
				INTERFERED_CNT,
				MS_POWER_SUM,
				MS_POWER_CNT,
				TOTAL_SERVING_CNT
				)
			    SELECT
				DATA_DATE
				,DATA_HOUR
				,INDOOR
				,MOVING
				,BSC_ID
				,CELL_ID
				,CALL_TYPE
				,CALL_STATUS
				,BANDINDEX
				,CELL_INDOOR
				,CLUSTER_ID
				,LAC
				,SITE_ID
				,CELL_LON
				,CELL_LAT
				,BCCH_ARFCN
				,CELL_NAME
				,IFNULL(SUM(FP_RxLev_BEST_SUM),0) AS FP_RxLev_BEST_SUM
				,IFNULL(SUM(FP_RxQual_BEST_SUM),0) AS FP_RxQual_BEST_SUM
				,IFNULL(AVG(FP_RxLev_BEST_MED_AVG),0) AS FP_RxLev_BEST_MED_AVG
				,IFNULL(AVG(FP_RxQual_BEST_MED_AVG),0) AS FP_RxQual_BEST_MED_AVG
				,IFNULL(SUM(FP_RxLev_ALL_SUM),0) AS FP_RxLev_ALL_SUM
				,IFNULL(SUM(FP_RxQual_ALL_SUM),0) AS FP_RxQual_ALL_SUM
				,IFNULL(AVG(FP_RxLev_ALL_MED_AVG),0) AS FP_RxLev_ALL_MED_AVG
				,IFNULL(AVG(FP_RxQual_ALL_MED_AVG),0) AS FP_RxQual_ALL_MED_AVG
				,IFNULL(SUM(MMR_CNT),0) AS MMR_CNT
				,IFNULL(SUM(BEST_CNT),0) AS BEST_CNT
				,IFNULL(SUM(BEST_SERVING_CNT),0) AS BEST_SERVING_CNT
				,IFNULL(SUM(SERVING_CNT),0) AS SERVING_CNT
				,IFNULL(SUM(RXLEV_GAP_SUM),0) AS RXLEV_GAP_SUM
				,IFNULL(SUM(RXLEV_GAP_CNT),0) AS RXLEV_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_SUM),0) AS SERVING_RXLEV_BETTER_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_CNT),0) AS SERVING_RXLEV_BETTER_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_SUM),0) AS SERVING_RXLEV_WORSE_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_CNT),0) AS SERVING_RXLEV_WORSE_GAP_CNT
				,IFNULL(SUM(INTERFERED_CNT),0) AS INTERFERED_CNT
				,IFNULL(SUM(MS_POWER_SUM),0) AS MS_POWER_SUM
				,IFNULL(SUM(MS_POWER_CNT),0) AS MS_POWER_CNT
				,IFNULL(SUM(TOTAL_SERVING_CNT),0) AS TOTAL_SERVING_CNT
			FROM ',GT_DB,RUN,'.tmp_table_tile_fp_gsm_',WORKER_ID,'
			GROUP BY   
				DATA_DATE
				,DATA_HOUR
				,INDOOR
				,MOVING
				,BSC_ID
				,CELL_ID
				,CALL_TYPE
				,CALL_STATUS
			ORDER BY NULL;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_FP_GSM','INSERT INTO table_tile_fp_gsm_t_def ', NOW());
	SET @SqlCmd=CONCAT('INSERT INTO  ',GT_DB,RUN,'.table_tile_fp_gsm_t_def
				(
				DATA_DATE,
				DATA_HOUR,
				TILE_ID,
				FP_RxLev_BEST_SUM,
				FP_RxQual_BEST_SUM,
				FP_RxLev_BEST_MED_AVG,
				FP_RxQual_BEST_MED_AVG,
				FP_RxLev_ALL_SUM,
				FP_RxQual_ALL_SUM,
				FP_RxLev_ALL_MED_AVG,
				FP_RxQual_ALL_MED_AVG,
				MMR_CNT,
				BEST_CNT,
				BEST_SERVING_CNT,
				SERVING_CNT,
				RXLEV_GAP_SUM,
				RXLEV_GAP_CNT,
				SERVING_RXLEV_BETTER_GAP_SUM,
				SERVING_RXLEV_BETTER_GAP_CNT,
				SERVING_RXLEV_WORSE_GAP_SUM,
				SERVING_RXLEV_WORSE_GAP_CNT,
				INTERFERED_CNT,
				MS_POWER_SUM,
				MS_POWER_CNT,
				TOTAL_SERVING_CNT
				)
			    SELECT
				DATA_DATE
				,DATA_HOUR
				,TILE_ID
				,IFNULL(SUM(FP_RxLev_BEST_SUM),0) AS FP_RxLev_BEST_SUM
				,IFNULL(SUM(FP_RxQual_BEST_SUM),0) AS FP_RxQual_BEST_SUM
				,IFNULL(AVG(FP_RxLev_BEST_MED_AVG),0) AS FP_RxLev_BEST_MED_AVG
				,IFNULL(AVG(FP_RxQual_BEST_MED_AVG),0) AS FP_RxQual_BEST_MED_AVG
				,IFNULL(SUM(FP_RxLev_ALL_SUM),0) AS FP_RxLev_ALL_SUM
				,IFNULL(SUM(FP_RxQual_ALL_SUM),0) AS FP_RxQual_ALL_SUM
				,IFNULL(AVG(FP_RxLev_ALL_MED_AVG),0) AS FP_RxLev_ALL_MED_AVG
				,IFNULL(AVG(FP_RxQual_ALL_MED_AVG),0) AS FP_RxQual_ALL_MED_AVG
				,IFNULL(SUM(MMR_CNT),0) AS MMR_CNT
				,IFNULL(SUM(BEST_CNT),0) AS BEST_CNT
				,IFNULL(SUM(BEST_SERVING_CNT),0) AS BEST_SERVING_CNT
				,IFNULL(SUM(SERVING_CNT),0) AS SERVING_CNT
				,IFNULL(SUM(RXLEV_GAP_SUM),0) AS RXLEV_GAP_SUM
				,IFNULL(SUM(RXLEV_GAP_CNT),0) AS RXLEV_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_SUM),0) AS SERVING_RXLEV_BETTER_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_CNT),0) AS SERVING_RXLEV_BETTER_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_SUM),0) AS SERVING_RXLEV_WORSE_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_CNT),0) AS SERVING_RXLEV_WORSE_GAP_CNT
				,IFNULL(SUM(INTERFERED_CNT),0) AS INTERFERED_CNT
				,IFNULL(SUM(MS_POWER_SUM),0) AS MS_POWER_SUM
				,IFNULL(SUM(MS_POWER_CNT),0) AS MS_POWER_CNT
				,IFNULL(SUM(TOTAL_SERVING_CNT),0) AS TOTAL_SERVING_CNT
			FROM ',GT_DB,RUN,'.tmp_table_tile_fp_gsm_',WORKER_ID,'
			GROUP BY   
				DATA_DATE
				,DATA_HOUR
				,TILE_ID
			ORDER BY NULL;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_FP_GSM','INSERT INTO table_tile_fp_gsm_c_def ', NOW());
	SET @SqlCmd=CONCAT('INSERT INTO  ',GT_DB,RUN,'.table_tile_fp_gsm_c_def
				(
				DATA_DATE,
				DATA_HOUR,
				BSC_ID,
				CELL_ID,
				CELL_LON,
				CELL_LAT,
				FP_RxLev_BEST_SUM,
				FP_RxQual_BEST_SUM,
				FP_RxLev_BEST_MED_AVG,
				FP_RxQual_BEST_MED_AVG,
				FP_RxLev_ALL_SUM,
				FP_RxQual_ALL_SUM,
				FP_RxLev_ALL_MED_AVG,
				FP_RxQual_ALL_MED_AVG,
				MMR_CNT,
				BEST_CNT,
				BEST_SERVING_CNT,
				SERVING_CNT,
				RXLEV_GAP_SUM,
				RXLEV_GAP_CNT,
				SERVING_RXLEV_BETTER_GAP_SUM,
				SERVING_RXLEV_BETTER_GAP_CNT,
				SERVING_RXLEV_WORSE_GAP_SUM,
				SERVING_RXLEV_WORSE_GAP_CNT,
				INTERFERED_CNT,
				MS_POWER_SUM,
				MS_POWER_CNT,
				TOTAL_SERVING_CNT
				)
			    SELECT
				DATA_DATE
				,DATA_HOUR
				,BSC_ID
				,CELL_ID
				,CELL_LON
				,CELL_LAT
				,IFNULL(SUM(FP_RxLev_BEST_SUM),0) AS FP_RxLev_BEST_SUM
				,IFNULL(SUM(FP_RxQual_BEST_SUM),0) AS FP_RxQual_BEST_SUM
				,IFNULL(AVG(FP_RxLev_BEST_MED_AVG),0) AS FP_RxLev_BEST_MED_AVG
				,IFNULL(AVG(FP_RxQual_BEST_MED_AVG),0) AS FP_RxQual_BEST_MED_AVG
				,IFNULL(SUM(FP_RxLev_ALL_SUM),0) AS FP_RxLev_ALL_SUM
				,IFNULL(SUM(FP_RxQual_ALL_SUM),0) AS FP_RxQual_ALL_SUM
				,IFNULL(AVG(FP_RxLev_ALL_MED_AVG),0) AS FP_RxLev_ALL_MED_AVG
				,IFNULL(AVG(FP_RxQual_ALL_MED_AVG),0) AS FP_RxQual_ALL_MED_AVG
				,IFNULL(SUM(MMR_CNT),0) AS MMR_CNT
				,IFNULL(SUM(BEST_CNT),0) AS BEST_CNT
				,IFNULL(SUM(BEST_SERVING_CNT),0) AS BEST_SERVING_CNT
				,IFNULL(SUM(SERVING_CNT),0) AS SERVING_CNT
				,IFNULL(SUM(RXLEV_GAP_SUM),0) AS RXLEV_GAP_SUM
				,IFNULL(SUM(RXLEV_GAP_CNT),0) AS RXLEV_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_SUM),0) AS SERVING_RXLEV_BETTER_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_CNT),0) AS SERVING_RXLEV_BETTER_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_SUM),0) AS SERVING_RXLEV_WORSE_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_CNT),0) AS SERVING_RXLEV_WORSE_GAP_CNT
				,IFNULL(SUM(INTERFERED_CNT),0) AS INTERFERED_CNT
				,IFNULL(SUM(MS_POWER_SUM),0) AS MS_POWER_SUM
				,IFNULL(SUM(MS_POWER_CNT),0) AS MS_POWER_CNT
				,IFNULL(SUM(TOTAL_SERVING_CNT),0) AS TOTAL_SERVING_CNT
			FROM ',GT_DB,RUN,'.tmp_table_tile_fp_gsm_',WORKER_ID,'
			GROUP BY   
				DATA_DATE
				,DATA_HOUR
				,BSC_ID
				,CELL_ID
			ORDER BY NULL;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_FP_GSM','INSERT INTO table_tile_fp_gsm_dy ', NOW());
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.table_tile_fp_gsm_dy
				(
				DATA_DATE,
				INDOOR,
				MOVING,
				TILE_ID,
				BSC_ID,
				CELL_ID,
				CALL_TYPE,
				CALL_STATUS,
				BANDINDEX,
				CELL_INDOOR,
				CLUSTER_ID,
				LAC,
				SITE_ID,
				CELL_LON,
				CELL_LAT,
				BCCH_ARFCN,
				CELL_NAME,
				FP_RxLev_BEST_SUM,
				FP_RxQual_BEST_SUM,
				FP_RxLev_BEST_MED_AVG,
				FP_RxQual_BEST_MED_AVG,
				FP_RxLev_ALL_SUM,
				FP_RxQual_ALL_SUM,
				FP_RxLev_ALL_MED_AVG,
				FP_RxQual_ALL_MED_AVG,
				MMR_CNT,
				BEST_CNT,
				BEST_SERVING_CNT,
				SERVING_CNT,
				RXLEV_GAP_SUM,
				RXLEV_GAP_CNT,
				SERVING_RXLEV_BETTER_GAP_SUM,
				SERVING_RXLEV_BETTER_GAP_CNT,
				SERVING_RXLEV_WORSE_GAP_SUM,
				SERVING_RXLEV_WORSE_GAP_CNT,
				INTERFERED_CNT,
				MS_POWER_SUM,
				MS_POWER_CNT,
				TOTAL_SERVING_CNT
				)
		 	SELECT
				DATA_DATE
				,INDOOR
				,MOVING
				,TILE_ID
				,BSC_ID
				,CELL_ID
				,CALL_TYPE
				,CALL_STATUS
				,BANDINDEX
				,CELL_INDOOR
				,CLUSTER_ID
				,LAC
				,SITE_ID
				,CELL_LON
				,CELL_LAT
				,BCCH_ARFCN
				,CELL_NAME
				,IFNULL(SUM(FP_RxLev_BEST_SUM),0) AS FP_RxLev_BEST_SUM
				,IFNULL(SUM(FP_RxQual_BEST_SUM),0) AS FP_RxQual_BEST_SUM
				,IFNULL(AVG(FP_RxLev_BEST_MED_AVG),0) AS FP_RxLev_BEST_MED_AVG
				,IFNULL(AVG(FP_RxQual_BEST_MED_AVG),0) AS FP_RxQual_BEST_MED_AVG
				,IFNULL(SUM(FP_RxLev_ALL_SUM),0) AS FP_RxLev_ALL_SUM
				,IFNULL(SUM(FP_RxQual_ALL_SUM),0) AS FP_RxQual_ALL_SUM
				,IFNULL(AVG(FP_RxLev_ALL_MED_AVG),0) AS FP_RxLev_ALL_MED_AVG
				,IFNULL(AVG(FP_RxQual_ALL_MED_AVG),0) AS FP_RxQual_ALL_MED_AVG
				,IFNULL(SUM(MMR_CNT),0) AS MMR_CNT
				,IFNULL(SUM(BEST_CNT),0) AS BEST_CNT
				,IFNULL(SUM(BEST_SERVING_CNT),0) AS BEST_SERVING_CNT
				,IFNULL(SUM(SERVING_CNT),0) AS SERVING_CNT
				,IFNULL(SUM(RXLEV_GAP_SUM),0) AS RXLEV_GAP_SUM
				,IFNULL(SUM(RXLEV_GAP_CNT),0) AS RXLEV_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_SUM),0) AS SERVING_RXLEV_BETTER_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_CNT),0) AS SERVING_RXLEV_BETTER_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_SUM),0) AS SERVING_RXLEV_WORSE_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_CNT),0) AS SERVING_RXLEV_WORSE_GAP_CNT
				,IFNULL(SUM(INTERFERED_CNT),0) AS INTERFERED_CNT
				,IFNULL(SUM(MS_POWER_SUM),0) AS MS_POWER_SUM
				,IFNULL(SUM(MS_POWER_CNT),0) AS MS_POWER_CNT
				,IFNULL(SUM(TOTAL_SERVING_CNT),0) AS TOTAL_SERVING_CNT
			FROM ',GT_DB,RUN,'.tmp_table_tile_fp_gsm_',WORKER_ID,'
-- 			GROUP BY 
-- 				DATA_DATE
-- 				,INDOOR
-- 				,MOVING
-- 				,TILE_ID
-- 				,BSC_ID
-- 				,CELL_ID
-- 				,CALL_TYPE
-- 				,CALL_STATUS
			ON DUPLICATE KEY UPDATE
				',GT_DB,'.table_tile_fp_gsm_dy.FP_RxLev_BEST_SUM=',GT_DB,'.table_tile_fp_gsm_dy.FP_RxLev_BEST_SUM+VALUES(FP_RxLev_BEST_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy.FP_RxQual_BEST_SUM=',GT_DB,'.table_tile_fp_gsm_dy.FP_RxQual_BEST_SUM+VALUES(FP_RxQual_BEST_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy.FP_RxLev_BEST_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy.FP_RxLev_BEST_MED_AVG+VALUES(FP_RxLev_BEST_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy.FP_RxQual_BEST_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy.FP_RxQual_BEST_MED_AVG+VALUES(FP_RxQual_BEST_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy.FP_RxLev_ALL_SUM=',GT_DB,'.table_tile_fp_gsm_dy.FP_RxLev_ALL_SUM+VALUES(FP_RxLev_ALL_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy.FP_RxQual_ALL_SUM=',GT_DB,'.table_tile_fp_gsm_dy.FP_RxQual_ALL_SUM+VALUES(FP_RxQual_ALL_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy.FP_RxLev_ALL_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy.FP_RxLev_ALL_MED_AVG+VALUES(FP_RxLev_ALL_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy.FP_RxQual_ALL_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy.FP_RxQual_ALL_MED_AVG+VALUES(FP_RxQual_ALL_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy.MMR_CNT=',GT_DB,'.table_tile_fp_gsm_dy.MMR_CNT+VALUES(MMR_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy.BEST_CNT=',GT_DB,'.table_tile_fp_gsm_dy.BEST_CNT+VALUES(BEST_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy.BEST_SERVING_CNT=',GT_DB,'.table_tile_fp_gsm_dy.BEST_SERVING_CNT+VALUES(BEST_SERVING_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy.SERVING_CNT=',GT_DB,'.table_tile_fp_gsm_dy.SERVING_CNT+VALUES(SERVING_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy.RXLEV_GAP_SUM=',GT_DB,'.table_tile_fp_gsm_dy.RXLEV_GAP_SUM+VALUES(RXLEV_GAP_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy.RXLEV_GAP_CNT=',GT_DB,'.table_tile_fp_gsm_dy.RXLEV_GAP_CNT+VALUES(RXLEV_GAP_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy.SERVING_RXLEV_BETTER_GAP_SUM=',GT_DB,'.table_tile_fp_gsm_dy.SERVING_RXLEV_BETTER_GAP_SUM+VALUES(SERVING_RXLEV_BETTER_GAP_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy.SERVING_RXLEV_BETTER_GAP_CNT=',GT_DB,'.table_tile_fp_gsm_dy.SERVING_RXLEV_BETTER_GAP_CNT+VALUES(SERVING_RXLEV_BETTER_GAP_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy.SERVING_RXLEV_WORSE_GAP_SUM=',GT_DB,'.table_tile_fp_gsm_dy.SERVING_RXLEV_WORSE_GAP_SUM+VALUES(SERVING_RXLEV_WORSE_GAP_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy.SERVING_RXLEV_WORSE_GAP_CNT=',GT_DB,'.table_tile_fp_gsm_dy.SERVING_RXLEV_WORSE_GAP_CNT+VALUES(SERVING_RXLEV_WORSE_GAP_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy.INTERFERED_CNT=',GT_DB,'.table_tile_fp_gsm_dy.INTERFERED_CNT+VALUES(INTERFERED_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy.MS_POWER_SUM=',GT_DB,'.table_tile_fp_gsm_dy.MS_POWER_SUM+VALUES(MS_POWER_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy.MS_POWER_CNT=',GT_DB,'.table_tile_fp_gsm_dy.MS_POWER_CNT+VALUES(MS_POWER_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy.TOTAL_SERVING_CNT=',GT_DB,'.table_tile_fp_gsm_dy.TOTAL_SERVING_CNT+VALUES(TOTAL_SERVING_CNT)
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_FP_GSM','INSERT INTO table_tile_fp_gsm_dy_t ', NOW());
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.table_tile_fp_gsm_dy_t
				(
				DATA_DATE,
				INDOOR,
				MOVING,
				TILE_ID,
				CALL_TYPE,
				CALL_STATUS,
				FP_RxLev_BEST_SUM,
				FP_RxQual_BEST_SUM,
				FP_RxLev_BEST_MED_AVG,
				FP_RxQual_BEST_MED_AVG,
				FP_RxLev_ALL_SUM,
				FP_RxQual_ALL_SUM,
				FP_RxLev_ALL_MED_AVG,
				FP_RxQual_ALL_MED_AVG,
				MMR_CNT,
				BEST_CNT,
				BEST_SERVING_CNT,
				SERVING_CNT,
				RXLEV_GAP_SUM,
				RXLEV_GAP_CNT,
				SERVING_RXLEV_BETTER_GAP_SUM,
				SERVING_RXLEV_BETTER_GAP_CNT,
				SERVING_RXLEV_WORSE_GAP_SUM,
				SERVING_RXLEV_WORSE_GAP_CNT,
				INTERFERED_CNT,
				MS_POWER_SUM,
				MS_POWER_CNT,
				TOTAL_SERVING_CNT
				)
		 	SELECT
				DATA_DATE
				,INDOOR
				,MOVING
				,TILE_ID
				,CALL_TYPE
				,CALL_STATUS
				,IFNULL(SUM(FP_RxLev_BEST_SUM),0) AS FP_RxLev_BEST_SUM
				,IFNULL(SUM(FP_RxQual_BEST_SUM),0) AS FP_RxQual_BEST_SUM
				,IFNULL(AVG(FP_RxLev_BEST_MED_AVG),0) AS FP_RxLev_BEST_MED_AVG
				,IFNULL(AVG(FP_RxQual_BEST_MED_AVG),0) AS FP_RxQual_BEST_MED_AVG
				,IFNULL(SUM(FP_RxLev_ALL_SUM),0) AS FP_RxLev_ALL_SUM
				,IFNULL(SUM(FP_RxQual_ALL_SUM),0) AS FP_RxQual_ALL_SUM
				,IFNULL(AVG(FP_RxLev_ALL_MED_AVG),0) AS FP_RxLev_ALL_MED_AVG
				,IFNULL(AVG(FP_RxQual_ALL_MED_AVG),0) AS FP_RxQual_ALL_MED_AVG
				,IFNULL(SUM(MMR_CNT),0) AS MMR_CNT
				,IFNULL(SUM(BEST_CNT),0) AS BEST_CNT
				,IFNULL(SUM(BEST_SERVING_CNT),0) AS BEST_SERVING_CNT
				,IFNULL(SUM(SERVING_CNT),0) AS SERVING_CNT
				,IFNULL(SUM(RXLEV_GAP_SUM),0) AS RXLEV_GAP_SUM
				,IFNULL(SUM(RXLEV_GAP_CNT),0) AS RXLEV_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_SUM),0) AS SERVING_RXLEV_BETTER_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_CNT),0) AS SERVING_RXLEV_BETTER_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_SUM),0) AS SERVING_RXLEV_WORSE_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_CNT),0) AS SERVING_RXLEV_WORSE_GAP_CNT
				,IFNULL(SUM(INTERFERED_CNT),0) AS INTERFERED_CNT
				,IFNULL(SUM(MS_POWER_SUM),0) AS MS_POWER_SUM
				,IFNULL(SUM(MS_POWER_CNT),0) AS MS_POWER_CNT
				,IFNULL(SUM(TOTAL_SERVING_CNT),0) AS TOTAL_SERVING_CNT
			FROM ',GT_DB,RUN,'.tmp_table_tile_fp_gsm_',WORKER_ID,'
			GROUP BY 
				DATA_DATE
				,INDOOR
				,MOVING
				,TILE_ID
				,CALL_TYPE
				,CALL_STATUS
			ON DUPLICATE KEY UPDATE
				',GT_DB,'.table_tile_fp_gsm_dy_t.FP_RxLev_BEST_SUM=',GT_DB,'.table_tile_fp_gsm_dy_t.FP_RxLev_BEST_SUM+VALUES(FP_RxLev_BEST_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_t.FP_RxQual_BEST_SUM=',GT_DB,'.table_tile_fp_gsm_dy_t.FP_RxQual_BEST_SUM+VALUES(FP_RxQual_BEST_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_t.FP_RxLev_BEST_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy_t.FP_RxLev_BEST_MED_AVG+VALUES(FP_RxLev_BEST_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy_t.FP_RxQual_BEST_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy_t.FP_RxQual_BEST_MED_AVG+VALUES(FP_RxQual_BEST_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy_t.FP_RxLev_ALL_SUM=',GT_DB,'.table_tile_fp_gsm_dy_t.FP_RxLev_ALL_SUM+VALUES(FP_RxLev_ALL_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_t.FP_RxQual_ALL_SUM=',GT_DB,'.table_tile_fp_gsm_dy_t.FP_RxQual_ALL_SUM+VALUES(FP_RxQual_ALL_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_t.FP_RxLev_ALL_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy_t.FP_RxLev_ALL_MED_AVG+VALUES(FP_RxLev_ALL_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy_t.FP_RxQual_ALL_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy_t.FP_RxQual_ALL_MED_AVG+VALUES(FP_RxQual_ALL_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy_t.MMR_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t.MMR_CNT+VALUES(MMR_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_t.BEST_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t.BEST_CNT+VALUES(BEST_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_t.BEST_SERVING_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t.BEST_SERVING_CNT+VALUES(BEST_SERVING_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_t.SERVING_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t.SERVING_CNT+VALUES(SERVING_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_t.RXLEV_GAP_SUM=',GT_DB,'.table_tile_fp_gsm_dy_t.RXLEV_GAP_SUM+VALUES(RXLEV_GAP_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_t.RXLEV_GAP_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t.RXLEV_GAP_CNT+VALUES(RXLEV_GAP_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_t.SERVING_RXLEV_BETTER_GAP_SUM=',GT_DB,'.table_tile_fp_gsm_dy_t.SERVING_RXLEV_BETTER_GAP_SUM+VALUES(SERVING_RXLEV_BETTER_GAP_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_t.SERVING_RXLEV_BETTER_GAP_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t.SERVING_RXLEV_BETTER_GAP_CNT+VALUES(SERVING_RXLEV_BETTER_GAP_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_t.SERVING_RXLEV_WORSE_GAP_SUM=',GT_DB,'.table_tile_fp_gsm_dy_t.SERVING_RXLEV_WORSE_GAP_SUM+VALUES(SERVING_RXLEV_WORSE_GAP_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_t.SERVING_RXLEV_WORSE_GAP_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t.SERVING_RXLEV_WORSE_GAP_CNT+VALUES(SERVING_RXLEV_WORSE_GAP_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_t.INTERFERED_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t.INTERFERED_CNT+VALUES(INTERFERED_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_t.MS_POWER_SUM=',GT_DB,'.table_tile_fp_gsm_dy_t.MS_POWER_SUM+VALUES(MS_POWER_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_t.MS_POWER_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t.MS_POWER_CNT+VALUES(MS_POWER_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_t.TOTAL_SERVING_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t.TOTAL_SERVING_CNT+VALUES(TOTAL_SERVING_CNT)
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_FP_GSM','INSERT INTO table_tile_fp_gsm_dy_c ', NOW());
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.table_tile_fp_gsm_dy_c
		(
				DATA_DATE,
				INDOOR,
				MOVING,
				BSC_ID,
				CELL_ID,
				CALL_TYPE,
				CALL_STATUS,
				BANDINDEX,
				CELL_INDOOR,
				CLUSTER_ID,
				LAC,
				SITE_ID,
				CELL_LON,
				CELL_LAT,
				BCCH_ARFCN,
				CELL_NAME,
				FP_RxLev_BEST_SUM,
				FP_RxQual_BEST_SUM,
				FP_RxLev_BEST_MED_AVG,
				FP_RxQual_BEST_MED_AVG,
				FP_RxLev_ALL_SUM,
				FP_RxQual_ALL_SUM,
				FP_RxLev_ALL_MED_AVG,
				FP_RxQual_ALL_MED_AVG,
				MMR_CNT,
				BEST_CNT,
				BEST_SERVING_CNT,
				SERVING_CNT,
				RXLEV_GAP_SUM,
				RXLEV_GAP_CNT,
				SERVING_RXLEV_BETTER_GAP_SUM,
				SERVING_RXLEV_BETTER_GAP_CNT,
				SERVING_RXLEV_WORSE_GAP_SUM,
				SERVING_RXLEV_WORSE_GAP_CNT,
				INTERFERED_CNT,
				MS_POWER_SUM,
				MS_POWER_CNT,
				TOTAL_SERVING_CNT
		)
		 	SELECT
				DATA_DATE
				,INDOOR
				,MOVING
				,BSC_ID
				,CELL_ID
				,CALL_TYPE
				,CALL_STATUS
				,BANDINDEX
				,CELL_INDOOR
				,CLUSTER_ID
				,LAC
				,SITE_ID
				,CELL_LON
				,CELL_LAT
				,BCCH_ARFCN
				,CELL_NAME
				,IFNULL(SUM(FP_RxLev_BEST_SUM),0) AS FP_RxLev_BEST_SUM
				,IFNULL(SUM(FP_RxQual_BEST_SUM),0) AS FP_RxQual_BEST_SUM
				,IFNULL(AVG(FP_RxLev_BEST_MED_AVG),0) AS FP_RxLev_BEST_MED_AVG
				,IFNULL(AVG(FP_RxQual_BEST_MED_AVG),0) AS FP_RxQual_BEST_MED_AVG
				,IFNULL(SUM(FP_RxLev_ALL_SUM),0) AS FP_RxLev_ALL_SUM
				,IFNULL(SUM(FP_RxQual_ALL_SUM),0) AS FP_RxQual_ALL_SUM
				,IFNULL(AVG(FP_RxLev_ALL_MED_AVG),0) AS FP_RxLev_ALL_MED_AVG
				,IFNULL(AVG(FP_RxQual_ALL_MED_AVG),0) AS FP_RxQual_ALL_MED_AVG
				,IFNULL(SUM(MMR_CNT),0) AS MMR_CNT
				,IFNULL(SUM(BEST_CNT),0) AS BEST_CNT
				,IFNULL(SUM(BEST_SERVING_CNT),0) AS BEST_SERVING_CNT
				,IFNULL(SUM(SERVING_CNT),0) AS SERVING_CNT
				,IFNULL(SUM(RXLEV_GAP_SUM),0) AS RXLEV_GAP_SUM
				,IFNULL(SUM(RXLEV_GAP_CNT),0) AS RXLEV_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_SUM),0) AS SERVING_RXLEV_BETTER_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_CNT),0) AS SERVING_RXLEV_BETTER_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_SUM),0) AS SERVING_RXLEV_WORSE_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_CNT),0) AS SERVING_RXLEV_WORSE_GAP_CNT
				,IFNULL(SUM(INTERFERED_CNT),0) AS INTERFERED_CNT
				,IFNULL(SUM(MS_POWER_SUM),0) AS MS_POWER_SUM
				,IFNULL(SUM(MS_POWER_CNT),0) AS MS_POWER_CNT
				,IFNULL(SUM(TOTAL_SERVING_CNT),0) AS TOTAL_SERVING_CNT
			FROM ',GT_DB,RUN,'.tmp_table_tile_fp_gsm_',WORKER_ID,'
			GROUP BY
				DATA_DATE
				,INDOOR
				,MOVING
				,BSC_ID
				,CELL_ID
				,CALL_TYPE
				,CALL_STATUS
			ON DUPLICATE KEY UPDATE
				',GT_DB,'.table_tile_fp_gsm_dy_c.FP_RxLev_BEST_SUM=',GT_DB,'.table_tile_fp_gsm_dy_c.FP_RxLev_BEST_SUM+VALUES(FP_RxLev_BEST_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_c.FP_RxQual_BEST_SUM=',GT_DB,'.table_tile_fp_gsm_dy_c.FP_RxQual_BEST_SUM+VALUES(FP_RxQual_BEST_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_c.FP_RxLev_BEST_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy_c.FP_RxLev_BEST_MED_AVG+VALUES(FP_RxLev_BEST_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy_c.FP_RxQual_BEST_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy_c.FP_RxQual_BEST_MED_AVG+VALUES(FP_RxQual_BEST_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy_c.FP_RxLev_ALL_SUM=',GT_DB,'.table_tile_fp_gsm_dy_c.FP_RxLev_ALL_SUM+VALUES(FP_RxLev_ALL_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_c.FP_RxQual_ALL_SUM=',GT_DB,'.table_tile_fp_gsm_dy_c.FP_RxQual_ALL_SUM+VALUES(FP_RxQual_ALL_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_c.FP_RxLev_ALL_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy_c.FP_RxLev_ALL_MED_AVG+VALUES(FP_RxLev_ALL_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy_c.FP_RxQual_ALL_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy_c.FP_RxQual_ALL_MED_AVG+VALUES(FP_RxQual_ALL_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy_c.MMR_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c.MMR_CNT+VALUES(MMR_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_c.BEST_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c.BEST_CNT+VALUES(BEST_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_c.BEST_SERVING_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c.BEST_SERVING_CNT+VALUES(BEST_SERVING_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_c.SERVING_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c.SERVING_CNT+VALUES(SERVING_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_c.RXLEV_GAP_SUM=',GT_DB,'.table_tile_fp_gsm_dy_c.RXLEV_GAP_SUM+VALUES(RXLEV_GAP_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_c.RXLEV_GAP_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c.RXLEV_GAP_CNT+VALUES(RXLEV_GAP_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_c.SERVING_RXLEV_BETTER_GAP_SUM=',GT_DB,'.table_tile_fp_gsm_dy_c.SERVING_RXLEV_BETTER_GAP_SUM+VALUES(SERVING_RXLEV_BETTER_GAP_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_c.SERVING_RXLEV_BETTER_GAP_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c.SERVING_RXLEV_BETTER_GAP_CNT+VALUES(SERVING_RXLEV_BETTER_GAP_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_c.SERVING_RXLEV_WORSE_GAP_SUM=',GT_DB,'.table_tile_fp_gsm_dy_c.SERVING_RXLEV_WORSE_GAP_SUM+VALUES(SERVING_RXLEV_WORSE_GAP_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_c.SERVING_RXLEV_WORSE_GAP_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c.SERVING_RXLEV_WORSE_GAP_CNT+VALUES(SERVING_RXLEV_WORSE_GAP_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_c.INTERFERED_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c.INTERFERED_CNT+VALUES(INTERFERED_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_c.MS_POWER_SUM=',GT_DB,'.table_tile_fp_gsm_dy_c.MS_POWER_SUM+VALUES(MS_POWER_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_c.MS_POWER_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c.MS_POWER_CNT+VALUES(MS_POWER_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_c.TOTAL_SERVING_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c.TOTAL_SERVING_CNT+VALUES(TOTAL_SERVING_CNT)
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_FP_GSM','INSERT INTO table_tile_fp_gsm_dy_t_def ', NOW());
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.table_tile_fp_gsm_dy_t_def
		(
				DATA_DATE,
				TILE_ID,
				FP_RxLev_BEST_SUM,
				FP_RxQual_BEST_SUM,
				FP_RxLev_BEST_MED_AVG,
				FP_RxQual_BEST_MED_AVG,
				FP_RxLev_ALL_SUM,
				FP_RxQual_ALL_SUM,
				FP_RxLev_ALL_MED_AVG,
				FP_RxQual_ALL_MED_AVG,
				MMR_CNT,
				BEST_CNT,
				BEST_SERVING_CNT,
				SERVING_CNT,
				RXLEV_GAP_SUM,
				RXLEV_GAP_CNT,
				SERVING_RXLEV_BETTER_GAP_SUM,
				SERVING_RXLEV_BETTER_GAP_CNT,
				SERVING_RXLEV_WORSE_GAP_SUM,
				SERVING_RXLEV_WORSE_GAP_CNT,
				INTERFERED_CNT,
				MS_POWER_SUM,
				MS_POWER_CNT,
				TOTAL_SERVING_CNT
		)
		 	SELECT
				DATA_DATE
				,TILE_ID
				,IFNULL(SUM(FP_RxLev_BEST_SUM),0) AS FP_RxLev_BEST_SUM
				,IFNULL(SUM(FP_RxQual_BEST_SUM),0) AS FP_RxQual_BEST_SUM
				,IFNULL(AVG(FP_RxLev_BEST_MED_AVG),0) AS FP_RxLev_BEST_MED_AVG
				,IFNULL(AVG(FP_RxQual_BEST_MED_AVG),0) AS FP_RxQual_BEST_MED_AVG
				,IFNULL(SUM(FP_RxLev_ALL_SUM),0) AS FP_RxLev_ALL_SUM
				,IFNULL(SUM(FP_RxQual_ALL_SUM),0) AS FP_RxQual_ALL_SUM
				,IFNULL(AVG(FP_RxLev_ALL_MED_AVG),0) AS FP_RxLev_ALL_MED_AVG
				,IFNULL(AVG(FP_RxQual_ALL_MED_AVG),0) AS FP_RxQual_ALL_MED_AVG
				,IFNULL(SUM(MMR_CNT),0) AS MMR_CNT
				,IFNULL(SUM(BEST_CNT),0) AS BEST_CNT
				,IFNULL(SUM(BEST_SERVING_CNT),0) AS BEST_SERVING_CNT
				,IFNULL(SUM(SERVING_CNT),0) AS SERVING_CNT
				,IFNULL(SUM(RXLEV_GAP_SUM),0) AS RXLEV_GAP_SUM
				,IFNULL(SUM(RXLEV_GAP_CNT),0) AS RXLEV_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_SUM),0) AS SERVING_RXLEV_BETTER_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_CNT),0) AS SERVING_RXLEV_BETTER_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_SUM),0) AS SERVING_RXLEV_WORSE_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_CNT),0) AS SERVING_RXLEV_WORSE_GAP_CNT
				,IFNULL(SUM(INTERFERED_CNT),0) AS INTERFERED_CNT
				,IFNULL(SUM(MS_POWER_SUM),0) AS MS_POWER_SUM
				,IFNULL(SUM(MS_POWER_CNT),0) AS MS_POWER_CNT
				,IFNULL(SUM(TOTAL_SERVING_CNT),0) AS TOTAL_SERVING_CNT
			FROM ',GT_DB,RUN,'.tmp_table_tile_fp_gsm_',WORKER_ID,'
			GROUP BY 
				DATA_DATE
				, TILE_ID
			ON DUPLICATE KEY UPDATE
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.FP_RxLev_BEST_SUM=',GT_DB,'.table_tile_fp_gsm_dy_t_def.FP_RxLev_BEST_SUM+VALUES(FP_RxLev_BEST_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.FP_RxQual_BEST_SUM=',GT_DB,'.table_tile_fp_gsm_dy_t_def.FP_RxQual_BEST_SUM+VALUES(FP_RxQual_BEST_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.FP_RxLev_BEST_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy_t_def.FP_RxLev_BEST_MED_AVG+VALUES(FP_RxLev_BEST_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.FP_RxQual_BEST_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy_t_def.FP_RxQual_BEST_MED_AVG+VALUES(FP_RxQual_BEST_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.FP_RxLev_ALL_SUM=',GT_DB,'.table_tile_fp_gsm_dy_t_def.FP_RxLev_ALL_SUM+VALUES(FP_RxLev_ALL_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.FP_RxQual_ALL_SUM=',GT_DB,'.table_tile_fp_gsm_dy_t_def.FP_RxQual_ALL_SUM+VALUES(FP_RxQual_ALL_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.FP_RxLev_ALL_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy_t_def.FP_RxLev_ALL_MED_AVG+VALUES(FP_RxLev_ALL_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.FP_RxQual_ALL_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy_t_def.FP_RxQual_ALL_MED_AVG+VALUES(FP_RxQual_ALL_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.MMR_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t_def.MMR_CNT+VALUES(MMR_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.BEST_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t_def.BEST_CNT+VALUES(BEST_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.BEST_SERVING_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t_def.BEST_SERVING_CNT+VALUES(BEST_SERVING_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.SERVING_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t_def.SERVING_CNT+VALUES(SERVING_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.RXLEV_GAP_SUM=',GT_DB,'.table_tile_fp_gsm_dy_t_def.RXLEV_GAP_SUM+VALUES(RXLEV_GAP_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.RXLEV_GAP_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t_def.RXLEV_GAP_CNT+VALUES(RXLEV_GAP_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.SERVING_RXLEV_BETTER_GAP_SUM=',GT_DB,'.table_tile_fp_gsm_dy_t_def.SERVING_RXLEV_BETTER_GAP_SUM+VALUES(SERVING_RXLEV_BETTER_GAP_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.SERVING_RXLEV_BETTER_GAP_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t_def.SERVING_RXLEV_BETTER_GAP_CNT+VALUES(SERVING_RXLEV_BETTER_GAP_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.SERVING_RXLEV_WORSE_GAP_SUM=',GT_DB,'.table_tile_fp_gsm_dy_t_def.SERVING_RXLEV_WORSE_GAP_SUM+VALUES(SERVING_RXLEV_WORSE_GAP_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.SERVING_RXLEV_WORSE_GAP_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t_def.SERVING_RXLEV_WORSE_GAP_CNT+VALUES(SERVING_RXLEV_WORSE_GAP_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.INTERFERED_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t_def.INTERFERED_CNT+VALUES(INTERFERED_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.MS_POWER_SUM=',GT_DB,'.table_tile_fp_gsm_dy_t_def.MS_POWER_SUM+VALUES(MS_POWER_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.MS_POWER_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t_def.MS_POWER_CNT+VALUES(MS_POWER_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_t_def.TOTAL_SERVING_CNT=',GT_DB,'.table_tile_fp_gsm_dy_t_def.TOTAL_SERVING_CNT+VALUES(TOTAL_SERVING_CNT)
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_FP_GSM','INSERT INTO table_tile_fp_gsm_dy_c_def ', NOW());
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,'.table_tile_fp_gsm_dy_c_def
		(
				DATA_DATE,
				BSC_ID,
				CELL_ID,
				CELL_LON,
				CELL_LAT,
				FP_RxLev_BEST_SUM,
				FP_RxQual_BEST_SUM,
				FP_RxLev_BEST_MED_AVG,
				FP_RxQual_BEST_MED_AVG,
				FP_RxLev_ALL_SUM,
				FP_RxQual_ALL_SUM,
				FP_RxLev_ALL_MED_AVG,
				FP_RxQual_ALL_MED_AVG,
				MMR_CNT,
				BEST_CNT,
				BEST_SERVING_CNT,
				SERVING_CNT,
				RXLEV_GAP_SUM,
				RXLEV_GAP_CNT,
				SERVING_RXLEV_BETTER_GAP_SUM,
				SERVING_RXLEV_BETTER_GAP_CNT,
				SERVING_RXLEV_WORSE_GAP_SUM,
				SERVING_RXLEV_WORSE_GAP_CNT,
				INTERFERED_CNT,
				MS_POWER_SUM,
				MS_POWER_CNT,
				TOTAL_SERVING_CNT
		)
		 	SELECT
				DATA_DATE
				,BSC_ID
				,CELL_ID
				,CELL_LON
				,CELL_LAT
				,IFNULL(SUM(FP_RxLev_BEST_SUM),0) AS FP_RxLev_BEST_SUM
				,IFNULL(SUM(FP_RxQual_BEST_SUM),0) AS FP_RxQual_BEST_SUM
				,IFNULL(AVG(FP_RxLev_BEST_MED_AVG),0) AS FP_RxLev_BEST_MED_AVG
				,IFNULL(AVG(FP_RxQual_BEST_MED_AVG),0) AS FP_RxQual_BEST_MED_AVG
				,IFNULL(SUM(FP_RxLev_ALL_SUM),0) AS FP_RxLev_ALL_SUM
				,IFNULL(SUM(FP_RxQual_ALL_SUM),0) AS FP_RxQual_ALL_SUM
				,IFNULL(AVG(FP_RxLev_ALL_MED_AVG),0) AS FP_RxLev_ALL_MED_AVG
				,IFNULL(AVG(FP_RxQual_ALL_MED_AVG),0) AS FP_RxQual_ALL_MED_AVG
				,IFNULL(SUM(MMR_CNT),0) AS MMR_CNT
				,IFNULL(SUM(BEST_CNT),0) AS BEST_CNT
				,IFNULL(SUM(BEST_SERVING_CNT),0) AS BEST_SERVING_CNT
				,IFNULL(SUM(SERVING_CNT),0) AS SERVING_CNT
				,IFNULL(SUM(RXLEV_GAP_SUM),0) AS RXLEV_GAP_SUM
				,IFNULL(SUM(RXLEV_GAP_CNT),0) AS RXLEV_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_SUM),0) AS SERVING_RXLEV_BETTER_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_BETTER_GAP_CNT),0) AS SERVING_RXLEV_BETTER_GAP_CNT
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_SUM),0) AS SERVING_RXLEV_WORSE_GAP_SUM
				,IFNULL(SUM(SERVING_RXLEV_WORSE_GAP_CNT),0) AS SERVING_RXLEV_WORSE_GAP_CNT
				,IFNULL(SUM(INTERFERED_CNT),0) AS INTERFERED_CNT
				,IFNULL(SUM(MS_POWER_SUM),0) AS MS_POWER_SUM
				,IFNULL(SUM(MS_POWER_CNT),0) AS MS_POWER_CNT
				,IFNULL(SUM(TOTAL_SERVING_CNT),0) AS TOTAL_SERVING_CNT
			FROM ',GT_DB,RUN,'.tmp_table_tile_fp_gsm_',WORKER_ID,'
			GROUP BY 
				DATA_DATE
				,BSC_ID
				,CELL_ID
			ON DUPLICATE KEY UPDATE
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.FP_RxLev_BEST_SUM=',GT_DB,'.table_tile_fp_gsm_dy_c_def.FP_RxLev_BEST_SUM+VALUES(FP_RxLev_BEST_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.FP_RxQual_BEST_SUM=',GT_DB,'.table_tile_fp_gsm_dy_c_def.FP_RxQual_BEST_SUM+VALUES(FP_RxQual_BEST_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.FP_RxLev_BEST_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy_c_def.FP_RxLev_BEST_MED_AVG+VALUES(FP_RxLev_BEST_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.FP_RxQual_BEST_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy_c_def.FP_RxQual_BEST_MED_AVG+VALUES(FP_RxQual_BEST_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.FP_RxLev_ALL_SUM=',GT_DB,'.table_tile_fp_gsm_dy_c_def.FP_RxLev_ALL_SUM+VALUES(FP_RxLev_ALL_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.FP_RxQual_ALL_SUM=',GT_DB,'.table_tile_fp_gsm_dy_c_def.FP_RxQual_ALL_SUM+VALUES(FP_RxQual_ALL_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.FP_RxLev_ALL_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy_c_def.FP_RxLev_ALL_MED_AVG+VALUES(FP_RxLev_ALL_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.FP_RxQual_ALL_MED_AVG=',GT_DB,'.table_tile_fp_gsm_dy_c_def.FP_RxQual_ALL_MED_AVG+VALUES(FP_RxQual_ALL_MED_AVG),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.MMR_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c_def.MMR_CNT+VALUES(MMR_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.BEST_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c_def.BEST_CNT+VALUES(BEST_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.BEST_SERVING_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c_def.BEST_SERVING_CNT+VALUES(BEST_SERVING_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.SERVING_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c_def.SERVING_CNT+VALUES(SERVING_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.RXLEV_GAP_SUM=',GT_DB,'.table_tile_fp_gsm_dy_c_def.RXLEV_GAP_SUM+VALUES(RXLEV_GAP_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.RXLEV_GAP_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c_def.RXLEV_GAP_CNT+VALUES(RXLEV_GAP_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.SERVING_RXLEV_BETTER_GAP_SUM=',GT_DB,'.table_tile_fp_gsm_dy_c_def.SERVING_RXLEV_BETTER_GAP_SUM+VALUES(SERVING_RXLEV_BETTER_GAP_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.SERVING_RXLEV_BETTER_GAP_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c_def.SERVING_RXLEV_BETTER_GAP_CNT+VALUES(SERVING_RXLEV_BETTER_GAP_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.SERVING_RXLEV_WORSE_GAP_SUM=',GT_DB,'.table_tile_fp_gsm_dy_c_def.SERVING_RXLEV_WORSE_GAP_SUM+VALUES(SERVING_RXLEV_WORSE_GAP_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.SERVING_RXLEV_WORSE_GAP_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c_def.SERVING_RXLEV_WORSE_GAP_CNT+VALUES(SERVING_RXLEV_WORSE_GAP_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.INTERFERED_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c_def.INTERFERED_CNT+VALUES(INTERFERED_CNT)	,
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.MS_POWER_SUM=',GT_DB,'.table_tile_fp_gsm_dy_c_def.MS_POWER_SUM+VALUES(MS_POWER_SUM),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.MS_POWER_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c_def.MS_POWER_CNT+VALUES(MS_POWER_CNT),
				',GT_DB,'.table_tile_fp_gsm_dy_c_def.TOTAL_SERVING_CNT=',GT_DB,'.table_tile_fp_gsm_dy_c_def.TOTAL_SERVING_CNT+VALUES(TOTAL_SERVING_CNT)
		;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_FP_GSM',CONCAT('Done: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());
	
		
END$$
DELIMITER ;
