DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Sub_Generate_UE_TX_POWER`(IN GT_DB VARCHAR(100), IN KIND VARCHAR(20), IN VENDOR_SOURCE VARCHAR(20),IN GT_COVMO VARCHAR(100))
BEGIN
	DECLARE RNC_ID INT;
	DECLARE O_GT_DB VARCHAR(100) DEFAULT GT_DB;
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE PARTITION_ID INT DEFAULT SUBSTRING(RIGHT(GT_DB,18),10,2) ;
	DECLARE GT_DATE VARCHAR(18) DEFAULT RIGHT(GT_DB,18);
	DECLARE STARTDATE VARCHAR(10) DEFAULT CONCAT(LEFT(GT_DATE,4),'-',SUBSTRING(GT_DATE,5,2),'-',SUBSTRING(GT_DATE,7,2));
	DECLARE STARTHOUR VARCHAR(2) DEFAULT SUBSTRING(RIGHT(GT_DB,18),10,2);
	DECLARE ENDHOUR VARCHAR(2) DEFAULT IF(SUBSTRING(RIGHT(GT_DB,18),15,2)='00','24',SUBSTRING(RIGHT(GT_DB,18),15,2));
	DECLARE SH_EH VARCHAR(9) DEFAULT RIGHT(GT_DB,9);
	DECLARE RUN VARCHAR(20);
	SELECT gt_strtok(GT_DB,2,'_') INTO RNC_ID;
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_UE_TX_POWER','START', NOW());
	
	CALL SP_Sub_Set_Session_Param(GT_DB);
	SELECT REPLACE(GT_DB,SH_EH,'0000_0000') INTO GT_DB;
	
	IF VENDOR_SOURCE = 'GW' THEN
		IF KIND = 'DAILY' THEN
			SET RUN = '_tmp';
		ELSEIF KIND = 'RERUN' THEN
			SET RUN = '_rerun';
		END IF;
	ELSEIF VENDOR_SOURCE = 'AP' THEN
		SET RUN = '';
	END IF;
	SET @SqlCmd=CONCAT('SELECT att_value INTO @ZOOM_LEVEL FROM ',GT_DB,RUN,'.`sys_config` WHERE `group_name`=''system'' AND att_name = ''MapResolution'';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('ALTER TABLE ',GT_DB,RUN,'.table_tile_ue_tx_power TRUNCATE PARTITION h',PARTITION_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;			
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_UE_TX_POWER','INSERT INTO table_tile_ue_tx_power', NOW());	
	
	SET @SqlCmd=CONCAT('INSERT INTO ',GT_DB,RUN,'.table_tile_ue_tx_power
			    (DATA_DATE,DATA_HOUR,INDOOR,MOVING,TILE_ID,RNC_ID,FREQUENCY,UARFCN,CALL_TYPE,CALL_STATUS,CALL_CNT,UE_TX_POWER_AVG)	
			    SELECT
					 DATA_DATE
					, DATA_HOUR
					, INDOOR
					, MOVING
					, gt_covmo_proj_geohash_to_hex_geohash(POS_UE_TXP_LOC, ',@ZOOM_LEVEL,') AS TILE_ID
					, POS_UE_TXP_RNC AS RNC_ID
					, POS_UE_TXP_FREQUENCY 
					, POS_UE_TXP_UARFCN
					, CALL_TYPE 
					, CALL_STATUS
					, COUNT(POS_UE_TXP_RNC) AS CALL_CNT
					, AVG(POS_UE_TXP_QUALITY_VALUE) AS UE_TX_POWER_AVG
				FROM ',GT_DB,RUN,'.table_call
				WHERE POS_UE_RNC =',RNC_ID,'
				AND DATA_HOUR >= ',STARTHOUR,' AND DATA_HOUR < ',ENDHOUR,'
				GROUP BY  DATA_DATE 
					, DATA_HOUR 
					, gt_covmo_proj_geohash_to_hex_geohash(POS_UE_TXP_LOC, ',@ZOOM_LEVEL,')
					, POS_UE_TXP_RNC
					, POS_UE_TXP_FREQUENCY 
					, POS_UE_TXP_UARFCN
					, CALL_TYPE
					, INDOOR
					, MOVING
					, CALL_STATUS
				ORDER BY NULL;');
		PREPARE Stmt FROM @SqlCmd;
		EXECUTE Stmt;
		DEALLOCATE PREPARE Stmt;	
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_UE_TX_POWER',CONCAT('Done: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());
		
END$$
DELIMITER ;
