DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Sub_Update_CallTable`(IN GT_DB VARCHAR(100),IN GT_COVMO VARCHAR(100))
BEGIN
	DECLARE RNC_ID INT;
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE GT_DB_START_MIN VARCHAR(10) DEFAULT SUBSTRING(RIGHT(GT_DB,18),12,2);
	DECLARE WORKER_ID VARCHAR(10) DEFAULT CONNECTION_ID();
	DECLARE CURRENT_NT_DB VARCHAR(50) DEFAULT CONCAT('gt_nt_',gt_strtok(GT_DB,3,'_'));
	
 	SELECT SUBSTRING(SUBSTRING(GT_DB, 4,LENGTH(GT_DB)-4),1, LOCATE('_', SUBSTRING(GT_DB, 4,LENGTH(GT_DB)-4))-1) INTO RNC_ID;
 
 
	
 
	
	
	
	
	
	INSERT INTO gt_gw_main.sp_log VALUES(GT_DB,'SP_Sub_Update_CallTable','UPDATE DATA_DATE AND DATA_HOUR', NOW());
	
	SET @SqlCmd=CONCAT('UPDATE ',GT_DB,'.table_cell_usage SET 
			`DATA_DATE` = CONCAT(DATE(DATE_TIME),'' 00:00:00''),
			`DATA_HOUR` = HOUR(DATE_TIME);');
	PREPARE Stmt FROM @SqlCmd; 
	EXECUTE Stmt; 
	DEALLOCATE PREPARE Stmt;
	
	SET @SqlCmd=CONCAT('UPDATE ',GT_DB,'.table_nbap_cmr SET 
			`DATA_DATE` = CONCAT(DATE(DATE_TIME),'' 00:00:00''),
			`DATA_HOUR` = HOUR(DATE_TIME);');
	PREPARE Stmt FROM @SqlCmd; 
	EXECUTE Stmt; 
	DEALLOCATE PREPARE Stmt;
	
	
	
	INSERT INTO gt_gw_main.sp_log VALUES(GT_DB,'SP_Sub_Update_CallTable',CONCAT('Done2: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());
	
END$$
DELIMITER ;
