DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Sub_Generate_Active_Call`(IN GT_DB VARCHAR(100), IN KIND VARCHAR(20), IN VENDOR_SOURCE VARCHAR(20))
BEGIN
	DECLARE O_GT_DB VARCHAR(100) DEFAULT GT_DB;
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE GT_DATE VARCHAR(18) default right(GT_DB,18);
	DECLARE SH_EH VARCHAR(9) DEFAULT RIGHT(GT_DB,9);
	DECLARE STARTHOUR VARCHAR(2) DEFAULT SUBSTRING(RIGHT(GT_DB,18),10,2);
	DECLARE ENDHOUR VARCHAR(2) DEFAULT IF(SUBSTRING(RIGHT(GT_DB,18),15,2)='00','24',SUBSTRING(RIGHT(GT_DB,18),15,2));
	DECLARE PARTITION_ID INT DEFAULT SUBSTRING(RIGHT(GT_DB,18),10,2) ;
	DECLARE RUN VARCHAR(20);
	
       	SET SESSION max_heap_table_size = 1024*1024*1024*4; 
        SET SESSION tmp_table_size = 1024*1024*1024*4; 
        SET SESSION join_buffer_size = 1024*1024*1024; 
        SET SESSION sort_buffer_size = 1024*1024*1024; 
        SET SESSION read_buffer_size = 1024*1024*1024; 
 	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_Active_call','Inset data to `table_active_call`', NOW());	
	
	
	CALL SP_Sub_Set_Session_Param(GT_DB);
	SELECT REPLACE(GT_DB,SH_EH,'0000_0000') INTO GT_DB;
	
	IF VENDOR_SOURCE = 'GW' THEN
		IF KIND = 'DAILY' THEN
			SET RUN = '_tmp';
		ELSEIF KIND = 'RERUN' THEN
			SET RUN = '_rerun';
		END IF;
	ELSEIF VENDOR_SOURCE = 'AP' THEN
		SET RUN = '';
	END IF;
	
	SET @SqlCmd=CONCAT('ALTER TABLE ',GT_DB,RUN,'.table_active_call TRUNCATE PARTITION h',PARTITION_ID,';');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;	
	
	
	SET @SqlCmd=CONCAT('	INSERT INTO   ',GT_DB,RUN,'.`table_active_call`
				SELECT  CASE WHEN FLOOR(SECOND(DATE_TIME)/15)=1 THEN CONCAT (LEFT(DATE_TIME,16),'':15'')
					     WHEN FLOOR(SECOND(DATE_TIME)/15)=2 THEN CONCAT (LEFT(DATE_TIME,16),'':30'')
					     WHEN FLOOR(SECOND(DATE_TIME)/15)=3 THEN CONCAT (LEFT(DATE_TIME,16),'':45'')
					     WHEN FLOOR(SECOND(DATE_TIME)/15)=0 THEN CONCAT (LEFT(DATE_TIME,16),'':00'')
					END AS NEW_DATE_TIME			
				, `ACTIVE_SET_CELL_ID`,`ACTIVE_SET_RNC_ID`, SUM(`COUNT`) AS CNT
				,CONCAT(DATE(CASE WHEN FLOOR(SECOND(DATE_TIME)/15)=1 THEN CONCAT (LEFT(DATE_TIME,16),'':15'')
					     WHEN FLOOR(SECOND(DATE_TIME)/15)=2 THEN CONCAT (LEFT(DATE_TIME,16),'':30'')
					     WHEN FLOOR(SECOND(DATE_TIME)/15)=3 THEN CONCAT (LEFT(DATE_TIME,16),'':45'')
					     WHEN FLOOR(SECOND(DATE_TIME)/15)=0 THEN CONCAT (LEFT(DATE_TIME,16),'':00'')
					END),'' 00:00:00'') AS DATA_HOUR
				,HOUR(CASE WHEN FLOOR(SECOND(DATE_TIME)/15)=1 THEN CONCAT (LEFT(DATE_TIME,16),'':15'')
					     WHEN FLOOR(SECOND(DATE_TIME)/15)=2 THEN CONCAT (LEFT(DATE_TIME,16),'':30'')
					     WHEN FLOOR(SECOND(DATE_TIME)/15)=3 THEN CONCAT (LEFT(DATE_TIME,16),'':45'')
					     WHEN FLOOR(SECOND(DATE_TIME)/15)=0 THEN CONCAT (LEFT(DATE_TIME,16),'':00'')
					END) AS DATA_HOUR
				FROM ',GT_DB,RUN,'.table_cell_usage
				WHERE DATA_HOUR >= ',STARTHOUR,' AND DATA_HOUR < ',ENDHOUR,'
				GROUP BY   CASE WHEN FLOOR(SECOND(DATE_TIME)/15)=1 THEN CONCAT (LEFT(DATE_TIME,16),'':15'')
					     WHEN FLOOR(SECOND(DATE_TIME)/15)=2 THEN CONCAT (LEFT(DATE_TIME,16),'':30'')
					     WHEN FLOOR(SECOND(DATE_TIME)/15)=3 THEN CONCAT (LEFT(DATE_TIME,16),'':45'')
					     WHEN FLOOR(SECOND(DATE_TIME)/15)=0 THEN CONCAT (LEFT(DATE_TIME,16),'':00'')
					   END  
					   ,`ACTIVE_SET_CELL_ID`
					   ,`ACTIVE_SET_RNC_ID`;');
	PREPARE Stmt FROM @SqlCmd;
	EXECUTE Stmt;
	DEALLOCATE PREPARE Stmt;
	
	
	
					
	
	INSERT INTO gt_gw_main.sp_log VALUES(O_GT_DB,'SP_Sub_Generate_Active_call',CONCAT('Done: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());
	
	
        SET SESSION max_heap_table_size = 1024*1024*128; 
        SET SESSION tmp_table_size = 1024*1024*128; 
        SET SESSION join_buffer_size = 1024*1024*128; 
        SET SESSION sort_buffer_size = 1024*1024*128; 
        SET SESSION read_buffer_size = 1024*1024*128; 
	
END$$
DELIMITER ;
