DELIMITER $$
USE `gt_gw_main`$$
DROP PROCEDURE IF EXISTS `SP_CreateDB_LTE`$$
CREATE DEFINER=`covmo`@`%` PROCEDURE `SP_Update_DailyDB_Plus_LTE`(IN O_GT_DB VARCHAR(50), IN DAILY_DB VARCHAR(100),TECH_MASK SMALLINT(4))
BEGIN	
	DECLARE START_TIME DATETIME DEFAULT SYSDATE();
	DECLARE PMC_FLAG VARCHAR(10);
	
    	INSERT INTO gt_gw_main.SP_LOG VALUES(O_GT_DB,'SP_Update_DailyDB_Plus','Start', START_TIME);
	SELECT LOWER(`value`) INTO PMC_FLAG FROM gt_gw_main.integration_param WHERE gt_group = 'sp' AND gt_name = 'pmc' ;
	
	IF PMC_FLAG = 'true' THEN 
		CALL gt_gw_main.SP_Sub_Gen_CELL_PMC_RPT(DAILY_DB,O_GT_DB,'HOURLY');
	END IF;	
	INSERT INTO gt_gw_main.SP_LOG VALUES(O_GT_DB,'SP_Update_DailyDB_Plus',CONCAT('Done: ',TIMESTAMPDIFF(SECOND,START_TIME,SYSDATE()),' seconds.'), NOW());
END$$
DELIMITER ;
